export enum GamePhase {
  ARRIVAL = 'ARRIVAL',
  TRAITOR_SELECTION = 'TRAITOR_SELECTION',
  BREAKFAST = 'BREAKFAST',
  MISSION = 'MISSION',
  ROUND_TABLE = 'ROUND_TABLE',
  TRAITORS_MEETING = 'TRAITORS_MEETING',
  ENDGAME_ROUND_TABLE = 'ENDGAME_ROUND_TABLE',
  FINALE = 'FINALE',
}
