import { lines } from './lines';

/**
 * Personagens que vêm falar a sós com o jogador.
 * {user} = quem vem falar, {user1} = jogador, {user2}... = outras pessoas citadas.
 * {we} = "Eu e {user2}" / "Eu, {user2} e {user3}" (os membros da aliança de quem convida).
 */

export const APPROACH_INVITE_GROUP = lines(`
{user} chamou {user1} num canto: "{we} queremos você com a gente."
{user} cochichou com {user1}: "{we} temos uma vaga. É sua."
{user} puxou {user1} pelo braço: "{we} estamos fechados. Falta você."
{user} disse a {user1}: "{we} conversamos. Você entra?"
{user} sussurrou para {user1}: "{we} confiamos em você."
{user} chamou {user1} no jardim: "{we} queremos te proteger."
{user} disse a {user1}: "{we} votamos juntos. Quer votar com a gente?"
{user} sentou ao lado de {user1}: "{we} precisamos de alguém como você."
{user} disse a {user1}: "{we} somos um time. Vem?"
{user} piscou para {user1}: "{we} te escolhemos."
{user} disse a {user1}: "{we} falamos de você. Só coisa boa."
{user} chamou {user1}: "{we} temos um plano. E ele inclui você."
{user} disse a {user1}: "{we} queremos você na nossa aliança."
{user} cochichou: "{user1}, {we} fechamos uma aliança. Entra?"
{user} disse a {user1}: "{we} estamos crescendo. Você é o próximo nome."
{user} disse a {user1}: "{we} protegemos quem é nosso. Quer ser?"
{user} chamou {user1} na biblioteca: "{we} queremos conversar com você."
{user} disse a {user1}: "{we} votamos juntos desde ontem. Vem com a gente."
{user} disse a {user1}: "{we} precisamos de mais um voto de confiança."
{user} disse a {user1}: "{we} achamos que você é Fiel. Vamos juntos?"
{user} sorriu para {user1}: "{we} te queremos por perto."
{user} disse a {user1}: "{we} somos discretos. Ninguém vai saber."
{user} disse a {user1}: "{we} te defendemos na mesa se você entrar."
{user} disse a {user1}: "{we} temos lugar pra você."
{user} chamou {user1} pro corredor: "{we} fechamos. Quer ser o próximo?"
{user} disse a {user1}: "{we} votamos em quem você quiser, se você vier."
{user} disse a {user1}: "{we} estamos de olho nos Traidores. Vem ajudar."
{user} disse a {user1}: "{we} precisamos de alguém esperto(a)."
{user} disse a {user1}: "{we} gostamos do seu jogo."
{user} disse a {user1}: "{we} somos leais. Você também é?"
{user} disse a {user1}: "{we} queremos chegar na final com você."
{user} disse a {user1}: "{we} te escolhemos antes que outro escolha."
{user} disse a {user1}: "{we} temos uma proposta pra você."
{user} disse a {user1}: "{we} somos poucos, mas somos firmes."
{user} disse a {user1}: "{we} queremos você no grupo."
{user} disse a {user1}: "{we} te chamamos porque confiamos."
{user} disse a {user1}: "{we} precisamos de um voto a mais."
{user} disse a {user1}: "{we} te protegemos à noite. Metaforicamente."
{user} disse a {user1}: "{we} estamos juntos. E você?"
{user} disse a {user1}: "{we} queremos saber se você topa."
{user} disse a {user1}: "{we} discutimos e decidimos: você."
{user} disse a {user1}: "{we} tamo junto. Falta você."
{user} disse a {user1}: "{we} já te defendemos uma vez. Entra de vez."
{user} disse a {user1}: "{we} queremos um time forte. Você é forte."
{user} disse a {user1}: "{we} somos família aqui. Quer ser?"
{user} disse a {user1}: "{we} te vemos como um de nós."
{user} disse a {user1}: "{we} precisamos de você na mesa."
{user} disse a {user1}: "{we} combinamos o voto toda noite. Vem."
{user} disse a {user1}: "{we} estamos te esperando."
{user} disse a {user1}: "{we} te chamamos com carinho."
{user} disse a {user1}: "{we} somos o grupo mais leal daqui."
{user} disse a {user1}: "{we} queremos crescer, mas com gente boa."
{user} disse a {user1}: "{we} votamos contigo se você votar com a gente."
{user} disse a {user1}: "{we} te queremos antes da próxima mesa."
{user} disse a {user1}: "{we} temos um lugar guardado pra você."
{user} disse a {user1}: "{we} confiamos no seu faro."
{user} disse a {user1}: "{we} queremos você do nosso lado."
{user} disse a {user1}: "{we} não confiamos em quase ninguém. Em você, sim."
{user} disse a {user1}: "{we} estamos fechando o grupo. Última chance."
{user} disse a {user1}: "{we} precisamos de alguém calmo(a). Você."
{user} disse a {user1}: "{we} te protegemos. Palavra."
{user} disse a {user1}: "{we} queremos você no nosso canto."
{user} disse a {user1}: "{we} gostamos de você de verdade."
{user} disse a {user1}: "{we} somos time. Quer jogar?"
{user} disse a {user1}: "{we} te queremos, e rápido."
{user} disse a {user1}: "{we} somos seu porto seguro, se quiser."
{user} disse a {user1}: "{we} votamos como um só. Seja o próximo."
{user} disse a {user1}: "{we} te chamamos pra jogar junto."
{user} disse a {user1}: "{we} precisamos de mais olhos. Os seus."
{user} disse a {user1}: "{we} te convidamos oficialmente."
{user} disse a {user1}: "{we} confiamos em você mais que nos outros."
{user} disse a {user1}: "{we} somos poucos e bons. Vem?"
{user} disse a {user1}: "{we} te queremos com a gente até o fim."
{user} disse a {user1}: "{we} estamos de braços abertos."
{user} disse a {user1}: "{we} te escolhemos a dedo."
{user} disse a {user1}: "{we} precisamos de alguém como você na mesa."
{user} disse a {user1}: "{we} queremos você antes que te tirem."
{user} disse a {user1}: "{we} temos votos, e queremos o seu junto."
{user} disse a {user1}: "{we} protegemos os nossos. Seja nosso."
{user} disse a {user1}: "{we} queremos um(a) aliado(a) de confiança."
{user} disse a {user1}: "{we} te achamos o(a) mais leal daqui."
{user} disse a {user1}: "{we} te chamamos porque você merece."
{user} disse a {user1}: "{we} somos um grupo pequeno e forte."
{user} disse a {user1}: "{we} te queremos, sem pressão. Mas queremos."
{user} disse a {user1}: "{we} já conversamos sobre você. Todos concordaram."
{user} disse a {user1}: "{we} queremos você na nossa roda."
{user} disse a {user1}: "{we} estamos juntos há dias. Vem."
{user} disse a {user1}: "{we} te damos segurança."
{user} disse a {user1}: "{we} queremos você no nosso plano."
{user} disse a {user1}: "{we} votamos juntos e vamos longe. Vem?"
{user} disse a {user1}: "{we} te queremos antes da próxima noite."
{user} disse a {user1}: "{we} somos sua melhor chance aqui."
{user} disse a {user1}: "{we} te defendemos se você nos defender."
{user} disse a {user1}: "{we} te chamamos pra ser dos nossos."
{user} disse a {user1}: "{we} precisamos de alguém sincero(a)."
{user} disse a {user1}: "{we} te convidamos de coração."
{user} disse a {user1}: "{we} queremos você com a gente, sério."
{user} disse a {user1}: "{we} gostamos de como você joga."
{user} disse a {user1}: "{we} somos leais até o fim. Vem?"
{user} disse a {user1}: "{we} queremos seu voto e sua amizade."
{user} disse a {user1}: "{we} te protegemos na mesa, prometo."
{user} disse a {user1}: "{we} estamos te chamando agora."
{user} disse a {user1}: "{we} somos o grupo que ninguém vê."
{user} disse a {user1}: "{we} precisamos de você pra ganhar."
{user} disse a {user1}: "{we} te escolhemos entre todos."
{user} disse a {user1}: "{we} queremos você antes que seja tarde."
{user} disse a {user1}: "{we} votamos juntos e você votaria com a gente."
{user} disse a {user1}: "{we} somos um time unido."
{user} disse a {user1}: "{we} te queremos por perto na mesa."
{user} disse a {user1}: "{we} vamos até a final. Com você, se quiser."
{user} disse a {user1}: "{we} te damos nossa palavra."
{user} disse a {user1}: "{we} queremos você, e só você."
{user} disse a {user1}: "{we} te convidamos pra aliança."
{user} disse a {user1}: "{we} confiamos em você. Confia em nós?"
{user} disse a {user1}: "{we} somos fechados. Mas abrimos pra você."
{user} disse a {user1}: "{we} queremos você no grupo agora."
{user} disse a {user1}: "{we} somos seu lugar seguro."
{user} disse a {user1}: "{we} te chamamos porque você é Fiel."
{user} disse a {user1}: "{we} votamos por você se precisar."
{user} disse a {user1}: "{we} precisamos de alguém firme."
{user} disse a {user1}: "{we} te queremos com a gente, fechado?"
{user} disse a {user1}: "{we} somos poucos, mas leais."
{user} disse a {user1}: "{we} te convidamos antes de todos."
{user} disse a {user1}: "{we} queremos seu olhar no grupo."
{user} disse a {user1}: "{we} te protegemos, e você protege a gente."
{user} disse a {user1}: "{we} te chamamos pra jogar com a gente."
{user} disse a {user1}: "{we} somos o time certo pra você."
{user} disse a {user1}: "{we} queremos você com a gente na mesa final."
{user} disse a {user1}: "{we} já temos um plano. Falta você."
{user} disse a {user1}: "{we} confiamos em você, e é raro."
{user} disse a {user1}: "{we} te queremos antes da mesa."
{user} disse a {user1}: "{we} estamos contigo. Fica com a gente."
{user} disse a {user1}: "{we} somos sua aliança, se você quiser."
{user} disse a {user1}: "{we} te chamamos, porque você merece."
{user} disse a {user1}: "{we} precisamos de alguém leal. Você é."
{user} disse a {user1}: "{we} queremos você, e ninguém mais."
{user} disse a {user1}: "{we} somos a sua melhor aposta."
{user} disse a {user1}: "{we} te queremos com a gente, e é agora."
{user} disse a {user1}: "{we} votamos juntos. Você também vai."
{user} disse a {user1}: "{we} te convidamos com todo respeito."
{user} disse a {user1}: "{we} somos seu time a partir de hoje, se aceitar."
{user} disse a {user1}: "{we} te chamamos pro nosso lado."
{user} disse a {user1}: "{we} queremos você na nossa proteção."
{user} disse a {user1}: "{we} somos leais a quem é leal."
{user} disse a {user1}: "{we} precisamos de mais um. Você."
{user} disse a {user1}: "{we} te queremos, e confiamos em você."
{user} disse a {user1}: "{we} somos o grupo do bem."
{user} disse a {user1}: "{we} te chamamos pra somar."
{user} disse a {user1}: "{we} queremos você com a gente, de verdade."
{user} disse a {user1}: "{we} te protegemos até o fim."
{user} disse a {user1}: "{we} te escolhemos. Agora é com você."
{user} disse a {user1}: "{we} estamos juntos. Seja parte disso."
{user} disse a {user1}: "{we} te queremos, sem rodeios."
{user} disse a {user1}: "{we} te damos um lugar na nossa mesa."
{user} disse a {user1}: "{we} precisamos do seu voto e da sua cabeça."
{user} disse a {user1}: "{we} somos leais. Vem ser também."
{user} disse a {user1}: "{we} queremos você antes que os Traidores te peguem."
{user} disse a {user1}: "{we} te convidamos agora, e só agora."
{user} disse a {user1}: "{we} somos sua aliança ideal."
{user} disse a {user1}: "{we} te queremos, e te protegemos."
{user} disse a {user1}: "{we} votamos contigo sempre, se vier."
{user} disse a {user1}: "{we} te chamamos pra fazer parte."
{user} disse a {user1}: "{we} somos unidos. Falta você."
{user} disse a {user1}: "{we} te queremos por perto, sempre."
{user} disse a {user1}: "{we} confiamos em você de olhos fechados."
{user} disse a {user1}: "{we} te queremos, e não é pouco."
{user} disse a {user1}: "{we} somos seu grupo, se você quiser."
{user} disse a {user1}: "{we} precisamos de você com a gente."
{user} disse a {user1}: "{we} te chamamos porque você é das nossas."
{user} disse a {user1}: "{we} queremos você no nosso lado da mesa."
{user} disse a {user1}: "{we} somos leais, e você também."
{user} disse a {user1}: "{we} te convidamos pra jogar junto até o fim."
{user} disse a {user1}: "{we} te queremos com carinho e estratégia."
{user} disse a {user1}: "{we} somos um bom time. Com você, melhor."
{user} disse a {user1}: "{we} te chamamos pra nossa aliança agora."
{user} disse a {user1}: "{we} queremos você, sem pressão."
{user} disse a {user1}: "{we} te protegemos, pode confiar."
{user} disse a {user1}: "{we} somos a sua turma aqui dentro."
{user} disse a {user1}: "{we} precisamos do seu voto. E de você."
{user} disse a {user1}: "{we} te queremos na nossa história."
{user} disse a {user1}: "{we} te convidamos porque confiamos."
{user} disse a {user1}: "{we} somos fiéis entre nós. Vem?"
{user} disse a {user1}: "{we} te queremos, e é pra valer."
{user} disse a {user1}: "{we} te chamamos pra ficar com a gente."
{user} disse a {user1}: "{we} somos um grupo fechado, mas pra você a porta abre."
{user} disse a {user1}: "{we} queremos você com a gente até a última vela."
{user} disse a {user1}: "{we} te damos proteção e voto."
{user} disse a {user1}: "{we} somos sua chance de chegar longe."
{user} disse a {user1}: "{we} te queremos, fechado?"
{user} disse a {user1}: "{we} te chamamos, e esperamos um sim."
{user} disse a {user1}: "{we} te escolhemos porque você é bom(boa)."
{user} disse a {user1}: "{we} somos leais a você desde já."
{user} disse a {user1}: "{we} queremos você com a gente, confia."
{user} disse a {user1}: "{we} te chamamos pra aliança, com todo carinho."
{user} fez sinal para {user1}: "{we} precisamos de mais uma cabeça boa."
{user} disse a {user1}: "{we} te escolhemos. Topa?"
{user} chamou {user1} no jardim: "{we} queremos proteger você."
{user} disse a {user1}: "{we} conversamos. Seu nome saiu na hora."
{user} disse a {user1}: "{we} estamos montando um time. Entra?"
{user} disse a {user1}: "{we} votamos juntos. Vem com a gente."
{user} disse a {user1}: "{we} confiamos em você. Quer ser parte?"
{user} disse a {user1}, baixinho: "{we} queremos chegar na final com você."
{user} disse a {user1}: "{we} precisamos de alguém como você."
`);

export const APPROACH_INVITE_PAIR = lines(`
{user} puxou {user1} para um canto: "Eu e você, até o fim. Fechado?"
{user} chamou {user1} no jardim: "Preciso de alguém de confiança. Aliança?"
{user} sentou do lado de {user1}: "Gostei de você. Vamos juntos nessa?"
{user} brindou com {user1}: "Eu e você, parceria desde o primeiro dia?"
{user} cochichou com {user1}: "Quer ser minha dupla aqui?"
{user} disse a {user1}: "Eu e você somos parecidos. Vamos juntos?"
{user} chamou {user1} pro corredor: "Fecha comigo?"
{user} disse a {user1}: "Eu confio em você. Você confia em mim?"
{user} estendeu a mão para {user1}: "Parceria?"
{user} disse a {user1}: "Vamos nos cuidar? Eu e você."
{user} disse a {user1}: "Eu quero você do meu lado."
{user} disse a {user1}: "Preciso de um(a) parceiro(a). Topa?"
{user} disse a {user1}: "Eu te protejo, você me protege. Combinado?"
{user} disse a {user1}: "Você e eu, dupla secreta?"
{user} sussurrou para {user1}: "Aliança? Só nós dois."
{user} disse a {user1}: "Eu não confio em quase ninguém. Em você, sim."
{user} disse a {user1}: "Vamos jogar juntos, que tal?"
{user} disse a {user1}: "Quer ser meu(minha) aliado(a)?"
{user} disse a {user1}: "Eu te escolhi. Me escolhe também?"
{user} disse a {user1}: "Juntos a gente vai longe."
{user} disse a {user1}: "Eu e você contra o resto?"
{user} disse a {user1}: "Me dá sua mão e seu voto?"
{user} disse a {user1}: "Uma aliança só nossa. Topa?"
{user} disse a {user1}: "Eu sinto que posso confiar em você."
{user} disse a {user1}: "Vamos combinar de nunca votar um no outro?"
{user} disse a {user1}: "Eu quero dividir essa jornada com você."
{user} disse a {user1}: "Fecha comigo e ninguém te toca."
{user} disse a {user1}: "Seremos a dupla que ninguém espera."
{user} disse a {user1}: "Eu cubro suas costas. Topa?"
{user} disse a {user1}: "A gente combina. Vamos juntos?"
{user} disse a {user1}: "Eu quero você na minha retaguarda."
{user} disse a {user1}: "Você tem cara de parceiro(a) leal."
{user} disse a {user1}: "Eu preciso de alguém firme. Você?"
{user} disse a {user1}: "Proposta: você e eu, até a última vela."
{user} disse a {user1}: "Vamos fazer um pacto?"
{user} disse a {user1}: "Eu confio no seu jogo. Vamos unir?"
{user} disse a {user1}: "Quer fechar comigo antes que alguém feche?"
{user} disse a {user1}: "Eu te chamo pra ser minha dupla."
{user} disse a {user1}: "Juntos a gente se protege."
{user} disse a {user1}: "Eu quero jogar com você, não contra."
{user} disse a {user1}: "Você me passa segurança. Aliança?"
{user} disse a {user1}: "Eu e você: a dupla mais forte."
{user} disse a {user1}: "Vamos nos unir? Eu sinto que vale."
{user} disse a {user1}: "Eu não quero passar por isso sozinho(a)."
{user} disse a {user1}: "Aliança? Prometo ser leal."
{user} disse a {user1}: "Eu tô montando meu time. Você é o(a) primeiro(a)."
{user} disse a {user1}: "Vamos juntos até alguém nos separar?"
{user} disse a {user1}: "Eu te dou meu voto. Me dá o seu?"
{user} disse a {user1}: "Quer ser meu escudo? Eu sou o seu."
{user} disse a {user1}: "Eu confio em você, e isso é raro."
{user} disse a {user1}: "Proposta simples: lealdade."
{user} disse a {user1}: "Eu quero ser seu(sua) aliado(a)."
{user} disse a {user1}: "Juntos a gente vence o medo."
{user} disse a {user1}: "Fecha comigo, que eu fecho contigo."
{user} disse a {user1}: "Eu vejo em você um(a) aliado(a)."
{user} disse a {user1}: "Vamos fazer história juntos?"
{user} disse a {user1}: "Eu te ofereço minha lealdade."
{user} disse a {user1}: "Uma dupla discreta. Que tal?"
{user} disse a {user1}: "Eu quero você comigo até o fim."
{user} disse a {user1}: "Aliança? Eu levo o chá."
{user} disse a {user1}: "Vamos cuidar um do outro?"
{user} disse a {user1}: "Eu quero você na minha lista de proteção."
{user} disse a {user1}: "Seremos inseparáveis, se você quiser."
{user} disse a {user1}: "Você e eu, pacto fechado?"
{user} disse a {user1}: "Eu te chamo pra aliança antes que seja tarde."
{user} disse a {user1}: "Eu preciso de você e você de mim."
{user} disse a {user1}: "Vamos fechar essa parceria?"
{user} disse a {user1}: "Eu te protejo com unhas e dentes. Aceita?"
{user} disse a {user1}: "Juntos a gente enxerga melhor."
{user} disse a {user1}: "Eu quero seu sim."
{user} disse a {user1}: "Uma parceria de verdade. Topa?"
{user} disse a {user1}: "Eu confio no seu olhar. Aliança?"
{user} disse a {user1}: "Vamos juntos? Sem pensar muito."
{user} disse a {user1}: "Eu te ofereço minha amizade e meu voto."
{user} disse a {user1}: "Você é a pessoa que eu queria do lado."
{user} disse a {user1}: "Fecha comigo? Eu não te largo."
{user} disse a {user1}: "Eu e você, o time que ninguém separa."
{user} disse a {user1}: "Vamos nos unir antes que nos dividam."
{user} disse a {user1}: "Eu te chamo com o coração aberto."
{user} disse a {user1}: "Quero você comigo quando a coisa apertar."
{user} disse a {user1}: "Aliança? Sim ou claro?"
{user} disse a {user1}: "Eu confio em você. Vamos juntos."
{user} disse a {user1}: "Seremos a dupla do castelo."
{user} disse a {user1}: "Eu te dou minha palavra. Você me dá a sua?"
{user} disse a {user1}: "Vamos jogar como um só?"
{user} disse a {user1}: "Eu te chamo pra ser minha pessoa aqui."
{user} disse a {user1}: "Juntos, a gente aguenta tudo."
{user} disse a {user1}: "Eu quero você na minha vida de castelo."
{user} disse a {user1}: "Uma aliança nossa? Topa?"
{user} disse a {user1}: "Eu te escolhi. Agora é com você."
{user} disse a {user1}: "Quer fechar? Tô falando sério."
{user} disse a {user1}: "Eu sinto que a gente combina."
{user} disse a {user1}: "Vamos jogar juntos e rir depois?"
{user} disse a {user1}: "Eu te ofereço um porto seguro."
{user} disse a {user1}: "Proposta: você e eu, sem ninguém saber."
{user} disse a {user1}: "Eu quero você do meu lado da mesa."
{user} disse a {user1}: "Juntos somos mais fortes. Topa?"
{user} disse a {user1}: "Eu confio em você de olhos fechados. Aliança?"
{user} disse a {user1}: "Vamos nos proteger, eu e você?"
{user} disse a {user1}: "Eu quero dividir tudo com você aqui."
{user} disse a {user1}: "Você é minha primeira escolha."
{user} disse a {user1}: "Aliança? Eu garanto minha lealdade."
{user} disse a {user1}: "Eu e você até a final, fechado?"
{user} disse a {user1}: "Vamos ser o time que ninguém vê?"
{user} disse a {user1}: "Eu te chamo pra jogar junto."
{user} disse a {user1}: "Quero você comigo nessa loucura."
{user} disse a {user1}: "Eu te dou meu voto, sempre. Topa?"
{user} disse a {user1}: "Juntos, a gente sobrevive."
{user} disse a {user1}: "Eu te ofereço minha confiança."
{user} disse a {user1}: "Quer ser meu(minha) aliado(a) de fé?"
{user} disse a {user1}: "Eu quero você comigo, simples assim."
{user} disse a {user1}: "Vamos fechar? Eu sinto que vale a pena."
{user} disse a {user1}: "Eu e você, pacto de sobrevivência."
{user} disse a {user1}: "Eu confio no seu jogo, e no seu coração."
{user} disse a {user1}: "Juntos até o fim, que tal?"
{user} disse a {user1}: "Eu te chamo pra aliança agora."
{user} disse a {user1}: "Quero você comigo. Topa?"
{user} disse a {user1}: "Eu sou leal. Quer testar?"
{user} disse a {user1}: "Vamos juntos, eu cuido de você."
{user} disse a {user1}: "Eu e você somos o melhor time."
{user} disse a {user1}: "Aliança? Eu tô pronto(a)."
{user} disse a {user1}: "Eu te escolho. Me escolhe?"
{user} disse a {user1}: "Vamos nos blindar um ao outro?"
{user} disse a {user1}: "Eu quero você no meu time."
{user} disse a {user1}: "Juntos a gente atravessa esse castelo."
{user} disse a {user1}: "Eu confio. Aliança?"
{user} disse a {user1}: "Quer ser minha dupla fixa?"
{user} disse a {user1}: "Eu te dou minha lealdade de presente."
{user} disse a {user1}: "Vamos nos unir, eu e você?"
{user} disse a {user1}: "Eu quero seguir junto com você."
{user} disse a {user1}: "Fecha comigo, que a gente vence junto."
{user} disse a {user1}: "Eu e você: o pacto mais forte daqui."
{user} disse a {user1}: "Quer fazer parte do meu plano?"
{user} disse a {user1}: "Eu te chamo pra ser minha parceria."
{user} disse a {user1}: "Juntos a gente é imbatível."
{user} disse a {user1}: "Eu confio em você como em ninguém."
{user} disse a {user1}: "Aliança? Eu não te decepciono."
{user} disse a {user1}: "Eu quero você comigo nas mesas."
{user} disse a {user1}: "Vamos juntos? Eu garanto."
{user} disse a {user1}: "Eu te ofereço amizade de verdade."
{user} disse a {user1}: "Você e eu, até a última porta."
{user} disse a {user1}: "Eu te escolhi pra ser meu(minha) aliado(a)."
{user} disse a {user1}: "Quer se unir comigo?"
{user} disse a {user1}: "Eu confio no seu instinto. Vamos juntos?"
{user} disse a {user1}: "Juntos, a gente se salva."
{user} disse a {user1}: "Eu te quero na minha aliança."
{user} disse a {user1}: "Aliança? Palavra de honra."
{user} disse a {user1}: "Eu e você contra o caos."
{user} disse a {user1}: "Vamos fazer um pacto antes da mesa?"
{user} disse a {user1}: "Eu te chamo pro meu lado."
{user} disse a {user1}: "Quero você comigo. Sério."
{user} disse a {user1}: "Eu te protejo. Aceita?"
{user} disse a {user1}: "Juntos a gente vai além."
{user} disse a {user1}: "Eu confio em você. Fecha?"
{user} disse a {user1}: "Quer jogar comigo até o fim?"
{user} disse a {user1}: "Eu te dou meu sim, se você me der o seu."
{user} disse a {user1}: "Vamos nos cuidar, combinado?"
{user} disse a {user1}: "Eu e você, aliança secreta."
{user} disse a {user1}: "Eu quero você na minha retaguarda. Topa?"
{user} disse a {user1}: "Juntos a gente enfrenta a mesa."
{user} disse a {user1}: "Eu te chamo porque confio."
{user} disse a {user1}: "Aliança? Não vou te largar."
{user} disse a {user1}: "Eu e você, pra valer?"
{user} disse a {user1}: "Vamos juntos, eu sinto que é certo."
{user} disse a {user1}: "Eu te quero comigo. Fecha?"
{user} disse a {user1}: "Quer ser meu escudo e eu o seu?"
{user} disse a {user1}: "Eu confio em você. Pacto?"
{user} disse a {user1}: "Juntos a gente é muito mais."
{user} disse a {user1}: "Eu te chamo pra ficar comigo."
{user} disse a {user1}: "Aliança? Eu tô contigo."
{user} disse a {user1}: "Eu e você, fechado até a final?"
{user} disse a {user1}: "Vamos nos proteger nessa?"
{user} disse a {user1}: "Eu quero você do meu lado, sempre."
{user} disse a {user1}: "Juntos a gente vence."
{user} disse a {user1}: "Eu te chamo com toda confiança."
{user} disse a {user1}: "Aliança? Só depende de você."
{user} disse a {user1}: "Eu e você, amigos e aliados."
{user} disse a {user1}: "Vamos fechar hoje?"
{user} disse a {user1}: "Eu te escolho, sem pensar."
{user} disse a {user1}: "Quer fazer dupla comigo?"
{user} disse a {user1}: "Eu confio em você. Vem comigo."
{user} disse a {user1}: "Juntos, até o fim."
{user} disse a {user1}: "Eu te chamo pra aliança, com carinho."
{user} disse a {user1}: "Aliança? Prometo que vale a pena."
{user} disse a {user1}: "Eu e você, parceria firme."
{user} disse a {user1}: "Vamos juntos, eu e você?"
{user} disse a {user1}: "Eu quero você como meu(minha) aliado(a)."
{user} disse a {user1}: "Juntos a gente é mais forte, você sabe."
{user} disse a {user1}: "Eu te chamo pra parceria."
{user} disse a {user1}: "Aliança? Confia em mim."
{user} disse a {user1}: "Eu cuido de você, você cuida de mim. Topa?"
{user} disse a {user1}: "Sinto que posso confiar em você. Dupla?"
{user} disse a {user1}: "Vamos fazer um pacto? Só nós dois."
{user} disse a {user1}: "Eu quero chegar no final com você."
{user} estendeu a mão a {user1}: "Parceria?"
{user} disse a {user1}: "Juntos a gente enxerga mais. Aceita?"
{user} disse a {user1}: "Não quero jogar sozinho(a). Vem comigo?"
{user} disse a {user1}: "Te escolhi. Agora é você que decide."
{user} disse a {user1}: "Dupla que confia não cai fácil. Bora?"
{user} disse a {user1}: "Eu nunca escreveria seu nome. Promete o mesmo?"
{user} disse a {user1}: "Você tem cara de aliado(a) leal. Fecha?"
{user} disse a {user1}: "Eu e você, protegendo um ao outro. Que tal?"
{user} disse a {user1}: "Proposta: a gente se fecha. Sem segredo."
{user} disse a {user1}: "Preciso de um ombro aqui. Pode ser o seu?"
`);

export const APPROACH_IMPRESSION_GOOD = lines(`
{user} veio se apresentar a {user1}: "Adorei sua energia!"
{user} elogiou {user1}: "Você chegou chegando, hein?"
{user} sorriu para {user1}: "Finalmente alguém simpático aqui."
{user} disse a {user1}: "Você tem um sorriso bonito."
{user} disse a {user1}: "Gostei de você de cara."
{user} brindou com {user1}: "Ao nosso primeiro dia!"
{user} disse a {user1}: "Você parece gente boa demais."
{user} disse a {user1}: "Que figurino, hein?"
{user} disse a {user1}: "Você me lembra meu melhor amigo(a)."
{user} riu com {user1}: "Você é engraçado(a)!"
{user} disse a {user1}: "Senta aqui do meu lado."
{user} disse a {user1}: "Você tem um jeito leve."
{user} disse a {user1}: "Prazer! Tô gostando de você."
{user} disse a {user1}: "Que bom te conhecer."
{user} disse a {user1}: "Você passa uma paz."
{user} ofereceu uma taça a {user1}: "Pra você, com carinho."
{user} disse a {user1}: "Você é o(a) mais simpático(a) que conheci hoje."
{user} disse a {user1}: "Eu sinto que a gente vai se dar bem."
{user} disse a {user1}: "Você tem cara de quem conta boas histórias."
{user} disse a {user1}: "Adorei seu estilo."
{user} disse a {user1}: "Você me deixou à vontade."
{user} disse a {user1}: "Você é um amor, sabia?"
{user} disse a {user1}: "Nossa, que energia boa."
{user} disse a {user1}: "Você é luz."
{user} disse a {user1}: "Eu gostei do seu papo."
{user} disse a {user1}: "Você é daquelas pessoas raras."
{user} disse a {user1}: "Seu riso é contagiante."
{user} disse a {user1}: "Você é muito charmoso(a)."
{user} disse a {user1}: "Queria ter te conhecido antes."
{user} disse a {user1}: "Você chegou e o salão ficou mais leve."
{user} disse a {user1}: "Você tem um brilho diferente."
{user} disse a {user1}: "Você parece tão tranquilo(a)."
{user} disse a {user1}: "Gostei da sua história."
{user} disse a {user1}: "Você é muito educado(a)."
{user} disse a {user1}: "Vou querer você perto."
{user} disse a {user1}: "Você é incrível, e eu mal te conheço."
{user} disse a {user1}: "Você é a melhor surpresa da noite."
{user} disse a {user1}: "Seu jeito é muito gostoso de conviver."
{user} disse a {user1}: "Você tem um coração bom, dá pra ver."
{user} disse a {user1}: "Você é gente como a gente."
{user} disse a {user1}: "Adorei conversar com você."
{user} disse a {user1}: "Você é muito divertido(a)."
{user} disse a {user1}: "Você é a pessoa mais gentil daqui."
{user} disse a {user1}: "Você me fez rir no primeiro minuto."
{user} disse a {user1}: "Eu sinto que posso confiar em você."
{user} disse a {user1}: "Você tem uma presença incrível."
{user} disse a {user1}: "Seu sotaque é lindo."
{user} disse a {user1}: "Você é tão autêntico(a)."
{user} disse a {user1}: "Queria ser seu(sua) amigo(a) aqui."
{user} disse a {user1}: "Você parece um personagem de filme."
{user} disse a {user1}: "Você é sensacional."
{user} disse a {user1}: "Eu adorei você, de verdade."
{user} disse a {user1}: "Você é muito elegante."
{user} disse a {user1}: "Que bom ter alguém como você aqui."
{user} disse a {user1}: "Você me passou confiança logo de cara."
{user} disse a {user1}: "Você é demais."
{user} disse a {user1}: "Vamos ser amigos?"
{user} disse a {user1}: "Você tem um astral maravilhoso."
{user} disse a {user1}: "Eu gostei de você antes de você falar."
{user} disse a {user1}: "Você é muito fofo(a)."
{user} disse a {user1}: "Você é aquele tipo de pessoa que ilumina."
{user} disse a {user1}: "Seu abraço é o melhor."
{user} disse a {user1}: "Você é de uma simpatia rara."
{user} disse a {user1}: "Você tem tudo pra ser meu(minha) favorito(a)."
{user} disse a {user1}: "Eu adoro gente como você."
{user} disse a {user1}: "Você é muito especial."
{user} disse a {user1}: "Você me conquistou."
{user} disse a {user1}: "Que pessoa boa você é."
{user} disse a {user1}: "Você tem uma energia que acalma."
{user} disse a {user1}: "Adorei sua risada."
{user} disse a {user1}: "Você é muito querido(a)."
{user} disse a {user1}: "Você é um presente pra esse lugar."
{user} disse a {user1}: "Eu confio no meu instinto. E ele gostou de você."
{user} disse a {user1}: "Você parece que já é de casa."
{user} disse a {user1}: "Você é muito carismático(a)."
{user} disse a {user1}: "Você é a minha pessoa favorita até agora."
{user} disse a {user1}: "Você é ótimo(a) de conversa."
{user} disse a {user1}: "Que alegria te conhecer."
{user} disse a {user1}: "Você tem um jeito muito bonito."
{user} disse a {user1}: "Eu gostei muito do seu jeito."
{user} disse a {user1}: "Você me deixou encantado(a)."
{user} disse a {user1}: "Você é uma pessoa de luz."
{user} disse a {user1}: "Você tem cara de melhor amigo(a)."
{user} disse a {user1}: "Seu jeito me acalma."
{user} disse a {user1}: "Você é uma figura, adorei."
{user} disse a {user1}: "Você tem um coração enorme."
{user} disse a {user1}: "Eu quero ser seu(sua) vizinho(a) de quarto."
{user} disse a {user1}: "Você é a alegria desse salão."
{user} disse a {user1}: "Você é muito bem-vindo(a)."
{user} disse a {user1}: "Você é o tipo de gente que eu admiro."
{user} disse a {user1}: "Eu te achei incrível."
{user} disse a {user1}: "Você tem uma alma leve."
{user} disse a {user1}: "Você é muito gente fina."
{user} disse a {user1}: "Eu fiquei feliz em te conhecer."
{user} disse a {user1}: "Você é tão simpático(a) que dá gosto."
{user} disse a {user1}: "Seu jeito é contagiante."
{user} disse a {user1}: "Você me fez sentir em casa."
{user} disse a {user1}: "Você é muito bacana."
{user} disse a {user1}: "Você é a pessoa mais legal daqui."
{user} disse a {user1}: "Eu gostei demais de você."
{user} disse a {user1}: "Você é diferente, e isso é bom."
{user} disse a {user1}: "Você tem uma elegância natural."
{user} disse a {user1}: "Eu te achei um amor."
{user} disse a {user1}: "Você é aquele raio de sol no meio da neblina."
{user} disse a {user1}: "Eu já te adoro."
{user} disse a {user1}: "Você é a companhia perfeita."
{user} disse a {user1}: "Seu olhar é muito sincero."
{user} disse a {user1}: "Eu tô feliz que você tá aqui."
{user} disse a {user1}: "Você é muito divertido(a) de verdade."
{user} disse a {user1}: "Você tem uma vibe incrível."
{user} disse a {user1}: "Eu quero conversar mais com você."
{user} disse a {user1}: "Você é o(a) mais bonito(a) do salão."
{user} disse a {user1}: "Eu adorei sua chegada."
{user} disse a {user1}: "Você tem um jeito que conquista."
{user} disse a {user1}: "Você é uma graça."
{user} disse a {user1}: "Eu me senti bem perto de você."
{user} disse a {user1}: "Você é muito especial, sério."
{user} disse a {user1}: "Você é a pessoa que eu queria encontrar aqui."
{user} disse a {user1}: "Seu sorriso me ganhou."
{user} disse a {user1}: "Você é gentil com todo mundo. Adoro."
{user} disse a {user1}: "Você tem um jeito doce."
{user} disse a {user1}: "Eu gostei de você de primeira."
{user} disse a {user1}: "Você é demais, de verdade."
{user} disse a {user1}: "Você tem uma alegria linda."
{user} disse a {user1}: "Eu sinto que você é boa gente."
{user} disse a {user1}: "Você me deixou de bom humor."
{user} disse a {user1}: "Você é muito bem-humorado(a)."
{user} disse a {user1}: "Eu adorei sua companhia."
{user} disse a {user1}: "Você é aquele tipo de pessoa inesquecível."
{user} disse a {user1}: "Seu jeito me encantou."
{user} disse a {user1}: "Você é uma pessoa maravilhosa."
{user} disse a {user1}: "Eu fiquei fã de você."
{user} disse a {user1}: "Você tem uma energia boa demais."
{user} disse a {user1}: "Eu quero você por perto."
{user} disse a {user1}: "Você é muito simpático(a), de verdade."
{user} disse a {user1}: "Você é o(a) melhor que conheci hoje."
{user} disse a {user1}: "Você tem cara de gente do bem."
{user} disse a {user1}: "Seu papo é muito bom."
{user} disse a {user1}: "Eu sinto que vamos ser grandes amigos."
{user} disse a {user1}: "Você é muito gentil."
{user} disse a {user1}: "Você me fez sorrir."
{user} disse a {user1}: "Eu adoro seu estilo."
{user} disse a {user1}: "Você é muito querido(a), sabia?"
{user} disse a {user1}: "Você tem um carisma impressionante."
{user} disse a {user1}: "Eu gostei muito de você, sério."
{user} disse a {user1}: "Você é uma pessoa linda."
{user} disse a {user1}: "Seu jeito é único."
{user} disse a {user1}: "Eu quero ser seu(sua) amigo(a)."
{user} disse a {user1}: "Você é incrível."
{user} disse a {user1}: "Você tem uma luz própria."
{user} disse a {user1}: "Eu me sinto bem com você."
{user} disse a {user1}: "Você é muito legal."
{user} disse a {user1}: "Você tem um coração bonito."
{user} disse a {user1}: "Eu te achei muito simpático(a)."
{user} disse a {user1}: "Você é a pessoa mais agradável daqui."
{user} disse a {user1}: "Seu sorriso é lindo."
{user} disse a {user1}: "Eu gostei do seu jeito de falar."
{user} disse a {user1}: "Você é muito sincero(a)."
{user} disse a {user1}: "Você tem uma alegria contagiante."
{user} disse a {user1}: "Eu adorei te conhecer."
{user} disse a {user1}: "Você é muito charmoso(a), hein?"
{user} disse a {user1}: "Você parece muito do bem."
{user} disse a {user1}: "Eu sinto que você é especial."
{user} disse a {user1}: "Você é o(a) mais divertido(a) daqui."
{user} disse a {user1}: "Você tem um jeito acolhedor."
{user} disse a {user1}: "Eu quero ficar perto de você."
{user} disse a {user1}: "Você é muito elegante, adorei."
{user} disse a {user1}: "Você é uma companhia incrível."
{user} disse a {user1}: "Eu fiquei encantado(a) com você."
{user} disse a {user1}: "Você é uma pessoa muito boa."
{user} disse a {user1}: "Seu riso é o melhor som da noite."
{user} disse a {user1}: "Eu gostei demais do seu jeito."
{user} disse a {user1}: "Você é a pessoa mais leve daqui."
{user} disse a {user1}: "Você me deixou feliz."
{user} disse a {user1}: "Eu adorei sua simpatia."
{user} disse a {user1}: "Você é muito bacana, de verdade."
{user} disse a {user1}: "Você tem cara de quem abraça bem."
{user} disse a {user1}: "Eu sinto que você é sincero(a)."
{user} disse a {user1}: "Você é o máximo."
{user} disse a {user1}: "Você tem uma energia ótima."
{user} disse a {user1}: "Eu quero dividir uma mesa com você."
{user} disse a {user1}: "Você é muito especial pra mim já."
{user} disse a {user1}: "Seu jeito é muito bonito."
{user} disse a {user1}: "Eu gostei da sua vibe."
{user} disse a {user1}: "Você é um amor de pessoa."
{user} disse a {user1}: "Você me conquistou de primeira."
{user} abraçou {user1} como velhos amigos.
{user} disse a {user1}: "Tô sentindo que a gente vai se dar bem."
{user} riu da piada de {user1}: "Você é hilário(a)!"
{user} disse a {user1}: "Seu sorriso deixou o salão mais leve."
{user} elogiou o figurino de {user1}: "Arrasou!"
{user} disse a {user1}: "Achei minha dupla de conversa."
{user} disse a {user1}: "De todo mundo aqui, gostei de você primeiro."
{user} disse a {user1}: "Você tem cara de gente boa."
{user} ofereceu uma taça a {user1}: "Um brinde a nós."
{user} disse a {user1}: "Que energia boa a sua!"
{user} disse a {user1}: "Já vi que você é das minhas."
{user} disse a {user1}: "Você parece alguém que eu conheço há anos."
{user} disse a {user1}: "Adoro gente com seu estilo."
{user} disse a {user1}: "Senta aqui comigo. Quero te conhecer."
{user} disse a {user1}: "Finalmente alguém divertido(a) nesse castelo."
{user} disse a {user1}: "Me conta de você. Fiquei curioso(a)."
{user} disse a {user1}: "Gostei da sua chegada. Com classe."
{user} riu com {user1}: "Você é o(a) primeiro(a) que me fez rir aqui."
{user} disse a {user1}: "Você tem um ar de confiança. Gosto disso."
`);

export const APPROACH_IMPRESSION_BAD = lines(`
{user} olhou {user1} de cima a baixo e nem se apresentou.
{user} cochichou sobre {user1} e riu quando {user1} olhou.
{user} ignorou {user1} e foi falar com outra pessoa.
{user} disse a {user1}, seco(a): "Ah. Oi."
{user} torceu o nariz quando {user1} sentou perto.
{user} disse a {user1}: "Você fala alto, né?"
{user} revirou os olhos para {user1}.
{user} disse a {user1}: "Que roupa é essa?"
{user} deu as costas quando {user1} chegou.
{user} disse a {user1}: "Você é sempre assim?"
{user} fingiu não ver {user1}.
{user} disse a {user1}: "Hm. Prazer. Acho."
{user} riu da história de {user1}. Não do jeito bom.
{user} disse a {user1}: "Você se acha, né?"
{user} saiu da roda quando {user1} entrou.
{user} disse a {user1}: "Não fui com a sua cara."
{user} fez careta para {user1}.
{user} disse a {user1}: "Pode sentar em outro lugar?"
{user} bocejou enquanto {user1} falava.
{user} disse a {user1}: "Você é meio estranho(a)."
{user} olhou torto para {user1}.
{user} disse a {user1}: "Ninguém perguntou."
{user} cortou {user1} no meio da frase.
{user} disse a {user1}: "Você tá forçando."
{user} cochichou sobre {user1} com alguém.
{user} disse a {user1}: "Seu perfume é forte demais."
{user} fez cara de tédio para {user1}.
{user} disse a {user1}: "Hm. Legal. Tchau."
{user} ignorou o brinde de {user1}.
{user} disse a {user1}: "Você é aquele tipo que quer aparecer."
{user} mudou de lugar quando {user1} sentou.
{user} disse a {user1}: "Não sei se vou com você."
{user} olhou para {user1} com desprezo.
{user} disse a {user1}: "Você não para de falar?"
{user} imitou {user1} pelas costas.
{user} disse a {user1}: "Você me cansa."
{user} riu de {user1} com outra pessoa.
{user} disse a {user1}: "Você é muito metido(a)."
{user} fingiu que o celular... que não tinha celular. Só pra não falar com {user1}.
{user} disse a {user1}: "Menos, por favor."
{user} desviou o olhar de {user1}.
{user} disse a {user1}: "Você se esforça demais."
{user} não apertou a mão de {user1}.
{user} disse a {user1}: "Você é chato(a), sabia?"
{user} deu um sorriso falso para {user1}.
{user} disse a {user1}: "Não gostei de você. Nada pessoal."
{user} saiu andando enquanto {user1} falava.
{user} disse a {user1}: "Hm, você de novo."
{user} ficou de braços cruzados perto de {user1}.
{user} disse a {user1}: "Você não me engana com esse sorriso."
{user} comentou alto que {user1} fala demais.
{user} disse a {user1}: "Você é muito exibido(a)."
{user} fez um comentário azedo sobre {user1}.
{user} disse a {user1}: "Eu prefiro distância."
{user} riu da roupa de {user1}.
{user} disse a {user1}: "Você é intenso(a) demais."
{user} evitou {user1} a noite toda.
{user} disse a {user1}: "Você tem cara de problema."
{user} deu um aceno frio para {user1}.
{user} disse a {user1}: "Não força amizade."
{user} bufou quando {user1} contou uma piada.
{user} disse a {user1}: "Isso foi sem graça."
{user} olhou {user1} como quem mede o inimigo.
{user} disse a {user1}: "Você é desses que conta vantagem."
{user} virou a cara para {user1}.
{user} disse a {user1}: "Você não é meu tipo de gente."
{user} fez um comentário irônico sobre {user1}.
{user} disse a {user1}: "Você parece falso(a)."
{user} riu da cara de {user1}.
{user} disse a {user1}: "Não me leva a mal, mas não curti."
{user} trocou de mesa para fugir de {user1}.
{user} disse a {user1}: "Você é muito barulhento(a)."
{user} deu uma resposta seca a {user1}.
{user} disse a {user1}: "Eu te conheço de algum lugar? Espero que não."
{user} ignorou a pergunta de {user1}.
{user} disse a {user1}: "Você fala muito de si."
{user} fez cara de nojo quando {user1} riu.
{user} disse a {user1}: "Você é esquisito(a)."
{user} tratou {user1} com frieza.
{user} disse a {user1}: "Não tenho paciência pra você."
{user} olhou {user1} de cima.
{user} disse a {user1}: "Você é convencido(a) demais."
{user} fingiu não ouvir {user1}.
{user} disse a {user1}: "Você é muito forçado(a)."
{user} riu baixinho de {user1}.
{user} disse a {user1}: "Não curti seu jeito."
{user} saiu da conversa sem dar tchau a {user1}.
{user} disse a {user1}: "Você é meio mala."
{user} fez um gesto de desprezo para {user1}.
{user} disse a {user1}: "Você parece arrogante."
{user} deu as costas pra {user1} sem cerimônia.
{user} disse a {user1}: "Menos ego, por favor."
{user} fechou a cara quando {user1} se aproximou.
{user} disse a {user1}: "Você não é tudo isso."
{user} ironizou a apresentação de {user1}.
{user} disse a {user1}: "Seu jeito me incomoda."
{user} fez questão de não olhar para {user1}.
{user} disse a {user1}: "Eu te acho antipático(a)."
{user} deu um sorrisinho debochado para {user1}.
{user} disse a {user1}: "Você não me desce."
{user} riu de {user1} com a boca tampada.
{user} disse a {user1}: "Você é muito cheio(a) de si."
{user} bufou quando {user1} entrou.
{user} disse a {user1}: "Eu não confiaria em você."
{user} fez uma piada às custas de {user1}.
{user} disse a {user1}: "Você é aquele tipo que eu evito."
{user} deu um aceno de cabeça gelado a {user1}.
{user} disse a {user1}: "Não curto gente como você."
{user} olhou {user1} e cochichou algo maldoso.
{user} disse a {user1}: "Você é sem graça."
{user} fingiu uma tosse quando {user1} falou.
{user} disse a {user1}: "Você não sabe a hora de parar."
{user} saiu rindo depois de passar por {user1}.
{user} disse a {user1}: "Você é esnobe."
{user} fez cara de paisagem para {user1}.
{user} disse a {user1}: "Você é muito dramático(a)."
{user} deu uma cotovelada leve em {user1} ao passar.
{user} disse a {user1}: "Ai, que preguiça de você."
{user} desdenhou do sotaque de {user1}.
{user} disse a {user1}: "Você é muito intrometido(a)."
{user} deixou {user1} falando sozinho(a).
{user} disse a {user1}: "Não gostei de você. Simples."
{user} revirou os olhos quando {user1} riu.
{user} disse a {user1}: "Você é muito pedante."
{user} fez um comentário maldoso sobre {user1}.
{user} disse a {user1}: "Você é chato(a) de doer."
{user} se afastou de {user1} sem disfarçar.
{user} disse a {user1}: "Você é muito falso(a)."
{user} riu da gafe de {user1}.
{user} disse a {user1}: "Você não me convence."
{user} fez questão de interromper {user1}.
{user} disse a {user1}: "Você é muito sem noção."
{user} olhou {user1} com tédio.
{user} disse a {user1}: "Eu não te suporto."
{user} imitou a risada de {user1}.
{user} disse a {user1}: "Você me irrita."
{user} riu quando {user1} tropeçou.
{user} disse a {user1}: "Você é muito metido(a) a esperto(a)."
{user} fez um muxoxo para {user1}.
{user} disse a {user1}: "Não sou seu(sua) amigo(a), tá?"
{user} desviou de {user1} no corredor.
{user} disse a {user1}: "Você é muito cansativo(a)."
{user} deu uma risadinha maldosa para {user1}.
{user} disse a {user1}: "Você tá sobrando aqui."
{user} olhou para {user1} como quem olha uma mancha.
{user} disse a {user1}: "Você é muito sem sal."
{user} ignorou {user1} de propósito.
{user} disse a {user1}: "Eu não gostei de você."
{user} fez questão de não cumprimentar {user1}.
{user} disse a {user1}: "Você é muito irritante."
{user} riu da história de {user1} sem disfarçar o deboche.
{user} disse a {user1}: "Você é o tipo que eu não chamo pra festa."
{user} fez um comentário azedo quando {user1} passou.
{user} disse a {user1}: "Você não é bem-vindo(a) na minha roda."
{user} fingiu dormir quando {user1} sentou perto.
{user} disse a {user1}: "Você é muito arrogante."
{user} fez uma cara de 'lá vem' quando viu {user1}.
{user} disse a {user1}: "Você é insuportável."
{user} riu de {user1} com dois outros convidados.
{user} disse a {user1}: "Você é muito pretensioso(a)."
{user} deu uma resposta atravessada a {user1}.
{user} disse a {user1}: "Você não é engraçado(a)."
{user} virou os olhos quando {user1} se apresentou.
{user} disse a {user1}: "Você tem cara de encrenca."
{user} fez questão de mudar de assunto quando {user1} falou.
{user} disse a {user1}: "Você é muito forçado(a), sério."
{user} deu uma gargalhada debochada de {user1}.
{user} disse a {user1}: "Você me dá preguiça."
{user} saiu do salão quando {user1} entrou.
{user} disse a {user1}: "Você é muito cheio(a) de pose."
{user} olhou com cara feia para {user1}.
{user} disse a {user1}: "Não tô a fim de conversa."
{user} deu um passo pra trás quando {user1} chegou.
{user} disse a {user1}: "Você é muito estranho(a), hein?"
{user} riu alto do que {user1} disse.
{user} disse a {user1}: "Você não sabe ouvir."
{user} fez questão de ignorar o elogio de {user1}.
{user} disse a {user1}: "Você é muito arrogante pra mim."
{user} bufou e saiu.
{user} disse a {user1}: "Você é muito sem noção, sério."
{user} deu uma olhada atravessada em {user1}.
{user} disse a {user1}: "Eu passo, obrigado(a)."
{user} fez questão de rir por último de {user1}.
{user} disse a {user1}: "Você não me desperta nada. Nada bom."
{user} ignorou {user1} e riu com outro.
{user} disse a {user1}: "Você é muito convencido(a)."
{user} disse a {user1}: "Você me parece encrenca pura."
{user} fingiu não ouvir quando {user1} disse oi.
{user} sorriu amarelo para {user1} e virou as costas.
{user} comentou alto: "Nossa, que figurino é esse, {user1}?"
{user} apertou a mão de {user1} como quem pega algo nojento.
{user} disse a {user1}: "Você é sempre assim, intenso(a)?"
{user} olhou para {user1} e soltou: "Hm. Interessante."
{user} riu da piada de {user1}... de nervoso.
{user} bocejou enquanto {user1} se apresentava.
{user} disse a {user1}: "Você me lembra alguém que eu não gosto."
{user} olhou {user1} e cochichou algo com quem estava ao lado.
{user} disse a {user1}: "Energia forte a sua. Forte demais."
{user} comentou sobre {user1}: "Veio pra aparecer, né?"
{user} disse a {user1}: "Você fala bastante, hein?"
{user} trocou de lugar quando {user1} sentou do lado.
{user} olhou a mala de {user1}: "Veio pra ficar muito, pelo visto."
{user} deu um "prazer" seco para {user1} e saiu.
{user} disse a {user1}: "Não sei se vou com a sua cara."
{user} riu de {user1} com alguém, sem nem disfarçar.
`);

export const APPROACH_GOSSIP_DISLIKE = lines(`
{user} cochichou com {user1}: "Cuidado com {user2}. Vive falando de você."
{user} contou a {user1}, baixinho: "{user2} não vai com a sua cara."
{user} chegou perto de {user1}: "Ouvi {user2} falando seu nome. Não era elogio."
{user} disse a {user1}: "{user2} tá te queimando pros outros."
{user} avisou {user1}: "{user2} disse que você é falso(a)."
{user} cochichou: "{user1}, {user2} tá armando contra você."
{user} disse a {user1}: "{user2} revira os olhos quando você fala."
{user} contou a {user1}: "{user2} te chamou de cobra."
{user} disse a {user1}: "Toma cuidado. {user2} te odeia."
{user} disse a {user1}: "{user2} tá desconfiando de você."
{user} contou a {user1}: "{user2} falou mal de você no café."
{user} disse a {user1}: "{user2} não suporta você, sabia?"
{user} cochichou: "{user2} tá juntando gente contra você."
{user} disse a {user1}: "{user2} fez piada de você pelas costas."
{user} avisou {user1}: "{user2} quer seu nome no quadro."
{user} disse a {user1}: "{user2} diz que você é o(a) mais falso(a) daqui."
{user} contou a {user1}: "{user2} riu de você com outros."
{user} disse a {user1}: "{user2} tem ranço de você."
{user} cochichou: "{user2} te imita quando você sai."
{user} disse a {user1}: "{user2} tá te vigiando."
{user} contou a {user1}: "{user2} disse que não confia em você."
{user} disse a {user1}: "{user2} falou que você é arrogante."
{user} avisou {user1}: "{user2} vai votar em você, eu acho."
{user} disse a {user1}: "{user2} te acha suspeito(a)."
{user} contou a {user1}: "{user2} tá falando de você pra todo mundo."
{user} disse a {user1}: "{user2} ficou com raiva de você ontem."
{user} cochichou: "{user2} tá te chamando de Traidor(a)."
{user} disse a {user1}: "{user2} não gosta nem do seu jeito de andar."
{user} contou a {user1}: "{user2} disse que você finge demais."
{user} disse a {user1}: "Se cuida com {user2}. É veneno."
{user} avisou {user1}: "{user2} quer te ver fora."
{user} disse a {user1}: "{user2} tá guardando rancor de você."
{user} contou a {user1}: "{user2} te critica o tempo todo."
{user} disse a {user1}: "{user2} tem inveja de você, é isso."
{user} cochichou: "{user2} falou que você é chato(a)."
{user} disse a {user1}: "{user2} tá contra você e não esconde."
{user} contou a {user1}: "{user2} tá plantando dúvida sobre você."
{user} disse a {user1}: "{user2} te acha perigoso(a)."
{user} avisou {user1}: "{user2} tá de olho em você, e não é bom."
{user} disse a {user1}: "{user2} disse que você não merece estar aqui."
{user} contou a {user1}: "{user2} tá te difamando."
{user} disse a {user1}: "{user2} te olha com raiva."
{user} cochichou: "{user2} fala que você é manipulador(a)."
{user} disse a {user1}: "{user2} não te suporta mais."
{user} contou a {user1}: "{user2} disse que você é a cobra do castelo."
{user} disse a {user1}: "{user2} quer te tirar do jogo."
{user} avisou {user1}: "{user2} tá te chamando de mentiroso(a)."
{user} disse a {user1}: "{user2} tem um problema com você."
{user} contou a {user1}: "{user2} falou de você com desprezo."
{user} disse a {user1}: "{user2} tá juntando votos contra você."
{user} cochichou: "{user2} disse que você é suspeito(a) demais."
{user} disse a {user1}: "Fica esperto(a) com {user2}."
{user} contou a {user1}: "{user2} te chamou de falso(a) na frente de todos."
{user} disse a {user1}: "{user2} tá contra você, eu vi."
{user} avisou {user1}: "{user2} vai te acusar na mesa."
{user} disse a {user1}: "{user2} não aguenta você."
{user} contou a {user1}: "{user2} tá falando que você é Traidor(a)."
{user} disse a {user1}: "{user2} te detesta, e todo mundo percebe."
{user} cochichou: "{user2} fez careta quando você passou."
{user} disse a {user1}: "{user2} tá te caçando."
{user} contou a {user1}: "{user2} disse que você é insuportável."
{user} disse a {user1}: "{user2} tá com você na mira."
{user} avisou {user1}: "{user2} falou de você no jardim."
{user} disse a {user1}: "{user2} não te engole."
{user} contou a {user1}: "{user2} tá tentando me convencer contra você."
{user} disse a {user1}: "{user2} tem raiva de você, não sei por quê."
{user} cochichou: "{user2} riu quando falaram de você."
{user} disse a {user1}: "{user2} tá falando pelas suas costas."
{user} contou a {user1}: "{user2} disse que você não é confiável."
{user} disse a {user1}: "{user2} é seu(sua) inimigo(a), só pra saber."
{user} avisou {user1}: "{user2} quer você longe."
{user} disse a {user1}: "{user2} tá desconfiado(a) de você."
{user} contou a {user1}: "{user2} te acha falso(a) e metido(a)."
{user} disse a {user1}: "{user2} vai te trair, eu sinto."
{user} cochichou: "{user2} te chamou de sonso(a)."
{user} disse a {user1}: "{user2} tá contra você, cuidado."
{user} contou a {user1}: "{user2} falou horrores de você."
{user} disse a {user1}: "{user2} tem nojo do seu jeito."
{user} avisou {user1}: "{user2} quer te ver pelas costas."
{user} disse a {user1}: "{user2} diz que você é interesseiro(a)."
{user} contou a {user1}: "{user2} tá fazendo campanha contra você."
{user} disse a {user1}: "{user2} não confia em você nem um pouco."
{user} cochichou: "{user2} te acha o(a) mais perigoso(a)."
{user} disse a {user1}: "{user2} tá de marcação com você."
{user} contou a {user1}: "{user2} disse que te acha falso(a)."
{user} disse a {user1}: "{user2} fala mal de você com qualquer um."
{user} avisou {user1}: "{user2} vai te derrubar se puder."
{user} disse a {user1}: "{user2} tá te difamando no castelo."
{user} contou a {user1}: "{user2} disse que você é cobra criada."
{user} disse a {user1}: "{user2} tem implicância com você."
{user} cochichou: "{user2} fala de você com raiva."
{user} disse a {user1}: "{user2} quer seu fim no jogo."
{user} contou a {user1}: "{user2} tá contando os dias pra você sair."
{user} disse a {user1}: "{user2} tá te chamando de sonso(a)."
{user} avisou {user1}: "{user2} tá contra você, pode anotar."
{user} disse a {user1}: "{user2} te olha torto o tempo todo."
{user} contou a {user1}: "{user2} falou que não te suporta."
{user} disse a {user1}: "{user2} tá tramando algo contra você."
{user} cochichou: "{user2} te acha arrogante."
{user} disse a {user1}: "{user2} quer seu nome na mesa hoje."
{user} contou a {user1}: "{user2} diz que você é Traidor(a) disfarçado(a)."
{user} disse a {user1}: "{user2} tá com ranço de você."
{user} avisou {user1}: "{user2} tá contra você e juntando gente."
{user} disse a {user1}: "{user2} fala de você com desprezo."
{user} contou a {user1}: "{user2} te chamou de falso(a) no corredor."
{user} disse a {user1}: "{user2} não te quer por perto."
{user} cochichou: "{user2} riu de você no café."
{user} disse a {user1}: "{user2} tá te difamando, sério."
{user} contou a {user1}: "{user2} falou que você é chato(a) demais."
{user} disse a {user1}: "{user2} te quer fora do jogo."
{user} avisou {user1}: "{user2} vai votar em você, com certeza."
{user} disse a {user1}: "{user2} não vai com a sua cara, de jeito nenhum."
{user} contou a {user1}: "{user2} fala mal de você pra quem quiser ouvir."
{user} disse a {user1}: "{user2} tá contra você desde o começo."
{user} cochichou: "{user2} disse que você é perigoso(a)."
{user} disse a {user1}: "{user2} tem uma birra com você."
{user} contou a {user1}: "{user2} te chamou de mentiroso(a)."
{user} disse a {user1}: "{user2} tá tentando te isolar."
{user} avisou {user1}: "{user2} vai te acusar de novo."
{user} disse a {user1}: "{user2} te acha insuportável."
{user} contou a {user1}: "{user2} disse que você é o problema."
{user} disse a {user1}: "{user2} tá de olho em você, e com raiva."
{user} cochichou: "{user2} falou que você não é Fiel."
{user} disse a {user1}: "{user2} te critica pra todo mundo."
{user} contou a {user1}: "{user2} tá contra você e quer apoio."
{user} disse a {user1}: "{user2} tem muita raiva de você."
{user} avisou {user1}: "{user2} tá te queimando na mesa."
{user} disse a {user1}: "{user2} diz que você é manipulador(a)."
{user} contou a {user1}: "{user2} falou de você de um jeito feio."
{user} disse a {user1}: "{user2} não te suporta, é sério."
{user} cochichou: "{user2} tá torcendo pra você sair."
{user} disse a {user1}: "{user2} fala mal de você nas suas costas."
{user} contou a {user1}: "{user2} disse que você finge ser Fiel."
{user} disse a {user1}: "{user2} tá contra você, fica sabendo."
{user} avisou {user1}: "{user2} quer seu voto fora."
{user} disse a {user1}: "{user2} te olha de cara feia."
{user} contou a {user1}: "{user2} tá juntando provas contra você. Ou inventando."
{user} disse a {user1}: "{user2} não te quer na final."
{user} cochichou: "{user2} te acha um(a) falso(a)."
{user} disse a {user1}: "{user2} tá contra você e não disfarça."
{user} contou a {user1}: "{user2} fala de você com ódio."
{user} disse a {user1}: "{user2} quer te ver cair."
{user} avisou {user1}: "{user2} tá te difamando nas conversas."
{user} disse a {user1}: "{user2} te acha perigoso(a) demais."
{user} contou a {user1}: "{user2} disse que você não é quem parece."
{user} disse a {user1}: "{user2} tem aversão a você."
{user} cochichou: "{user2} falou que você é o(a) próximo(a)."
{user} disse a {user1}: "{user2} tá contra você, se cuida."
{user} contou a {user1}: "{user2} te chamou de cobra de novo."
{user} disse a {user1}: "{user2} tá te caçando na mesa."
{user} avisou {user1}: "{user2} vai te derrubar, fica esperto(a)."
{user} disse a {user1}: "{user2} tem ranço de você e fala pra todos."
{user} contou a {user1}: "{user2} disse que te odeia."
{user} disse a {user1}: "{user2} tá de marcação cerrada com você."
{user} cochichou: "{user2} quer você longe do prêmio."
{user} disse a {user1}: "{user2} fala de você o dia inteiro."
{user} contou a {user1}: "{user2} tá contra você, e forte."
{user} disse a {user1}: "{user2} te acha o(a) mais falso(a)."
{user} avisou {user1}: "{user2} tá armando pra mesa."
{user} disse a {user1}: "{user2} não te suporta, cuidado."
{user} contou a {user1}: "{user2} disse coisas pesadas de você."
{user} disse a {user1}: "{user2} tá contra você, eu ouvi."
{user} cochichou: "{user2} te quer fora hoje."
{user} disse a {user1}: "{user2} tem raiva de você, e muita."
{user} contou a {user1}: "{user2} tá difamando você por aí."
{user} disse a {user1}: "{user2} te olha como inimigo(a)."
{user} avisou {user1}: "{user2} quer seu nome no voto."
{user} disse a {user1}: "{user2} não vai com você, de jeito nenhum."
{user} contou a {user1}: "{user2} falou que você é o(a) Traidor(a)."
{user} disse a {user1}: "{user2} tá contra você. Toma cuidado."
{user} cochichou: "{user2} te chamou de falso(a), de novo."
{user} disse a {user1}: "{user2} tá torcendo contra você."
{user} contou a {user1}: "{user2} fala mal de você com gosto."
{user} disse a {user1}: "{user2} te acha uma ameaça."
{user} avisou {user1}: "{user2} tá contra você na mesa."
{user} disse a {user1}: "{user2} tem implicância, e das grandes."
{user} contou a {user1}: "{user2} disse que você não presta."
{user} disse a {user1}: "{user2} tá te queimando, eu vi com meus olhos."
{user} cochichou: "{user2} tá contra você e quer que eu fique também."
{user} disse a {user1}: "{user2} fala de você como inimigo(a)."
{user} contou a {user1}: "{user2} quer te ver pelas costas, literalmente."
{user} disse a {user1}: "{user2} tá contra você. Só te aviso."
{user} disse a {user1}: "{user2} te chamou de sonso(a). Achei que devia saber."
{user} contou a {user1}: "{user2} imitou seu jeito de falar. Riram muito."
{user} disse a {user1}: "{user2} diz que você é planta."
{user} disse a {user1}: "{user2} tem ranço de você. Não sei por quê."
{user} cochichou: "{user1}, {user2} falou que você é falso(a)."
{user} disse a {user1}: "{user2} revira o olho quando você fala."
{user} disse a {user1}: "Ouvi {user2} dizendo que não te suporta."
{user} disse a {user1}: "{user2} disse que você se acha demais."
{user} disse a {user1}: "Cuidado, {user2} anda te queimando."
{user} disse a {user1}: "{user2} falou de você com um desprezo..."
{user} disse a {user1}: "{user2} diz que você não é de confiança."
{user} disse a {user1}: "Não conta que fui eu, mas {user2} te detesta."
{user} disse a {user1}: "{user2} te chamou de cobra. Com todas as letras."
{user} disse a {user1}: "{user2} fica tenso(a) quando você chega."
{user} disse a {user1}: "{user2} disse que você fala demais."
{user} disse a {user1}: "{user2} tá te pintando como vilão(ã)."
{user} disse a {user1}: "{user2} jurou que vai te tirar daqui."
{user} disse a {user1}: "Vi {user2} fazendo careta pra você."
{user} disse a {user1}: "{user2} disse que você é puro teatro."
{user} disse a {user1}: "{user2} não gosta do seu jeito. Nem disfarça."
{user} disse a {user1}: "Sabe quem não te engole? {user2}."
`);

export const APPROACH_GOSSIP_VOTED = lines(`
{user} avisou {user1}: "{user2} votou em você. E vai votar de novo."
{user} contou a {user1}: "Você viu? {user2} escreveu seu nome."
{user} disse a {user1}: "{user2} votou em você ontem. Não esquece."
{user} cochichou: "{user2} votou em você e ainda riu."
{user} disse a {user1}: "Seu nome saiu da mão de {user2}."
{user} avisou {user1}: "{user2} votou em você sem pensar duas vezes."
{user} disse a {user1}: "{user2} tá de olho em você desde o voto."
{user} contou a {user1}: "{user2} votou em você e disse que vai repetir."
{user} disse a {user1}: "Não confia em {user2}. Votou em você."
{user} cochichou: "{user2} escreveu seu nome com gosto."
{user} disse a {user1}: "{user2} votou em você e ainda se gabou."
{user} avisou {user1}: "{user2} tá juntando votos pra você de novo."
{user} disse a {user1}: "Lembra quem votou em você? {user2}."
{user} contou a {user1}: "{user2} votou em você e quer mais gente junto."
{user} disse a {user1}: "{user2} já te escolheu como alvo."
{user} cochichou: "{user2} votou em você e fingiu que não."
{user} disse a {user1}: "{user2} não te perdoa, e votou de novo."
{user} avisou {user1}: "{user2} votou em você e vai continuar."
{user} disse a {user1}: "{user2} votou em você. Não é à toa."
{user} contou a {user1}: "{user2} disse que votou em você e dormiu bem."
{user} disse a {user1}: "{user2} escreveu seu nome em letra grande."
{user} cochichou: "{user2} votou em você, e sabe por quê? Medo."
{user} disse a {user1}: "{user2} votou em você e tá convencendo outros."
{user} avisou {user1}: "{user2} tem seu nome na ponta da caneta."
{user} disse a {user1}: "{user2} votou em você, cuidado."
{user} contou a {user1}: "{user2} falou que seu voto é fixo: você."
{user} disse a {user1}: "{user2} votou em você e vai de novo hoje."
{user} cochichou: "{user2} nem hesitou em escrever seu nome."
{user} disse a {user1}: "{user2} votou em você, eu vi."
{user} avisou {user1}: "{user2} tá te caçando nos votos."
{user} disse a {user1}: "{user2} votou em você e ainda pediu apoio."
{user} contou a {user1}: "{user2} votou em você e disse que tava certo."
{user} disse a {user1}: "{user2} tá com seu nome guardado."
{user} cochichou: "{user2} votou em você, e não foi a primeira vez."
{user} disse a {user1}: "{user2} tem você como alvo fixo."
{user} avisou {user1}: "{user2} votou em você e vai convencer mais gente."
{user} disse a {user1}: "{user2} escreveu seu nome e sorriu."
{user} contou a {user1}: "{user2} votou em você e comemorou baixinho."
{user} disse a {user1}: "{user2} te quer fora, olha o voto."
{user} cochichou: "{user2} votou em você com a maior calma."
{user} disse a {user1}: "{user2} tá contra você nas urnas."
{user} avisou {user1}: "{user2} votou em você, e pode votar de novo."
{user} disse a {user1}: "{user2} tem seu nome no voto dele(a)."
{user} contou a {user1}: "{user2} disse que você é o voto certo."
{user} disse a {user1}: "{user2} votou em você, e falou mal depois."
{user} cochichou: "{user2} escreveu seu nome primeiro."
{user} disse a {user1}: "{user2} votou em você e tá se fazendo de amigo(a)."
{user} avisou {user1}: "{user2} tá mirando em você de novo."
{user} disse a {user1}: "{user2} votou em você, e não se arrependeu."
{user} contou a {user1}: "{user2} votou em você e riu na saída."
{user} disse a {user1}: "{user2} te escolheu no voto. Fica esperto(a)."
{user} cochichou: "{user2} tem uma birra com você nos votos."
{user} disse a {user1}: "{user2} votou em você, e vai tentar de novo."
{user} avisou {user1}: "{user2} escreveu seu nome com convicção."
{user} disse a {user1}: "{user2} votou em você, eu sei."
{user} contou a {user1}: "{user2} tá contando votos contra você."
{user} disse a {user1}: "{user2} te quer no quadro."
{user} cochichou: "{user2} votou em você e fingiu surpresa."
{user} disse a {user1}: "{user2} votou em você e tá puxando outros."
{user} avisou {user1}: "{user2} não vai parar de votar em você."
{user} disse a {user1}: "{user2} votou em você, e com raiva."
{user} contou a {user1}: "{user2} disse que te vota até você sair."
{user} disse a {user1}: "{user2} escreveu seu nome, e eu vi."
{user} cochichou: "{user2} votou em você sem piscar."
{user} disse a {user1}: "{user2} tá contra você no voto e fora dele."
{user} avisou {user1}: "{user2} votou em você, e tem mais gente com ele(a)."
{user} disse a {user1}: "{user2} votou em você, não confia."
{user} contou a {user1}: "{user2} escreveu seu nome e ficou quieto(a)."
{user} disse a {user1}: "{user2} tem você na mira do voto."
{user} cochichou: "{user2} votou em você e ainda te abraçou depois."
{user} disse a {user1}: "{user2} votou em você, e isso diz muito."
{user} avisou {user1}: "{user2} vai votar em você hoje, aposto."
{user} disse a {user1}: "{user2} escreveu seu nome em letra caprichada."
{user} contou a {user1}: "{user2} votou em você e se justificou pra todos."
{user} disse a {user1}: "{user2} votou em você, e continua de olho."
{user} cochichou: "{user2} te escolheu no voto de novo."
{user} disse a {user1}: "{user2} votou em você, e você nem desconfiava."
{user} avisou {user1}: "{user2} tá com você no radar dos votos."
{user} disse a {user1}: "{user2} votou em você, e sorriu pra você no café."
{user} contou a {user1}: "{user2} escreveu seu nome e disse 'desculpa'."
{user} disse a {user1}: "{user2} votou em você, e é por medo."
{user} cochichou: "{user2} votou em você, cuidado com o abraço dele(a)."
{user} disse a {user1}: "{user2} te vota desde o primeiro dia."
{user} avisou {user1}: "{user2} votou em você, e vai convencer mais."
{user} disse a {user1}: "{user2} escreveu seu nome com calma."
{user} contou a {user1}: "{user2} votou em você e contou pra todo mundo."
{user} disse a {user1}: "{user2} votou em você, não esquece disso na mesa."
{user} cochichou: "{user2} tem seu nome decorado."
{user} disse a {user1}: "{user2} votou em você, e não foi por acaso."
{user} avisou {user1}: "{user2} é seu voto contrário fixo."
{user} disse a {user1}: "{user2} votou em você, e é leal ao próprio voto."
{user} contou a {user1}: "{user2} disse que vai votar em você até o fim."
{user} disse a {user1}: "{user2} escreveu seu nome, e eu achei injusto."
{user} cochichou: "{user2} votou em você, de novo."
{user} disse a {user1}: "{user2} te escolheu, e não esconde."
{user} avisou {user1}: "{user2} votou em você, e pode ser o(a) Traidor(a)."
{user} disse a {user1}: "{user2} votou em você, e ainda posou de amigo(a)."
{user} contou a {user1}: "{user2} escreveu seu nome e pediu segredo."
{user} disse a {user1}: "{user2} votou em você, fica de olho."
{user} cochichou: "{user2} te colocou no quadro."
{user} disse a {user1}: "{user2} votou em você, e sem motivo."
{user} avisou {user1}: "{user2} votou em você e tá orgulhoso(a) disso."
{user} disse a {user1}: "{user2} escreveu seu nome, e não foi o único."
{user} contou a {user1}: "{user2} votou em você e falou que tinha certeza."
{user} disse a {user1}: "{user2} votou em você, e vai tentar te tirar."
{user} cochichou: "{user2} escreveu seu nome e riu com o parceiro."
{user} disse a {user1}: "{user2} votou em você. Só pra você saber."
{user} avisou {user1}: "{user2} votou em você, e amanhã vai votar de novo."
{user} disse a {user1}: "{user2} te quer fora, olha o voto dele(a)."
{user} contou a {user1}: "{user2} votou em você, e se fez de inocente."
{user} disse a {user1}: "{user2} escreveu seu nome. Anota isso."
{user} cochichou: "{user2} votou em você sem pestanejar."
{user} disse a {user1}: "{user2} votou em você, e com vontade."
{user} avisou {user1}: "{user2} tem seu nome como alvo principal."
{user} disse a {user1}: "{user2} votou em você, e tá de olho em quem te defende."
{user} contou a {user1}: "{user2} votou em você e disse que foi estratégia."
{user} disse a {user1}: "{user2} escreveu seu nome, e fingiu que não."
{user} cochichou: "{user2} votou em você, e riu depois."
{user} disse a {user1}: "{user2} votou em você. Pensa nisso."
{user} avisou {user1}: "{user2} vai continuar votando em você."
{user} disse a {user1}: "{user2} escreveu seu nome com raiva."
{user} contou a {user1}: "{user2} votou em você e contou vantagem."
{user} disse a {user1}: "{user2} votou em você, e tá te vigiando."
{user} cochichou: "{user2} tem você no voto, é fato."
{user} disse a {user1}: "{user2} votou em você, e isso me incomodou."
{user} avisou {user1}: "{user2} votou em você, e tem aliados junto."
{user} disse a {user1}: "{user2} escreveu seu nome como quem já decidiu."
{user} contou a {user1}: "{user2} votou em você, e vai de novo, garantiu."
{user} disse a {user1}: "{user2} votou em você. Cuidado com ele(a)."
{user} cochichou: "{user2} votou em você, e ainda te elogiou depois."
{user} disse a {user1}: "{user2} te escolheu no voto, e vai escolher de novo."
{user} avisou {user1}: "{user2} votou em você, fica esperto(a) na mesa."
{user} disse a {user1}: "{user2} escreveu seu nome em silêncio."
{user} contou a {user1}: "{user2} votou em você e disse que não se arrepende."
{user} disse a {user1}: "{user2} votou em você, e não é amigo(a)."
{user} cochichou: "{user2} votou em você, e tá sorrindo pra você agora."
{user} disse a {user1}: "{user2} votou em você, e vai continuar tentando."
{user} avisou {user1}: "{user2} tem seu nome como prioridade."
{user} disse a {user1}: "{user2} escreveu seu nome e ficou aliviado(a)."
{user} contou a {user1}: "{user2} votou em você e riu com alguém."
{user} disse a {user1}: "{user2} votou em você, e isso não foi acaso."
{user} cochichou: "{user2} votou em você de novo, eu vi."
{user} disse a {user1}: "{user2} te quer fora, e votou pra isso."
{user} avisou {user1}: "{user2} votou em você, e vai votar sempre."
{user} disse a {user1}: "{user2} escreveu seu nome sem pena."
{user} contou a {user1}: "{user2} votou em você e se justificou mal."
{user} disse a {user1}: "{user2} votou em você, e ainda quer sua amizade."
{user} cochichou: "{user2} te votou, e é bom você saber."
{user} disse a {user1}: "{user2} votou em você, e tá do lado errado."
{user} avisou {user1}: "{user2} votou em você, e vai tentar de novo hoje."
{user} disse a {user1}: "{user2} escreveu seu nome primeiro que todos."
{user} contou a {user1}: "{user2} votou em você e disse que foi fácil."
{user} disse a {user1}: "{user2} votou em você, não baixa a guarda."
{user} cochichou: "{user2} votou em você com convicção."
{user} disse a {user1}: "{user2} votou em você, e fingiu tristeza."
{user} avisou {user1}: "{user2} vai te votar enquanto puder."
{user} disse a {user1}: "{user2} escreveu seu nome e não pestanejou."
{user} contou a {user1}: "{user2} votou em você e já planeja o próximo."
{user} disse a {user1}: "{user2} votou em você, e isso fala muito."
{user} cochichou: "{user2} votou em você, de propósito."
{user} disse a {user1}: "{user2} votou em você, e ainda se diz seu amigo(a)."
{user} avisou {user1}: "{user2} tá votando em você de novo, cuidado."
{user} disse a {user1}: "{user2} escreveu seu nome, e foi convicto(a)."
{user} contou a {user1}: "{user2} votou em você e disse que vai ganhar."
{user} disse a {user1}: "{user2} votou em você. Anota esse nome."
{user} cochichou: "{user2} te votou, e sorriu."
{user} disse a {user1}: "{user2} votou em você, e vai continuar."
{user} avisou {user1}: "{user2} votou em você, e tem cara de que vai de novo."
{user} disse a {user1}: "{user2} escreveu seu nome, e não foi o único."
{user} contou a {user1}: "{user2} votou em você e comemorou."
{user} disse a {user1}: "{user2} votou em você. Fica atento(a)."
{user} cochichou: "{user2} te votou, e tá tranquilo(a)."
{user} disse a {user1}: "{user2} votou em você, e é bom lembrar."
{user} avisou {user1}: "{user2} votou em você, e vai tentar mais."
{user} disse a {user1}: "{user2} escreveu seu nome com um sorriso."
{user} contou a {user1}: "{user2} votou em você e disse que foi certo."
{user} disse a {user1}: "{user2} votou em você, e tem mais a caminho."
{user} cochichou: "{user2} votou em você, e sabe disso."
{user} disse a {user1}: "{user2} votou em você, e não te quer bem."
{user} avisou {user1}: "{user2} votou em você, e vai continuar votando."
{user} disse a {user1}: "{user2} escreveu seu nome e não se arrependeu."
{user} contou a {user1}: "{user2} votou em você e disse que é Fiel."
{user} disse a {user1}: "{user2} votou em você, e tá de olho."
{user} cochichou: "{user2} te votou, e ainda te chamou pra conversar."
{user} disse a {user1}: "{user2} votou em você, fica esperto(a)."
{user} avisou {user1}: "{user2} tá com seu nome no bolso."
{user} disse a {user1}: "{user2} escreveu seu nome, e eu fiquei com raiva."
{user} contou a {user1}: "{user2} votou em você, e vai de novo, disse."
{user} disse a {user1}: "{user2} votou em você, não esquece."
{user} cochichou: "{user2} votou em você, e fez questão que eu visse."
{user} disse a {user1}: "{user2} votou em você, e quer que outros votem."
{user} avisou {user1}: "{user2} votou em você, é fato."
{user} disse a {user1}: "Seu nome no papel? Letra de {user2}."
{user} cochichou: "{user1}, quem votou em você foi {user2}."
{user} disse a {user1}: "{user2} escreveu seu nome sem hesitar."
{user} disse a {user1}: "Não esquece que {user2} votou contra você."
{user} disse a {user1}: "{user2} votou em você e depois sorriu."
{user} disse a {user1}: "{user2} te colocou na forca ontem."
{user} disse a {user1}: "O voto de {user2} foi seu. Anota."
{user} disse a {user1}: "{user2} te traiu no voto. Simples assim."
{user} disse a {user1}: "Você confia em {user2}? Seu nome saiu dali."
{user} disse a {user1}: "{user2} votou em você e fingiu que não."
{user} disse a {user1}: "Quem te queria fora ontem? {user2}."
{user} disse a {user1}: "{user2} tem você como alvo. O voto mostrou."
`);

export const APPROACH_WARNING_LEADER = lines(`
{user} avisou {user1}: "{user2} está juntando votos contra você."
{user} cochichou: "{user1}, {user2} tá puxando a mesa pra você."
{user} disse a {user1}: "{user2} tá fazendo campanha contra você."
{user} disse a {user1}: "Seu nome tá na boca de {user2}. E não é bom."
{user} alertou {user1}: "{user2} quer você no quadro hoje."
{user} disse a {user1}: "{user2} tá convencendo gente a votar em você."
{user} chamou {user1} de lado: "{user2} tá liderando contra você."
{user} disse a {user1}: "{user2} tá de porta em porta falando de você."
{user} cochichou: "{user2} já tem três votos contra você."
{user} disse a {user1}: "{user2} armou pra você, se prepara."
{user} avisou {user1}: "{user2} vai te acusar primeiro na mesa."
{user} disse a {user1}: "{user2} tá organizando os votos contra você."
{user} disse a {user1}: "Cuidado: {user2} tá puxando todo mundo."
{user} cochichou: "{user2} quer seu nome hoje, e tá conseguindo."
{user} disse a {user1}: "{user2} tá vendendo você como Traidor(a)."
{user} alertou {user1}: "{user2} conversou com metade da mesa sobre você."
{user} disse a {user1}: "{user2} tá costurando votos contra você."
{user} disse a {user1}: "Você precisa agir. {user2} tá forte contra você."
{user} cochichou: "{user2} convenceu os aliados dele(a) a votar em você."
{user} disse a {user1}: "{user2} tá contando votos. Os seus."
{user} avisou {user1}: "{user2} vai abrir a mesa falando de você."
{user} disse a {user1}: "{user2} tá conseguindo virar a mesa contra você."
{user} disse a {user1}: "{user2} tá liderando sua queda."
{user} cochichou: "{user2} te quer fora, e tá organizando isso."
{user} disse a {user1}: "{user2} tá te pintando de Traidor(a) pra todos."
{user} alertou {user1}: "{user2} tem um plano contra você."
{user} disse a {user1}: "{user2} tá recrutando votos contra você."
{user} disse a {user1}: "Se prepara: {user2} vem com tudo na mesa."
{user} cochichou: "{user2} já convenceu gente contra você."
{user} disse a {user1}: "{user2} tá mobilizando o castelo contra você."
{user} avisou {user1}: "{user2} tá puxando o voto pra você."
{user} disse a {user1}: "{user2} vai te derrubar se ninguém fizer nada."
{user} disse a {user1}: "{user2} tá cochichando seu nome com todo mundo."
{user} cochichou: "{user2} quer seu nome e já tem apoio."
{user} disse a {user1}: "{user2} tá liderando uma caçada. Você é a caça."
{user} alertou {user1}: "{user2} tá juntando um bloco contra você."
{user} disse a {user1}: "{user2} tá conseguindo, você tem que reagir."
{user} disse a {user1}: "{user2} tá falando de você com todo mundo."
{user} cochichou: "{user2} armou uma frente contra você."
{user} disse a {user1}: "{user2} tá manipulando a mesa contra você."
{user} avisou {user1}: "{user2} quer você fora hoje, e tem votos."
{user} disse a {user1}: "{user2} tá sendo o(a) cabeça contra você."
{user} disse a {user1}: "Você é o alvo de {user2}. Age rápido."
{user} cochichou: "{user2} tá vendendo seu nome."
{user} disse a {user1}: "{user2} tá conquistando gente contra você."
{user} alertou {user1}: "{user2} tem a mesa quase na mão contra você."
{user} disse a {user1}: "{user2} tá liderando o movimento contra você."
{user} disse a {user1}: "{user2} tá pedindo voto em você de mesa em mesa."
{user} cochichou: "{user2} tá contra você e é influente."
{user} disse a {user1}: "{user2} tá organizando a sua saída."
{user} avisou {user1}: "{user2} já tem a maioria, quase."
{user} disse a {user1}: "{user2} tá conseguindo virar os indecisos."
{user} disse a {user1}: "Cuidado com {user2}, tá liderando contra você."
{user} cochichou: "{user2} te escolheu como alvo da mesa."
{user} disse a {user1}: "{user2} tá sendo convincente contra você."
{user} alertou {user1}: "{user2} tá fazendo lobby contra você."
{user} disse a {user1}: "{user2} tá puxando votos, e são muitos."
{user} disse a {user1}: "{user2} tá costurando sua saída."
{user} cochichou: "{user2} já tem aliados votando em você."
{user} disse a {user1}: "{user2} tá mobilizando todo mundo."
{user} avisou {user1}: "{user2} vai te acusar com força."
{user} disse a {user1}: "{user2} tá conseguindo virar a opinião."
{user} disse a {user1}: "{user2} tá liderando a caça contra você."
{user} cochichou: "{user2} tá contra você e tem seguidores."
{user} disse a {user1}: "{user2} tá te queimando e juntando votos."
{user} alertou {user1}: "{user2} tem um bloco pronto contra você."
{user} disse a {user1}: "{user2} tá convencendo até os seus amigos."
{user} disse a {user1}: "{user2} quer você fora, e tá trabalhando pra isso."
{user} cochichou: "{user2} tá liderando uma campanha pesada contra você."
{user} disse a {user1}: "{user2} tá conseguindo, reage."
{user} avisou {user1}: "{user2} tá pedindo seu nome no voto."
{user} disse a {user1}: "{user2} tá com a mesa contra você."
{user} disse a {user1}: "{user2} tá liderando, e você tá na mira."
{user} cochichou: "{user2} já fechou votos contra você."
{user} disse a {user1}: "{user2} tá mexendo os pauzinhos contra você."
{user} alertou {user1}: "{user2} tá conquistando votos contra você."
{user} disse a {user1}: "{user2} tá sendo o motor contra você."
{user} disse a {user1}: "{user2} tá conversando com todo mundo sobre você."
{user} cochichou: "{user2} te quer no quadro, e tá perto."
{user} disse a {user1}: "{user2} tá liderando os votos. Contra você."
{user} avisou {user1}: "{user2} tá tramando a sua saída."
{user} disse a {user1}: "{user2} tem influência, e tá usando contra você."
{user} disse a {user1}: "Você precisa de defesa. {user2} tá atacando."
{user} cochichou: "{user2} tá liderando a oposição a você."
{user} disse a {user1}: "{user2} tá conseguindo votos contra você fácil."
{user} alertou {user1}: "{user2} tá convencendo os indecisos."
{user} disse a {user1}: "{user2} tá puxando o castelo pra você."
{user} disse a {user1}: "{user2} tá orquestrando tudo."
{user} cochichou: "{user2} tem um plano e você é o alvo."
{user} disse a {user1}: "{user2} tá liderando, e forte."
{user} avisou {user1}: "{user2} quer seu nome, e tá juntando gente."
{user} disse a {user1}: "{user2} tá sendo o(a) líder contra você."
{user} disse a {user1}: "{user2} tá costurando uma aliança contra você."
{user} cochichou: "{user2} tá pedindo votos contra você."
{user} disse a {user1}: "{user2} tá mobilizando a mesa."
{user} alertou {user1}: "{user2} já tem um grupo votando em você."
{user} disse a {user1}: "{user2} tá conseguindo o que quer."
{user} disse a {user1}: "{user2} tá liderando a sua caçada."
{user} cochichou: "{user2} tá contra você, e é o(a) mais influente."
{user} disse a {user1}: "{user2} tá puxando todos os votos."
{user} avisou {user1}: "{user2} vai te acusar e tem apoio."
{user} disse a {user1}: "{user2} tá liderando contra você, se cuida."
{user} disse a {user1}: "{user2} tá conquistando a mesa."
{user} cochichou: "{user2} já tem votos suficientes contra você, quase."
{user} disse a {user1}: "{user2} tá organizando tudo contra você."
{user} alertou {user1}: "{user2} tá convencendo seus aliados."
{user} disse a {user1}: "{user2} tá puxando voto, e é pra você."
{user} disse a {user1}: "{user2} tá liderando uma frente."
{user} cochichou: "{user2} quer você fora hoje."
{user} disse a {user1}: "{user2} tá sendo muito convincente contra você."
{user} avisou {user1}: "{user2} tem a mesa inclinada contra você."
{user} disse a {user1}: "{user2} tá liderando, e você precisa reagir."
{user} disse a {user1}: "{user2} tá te acusando pra todo mundo."
{user} cochichou: "{user2} armou contra você na surdina."
{user} disse a {user1}: "{user2} tá liderando e você tá perdendo votos."
{user} alertou {user1}: "{user2} já conversou com todos contra você."
{user} disse a {user1}: "{user2} tá costurando sua eliminação."
{user} disse a {user1}: "{user2} tá liderando o voto."
{user} cochichou: "{user2} te quer fora, e tá conseguindo apoio."
{user} disse a {user1}: "{user2} tá mobilizando contra você, age."
{user} avisou {user1}: "{user2} vai abrir a mesa com seu nome."
{user} disse a {user1}: "{user2} tá liderando a oposição."
{user} disse a {user1}: "{user2} tá conseguindo votos, cuidado."
{user} cochichou: "{user2} tá contra você e é bom de papo."
{user} disse a {user1}: "{user2} tá puxando a mesa, e forte."
{user} alertou {user1}: "{user2} tá conseguindo a maioria contra você."
{user} disse a {user1}: "{user2} tá sendo o(a) mentor(a) contra você."
{user} disse a {user1}: "{user2} tá liderando, e você precisa de aliados."
{user} cochichou: "{user2} já tem gente comprometida contra você."
{user} disse a {user1}: "{user2} tá organizando o voto contra você."
{user} avisou {user1}: "{user2} tá convencendo, e rápido."
{user} disse a {user1}: "{user2} tá liderando, se prepara."
{user} disse a {user1}: "{user2} quer seu nome e tá quase lá."
{user} cochichou: "{user2} tá fazendo a cabeça da mesa contra você."
{user} disse a {user1}: "{user2} tá liderando a sua saída."
{user} alertou {user1}: "{user2} tá pedindo apoio contra você."
{user} disse a {user1}: "{user2} tá conquistando todos contra você."
{user} disse a {user1}: "{user2} tá liderando, e é perigoso."
{user} cochichou: "{user2} tá contra você e tem força."
{user} disse a {user1}: "{user2} tá puxando os votos contra você."
{user} avisou {user1}: "{user2} tem um plano pra hoje, e é você."
{user} disse a {user1}: "{user2} tá liderando a mesa contra você."
{user} disse a {user1}: "{user2} tá conseguindo virar geral."
{user} cochichou: "{user2} quer você fora, e tá sendo ouvido(a)."
{user} disse a {user1}: "{user2} tá liderando, você tem que se defender."
{user} alertou {user1}: "{user2} tá convencendo até quem gostava de você."
{user} disse a {user1}: "{user2} tá puxando todo mundo pra você."
{user} disse a {user1}: "{user2} tá liderando, e tá funcionando."
{user} cochichou: "{user2} já tem uma lista de votos contra você."
{user} disse a {user1}: "{user2} tá organizando, e você é o nome."
{user} avisou {user1}: "{user2} vai com tudo contra você hoje."
{user} disse a {user1}: "{user2} tá liderando, reage logo."
{user} disse a {user1}: "{user2} tá conseguindo votos contra você, sério."
{user} cochichou: "{user2} tá mobilizando todos."
{user} disse a {user1}: "{user2} tá liderando uma campanha contra você."
{user} alertou {user1}: "{user2} já convenceu metade."
{user} disse a {user1}: "{user2} tá puxando a mesa, se protege."
{user} disse a {user1}: "{user2} tá liderando contra você, e é forte."
{user} cochichou: "{user2} te quer no quadro, e tá conseguindo."
{user} disse a {user1}: "{user2} tá organizando a sua saída hoje."
{user} avisou {user1}: "{user2} tem apoio pra te tirar."
{user} disse a {user1}: "{user2} tá liderando, e você precisa agir."
{user} disse a {user1}: "{user2} tá conquistando votos, cuidado."
{user} cochichou: "{user2} tá contra você, com a mesa junto."
{user} disse a {user1}: "{user2} tá puxando, e é pra você."
{user} alertou {user1}: "{user2} tá convencendo todo mundo."
{user} disse a {user1}: "{user2} tá liderando a caçada."
{user} disse a {user1}: "{user2} tá organizando, fica esperto(a)."
{user} cochichou: "{user2} já tem a mesa quase inteira."
{user} disse a {user1}: "{user2} tá liderando contra você. Age."
{user} avisou {user1}: "{user2} tá puxando os votos pra você hoje."
{user} disse a {user1}: "{user2} tá conseguindo, não fica parado(a)."
{user} disse a {user1}: "{user2} tá liderando uma frente contra você."
{user} cochichou: "{user2} quer seu fim, e tem apoio."
{user} disse a {user1}: "{user2} tá mobilizando a mesa contra você."
{user} alertou {user1}: "{user2} tá liderando, e rápido."
{user} disse a {user1}: "{user2} tá conquistando votos contra você agora."
{user} disse a {user1}: "{user2} tá liderando, e você é o alvo."
{user} cochichou: "{user2} tá costurando votos com todo mundo."
{user} disse a {user1}: "{user2} tá liderando a oposição, cuidado."
{user} avisou {user1}: "{user2} tá contra você, e com força total."
{user} disse a {user1}: "{user2} tá puxando a mesa inteira."
{user} disse a {user1}: "{user2} tá liderando, e tá quase conseguindo."
{user} cochichou: "{user2} tá contra você e juntando um exército."
{user} disse a {user1}: "{user2} tá organizando tudo, você precisa reagir."
{user} disse a {user1}: "{user2} tá de casa em casa pedindo voto em você."
{user} cochichou com {user1}: "Quem puxa contra você é {user2}."
{user} avisou {user1}: "{user2} tá te pintando de Traidor(a)."
{user} disse a {user1}: "{user2} jurou que você cai hoje."
{user} disse a {user1}: "Fica de olho em {user2}. Tá articulando."
{user} disse a {user1}: "{user2} fez uma lista. Você tá no topo."
{user} disse a {user1}: "Se você cair, foi {user2}."
{user} disse a {user1}: "{user2} tá convencendo gente. Rápido."
{user} disse a {user1}: "Conversa com as pessoas antes de {user2}."
{user} disse a {user1}: "{user2} me pediu voto em você. Eu disse não."
{user} disse a {user1}: "{user2} quer sua cabeça. Literalmente."
{user} disse a {user1}: "Neutraliza {user2} antes que seja tarde."
{user} disse a {user1}: "{user2} tá liderando o coro. Te aviso."
{user} disse a {user1}: "Achei que você devia saber: {user2}."
{user} disse a {user1}: "Todo mundo que falou de você tinha falado com {user2}."
{user} disse a {user1}: "{user2} tá te usando de alvo pra se salvar."
{user} disse a {user1}: "Vi {user2} contando votos. O seu inclusive."
`);

export const APPROACH_WARNING_GENERIC = lines(`
{user} alertou {user1}: "Seu nome está rodando para a mesa de hoje."
{user} disse a {user1}: "Tão falando de você. Cuidado."
{user} cochichou: "{user1}, você tá na mira hoje."
{user} disse a {user1}: "Seu nome tá circulando. Se prepara."
{user} avisou {user1}: "Tem gente querendo votar em você."
{user} disse a {user1}: "A mesa tá pesada pro seu lado."
{user} cochichou: "Ouvi seu nome em três conversas."
{user} disse a {user1}: "Você precisa se defender hoje."
{user} alertou {user1}: "Tão te achando suspeito(a)."
{user} disse a {user1}: "O castelo tá olhando pra você."
{user} cochichou: "Seu nome não para de aparecer."
{user} disse a {user1}: "Cuidado na mesa. Você tá exposto(a)."
{user} avisou {user1}: "Tem votos indo pra você."
{user} disse a {user1}: "Você tá no topo das conversas. Não é bom."
{user} cochichou: "Te protege, {user1}. Tá difícil pra você."
{user} disse a {user1}: "Hoje pode ser seu dia. No sentido ruim."
{user} alertou {user1}: "Tão te colocando como suspeito(a) principal."
{user} disse a {user1}: "Você precisa de aliados hoje."
{user} cochichou: "O clima tá contra você."
{user} disse a {user1}: "Tem gente juntando voto em você."
{user} avisou {user1}: "Você tá sendo muito comentado(a)."
{user} disse a {user1}: "Se prepara pra se defender na mesa."
{user} cochichou: "Seu nome tá forte hoje."
{user} disse a {user1}: "Te cuida, tão falando de você."
{user} alertou {user1}: "A mesa pode virar contra você."
{user} disse a {user1}: "Você tá em perigo. Sério."
{user} cochichou: "Tão desconfiando de você, e muito."
{user} disse a {user1}: "Seu nome apareceu no café. E na missão."
{user} avisou {user1}: "Você é o assunto do dia. Infelizmente."
{user} disse a {user1}: "Tem gente armando contra você."
{user} cochichou: "Você precisa reagir antes da mesa."
{user} disse a {user1}: "Tão te olhando torto."
{user} alertou {user1}: "Seu nome tá na lista de muita gente."
{user} disse a {user1}: "A pressão tá em você hoje."
{user} cochichou: "Ouvi gente dizendo que vai votar em você."
{user} disse a {user1}: "Te protege, que a coisa tá feia."
{user} avisou {user1}: "Você tá na berlinda."
{user} disse a {user1}: "Tem uma onda contra você."
{user} cochichou: "Seu nome tá no ar, e não é elogio."
{user} disse a {user1}: "Hoje você precisa brilhar na defesa."
{user} alertou {user1}: "Tão te colocando como Traidor(a)."
{user} disse a {user1}: "Você tá correndo risco."
{user} cochichou: "A mesa tá se virando pra você."
{user} disse a {user1}: "Te cuida, {user1}."
{user} avisou {user1}: "Seu nome tá rondando todas as rodas."
{user} disse a {user1}: "Você precisa conversar com mais gente hoje."
{user} cochichou: "Tão falando mal de você por aí."
{user} disse a {user1}: "A coisa tá complicada pra você."
{user} alertou {user1}: "Você pode ser o nome de hoje."
{user} disse a {user1}: "Se cuida na mesa, é sério."
{user} cochichou: "Te protege, que tem gente te caçando."
{user} disse a {user1}: "Seu nome virou tema."
{user} avisou {user1}: "Tem votos se formando contra você."
{user} disse a {user1}: "Você tá sendo muito visado(a)."
{user} cochichou: "Não baixa a guarda hoje."
{user} disse a {user1}: "A maré tá contra você."
{user} alertou {user1}: "Tão te achando o(a) mais suspeito(a)."
{user} disse a {user1}: "Você precisa agir hoje."
{user} cochichou: "Ouvi coisas sobre você que não gostei."
{user} disse a {user1}: "Seu nome tá em alta. E não é bom."
{user} avisou {user1}: "Você tá na mira da mesa."
{user} disse a {user1}: "Tem gente convencida de que é você."
{user} cochichou: "A conversa tá toda em cima de você."
{user} disse a {user1}: "Se prepara pra hoje."
{user} alertou {user1}: "Você tá correndo perigo de verdade."
{user} disse a {user1}: "O castelo tá contra você hoje."
{user} cochichou: "Tão te citando como suspeito(a)."
{user} disse a {user1}: "Você precisa se mexer."
{user} avisou {user1}: "Seu nome tá rodando, fica esperto(a)."
{user} disse a {user1}: "A mesa tá inclinada pra você."
{user} cochichou: "Te cuida, sério."
{user} disse a {user1}: "Você é o nome mais falado hoje."
{user} alertou {user1}: "Tão te desenhando como Traidor(a)."
{user} disse a {user1}: "A pressão tá toda em você."
{user} cochichou: "Ouvi seu nome no jardim, na biblioteca..."
{user} disse a {user1}: "Você tá em risco hoje."
{user} avisou {user1}: "Tem uma corrente contra você."
{user} disse a {user1}: "Se defende bem na mesa."
{user} cochichou: "O clima pesou pro seu lado."
{user} disse a {user1}: "Você precisa de apoio hoje."
{user} alertou {user1}: "Seu nome tá na ponta da língua de muitos."
{user} disse a {user1}: "Tão armando pra você."
{user} cochichou: "Te protege, {user1}, que a coisa tá feia."
{user} disse a {user1}: "Você tá sendo o alvo da vez."
{user} avisou {user1}: "Tem voto indo pra você, e não é pouco."
{user} disse a {user1}: "A mesa hoje é sobre você."
{user} cochichou: "Tão desconfiando de você de verdade."
{user} disse a {user1}: "Seu nome tá forte nas conversas."
{user} alertou {user1}: "Você precisa ficar atento(a)."
{user} disse a {user1}: "Te cuida, a mesa não perdoa."
{user} cochichou: "Ouvi gente combinando voto em você."
{user} disse a {user1}: "Você tá sob pressão hoje."
{user} avisou {user1}: "O castelo tá te olhando."
{user} disse a {user1}: "Você precisa virar esse jogo."
{user} cochichou: "Seu nome tá circulando demais."
{user} disse a {user1}: "Hoje você precisa de sorte."
{user} alertou {user1}: "Tão te colocando no centro."
{user} disse a {user1}: "Você tá no radar de todo mundo."
{user} cochichou: "Te cuida, que tá difícil."
{user} disse a {user1}: "A mesa vai ser dura com você."
{user} avisou {user1}: "Seu nome tá em todas as bocas."
{user} disse a {user1}: "Você tá correndo risco sério."
{user} cochichou: "O vento tá contra você."
{user} disse a {user1}: "Se prepara, {user1}."
{user} alertou {user1}: "Tão juntando votos pra você."
{user} disse a {user1}: "Você precisa se defender com força."
{user} cochichou: "Ouvi que você é o nome de hoje."
{user} disse a {user1}: "Te protege, que a coisa tá ruim."
{user} avisou {user1}: "Você tá sendo muito comentado(a), e mal."
{user} disse a {user1}: "A mesa tá mirando você."
{user} cochichou: "Te cuida, que hoje é complicado."
{user} disse a {user1}: "Seu nome tá forte, e não é bom."
{user} alertou {user1}: "Você pode sair hoje, se não reagir."
{user} disse a {user1}: "Tem gente convencida contra você."
{user} cochichou: "O castelo tá virando contra você."
{user} disse a {user1}: "Você precisa agir antes da mesa."
{user} avisou {user1}: "Seu nome tá circulando, e rápido."
{user} disse a {user1}: "Te cuida na mesa."
{user} cochichou: "Tão falando que é você."
{user} disse a {user1}: "Você tá na berlinda hoje."
{user} alertou {user1}: "A mesa tá pesada pra você."
{user} disse a {user1}: "Se defende, que você tá em risco."
{user} cochichou: "Ouvi seu nome em todo canto."
{user} disse a {user1}: "Você precisa de aliados urgente."
{user} avisou {user1}: "Tem gente armando voto em você."
{user} disse a {user1}: "Te protege, {user1}."
{user} cochichou: "Seu nome tá no centro das atenções."
{user} disse a {user1}: "A coisa tá feia pra você hoje."
{user} alertou {user1}: "Tão te vendo como suspeito(a) número um."
{user} disse a {user1}: "Você precisa se mexer hoje."
{user} cochichou: "Te cuida, sério mesmo."
{user} disse a {user1}: "Você tá sendo muito visado(a) hoje."
{user} avisou {user1}: "Seu nome tá forte na mesa."
{user} disse a {user1}: "Se prepara pra se defender."
{user} cochichou: "O clima tá todo contra você."
{user} disse a {user1}: "Você corre perigo hoje."
{user} alertou {user1}: "Tão armando contra você."
{user} disse a {user1}: "A mesa tá de olho em você."
{user} cochichou: "Te protege, que tá difícil."
{user} disse a {user1}: "Você é o assunto da mesa."
{user} avisou {user1}: "Tem votos contra você se formando."
{user} disse a {user1}: "Te cuida, {user1}, sério."
{user} cochichou: "Seu nome tá em todas as conversas."
{user} disse a {user1}: "Você precisa reagir já."
{user} alertou {user1}: "A maré virou contra você."
{user} disse a {user1}: "Se defende, que a mesa tá contra."
{user} cochichou: "Ouvi que vão votar em você."
{user} disse a {user1}: "Você tá na mira, cuidado."
{user} avisou {user1}: "Seu nome tá forte, se prepara."
{user} disse a {user1}: "Te protege, a coisa tá pesada."
{user} cochichou: "O castelo tá falando de você."
{user} disse a {user1}: "Você precisa de defesa hoje."
{user} alertou {user1}: "Tão te colocando contra a parede."
{user} disse a {user1}: "A mesa tá difícil pra você."
{user} cochichou: "Te cuida, que tá feio."
{user} disse a {user1}: "Você tá sendo muito falado(a)."
{user} avisou {user1}: "Seu nome tá rodando pra hoje."
{user} disse a {user1}: "Se prepara bem, {user1}."
{user} cochichou: "O clima pesou contra você."
{user} disse a {user1}: "Você tá correndo risco hoje."
{user} alertou {user1}: "Tem gente fechando voto em você."
{user} disse a {user1}: "Te cuida na mesa de hoje."
{user} cochichou: "Seu nome tá circulando, não é boato."
{user} disse a {user1}: "Você precisa agir."
{user} avisou {user1}: "A mesa tá toda sobre você."
{user} disse a {user1}: "Se defende com tudo hoje."
{user} cochichou: "Te protege, sério."
{user} disse a {user1}: "Você tá no centro do furacão."
{user} alertou {user1}: "Tão te vendo como alvo."
{user} disse a {user1}: "A coisa tá ruim pra você, se cuida."
{user} cochichou: "Ouvi seu nome demais hoje."
{user} disse a {user1}: "Você precisa reagir antes que seja tarde."
{user} avisou {user1}: "Seu nome tá pesado na mesa."
{user} disse a {user1}: "Te cuida, é sério."
{user} cochichou: "O castelo tá contra você hoje."
{user} disse a {user1}: "Você tá na mira de verdade."
{user} alertou {user1}: "Se prepara, a mesa vem aí."
{user} disse a {user1}: "Te protege, {user1}, tá feio."
{user} cochichou: "Seu nome tá sendo muito falado."
{user} disse a {user1}: "Você corre risco hoje, se cuida."
{user} avisou {user1}: "Tão juntando votos contra você, cuidado."
{user} disse a {user1}: "Ouvi seu nome no corredor. Não era bom."
{user} disse a {user1}: "Toma cuidado com o que fala hoje."
{user} disse a {user1}: "Tem gente contando voto em você."
{user} cochichou para {user1}: "Se prepara. Vão pra cima de você."
{user} disse a {user1}: "Seu nome tá circulando. Muito."
{user} avisou {user1}: "Não me pergunta como, mas você tá em perigo."
{user} disse a {user1}: "Você anda sendo comentado(a). Fica esperto(a)."
{user} disse a {user1}: "Tem um grupo querendo te tirar."
{user} disse a {user1}: "Arruma uma defesa boa. Vai precisar."
{user} disse a {user1}: "O clima virou contra você. Cuidado."
{user} disse a {user1}: "Eu não voto em você. Mas muitos vão."
{user} disse a {user1}: "Tô te avisando porque gosto de você."
{user} disse a {user1}: "Fala com as pessoas hoje. Você tá na berlinda."
{user} disse a {user1}: "Seu nome virou assunto no quarto."
{user} disse a {user1}: "Hoje não é dia de provocar ninguém, ok?"
{user} disse a {user1}: "Te colocaram na lista. Não sei quem começou."
{user} disse a {user1}: "Olha, tô com um pressentimento ruim pra você."
{user} disse a {user1}: "Se precisar de ajuda, tô aqui. Você vai precisar."
{user} disse a {user1}: "Anda circulando que você é suspeito(a)."
`);
