import { lines } from './lines';

/** {user} = quem vem falar, {user1} = jogador, {user2} = outra pessoa citada. */

export const APPROACH_SUSPICION = lines(`
{user} baixou a voz com {user1}: "Eu acho que é {user2}. E você?"
{user} perguntou a {user1}: "Você também reparou em {user2}?"
{user} confessou a {user1}: "Meu voto hoje é {user2}."
{user} cochichou com {user1}: "{user2} mente muito bem. Muito bem."
{user} disse a {user1}: "Não tiro o olho de {user2}."
{user} disse a {user1}: "{user2} tá estranho(a) desde ontem."
{user} cochichou: "{user1}, {user2} me dá arrepio."
{user} disse a {user1}: "Viu a cara de {user2} no café?"
{user} disse a {user1}: "{user2} sabia da morte antes. Aposto."
{user} disse a {user1}: "Eu vi {user2} no corredor de madrugada."
{user} disse a {user1}: "{user2} tem resposta pra tudo. Suspeito."
{user} disse a {user1}: "{user2} é calmo(a) demais."
{user} disse a {user1}: "Olha como {user2} vota. Sempre em Fiel."
{user} disse a {user1}: "{user2} muda de lado toda hora."
{user} cochichou: "{user2} tem cara de capa preta."
{user} disse a {user1}: "Eu apostaria em {user2}."
{user} disse a {user1}: "{user2} ri na hora errada."
{user} disse a {user1}: "{user2} tá sempre perto de quem morre."
{user} disse a {user1}: "{user2} desvia o olhar quando falam da torre."
{user} disse a {user1}: "Sabe quem eu não engulo? {user2}."
{user} disse a {user1}: "{user2} tá manipulando a mesa."
{user} cochichou: "{user2} não chorou por ninguém."
{user} disse a {user1}: "{user2} tá protegendo alguém. Quem?"
{user} disse a {user1}: "{user2} fala demais de lealdade."
{user} disse a {user1}: "{user2} me olhou estranho hoje."
{user} disse a {user1}: "{user2} faz perguntas demais."
{user} disse a {user1}: "Você confia em {user2}? Eu não."
{user} cochichou: "{user2} tá rindo da gente, eu sinto."
{user} disse a {user1}: "{user2} é o nome que não sai da minha cabeça."
{user} disse a {user1}: "Vamos ficar de olho em {user2} juntos?"
{user} disse a {user1}: "{user2} mentiu pra mim, tenho certeza."
{user} disse a {user1}: "{user2} tá sempre um passo à frente."
{user} disse a {user1}: "{user2} evita ficar sozinho(a) com Fiel."
{user} cochichou: "{user2} tá blefando o tempo todo."
{user} disse a {user1}: "{user2} tem um jogo muito calculado."
{user} disse a {user1}: "{user2} tá seguro(a) demais pra quem tá em risco."
{user} disse a {user1}: "{user2} fingiu surpresa, eu vi."
{user} disse a {user1}: "{user2} tem um sorriso que não convence."
{user} cochichou: "{user2} tá guiando os votos."
{user} disse a {user1}: "{user2} some nas horas difíceis."
{user} disse a {user1}: "{user2} tem ligação com quem saiu Traidor."
{user} disse a {user1}: "{user2} tá tranquilo(a) demais depois das mortes."
{user} disse a {user1}: "Vou votar em {user2}. Vem comigo?"
{user} cochichou: "{user2} é bom(boa) demais nesse jogo."
{user} disse a {user1}: "{user2} tá sempre com a resposta pronta."
{user} disse a {user1}: "{user2} tá escondendo algo."
{user} disse a {user1}: "{user2} é frio(a) demais."
{user} disse a {user1}: "{user2} olhou pra torre ontem."
{user} cochichou: "{user2} tá jogando dos dois lados."
{user} disse a {user1}: "{user2} tem pose de inocente. Só pose."
{user} disse a {user1}: "{user2} nunca acusa ninguém. Estranho."
{user} disse a {user1}: "{user2} é o nome da minha lista."
{user} disse a {user1}: "{user2} tá sempre bem informado(a)."
{user} cochichou: "{user2} tá cercando as pessoas certas."
{user} disse a {user1}: "Você não acha {user2} esquisito(a)?"
{user} disse a {user1}: "{user2} tá tramando algo."
{user} disse a {user1}: "{user2} vota sempre no último segundo."
{user} disse a {user1}: "{user2} jogou alguém embaixo do ônibus."
{user} cochichou: "{user2} tá com medo de ser pego(a)."
{user} disse a {user1}: "{user2} tem a paciência de quem sabe o final."
{user} disse a {user1}: "{user2} fala baixo quando o assunto é voto."
{user} disse a {user1}: "Tô com {user2} atravessado(a)."
{user} disse a {user1}: "{user2} é muito calculista."
{user} cochichou: "{user2} escolhe as palavras com cuidado demais."
{user} disse a {user1}: "{user2} tá sempre perto do perigo."
{user} disse a {user1}: "{user2} quer parecer útil demais."
{user} disse a {user1}: "{user2} é o(a) mais perigoso(a) daqui."
{user} disse a {user1}: "Meu faro diz {user2}."
{user} cochichou: "{user2} tá sorrindo demais ultimamente."
{user} disse a {user1}: "{user2} tem cara de quem sobe a escada."
{user} disse a {user1}: "{user2} tá fazendo o jogo da torre."
{user} disse a {user1}: "{user2} anda cochichando demais."
{user} disse a {user1}: "{user2} tem um segredo, eu sinto."
{user} cochichou: "{user2} sempre sobrevive. Por quê?"
{user} disse a {user1}: "{user2} me evita desde ontem."
{user} disse a {user1}: "{user2} tá desviando atenção."
{user} disse a {user1}: "{user2} tem um olhar de raposa."
{user} disse a {user1}: "{user2} tá blindado(a) demais."
{user} cochichou: "{user2} fala comigo como quem esconde algo."
{user} disse a {user1}: "{user2} tá sempre no lugar certo na hora certa."
{user} disse a {user1}: "{user2} nunca vota em quem sai Traidor."
{user} disse a {user1}: "{user2} tem a frieza que Traidor precisa."
{user} disse a {user1}: "Você viu como {user2} reagiu à notícia?"
{user} cochichou: "{user2} tá brincando com a gente."
{user} disse a {user1}: "{user2} tem a cara mais lavada do castelo."
{user} disse a {user1}: "{user2} tá protegido(a) por alguém."
{user} disse a {user1}: "{user2} parece esconder a capa no armário."
{user} disse a {user1}: "{user2} tá rindo por dentro."
{user} cochichou: "{user2} manipula com sorriso."
{user} disse a {user1}: "{user2} é o meu mistério favorito."
{user} disse a {user1}: "{user2} tá aproveitando a confusão."
{user} disse a {user1}: "{user2} tá desconfiado(a) de todo mundo. Menos dos Traidores."
{user} disse a {user1}: "{user2} tem uma energia estranha."
{user} cochichou: "{user2} fingiu tristeza, eu vi."
{user} disse a {user1}: "{user2} é o elo que falta."
{user} disse a {user1}: "{user2} tá sempre de olho na escada."
{user} disse a {user1}: "{user2} tem um jogo sujo."
{user} disse a {user1}: "{user2} tá afiando a adaga, aposto."
{user} cochichou: "{user2} tá com a consciência pesada."
{user} disse a {user1}: "{user2} vota com a cabeça, não com o coração."
{user} disse a {user1}: "{user2} tá sempre sabendo demais."
{user} disse a {user1}: "{user2} tá brincando de Fiel."
{user} disse a {user1}: "{user2} não me passa verdade."
{user} cochichou: "{user2} tem cara de quem guarda segredo."
{user} disse a {user1}: "{user2} tá desviando das perguntas."
{user} disse a {user1}: "{user2} é bom(boa) em se fazer de vítima."
{user} disse a {user1}: "{user2} tá nos enganando, eu acho."
{user} disse a {user1}: "Anota esse nome: {user2}."
{user} cochichou: "{user2} tá agindo estranho."
{user} disse a {user1}: "{user2} tem algo errado."
{user} disse a {user1}: "{user2} fica quieto(a) na hora certa."
{user} disse a {user1}: "{user2} é o(a) suspeito(a) mais quieto(a)."
{user} disse a {user1}: "{user2} tá sempre calmo(a). Calmo(a) demais."
{user} cochichou: "{user2} fala uma coisa e faz outra."
{user} disse a {user1}: "{user2} tem uma calma que assusta."
{user} disse a {user1}: "{user2} tá sempre perto das decisões."
{user} disse a {user1}: "{user2} não me convence."
{user} disse a {user1}: "{user2} tem um olhar calculista."
{user} cochichou: "{user2} tá sendo protegido(a) demais."
{user} disse a {user1}: "Eu desconfio de {user2}, e você?"
{user} disse a {user1}: "{user2} tá sempre bem na foto."
{user} disse a {user1}: "{user2} tem resposta ensaiada."
{user} disse a {user1}: "{user2} tá sempre seguro(a)."
{user} cochichou: "{user2} fala de todos, menos de si."
{user} disse a {user1}: "{user2} some quando o assunto esquenta."
{user} disse a {user1}: "{user2} é bom(boa) de teatro."
{user} disse a {user1}: "{user2} tá sempre tranquilo(a) nas mortes."
{user} disse a {user1}: "{user2} tá no meu radar há dias."
{user} cochichou: "{user2} tá rondando demais."
{user} disse a {user1}: "{user2} tem um jeito que não me agrada."
{user} disse a {user1}: "{user2} é muito certinho(a) pra ser verdade."
{user} disse a {user1}: "{user2} tá sempre defendendo quem não devia."
{user} disse a {user1}: "{user2} tem um plano, e não é de Fiel."
{user} cochichou: "{user2} tá sempre sorrindo pros Traidores. Quer dizer, pros suspeitos."
{user} disse a {user1}: "{user2} tá muito à vontade aqui."
{user} disse a {user1}: "{user2} é o(a) mais difícil de ler."
{user} disse a {user1}: "{user2} tá sempre um pouco longe."
{user} disse a {user1}: "{user2} tá com a cabeça na torre, aposto."
{user} cochichou: "{user2} tem cara de quem trai."
{user} disse a {user1}: "{user2} vive dizendo que é Fiel. Demais."
{user} disse a {user1}: "{user2} tá sempre perto de mim. Por quê?"
{user} disse a {user1}: "{user2} olha pra todo mundo como quem escolhe."
{user} disse a {user1}: "{user2} é o nome que eu não falei na mesa."
{user} cochichou: "{user2} tá se escondendo atrás de alguém."
{user} disse a {user1}: "{user2} tá sempre com uma carta na manga."
{user} disse a {user1}: "{user2} tem um sangue frio que me assusta."
{user} disse a {user1}: "{user2} parece saber o final da história."
{user} disse a {user1}: "Você viu {user2} ontem? Estranhíssimo(a)."
{user} cochichou: "{user2} tá sempre no meio das intrigas."
{user} disse a {user1}: "{user2} é o(a) mais misterioso(a)."
{user} disse a {user1}: "{user2} tá contra alguém, mas não diz quem."
{user} disse a {user1}: "{user2} evita as perguntas certas."
{user} disse a {user1}: "{user2} tem uma frieza estranha."
{user} cochichou: "{user2} tá sempre com a pose certa."
{user} disse a {user1}: "{user2} parece jogar pra torre."
{user} disse a {user1}: "{user2} tem cara de raposa."
{user} disse a {user1}: "{user2} tá sempre sem culpa. Estranho."
{user} disse a {user1}: "{user2} fala muito e não diz nada."
{user} cochichou: "{user2} me dá frio na espinha."
{user} disse a {user1}: "{user2} tá sempre em cima do muro."
{user} disse a {user1}: "{user2} é o(a) Traidor(a) perfeito(a). Pensa."
{user} disse a {user1}: "{user2} tá nos observando demais."
{user} disse a {user1}: "{user2} parece contar os votos antes."
{user} cochichou: "{user2} tá com um brilho estranho no olhar."
{user} disse a {user1}: "{user2} é o(a) mais estranho(a) daqui."
{user} disse a {user1}: "{user2} tá sempre desviando."
{user} disse a {user1}: "{user2} tem um segredo pesado."
{user} disse a {user1}: "{user2} é suspeito(a) pra mim."
{user} cochichou: "{user2} tá se fazendo de bobo(a)."
{user} disse a {user1}: "{user2} age igual Traidor de temporada passada."
{user} disse a {user1}: "{user2} tá sempre sabendo quem vai morrer."
{user} disse a {user1}: "{user2} tem uma calma ensaiada."
{user} disse a {user1}: "{user2} é o nome de hoje, pra mim."
{user} cochichou: "{user2} tá tentando parecer inofensivo(a)."
{user} disse a {user1}: "{user2} tá sempre com a guarda alta."
{user} disse a {user1}: "{user2} parece esperar a noite."
{user} disse a {user1}: "{user2} tá fingindo, eu sinto."
{user} disse a {user1}: "{user2} é bom(boa) em mentir, eu acho."
{user} cochichou: "{user2} tá sempre um pouco culpado(a) no olhar."
{user} disse a {user1}: "{user2} tem o voto mais estranho da mesa."
{user} disse a {user1}: "{user2} tá sempre protegendo os mesmos."
{user} disse a {user1}: "{user2} é o elo com a torre."
{user} disse a {user1}: "{user2} tá sempre se esquivando."
{user} cochichou: "{user2} é meu voto, e queria que fosse o seu."
{user} disse a {user1}: "{user2} tá ganhando tempo."
{user} disse a {user1}: "{user2} tem um olhar que esconde."
{user} disse a {user1}: "{user2} tá sempre de olho nos outros."
{user} disse a {user1}: "{user2} parece contar segredos com os olhos."
{user} cochichou: "{user2} tá sempre um tom abaixo. Suspeito."
{user} disse a {user1}: "{user2} tem ar de culpa."
{user} disse a {user1}: "{user2} tá sempre bem na hora certa."
{user} disse a {user1}: "{user2} parece ter uma aliança secreta."
{user} disse a {user1}: "{user2} é o(a) que eu mais vigio."
{user} cochichou: "{user2} tá fazendo teatro, confia."
{user} disse a {user1}: "{user2} mudou de história duas vezes."
{user} cochichou: "{user1}, {user2} tá calmo(a) demais."
{user} disse a {user1}: "Não consigo tirar {user2} da cabeça."
{user} disse a {user1}: "{user2} some bem na hora das conversas."
{user} disse a {user1}: "Tem algo em {user2} que não fecha."
{user} disse a {user1}: "Olha como {user2} se defende. Exagerado(a)."
{user} disse a {user1}: "{user2} sabe coisas que não devia saber."
{user} disse a {user1}: "Se não for {user2}, eu erro feio."
{user} disse a {user1}: "Me ajuda a observar {user2} hoje?"
`);

export const APPROACH_AGREE = lines(`
{user} disse a {user1}: "Você tem razão sobre {user2}. Tô contigo."
{user} procurou {user1}: "Pensei no que você disse de {user2}. Faz sentido."
{user} disse a {user1}: "Você viu primeiro. {user2} é suspeito(a)."
{user} disse a {user1}: "Depois do que você falou, eu vi {user2} diferente."
{user} disse a {user1}: "Você acertou em {user2}, eu acho."
{user} cochichou: "{user1}, eu também desconfio de {user2} agora."
{user} disse a {user1}: "Vou votar com você em {user2}."
{user} disse a {user1}: "Você me convenceu sobre {user2}."
{user} disse a {user1}: "Eu reparei em {user2}, como você disse."
{user} disse a {user1}: "{user2}? Você tava certo(a)."
{user} disse a {user1}: "Seu olho é bom. {user2} tá estranho(a)."
{user} disse a {user1}: "Tô do seu lado contra {user2}."
{user} disse a {user1}: "Você acusou {user2} e eu fiquei pensando. Faz sentido."
{user} disse a {user1}: "Eu vi o que você viu em {user2}."
{user} cochichou: "{user2} tá mesmo escondendo algo, você tinha razão."
{user} disse a {user1}: "Seu palpite sobre {user2} me pegou."
{user} disse a {user1}: "Vamos juntos contra {user2}?"
{user} disse a {user1}: "Eu vou te apoiar sobre {user2}."
{user} disse a {user1}: "Você falou de {user2} e tudo encaixou."
{user} disse a {user1}: "Concordo com você sobre {user2}. Totalmente."
{user} cochichou: "Você tá certo(a) sobre {user2}."
{user} disse a {user1}: "Depois da sua fala, {user2} ficou na minha lista."
{user} disse a {user1}: "Você me abriu os olhos pra {user2}."
{user} disse a {user1}: "Eu confio no seu faro. {user2}."
{user} disse a {user1}: "Seu voto em {user2} é o meu também."
{user} disse a {user1}: "Você tem coragem de falar de {user2}. Admiro."
{user} cochichou: "Tô contigo, {user2} vai cair."
{user} disse a {user1}: "Você viu o jogo de {user2} antes de todos."
{user} disse a {user1}: "Eu fiquei com a pulga depois do que você disse de {user2}."
{user} disse a {user1}: "Você e eu pensamos igual sobre {user2}."
{user} disse a {user1}: "Eu vou falar de {user2} na mesa também."
{user} disse a {user1}: "Você não tá sozinho(a) contra {user2}."
{user} cochichou: "Eu te ouvi falando de {user2}. Concordo."
{user} disse a {user1}: "Você acertou em cheio com {user2}."
{user} disse a {user1}: "Tô de olho em {user2}, como você pediu."
{user} disse a {user1}: "Seu argumento sobre {user2} me convenceu."
{user} disse a {user1}: "Você é esperto(a). {user2} é suspeito(a) mesmo."
{user} disse a {user1}: "Vamos juntos tirar {user2}."
{user} cochichou: "Você tinha razão, {user2} tá estranho(a)."
{user} disse a {user1}: "Eu apoio sua acusação a {user2}."
{user} disse a {user1}: "Depois de você, eu comecei a reparar em {user2}."
{user} disse a {user1}: "Você me fez desconfiar de {user2}. Obrigado(a)."
{user} disse a {user1}: "Eu tô com você sobre {user2}."
{user} disse a {user1}: "{user2} tá no meu voto também, graças a você."
{user} cochichou: "Você viu certo em {user2}."
{user} disse a {user1}: "Eu vou seguir seu palpite em {user2}."
{user} disse a {user1}: "Você e eu, contra {user2}."
{user} disse a {user1}: "Você não tá louco(a). {user2} é estranho(a)."
{user} disse a {user1}: "Eu concordo com cada palavra sobre {user2}."
{user} disse a {user1}: "Você me convenceu, e eu vou espalhar sobre {user2}."
{user} cochichou: "Tô com você na mesa contra {user2}."
{user} disse a {user1}: "Você tá certíssimo(a) sobre {user2}."
{user} disse a {user1}: "Eu vi {user2} fazer o que você disse."
{user} disse a {user1}: "Você acertou, {user2} tá mentindo."
{user} disse a {user1}: "Eu vou te ajudar a provar sobre {user2}."
{user} disse a {user1}: "Seu instinto sobre {user2} é certeiro."
{user} cochichou: "Você tem meu voto contra {user2}."
{user} disse a {user1}: "Depois do que você disse, {user2} me assusta."
{user} disse a {user1}: "Você me ganhou sobre {user2}."
{user} disse a {user1}: "Eu tô com você, {user2} é o nome."
{user} disse a {user1}: "Você tinha razão, e eu demorei a ver."
{user} disse a {user1}: "Vou votar em {user2}, você me convenceu."
{user} cochichou: "Você acertou em {user2}. Vamos juntos."
{user} disse a {user1}: "Eu reparei, {user2} tá igual você falou."
{user} disse a {user1}: "Você abriu meus olhos."
{user} disse a {user1}: "{user2} é suspeito(a), como você disse."
{user} disse a {user1}: "Eu tô do seu lado nessa acusação."
{user} disse a {user1}: "Você tem razão, e eu vou falar isso na mesa."
{user} cochichou: "Tô contigo, {user1}. {user2}."
{user} disse a {user1}: "Seu olhar sobre {user2} é certo."
{user} disse a {user1}: "Você viu o que ninguém viu em {user2}."
{user} disse a {user1}: "Eu concordo, {user2} tá jogando sujo."
{user} disse a {user1}: "Você me convenceu, e rápido."
{user} disse a {user1}: "Eu vou votar com você. {user2}."
{user} cochichou: "Você tá certo(a), eu senti o mesmo."
{user} disse a {user1}: "{user2} tá do jeito que você falou."
{user} disse a {user1}: "Você me fez ver {user2} de verdade."
{user} disse a {user1}: "Eu tô contigo nessa, até o fim."
{user} disse a {user1}: "Você é o(a) único(a) que teve coragem de falar de {user2}."
{user} disse a {user1}: "Eu concordo, e vou juntar votos."
{user} cochichou: "Seu palpite sobre {user2} faz todo sentido."
{user} disse a {user1}: "Você acertou, e eu tô com você."
{user} disse a {user1}: "{user2} tá sendo desmascarado(a) por você."
{user} disse a {user1}: "Eu vi a mesma coisa em {user2}."
{user} disse a {user1}: "Você me convenceu de vez."
{user} disse a {user1}: "Tô com você, e com a mesa se precisar."
{user} cochichou: "Você tá certo(a) sobre {user2}, eu acho."
{user} disse a {user1}: "Seu voto é o meu voto: {user2}."
{user} disse a {user1}: "Você tem razão, e isso me assusta."
{user} disse a {user1}: "Eu vou te apoiar na mesa contra {user2}."
{user} disse a {user1}: "Você viu primeiro, e eu vi depois."
{user} disse a {user1}: "Concordo, {user2} tá suspeito(a)."
{user} cochichou: "Você me deixou convencido(a) sobre {user2}."
{user} disse a {user1}: "Eu vou falar de {user2} com mais gente."
{user} disse a {user1}: "Você tá no caminho certo."
{user} disse a {user1}: "Eu tô com você contra {user2}, sem dúvida."
{user} disse a {user1}: "Você tinha razão desde o começo."
{user} disse a {user1}: "Seu instinto é bom, {user1}."
{user} cochichou: "{user2} vai cair, e você tava certo(a)."
{user} disse a {user1}: "Eu vou te acompanhar contra {user2}."
{user} disse a {user1}: "Você me ajudou a ver {user2}."
{user} disse a {user1}: "Concordo, e vou votar assim."
{user} disse a {user1}: "Você tem um olho clínico."
{user} disse a {user1}: "Eu reparei em {user2} depois de você."
{user} cochichou: "Você tá certo(a), vamos juntos."
{user} disse a {user1}: "{user2}? Você acertou."
{user} disse a {user1}: "Eu apoio sua desconfiança."
{user} disse a {user1}: "Você me convenceu com calma."
{user} disse a {user1}: "Tô contigo, {user2} é o alvo."
{user} disse a {user1}: "Você tem razão, e eu confio em você."
{user} cochichou: "Seu palpite virou o meu."
{user} disse a {user1}: "Eu tô de olho em {user2} por sua causa."
{user} disse a {user1}: "Você acertou em cheio."
{user} disse a {user1}: "Concordo, {user2} é perigoso(a)."
{user} disse a {user1}: "Você me fez pensar direito."
{user} disse a {user1}: "Eu vou seguir você nessa."
{user} cochichou: "Você viu certo, {user1}."
{user} disse a {user1}: "Eu confio no que você disse de {user2}."
{user} disse a {user1}: "Você me ganhou com esse argumento."
{user} disse a {user1}: "Tô contigo contra {user2}, pode contar."
{user} disse a {user1}: "Você tá certo(a), e eu tô junto."
{user} disse a {user1}: "Eu concordo cem por cento."
{user} cochichou: "Seu olhar sobre {user2} me convenceu."
{user} disse a {user1}: "Você tinha razão, {user2} tá estranho(a)."
{user} disse a {user1}: "Eu vou votar em {user2} contigo."
{user} disse a {user1}: "Você é certeiro(a)."
{user} disse a {user1}: "Concordo com sua leitura de {user2}."
{user} disse a {user1}: "Você me fez desconfiar, e com razão."
{user} cochichou: "Tô contigo nessa, {user1}."
{user} disse a {user1}: "{user2} é suspeito(a). Você tava certo(a)."
{user} disse a {user1}: "Eu vou te ajudar com {user2}."
{user} disse a {user1}: "Você me abriu os olhos, obrigado(a)."
{user} disse a {user1}: "Concordo, e vou falar na mesa."
{user} disse a {user1}: "Você tem razão sobre {user2}, tô contigo."
{user} cochichou: "Eu senti o mesmo que você."
{user} disse a {user1}: "Seu voto em {user2} faz sentido."
{user} disse a {user1}: "Você acertou, e eu apoio."
{user} disse a {user1}: "Tô contigo, vamos derrubar {user2}."
{user} disse a {user1}: "Você me convenceu, sem dúvida."
{user} disse a {user1}: "Eu reparei em {user2}, você tinha razão."
{user} cochichou: "Você tá certo(a), e eu vou junto."
{user} disse a {user1}: "Concordo com você, {user2} é estranho(a)."
{user} disse a {user1}: "Você viu o que eu não vi."
{user} disse a {user1}: "Eu tô do seu lado nisso."
{user} disse a {user1}: "Você tem razão, vamos juntos contra {user2}."
{user} disse a {user1}: "Eu vou votar com você."
{user} cochichou: "Seu palpite é o melhor que ouvi."
{user} disse a {user1}: "Você acertou sobre {user2}, de verdade."
{user} disse a {user1}: "Eu concordo, e tô contigo."
{user} disse a {user1}: "Você me convenceu totalmente sobre {user2}."
{user} disse a {user1}: "Tô com você, {user1}."
{user} disse a {user1}: "Você tem razão, {user2} é o nome."
{user} cochichou: "Eu confio no seu instinto sobre {user2}."
{user} disse a {user1}: "Você viu, e agora eu vejo também."
{user} disse a {user1}: "Concordo, e vou votar em {user2}."
{user} disse a {user1}: "Você me fez reparar em {user2}."
{user} disse a {user1}: "Tô contigo nessa acusação."
{user} disse a {user1}: "Você tinha razão, eu fui lento(a)."
{user} cochichou: "Vamos juntos em {user2}, você tá certo(a)."
{user} disse a {user1}: "Eu apoio você contra {user2}."
{user} disse a {user1}: "Você acertou em {user2}, eu sinto."
{user} disse a {user1}: "Concordo com tudo que você disse."
{user} disse a {user1}: "Você me convenceu, e vou espalhar."
{user} disse a {user1}: "Eu tô com você sobre {user2}, sempre."
{user} cochichou: "Você tem razão, e eu sou testemunha."
{user} disse a {user1}: "{user2} tá na minha mira também."
{user} disse a {user1}: "Você me ajudou a enxergar."
{user} disse a {user1}: "Concordo, e vamos juntos."
{user} disse a {user1}: "Você tá certo(a), e eu vou te apoiar."
{user} disse a {user1}: "Eu vi {user2} como você disse."
{user} cochichou: "Você acertou, {user1}, e muito."
{user} disse a {user1}: "Tô contigo contra {user2}, com certeza."
{user} disse a {user1}: "Você me convenceu. Vou votar em {user2}."
{user} disse a {user1}: "Concordo, {user2} é o(a) suspeito(a)."
{user} disse a {user1}: "Você tem razão, e eu admito."
{user} disse a {user1}: "Eu apoio você na mesa."
{user} cochichou: "Seu palpite sobre {user2} é bom."
{user} disse a {user1}: "Você acertou, eu confio."
{user} disse a {user1}: "Tô com você, {user2} vai sair."
{user} disse a {user1}: "Você me fez ver claramente."
{user} disse a {user1}: "Concordo com você, e muito."
{user} disse a {user1}: "Você tá certo(a) sobre {user2}, e eu vou junto."
{user} cochichou: "Tô do seu lado, {user1}."
{user} disse a {user1}: "Você tinha razão, e agora eu sei."
{user} disse a {user1}: "Eu vou votar em {user2}, por você."
{user} disse a {user1}: "Você me convenceu de vez, {user1}."
{user} disse a {user1}: "Concordo, e tô junto até o fim."
{user} disse a {user1}: "Eu também tô de olho em {user2}. Somos dois."
{user} disse a {user1}: "Você plantou a dúvida de {user2} em mim."
{user} disse a {user1}: "Depois do que você disse, só vejo {user2}."
{user} disse a {user1}: "Assino embaixo: {user2}."
{user} disse a {user1}: "{user2} mentiu pra mim também. Tô contigo."
{user} disse a {user1}: "Vamos juntos em {user2}?"
{user} disse a {user1}: "Achei que era loucura minha, mas {user2}..."
{user} disse a {user1}: "Você não tá sozinho(a) nessa de {user2}."
{user} disse a {user1}: "Seu raciocínio sobre {user2} fecha."
{user} disse a {user1}: "Conversei com {user2} e senti o mesmo."
{user} disse a {user1}: "Me convenceu. {user2} tá estranho(a)."
{user} disse a {user1}: "Se você for em {user2}, eu vou junto."
{user} disse a {user1}: "Eu reparei em {user2} também. Muito."
{user} disse a {user1}: "Você e eu na mesma: {user2}."
{user} disse a {user1}: "Achei coerente o que você falou de {user2}."
{user} disse a {user1}: "Fico feliz que alguém mais viu {user2}."
`);

export const APPROACH_CONFRONT_VOTED = lines(`
{user} encarou {user1} no corredor: "Você escreveu meu nome. Eu vi."
{user} disse a {user1}: "Você votou em mim. Não esqueço."
{user} parou {user1}: "Por que meu nome, {user1}?"
{user} disse a {user1}: "Seu voto foi em mim. Vai explicar?"
{user} disse a {user1}: "Você votou em mim e ainda me olha na cara?"
{user} cruzou os braços: "Seu voto doeu, {user1}."
{user} disse a {user1}: "Você me votou. Guarda isso."
{user} disse a {user1}: "Eu vi seu voto. E vou lembrar."
{user} disse a {user1}: "Você escreveu meu nome. Por quê?"
{user} disse a {user1}: "Não esperava seu voto em mim."
{user} disse a {user1}: "Você me votou, e agora?"
{user} chamou {user1} num canto: "Me explica seu voto."
{user} disse a {user1}: "Você votou em mim, e isso tem consequência."
{user} disse a {user1}: "Seu voto me pegou de surpresa."
{user} disse a {user1}: "Você me escolheu. Eu vou te escolher também."
{user} disse a {user1}: "Eu não esqueço quem votou em mim."
{user} disse a {user1}: "Você votou em mim sem motivo."
{user} disse a {user1}: "Meu nome na sua mão. Que feio."
{user} disse a {user1}: "Você votou em mim, e tá sorrindo?"
{user} disse a {user1}: "Seu voto foi um recado. Entendi."
{user} disse a {user1}: "Você me votou, e eu achava que a gente era amigo."
{user} disse a {user1}: "Por que eu, {user1}? Me fala."
{user} disse a {user1}: "Você me votou e acha que eu não vi?"
{user} disse a {user1}: "Seu voto em mim foi um erro."
{user} disse a {user1}: "Você escreveu meu nome com essa mão?"
{user} disse a {user1}: "Vou lembrar disso na próxima mesa."
{user} disse a {user1}: "Você votou em mim. Agora é pessoal."
{user} disse a {user1}: "Seu voto me machucou, {user1}."
{user} disse a {user1}: "Você me escolheu, e eu não vou esquecer."
{user} disse a {user1}: "Me explica por que você me votou."
{user} disse a {user1}: "Você votou em mim, e isso diz muito."
{user} disse a {user1}: "Seu nome tá anotado. Por causa do voto."
{user} disse a {user1}: "Você me votou, e eu sou Fiel."
{user} disse a {user1}: "Seu voto foi baixo."
{user} disse a {user1}: "Você votou em mim, e eu te defendi antes."
{user} disse a {user1}: "Não achei que você teria coragem."
{user} disse a {user1}: "Você me votou, e vai ver o troco."
{user} disse a {user1}: "Seu voto em mim foi injusto."
{user} disse a {user1}: "Você escreveu meu nome e não me olhou."
{user} disse a {user1}: "Você me votou, e eu vou provar que errou."
{user} disse a {user1}: "Seu voto me mostrou quem você é."
{user} disse a {user1}: "Você votou em mim, e eu não te fiz nada."
{user} disse a {user1}: "Me votou por medo, né?"
{user} disse a {user1}: "Você me votou, e agora a gente conversa."
{user} disse a {user1}: "Seu voto foi uma facada."
{user} disse a {user1}: "Você votou em mim. Traidor faz isso."
{user} disse a {user1}: "Seu voto em mim foi estratégia ou raiva?"
{user} disse a {user1}: "Você me escolheu, e isso não passa."
{user} disse a {user1}: "Eu vi você escrevendo meu nome."
{user} disse a {user1}: "Você votou em mim, por quê?"
{user} disse a {user1}: "Seu voto não foi bonito."
{user} disse a {user1}: "Você me votou e ainda quer conversar?"
{user} disse a {user1}: "Seu voto em mim vai ter volta."
{user} disse a {user1}: "Você escreveu meu nome. Anotei o seu."
{user} disse a {user1}: "Você me votou, e eu não esqueço fácil."
{user} disse a {user1}: "Seu voto foi uma decepção."
{user} disse a {user1}: "Você votou em mim e foi o primeiro."
{user} disse a {user1}: "Eu sei que você votou em mim."
{user} disse a {user1}: "Seu voto em mim foi um tiro no pé."
{user} disse a {user1}: "Você me votou, e agora eu te vigio."
{user} disse a {user1}: "Seu voto foi a coisa mais baixa de ontem."
{user} disse a {user1}: "Você votou em mim, e isso muda tudo."
{user} disse a {user1}: "Me votar foi sua escolha. A minha vem agora."
{user} disse a {user1}: "Você escreveu meu nome e dormiu bem?"
{user} disse a {user1}: "Seu voto em mim foi pessoal, eu sei."
{user} disse a {user1}: "Você me votou, e eu vou te lembrar disso."
{user} disse a {user1}: "Seu voto não foi esquecido."
{user} disse a {user1}: "Você votou em mim, e vai se arrepender."
{user} disse a {user1}: "Seu voto foi claro. O meu também vai ser."
{user} disse a {user1}: "Você me votou, e isso me fez pensar."
{user} disse a {user1}: "Seu voto em mim foi covarde."
{user} disse a {user1}: "Você escreveu meu nome. Coragem, hein?"
{user} disse a {user1}: "Você me votou, e a gente precisa conversar."
{user} disse a {user1}: "Seu voto foi um aviso. Recebido."
{user} disse a {user1}: "Você votou em mim e agora quer paz?"
{user} disse a {user1}: "Seu voto me deixou triste."
{user} disse a {user1}: "Você me votou, e eu te respeitava."
{user} disse a {user1}: "Seu voto em mim foi um erro de cálculo."
{user} disse a {user1}: "Você escreveu meu nome e eu escrevo o seu."
{user} disse a {user1}: "Você me votou, e eu vi sua cara."
{user} disse a {user1}: "Seu voto não vai ficar barato."
{user} disse a {user1}: "Você votou em mim. Sabe o que isso significa?"
{user} disse a {user1}: "Seu voto em mim foi injustíssimo."
{user} disse a {user1}: "Você me escolheu, eu lembro."
{user} disse a {user1}: "Seu voto foi a gota d'água."
{user} disse a {user1}: "Você votou em mim, e eu não te perdoo."
{user} disse a {user1}: "Seu voto em mim foi uma traição."
{user} disse a {user1}: "Você escreveu meu nome com calma. Assustador."
{user} disse a {user1}: "Você me votou, e agora a gente é rival."
{user} disse a {user1}: "Seu voto me deixou alerta."
{user} disse a {user1}: "Você votou em mim, e isso ficou marcado."
{user} disse a {user1}: "Seu voto em mim foi sem sentido."
{user} disse a {user1}: "Você me votou. Explica, que eu escuto."
{user} disse a {user1}: "Seu voto foi um ataque."
{user} disse a {user1}: "Você escreveu meu nome e fingiu que não."
{user} disse a {user1}: "Você me votou, e eu tô de olho."
{user} disse a {user1}: "Seu voto me fez perder a confiança."
{user} disse a {user1}: "Você votou em mim, não esquece que eu sei."
{user} disse a {user1}: "Seu voto em mim foi pesado."
{user} disse a {user1}: "Você me escolheu, e agora eu te escolho."
{user} disse a {user1}: "Seu voto foi uma surpresa ruim."
{user} disse a {user1}: "Você votou em mim, e vai ter que conviver com isso."
{user} disse a {user1}: "Seu voto em mim me deu raiva."
{user} disse a {user1}: "Você escreveu meu nome, e foi feio."
{user} disse a {user1}: "Você me votou, e isso tem preço."
{user} disse a {user1}: "Seu voto me mostrou seu lado."
{user} disse a {user1}: "Você votou em mim, e eu não entendi."
{user} disse a {user1}: "Seu voto em mim foi uma bomba."
{user} disse a {user1}: "Você me escolheu. Por quê, de verdade?"
{user} disse a {user1}: "Seu voto não vai sair da minha cabeça."
{user} disse a {user1}: "Você votou em mim, e eu vou te cobrar."
{user} disse a {user1}: "Seu voto em mim foi precipitado."
{user} disse a {user1}: "Você escreveu meu nome sem hesitar."
{user} disse a {user1}: "Você me votou, e eu achava que confiava em mim."
{user} disse a {user1}: "Seu voto foi um recado claro."
{user} disse a {user1}: "Você votou em mim, e eu vou lembrar na mesa."
{user} disse a {user1}: "Seu voto em mim foi estranho."
{user} disse a {user1}: "Você me escolheu, e isso me incomoda."
{user} disse a {user1}: "Seu voto me fez desconfiar de você."
{user} disse a {user1}: "Você votou em mim, e isso não se faz."
{user} disse a {user1}: "Seu voto em mim foi a pior surpresa."
{user} disse a {user1}: "Você escreveu meu nome, e eu escrevo o seu hoje."
{user} disse a {user1}: "Você me votou, e agora sou eu quem desconfia."
{user} disse a {user1}: "Seu voto foi um tapa."
{user} disse a {user1}: "Você votou em mim, e eu sei de tudo."
{user} disse a {user1}: "Seu voto em mim foi mal pensado."
{user} disse a {user1}: "Você me escolheu, e eu não vou fingir que não vi."
{user} disse a {user1}: "Seu voto me marcou, e não no bom sentido."
{user} disse a {user1}: "Você votou em mim, e eu vou reagir."
{user} disse a {user1}: "Seu voto em mim foi pesado demais."
{user} disse a {user1}: "Você escreveu meu nome. Eu não esqueço nomes."
{user} disse a {user1}: "Você me votou, e agora eu sei quem é você."
{user} disse a {user1}: "Seu voto foi desnecessário."
{user} disse a {user1}: "Você votou em mim, e isso vai pesar."
{user} disse a {user1}: "Seu voto em mim foi a maior decepção."
{user} disse a {user1}: "Você me escolheu, e eu te pergunto: por quê?"
{user} disse a {user1}: "Seu voto não foi justo."
{user} disse a {user1}: "Você votou em mim, e eu tô magoado(a)."
{user} disse a {user1}: "Seu voto em mim foi frio."
{user} disse a {user1}: "Você escreveu meu nome, e vai pagar."
{user} disse a {user1}: "Você me votou, e isso fica entre a gente. Por enquanto."
{user} disse a {user1}: "Seu voto me mostrou o jogo."
{user} disse a {user1}: "Você votou em mim, e eu não vou esquecer nunca."
{user} disse a {user1}: "Seu voto em mim foi traiçoeiro."
{user} disse a {user1}: "Você me escolheu, e eu tô atento(a) agora."
{user} disse a {user1}: "Seu voto foi o motivo da minha insônia."
{user} disse a {user1}: "Você votou em mim, e isso me deixou furioso(a)."
{user} disse a {user1}: "Seu voto em mim não teve lógica."
{user} disse a {user1}: "Você escreveu meu nome. Tá anotado."
{user} disse a {user1}: "Você me votou, e eu vou te devolver."
{user} disse a {user1}: "Seu voto foi um erro que você vai pagar."
{user} disse a {user1}: "Você votou em mim, e eu vi tudo."
{user} disse a {user1}: "Seu voto em mim foi decepcionante."
{user} disse a {user1}: "Você me escolheu, e eu vou te escolher na mesa."
{user} disse a {user1}: "Seu voto me fez chorar à noite."
{user} disse a {user1}: "Você votou em mim, e agora eu quero entender."
{user} disse a {user1}: "Seu voto em mim foi uma afronta."
{user} disse a {user1}: "Você escreveu meu nome, e eu li."
{user} disse a {user1}: "Você me votou, e eu fiquei sem chão."
{user} disse a {user1}: "Seu voto foi um sinal."
{user} disse a {user1}: "Você votou em mim, e eu vou me lembrar."
{user} disse a {user1}: "Seu voto em mim foi um golpe."
{user} disse a {user1}: "Você me escolheu, e isso me deixou alerta."
{user} disse a {user1}: "Seu voto não vai passar em branco."
{user} disse a {user1}: "Você votou em mim, e isso me deixou pensativo(a)."
{user} disse a {user1}: "Seu voto em mim foi agressivo."
{user} disse a {user1}: "Você escreveu meu nome, e sorriu."
{user} disse a {user1}: "Você me votou, e eu não entendo você."
{user} disse a {user1}: "Seu voto foi uma ofensa."
{user} disse a {user1}: "Você votou em mim, e eu sei o porquê."
{user} disse a {user1}: "Seu voto em mim foi pura estratégia, né?"
{user} disse a {user1}: "Você me escolheu, e isso ficou marcado em mim."
{user} disse a {user1}: "Seu voto me fez repensar tudo."
{user} disse a {user1}: "Você votou em mim, e eu não confio mais."
{user} disse a {user1}: "Seu voto em mim foi o que eu não esperava."
{user} disse a {user1}: "Você escreveu meu nome, e a gente vai conversar."
{user} disse a {user1}: "Você me votou, e agora sou eu que vou atrás."
{user} disse a {user1}: "Seu voto foi um desrespeito."
{user} disse a {user1}: "Você votou em mim, e isso me doeu."
{user} disse a {user1}: "Seu voto em mim foi um recado. Eu mando outro."
{user} disse a {user1}: "Você me escolheu, e agora me escuta."
{user} disse a {user1}: "Seu voto ficou na minha garganta."
{user} disse a {user1}: "Você votou em mim, e eu tô de olho em você."
{user} disse a {user1}: "Seu voto em mim foi um erro, {user1}."
{user} disse a {user1}: "Eu vi seu voto. Tá guardado."
{user} disse a {user1}: "Meu nome, com a sua letra. Que decepção."
{user} disse a {user1}: "Você votou em mim olhando nos meus olhos."
{user} disse a {user1}: "Achei que você tava comigo. Me enganei."
{user} disse a {user1}: "Seu voto em mim foi um recado?"
{user} disse a {user1}: "Me explica esse voto. Eu espero."
{user} disse a {user1}: "Quando eu vi meu nome no seu papel, gelei."
{user} disse a {user1}: "Não me pede favor depois daquele voto."
{user} disse a {user1}: "Você quis me ver fora. Agora sabe que eu sei."
{user} disse a {user1}: "Você votou em mim. Eu vou retribuir."
{user} disse a {user1}: "Voto é voto. Mas o seu doeu."
{user} disse a {user1}: "Quem vota em mim vira alvo meu."
{user} disse a {user1}: "Seu voto disse tudo que você não tem coragem."
{user} disse a {user1}: "Eu não esperava isso de você."
{user} disse a {user1}: "Seu voto me acordou pro seu jogo."
{user} disse a {user1}: "Você me queria fora. Eu tô aqui ainda."
{user} disse a {user1}: "Fiquei sabendo do seu voto. Obrigado(a) por nada."
`);

export const APPROACH_CONFRONT_ACCUSED = lines(`
{user} foi tirar satisfação com {user1}: "Por que você me acusou?"
{user} disse a {user1}: "Você me chamou de Traidor(a). Com que direito?"
{user} parou {user1}: "Me explica aquela acusação."
{user} disse a {user1}: "Você me acusou na frente de todos."
{user} disse a {user1}: "Você vai se arrepender de me acusar."
{user} disse a {user1}: "Sua acusação foi baixa."
{user} disse a {user1}: "Eu sou Fiel, e você me acusou."
{user} disse a {user1}: "Você me expôs. Por quê?"
{user} disse a {user1}: "Não esquece o que você falou de mim."
{user} disse a {user1}: "Você me acusou sem prova."
{user} disse a {user1}: "Me acusar foi seu maior erro."
{user} disse a {user1}: "Você me queimou pra mesa inteira."
{user} disse a {user1}: "Acusação sua não vale nada."
{user} disse a {user1}: "Você me acusou, agora aguenta."
{user} disse a {user1}: "Por que eu? Me responde."
{user} disse a {user1}: "Sua acusação me machucou."
{user} disse a {user1}: "Você me acusou e nem piscou."
{user} disse a {user1}: "Eu vou provar que você errou."
{user} disse a {user1}: "Você me acusou pra se esconder?"
{user} disse a {user1}: "Me acusar foi covardia."
{user} disse a {user1}: "Você me apontou o dedo. Eu aponto de volta."
{user} disse a {user1}: "Sua acusação foi injusta."
{user} disse a {user1}: "Você me acusou, e eu não esqueço."
{user} disse a {user1}: "Me explica o que te fez me acusar."
{user} disse a {user1}: "Você me chamou de cobra. Olha o espelho."
{user} disse a {user1}: "Você me acusou, e agora tá de boa?"
{user} disse a {user1}: "Sua acusação vai ter volta."
{user} disse a {user1}: "Você me acusou pra todo mundo ouvir."
{user} disse a {user1}: "Me acusar foi um erro de cálculo."
{user} disse a {user1}: "Você me acusou, e eu te considerava."
{user} disse a {user1}: "Sua acusação não tem fundamento."
{user} disse a {user1}: "Você me acusou, e eu tô magoado(a)."
{user} disse a {user1}: "Por que você quis me derrubar?"
{user} disse a {user1}: "Você me acusou, e agora eu te vigio."
{user} disse a {user1}: "Sua acusação foi pessoal."
{user} disse a {user1}: "Você me acusou e fugiu. Volta aqui."
{user} disse a {user1}: "Me acusar não vai te salvar."
{user} disse a {user1}: "Você me acusou, e isso me deixou furioso(a)."
{user} disse a {user1}: "Sua acusação é teatro."
{user} disse a {user1}: "Você me acusou, e eu vou mostrar quem é Traidor."
{user} disse a {user1}: "Me explica, sem rodeio."
{user} disse a {user1}: "Você me acusou, e eu tava do seu lado."
{user} disse a {user1}: "Sua acusação foi um ataque gratuito."
{user} disse a {user1}: "Você me acusou, e eu sei por quê."
{user} disse a {user1}: "Me acusar foi a pior coisa que você fez aqui."
{user} disse a {user1}: "Você me acusou, e agora a gente é inimigo(a)."
{user} disse a {user1}: "Sua acusação não cola."
{user} disse a {user1}: "Você me acusou, e eu vou te acusar também."
{user} disse a {user1}: "Por que tanto ódio de mim?"
{user} disse a {user1}: "Você me acusou, e ninguém acreditou."
{user} disse a {user1}: "Sua acusação foi desespero."
{user} disse a {user1}: "Você me acusou, e eu não mereço isso."
{user} disse a {user1}: "Me acusar foi fácil, né?"
{user} disse a {user1}: "Você me acusou, e eu vou me defender até o fim."
{user} disse a {user1}: "Sua acusação me fez perder o sono."
{user} disse a {user1}: "Você me acusou, e eu não vou deixar barato."
{user} disse a {user1}: "Por que você me escolheu como alvo?"
{user} disse a {user1}: "Você me acusou, e agora me encara."
{user} disse a {user1}: "Sua acusação foi uma faca nas costas."
{user} disse a {user1}: "Você me acusou, e eu quero entender."
{user} disse a {user1}: "Me acusar foi um erro. Um grande erro."
{user} disse a {user1}: "Você me acusou, e eu achava que a gente era amigo."
{user} disse a {user1}: "Sua acusação foi mentira."
{user} disse a {user1}: "Você me acusou, e eu te devolvo na mesa."
{user} disse a {user1}: "Por que me colocar na berlinda?"
{user} disse a {user1}: "Você me acusou, e isso vai pesar."
{user} disse a {user1}: "Sua acusação foi um tiro no escuro."
{user} disse a {user1}: "Você me acusou, e eu vou provar o contrário."
{user} disse a {user1}: "Me acusar foi covarde e baixo."
{user} disse a {user1}: "Você me acusou, e agora vai aguentar."
{user} disse a {user1}: "Sua acusação me mostrou quem você é."
{user} disse a {user1}: "Você me acusou, e eu não esqueço nunca."
{user} disse a {user1}: "Por que, {user1}? Por quê?"
{user} disse a {user1}: "Você me acusou, e todo mundo viu."
{user} disse a {user1}: "Sua acusação foi um erro seu."
{user} disse a {user1}: "Você me acusou, e eu vou atrás de você."
{user} disse a {user1}: "Me acusar foi uma escolha. A minha vem agora."
{user} disse a {user1}: "Você me acusou, e isso me machucou de verdade."
{user} disse a {user1}: "Sua acusação não tinha motivo."
{user} disse a {user1}: "Você me acusou, e eu quero desculpas."
{user} disse a {user1}: "Por que você me atacou?"
{user} disse a {user1}: "Você me acusou, e agora me evita?"
{user} disse a {user1}: "Sua acusação foi a coisa mais injusta."
{user} disse a {user1}: "Você me acusou, e eu não sou quem você pensa."
{user} disse a {user1}: "Me acusar foi fácil pra você."
{user} disse a {user1}: "Você me acusou, e eu vou te mostrar."
{user} disse a {user1}: "Sua acusação foi pura inveja."
{user} disse a {user1}: "Você me acusou, e eu fiquei chocado(a)."
{user} disse a {user1}: "Por que você quer tanto me tirar?"
{user} disse a {user1}: "Você me acusou, e agora é pessoal."
{user} disse a {user1}: "Sua acusação foi baixaria."
{user} disse a {user1}: "Você me acusou, e eu tô de olho."
{user} disse a {user1}: "Me acusar foi desnecessário."
{user} disse a {user1}: "Você me acusou, e isso não se faz."
{user} disse a {user1}: "Sua acusação foi desesperada."
{user} disse a {user1}: "Você me acusou, e eu quero saber o porquê."
{user} disse a {user1}: "Por que me acusar, se eu sou Fiel?"
{user} disse a {user1}: "Você me acusou, e eu vou te enfrentar."
{user} disse a {user1}: "Sua acusação me deixou sem chão."
{user} disse a {user1}: "Você me acusou, e agora pede paz?"
{user} disse a {user1}: "Me acusar foi um golpe baixo."
{user} disse a {user1}: "Você me acusou, e eu vou provar sua mentira."
{user} disse a {user1}: "Sua acusação foi um ataque."
{user} disse a {user1}: "Você me acusou, e eu não vou fingir que não."
{user} disse a {user1}: "Por que eu, e não outro?"
{user} disse a {user1}: "Você me acusou, e eu tô muito chateado(a)."
{user} disse a {user1}: "Sua acusação não tem lógica."
{user} disse a {user1}: "Você me acusou, e eu vou reagir."
{user} disse a {user1}: "Me acusar foi coisa de Traidor(a)."
{user} disse a {user1}: "Você me acusou, e isso vai ter volta na mesa."
{user} disse a {user1}: "Sua acusação foi injustiça pura."
{user} disse a {user1}: "Você me acusou, e eu te respeitava."
{user} disse a {user1}: "Por que você me acusou? Fala."
{user} disse a {user1}: "Você me acusou, e eu sei que foi estratégia."
{user} disse a {user1}: "Sua acusação foi mal pensada."
{user} disse a {user1}: "Você me acusou, e eu vou lembrar."
{user} disse a {user1}: "Me acusar foi a jogada mais suja."
{user} disse a {user1}: "Você me acusou, e eu quero uma explicação."
{user} disse a {user1}: "Sua acusação me deixou com raiva."
{user} disse a {user1}: "Você me acusou, e eu vou te devolver."
{user} disse a {user1}: "Por que você fez isso comigo?"
{user} disse a {user1}: "Você me acusou, e agora eu desconfio de você."
{user} disse a {user1}: "Sua acusação foi uma afronta."
{user} disse a {user1}: "Você me acusou, e eu não mereço."
{user} disse a {user1}: "Me acusar foi um erro que você vai pagar."
{user} disse a {user1}: "Você me acusou, e isso ficou marcado."
{user} disse a {user1}: "Sua acusação foi um tapa na cara."
{user} disse a {user1}: "Você me acusou, e eu vou mostrar a verdade."
{user} disse a {user1}: "Por que me escolheu pra acusar?"
{user} disse a {user1}: "Você me acusou, e eu não entendo."
{user} disse a {user1}: "Sua acusação foi o que eu não esperava."
{user} disse a {user1}: "Você me acusou, e agora sou eu que te acuso."
{user} disse a {user1}: "Me acusar não te fez melhor."
{user} disse a {user1}: "Você me acusou, e eu fiquei muito triste."
{user} disse a {user1}: "Sua acusação foi desleal."
{user} disse a {user1}: "Você me acusou, e eu quero justiça."
{user} disse a {user1}: "Por que você me atacou daquele jeito?"
{user} disse a {user1}: "Você me acusou, e todo mundo percebeu que foi forçado."
{user} disse a {user1}: "Sua acusação foi sem noção."
{user} disse a {user1}: "Você me acusou, e eu vou me vingar na mesa."
{user} disse a {user1}: "Me acusar foi fácil. Provar é outra coisa."
{user} disse a {user1}: "Você me acusou, e eu não vou esquecer disso."
{user} disse a {user1}: "Sua acusação foi precipitada."
{user} disse a {user1}: "Você me acusou, e eu quero que retire."
{user} disse a {user1}: "Por que me acusou, se nem me conhece?"
{user} disse a {user1}: "Você me acusou, e agora vai ter que me ouvir."
{user} disse a {user1}: "Sua acusação foi um erro enorme."
{user} disse a {user1}: "Você me acusou, e eu vou te cobrar."
{user} disse a {user1}: "Me acusar foi covardia pura."
{user} disse a {user1}: "Você me acusou, e eu tô de olho em cada passo seu."
{user} disse a {user1}: "Sua acusação foi um veneno."
{user} disse a {user1}: "Você me acusou, e eu vou provar que sou Fiel."
{user} disse a {user1}: "Por que tanta raiva de mim, {user1}?"
{user} disse a {user1}: "Você me acusou, e eu fiquei sem entender."
{user} disse a {user1}: "Sua acusação foi uma grande injustiça."
{user} disse a {user1}: "Você me acusou, e agora a gente vai resolver."
{user} disse a {user1}: "Me acusar foi mais fácil que pensar, né?"
{user} disse a {user1}: "Você me acusou, e isso não vai passar."
{user} disse a {user1}: "Sua acusação foi baixa demais."
{user} disse a {user1}: "Você me acusou, e eu te pergunto na cara: por quê?"
{user} disse a {user1}: "Por que você me jogou pra mesa?"
{user} disse a {user1}: "Você me acusou, e eu não vou abaixar a cabeça."
{user} disse a {user1}: "Sua acusação foi pura maldade."
{user} disse a {user1}: "Você me acusou, e eu vou te enfrentar na mesa."
{user} disse a {user1}: "Me acusar foi sua maior bobagem."
{user} disse a {user1}: "Você me acusou, e eu tô esperando desculpas."
{user} disse a {user1}: "Sua acusação foi um insulto."
{user} disse a {user1}: "Você me acusou, e eu vou mostrar quem mente."
{user} disse a {user1}: "Por que você decidiu me acusar?"
{user} disse a {user1}: "Você me acusou, e agora a guerra começou."
{user} disse a {user1}: "Sua acusação foi um erro. E eu vou provar."
{user} disse a {user1}: "Você me acusou, e eu nunca vou esquecer."
{user} disse a {user1}: "Me acusar foi a sua escolha. Aguenta."
{user} disse a {user1}: "Você me acusou, e eu te devo uma resposta."
{user} disse a {user1}: "Sua acusação foi o fim da nossa paz."
{user} disse a {user1}: "Você me acusou, e eu vou lembrar disso sempre."
{user} disse a {user1}: "Você me acusou sem prova nenhuma."
{user} disse a {user1}: "Me jogou na fogueira. Por quê?"
{user} disse a {user1}: "Traidor(a) eu? Olha pra você primeiro."
{user} disse a {user1}: "Você quis me queimar na frente de todo mundo."
{user} disse a {user1}: "Aquela acusação foi baixa, {user1}."
{user} disse a {user1}: "Com que base você falou de mim?"
{user} disse a {user1}: "Você me expôs. Agora me escuta."
{user} disse a {user1}: "Acusar é fácil. Provar é que eu quero ver."
{user} disse a {user1}: "Você me apontou. Eu vou lembrar."
{user} disse a {user1}: "Me acusar foi seu maior erro aqui."
{user} disse a {user1}, com lágrimas nos olhos: "Por que eu?"
{user} disse a {user1}: "Você não me conhece pra me acusar."
{user} disse a {user1}: "Aquilo que você falou de mim doeu."
{user} disse a {user1}: "Quem acusa assim tem algo a esconder."
{user} disse a {user1}: "Seu dedo apontado pra mim ainda me incomoda."
{user} disse a {user1}: "Quer me acusar? Me acusa na cara, aqui."
{user} disse a {user1}: "Você colocou um alvo em mim. Parabéns."
{user} disse a {user1}: "Você me chamou de mentiroso(a). Explica."
{user} disse a {user1}: "Eu tava do seu lado. E você me acusou."
{user} disse a {user1}: "Ainda não entendi aquela acusação."
{user} disse a {user1}: "Me acusar pra se proteger? Que feio."
{user} disse a {user1}: "Tira meu nome da sua boca."
{user} disse a {user1}: "Você me acusou e nem olhou nos meus olhos."
{user} disse a {user1}: "Eu sou Fiel. E você me fez parecer o contrário."
{user} disse a {user1}: "Me ataca de novo e a gente conversa na mesa."
{user} disse a {user1}: "Foi por maldade ou por medo?"
`);

export const APPROACH_CONFRONT = lines(`
{user} passou por {user1} e soltou: "Eu sei o seu jogo."
{user} disse a {user1}, seco(a): "Tô de olho em você."
{user} encarou {user1}: "Não gosto de você. Só pra constar."
{user} disse a {user1}: "Você não me engana."
{user} disse a {user1}: "Cuidado comigo, {user1}."
{user} disse a {user1}: "Você tá na minha lista."
{user} esbarrou em {user1}: "Opa. Não foi sem querer."
{user} disse a {user1}: "Seu sorriso não me convence."
{user} disse a {user1}: "Eu não confio em você. Nunca vou."
{user} cruzou com {user1} e fez cara feia.
{user} disse a {user1}: "Você é falso(a) e eu sei."
{user} disse a {user1}: "Fica longe de mim."
{user} disse a {user1}: "Seu tempo aqui tá acabando."
{user} disse a {user1}: "Você me irrita profundamente."
{user} disse a {user1}: "Eu vou te derrubar."
{user} disse a {user1}: "Pode sorrir. Eu sei quem você é."
{user} disse a {user1}: "Você é o(a) próximo(a), anota."
{user} disse a {user1}: "Não vem com conversa pra cima de mim."
{user} disse a {user1}: "Você acha que engana quem?"
{user} disse a {user1}: "Eu tô contando os dias pra você sair."
{user} disse a {user1}: "Você é veneno."
{user} disse a {user1}: "Não me dirige a palavra."
{user} disse a {user1}: "Você tá com os dias contados."
{user} disse a {user1}: "Eu sei o que você fez."
{user} disse a {user1}: "Você não é bem-vindo(a) perto de mim."
{user} disse a {user1}: "Sua máscara vai cair."
{user} disse a {user1}: "Eu não esqueço, {user1}."
{user} disse a {user1}: "Você é o(a) mais falso(a) do castelo."
{user} disse a {user1}: "Seu jogo é sujo."
{user} disse a {user1}: "Fica esperto(a), que eu tô atento(a)."
{user} disse a {user1}: "Você me dá nojo."
{user} disse a {user1}: "Eu não gosto de você, e não vou fingir."
{user} disse a {user1}: "Você não passa da próxima mesa."
{user} disse a {user1}: "Você é uma cobra."
{user} disse a {user1}: "Eu vou votar em você hoje."
{user} disse a {user1}: "Você fala demais."
{user} disse a {user1}: "Sua hora vai chegar."
{user} disse a {user1}: "Você é pequeno(a) demais pra esse jogo."
{user} disse a {user1}: "Você acha que é esperto(a). Não é."
{user} disse a {user1}: "Eu tô de olho em cada passo seu."
{user} disse a {user1}: "Você é o problema daqui."
{user} disse a {user1}: "Não me provoca."
{user} disse a {user1}: "Seu teatro acabou pra mim."
{user} disse a {user1}: "Você é Traidor(a). Eu sinto."
{user} disse a {user1}: "Eu não confio nem no seu bom dia."
{user} disse a {user1}: "Você vai cair, e eu vou assistir."
{user} disse a {user1}: "Você me deve respeito."
{user} disse a {user1}: "Eu sei quem você é de verdade."
{user} disse a {user1}: "Você é arrogante e eu não suporto."
{user} disse a {user1}: "Você não tem vergonha na cara."
{user} disse a {user1}: "Eu vou falar de você na mesa."
{user} disse a {user1}: "Você acha que tá seguro(a)? Não tá."
{user} disse a {user1}: "Você é o tipo que eu desprezo."
{user} disse a {user1}: "Fica sabendo que eu não gosto de você."
{user} disse a {user1}: "Você não vai ganhar esse jogo."
{user} disse a {user1}: "Seu nome tá no meu voto."
{user} disse a {user1}: "Você me cansa, {user1}."
{user} disse a {user1}: "Eu não quero conversa."
{user} disse a {user1}: "Você é uma fraude."
{user} disse a {user1}: "Eu vejo através de você."
{user} disse a {user1}: "Você não me assusta."
{user} disse a {user1}: "Sua simpatia é de mentira."
{user} disse a {user1}: "Você vai se arrepender de cruzar meu caminho."
{user} disse a {user1}: "Eu te acho perigoso(a)."
{user} disse a {user1}: "Você é o(a) inimigo(a) número um."
{user} disse a {user1}: "Eu não tenho paciência pra você."
{user} disse a {user1}: "Você tá sobrando aqui."
{user} disse a {user1}: "Eu sei de tudo, {user1}."
{user} disse a {user1}: "Você não me conhece. Ainda."
{user} disse a {user1}: "Você é o(a) vilão(ã) dessa história."
{user} disse a {user1}: "Fica esperto(a) na mesa."
{user} disse a {user1}: "Seu jogo tá com os dias contados."
{user} disse a {user1}: "Você é o(a) mais chato(a) daqui."
{user} disse a {user1}: "Não me olha assim."
{user} disse a {user1}: "Eu vou provar quem você é."
{user} disse a {user1}: "Você tá jogando com fogo."
{user} disse a {user1}: "Eu não esqueço cara."
{user} disse a {user1}: "Você é sujo(a)."
{user} disse a {user1}: "Seu lugar não é aqui."
{user} disse a {user1}: "Eu vou te desmascarar."
{user} disse a {user1}: "Você é falso(a) do começo ao fim."
{user} disse a {user1}: "Não me testa, {user1}."
{user} disse a {user1}: "Você vai ver do que eu sou capaz."
{user} disse a {user1}: "Eu não suporto sua voz."
{user} disse a {user1}: "Você é um(a) manipulador(a)."
{user} disse a {user1}: "Fica longe da minha aliança."
{user} disse a {user1}: "Você não é quem diz ser."
{user} disse a {user1}: "Eu tô atrás de você."
{user} disse a {user1}: "Você tem cara de Traidor(a)."
{user} disse a {user1}: "Eu te detesto."
{user} disse a {user1}: "Você vai sair antes de mim."
{user} disse a {user1}: "Não me procura mais."
{user} disse a {user1}: "Você me dá arrepio."
{user} disse a {user1}: "Eu sei o que você esconde."
{user} disse a {user1}: "Você é o(a) pior do castelo."
{user} disse a {user1}: "Eu vou te enfrentar."
{user} disse a {user1}: "Você tá na mira."
{user} disse a {user1}: "Seu fim tá próximo."
{user} disse a {user1}: "Você é um problema pra mim."
{user} disse a {user1}: "Eu não confio em você nem pra carregar uma xícara."
{user} disse a {user1}: "Você é intragável."
{user} disse a {user1}: "Eu vou lembrar de você na mesa."
{user} disse a {user1}: "Você não sabe com quem tá lidando."
{user} disse a {user1}: "Fica esperto(a), é só isso."
{user} disse a {user1}: "Você é uma farsa."
{user} disse a {user1}: "Eu não gosto do seu jeito."
{user} disse a {user1}: "Você vai cair, pode anotar."
{user} disse a {user1}: "Eu tô vendo seu jogo."
{user} disse a {user1}: "Você é o(a) Traidor(a), eu aposto."
{user} disse a {user1}: "Seu teatro não me convence."
{user} disse a {user1}: "Você me irrita só de existir."
{user} disse a {user1}: "Eu vou te tirar daqui."
{user} disse a {user1}: "Você é perigoso(a), e eu sei."
{user} disse a {user1}: "Não conta comigo."
{user} disse a {user1}: "Você é o(a) mais falso(a) que já vi."
{user} disse a {user1}: "Eu tô contra você."
{user} disse a {user1}: "Você vai se ver comigo."
{user} disse a {user1}: "Seu jogo tá exposto."
{user} disse a {user1}: "Você é sonso(a) demais."
{user} disse a {user1}: "Eu não te engulo."
{user} disse a {user1}: "Você vai pagar por tudo."
{user} disse a {user1}: "Eu te vigio de perto."
{user} disse a {user1}: "Você é o nome da minha lista."
{user} disse a {user1}: "Seu tempo tá acabando, {user1}."
{user} disse a {user1}: "Você me deixa desconfiado(a)."
{user} disse a {user1}: "Eu vou te mostrar."
{user} disse a {user1}: "Você não passa confiança nenhuma."
{user} disse a {user1}: "Eu não te quero por perto."
{user} disse a {user1}: "Você vai sair, é questão de tempo."
{user} disse a {user1}: "Seu jogo me enoja."
{user} disse a {user1}: "Você é um(a) aproveitador(a)."
{user} disse a {user1}: "Eu sei quem você é, não adianta."
{user} disse a {user1}: "Você é meu alvo."
{user} disse a {user1}: "Eu vou te acusar na mesa."
{user} disse a {user1}: "Você não é bem-vindo(a)."
{user} disse a {user1}: "Seu sorriso é falso."
{user} disse a {user1}: "Você tá com medo, né?"
{user} disse a {user1}: "Eu não esqueço nada."
{user} disse a {user1}: "Você é uma pedra no meu sapato."
{user} disse a {user1}: "Eu tô de olho, {user1}."
{user} disse a {user1}: "Você vai ver só."
{user} disse a {user1}: "Seu jogo é covarde."
{user} disse a {user1}: "Você não vai durar."
{user} disse a {user1}: "Eu te acho suspeito(a) demais."
{user} disse a {user1}: "Você é o(a) cobra do castelo."
{user} disse a {user1}: "Eu vou lutar contra você."
{user} disse a {user1}: "Você não me conquista."
{user} disse a {user1}: "Seu nome tá marcado."
{user} disse a {user1}: "Você é falso(a) e eu vou provar."
{user} disse a {user1}: "Eu não gosto de você, e todo mundo sabe."
{user} disse a {user1}: "Você vai se arrepender."
{user} disse a {user1}: "Eu não vou parar até você sair."
{user} disse a {user1}: "Você é o(a) inimigo(a) aqui."
{user} disse a {user1}: "Seu disfarce não me engana."
{user} disse a {user1}: "Você tá com os dias contados, sério."
{user} disse a {user1}: "Eu te observo o tempo todo."
{user} disse a {user1}: "Você é a pessoa que eu mais desconfio."
{user} disse a {user1}: "Não se aproxima de mim."
{user} disse a {user1}: "Você vai cair na mesa."
{user} disse a {user1}: "Eu sei o seu segredo."
{user} disse a {user1}: "Você me dá nos nervos."
{user} disse a {user1}: "Seu fim tá chegando, {user1}."
{user} disse a {user1}: "Você é Traidor(a), e eu vou mostrar."
{user} disse a {user1}: "Eu não confio em você, simples."
{user} disse a {user1}: "Você vai pagar caro."
{user} disse a {user1}: "Eu tô contra você, sempre."
{user} disse a {user1}: "Você é a vergonha do castelo."
{user} disse a {user1}: "Seu jogo vai ruir."
{user} disse a {user1}: "Você não me engana, nem por um segundo."
{user} disse a {user1}: "Eu vou atrás de você."
{user} disse a {user1}: "Você é o(a) mais perigoso(a) pra mim."
{user} disse a {user1}: "Não me provoca mais."
{user} disse a {user1}: "Você é o meu voto."
{user} disse a {user1}: "Eu não esqueço sua cara."
{user} disse a {user1}: "Você vai ver o troco."
{user} disse a {user1}: "Seu teatro é ridículo."
{user} disse a {user1}: "Você é falso(a), e isso me irrita."
{user} disse a {user1}: "Eu tô de olho em você, sempre."
{user} disse a {user1}: "Seu teatrinho não cola comigo."
{user} encarou {user1}: "Eu não confio em você. E não vou fingir."
{user} disse a {user1}: "Você pode enganar os outros. Eu não."
{user} passou por {user1}: "Sorrisinho falso, hein?"
{user} disse a {user1}: "Toma cuidado com quem você mexe."
{user} disse a {user1}: "Sua simpatia me dá arrepio."
{user} disse a {user1}: "Você não me engana nem um pouco."
{user} disse a {user1}: "Uma hora a máscara cai. A sua tá escorregando."
{user} disse a {user1}: "Não senta perto de mim, obrigado(a)."
{user} disse a {user1}: "Eu tenho seu número, viu?"
{user} disse a {user1}: "Seu jogo tá muito óbvio pra mim."
{user} disse a {user1}: "Não me chama de amigo(a). Não somos."
{user} disse a {user1}: "Você fala muito e diz nada."
{user} disse a {user1}, com desdém: "Ah, é você. Oi."
{user} disse a {user1}: "Não gosto do jeito que você olha pros outros."
{user} disse a {user1}: "Quanto mais você fala, menos eu confio."
{user} disse a {user1}: "Você é o tipo de gente que eu evito."
{user} disse a {user1}: "Vou ficar colado(a) em você. Só pra ver."
{user} disse a {user1}: "Sua cara de paisagem não me convence."
{user} disse a {user1}: "Guarda seu charme pros outros."
{user} disse a {user1}: "Eu vou ser seu pesadelo aqui dentro."
{user} disse a {user1}: "Fica esperto(a). Eu não esqueço nada."
{user} disse a {user1}: "Com você eu não tenho papo."
{user} disse a {user1}: "Todo mundo tem um lado sombrio. O seu aparece."
`);

export const APPROACH_HELP = lines(`
{user} procurou {user1}, nervoso(a): "Você vai votar em mim hoje?"
{user} pediu a {user1}: "Me defende na mesa? Eu sou Fiel."
{user} disse a {user1}: "Tão falando de mim. Me ajuda?"
{user} segurou o braço de {user1}: "Eu preciso de você hoje."
{user} disse a {user1}: "Por favor, não vota em mim."
{user} disse a {user1}: "Eu tô com medo. Me ajuda a sobreviver."
{user} disse a {user1}: "Fala bem de mim na mesa?"
{user} disse a {user1}: "Eu juro que sou Fiel. Acredita em mim."
{user} disse a {user1}: "Eu tô sozinho(a). Você me apoia?"
{user} disse a {user1}: "Se você me defender, eu te devo a vida."
{user} disse a {user1}: "Meu nome tá forte hoje. Me ajuda."
{user} disse a {user1}: "Eu não sou Traidor(a). Você sabe."
{user} disse a {user1}: "Me dá um voto de confiança?"
{user} disse a {user1}: "Eu preciso de alguém do meu lado."
{user} disse a {user1}: "Você pode convencer os outros? Eu sou Fiel."
{user} disse a {user1}: "Não deixa me tirarem, por favor."
{user} disse a {user1}: "Eu tô desesperado(a), {user1}."
{user} disse a {user1}: "Você acredita em mim, né?"
{user} disse a {user1}: "Me ajuda a desviar os votos."
{user} disse a {user1}: "Eu vou te proteger depois, prometo."
{user} disse a {user1}: "Não me abandona hoje."
{user} disse a {user1}: "Eu preciso da sua voz na mesa."
{user} disse a {user1}: "Você é minha última esperança."
{user} disse a {user1}: "Me defende, e eu te defendo sempre."
{user} disse a {user1}: "Tão armando contra mim. Me ajuda."
{user} disse a {user1}: "Eu sou inocente, juro."
{user} disse a {user1}: "Fica do meu lado hoje, por favor."
{user} disse a {user1}: "Eu não quero sair assim."
{user} disse a {user1}: "Você pode falar comigo na mesa?"
{user} disse a {user1}: "Eu confio em você pra me salvar."
{user} disse a {user1}: "Não vota em mim, eu te imploro."
{user} disse a {user1}: "Eu preciso que alguém acredite em mim."
{user} disse a {user1}: "Me ajuda a mostrar que sou Fiel."
{user} disse a {user1}: "Você me conhece. Sabe que não sou eu."
{user} disse a {user1}: "Eu tô no alvo, e não sei por quê."
{user} disse a {user1}: "Me ajuda, {user1}. De verdade."
{user} disse a {user1}: "Eu vou precisar de você hoje."
{user} disse a {user1}: "Você me salva e eu te salvo."
{user} disse a {user1}: "Não deixa a mesa me engolir."
{user} disse a {user1}: "Eu sou Fiel, e preciso de ajuda."
{user} disse a {user1}: "Você vai estar comigo na mesa?"
{user} disse a {user1}: "Eu tô com medo de sair hoje."
{user} disse a {user1}: "Me defende, por favor."
{user} disse a {user1}: "Eu preciso de um(a) aliado(a) agora."
{user} disse a {user1}: "Você pode puxar voto pra outro?"
{user} disse a {user1}: "Eu juro pela minha família que sou Fiel."
{user} disse a {user1}: "Não me deixa sozinho(a) nessa."
{user} disse a {user1}: "Você acredita em mim? Preciso ouvir."
{user} disse a {user1}: "Me ajuda a sair dessa."
{user} disse a {user1}: "Eu te devo uma se você me ajudar."
{user} disse a {user1}: "Tão me acusando. Você me defende?"
{user} disse a {user1}: "Eu sou inocente, e tô com medo."
{user} disse a {user1}: "Me salva na mesa, {user1}."
{user} disse a {user1}: "Eu preciso do seu voto longe de mim."
{user} disse a {user1}: "Você pode falar a meu favor?"
{user} disse a {user1}: "Eu não sei mais o que fazer."
{user} disse a {user1}: "Me ajuda a provar que sou Fiel."
{user} disse a {user1}: "Você é a única pessoa que eu confio."
{user} disse a {user1}: "Não vota em mim, pelo amor de Deus."
{user} disse a {user1}: "Eu preciso de apoio hoje."
{user} disse a {user1}: "Me defende e eu nunca vou esquecer."
{user} disse a {user1}: "Eu tô sendo injustiçado(a). Me ajuda."
{user} disse a {user1}: "Você vai me defender, né?"
{user} disse a {user1}: "Eu não quero ir embora, {user1}."
{user} disse a {user1}: "Me ajuda a convencer a mesa."
{user} disse a {user1}: "Eu sou Fiel, e você sabe disso."
{user} disse a {user1}: "Não me deixa na mão hoje."
{user} disse a {user1}: "Eu preciso que você acredite em mim."
{user} disse a {user1}: "Você pode ser minha voz na mesa?"
{user} disse a {user1}: "Eu tô com o coração na mão."
{user} disse a {user1}: "Me ajuda, e eu retribuo."
{user} disse a {user1}: "Eu confio em você pra isso."
{user} disse a {user1}: "Tão querendo me tirar. Me protege."
{user} disse a {user1}: "Eu não sou quem eles pensam."
{user} disse a {user1}: "Você me dá uma força?"
{user} disse a {user1}: "Eu preciso sobreviver a hoje."
{user} disse a {user1}: "Me defende na mesa, eu te imploro."
{user} disse a {user1}: "Eu sou inocente, me ajuda a mostrar."
{user} disse a {user1}: "Você vai me salvar?"
{user} disse a {user1}: "Eu tô perdido(a) sem apoio."
{user} disse a {user1}: "Me ajuda a desviar a atenção de mim."
{user} disse a {user1}: "Eu juro que não fiz nada."
{user} disse a {user1}: "Você é minha salvação hoje."
{user} disse a {user1}: "Não vota em mim, eu sou Fiel."
{user} disse a {user1}: "Eu preciso de alguém que me defenda."
{user} disse a {user1}: "Me ajuda, e eu fico te devendo pra sempre."
{user} disse a {user1}: "Eu tô com medo da mesa."
{user} disse a {user1}: "Você acredita que sou Fiel?"
{user} disse a {user1}: "Me protege hoje, só hoje."
{user} disse a {user1}: "Eu preciso de você, sério."
{user} disse a {user1}: "Me defende, que eu mereço."
{user} disse a {user1}: "Eu tô sendo perseguido(a)."
{user} disse a {user1}: "Você pode me ajudar a ficar?"
{user} disse a {user1}: "Eu não sou Traidor(a), eu juro."
{user} disse a {user1}: "Me ajuda a sobreviver mais uma noite."
{user} disse a {user1}: "Eu preciso do seu apoio na mesa."
{user} disse a {user1}: "Você vai estar do meu lado?"
{user} disse a {user1}: "Eu tô com muito medo, {user1}."
{user} disse a {user1}: "Me defende, que eu faço o mesmo por você."
{user} disse a {user1}: "Eu sou Fiel, e preciso que alguém veja."
{user} disse a {user1}: "Não me deixa cair."
{user} disse a {user1}: "Você pode puxar a mesa pra longe de mim?"
{user} disse a {user1}: "Eu preciso de uma chance."
{user} disse a {user1}: "Me ajuda a mostrar quem eu sou."
{user} disse a {user1}: "Eu confio em você. Me ajuda."
{user} disse a {user1}: "Tão errando comigo. Me defende."
{user} disse a {user1}: "Eu não quero sair injustiçado(a)."
{user} disse a {user1}: "Você me dá seu voto de confiança?"
{user} disse a {user1}: "Eu tô à beira do abismo."
{user} disse a {user1}: "Me salva, {user1}, por favor."
{user} disse a {user1}: "Eu sou inocente, e você pode provar."
{user} disse a {user1}: "Não me abandona na mesa."
{user} disse a {user1}: "Eu preciso de você mais do que nunca."
{user} disse a {user1}: "Me defende, eu tô no alvo."
{user} disse a {user1}: "Você acredita em mim, né? Preciso disso."
{user} disse a {user1}: "Eu não tenho mais ninguém."
{user} disse a {user1}: "Me ajuda a ficar mais um dia."
{user} disse a {user1}: "Eu sou Fiel, juro por tudo."
{user} disse a {user1}: "Você vai me proteger?"
{user} disse a {user1}: "Eu tô tremendo de medo."
{user} disse a {user1}: "Me defende e eu nunca te traio."
{user} disse a {user1}: "Eu preciso de uma voz a meu favor."
{user} disse a {user1}: "Não me deixa ser banido(a)."
{user} disse a {user1}: "Você pode convencer alguém por mim?"
{user} disse a {user1}: "Eu sou inocente, me ajuda."
{user} disse a {user1}: "Me protege na mesa, {user1}."
{user} disse a {user1}: "Eu tô sozinho(a) contra todos."
{user} disse a {user1}: "Você é o(a) único(a) que pode me ajudar."
{user} disse a {user1}: "Não vota em mim, eu imploro."
{user} disse a {user1}: "Eu preciso de você do meu lado."
{user} disse a {user1}: "Me defende, que eu sou Fiel."
{user} disse a {user1}: "Eu não sei o que fiz pra estar assim."
{user} disse a {user1}: "Você vai me apoiar hoje?"
{user} disse a {user1}: "Eu preciso de ajuda, de verdade."
{user} disse a {user1}: "Me salva, e eu te salvo."
{user} disse a {user1}: "Eu sou inocente, acredita em mim."
{user} disse a {user1}: "Não me deixa cair hoje."
{user} disse a {user1}: "Você pode me defender?"
{user} disse a {user1}: "Eu tô com medo de verdade."
{user} disse a {user1}: "Me ajuda a desviar esse voto."
{user} disse a {user1}: "Eu sou Fiel, e preciso de você."
{user} disse a {user1}: "Você vai me salvar na mesa?"
{user} disse a {user1}: "Eu não quero sair, {user1}."
{user} disse a {user1}: "Me defende, por tudo que é sagrado."
{user} disse a {user1}: "Eu preciso de um amigo agora."
{user} disse a {user1}: "Você acredita em mim? Diz que sim."
{user} disse a {user1}: "Me ajuda, eu te peço."
{user} disse a {user1}: "Eu sou Fiel, e tão me caçando."
{user} disse a {user1}: "Não vota em mim, e fala com os outros."
{user} disse a {user1}: "Eu tô no limite."
{user} disse a {user1}: "Me protege, {user1}, só hoje."
{user} disse a {user1}: "Eu preciso sobreviver, me ajuda."
{user} disse a {user1}: "Você vai me defender? Preciso saber."
{user} disse a {user1}: "Eu sou inocente, juro de novo."
{user} disse a {user1}: "Me ajuda a mostrar que não sou eu."
{user} disse a {user1}: "Eu tô com medo de ser o próximo."
{user} disse a {user1}: "Você pode ficar do meu lado?"
{user} disse a {user1}: "Eu preciso da sua ajuda hoje."
{user} disse a {user1}: "Me defende, e eu fico te devendo."
{user} disse a {user1}: "Eu sou Fiel, me ajuda a provar."
{user} disse a {user1}: "Não me abandona, {user1}."
{user} disse a {user1}: "Você é minha única chance."
{user} disse a {user1}: "Eu tô desesperado(a), me ajuda."
{user} disse a {user1}: "Me salva na mesa de hoje."
{user} disse a {user1}: "Eu preciso que você me defenda."
{user} disse a {user1}: "Você acredita em mim? Por favor."
{user} disse a {user1}: "Eu sou inocente, e tô com medo."
{user} disse a {user1}: "Me ajuda, que eu retribuo sempre."
{user} disse a {user1}: "Eu não quero ser o(a) próximo(a)."
{user} disse a {user1}: "Você pode me salvar?"
{user} disse a {user1}: "Eu preciso de você, {user1}."
{user} disse a {user1}: "Me defende na mesa, eu confio em você."
{user} disse a {user1}: "Eu sou Fiel, acredita."
{user} disse a {user1}: "Não vota em mim, por favor, por favor."
{user} disse a {user1}: "Eu tô no alvo, me ajuda a sair."
{user} disse a {user1}: "Você vai me proteger, né?"
{user} disse a {user1}: "Eu preciso de um voto de confiança seu."
{user} disse a {user1}: "Me ajuda a ficar, {user1}."
{user} disse a {user1}: "Eu sou inocente, e você é minha esperança."
{user} disse a {user1}, tremendo: "Acho que é meu fim hoje."
{user} pediu a {user1}: "Fala bem de mim pros outros?"
{user} disse a {user1}: "Não tenho mais ninguém. Me ajuda."
{user} disse a {user1}: "Se meu nome aparecer, me defende?"
{user} disse a {user1}: "Tô com medo, {user1}. De verdade."
{user} disse a {user1}: "Você tem voz na mesa. Usa por mim."
{user} disse a {user1}: "Me dá uma chance. Não vota em mim."
{user} disse a {user1}: "Todo mundo me olha torto. Você também?"
{user} disse a {user1}: "Me fala o que eu faço pra sair dessa."
{user} disse a {user1}: "Eu nunca votei em você. Lembra disso."
{user} disse a {user1}: "Preciso de um aliado(a) hoje. Pode ser você?"
{user} disse a {user1}: "Só quero chegar em casa sabendo que tentei."
{user} disse a {user1}: "Me ajuda e eu te devo uma pra sempre."
{user} disse a {user1}: "Não me deixa cair por boato."
{user} disse a {user1}: "Eu tô sendo injustiçado(a). Você vê isso?"
{user} disse a {user1}: "Me protege só hoje. Amanhã eu retribuo."
{user} disse a {user1}: "Você acredita em mim? Preciso ouvir isso."
{user} disse a {user1}: "Eu tô perdido(a). Me orienta."
{user} disse a {user1}: "Se eu sair hoje, os Traidores ganham."
{user} disse a {user1}: "Me ajuda a convencer os outros?"
{user} disse a {user1}: "Juro por tudo: eu não sou Traidor(a)."
{user} disse a {user1}, chorando: "Eu não aguento mais essa pressão."
{user} disse a {user1}: "Seu voto pode me salvar hoje."
`);

export const APPROACH_GRIEF = lines(`
{user} abraçou {user1}: "{user2} confiava em você. Descobre quem foi."
{user} chorou com {user1}: "Eu não acredito que {user2} se foi."
{user} disse a {user1}: "{user2} era a melhor pessoa daqui."
{user} disse a {user1}: "Eu vou vingar {user2}. Me ajuda?"
{user} disse a {user1}: "{user2} falava bem de você, sabia?"
{user} disse a {user1}: "Sem {user2}, esse castelo ficou vazio."
{user} disse a {user1}: "{user2} não merecia isso."
{user} disse a {user1}: "Eu dormi do lado de {user2}. E não ouvi nada."
{user} disse a {user1}: "{user2} tinha medo de morrer. E morreu."
{user} disse a {user1}: "Me promete que a gente acha quem matou {user2}."
{user} disse a {user1}: "{user2} era meu(minha) melhor amigo(a) aqui."
{user} disse a {user1}: "{user2} desconfiava de alguém. Quem será?"
{user} disse a {user1}: "Eu não consigo parar de chorar por {user2}."
{user} disse a {user1}: "{user2} me disse ontem que tinha medo."
{user} disse a {user1}: "Vamos fazer isso por {user2}."
{user} disse a {user1}: "{user2} tava chegando perto. Por isso morreu."
{user} disse a {user1}: "Eu sinto tanta falta de {user2}."
{user} disse a {user1}: "{user2} acreditava na gente."
{user} disse a {user1}: "Quem fez isso com {user2} vai pagar."
{user} disse a {user1}: "{user2} era a alegria da mesa."
{user} disse a {user1}: "Eu não acredito que não vou ver {user2} de novo."
{user} disse a {user1}: "{user2} tinha um palpite. Morreu com ele."
{user} disse a {user1}: "Você tava perto de {user2}. Viu algo?"
{user} disse a {user1}: "{user2} merecia a final."
{user} disse a {user1}: "Eu queria ter protegido {user2}."
{user} disse a {user1}: "{user2} era Fiel até o osso."
{user} disse a {user1}: "Me abraça. Eu perdi {user2}."
{user} disse a {user1}: "{user2} me fez prometer que eu ia até o fim."
{user} disse a {user1}: "Eu vou honrar {user2}."
{user} disse a {user1}: "{user2} falava de você com carinho."
{user} disse a {user1}: "Esse café sem {user2} é outro."
{user} disse a {user1}: "{user2} era meu porto seguro."
{user} disse a {user1}: "A gente precisa achar quem tirou {user2}."
{user} disse a {user1}: "{user2} não fez mal a ninguém."
{user} disse a {user1}: "Eu tô destruído(a) por {user2}."
{user} disse a {user1}: "{user2} me deixou um recado ontem. Sobre alguém."
{user} disse a {user1}: "Eu não sei jogar sem {user2}."
{user} disse a {user1}: "{user2} era o coração da minha aliança."
{user} disse a {user1}: "Você vai me ajudar a vingar {user2}?"
{user} disse a {user1}: "{user2} tinha tanta vida."
{user} disse a {user1}: "Eu sinto que traí {user2} por não ver antes."
{user} disse a {user1}: "{user2} confiava em pouca gente. Em você, sim."
{user} disse a {user1}: "Eu vou lembrar de {user2} em cada voto."
{user} disse a {user1}: "{user2} era o(a) mais leal."
{user} disse a {user1}: "Quem matou {user2} tá sentado(a) nessa mesa."
{user} disse a {user1}: "{user2} tinha o riso mais bonito."
{user} disse a {user1}: "Eu não durmo sem pensar em {user2}."
{user} disse a {user1}: "{user2} merecia mais tempo."
{user} disse a {user1}: "Descobre por mim quem fez isso com {user2}."
{user} disse a {user1}: "{user2} era família."
{user} disse a {user1}: "Eu perdi meu chão com {user2}."
{user} disse a {user1}: "{user2} falava que ia ganhar pela família."
{user} disse a {user1}: "Me ajuda a honrar {user2}."
{user} disse a {user1}: "{user2} era o(a) primeiro(a) a acordar. Hoje não acordou."
{user} disse a {user1}: "Eu ainda vejo {user2} na cadeira dele(a)."
{user} disse a {user1}: "{user2} tinha certeza de quem era Traidor."
{user} disse a {user1}: "Eu vou lutar por {user2}."
{user} disse a {user1}: "{user2} não devia ter morrido."
{user} disse a {user1}: "Eu queria ter dito adeus a {user2}."
{user} disse a {user1}: "{user2} te considerava amigo(a)."
{user} disse a {user1}: "A torre tirou {user2} de mim."
{user} disse a {user1}: "Eu tô com raiva e tristeza por {user2}."
{user} disse a {user1}: "{user2} era luz nesse castelo."
{user} disse a {user1}: "Vamos juntos descobrir quem matou {user2}."
{user} disse a {user1}: "{user2} me ensinou a confiar."
{user} disse a {user1}: "Eu sinto um vazio sem {user2}."
{user} disse a {user1}: "{user2} tinha medo de quem? Você sabe?"
{user} disse a {user1}: "{user2} era o(a) mais sincero(a)."
{user} disse a {user1}: "Eu vou carregar {user2} comigo até a final."
{user} disse a {user1}: "{user2} merecia justiça."
{user} disse a {user1}: "Eu não acredito que a porta não abriu pra {user2}."
{user} disse a {user1}: "{user2} tava tão feliz ontem."
{user} disse a {user1}: "Me promete que não vai esquecer {user2}."
{user} disse a {user1}: "{user2} tinha um coração enorme."
{user} disse a {user1}: "Eu vou fazer a mesa pagar por {user2}."
{user} disse a {user1}: "{user2} era meu(minha) irmão(ã) aqui dentro."
{user} disse a {user1}: "Eu tô sem forças depois de {user2}."
{user} disse a {user1}: "{user2} acreditava em você, {user1}."
{user} disse a {user1}: "A gente vai achar quem foi, por {user2}."
{user} disse a {user1}: "{user2} não merecia esse fim."
{user} disse a {user1}: "Eu ainda escuto a voz de {user2}."
{user} disse a {user1}: "{user2} tava desconfiando de alguém. E pagou."
{user} disse a {user1}: "Eu vou honrar {user2} com meu voto."
{user} disse a {user1}: "{user2} era a melhor companhia."
{user} disse a {user1}: "Eu não consigo comer sem {user2} aqui."
{user} disse a {user1}: "{user2} tinha tantos planos."
{user} disse a {user1}: "Me ajuda a não deixar a morte de {user2} em vão."
{user} disse a {user1}: "{user2} era o(a) mais corajoso(a)."
{user} disse a {user1}: "Eu vou sentir falta de {user2} pra sempre."
{user} disse a {user1}: "{user2} merecia ganhar."
{user} disse a {user1}: "Quem tirou {user2} daqui tem sangue frio."
{user} disse a {user1}: "{user2} me abraçou ontem como despedida."
{user} disse a {user1}: "Eu não vou descansar até achar quem matou {user2}."
{user} disse a {user1}: "{user2} era Fiel, e todos sabiam."
{user} disse a {user1}: "Eu tô de luto por {user2}."
{user} disse a {user1}: "{user2} confiava em mim, e eu não protegi."
{user} disse a {user1}: "Vamos fazer justiça por {user2}."
{user} disse a {user1}: "{user2} tinha um sorriso que ninguém vai substituir."
{user} disse a {user1}: "Eu perdi {user2}, e perdi o chão."
{user} disse a {user1}: "{user2} falou de você antes de dormir."
{user} disse a {user1}: "Me dá um abraço, por {user2}."
{user} disse a {user1}: "{user2} era a pessoa mais bondosa."
{user} disse a {user1}: "Eu vou vingar {user2} na mesa."
{user} disse a {user1}: "{user2} não merecia a torre."
{user} disse a {user1}: "Eu sinto que {user2} ainda tá aqui."
{user} disse a {user1}: "{user2} era o(a) mais leal que eu conheci."
{user} disse a {user1}: "Descobrir quem matou {user2} é minha missão."
{user} disse a {user1}: "{user2} tinha um palpite forte ontem."
{user} disse a {user1}: "Eu tô com o coração partido por {user2}."
{user} disse a {user1}: "{user2} era meu(minha) aliado(a) de verdade."
{user} disse a {user1}: "Eu vou jogar por {user2} agora."
{user} disse a {user1}: "{user2} merecia sair pela porta da frente."
{user} disse a {user1}: "Eu não acredito que tiraram {user2}."
{user} disse a {user1}: "{user2} era a alegria do café."
{user} disse a {user1}: "Me ajuda a achar quem fez isso com {user2}."
{user} disse a {user1}: "{user2} era a pessoa que eu mais confiava."
{user} disse a {user1}: "Eu vou lembrar de {user2} a cada mesa."
{user} disse a {user1}: "{user2} tinha medo de alguém específico."
{user} disse a {user1}: "Eu tô arrasado(a) sem {user2}."
{user} disse a {user1}: "{user2} merecia paz, não adaga."
{user} disse a {user1}: "Eu queria ter ficado acordado(a) por {user2}."
{user} disse a {user1}: "{user2} era sincero(a) comigo sempre."
{user} disse a {user1}: "Vamos vencer por {user2}."
{user} disse a {user1}: "{user2} não merecia ser a vítima."
{user} disse a {user1}: "Eu sinto um buraco no peito por {user2}."
{user} disse a {user1}: "{user2} era a minha certeza aqui."
{user} disse a {user1}: "Eu vou fazer o castelo lembrar de {user2}."
{user} disse a {user1}: "{user2} te via como amigo(a)."
{user} disse a {user1}: "Eu perdi meu(minha) melhor aliado(a): {user2}."
{user} disse a {user1}: "{user2} era a pessoa mais honesta."
{user} disse a {user1}: "Eu vou honrar a memória de {user2}."
{user} disse a {user1}: "{user2} tava tão perto da verdade."
{user} disse a {user1}: "Eu não consigo acreditar em {user2} morto(a)."
{user} disse a {user1}: "{user2} merecia tudo de bom."
{user} disse a {user1}: "Me ajuda a vingar {user2}, por favor."
{user} disse a {user1}: "{user2} era meu raio de sol."
{user} disse a {user1}: "Eu vou encontrar quem fez isso com {user2}."
{user} disse a {user1}: "{user2} era o(a) mais gentil."
{user} disse a {user1}: "Eu tô sem chão sem {user2}."
{user} disse a {user1}: "{user2} merecia a final, e sabia disso."
{user} disse a {user1}: "Eu vou jogar pelo nome de {user2}."
{user} disse a {user1}: "{user2} falava que você era de confiança."
{user} disse a {user1}: "Eu não esqueço {user2}, nunca."
{user} disse a {user1}: "{user2} era a minha pessoa aqui."
{user} disse a {user1}: "Vamos achar o(a) Traidor(a) que matou {user2}."
{user} disse a {user1}: "{user2} não fez nada pra merecer isso."
{user} disse a {user1}: "Eu sinto tanto por {user2}."
{user} disse a {user1}: "{user2} era o(a) mais leal da minha aliança."
{user} disse a {user1}: "Eu vou fazer justiça por {user2}."
{user} disse a {user1}: "{user2} tinha uma luz que ninguém tem."
{user} disse a {user1}: "Eu tô triste demais por {user2}."
{user} disse a {user1}: "{user2} merecia viver até o fim."
{user} disse a {user1}: "Me ajuda a honrar {user2} na mesa."
{user} disse a {user1}: "{user2} era a pessoa mais doce."
{user} disse a {user1}: "Eu vou descobrir quem tirou {user2} de nós."
{user} disse a {user1}: "{user2} era meu(minha) confidente."
{user} disse a {user1}: "Eu tô com saudade de {user2} já."
{user} disse a {user1}: "{user2} merecia outro destino."
{user} disse a {user1}: "Eu vou lutar pela memória de {user2}."
{user} disse a {user1}: "{user2} era fiel ao grupo e a mim."
{user} disse a {user1}: "Eu não acredito que perdi {user2}."
{user} disse a {user1}: "{user2} tava desconfiado(a) de alguém, eu sei."
{user} disse a {user1}: "Me promete que vai me ajudar por {user2}."
{user} disse a {user1}: "{user2} era a melhor de nós."
{user} disse a {user1}: "Eu vou vencer por {user2}."
{user} disse a {user1}: "{user2} era o(a) mais querido(a)."
{user} disse a {user1}: "Eu tô devastado(a) por {user2}."
{user} disse a {user1}: "{user2} merecia um abraço, não uma adaga."
{user} disse a {user1}: "Eu vou encontrar o culpado por {user2}."
{user} disse a {user1}: "{user2} falava de você com admiração."
{user} disse a {user1}: "Eu sinto falta de {user2} a cada minuto."
{user} disse a {user1}: "{user2} era o(a) mais verdadeiro(a)."
{user} disse a {user1}: "Eu vou fazer valer a morte de {user2}."
{user} disse a {user1}: "{user2} não merecia partir assim."
{user} disse a {user1}: "Eu vou chorar por {user2} e depois agir."
{user} disse a {user1}: "{user2} era parte de mim aqui dentro."
{user} disse a {user1}: "Vamos juntos por {user2}, {user1}."
{user} disse a {user1}: "{user2} era o(a) mais corajoso(a) de todos."
{user} disse a {user1}: "Eu não vou esquecer {user2}, e nem a mesa vai."
{user} disse a {user1}: "{user2} merecia vencer esse jogo."
{user} disse a {user1}: "Eu vou honrar {user2} até o fim."
{user} disse a {user1}: "{user2} era a minha esperança aqui."
{user} disse a {user1}: "Me ajuda, por {user2}."
{user} disse a {user1}, com os olhos vermelhos: "{user2} me fez companhia a noite toda."
{user} abraçou {user1} forte: "Por que {user2}? Por quê?"
{user} disse a {user1}: "{user2} não merecia sair assim."
{user} disse a {user1}: "Ainda sinto o perfume de {user2} no quarto."
{user} disse a {user1}: "Eu prometi a {user2} que ia até o fim."
{user} disse a {user1}: "Vou fazer isso por {user2}."
{user} disse a {user1}: "{user2} tinha o riso mais bonito daqui."
{user} disse a {user1}: "Não consigo parar de pensar em {user2}."
{user} disse a {user1}: "A cadeira de {user2}... não consigo olhar."
{user} disse a {user1}: "{user2} era meu porto seguro aqui."
{user} chorou no ombro de {user1}: "{user2}..."
{user} disse a {user1}: "Eu ia contar um segredo pra {user2} hoje."
{user} disse a {user1}: "Parece um pesadelo sem {user2}."
{user} disse a {user1}: "{user2} me disse boa noite. Foi a última vez."
{user} disse a {user1}: "Guarda um lugar pra {user2} na nossa memória."
{user} disse a {user1}: "Eu tô destruído(a) com {user2}."
{user} disse a {user1}, sem conseguir segurar o choro: "{user2} não volta mais."
{user} disse a {user1}: "{user2} me deu o último abraço ontem."
{user} disse a {user1}: "Tô me sentindo culpado(a) por {user2}."
`);
