import { lines } from './lines';

/** Falas do jogador: {user} = jogador, {user1} = com quem fala. */

export const SAY_DEFEND = lines(`
{user} ficou de pé: "Eu respondo por {user1}."
{user} disse: "Parem de olhar pra {user1}. Não tem prova nenhuma."
{user} defendeu {user1}: "Vocês estão errando feio."
{user} disse: "{user1} é Fiel. Eu coloco a mão no fogo."
{user} disse: "Se {user1} for Traidor(a), eu saio junto."
{user} pediu calma: "Deixem {user1} em paz."
{user} disse: "Acusar {user1} é fazer o trabalho da torre."
{user} disse: "{user1} é a pessoa mais honesta desse castelo."
{user} disse: "Eu conheço {user1}. Não é Traidor(a)."
{user} disse: "Votar em {user1} é jogar um voto fora."
{user} disse: "Vocês tão caçando {user1} porque é fácil."
{user} disse: "{user1} tá sendo usado(a) de bode expiatório."
{user} disse: "Ninguém aqui trouxe um motivo real contra {user1}."
{user} disse: "Eu confio em {user1} de olhos fechados."
{user} disse: "Se tirarem {user1}, os Traidores agradecem."
{user} disse: "{user1} chora de verdade. Traidor não chora assim."
{user} saiu em defesa de {user1}: "Isso é perseguição."
{user} disse: "{user1} já provou lealdade mais de uma vez."
{user} disse: "Tirem os olhos de {user1}. Tá errado."
{user} disse: "{user1} é o(a) mais transparente daqui."
{user} disse: "Eu vi o coração de {user1}. É Fiel."
{user} disse: "Quem acusa {user1} tem algo a esconder."
{user} disse: "{user1} não merece essa pressão."
{user} disse: "Eu apostaria tudo na inocência de {user1}."
{user} disse: "Vocês querem um culpado rápido. {user1} não é."
{user} disse: "{user1} me ajudou quando ninguém ajudou."
{user} disse: "Se {user1} fosse da torre, eu já tava morto(a)."
{user} disse: "{user1} é fiel até no jeito de rir."
{user} disse: "Olhem melhor: {user1} não se encaixa."
{user} disse: "Não confundam timidez com traição. {user1} é tímido(a)."
{user} disse: "{user1} é leal. Isso eu garanto."
{user} disse: "Parem com essa caça às bruxas contra {user1}."
{user} disse: "Não vou deixar {user1} ser crucificado(a)."
{user} disse: "Eu desmonto cada acusação contra {user1}."
{user} disse: "{user1} é inocente e vocês sabem."
{user} disse: "Acusar {user1} é preguiça de pensar."
{user} disse: "{user1} é família pra mim aqui dentro."
{user} disse: "Traidor não arrisca a pele como {user1} arrisca."
{user} disse: "{user1} é das poucas pessoas sinceras daqui."
{user} disse: "Quem desconfia de {user1} não conhece {user1}."
{user} disse: "Deixa {user1} respirar, gente."
{user} disse: "{user1} tá no alvo porque incomoda os Traidores."
{user} disse: "{user1} só fala demais. Não é crime."
{user} disse: "Eu fico do lado de {user1}. Sempre."
{user} disse: "Vocês vão se arrepender de votar em {user1}."
{user} disse: "{user1} é Fiel com F maiúsculo."
{user} disse: "Não vou votar em {user1} nem que me paguem."
{user} disse: "{user1} é boa pessoa. Ponto."
{user} disse: "Isso é armação contra {user1}."
{user} disse: "Estão empurrando {user1} pra fora. Quem ganha com isso?"
{user} disse: "{user1} tem mais medo que qualquer um aqui."
{user} disse: "Olha a cara de {user1}: é pavor, não culpa."
{user} disse: "{user1} não teria estômago pra matar ninguém."
{user} disse: "Eu sei o que {user1} passou. Não é Traidor(a)."
{user} disse: "Protejam {user1}. É uma das nossas."
{user} disse: "{user1} não merece o nome no quadro."
{user} disse: "Cada acusação a {user1} é um presente pros Traidores."
{user} disse: "{user1} é a última pessoa que eu tiraria."
{user} disse: "{user1} vota com o coração. Traidor vota com a cabeça."
{user} disse: "Deixem {user1} fora dessa."
{user} disse: "{user1} foi quem mais se esforçou até agora."
{user} disse: "Não é porque {user1} é quieto(a) que é culpado(a)."
{user} disse: "Traidor(a) nunca seria tão desastrado(a) quanto {user1}."
{user} disse: "Eu senti verdade em cada palavra de {user1}."
{user} disse: "{user1} merece um voto de confiança."
{user} disse: "Vocês estão errando o alvo. Não é {user1}."
{user} disse: "Se é pra desconfiar de alguém, não é de {user1}."
{user} disse: "{user1} tá sofrendo à toa."
{user} disse: "{user1} tem minha palavra e meu voto."
{user} disse: "Não deixem o medo decidir sobre {user1}."
{user} disse: "{user1} é Fiel e eu vou provar."
{user} disse: "Eu tenho certeza sobre {user1}. Absoluta."
{user} disse: "{user1} é a pessoa errada pra se desconfiar."
{user} disse: "Olhem pra quem acusa {user1}. Olhem direito."
{user} disse: "{user1} não tem malícia pra ser Traidor(a)."
{user} disse: "{user1} sempre falou a verdade comigo."
{user} disse: "Traidor não ajuda os outros como {user1} ajuda."
{user} disse: "Vocês tão perdendo tempo com {user1}."
{user} disse: "{user1} é a pessoa mais pura do castelo."
{user} disse: "Não coloquem a culpa em quem não tem, gente. {user1} não tem."
{user} disse: "Se {user1} cair hoje, a gente perde um Fiel."
{user} disse: "{user1} merece estar aqui até o fim."
{user} disse: "Parem de falar de {user1} pelas costas."
{user} disse: "Eu vi {user1} chorar escondido(a). É Fiel."
{user} disse: "{user1} não sabe nem mentir sobre o que comeu."
{user} disse: "{user1} é leal até demais."
{user} disse: "Tem gente usando {user1} pra se esconder."
{user} disse: "Eu seguro a barra de {user1}."
{user} disse: "Se votarem em {user1}, não contem comigo."
{user} disse: "{user1} é o coração desse grupo."
{user} disse: "Não façam com {user1} o que fizeram com o último."
{user} disse: "Aprendam com o erro: {user1} é Fiel."
{user} disse: "{user1} tem cara de culpa? Tem cara de cansaço!"
{user} disse: "{user1} não esconde nada. Eu garanto."
{user} disse: "{user1} é a pessoa mais fácil de ler daqui. É Fiel."
{user} disse: "Não tem um fato contra {user1}. Só boato."
{user} disse: "Eu me recuso a ver {user1} saindo assim."
{user} disse: "{user1} merece desculpas de metade de vocês."
{user} disse: "{user1} é a vítima perfeita pros Traidores. Não caiam."
{user} disse: "Olha, eu não mudo de ideia: {user1} é Fiel."
{user} disse: "{user1} tá sendo sincero(a) e vocês não enxergam."
{user} disse: "Deixa que eu falo por {user1}."
{user} disse: "Traidor(a) mesmo tá rindo de ver {user1} acuado(a)."
{user} disse: "{user1} é o meu escudo e eu sou o dele(a)."
{user} disse: "Quem tem coragem de votar em {user1} olhando nos olhos?"
{user} disse: "Não troquem um Fiel por uma suspeita vazia."
{user} disse: "{user1} já foi atacado(a) demais."
{user} disse: "Eu não abandono {user1}."
{user} disse: "{user1} é inocente até que provem o contrário."
{user} disse: "{user1} tá do nosso lado, pelo amor de Deus."
{user} disse: "Parem! {user1} é o(a) mais leal daqui!"
{user} disse: "Eu confio mais em {user1} do que em mim."
{user} disse: "{user1} é a prova de que ainda existe gente boa aqui."
{user} disse: "Se eu estiver errado(a) sobre {user1}, me banam depois."
{user} disse: "{user1} tem minha confiança total."
{user} disse: "Fiquem com a dúvida, mas não votem em {user1}."
{user} disse: "Essa história contra {user1} não para em pé."
{user} disse: "{user1} merece justiça, não acusação."
{user} disse: "Os Traidores escolheram {user1} pra vocês acusarem."
{user} disse: "{user1} é Fiel. Eu sinto."
{user} disse: "Não vou deixar {user1} sozinho(a) nessa."
{user} disse: "Quem conhece {user1} sabe que é Fiel."
{user} disse: "{user1} tem a consciência mais limpa daqui."
{user} disse: "Vocês estão confundindo nervosismo com culpa."
{user} disse: "{user1} não tem cara de traição, tem cara de medo."
{user} disse: "Eu fico na frente de {user1} se precisar."
{user} disse: "{user1} é fiel ao grupo desde o primeiro dia."
{user} disse: "O jogo de {user1} é limpo. Limpo!"
{user} disse: "{user1} não merece o que tão fazendo."
{user} disse: "{user1} é inocente, e o tempo vai mostrar."
{user} disse: "Apontem pra outro lado. {user1} não é."
{user} disse: "Guardem o voto de {user1} pra quem merece."
{user} disse: "{user1} é tudo menos Traidor(a)."
{user} disse: "Eu garanto {user1} com meu nome."
{user} disse: "A gente precisa de {user1} até o final."
{user} disse: "Não repitam o erro. {user1} é Fiel."
{user} disse: "{user1} é o tipo de gente que eu queria lá fora."
{user} disse: "Vocês estão sendo injustos com {user1}."
{user} disse: "Os fatos falam por {user1}. Leiam os fatos."
{user} disse: "{user1} não teria coragem de trair ninguém."
{user} disse: "Eu quero {user1} ao meu lado na final."
{user} disse: "Olha o tanto que {user1} já fez pelo grupo."
{user} disse: "{user1} é só honesto(a) demais pra esse jogo."
{user} disse: "Quem tá atacando {user1} tá desviando atenção."
{user} disse: "{user1} merece paz, não suspeita."
{user} disse: "Pode desconfiar de mim, mas não de {user1}."
{user} disse: "Por {user1}, eu brigo com a mesa inteira."
{user} disse: "{user1} é Fiel e não tem discussão."
{user} disse: "Não vou votar em {user1}. Nem hoje, nem nunca."
{user} disse: "{user1} é o alvo errado, e todo mundo vai ver."
{user} disse: "O nome de {user1} não merece estar em nenhum voto."
{user} disse: "{user1} passa confiança. Eu sinto isso."
{user} disse: "Eu vou defender {user1} até o último minuto."
{user} disse: "{user1} é leal. Eu vi, eu sei."
{user} disse: "{user1} é o tipo de Fiel que os Traidores temem."
{user} disse: "Tirar {user1} é um tiro no pé."
{user} disse: "{user1} não fez nada pra merecer isso."
{user} disse: "Eu tô com {user1} e não abro."
{user} disse: "{user1} é inocente como criança."
{user} disse: "Não tem traição nenhuma em {user1}."
{user} disse: "{user1} tá do lado certo dessa história."
{user} disse: "Vou repetir quantas vezes precisar: {user1} é Fiel."
{user} disse: "{user1} merece o benefício da dúvida."
{user} disse: "Eu olho {user1} e vejo verdade."
{user} disse: "{user1} é quem segura esse grupo."
{user} disse: "Sem {user1}, a gente fica mais fraco."
{user} disse: "{user1} não tem culpa de ser simpático(a)."
{user} disse: "Não é porque {user1} sobreviveu que é Traidor(a)."
{user} disse: "{user1} sofreu mais que todo mundo aqui."
{user} disse: "Isso é intriga contra {user1}. Não caiam."
{user} disse: "{user1} é meu voto de confiança."
{user} disse: "Parem de transformar {user1} em vilão(ã)."
{user} disse: "{user1} não tem jogo sujo."
{user} disse: "{user1} é a última pessoa que me trairia."
{user} disse: "Estou com {user1} até o fim."
{user} disse: "Eu vi a lealdade de {user1} de perto."
{user} disse: "{user1} é Fiel. Anotem."
{user} disse: "Não deixem os Traidores escolherem por vocês. Não é {user1}."
{user} disse: "{user1} é a pessoa que eu mais confio aqui."
{user} disse: "{user1} vale ouro pros Fiéis."
{user} disse: "Deixem {user1} fora da mira hoje."
{user} disse: "{user1} é Fiel e tá cansado(a) de provar."
{user} disse: "Eu jogo meu voto fora antes de votar em {user1}."
{user} disse: "{user1} tem a alma leve. Não é Traidor(a)."
{user} disse: "Juro que {user1} é das nossas."
{user} disse: "Eu tô vendo injustiça com {user1}."
{user} disse: "{user1} é o tipo que perde pra não trair."
{user} disse: "Eu seguro o braço de quem votar em {user1}."
{user} disse: "{user1} não merece ir embora assim."
{user} levantou a mão: "Calma. {user1} não fez nada."
{user} disse: "Se é pra desconfiar de {user1}, desconfia de mim também."
{user} disse: "{user1} tá sendo o alvo fácil. Isso é preguiça."
{user} disse: "Deixem {user1} em paz. Vocês estão caçando fantasma."
{user} disse: "Boato não é prova. {user1} fica."
{user} disse: "Eu coloco minha cara a tapa por {user1}."
{user} se colocou entre {user1} e o grupo: "Chega."
{user} disse: "Olhem os votos de {user1}. Sempre do lado certo."
{user} disse: "Atacar {user1} é fazer o jogo dos Traidores."
{user} disse: "{user1} é a pessoa mais honesta aqui."
{user} disse: "Vocês querem culpar alguém. Não precisa ser {user1}."
{user} disse: "Eu vi {user1} chorar por Fiel. Traidor(a) não faz isso."
{user} disse: "{user1} não tem nada a ver com isso. Eu garanto."
`);

export const SAY_TRUST = lines(`
{user} disse a {user1}, em voz baixa: "Eu confio em você."
{user} garantiu a {user1}: "Nunca escreveria seu nome."
{user} disse a {user1}: "Você é das poucas pessoas em quem eu confio."
{user} segurou a mão de {user1}: "Tô com você."
{user} disse a {user1}: "Pode contar comigo pra tudo."
{user} disse a {user1}: "Gostei de você de cara. Dá pra confiar."
{user} disse a {user1}: "Com você eu baixo a guarda."
{user} disse a {user1}: "Você é meu porto seguro aqui."
{user} disse a {user1}: "Se eu tiver que confiar em alguém, é em você."
{user} disse a {user1}: "Você não me decepciona, eu sei."
{user} disse a {user1}: "Eu acredito em você. De verdade."
{user} disse a {user1}: "Seu nome nunca vai sair da minha boca."
{user} disse a {user1}: "Você passa verdade."
{user} disse a {user1}: "Eu sinto que você é do bem."
{user} disse a {user1}: "Confio em você mais do que em mim."
{user} disse a {user1}: "Você pode me contar qualquer coisa."
{user} disse a {user1}: "Seu segredo tá guardado comigo."
{user} disse a {user1}: "Eu durmo tranquilo(a) sabendo que você tá aqui."
{user} disse a {user1}: "Você é a minha certeza no meio da dúvida."
{user} disse a {user1}: "Eu vou te proteger, pode deixar."
{user} disse a {user1}: "Você tem minha confiança. Não desperdiça."
{user} disse a {user1}: "Eu fecho o olho e confio em você."
{user} disse a {user1}: "Você é gente como a gente."
{user} disse a {user1}: "Se todos fossem como você, esse jogo seria fácil."
{user} disse a {user1}: "Eu sei que você não me trairia."
{user} disse a {user1}: "Com você eu posso ser eu mesmo(a)."
{user} disse a {user1}: "Seu coração é bom, dá pra ver."
{user} disse a {user1}: "Você é meu voto de confiança."
{user} disse a {user1}: "Eu te escuto antes de qualquer um."
{user} disse a {user1}: "Confio no seu faro."
{user} disse a {user1}: "Você é a pessoa mais leal que conheci aqui."
{user} disse a {user1}: "Eu vou te defender, venha o que vier."
{user} disse a {user1}: "Seu nome tá riscado da minha lista."
{user} disse a {user1}: "Você tem cara de gente de palavra."
{user} disse a {user1}: "Eu conto com você na hora difícil."
{user} disse a {user1}: "Você é meu braço direito aqui."
{user} disse a {user1}: "Você me passa uma paz enorme."
{user} disse a {user1}: "Não importa o que falem, eu confio."
{user} disse a {user1}: "Eu tô do seu lado, sempre."
{user} disse a {user1}: "Com você, a minha guarda cai."
{user} disse a {user1}: "Você é o(a) único(a) que eu não questiono."
{user} disse a {user1}: "Confio tanto que me assusta."
{user} disse a {user1}: "Você é verdade num lugar de mentira."
{user} disse a {user1}: "Eu te deixo de fora de qualquer suspeita."
{user} disse a {user1}: "Seu olhar é honesto. Isso me basta."
{user} disse a {user1}: "Você é minha família aqui dentro."
{user} disse a {user1}: "A gente se entende sem falar. Confio."
{user} disse a {user1}: "Eu nunca duvidei de você."
{user} disse a {user1}: "Você tem crédito comigo."
{user} disse a {user1}: "Eu te dou minha confiança de presente."
{user} disse a {user1}: "Pode dormir tranquilo(a): eu tô contigo."
{user} disse a {user1}: "Seu jeito me acalma."
{user} disse a {user1}: "Você é luz nesse castelo escuro."
{user} disse a {user1}: "Conte comigo na próxima votação."
{user} disse a {user1}: "Eu te coloco na minha lista de confiança."
{user} disse a {user1}: "Você não tem cara de quem trai."
{user} disse a {user1}: "Tô apostando minhas fichas em você."
{user} disse a {user1}: "Você é meu norte aqui."
{user} disse a {user1}: "Se você falar, eu acredito."
{user} disse a {user1}: "Você merece toda a confiança do mundo."
{user} disse a {user1}: "Não conta pra ninguém, mas você é meu favorito(a)."
{user} disse a {user1}: "Eu te defenderia até de olhos vendados."
{user} disse a {user1}: "Você tem minha lealdade."
{user} disse a {user1}: "Eu sei quem você é. E gosto."
{user} disse a {user1}: "Você é a pessoa certa pra se ter ao lado."
{user} disse a {user1}: "Você me inspira confiança desde o começo."
{user} disse a {user1}: "Eu nunca colocaria você em risco."
{user} disse a {user1}: "Você é a exceção da minha desconfiança."
{user} disse a {user1}: "Eu te confio minha vida aqui dentro."
{user} disse a {user1}: "Você é o meu lugar seguro."
{user} disse a {user1}: "Eu vou lembrar de você quando tudo apertar."
{user} disse a {user1}: "Você me faz acreditar que dá pra confiar."
{user} disse a {user1}: "Sua palavra vale muito pra mim."
{user} disse a {user1}: "Você é verdadeiro(a). Isso é raro."
{user} disse a {user1}: "Você não precisa me provar nada."
{user} disse a {user1}: "Te dou minha confiança sem pedir nada em troca."
{user} disse a {user1}: "Eu sinto sinceridade em você."
{user} disse a {user1}: "Você é meu aliado(a) de alma."
{user} disse a {user1}: "Confio em você como confio no sol nascer."
{user} disse a {user1}: "Você é firme. Gosto disso."
{user} disse a {user1}: "Sei que você vai estar lá por mim."
{user} disse a {user1}: "Eu apostaria em você até contra o mundo."
{user} disse a {user1}: "Você é minha certeza."
{user} disse a {user1}: "Me conta tudo, eu sou túmulo."
{user} disse a {user1}: "Confio em você e não vou mudar."
{user} disse a {user1}: "Você é o tipo de pessoa que eu levo pra vida."
{user} disse a {user1}: "Eu vejo bondade em você."
{user} disse a {user1}: "Com você eu não tenho medo."
{user} disse a {user1}: "Você é um abrigo no meio da tempestade."
{user} disse a {user1}: "Eu guardo seu nome com carinho."
{user} disse a {user1}: "Você é gente fina. Confio."
{user} disse a {user1}: "Eu te escolho pra confiar."
{user} disse a {user1}: "Você é o(a) mais sincero(a) daqui."
{user} disse a {user1}: "Eu nunca vou esquecer que você me acolheu."
{user} disse a {user1}: "Você tem meu respeito e minha confiança."
{user} disse a {user1}: "Eu te enxergo. E gosto do que vejo."
{user} disse a {user1}: "Você me dá coragem."
{user} disse a {user1}: "Confio no seu julgamento."
{user} disse a {user1}: "Seu jeito é leve e honesto."
{user} disse a {user1}: "Você é meu amuleto da sorte."
{user} disse a {user1}: "Eu sei que posso contar com você."
{user} disse a {user1}: "Você é aquela pessoa que a gente não duvida."
{user} disse a {user1}: "Você me conquistou na primeira conversa."
{user} disse a {user1}: "Eu te protejo e você me protege. Combinado?"
{user} disse a {user1}: "Seu silêncio me passa confiança."
{user} disse a {user1}: "Eu vou te ouvir antes de decidir qualquer coisa."
{user} disse a {user1}: "Você tem o coração no lugar certo."
{user} disse a {user1}: "Eu não troco você por ninguém aqui."
{user} disse a {user1}: "Você é fiel a você mesmo(a). Admiro."
{user} disse a {user1}: "Eu sinto que a gente vai longe."
{user} disse a {user1}: "Você é meu refúgio."
{user} disse a {user1}: "Confiar em você foi a melhor escolha que fiz."
{user} disse a {user1}: "Você não me engana, e isso é bom."
{user} disse a {user1}: "Eu te vejo como irmão(ã)."
{user} disse a {user1}: "Você tem o olhar mais sincero daqui."
{user} disse a {user1}: "Te dou a chave do meu voto."
{user} disse a {user1}: "Você me acalma quando tudo pega fogo."
{user} disse a {user1}: "Você é aquele amigo(a) que a gente não esperava."
{user} disse a {user1}: "Eu sei que você é do bem, não precisa dizer."
{user} disse a {user1}: "Você não é como os outros."
{user} disse a {user1}: "Eu confio porque você nunca me deu motivo pra não."
{user} disse a {user1}: "Você me devolveu a fé nas pessoas."
{user} disse a {user1}: "Eu seguro sua mão até a última porta."
{user} disse a {user1}: "Você é o primeiro nome da minha lista de confiança."
{user} disse a {user1}: "Seu riso é sincero. Isso diz tudo."
{user} disse a {user1}: "Você me faz sentir em casa."
{user} disse a {user1}: "Eu não te largo por nada."
{user} disse a {user1}: "Você é um presente nesse castelo."
{user} disse a {user1}: "Você pode confiar em mim também."
{user} disse a {user1}: "Eu sou seu(sua), no jogo e fora dele."
{user} disse a {user1}: "Você é minha aposta segura."
{user} disse a {user1}: "Eu te defendo de olhos fechados."
{user} disse a {user1}: "Você é boa pessoa, e isso aqui é raro."
{user} disse a {user1}: "Seu abraço é o mais sincero do castelo."
{user} disse a {user1}: "Você é o meu voto de fé."
{user} disse a {user1}: "Eu confio em você até quando duvido de mim."
{user} disse a {user1}: "Você tem o meu sim."
{user} disse a {user1}: "Eu te conheço pouco, mas já confio muito."
{user} disse a {user1}: "Você é firme como uma rocha."
{user} disse a {user1}: "Eu sei que a gente se protege."
{user} disse a {user1}: "Você é o tipo de pessoa que eu queria ser."
{user} disse a {user1}: "Com você, eu falo sem filtro."
{user} disse a {user1}: "Você é meu ponto de equilíbrio."
{user} disse a {user1}: "Eu confio no seu instinto."
{user} disse a {user1}: "Você me passa calma e verdade."
{user} disse a {user1}: "Eu nunca vou apontar pra você."
{user} disse a {user1}: "Você é parceria de verdade."
{user} disse a {user1}: "Eu te guardo do lado esquerdo do peito."
{user} disse a {user1}: "Você é aquela certeza que eu precisava."
{user} disse a {user1}: "Eu confio. Simples assim."
{user} disse a {user1}: "Você é a pessoa que eu chamaria no desespero."
{user} disse a {user1}: "Seu caráter fala por você."
{user} disse a {user1}: "Eu vou até o fim com você."
{user} disse a {user1}: "Você merece o meu melhor."
{user} disse a {user1}: "Você é luz, não sombra."
{user} disse a {user1}: "Eu te vejo e vejo lealdade."
{user} disse a {user1}: "Você é minha pessoa aqui."
{user} disse a {user1}: "Eu confio no que você diz e no que você cala."
{user} disse a {user1}: "Você me faz querer continuar."
{user} disse a {user1}: "Você tem meu coração e meu voto."
{user} disse a {user1}: "Eu sei que você é de verdade."
{user} disse a {user1}: "Você é meu escudo humano. No bom sentido."
{user} disse a {user1}: "Eu confio em você de um jeito bobo."
{user} disse a {user1}: "Você é o ombro que eu procuro."
{user} disse a {user1}: "Eu nunca vou te dar as costas."
{user} disse a {user1}: "Você me faz rir e confiar. Combinação rara."
{user} disse a {user1}: "Seu nome é sinônimo de confiança pra mim."
{user} disse a {user1}: "Você é o meu melhor achado aqui."
{user} disse a {user1}: "Eu confio. E vou continuar confiando."
{user} disse a {user1}: "Você é aquele(a) que fica."
{user} disse a {user1}: "Eu acredito em cada palavra sua."
{user} disse a {user1}: "Você é meu time."
{user} disse a {user1}: "Eu te escolheria de novo."
{user} disse a {user1}: "Você tem meu voto de confiança eterno."
{user} disse a {user1}: "Eu confio em você de corpo e alma."
{user} disse a {user1}: "Você é o(a) parceiro(a) que eu pedi."
{user} disse a {user1}: "Eu sei que você me protege quando eu não vejo."
{user} disse a {user1}: "Você é um bom sinal nesse lugar."
{user} disse a {user1}: "Eu confio sem medo de errar."
{user} disse a {user1}: "Você é meu refúgio no castelo."
{user} disse a {user1}: "Eu sei que posso fechar os olhos perto de você."
{user} disse a {user1}: "Você me dá esperança."
{user} disse a {user1}: "Eu confio em você até o último voto."
{user} disse a {user1}: "Você é o nome que eu protejo."
{user} disse a {user1}: "Eu te dou meu voto e minha confiança."
{user} disse a {user1}: "Você é o(a) melhor que esse castelo tem."
{user} disse a {user1}: "Eu sei que estamos juntos nessa."
{user} disse a {user1}: "Você é minha aposta certa."
{user} disse a {user1}: "Eu confio em você como em um velho amigo."
{user} disse a {user1}: "Você não precisa ter medo de mim."
{user} disse a {user1}: "Eu seguro sua barra quando precisar."
{user} disse a {user1}: "Meu voto nunca vai ser seu."
{user} disse a {user1}: "Você pode contar comigo. Sempre."
{user} disse a {user1}: "Se um dia eu duvidar de você, me avisa que é loucura."
{user} disse a {user1}: "Eu boto a mão no fogo por você."
{user} disse a {user1}: "Não sei explicar, mas confio em você."
{user} disse a {user1}: "Você é Fiel. Eu sinto isso."
{user} disse a {user1}: "Pode me contar qualquer coisa. Fica entre nós."
{user} disse a {user1}: "Confio em você mais que em mim mesmo(a)."
{user} disse a {user1}: "Você nunca me deu motivo pra desconfiar."
{user} disse a {user1}: "Te defendo onde for preciso."
`);

export const SAY_PRAISE = lines(`
{user} elogiou {user1}: "Você chegou pra ganhar, hein?"
{user} disse a {user1}: "Foi a melhor apresentação da noite."
{user} disse a {user1}: "Você é incrível, sabia?"
{user} elogiou {user1} na frente do grupo.
{user} disse a {user1}: "Você tá jogando muito bem."
{user} disse a {user1}: "Seu sorriso ilumina o salão."
{user} disse a {user1}: "Que estilo, meu Deus!"
{user} disse a {user1}: "Você tem uma inteligência absurda."
{user} disse a {user1}: "Você é a pessoa mais divertida daqui."
{user} disse a {user1}: "Sem você, a gente tinha perdido tudo."
{user} disse a {user1}: "Você é um exemplo pra todo mundo."
{user} disse a {user1}: "Que coragem a sua!"
{user} disse a {user1}: "Você fala bonito demais."
{user} disse a {user1}: "Você tem uma energia contagiante."
{user} disse a {user1}: "Você é mais forte do que imagina."
{user} disse a {user1}: "Seu jeito é único."
{user} disse a {user1}: "Você é a alma desse grupo."
{user} disse a {user1}: "Você é elegante até de pijama."
{user} disse a {user1}: "Admiro demais a sua calma."
{user} disse a {user1}: "Você é brilhante, de verdade."
{user} disse a {user1}: "Seu olhar é de quem sabe o que quer."
{user} disse a {user1}: "Você é um(a) líder nato(a)."
{user} disse a {user1}: "Você arrasou!"
{user} disse a {user1}: "Seu senso de humor é o melhor do castelo."
{user} disse a {user1}: "Você tem um coração enorme."
{user} disse a {user1}: "Você é muito mais esperto(a) do que parece."
{user} disse a {user1}: "Você tem presença de cena."
{user} disse a {user1}: "Seu cabelo tá impecável hoje."
{user} disse a {user1}: "Você é uma inspiração."
{user} disse a {user1}: "Você carregou o grupo nas costas."
{user} disse a {user1}: "Que postura, que atitude!"
{user} disse a {user1}: "Você é gente boa demais."
{user} disse a {user1}: "Você faz tudo parecer fácil."
{user} disse a {user1}: "Você tem o melhor abraço do castelo."
{user} disse a {user1}: "Você é o tipo de pessoa que a gente admira."
{user} disse a {user1}: "Você tem classe."
{user} disse a {user1}: "Ninguém cozinha como você."
{user} disse a {user1}: "Você é incrível na pressão."
{user} disse a {user1}: "Você tem uma força que impressiona."
{user} disse a {user1}: "Sua risada é a trilha sonora daqui."
{user} disse a {user1}: "Você é um(a) jogador(a) de respeito."
{user} disse a {user1}: "Você tem uma elegância natural."
{user} disse a {user1}: "Você foi impecável hoje."
{user} disse a {user1}: "Você é o(a) mais bonito(a) do castelo, fácil."
{user} disse a {user1}: "Você tem uma cabeça estratégica."
{user} disse a {user1}: "Você é gentil com todo mundo. Isso é lindo."
{user} disse a {user1}: "Você tem o dom da palavra."
{user} disse a {user1}: "Você brilha sem esforço."
{user} disse a {user1}: "Você é mais corajoso(a) que todos nós."
{user} disse a {user1}: "Você salvou o dia."
{user} disse a {user1}: "Você é talentoso(a) demais."
{user} disse a {user1}: "Você tem uma calma que dá inveja."
{user} disse a {user1}: "Você é o orgulho desse grupo."
{user} disse a {user1}: "Você tem cara de campeão(ã)."
{user} disse a {user1}: "Você é a pessoa mais elegante que já vi."
{user} disse a {user1}: "Seu jeito de falar prende a atenção."
{user} disse a {user1}: "Você é um(a) guerreiro(a)."
{user} disse a {user1}: "Você deixa tudo mais leve."
{user} disse a {user1}: "Você é ótima companhia."
{user} disse a {user1}: "Você tem um charme perigoso."
{user} disse a {user1}: "Você é mais legal do que todo mundo pensa."
{user} disse a {user1}: "Você arrasa em tudo que faz."
{user} disse a {user1}: "Você é um(a) artista, sabia?"
{user} disse a {user1}: "Você tem uma alma bonita."
{user} disse a {user1}: "Você é o máximo."
{user} disse a {user1}: "Você é firme e doce ao mesmo tempo."
{user} disse a {user1}: "Você é o tipo de pessoa que muda o ambiente."
{user} disse a {user1}: "Seu instinto é certeiro."
{user} disse a {user1}: "Você é impressionante."
{user} disse a {user1}: "Você me surpreende todo dia."
{user} disse a {user1}: "Você é a melhor parte do meu dia."
{user} disse a {user1}: "Você tem uma sabedoria rara."
{user} disse a {user1}: "Você é linda(o) por dentro e por fora."
{user} disse a {user1}: "Você é incansável."
{user} disse a {user1}: "Você é o(a) mais engraçado(a) que conheço."
{user} disse a {user1}: "Você tem uma luz própria."
{user} disse a {user1}: "Você é o(a) melhor jogador(a) dessa temporada."
{user} disse a {user1}: "Você é de uma gentileza absurda."
{user} disse a {user1}: "Você é um(a) gigante."
{user} disse a {user1}: "Você honra esse castelo."
{user} disse a {user1}: "Você é tão autêntico(a)."
{user} disse a {user1}: "Seu figurino de chegada ganhou de todos."
{user} disse a {user1}: "Você tem o melhor papo daqui."
{user} disse a {user1}: "Você é aquele tipo de pessoa rara."
{user} disse a {user1}: "Você é muito sábio(a)."
{user} disse a {user1}: "Você é determinado(a) demais."
{user} disse a {user1}: "Você tem um carisma que não se ensina."
{user} disse a {user1}: "Você foi o destaque de hoje."
{user} disse a {user1}: "Você é o sal desse castelo."
{user} disse a {user1}: "Você tem mãos de ouro."
{user} disse a {user1}: "Você pensa rápido demais."
{user} disse a {user1}: "Você é o nosso MVP."
{user} disse a {user1}: "Você tem um coração de ouro."
{user} disse a {user1}: "Você é o(a) mais bem-humorado(a) daqui."
{user} disse a {user1}: "Você é tão leve de conviver."
{user} disse a {user1}: "Você é talento puro."
{user} disse a {user1}: "Você tem uma voz linda."
{user} disse a {user1}: "Você é o(a) mais corajoso(a) que conheço."
{user} disse a {user1}: "Você é um(a) fenômeno."
{user} disse a {user1}: "Você me dá orgulho."
{user} disse a {user1}: "Você é a pessoa mais generosa daqui."
{user} disse a {user1}: "Você brilhou na missão."
{user} disse a {user1}: "Você salvou a missão sozinho(a)."
{user} disse a {user1}: "Você mergulhou naquele lago como ninguém."
{user} disse a {user1}: "Você tem o melhor gosto pra roupa."
{user} disse a {user1}: "Você é esperto(a) e humilde. Raridade."
{user} disse a {user1}: "Você é um(a) excelente ouvinte."
{user} disse a {user1}: "Você faz a gente se sentir bem."
{user} disse a {user1}: "Você tem uma paciência de santo(a)."
{user} disse a {user1}: "Você é muito especial."
{user} disse a {user1}: "Você é o tipo de gente que dá gosto conhecer."
{user} disse a {user1}: "Você é tão firme nas suas ideias."
{user} disse a {user1}: "Você é um espetáculo."
{user} disse a {user1}: "Você tem uma alegria que contamina."
{user} disse a {user1}: "Você é um(a) excelente estrategista."
{user} disse a {user1}: "Você é de uma lealdade linda."
{user} disse a {user1}: "Você arrebenta nas conversas."
{user} disse a {user1}: "Você é a pessoa mais doce daqui."
{user} disse a {user1}: "Você é uma fortaleza."
{user} disse a {user1}: "Você é brilhante, e nem sabe."
{user} disse a {user1}: "Você tem uma elegância de realeza."
{user} disse a {user1}: "Você tem tudo pra chegar na final."
{user} disse a {user1}: "Você é demais, simplesmente demais."
{user} disse a {user1}: "Você me representa."
{user} disse a {user1}: "Você é um(a) craque."
{user} disse a {user1}: "Você tem uma força de vontade enorme."
{user} disse a {user1}: "Você é a pessoa mais animada daqui."
{user} disse a {user1}: "Você é luz pura."
{user} disse a {user1}: "Você é o meu destaque da semana."
{user} disse a {user1}: "Você é muito bem resolvido(a)."
{user} disse a {user1}: "Você tem a melhor gargalhada."
{user} disse a {user1}: "Você é incrível no que faz."
{user} disse a {user1}: "Você tem o dom de acalmar as pessoas."
{user} disse a {user1}: "Você é uma pessoa iluminada."
{user} disse a {user1}: "Você é muito estiloso(a)."
{user} disse a {user1}: "Você foi fera hoje."
{user} disse a {user1}: "Você tem uma cabeça muito boa."
{user} disse a {user1}: "Você é gentil até quando tá cansado(a)."
{user} disse a {user1}: "Você é o tipo de pessoa que faz falta."
{user} disse a {user1}: "Você é um(a) excelente parceiro(a)."
{user} disse a {user1}: "Você tem um brilho diferente."
{user} disse a {user1}: "Você é o charme do castelo."
{user} disse a {user1}: "Você é muito corajoso(a) de falar o que pensa."
{user} disse a {user1}: "Você é o(a) mais verdadeiro(a) de todos."
{user} disse a {user1}: "Você é de outro nível."
{user} disse a {user1}: "Você tem um jeito de princesa/príncipe."
{user} disse a {user1}: "Você é muito divertido(a) de verdade."
{user} disse a {user1}: "Você é o(a) melhor contador(a) de histórias."
{user} disse a {user1}: "Você é top, sem discussão."
{user} disse a {user1}: "Você é uma pessoa admirável."
{user} disse a {user1}: "Você tem uma energia boa demais."
{user} disse a {user1}: "Você mandou muito bem."
{user} disse a {user1}: "Você é o(a) mais habilidoso(a) daqui."
{user} disse a {user1}: "Você é um sol."
{user} disse a {user1}: "Você é a pessoa mais linda que eu já conheci."
{user} disse a {user1}: "Você é o(a) melhor companheiro(a) de quarto."
{user} disse a {user1}: "Você tem uma serenidade incrível."
{user} disse a {user1}: "Você é um(a) excelente jogador(a)."
{user} disse a {user1}: "Você é uma obra de arte."
{user} disse a {user1}: "Você é tudo de bom."
{user} disse a {user1}: "Você é fera nas palavras."
{user} disse a {user1}: "Você tem uma intuição poderosa."
{user} disse a {user1}: "Você é aquele(a) que todo mundo quer por perto."
{user} disse a {user1}: "Você é demais na pressão."
{user} disse a {user1}: "Você é um(a) estrategista brilhante."
{user} disse a {user1}: "Você é de uma sensibilidade rara."
{user} disse a {user1}: "Você tem um sorriso que desarma."
{user} disse a {user1}: "Você é fenomenal."
{user} disse a {user1}: "Você é muito querido(a) aqui."
{user} disse a {user1}: "Você brilhou mais que o lustre do salão."
{user} disse a {user1}: "Você é muito mais do que mostra."
{user} disse a {user1}: "Você é a estrela do castelo."
{user} disse a {user1}: "Você me impressiona."
{user} disse a {user1}: "Você é demais, e eu não canso de dizer."
{user} disse a {user1}: "Você tem o melhor jogo daqui."
{user} disse a {user1}: "Você é muito firme e muito doce."
{user} disse a {user1}: "Você é um exemplo de garra."
{user} disse a {user1}: "Você é muito elegante no jeito de falar."
{user} disse a {user1}: "Você tem uma coragem admirável."
{user} disse a {user1}: "Você é o talento escondido do grupo."
{user} disse a {user1}: "Você é incrível e merece ouvir isso."
{user} disse a {user1}: "Você é a melhor surpresa dessa temporada."
{user} disse a {user1}: "Você é muito sagaz."
{user} disse a {user1}: "Você tem um coração gigante."
{user} disse a {user1}: "Você é muito bom(boa) em ler pessoas."
{user} disse a {user1}: "Você é luz e é força."
{user} disse a {user1}: "Você é o(a) mais bonito(a) sem esforço."
{user} disse a {user1}: "Você é a pessoa que eu mais admiro aqui."
{user} disse a {user1}: "Você é demais, de verdade verdadeira."
{user} disse a {user1}: "Você tem uma calma que eu invejo."
{user} disse a {user1}: "Admiro seu jeito de jogar."
{user} disse a {user1}: "Você deixa esse lugar mais leve."
{user} disse a {user1}: "Poucos têm o seu carisma."
{user} disse a {user1}: "Gosto de conversar com você. De verdade."
{user} disse a {user1}: "Você é mais esperto(a) do que parece."
{user} disse a {user1}: "Seu sorriso salva o dia de qualquer um."
{user} disse a {user1}: "Você é dos bons. Dá pra ver."
{user} disse a {user1}: "Queria ter sua coragem."
{user} disse a {user1}: "Você é muito bom(boa) de papo."
{user} disse a {user1}: "Você tem estilo, hein?"
{user} disse a {user1}: "Com você por perto eu me sinto seguro(a)."
{user} disse a {user1}: "Você merece chegar longe."
{user} disse a {user1}: "Admiro quem joga limpo como você."
`);

export const SAY_JOKE = lines(`
{user} brincou com {user1}: "Se eu morrer hoje, fica com meu croissant."
{user} fez uma piada sobre o frio da Escócia e {user1} riu.
{user} brincou que {user1} tem cara de quem esconde a capa preta no armário.
{user} imitou um viking e {user1} gargalhou.
{user} disse a {user1}: "Esse castelo tem mais corrente de ar que meu ex."
{user} brincou: "{user1}, se for Traidor(a), me mata por último, tá?"
{user} disse a {user1}: "Eu vim pelo prêmio e fiquei pelo mingau."
{user} brincou: "{user1}, você ronca ou é o fantasma do castelo?"
{user} disse a {user1}: "Minha estratégia é sobreviver ao café."
{user} fez careta para {user1}: "Isso é cara de Fiel ou de fome?"
{user} disse a {user1}: "Se eu sumir, procura na cozinha."
{user} brincou: "{user1}, a gente devia abrir um podcast sobre esse castelo."
{user} disse a {user1}: "Dormi abraçado(a) com o travesseiro. Ele é Fiel."
{user} brincou: "{user1}, essa armadura te olhou. Cuidado."
{user} disse a {user1}: "Eu confio em você igual confio na previsão do tempo."
{user} fez voz de narrador: "E {user1} sobrevive mais um dia!"
{user} disse a {user1}: "Meu único Traidor é o espelho de manhã."
{user} brincou: "{user1}, você tem cara de quem rouba sobremesa."
{user} disse a {user1}: "O frio daqui congela até as fofocas."
{user} brincou: "{user1}, se o fantasma aparecer, você vai na frente."
{user} disse a {user1}: "Tô tão desconfiado(a) que desconfiei da torrada."
{user} brincou: "Se eu for banido(a), levo a lareira."
{user} disse a {user1}: "Minha tática é elogiar a comida e rezar."
{user} brincou: "{user1}, você já se perdeu no corredor? Eu três vezes."
{user} disse a {user1}: "Aqui até o gato tem cara de suspeito."
{user} fez piada: "Quem inventou esse castelo não conhecia aquecedor."
{user} disse a {user1}: "Eu vim de casaco, mas o frio veio de sobretudo."
{user} brincou: "{user1}, tua cara de sono tá mais suspeita que qualquer um."
{user} disse a {user1}: "Se o chá esfriar, é culpa dos Traidores."
{user} brincou: "{user1}, você tem seguro de vida? Pergunto por nada."
{user} disse a {user1}: "Eu só vim pra usar esse figurino."
{user} brincou: "{user1}, a gente sobrevive nem que seja por teimosia."
{user} disse a {user1}: "O castelo é lindo, mas o wi-fi é de 1500."
{user} imitou o apresentador e {user1} quase caiu da cadeira.
{user} brincou: "{user1}, minha cara de Fiel é cara de fome."
{user} disse a {user1}: "Se eu chorar, é o frio. Juro."
{user} brincou: "{user1}, o quadro da parede me segue com os olhos."
{user} disse a {user1}: "Eu tenho medo de escada. E de Traidor."
{user} brincou: "{user1}, você tá com cara de quem comeu o último bolo."
{user} disse a {user1}: "Meu plano é fazer amizade com o cozinheiro."
{user} brincou: "{user1}, relaxa. Se matarem alguém, que seja o chato."
{user} disse a {user1}: "Eu durmo de meia, casaco e esperança."
{user} brincou: "{user1}, você viu meu sapato? Perdi na chegada."
{user} disse a {user1}: "Esse castelo tem mais escada que academia."
{user} brincou: "{user1}, se você for Traidor(a), me avisa antes do café."
{user} disse a {user1}: "Vou abrir um curso: como parecer inocente."
{user} brincou: "O único que eu acuso hoje é o travesseiro duro."
{user} disse a {user1}: "Traidor mesmo é quem deixa a porta aberta no frio."
{user} brincou: "{user1}, você tem sotaque de vilão de novela."
{user} disse a {user1}: "Me chama de detetive, mas eu só acerto palpite de novela."
{user} brincou: "{user1}, cuidado que a gaita de foles tá te seguindo."
{user} disse a {user1}: "Eu confio mais no ovo mexido que em metade da mesa."
{user} brincou: "{user1}, nosso lema: ninguém morre de fome."
{user} disse a {user1}: "Queria um cobertor Fiel, esse aqui me trai."
{user} brincou: "{user1}, eu treinei cara de surpresa no espelho."
{user} disse a {user1}: "Esse castelo tem mais fantasma que hóspede."
{user} brincou: "{user1}, vamos fingir que é um spa. Um spa assombrado."
{user} disse a {user1}: "Se o prêmio for em libra, eu viro britânico(a)."
{user} brincou: "{user1}, você anda tão silencioso(a) que parece ninja."
{user} disse a {user1}: "Tô tentando parecer misterioso(a), mas só pareço com sono."
{user} brincou: "{user1}, o frio aqui tem personalidade."
{user} disse a {user1}: "Eu achei que era um castelo, mas é uma geladeira gótica."
{user} brincou: "{user1}, me empresta a sua calma? Devolvo amanhã."
{user} disse a {user1}: "Minha maior missão é achar o banheiro à noite."
{user} brincou: "{user1}, se cair um lustre, você me salva?"
{user} disse a {user1}: "Eu queria saber quem pegou meu chinelo."
{user} brincou: "{user1}, com essa cara você ganha qualquer jogo de pôquer."
{user} disse a {user1}: "Tô desconfiando até da minha sombra."
{user} brincou: "{user1}, cadê o tapete vermelho?"
{user} disse a {user1}: "Eu pedi um quarto com vista e ganhei um corvo."
{user} brincou: "{user1}, você acordou lindo(a) ou é o filtro do castelo?"
{user} disse a {user1}: "O café da manhã é minha única certeza."
{user} brincou: "{user1}, acho que o cachorro do castelo é Traidor."
{user} disse a {user1}: "Eu treinei meu discurso de despedida. Chorei sozinho(a)."
{user} brincou: "{user1}, relaxa, eu só mordo no café."
{user} disse a {user1}: "Eu troco meu voto por uma sopa quente."
{user} brincou: "{user1}, a gente devia ganhar prêmio só por aguentar o frio."
{user} disse a {user1}: "Minha capa preta é o edredom."
{user} brincou: "{user1}, você tem cara de quem conversa com armadura."
{user} disse a {user1}: "Se eu for Traidor(a), sou o(a) mais incompetente da história."
{user} brincou: "{user1}, você tem um talento pra aparecer do nada."
{user} disse a {user1}: "Eu confio em você igual confio em escada de castelo."
{user} brincou: "{user1}, o espelho do corredor me deu medo."
{user} disse a {user1}: "Vim pelo dinheiro, fico pela fofoca."
{user} brincou: "{user1}, você viu o tamanho dessa lareira? Cabe um sofá."
{user} disse a {user1}: "Eu achei que ia ser glamour, mas é bota de chuva."
{user} brincou: "{user1}, se o dragão aparecer, finge de morto(a)."
{user} disse a {user1}: "Eu só sei que nada sei. E que tô com fome."
{user} brincou: "{user1}, você anda igual detetive de filme antigo."
{user} disse a {user1}: "Se me matarem, avisa minha mãe que eu fui chique."
{user} brincou: "{user1}, vamos apostar quem congela primeiro?"
{user} disse a {user1}: "Eu sou Fiel até no amor pela comida."
{user} brincou: "{user1}, esse chá tem gosto de segredo."
{user} disse a {user1}: "Minha estratégia é ser tão chato(a) que ninguém me mate."
{user} brincou: "{user1}, você tem uma aura de vilão(ã) charmoso(a)."
{user} disse a {user1}: "Eu passei a noite contando os pinguins do teto."
{user} brincou: "{user1}, você é mais misterioso(a) que o cardápio."
{user} disse a {user1}: "Eu achei um fantasma. Era meu reflexo."
{user} brincou: "{user1}, se sair viva(o) daqui, a gente abre um bar."
{user} disse a {user1}: "Eu vou ganhar pelo cansaço dos outros."
{user} brincou: "{user1}, a gente tá num filme de terror com orçamento de novela."
{user} disse a {user1}: "Eu trouxe cinco casacos e todos são inúteis."
{user} brincou: "{user1}, seu cabelo sobreviveu à neblina? Parabéns."
{user} disse a {user1}: "Eu tenho um plano infalível: falhar com estilo."
{user} brincou: "{user1}, se o apresentador sorrir, a gente corre."
{user} disse a {user1}: "Minha cama range tanto que parece Traidor(a) andando."
{user} brincou: "{user1}, eu confiei no mapa e fui parar no porão."
{user} disse a {user1}: "Queria um castelo com micro-ondas."
{user} brincou: "{user1}, você viu a cara do cozinheiro? Suspeitíssimo."
{user} disse a {user1}: "Eu sou do time que come primeiro e desconfia depois."
{user} brincou: "{user1}, se o fantasma tiver voto, eu tô perdido(a)."
{user} disse a {user1}: "Eu nasci pra reality, só não pro frio."
{user} brincou: "{user1}, vamos fazer um pacto: ninguém rouba o cobertor."
{user} disse a {user1}: "Aqui até a cortina tem cara de traição."
{user} brincou: "{user1}, você tem sobrancelha de quem sabe de algo."
{user} disse a {user1}: "Se eu gritar à noite, foi uma aranha."
{user} brincou: "{user1}, amanhã eu desço de armadura."
{user} disse a {user1}: "Minha única aliança é com a garrafa térmica."
{user} brincou: "{user1}, cuidado, o corvo da janela anota tudo."
{user} disse a {user1}: "Eu durmo com um olho aberto e outro remelento."
{user} brincou: "{user1}, você sempre ri da minha piada ruim. Obrigado(a)."
{user} disse a {user1}: "Juro, o castelo tem mais porta do que saída."
{user} brincou: "{user1}, que tal fingir que somos da realeza?"
{user} disse a {user1}: "Eu trouxe meu bom humor. Esqueci o protetor de frio."
{user} brincou: "{user1}, seu olhar me dá medo. Mas é um medo bom."
{user} disse a {user1}: "Eu vou fazer um documentário: sobrevivendo às escadas."
{user} brincou: "{user1}, você já viu um escocês de saia correndo? Eu vi."
{user} disse a {user1}: "Nesse frio, até a mentira sai com fumaça."
{user} brincou: "{user1}, se eu ganhar, compro um aquecedor pro castelo."
{user} disse a {user1}: "Eu sou péssimo(a) em mentir, então só como."
{user} brincou: "{user1}, você parece personagem de livro de mistério."
{user} disse a {user1}: "Meu jogo é igual chá inglês: morno e confuso."
{user} brincou: "{user1}, a gente devia cobrar ingresso desse drama."
{user} disse a {user1}: "Eu já tô falando com as plantas. Elas me entendem."
{user} brincou: "{user1}, o mordomo me olhou estranho. Será Traidor?"
{user} disse a {user1}: "Eu só confio em quem divide a sobremesa."
{user} brincou: "{user1}, você tem cara de quem ganharia um Oscar aqui."
{user} disse a {user1}: "Se o castelo falasse, pediria férias."
{user} brincou: "{user1}, vamos combinar de não morrer hoje?"
{user} disse a {user1}: "Minha estratégia secreta: dormir cedo."
{user} brincou: "{user1}, seu casaco tem mais bolso que o castelo tem quarto."
{user} disse a {user1}: "Eu tô tão perdido(a) que confio até no GPS da cozinha."
{user} brincou: "{user1}, quem ronca mais, você ou o fantasma?"
{user} disse a {user1}: "A única coisa que eu mato aqui é saudade."
{user} brincou: "{user1}, o lago tá tão frio que os peixes usam gorro."
{user} disse a {user1}: "Eu tenho cara de Fiel e alma de fofoqueiro(a)."
{user} brincou: "{user1}, se me chamarem na torre, vou de pantufa."
{user} disse a {user1}: "Eu não sou suspeito(a), sou só esquisito(a)."
{user} brincou: "{user1}, a gente devia dar nome pras armaduras."
{user} disse a {user1}: "Juro que vi um fantasma. Ou era a cortina."
{user} brincou: "{user1}, o prêmio é em dinheiro ou em mingau?"
{user} disse a {user1}: "Meu superpoder é sumir quando tem louça."
{user} brincou: "{user1}, relaxa, eu só fico perigoso(a) com fome."
{user} disse a {user1}: "Se eu for banido(a), quero trilha sonora épica."
{user} brincou: "{user1}, seu segredo tá seguro. Eu esqueço tudo."
{user} disse a {user1}: "Eu trouxe um dicionário de gaélico e não sei ler."
{user} brincou: "{user1}, fala baixo que a parede escuta."
{user} disse a {user1}: "Eu achei a biblioteca. Me perdi nela por uma hora."
{user} brincou: "{user1}, a neblina tá tão grossa que dá pra passar manteiga."
{user} disse a {user1}: "Eu vou escrever um livro: memórias de um(a) desconfiado(a)."
{user} brincou: "{user1}, você tem o sorriso mais suspeito e mais bonito."
{user} disse a {user1}: "Eu confio no meu instinto. Ele erra muito, mas confio."
{user} brincou: "{user1}, amanhã a gente faz yoga no salão?"
{user} disse a {user1}: "O frio daqui é tipo ex: chega sem avisar."
{user} brincou: "{user1}, você me lembra aquele tio que conta piada ruim."
{user} disse a {user1}: "Se eu sumir, fui tomar banho quente. Voltei em três dias."
{user} brincou: "{user1}, eu sou tão Fiel que peço desculpa pra porta."
{user} disse a {user1}: "Eu queria um castelo com elevador."
{user} brincou: "{user1}, a gente ganha nem que seja no grito."
{user} disse a {user1}: "Meu medo não é Traidor, é a sopa de ontem."
{user} brincou: "{user1}, se eu tiver cara de culpa, é gastrite."
{user} disse a {user1}: "Aqui eu aprendi a desconfiar até do relógio."
{user} brincou: "{user1}, você tem ombro de chorar e de rir."
{user} disse a {user1}: "Eu cheguei cheio(a) de pose e já perdi metade."
{user} brincou: "{user1}, se tiver mais uma escada, eu desisto."
{user} disse a {user1}: "Eu durmo de gorro. Não me julga."
{user} brincou: "{user1}, você é o tipo que sobrevive a filme de terror."
{user} disse a {user1}: "A gente precisa de um bingo das fofocas."
{user} brincou: "{user1}, eu confio em você e na manteiga. Nessa ordem."
{user} disse a {user1}: "Eu não sei jogar isso, mas sei fazer amigos."
{user} brincou: "{user1}, pior que Traidor é ronco de colega de quarto."
{user} disse a {user1}: "Eu sou tão desastrado(a) que Traidor nenhum me recruta."
{user} brincou: "{user1}, amanhã eu desço de peruca pra confundir geral."
{user} brincou com {user1}: "Se eu for Traidor(a), você é o Papa."
{user} disse a {user1}: "Se me matarem hoje, fica com minhas meias."
{user} brincou: "{user1}, com essa cara de santo(a), só pode ser Traidor(a)."
{user} riu com {user1}: "Esse castelo tem mais fofoca que grupo de família."
{user} brincou: "{user1}, você dorme de capa?"
{user} disse a {user1}: "Se ficar mais tenso aqui, eu viro Traidor(a) de raiva."
{user} disse a {user1}: "Você anda mais sumido(a) que Wi-Fi de castelo."
{user} brincou com {user1}: "Meu sexto sentido diz que você deve dinheiro pra alguém."
{user} disse a {user1}: "Relaxa. Se você morrer, eu choro bonito."
{user} brincou: "{user1}, piscar muito é crime aqui, viu?"
{user} disse a {user1}: "Juro que sou Fiel. Palavra de escoteiro(a) falso(a)."
{user} disse a {user1}: "Com essa sua cara de paisagem, tu é cenário."
{user} brincou: "Se {user1} for Traidor(a), eu mudo de nome."
{user} disse a {user1}: "O clima aqui tá igual velório com open bar."
{user} disse a {user1}: "Vou escrever seu nome só pra ver sua cara."
{user} brincou com {user1}: "Quem ronca à noite é suspeito. Aviso."
{user} disse a {user1}: "Isso aqui é reality ou terapia em grupo?"
{user} brincou: "{user1}, você é tão Fiel que chega a ser suspeito."
{user} disse a {user1}: "Se o drama pagasse, a gente já tava rico."
{user} brincou com {user1}: "Esse sorriso aí tá valendo quanto?"
{user} disse a {user1}: "Traidor(a) eu? Eu mal consigo trair a dieta."
{user} disse a {user1}: "Te vejo na final. Ou no velório. O que vier."
`);

export const SAY_ALLIANCE = lines(`
{user} puxou {user1} para um canto e propôs uma aliança.
{user} ofereceu a {user1} um pacto: um protege o outro.
{user} disse a {user1}: "Eu e você, juntos nessa. Fechado?"
{user} estendeu a mão para {user1}: "Aliança?"
{user} disse a {user1}: "Vamos jogar juntos até o fim?"
{user} cochichou com {user1}: "Eu cuido de você e você de mim."
{user} disse a {user1}: "Precisamos um do outro. Aliança?"
{user} propôs a {user1}: "A gente vota junto daqui pra frente."
{user} disse a {user1}: "Quero você do meu lado. Topa?"
{user} disse a {user1}: "Juntos a gente vai mais longe."
{user} chamou {user1} no jardim: "Vamos fechar uma parceria?"
{user} disse a {user1}: "Minha palavra é sua. E a sua?"
{user} disse a {user1}: "Eu te protejo na mesa. Você me protege?"
{user} propôs a {user1}: "Uma aliança só nossa, sem ninguém saber."
{user} disse a {user1}: "Eu confio em você. Vamos juntos?"
{user} disse a {user1}: "Dupla imbatível: eu e você."
{user} disse a {user1}: "Vamos fazer um pacto de sangue? Sem sangue."
{user} disse a {user1}: "Eu não quero passar por isso sozinho(a). E você?"
{user} disse a {user1}: "Fecha comigo e ninguém te toca."
{user} disse a {user1}: "Eu e você até a final. Topa?"
{user} propôs a {user1}: "A gente divide informação e voto."
{user} disse a {user1}: "Pensa bem: aliança comigo é segurança."
{user} disse a {user1}: "Vamos juntos, que a gente se entende."
{user} disse a {user1}: "Eu quero você no meu time."
{user} disse a {user1}: "Proposta: você me avisa, eu te aviso."
{user} disse a {user1}: "Seja meu(minha) parceiro(a) de castelo."
{user} disse a {user1}: "Aliança secreta: só nós dois sabemos."
{user} disse a {user1}: "Um por todos e todos por um. Nós dois, no caso."
{user} disse a {user1}: "Eu vejo em você um(a) aliado(a) perfeito(a)."
{user} disse a {user1}: "Me dá sua mão e seu voto."
{user} disse a {user1}: "Vamos combinar de nunca votar um no outro."
{user} disse a {user1}: "Você e eu contra o mundo. Aceita?"
{user} disse a {user1}: "Tá precisando de um(a) aliado(a)? Aqui."
{user} disse a {user1}: "Eu vou até o fim com você, se você for comigo."
{user} disse a {user1}: "A gente fecha hoje e ninguém abre."
{user} disse a {user1}: "Quero construir algo com você nesse jogo."
{user} disse a {user1}: "Juntos, a gente é mais forte."
{user} disse a {user1}: "Vamos jogar em dupla, na surdina."
{user} disse a {user1}: "Te ofereço minha lealdade. Quer?"
{user} disse a {user1}: "Eu te escolhi. Você me escolhe?"
{user} disse a {user1}: "Pacto fechado com aperto de mão?"
{user} disse a {user1}: "Eu cubro suas costas, você cobre as minhas."
{user} disse a {user1}: "Vamos nos proteger na mesa, combinado?"
{user} disse a {user1}: "Uma aliança com você me deixaria em paz."
{user} disse a {user1}: "Quer ser meu(minha) cúmplice? Do bem."
{user} disse a {user1}: "Eu preciso de alguém de confiança. É você."
{user} disse a {user1}: "Proponho: informação compartilhada, voto combinado."
{user} disse a {user1}: "Vamos juntos, e o resto que se vire."
{user} disse a {user1}: "Eu seria uma ótima dupla pra você."
{user} disse a {user1}: "Tô te chamando pra minha aliança."
{user} disse a {user1}: "Vamos selar isso com um brinde?"
{user} disse a {user1}: "A gente pode ir longe se ficar junto."
{user} disse a {user1}: "Me deixa ser seu escudo e você o meu."
{user} disse a {user1}: "Eu quero você na minha lista de proteção."
{user} disse a {user1}: "Vamos fazer uma aliança de verdade, não de fachada."
{user} disse a {user1}: "Você topa jogar comigo até o fim?"
{user} disse a {user1}: "Juntos a gente enxerga melhor os Traidores."
{user} disse a {user1}: "Um pacto: ninguém escreve o nome do outro."
{user} disse a {user1}: "Eu quero você comigo na mesa final."
{user} disse a {user1}: "Proposta indecente: aliança eterna."
{user} disse a {user1}: "Eu te ofereço minha confiança. Aceita?"
{user} disse a {user1}: "Vamos jogar juntos e rir de tudo depois."
{user} disse a {user1}: "Me dá um motivo pra não fazer aliança com você. Não tem."
{user} disse a {user1}: "Quer fechar comigo? Tô falando sério."
{user} disse a {user1}: "Você e eu somos parecidos. Vamos juntos."
{user} disse a {user1}: "Aliança? Sim ou claro?"
{user} disse a {user1}: "Eu não confio em quase ninguém, mas em você sim. Aliança?"
{user} disse a {user1}: "Juntos a gente sobrevive mais uma semana."
{user} disse a {user1}: "Eu quero ter você por perto quando apertar."
{user} disse a {user1}: "Vamos ser a dupla que ninguém espera?"
{user} disse a {user1}: "Te ofereço proteção e amizade."
{user} disse a {user1}: "Somos dois contra o caos. Topa?"
{user} disse a {user1}: "A gente troca figurinha e voto."
{user} disse a {user1}: "Vem comigo que a gente chega longe."
{user} disse a {user1}: "Uma parceria discreta, que tal?"
{user} disse a {user1}: "Eu te chamo pra ser meu braço direito."
{user} disse a {user1}: "Vamos fechar antes que alguém feche com você."
{user} disse a {user1}: "Nossa aliança pode ser nosso trunfo."
{user} disse a {user1}: "Eu não quero te ver do outro lado. Vem pro meu."
{user} disse a {user1}: "Quer ser minha dupla nessa loucura?"
{user} disse a {user1}: "Eu garanto seu voto se você garantir o meu."
{user} disse a {user1}: "Vamos jogar limpo, juntos."
{user} disse a {user1}: "Te proponho um pacto de sobrevivência."
{user} disse a {user1}: "Eu quero dividir essa jornada com você."
{user} disse a {user1}: "Nós dois somos o time mais forte daqui."
{user} disse a {user1}: "Me aceita como aliado(a)?"
{user} disse a {user1}: "Juntos a gente enfrenta qualquer mesa."
{user} disse a {user1}: "Vamos combinar o voto antes de cada mesa?"
{user} disse a {user1}: "Você tem meu voto garantido se fechar comigo."
{user} disse a {user1}: "Proponho sermos inseparáveis no jogo."
{user} disse a {user1}: "Eu seguro sua mão se você segurar a minha."
{user} disse a {user1}: "Aliança de dois é mais difícil de trair."
{user} disse a {user1}: "Vamos juntos até alguém nos separar. E ninguém vai."
{user} disse a {user1}: "Eu quero ser seu(sua) primeiro(a) aliado(a)."
{user} disse a {user1}: "A gente se fortalece junto."
{user} disse a {user1}: "Fecha comigo e eu te conto tudo que sei."
{user} disse a {user1}: "Eu te ofereço minha lealdade e meu voto."
{user} disse a {user1}: "Uma aliança nossa vai assustar muita gente."
{user} disse a {user1}: "Juntos, a gente vê o jogo inteiro."
{user} disse a {user1}: "Vamos fazer história juntos aqui?"
{user} disse a {user1}: "Eu não trairia você. Aliança?"
{user} disse a {user1}: "Seremos a dupla dinâmica do castelo."
{user} disse a {user1}: "Te chamo pra ser meu(minha) cúmplice de sobrevivência."
{user} disse a {user1}: "A gente pode proteger um ao outro sem ninguém saber."
{user} disse a {user1}: "Quero você comigo quando a coisa ficar feia."
{user} disse a {user1}: "Eu e você: aliança fechada?"
{user} disse a {user1}: "Me dá sua palavra que eu te dou a minha."
{user} disse a {user1}: "Juntos, a gente engana até o destino."
{user} disse a {user1}: "Eu confio no seu jogo. Vamos unir?"
{user} disse a {user1}: "Eu fico mais forte com você do lado."
{user} disse a {user1}: "Vamos fazer um pacto de lealdade?"
{user} disse a {user1}: "Nossa aliança começa agora, se você quiser."
{user} disse a {user1}: "A gente se ajuda e ninguém precisa saber."
{user} disse a {user1}: "Quer ser meu(minha) aliado(a) número um?"
{user} disse a {user1}: "Proponho uma aliança com prazo: até a final."
{user} disse a {user1}: "Se a gente se unir, ninguém segura."
{user} disse a {user1}: "Vamos cuidar um do outro?"
{user} disse a {user1}: "Eu quero dividir o prêmio com você, se chegarmos lá."
{user} disse a {user1}: "Eu te chamo pra aliança antes que seja tarde."
{user} disse a {user1}: "Juntos a gente aguenta qualquer tempestade."
{user} disse a {user1}: "Seu voto e o meu, sempre juntos. Topa?"
{user} disse a {user1}: "Eu tô montando meu time. Você é a primeira escolha."
{user} disse a {user1}: "Dupla fechada? Só depende de você."
{user} disse a {user1}: "Eu prometo não te deixar na mão."
{user} disse a {user1}: "A gente é mais forte junto, você sabe."
{user} disse a {user1}: "Quer fazer parte do meu plano?"
{user} disse a {user1}: "Eu te ofereço uma aliança de coração."
{user} disse a {user1}: "Vamos ser os últimos a sair, juntos."
{user} disse a {user1}: "Fecha comigo que eu não te abandono."
{user} disse a {user1}: "Eu quero sua amizade e seu voto. Nessa ordem."
{user} disse a {user1}: "Proposta: a gente se protege em silêncio."
{user} disse a {user1}: "Uma aliança com você seria um presente."
{user} disse a {user1}: "Eu quero jogar com você, não contra você."
{user} disse a {user1}: "Vamos ser o time que ninguém vê chegando."
{user} disse a {user1}: "Eu tenho um plano, e ele inclui você."
{user} disse a {user1}: "Juntos a gente entende melhor esse castelo."
{user} disse a {user1}: "Me dá um sim e eu te dou minha lealdade."
{user} disse a {user1}: "Eu e você: o pacto mais forte daqui."
{user} disse a {user1}: "Vamos jogar como um só?"
{user} disse a {user1}: "Eu vou proteger você com unhas e dentes. Aceita?"
{user} disse a {user1}: "A gente pode se salvar juntos."
{user} disse a {user1}: "Aliança? Prometo ser leal."
{user} disse a {user1}: "Você me parece a pessoa certa pra fechar."
{user} disse a {user1}: "Eu quero você na minha retaguarda."
{user} disse a {user1}: "Vamos dividir o peso desse jogo?"
{user} disse a {user1}: "Eu te chamo pra aliança com o coração aberto."
{user} disse a {user1}: "Juntos a gente vence o medo."
{user} disse a {user1}: "Eu tenho um lugar pra você do meu lado."
{user} disse a {user1}: "Vamos fazer um pacto antes da próxima mesa."
{user} disse a {user1}: "Eu não quero outro(a) aliado(a). Quero você."
{user} disse a {user1}: "Te ofereço o meu voto em troca do seu."
{user} disse a {user1}: "Uma aliança discreta e firme. Que tal?"
{user} disse a {user1}: "Eu quero seguir junto com você."
{user} disse a {user1}: "Vamos fechar e mostrar pra eles como se joga."
{user} disse a {user1}: "Eu sei que a gente combina. Aliança?"
{user} disse a {user1}: "Proponho um pacto de proteção mútua."
{user} disse a {user1}: "Me escolhe como aliado(a) que eu te escolho também."
{user} disse a {user1}: "Juntos a gente chega à final, eu sinto."
{user} disse a {user1}: "Vamos nos blindar um ao outro?"
{user} disse a {user1}: "Eu fecho contigo agora, sem pensar duas vezes."
{user} disse a {user1}: "Aliança? Eu levo o chá, você leva a estratégia."
{user} disse a {user1}: "Você me passa confiança. Vamos juntos?"
{user} disse a {user1}: "Eu quero você como minha dupla fixa."
{user} disse a {user1}: "Te ofereço amizade de verdade nesse jogo."
{user} disse a {user1}: "A gente pode ser o terror dos Traidores."
{user} disse a {user1}: "Eu te chamo pro meu lado da mesa."
{user} disse a {user1}: "Vamos jogar juntos e confiar um no outro?"
{user} disse a {user1}: "Proposta simples: lealdade até o fim."
{user} disse a {user1}: "Eu vejo futuro na nossa aliança."
{user} disse a {user1}: "Fecha comigo e a gente vence junto."
{user} disse a {user1}: "Eu não quero te perder pra outra aliança."
{user} disse a {user1}: "Eu e você, o time que ninguém separa."
{user} disse a {user1}: "Vamos nos unir antes que nos dividam."
{user} disse a {user1}: "Te dou meu voto e minha palavra."
{user} disse a {user1}: "Uma aliança nossa muda esse jogo."
{user} disse a {user1}: "Eu te convido pra ser meu(minha) parceiro(a)."
{user} disse a {user1}: "Juntos a gente é imbatível. Topa?"
{user} disse a {user1}: "Eu preciso de você e você de mim."
{user} disse a {user1}: "Vamos jogar em equipe daqui pra frente?"
{user} disse a {user1}: "Eu tô te oferecendo um porto seguro."
{user} disse a {user1}: "Aceita ser meu(minha) aliado(a) de confiança?"
{user} disse a {user1}: "Vamos fazer um pacto que ninguém vai saber."
{user} disse a {user1}: "Eu quero você comigo até a última vela."
{user} disse a {user1}: "Juntos a gente atravessa esse castelo."
{user} disse a {user1}: "Fechado? Eu tô pronto(a) pra ser seu(sua) aliado(a)."
{user} disse a {user1}: "Proponho unir forças. O que acha?"
{user} disse a {user1}: "Eu escolho você. Agora é sua vez de escolher."
{user} disse a {user1}: "Uma aliança de dois, forte como castelo."
{user} disse a {user1}: "Eu quero dividir essa loucura com você."
{user} disse a {user1}: "A gente se protege e se diverte. Fechou?"
{user} disse a {user1}: "Vem ser meu(minha) aliado(a)?"
{user} disse a {user1}: "Eu cuido de você, você cuida de mim. Fechado?"
{user} estendeu o mindinho a {user1}: "Pacto?"
{user} disse a {user1}: "Quero você do meu lado até o fim."
{user} disse a {user1}: "Juntos a gente é mais forte. Topa?"
{user} disse a {user1}: "Vamos fazer um time? Só gente de confiança."
{user} disse a {user1}: "Eu nunca voto em você. Você promete o mesmo?"
{user} disse a {user1}: "Sinto que posso confiar em você. Aliança?"
{user} disse a {user1}: "Proposta séria: a gente fecha junto."
{user} disse a {user1}: "Me dá sua mão. Daqui pra frente, parceria."
{user} disse a {user1}: "Vem comigo. Eu não abandono aliado(a)."
{user} disse a {user1}: "Você e eu, protegendo um ao outro. Bora?"
{user} disse a {user1}: "Te escolhi pra ser meu braço direito."
{user} disse a {user1}: "Quero alguém leal. Acho que é você."
`);
