import { lines } from './lines';

/** Falas do jogador: {user} = jogador, {user1} = com quem fala, {user2} = de quem se fala. */

export const SAY_ASK = lines(`
{user} perguntou a {user1}, em particular: "Em quem você desconfia?"
{user} cochichou: "{user1}, me fala um nome."
{user} puxou {user1} de lado: "Quem te dá arrepio aqui?"
{user} perguntou: "{user1}, se fosse votar agora, votava em quem?"
{user} disse a {user1}: "Me conta sua lista. Fica entre nós."
{user} perguntou a {user1}: "Quem você acha que sobe na torre?"
{user} disse a {user1}: "Você observa muito. Quem te incomoda?"
{user} perguntou baixinho: "{user1}, quem é Traidor pra você?"
{user} disse a {user1}: "Confio no seu faro. Quem é?"
{user} perguntou a {user1}: "Tem alguém que você não engole?"
{user} chamou {user1} no corredor: "Me diz quem tá estranho."
{user} perguntou: "{user1}, de quem você fica longe?"
{user} disse a {user1}: "Um nome. Só um nome."
{user} perguntou a {user1}: "Quem você tiraria hoje?"
{user} disse a {user1}: "Vamos trocar suspeitas? Você primeiro."
{user} perguntou: "{user1}, qual é o seu palpite?"
{user} disse a {user1}: "Me ajuda a fechar minha lista."
{user} perguntou a {user1}: "Quem mentiu pra você aqui?"
{user} disse a {user1}: "Seu instinto aponta pra quem?"
{user} perguntou: "{user1}, quem você vigia de noite?"
{user} disse a {user1}: "Fala sem medo: quem é o problema?"
{user} perguntou a {user1}: "Quem mudou de comportamento?"
{user} disse a {user1}: "Eu te conto o meu se você me contar o seu."
{user} perguntou: "{user1}, quem você acha que tá sobrando aqui?"
{user} disse a {user1}: "Se você tivesse que apostar, apostava em quem?"
{user} perguntou a {user1}: "Quem ri na hora errada pra você?"
{user} disse a {user1}: "Me ajuda a enxergar o jogo."
{user} perguntou: "{user1}, quem tá manipulando a mesa?"
{user} disse a {user1}: "Quem você não deixaria perto da sua cama?"
{user} perguntou a {user1}: "Tem alguém que você desconfia calado(a)?"
{user} disse a {user1}: "Juro que não conto. Quem é?"
{user} perguntou: "{user1}, que nome não sai da sua cabeça?"
{user} disse a {user1}: "Você viu alguma coisa estranha essa noite?"
{user} perguntou a {user1}: "Quem você acha que protege quem?"
{user} disse a {user1}: "Quero saber sua opinião antes de votar."
{user} perguntou: "{user1}, quem é a cobra desse castelo?"
{user} disse a {user1}: "Me dá um nome pra eu ficar de olho."
{user} perguntou a {user1}: "Quem te olhou torto hoje?"
{user} disse a {user1}: "Você tem cara de quem já sabe. Fala."
{user} perguntou: "{user1}, quem você acha que vai morrer?"
{user} disse a {user1}: "Quem o seu coração diz que é Traidor?"
{user} perguntou a {user1}: "Em quem você não votaria nunca?"
{user} disse a {user1}: "E aí, quem tá no topo da sua lista?"
{user} perguntou: "{user1}, quem fala demais e diz de menos?"
{user} disse a {user1}: "Você sabe de algo que eu não sei?"
{user} perguntou a {user1}: "Quem te deixou desconfiado(a) ontem?"
{user} disse a {user1}: "Me fala quem você acha que é da torre."
{user} perguntou: "{user1}, quem você evita nas conversas?"
{user} disse a {user1}: "Vamos juntar nossas desconfianças?"
{user} perguntou a {user1}: "Quem tá calmo(a) demais pra você?"
{user} disse a {user1}: "Quero ouvir sua teoria."
{user} perguntou: "{user1}, quem ganhou com a última morte?"
{user} disse a {user1}: "Me fala o nome que você não teve coragem de falar na mesa."
{user} perguntou a {user1}: "Quem você acha que tá jogando sozinho(a)?"
{user} disse a {user1}: "Me dá uma pista. Qualquer uma."
{user} perguntou: "{user1}, quem te dá medo de verdade?"
{user} disse a {user1}: "Seu olhar tá apontando pra alguém. Pra quem?"
{user} perguntou a {user1}: "Quem você acha que é Fiel de fachada?"
{user} disse a {user1}: "Me conta quem tá na sua mira."
{user} perguntou: "{user1}, de quem é o jogo mais estranho?"
{user} disse a {user1}: "Não vou te julgar. Só me fala quem."
{user} perguntou a {user1}: "Quem nunca é alvo e devia ser?"
{user} disse a {user1}: "Me ajuda a não errar hoje."
{user} perguntou: "{user1}, quem você acha que sabe demais?"
{user} disse a {user1}: "Quem tá jogando com a gente de bobo?"
{user} perguntou a {user1}: "Quem você desconfia e ainda não falou?"
{user} disse a {user1}: "Eu preciso de uma segunda opinião."
{user} perguntou: "{user1}, quem é o nome da vez pra você?"
{user} disse a {user1}: "Diz aí, quem é que não te convence?"
{user} perguntou a {user1}: "Se o castelo pegasse fogo, quem salvava a própria pele primeiro?"
{user} disse a {user1}: "Você repara em tudo. O que reparou?"
{user} perguntou: "{user1}, quem sumiu ontem à noite?"
{user} disse a {user1}: "Me fala quem, que eu guardo como segredo."
{user} perguntou a {user1}: "Quem você acha que puxou o voto errado?"
{user} disse a {user1}: "Me ajuda: quem mente melhor aqui?"
{user} perguntou: "{user1}, quem você não quer na final?"
{user} disse a {user1}: "Eu sei que você tem um nome. Solta."
{user} perguntou a {user1}: "Quem deixa você com o pé atrás?"
{user} disse a {user1}: "Só entre nós: quem é?"
{user} perguntou: "{user1}, quem faz jogo duplo?"
{user} disse a {user1}: "Me passa sua leitura do castelo."
{user} perguntou a {user1}: "Quem você vê cochichando demais?"
{user} disse a {user1}: "Vamos comparar listas?"
{user} perguntou: "{user1}, se você errasse, em quem errava?"
{user} disse a {user1}: "Você me dá sua suspeita e eu te dou a minha."
{user} perguntou a {user1}: "Quem você ouviu falando da torre?"
{user} disse a {user1}: "Me conta quem te tira o sono."
{user} perguntou: "{user1}, qual é o nome mais óbvio pra você?"
{user} disse a {user1}: "E o menos óbvio? Quem seria?"
{user} perguntou a {user1}: "Quem você acha que vai te trair?"
{user} disse a {user1}: "Diz quem você acha, sem filtro."
{user} perguntou: "{user1}, quem votou estranho ontem?"
{user} disse a {user1}: "Tô perdido(a). Me ajuda com um nome."
{user} perguntou a {user1}: "Quem te pareceu falso(a) no café?"
{user} disse a {user1}: "Você confia em quem? E desconfia de quem?"
{user} perguntou: "{user1}, quem tem cara de capa preta?"
{user} disse a {user1}: "Você anda quieto(a). Tá pensando em quem?"
{user} perguntou a {user1}: "Quem ganha se a gente errar hoje?"
{user} disse a {user1}: "Me fala o nome, que eu investigo."
{user} perguntou: "{user1}, quem faz o papel de bonzinho(a)?"
{user} disse a {user1}: "Me confia um nome."
{user} perguntou a {user1}: "Quem você acha que manda na torre?"
{user} disse a {user1}: "Olha pros lados e me diz quem."
{user} perguntou: "{user1}, quem não chorou pela vítima?"
{user} disse a {user1}: "Quero saber quem você teme."
{user} perguntou a {user1}: "Quem tá sempre por perto das mortes?"
{user} disse a {user1}: "Me dá sua suspeita mais forte."
{user} perguntou: "{user1}, quem te deu uma resposta ensaiada?"
{user} disse a {user1}: "Seu voto de hoje é pra quem?"
{user} perguntou a {user1}: "Quem você acha que tá com medo?"
{user} disse a {user1}: "Vamos pensar juntos: quem é?"
{user} perguntou: "{user1}, quem tá se escondendo atrás dos outros?"
{user} disse a {user1}: "Tem um nome entalado aí. Solta."
{user} perguntou a {user1}: "Quem mudou de lado?"
{user} disse a {user1}: "Me fala quem você não defende nunca."
{user} perguntou: "{user1}, quem é mais perigoso(a) aqui?"
{user} disse a {user1}: "Me dá o nome que você votaria de olhos fechados."
{user} perguntou a {user1}: "Quem você viu subindo a escada?"
{user} disse a {user1}: "Se você me contar, eu voto com você."
{user} perguntou: "{user1}, quem ninguém percebe e devia?"
{user} disse a {user1}: "A gente precisa acertar. Quem é?"
{user} perguntou a {user1}: "Quem te deu uma sensação ruim hoje?"
{user} disse a {user1}: "Me fala a sua maior desconfiança."
{user} perguntou: "{user1}, quem você acha que é parceiro(a) de quem?"
{user} disse a {user1}: "Quem você acha que foi recrutado(a)?"
{user} perguntou a {user1}: "Quem fala demais de lealdade?"
{user} disse a {user1}: "Me conta o que você não contou pra ninguém."
{user} perguntou: "{user1}, quem sabe mentir olhando no olho?"
{user} disse a {user1}: "Quero sua sinceridade: quem?"
{user} perguntou a {user1}: "Quem você acha que vai votar em mim?"
{user} disse a {user1}: "Me fala quem, e a gente pensa junto."
{user} perguntou: "{user1}, quem tá seguro(a) demais?"
{user} disse a {user1}: "Me ajuda a desmascarar alguém."
{user} perguntou a {user1}: "Quem te lembra um vilão de novela?"
{user} disse a {user1}: "Me dá sua leitura rápida: quem?"
{user} perguntou: "{user1}, quem você não quer ver vencendo?"
{user} disse a {user1}: "Você tem uma suspeita guardada, eu sei."
{user} perguntou a {user1}: "Quem mudou de amizade de repente?"
{user} disse a {user1}: "Fala quem você acha que é, sem rodeio."
{user} perguntou: "{user1}, quem fica sempre em cima do muro?"
{user} disse a {user1}: "Me fala quem, que eu não espalho."
{user} perguntou a {user1}: "Quem te assusta no silêncio?"
{user} disse a {user1}: "Eu quero ouvir sua lista inteira."
{user} perguntou: "{user1}, quem nunca conta de quem desconfia?"
{user} disse a {user1}: "Me passa o nome antes da mesa."
{user} perguntou a {user1}: "Quem você acha que finge melhor?"
{user} disse a {user1}: "Me ajuda a escolher meu voto."
{user} perguntou: "{user1}, quem te parece Traidor(a) de verdade?"
{user} disse a {user1}: "Me conta. Eu juro que é segredo."
{user} perguntou a {user1}: "Quem tem mais a esconder aqui?"
{user} disse a {user1}: "Quem você acha que tá guiando os votos?"
{user} perguntou: "{user1}, quem você acha que tá acima de suspeita sem motivo?"
{user} disse a {user1}: "Quero sua opinião honesta sobre o castelo."
{user} perguntou a {user1}: "Quem você acha que se deu bem demais?"
{user} disse a {user1}: "Me fala quem, que eu faço o resto."
{user} perguntou: "{user1}, quem você acha que tá mentindo pra você?"
{user} disse a {user1}: "Me conta quem você vigia."
{user} perguntou a {user1}: "Quem nunca se abala?"
{user} disse a {user1}: "Me dá um nome e eu te dou um abraço."
{user} perguntou: "{user1}, quem você acha que está protegido(a) pelos Traidores?"
{user} disse a {user1}: "Me fala quem tá errado nessa história."
{user} perguntou a {user1}: "Quem você não suporta?"
{user} disse a {user1}: "Me fala quem, e a gente derruba juntos."
{user} perguntou: "{user1}, quem você acha que é o próximo alvo?"
{user} disse a {user1}: "Me conta o nome que tá te consumindo."
{user} perguntou a {user1}: "Quem você acha que te usaria de escudo?"
{user} disse a {user1}: "Vamos lá, um nome e eu paro de perguntar."
{user} perguntou: "{user1}, em quem você votou e se arrependeu?"
{user} disse a {user1}: "Me dá sua visão, que a minha tá turva."
{user} perguntou a {user1}: "Quem te enganou até agora?"
{user} disse a {user1}: "Você tem cara de quem sabe de tudo. Me conta."
{user} perguntou: "{user1}, quem aqui tem dois rostos?"
{user} disse a {user1}: "Me fala quem, antes que seja tarde."
{user} perguntou a {user1}: "Quem se aproximou de você com interesse?"
{user} disse a {user1}: "Me conta quem é a sua pulga atrás da orelha."
{user} perguntou: "{user1}, quem você mandaria pra casa hoje?"
{user} disse a {user1}: "Fala baixinho: quem?"
{user} perguntou a {user1}: "Quem você acha que é a mente por trás de tudo?"
{user} disse a {user1}: "Me fala quem te dá frio na barriga."
{user} perguntou: "{user1}, quem você acha que eu devia vigiar?"
{user} disse a {user1}: "Me indica alguém pra eu ficar de olho."
{user} perguntou a {user1}: "Quem tá no seu radar hoje?"
{user} disse a {user1}: "Me conta sua suspeita, que eu te conto a minha."
{user} perguntou: "{user1}, você desconfia de alguém da sua própria aliança?"
{user} disse a {user1}: "Me ajuda a entender quem é quem."
{user} perguntou a {user1}: "Quem você acha que finge amizade?"
{user} disse a {user1}: "Quem você acha que dorme sem culpa?"
{user} perguntou: "{user1}, se tivesse um Traidor na sala agora, quem seria?"
{user} disse a {user1}: "Me fala quem, e confia em mim."
{user} perguntou a {user1}: "Quem é o seu maior mistério aqui?"
{user} disse a {user1}: "Quero saber quem você teme mais."
{user} perguntou: "{user1}, quem te deixa em alerta?"
{user} disse a {user1}: "Me conta quem você acha, sem pressa."
{user} perguntou a {user1}: "Quem você acha que sabe o que aconteceu ontem?"
{user} disse a {user1}: "Você me ajuda a achar os Traidores?"
{user} perguntou: "{user1}, você tem algum nome pra me dar?"
{user} perguntou a {user1}: "Se tivesse que votar agora, seria quem?"
{user} disse a {user1}: "Me confia um nome. Fica entre nós."
{user} perguntou a {user1}: "Quem aqui você não deixaria sozinho(a) com você?"
{user} disse a {user1}: "Me ajuda a pensar: quem tá estranho?"
{user} perguntou a {user1}: "Qual o seu palpite? Sinceramente."
{user} perguntou a {user1}: "Quem você acha que mente melhor aqui?"
{user} disse a {user1}: "Você observa tudo. O que você viu?"
{user} perguntou a {user1}: "Em quem você não confia de jeito nenhum?"
{user} disse a {user1}: "Seu instinto diz o quê?"
`);

export const SAY_ASK_ABOUT = lines(`
{user} perguntou a {user1}, longe dos outros: "O que você acha de {user2}?"
{user} cochichou: "{user1}, qual sua impressão de {user2}?"
{user} perguntou a {user1}: "E {user2}? Confia?"
{user} disse a {user1}: "Me fala de {user2}. Sem filtro."
{user} perguntou: "{user1}, você entende o jogo de {user2}?"
{user} disse a {user1}: "Tô com uma dúvida sobre {user2}. E você?"
{user} perguntou a {user1}: "{user2} é Fiel pra você?"
{user} disse a {user1}: "Você conversa muito com {user2}. Como é?"
{user} perguntou: "{user1}, {user2} te passa confiança?"
{user} disse a {user1}: "Me ajuda a entender {user2}."
{user} perguntou a {user1}: "O que {user2} te falou de mim?"
{user} disse a {user1}: "Você votaria em {user2}?"
{user} perguntou: "{user1}, {user2} é do bem?"
{user} disse a {user1}: "Qual a sua leitura de {user2}?"
{user} perguntou a {user1}: "Você acha que {user2} esconde algo?"
{user} disse a {user1}: "Seja sincero(a): e {user2}?"
{user} perguntou: "{user1}, {user2} é seu(sua) amigo(a) mesmo?"
{user} disse a {user1}: "Me conta o que você sabe de {user2}."
{user} perguntou a {user1}: "{user2} te parece estranho(a)?"
{user} disse a {user1}: "Eu não consigo ler {user2}. Você consegue?"
{user} perguntou: "{user1}, dá pra confiar em {user2}?"
{user} disse a {user1}: "O que você sente perto de {user2}?"
{user} perguntou a {user1}: "Você colocaria a mão no fogo por {user2}?"
{user} disse a {user1}: "E {user2}, hein? Fala aí."
{user} perguntou: "{user1}, {user2} anda diferente?"
{user} disse a {user1}: "Me passa a ficha de {user2}."
{user} perguntou a {user1}: "Você gosta de {user2}?"
{user} disse a {user1}: "Sua opinião sobre {user2} me interessa."
{user} perguntou: "{user1}, {user2} é perigoso(a)?"
{user} disse a {user1}: "{user2} fala muito de você. Sabia?"
{user} perguntou a {user1}: "Você acha {user2} sincero(a)?"
{user} disse a {user1}: "Me diz uma palavra sobre {user2}."
{user} perguntou: "{user1}, {user2} já mentiu pra você?"
{user} disse a {user1}: "Como {user2} te trata quando ninguém tá vendo?"
{user} perguntou a {user1}: "Você deixaria {user2} chegar na final?"
{user} disse a {user1}: "Eu quero saber o que você pensa de {user2}."
{user} perguntou: "{user1}, {user2} tem cara de quê pra você?"
{user} disse a {user1}: "Me conta: {user2} é aliado(a) de quem?"
{user} perguntou a {user1}: "Você viu {user2} ontem à noite?"
{user} disse a {user1}: "{user2} é o tipo de pessoa em quem você confia?"
{user} perguntou: "{user1}, você e {user2} se dão bem?"
{user} disse a {user1}: "Me fala o bom e o ruim de {user2}."
{user} perguntou a {user1}: "{user2} te assusta ou te acalma?"
{user} disse a {user1}: "Você conhece {user2} melhor que eu. E aí?"
{user} perguntou: "{user1}, {user2} tá no seu radar?"
{user} disse a {user1}: "Qual o jogo de {user2}, afinal?"
{user} perguntou a {user1}: "Você acreditou no que {user2} disse ontem?"
{user} disse a {user1}: "Me dá uma nota pra {user2}, de zero a dez."
{user} perguntou: "{user1}, {user2} é sincero(a) com você?"
{user} disse a {user1}: "Tem algo sobre {user2} que eu deveria saber?"
{user} perguntou a {user1}: "Você acha que {user2} gosta de mim?"
{user} disse a {user1}: "Eu fico em dúvida com {user2}. Você não?"
{user} perguntou: "{user1}, o que você achou de {user2} logo de cara?"
{user} disse a {user1}: "Sua primeira impressão de {user2}, qual foi?"
{user} perguntou a {user1}: "{user2} é simpático(a) de verdade?"
{user} disse a {user1}: "Me conta de {user2} sem enfeite."
{user} perguntou: "{user1}, você dividiria quarto com {user2}?"
{user} disse a {user1}: "Como é o papo de {user2}?"
{user} perguntou a {user1}: "{user2} é uma boa pessoa?"
{user} disse a {user1}: "O que você achou do jeito de {user2}?"
{user} perguntou: "{user1}, {user2} passa uma energia boa?"
{user} disse a {user1}: "Me fala se eu posso contar com {user2}."
{user} perguntou a {user1}: "{user2} te contou algum segredo?"
{user} disse a {user1}: "Você e {user2} têm aliança?"
{user} perguntou: "{user1}, você defenderia {user2} na mesa?"
{user} disse a {user1}: "Me ajuda a decidir sobre {user2}."
{user} perguntou a {user1}: "{user2} tem jogo próprio?"
{user} disse a {user1}: "Você acha que {user2} tá protegido(a)?"
{user} perguntou: "{user1}, {user2} já te decepcionou?"
{user} disse a {user1}: "Me fala o que {user2} pensa de verdade."
{user} perguntou a {user1}: "{user2} é leal a quem?"
{user} disse a {user1}: "Você confiaria um segredo a {user2}?"
{user} perguntou: "{user1}, você acha que {user2} manipula?"
{user} disse a {user1}: "Me conta como {user2} reagiu à última notícia."
{user} perguntou a {user1}: "{user2} parece com medo?"
{user} disse a {user1}: "Você tem alguma pista sobre {user2}?"
{user} perguntou: "{user1}, {user2} merece estar aqui?"
{user} disse a {user1}: "Qual o seu palpite sobre {user2}?"
{user} perguntou a {user1}: "Você acha que {user2} vai longe?"
{user} disse a {user1}: "Me explica {user2}, porque eu não entendo."
{user} perguntou: "{user1}, {user2} é engraçado(a) ou falso(a)?"
{user} disse a {user1}: "Me fala de {user2} como se fosse pra sua mãe."
{user} perguntou a {user1}: "{user2} te trata bem?"
{user} disse a {user1}: "Eu queria saber se {user2} é de confiança."
{user} perguntou: "{user1}, você repara em algo estranho em {user2}?"
{user} disse a {user1}: "Me conta o que te incomoda em {user2}."
{user} perguntou a {user1}: "{user2} te lembra alguém lá de fora?"
{user} disse a {user1}: "Você acha que {user2} chora de verdade?"
{user} perguntou: "{user1}, {user2} ri de verdade ou por educação?"
{user} disse a {user1}: "Me passa o que você sabe sobre {user2}."
{user} perguntou a {user1}: "{user2} já votou em você?"
{user} disse a {user1}: "Você acha {user2} esperto(a) demais?"
{user} perguntou: "{user1}, {user2} tá jogando pra ganhar?"
{user} disse a {user1}: "O que {user2} faz quando ninguém tá olhando?"
{user} perguntou a {user1}: "Você acha que {user2} tem aliança secreta?"
{user} disse a {user1}: "Me conta se {user2} é fofoqueiro(a)."
{user} perguntou: "{user1}, você gosta do jeito de {user2}?"
{user} disse a {user1}: "Eu ouvi coisas de {user2}. E você?"
{user} perguntou a {user1}: "{user2} fala mal de alguém?"
{user} disse a {user1}: "Me ajuda: {user2} é Fiel ou é teatro?"
{user} perguntou: "{user1}, {user2} tem estômago pra trair?"
{user} disse a {user1}: "Qual o ponto fraco de {user2}?"
{user} perguntou a {user1}: "Você acha {user2} carente de atenção?"
{user} disse a {user1}: "Me conta o jeito de {user2} numa palavra."
{user} perguntou: "{user1}, {user2} te deixa confortável?"
{user} disse a {user1}: "Você bota fé em {user2}?"
{user} perguntou a {user1}: "{user2} parece se esforçar pra parecer inocente?"
{user} disse a {user1}: "Você acha que {user2} tá mentindo?"
{user} perguntou: "{user1}, {user2} tem medo de quem?"
{user} disse a {user1}: "Me conta o que você viu {user2} fazendo."
{user} perguntou a {user1}: "{user2} é amigo(a) de todo mundo?"
{user} disse a {user1}: "E {user2}, merece um voto de confiança?"
{user} perguntou: "{user1}, você teria {user2} na sua aliança?"
{user} disse a {user1}: "Me diz se {user2} é gente boa mesmo."
{user} perguntou a {user1}: "Você já brigou com {user2}?"
{user} disse a {user1}: "Me fala do humor de {user2}."
{user} perguntou: "{user1}, {user2} é quieto(a) ou calculista?"
{user} disse a {user1}: "O que você faria no meu lugar com {user2}?"
{user} perguntou a {user1}: "{user2} pode ser recrutado(a)?"
{user} disse a {user1}: "Me conta como {user2} vota."
{user} perguntou: "{user1}, você sente sinceridade em {user2}?"
{user} disse a {user1}: "Você acha que {user2} me vê como ameaça?"
{user} perguntou a {user1}: "{user2} tem um lado sombrio?"
{user} disse a {user1}: "Me fala de {user2} com carinho ou sem?"
{user} perguntou: "{user1}, você tem receio de {user2}?"
{user} disse a {user1}: "Me ajuda a decifrar {user2}."
{user} perguntou a {user1}: "Você acha {user2} bom(boa) de jogo?"
{user} disse a {user1}: "{user2} já te pediu pra votar em alguém?"
{user} perguntou: "{user1}, {user2} é influente?"
{user} disse a {user1}: "Me fala se {user2} merece minha confiança."
{user} perguntou a {user1}: "{user2} é igual por dentro e por fora?"
{user} disse a {user1}: "Me dá sua opinião honesta de {user2}."
{user} perguntou: "{user1}, {user2} te lembra um Traidor?"
{user} disse a {user1}: "Me fala o que {user2} tem de diferente."
{user} perguntou a {user1}: "{user2} tá mais pra aliado(a) ou pra ameaça?"
{user} disse a {user1}: "Você acha que {user2} tá sendo usado(a)?"
{user} perguntou: "{user1}, {user2} tem inimigos aqui?"
{user} disse a {user1}: "Me conta quem protege {user2}."
{user} perguntou a {user1}: "Você acha que {user2} chegou com plano?"
{user} disse a {user1}: "Eu queria sua visão sobre {user2}."
{user} perguntou: "{user1}, você acredita nas lágrimas de {user2}?"
{user} disse a {user1}: "Me fala o que {user2} te disse no jardim."
{user} perguntou a {user1}: "{user2} parece cansado(a) ou culpado(a)?"
{user} disse a {user1}: "Você diria que {user2} é leal?"
{user} perguntou: "{user1}, {user2} tá jogando pra alguém?"
{user} disse a {user1}: "Me conta se {user2} tá do nosso lado."
{user} perguntou a {user1}: "{user2} fala de mim pelas costas?"
{user} disse a {user1}: "Você acha que {user2} tem potencial pra vilão(ã)?"
{user} perguntou: "{user1}, você vê {user2} como amigo(a)?"
{user} disse a {user1}: "Me conta a última de {user2}."
{user} perguntou a {user1}: "{user2} é de confiança pra você?"
{user} disse a {user1}: "Me explica por que você gosta de {user2}."
{user} perguntou: "{user1}, por que você não gosta de {user2}?"
{user} disse a {user1}: "O que {user2} te faz sentir?"
{user} perguntou a {user1}: "Você acha {user2} bonito(a) de alma?"
{user} disse a {user1}: "{user2} tá sempre certo(a)? Estranho, né?"
{user} perguntou: "{user1}, {user2} já te protegeu?"
{user} disse a {user1}: "Me conta como {user2} era no primeiro dia."
{user} perguntou a {user1}: "{user2} mudou muito desde a chegada?"
{user} disse a {user1}: "Você acha que {user2} gosta de verdade de alguém aqui?"
{user} perguntou: "{user1}, {user2} tem alguma mania suspeita?"
{user} disse a {user1}: "Me fala de {user2} antes que eu decida."
{user} perguntou a {user1}: "Você e {user2} conversam sobre o jogo?"
{user} disse a {user1}: "Você acha que {user2} merece ganhar?"
{user} perguntou: "{user1}, {user2} tem coração mole?"
{user} disse a {user1}: "Me conta se {user2} já deu uma escorregada."
{user} perguntou a {user1}: "{user2} tem ciúme de alguém?"
{user} disse a {user1}: "Me ajuda a saber se {user2} é ameaça."
{user} perguntou: "{user1}, você gosta do jogo de {user2}?"
{user} disse a {user1}: "O que você diria de {user2} na mesa?"
{user} perguntou a {user1}: "{user2} tem cara de quem trai?"
{user} disse a {user1}: "Me passa sua sensação sobre {user2}."
{user} perguntou: "{user1}, você sente que {user2} é verdadeiro(a)?"
{user} disse a {user1}: "Me fala se {user2} anda com quem não devia."
{user} perguntou a {user1}: "{user2} é bom(boa) em esconder coisas?"
{user} disse a {user1}: "Você vê maldade em {user2}?"
{user} perguntou: "{user1}, {user2} te convence?"
{user} disse a {user1}: "Me conta quem {user2} odeia."
{user} perguntou a {user1}: "Você acha que {user2} está desesperado(a)?"
{user} disse a {user1}: "Me fala de {user2} em segredo."
{user} perguntou: "{user1}, {user2} merece o benefício da dúvida?"
{user} disse a {user1}: "Me diz se eu tô sendo injusto(a) com {user2}."
{user} perguntou a {user1}: "Você confiaria em {user2} numa missão?"
{user} disse a {user1}: "Me conta se {user2} já te ajudou."
{user} perguntou: "{user1}, {user2} é paciente ou explosivo(a)?"
{user} disse a {user1}: "Você acha que {user2} tem medo de ser banido(a)?"
{user} perguntou a {user1}: "{user2} é bom(boa) ouvinte?"
{user} disse a {user1}: "Me fala a verdade sobre {user2}."
{user} perguntou: "{user1}, quem é {user2} de verdade?"
{user} disse a {user1}: "Me conta se {user2} te deixa desconfiado(a)."
{user} perguntou a {user1}: "Você acha {user2} uma boa companhia?"
{user} disse a {user1}: "Me fala o que você não diria de {user2} em público."
{user} perguntou: "{user1}, {user2} é alguém que você admira?"
{user} disse a {user1}: "Me passa sua intuição sobre {user2}."
{user} perguntou a {user1}: "Você já conversou a sós com {user2}?"
{user} disse a {user1}: "Me ajuda: {user2} é confiável?"
{user} perguntou a {user1}: "{user2} te passa segurança?"
{user} disse a {user1}: "O que você sente quando {user2} fala?"
{user} perguntou a {user1}: "Você votaria em {user2}?"
{user} disse a {user1}: "Sinceramente, {user2}: sim ou não?"
{user} perguntou a {user1}: "{user2} já mentiu pra você?"
{user} disse a {user1}: "Qual o seu feeling sobre {user2}?"
{user} perguntou a {user1}: "Você colocaria {user2} na sua aliança?"
{user} disse a {user1}: "Tô confuso(a) sobre {user2}. E você?"
`);

export const SAY_PERSUADE_GUILTY = lines(`
{user} chamou {user1} a sós: "Presta atenção em {user2}. É Traidor(a)."
{user} contou a {user1} tudo o que viu {user2} fazer de estranho.
{user} disse a {user1}: "Eu tenho certeza sobre {user2}. Vota comigo."
{user} cochichou: "{user1}, {user2} tá enganando todo mundo."
{user} disse a {user1}: "Abre o olho com {user2}."
{user} disse a {user1}: "{user2} é o(a) Traidor(a) que a gente procura."
{user} disse a {user1}: "Juntos a gente tira {user2} hoje."
{user} disse a {user1}: "Olha como {user2} reage quando falam de morte."
{user} disse a {user1}: "{user2} tá manipulando a gente, acredita em mim."
{user} disse a {user1}: "Toda morte tem a digital de {user2}."
{user} disse a {user1}: "Eu vi {user2} saindo do quarto de madrugada."
{user} disse a {user1}: "{user2} nunca vota em quem sai Traidor. Repara."
{user} disse a {user1}: "Confia em mim: {user2} não é quem parece."
{user} disse a {user1}: "{user2} fala uma coisa pra você e outra pra mim."
{user} disse a {user1}: "A calma de {user2} não é normal."
{user} disse a {user1}: "Se a gente não tirar {user2}, a gente perde."
{user} disse a {user1}: "Você não acha estranho {user2} nunca ser alvo?"
{user} disse a {user1}: "{user2} escolheu as vítimas. Eu sinto."
{user} disse a {user1}: "Vamos votar juntos em {user2}?"
{user} disse a {user1}: "Eu juntei as peças: é {user2}."
{user} disse a {user1}: "{user2} tá rindo da nossa cara."
{user} disse a {user1}: "{user2} cochicha com quem não devia."
{user} disse a {user1}: "{user2} mentiu pra mim ontem. Descaradamente."
{user} disse a {user1}: "Ninguém desconfia de {user2}. Por isso é perfeito(a) pra torre."
{user} disse a {user1}: "Pensa nas mortes: todas ajudaram {user2}."
{user} disse a {user1}: "{user2} é bom(boa) demais em parecer inocente."
{user} disse a {user1}: "{user2} defendeu quem saiu Traidor. Lembra?"
{user} disse a {user1}: "O voto de {user2} ontem entregou tudo."
{user} disse a {user1}: "Não se deixa levar pelo charme de {user2}."
{user} disse a {user1}: "{user2} tem sempre uma resposta pronta. Ensaiada."
{user} disse a {user1}: "Eu te peço: fica de olho em {user2}."
{user} disse a {user1}: "{user2} olhou pra torre ontem à noite."
{user} disse a {user1}: "Se eu estiver errado(a) sobre {user2}, pode me cobrar."
{user} disse a {user1}: "{user2} tá se escondendo atrás de você."
{user} disse a {user1}: "{user2} é frio(a) demais pra ser Fiel."
{user} disse a {user1}: "Anota o que eu tô dizendo: {user2}."
{user} disse a {user1}: "{user2} sabia da morte antes da porta abrir."
{user} disse a {user1}: "Você viu a cara de {user2} no café? Nada de susto."
{user} disse a {user1}: "{user2} sempre muda o voto na última hora."
{user} disse a {user1}: "{user2} tá usando você de escudo, abre o olho."
{user} disse a {user1}: "O jeito de {user2} olhar pras pessoas me dá medo."
{user} disse a {user1}: "{user2} não chorou por ninguém até agora."
{user} disse a {user1}: "Eu não durmo tranquilo(a) com {user2} aqui."
{user} disse a {user1}: "{user2} faz perguntas demais sobre quem desconfia de quem."
{user} disse a {user1}: "{user2} evita falar das mortes."
{user} disse a {user1}: "{user2} tem um plano, e não é de Fiel."
{user} disse a {user1}: "Me ajuda a mostrar pra mesa quem é {user2}."
{user} disse a {user1}: "{user2} ri quando ninguém mais ri."
{user} disse a {user1}: "Todo mundo próximo de {user2} acaba morto."
{user} disse a {user1}: "{user2} mudou depois da primeira noite."
{user} disse a {user1}: "{user2} tem a paciência de quem sabe o final."
{user} disse a {user1}: "Eu apostaria meu prêmio em {user2}."
{user} disse a {user1}: "{user2} tá sempre perto de quem vai ser alvo."
{user} disse a {user1}: "Você confia em {user2}? Não devia."
{user} disse a {user1}: "{user2} fala em lealdade demais. Desconfia."
{user} disse a {user1}: "{user2} some na hora das conversas difíceis."
{user} disse a {user1}: "{user2} jogou alguém embaixo do ônibus. Eu vi."
{user} disse a {user1}: "Olha o histórico de votos de {user2}. Só Fiéis."
{user} disse a {user1}: "{user2} é o cérebro da torre, tenho certeza."
{user} disse a {user1}: "Você viu como {user2} desviou o assunto?"
{user} disse a {user1}: "{user2} tem resposta pra tudo, menos pra verdade."
{user} disse a {user1}: "Não vota em outra pessoa hoje. É {user2}."
{user} disse a {user1}: "{user2} tá sorrindo demais pra quem tá em perigo."
{user} disse a {user1}: "Eu sinto a traição em {user2}."
{user} disse a {user1}: "{user2} age como quem tem proteção."
{user} disse a {user1}: "{user2} nunca desconfia dos Traidores certos."
{user} disse a {user1}: "Pode perguntar pra {user2} onde tava. Não vai saber."
{user} disse a {user1}: "{user2} só fala comigo quando quer algo."
{user} disse a {user1}: "Vamos juntar votos contra {user2}?"
{user} disse a {user1}: "{user2} tentou me convencer de votar num Fiel."
{user} disse a {user1}: "Me escuta: {user2} é perigo."
{user} disse a {user1}: "{user2} tá ganhando tempo."
{user} disse a {user1}: "{user2} é leal a alguém que não é a gente."
{user} disse a {user1}: "{user2} tem o sono tranquilo de quem mata."
{user} disse a {user1}: "Se {user2} ficar, a gente cai um por um."
{user} disse a {user1}: "{user2} chora na hora certa demais."
{user} disse a {user1}: "Não é birra minha. É {user2} mesmo."
{user} disse a {user1}: "{user2} escolhe muito bem as palavras. Bem demais."
{user} disse a {user1}: "Eu tenho um pressentimento forte com {user2}."
{user} disse a {user1}: "{user2} sabe quem vai morrer. Olha como age."
{user} disse a {user1}: "{user2} me olhou como quem já decidiu minha morte."
{user} disse a {user1}: "Vota comigo em {user2} e a gente acerta."
{user} disse a {user1}: "{user2} tem uma aliança secreta. Aposto."
{user} disse a {user1}: "{user2} tá brincando com a gente."
{user} disse a {user1}: "Olha o tanto que {user2} protege quem não devia."
{user} disse a {user1}: "{user2} tá sempre um passo à frente. Por quê?"
{user} disse a {user1}: "Você vai se arrepender se não votar em {user2}."
{user} disse a {user1}: "{user2} fingiu surpresa, e fingiu mal."
{user} disse a {user1}: "{user2} tem cara de santo(a) e alma de torre."
{user} disse a {user1}: "Eu confio em você. Por isso te conto de {user2}."
{user} disse a {user1}: "Me ouve só um minuto sobre {user2}."
{user} disse a {user1}: "{user2} é a peça que falta no quebra-cabeça."
{user} disse a {user1}: "Não deixa {user2} te enganar como me enganou."
{user} disse a {user1}: "{user2} sempre sabe demais."
{user} disse a {user1}: "Tá tudo na cara, é {user2}."
{user} disse a {user1}: "{user2} é a pessoa que nunca é suspeita. Pensa nisso."
{user} disse a {user1}: "{user2} evita olhar nos olhos quando fala de voto."
{user} disse a {user1}: "Você viu {user2} no corredor? Eu vi."
{user} disse a {user1}: "{user2} tentou virar a mesa contra mim."
{user} disse a {user1}: "{user2} tá seguro(a) demais. Só quem é da torre fica assim."
{user} disse a {user1}: "{user2} tem sangue frio. Frio demais."
{user} disse a {user1}: "Pensa: quem ganha com cada morte? {user2}."
{user} disse a {user1}: "{user2} é o(a) Traidor(a) mais bem disfarçado(a)."
{user} disse a {user1}: "{user2} tá manipulando os votos há dias."
{user} disse a {user1}: "Eu confio no seu olhar. Olha pra {user2}."
{user} disse a {user1}: "Você não quer que {user2} chegue na final, quer?"
{user} disse a {user1}: "{user2} vai te trair na primeira chance."
{user} disse a {user1}: "Juntos, a gente derruba {user2}."
{user} disse a {user1}: "{user2} tem mais segredo que o castelo."
{user} disse a {user1}: "{user2} mentiu sobre onde dormiu."
{user} disse a {user1}: "Eu sinto o cheiro de traição quando {user2} passa."
{user} disse a {user1}: "Olha os olhos de {user2} na próxima mesa."
{user} disse a {user1}: "Não é suposição. É {user2}."
{user} disse a {user1}: "{user2} não liga pra quem morre."
{user} disse a {user1}: "{user2} foi recrutado(a). Tenho quase certeza."
{user} disse a {user1}: "{user2} é o tipo que abraça e apunhala."
{user} disse a {user1}: "Vamos provar juntos que é {user2}?"
{user} disse a {user1}: "{user2} tá brincando de Fiel."
{user} disse a {user1}: "Eu reparei: {user2} evita a escada de dia."
{user} disse a {user1}: "{user2} não tem nenhuma atitude de Fiel."
{user} disse a {user1}: "Você viu {user2} empurrar a culpa pra outro?"
{user} disse a {user1}: "Tira {user2} da sua lista de amigos."
{user} disse a {user1}: "{user2} tá ganhando a sua confiança pra te usar."
{user} disse a {user1}: "Me escuta, é sério: {user2}."
{user} disse a {user1}: "{user2} é perigoso(a) pra nós dois."
{user} disse a {user1}: "Seu voto em {user2} pode salvar a gente."
{user} disse a {user1}: "{user2} já começou a te isolar. Percebe?"
{user} disse a {user1}: "Eu vi {user2} rindo depois da última morte."
{user} disse a {user1}: "{user2} tem ligação com cada Traidor que caiu."
{user} disse a {user1}: "{user2} é a raposa no galinheiro."
{user} disse a {user1}: "Quem mais você acha que seria? É {user2}."
{user} disse a {user1}: "{user2} faz de tudo pra parecer útil."
{user} disse a {user1}: "Não protege {user2}, ele(a) não te protege."
{user} disse a {user1}: "{user2} tá contando os dias pra te tirar."
{user} disse a {user1}: "{user2} tem um olhar calculista."
{user} disse a {user1}: "Me dá esse voto: {user2}."
{user} disse a {user1}: "{user2} tá blefando o tempo todo."
{user} disse a {user1}: "Olha como {user2} fala de quem morreu. Sem dor."
{user} disse a {user1}: "{user2} evita ficar sozinho(a) com qualquer Fiel."
{user} disse a {user1}: "{user2} tentou saber em quem eu ia votar."
{user} disse a {user1}: "{user2} é a pedra no nosso caminho."
{user} disse a {user1}: "Não deixa {user2} escapar mais uma mesa."
{user} disse a {user1}: "Eu tenho quase prova sobre {user2}."
{user} disse a {user1}: "{user2} vai te agradecer por não votar nele(a). Com uma adaga."
{user} disse a {user1}: "{user2} não merece sua confiança."
{user} disse a {user1}: "Te juro, {user2} é da torre."
{user} disse a {user1}: "{user2} sempre sabe de quem desconfiar primeiro."
{user} disse a {user1}: "{user2} planta dúvidas nos outros. Clássico de Traidor."
{user} disse a {user1}: "{user2} tem uma calma assustadora."
{user} disse a {user1}: "Vamos virar a mesa contra {user2}."
{user} disse a {user1}: "{user2} tá rindo por dentro, eu sinto."
{user} disse a {user1}: "{user2} tentou me recrutar pra uma aliança estranha."
{user} disse a {user1}: "Se não for {user2}, eu não entendo mais nada."
{user} disse a {user1}: "{user2} tem pose de quem já ganhou."
{user} disse a {user1}: "{user2} pergunta de mais e responde de menos."
{user} disse a {user1}: "{user2} tá sempre no lugar certo na hora certa."
{user} disse a {user1}: "Olha pra {user2} com os meus olhos."
{user} disse a {user1}: "{user2} tem ligação com a morte de ontem."
{user} disse a {user1}: "{user2} manipula até o jeito de sentar à mesa."
{user} disse a {user1}: "Você é esperto(a). Sabe que é {user2}."
{user} disse a {user1}: "{user2} tá te enrolando, eu vejo."
{user} disse a {user1}: "{user2} nunca defende quem morre."
{user} disse a {user1}: "Eu quero seu voto em {user2}. Confia."
{user} disse a {user1}: "{user2} é muito bom(boa) em se fazer de vítima."
{user} disse a {user1}: "{user2} esconde a capa no fundo da mala."
{user} disse a {user1}: "Essa amizade de {user2} com todo mundo é fachada."
{user} disse a {user1}: "{user2} jogou alguém aos leões pra se salvar."
{user} disse a {user1}: "{user2} sabia onde a vítima dormia."
{user} disse a {user1}: "Não tem outro nome: {user2}."
{user} disse a {user1}: "{user2} tá guiando a mesa pro abismo."
{user} disse a {user1}: "{user2} é traição com cara de amizade."
{user} disse a {user1}: "Vota em {user2} e me agradece depois."
{user} disse a {user1}: "{user2} fez cara de alívio na hora errada."
{user} disse a {user1}: "Eu conheço o tipo de {user2}. É Traidor(a)."
{user} disse a {user1}: "{user2} é o lobo vestido de ovelha."
{user} disse a {user1}: "{user2} só confia em quem tá seguro(a). Estranho, não?"
{user} disse a {user1}: "Me dá sua palavra que você vai pensar em {user2}."
{user} disse a {user1}: "Todo caminho leva a {user2}."
{user} disse a {user1}: "{user2} tem um segredo pesado. Eu sinto."
{user} disse a {user1}: "Deixa eu te mostrar os furos de {user2}."
{user} disse a {user1}: "{user2} age igual Traidor(a) de temporada passada."
{user} disse a {user1}: "Eu tenho medo de {user2}. Você não devia ter?"
{user} disse a {user1}: "{user2} tá afiando a adaga pra você."
{user} disse a {user1}: "Quem acusou {user2} antes morreu. Por que será?"
{user} disse a {user1}: "Vamos juntos acabar com o jogo de {user2}."
{user} disse a {user1}: "{user2} vai sair, e você vai ver que eu tinha razão."
{user} disse a {user1}: "Não se apega a {user2}. Vai doer."
{user} disse a {user1}: "{user2} tá jogando com a nossa vida."
{user} disse a {user1}: "Repara como {user2} muda de voto no último segundo."
{user} disse a {user1}: "{user2} sempre sabe demais. Pensa nisso."
{user} disse a {user1}: "Se {user2} for Fiel, eu saio daqui de mãos dadas com o(a) Traidor(a)."
{user} disse a {user1}: "{user2} tava perto de todas as vítimas."
{user} disse a {user1}: "Vai por mim: {user2}. Não tem erro."
{user} disse a {user1}: "Você já viu {user2} acusar alguém de verdade? Nunca."
{user} disse a {user1}: "{user2} se esconde atrás do sorriso."
{user} disse a {user1}: "Escuta: {user2} mentiu pra mim ontem."
{user} disse a {user1}: "O jeito que {user2} reagiu à eliminação... estranho."
{user} disse a {user1}: "Me ajuda a tirar {user2}. É agora ou nunca."
{user} disse a {user1}: "{user2} vota sempre depois de todo mundo. Calculista."
{user} disse a {user1}: "Olha as alianças de {user2}. Ninguém dali morre."
{user} disse a {user1}: "Tô te pedindo: {user2}. Confia em mim."
{user} disse a {user1}: "Quem mais ganha com as mortes? {user2}."
{user} disse a {user1}: "{user2} tá sempre calmo(a). Calmo(a) demais."
`);

export const SAY_PERSUADE_INNOCENT = lines(`
{user} tentou convencer {user1}: "{user2} é Fiel. Eu tenho certeza."
{user} pediu a {user1}: "Tira {user2} da sua lista de suspeitos."
{user} disse a {user1}: "{user2} não é Traidor(a). Confia em mim."
{user} disse a {user1}: "Deixa {user2} em paz. É dos nossos."
{user} disse a {user1}: "Eu conheço {user2}. Não é da torre."
{user} disse a {user1}: "Votar em {user2} é jogar voto fora."
{user} disse a {user1}: "{user2} tá sendo usado(a) de bode expiatório."
{user} disse a {user1}: "Olha bem: {user2} não tem perfil de Traidor(a)."
{user} disse a {user1}: "{user2} chora de verdade. Eu vi."
{user} disse a {user1}: "{user2} é a pessoa mais honesta que conheci aqui."
{user} disse a {user1}: "Se {user2} for Traidor(a), eu desisto de jogar."
{user} disse a {user1}: "{user2} me ajudou quando ninguém ajudou."
{user} disse a {user1}: "{user2} é só nervoso(a). Não é culpa."
{user} disse a {user1}: "Não cai na conversa de quem acusa {user2}."
{user} disse a {user1}: "{user2} é leal até demais."
{user} disse a {user1}: "Tirar {user2} é fazer o trabalho da torre."
{user} disse a {user1}: "{user2} já provou ser Fiel pra mim."
{user} disse a {user1}: "{user2} não tem malícia nenhuma."
{user} disse a {user1}: "Pensa comigo: {user2} teria morrido se fosse da torre? Não."
{user} disse a {user1}: "{user2} é inocente, e o tempo vai mostrar."
{user} disse a {user1}: "Se você votar em {user2}, os Traidores comemoram."
{user} disse a {user1}: "Eu garanto {user2} com meu nome."
{user} disse a {user1}: "{user2} tá com medo, e medo não é culpa."
{user} disse a {user1}: "{user2} não sabe nem mentir sobre a sobremesa."
{user} disse a {user1}: "{user2} é transparente como água."
{user} disse a {user1}: "Me dá um voto de confiança por {user2}."
{user} disse a {user1}: "{user2} merece estar aqui até o fim."
{user} disse a {user1}: "A calma de {user2} é de quem não deve nada."
{user} disse a {user1}: "{user2} é o tipo de gente que os Traidores querem que a gente tire."
{user} disse a {user1}: "Eu confio mais em {user2} do que em mim."
{user} disse a {user1}: "{user2} não tem estômago pra matar ninguém."
{user} disse a {user1}: "{user2} tá sendo perseguido(a) à toa."
{user} disse a {user1}: "Olha o jogo limpo de {user2}."
{user} disse a {user1}: "{user2} ajudou todo mundo na missão."
{user} disse a {user1}: "Não troca um Fiel por uma suspeita vazia."
{user} disse a {user1}: "{user2} vota com o coração. Traidor vota com a cabeça."
{user} disse a {user1}: "{user2} seria o(a) pior Traidor(a) da história."
{user} disse a {user1}: "{user2} não esconde nada, eu garanto."
{user} disse a {user1}: "{user2} é inocente como criança."
{user} disse a {user1}: "Me escuta: não é {user2}."
{user} disse a {user1}: "{user2} tem a consciência limpa. Dá pra ver."
{user} disse a {user1}: "Protege {user2} comigo na mesa?"
{user} disse a {user1}: "{user2} é o coração desse grupo."
{user} disse a {user1}: "{user2} tá no alvo porque incomoda os Traidores."
{user} disse a {user1}: "Quem acusa {user2} tá desviando atenção."
{user} disse a {user1}: "{user2} passa a noite chorando de saudade de casa. Traidor não faz isso."
{user} disse a {user1}: "{user2} já foi atacado(a) demais."
{user} disse a {user1}: "{user2} é de confiança. Pode apostar."
{user} disse a {user1}: "Você vai se arrepender se votar em {user2}."
{user} disse a {user1}: "{user2} é a última pessoa que eu tiraria."
{user} disse a {user1}: "Não deixa o medo decidir sobre {user2}."
{user} disse a {user1}: "{user2} tem o olhar mais sincero daqui."
{user} disse a {user1}: "Eu vi {user2} defender um Fiel quando ninguém defendia."
{user} disse a {user1}: "{user2} não tem jogo sujo."
{user} disse a {user1}: "{user2} é leal ao grupo desde o primeiro dia."
{user} disse a {user1}: "Olha como {user2} sofre com cada morte."
{user} disse a {user1}: "{user2} é tímido(a), não traidor(a)."
{user} disse a {user1}: "Me ajuda a salvar {user2}."
{user} disse a {user1}: "Seu voto em {user2} seria um erro enorme."
{user} disse a {user1}: "{user2} é das nossas. Não duvida disso."
{user} disse a {user1}: "{user2} merece o benefício da dúvida."
{user} disse a {user1}: "Não tem um fato contra {user2}. Só boato."
{user} disse a {user1}: "{user2} é a prova de que tem gente boa aqui."
{user} disse a {user1}: "Eu dou minha palavra por {user2}."
{user} disse a {user1}: "{user2} tem muito medo pra ser da torre."
{user} disse a {user1}: "{user2} não tem cara de traição, tem cara de cansaço."
{user} disse a {user1}: "{user2} sempre falou a verdade comigo."
{user} disse a {user1}: "Estão armando contra {user2}. Não cai."
{user} disse a {user1}: "{user2} é fiel até no jeito de rir."
{user} disse a {user1}: "{user2} merece justiça, não suspeita."
{user} disse a {user1}: "Olha quem acusa {user2}. Olha direito."
{user} disse a {user1}: "{user2} é o alvo errado."
{user} disse a {user1}: "Se tirarem {user2}, a gente perde um Fiel."
{user} disse a {user1}: "{user2} tá do nosso lado, eu juro."
{user} disse a {user1}: "Por favor, não vota em {user2}."
{user} disse a {user1}: "{user2} não merece o nome no quadro."
{user} disse a {user1}: "{user2} é firme e honesto(a)."
{user} disse a {user1}: "Eu sinto verdade em {user2}."
{user} disse a {user1}: "{user2} tem um coração enorme."
{user} disse a {user1}: "Você conhece {user2}. Sabe que não é."
{user} disse a {user1}: "{user2} está sendo injustiçado(a)."
{user} disse a {user1}: "{user2} não teria coragem de trair ninguém."
{user} disse a {user1}: "{user2} chorou pela vítima de verdade."
{user} disse a {user1}: "{user2} só fala demais. Não é crime."
{user} disse a {user1}: "Guarda seu voto pra quem merece. Não é {user2}."
{user} disse a {user1}: "{user2} é alguém que a gente precisa na final."
{user} disse a {user1}: "{user2} é verdadeiro(a) num castelo de mentira."
{user} disse a {user1}: "Não repete o erro da última mesa com {user2}."
{user} disse a {user1}: "{user2} é inocente até que provem o contrário."
{user} disse a {user1}: "{user2} tem mais medo que todo mundo."
{user} disse a {user1}: "Eu seguro a barra de {user2}. Segura comigo?"
{user} disse a {user1}: "{user2} é leal a nós. Eu sei."
{user} disse a {user1}: "{user2} é bondade pura."
{user} disse a {user1}: "Traidor não se arrisca como {user2} se arrisca."
{user} disse a {user1}: "{user2} é inofensivo(a), confia."
{user} disse a {user1}: "{user2} merece paz."
{user} disse a {user1}: "Os Traidores escolheram {user2} pra gente acusar."
{user} disse a {user1}: "{user2} nunca me deu motivo pra desconfiar."
{user} disse a {user1}: "{user2} é o(a) mais transparente daqui."
{user} disse a {user1}: "Não deixa ninguém te convencer contra {user2}."
{user} disse a {user1}: "{user2} tem o coração no lugar certo."
{user} disse a {user1}: "{user2} tá ajudando a gente, não atrapalhando."
{user} disse a {user1}: "{user2} tem a alma leve. Não é Traidor(a)."
{user} disse a {user1}: "Me faz esse favor: confia em {user2}."
{user} disse a {user1}: "{user2} é um(a) Fiel de verdade."
{user} disse a {user1}: "{user2} não sabe nem guardar segredo. Imagina ser Traidor(a)."
{user} disse a {user1}: "{user2} tá do lado certo dessa história."
{user} disse a {user1}: "Eu vi {user2} sofrendo sozinho(a). É Fiel."
{user} disse a {user1}: "{user2} é o tipo de Fiel que os Traidores temem."
{user} disse a {user1}: "{user2} sempre se esforça pelo grupo."
{user} disse a {user1}: "Eu apostaria tudo na inocência de {user2}."
{user} disse a {user1}: "{user2} é o nosso escudo, não nossa ameaça."
{user} disse a {user1}: "Me escuta: {user2} é Fiel e tá assustado(a)."
{user} disse a {user1}: "{user2} tem o jogo mais limpo daqui."
{user} disse a {user1}: "{user2} é incapaz de fazer mal a alguém."
{user} disse a {user1}: "{user2} é leal até com quem não merece."
{user} disse a {user1}: "Não vota em {user2}. Por mim."
{user} disse a {user1}: "{user2} é a nossa melhor aliada(o)."
{user} disse a {user1}: "{user2} não merece ir embora assim."
{user} disse a {user1}: "{user2} tá sendo julgado(a) pela aparência."
{user} disse a {user1}: "Pensa nas atitudes de {user2}. Todas de Fiel."
{user} disse a {user1}: "{user2} tem um jeito atrapalhado, não traiçoeiro."
{user} disse a {user1}: "{user2} tem minha confiança total."
{user} disse a {user1}: "{user2} é sincero(a) até quando não devia."
{user} disse a {user1}: "Ajuda a salvar {user2} da mesa hoje."
{user} disse a {user1}: "Não é {user2}. Eu sei quem é, e não é."
{user} disse a {user1}: "{user2} não tem sangue frio pra ser da torre."
{user} disse a {user1}: "{user2} é inocente, e eu vou provar."
{user} disse a {user1}: "Me dá esse voto de confiança por {user2}."
{user} disse a {user1}: "{user2} tá no lugar errado, na hora errada."
{user} disse a {user1}: "{user2} merece mais uma chance."
{user} disse a {user1}: "Quem conhece {user2} sabe que é Fiel."
{user} disse a {user1}: "{user2} é leal, dá pra ver nos olhos."
{user} disse a {user1}: "{user2} é o(a) mais puro(a) desse castelo."
{user} disse a {user1}: "Olha, {user2} me contou coisas que um Traidor não contaria."
{user} disse a {user1}: "{user2} não protege ninguém suspeito. É Fiel."
{user} disse a {user1}: "Vamos proteger {user2} juntos?"
{user} disse a {user1}: "{user2} é um alvo fácil, e os Traidores sabem."
{user} disse a {user1}: "{user2} tem medo de escuro. Imagina subir na torre."
{user} disse a {user1}: "Tira o nome de {user2} da cabeça."
{user} disse a {user1}: "{user2} é bom(boa) demais pra ser Traidor(a)."
{user} disse a {user1}: "{user2} jamais trairia a gente."
{user} disse a {user1}: "{user2} é o tipo de pessoa que eu levaria pra vida."
{user} disse a {user1}: "Eu sei que {user2} parece estranho(a), mas é Fiel."
{user} disse a {user1}: "{user2} é nervoso(a), não culpado(a)."
{user} disse a {user1}: "Dá uma chance a {user2}. Eu dei, e valeu."
{user} disse a {user1}: "{user2} tá sozinho(a) nessa. Vamos ajudar."
{user} disse a {user1}: "{user2} é inocente e eu não abro mão."
{user} disse a {user1}: "{user2} só é diferente. Não é culpado(a)."
{user} disse a {user1}: "{user2} tem uma bondade que não se finge."
{user} disse a {user1}: "Se você confia em mim, confia em {user2}."
{user} disse a {user1}: "{user2} tá sendo usado(a) pelos Traidores de alvo."
{user} disse a {user1}: "{user2} merece estar na final com a gente."
{user} disse a {user1}: "{user2} ajudou até quem votou nele(a)."
{user} disse a {user1}: "{user2} não tem uma gota de maldade."
{user} disse a {user1}: "Me ouve: {user2} é Fiel, e a gente precisa dele(a)."
{user} disse a {user1}: "{user2} é o(a) mais leal da minha aliança."
{user} disse a {user1}: "Se você votar em {user2}, eu vou ficar triste."
{user} disse a {user1}: "{user2} é inocente, não deixa ninguém te enganar."
{user} disse a {user1}: "{user2} tem o jeito mais Fiel que eu já vi."
{user} disse a {user1}: "Pensa bem antes de apontar pra {user2}."
{user} disse a {user1}: "{user2} tá do nosso lado desde o começo."
{user} disse a {user1}: "Olha a dedicação de {user2} nas missões."
{user} disse a {user1}: "{user2} é o(a) Fiel mais injustiçado(a) do castelo."
{user} disse a {user1}: "{user2} fala o que pensa. Traidor não faz isso."
{user} disse a {user1}: "Eu confio em {user2} e queria que você confiasse."
{user} disse a {user1}: "Não tira {user2}. A gente precisa dele(a)."
{user} disse a {user1}: "{user2} tem a coragem que falta pra muitos."
{user} disse a {user1}: "{user2} vai ser o(a) próximo(a) a morrer, não a trair."
{user} disse a {user1}: "{user2} é sensível demais pra esse jogo sujo."
{user} disse a {user1}: "{user2} não é ameaça, é aliado(a)."
{user} disse a {user1}: "Me promete que não vai votar em {user2} hoje."
{user} disse a {user1}: "{user2} é leal e vai provar."
{user} disse a {user1}: "{user2} é a pessoa mais doce daqui."
{user} disse a {user1}: "Olha, eu vi {user2} rezando pelos mortos."
{user} disse a {user1}: "{user2} só tá cansado(a), não culpado(a)."
{user} disse a {user1}: "Não se deixa levar pelo coro contra {user2}."
{user} disse a {user1}: "{user2} tá do nosso lado, confia."
{user} disse a {user1}: "{user2} é leal, e eu sou testemunha."
{user} disse a {user1}: "Salva {user2} comigo hoje."
{user} disse a {user1}: "{user2} não tem nada a ver com as mortes."
{user} disse a {user1}: "{user2} é Fiel. Anota."
{user} disse a {user1}: "Eu confio em {user2}. Confia comigo."
{user} disse a {user1}: "{user2} é o(a) Fiel mais Fiel que conheço."
{user} disse a {user1}: "Não deixa {user2} ser a próxima injustiça."
{user} disse a {user1}: "{user2} é incapaz de mentir por muito tempo."
{user} disse a {user1}: "{user2} merece sua confiança, eu juro."
{user} disse a {user1}: "Se tirarem {user2}, os Traidores comemoram."
{user} disse a {user1}: "Eu conheço {user2}. É Fiel até o osso."
{user} disse a {user1}: "Olha os votos de {user2}. Sempre certos."
{user} disse a {user1}: "{user2} só é esquisito(a). Não é Traidor(a)."
{user} disse a {user1}: "Não cai nessa de {user2}. É armação."
{user} disse a {user1}: "Poupa {user2} hoje. Você vai me agradecer."
{user} disse a {user1}: "{user2} chorou de verdade pela vítima. Eu vi."
{user} disse a {user1}: "Quem aponta {user2} quer desviar o foco."
{user} disse a {user1}: "Me escuta: {user2} tá do nosso lado."
{user} disse a {user1}: "Eu confio em {user2}. Confia também."
{user} disse a {user1}: "Tira {user2} da mira. Tem gente pior."
{user} disse a {user1}: "Se errarmos com {user2}, a culpa é nossa."
{user} disse a {user1}: "{user2} não tem malícia pra ser Traidor(a)."
`);
