import { lines } from './lines';

/** Falas do jogador: {user} = jogador, {user1} = com quem fala. */

export const SAY_ACCUSE = lines(`
{user} apontou para {user1}: "É você. Eu sei que é você."
{user} não piscou: "{user1}, você é Traidor(a)."
{user} disse, alto e claro: "Meu voto é {user1}."
{user} encarou {user1}: "Pode parar de fingir."
{user} bateu na mesa: "{user1} tá mentindo pra todo mundo!"
{user} cruzou os braços: "{user1}, cadê a sua capa preta?"
{user} disse a {user1}: "Você joga bonito demais pra ser Fiel."
{user} riu sem graça: "{user1}, nem você acredita em você."
{user} levantou: "Eu aposto meu prêmio que {user1} é Traidor(a)."
{user} olhou nos olhos de {user1}: "Eu vejo a torre no seu olhar."
{user} soltou: "{user1} tem cheiro de traição."
{user} disse a {user1}: "Seu teatro acabou, querido(a)."
{user} acusou {user1} sem medo: "Você é a cobra do castelo."
{user} apontou o dedo: "{user1}, você sabe o que fez."
{user} falou firme: "Tem Traidor nessa sala, e é {user1}."
{user} disse a {user1}: "Você mudou de lado rápido demais."
{user} jogou a real: "{user1}, você nunca desconfia de ninguém. Por quê?"
{user} disse: "Toda vez que alguém morre, {user1} tá tranquilo(a)."
{user} provocou: "{user1}, dormiu bem depois da reunião na torre?"
{user} disse a {user1}: "Você protege demais quem não devia."
{user} gritou: "Acorda, gente! {user1} tá rindo da nossa cara!"
{user} disse a {user1}: "Você é bom(boa) demais em parecer inocente."
{user} foi direto(a): "Eu não confio em {user1}. Nunca confiei."
{user} disse: "{user1} fala muito e não diz nada. Típico."
{user} encarou {user1}: "Você tá jogando contra nós."
{user} disse a {user1}: "Seu sorriso não me engana mais."
{user} falou baixo, mas todo mundo ouviu: "É {user1}."
{user} disse: "Se {user1} for Fiel, eu saio daqui de joelhos."
{user} cravou: "{user1}, você é Traidor(a) e vai sair hoje."
{user} disse a {user1}: "Você empurra suspeita pros outros o tempo todo."
{user} riu: "{user1} Fiel? Conta outra."
{user} disse: "Eu vi {user1} cochichando com quem não devia."
{user} disse a {user1}: "Você só defende quem já tá salvo(a)."
{user} disse: "{user1} vota sempre no último segundo. Calculista."
{user} falou: "Minha intuição grita um nome: {user1}."
{user} disse a {user1}: "Você não chorou por ninguém até agora."
{user} apontou: "{user1} sabia quem ia morrer antes da gente."
{user} disse: "Eu não durmo em paz com {user1} nesse castelo."
{user} disse a {user1}: "Você me dá arrepio, e não é elogio."
{user} disse: "Quero ver {user1} explicar essa."
{user} jogou na cara: "{user1}, você é a falsidade em pessoa."
{user} disse a {user1}: "Seu nome não sai da minha cabeça, e não é bom sinal."
{user} disse: "{user1} faz carinho com uma mão e apunhala com a outra."
{user} falou: "Olhem pra {user1}. Olhem direito."
{user} disse a {user1}: "Você é o(a) mais perigoso(a) daqui."
{user} disse: "Chega de proteger {user1}. É Traidor(a)!"
{user} encarou {user1}: "Você nem negou direito."
{user} disse: "{user1} tem resposta pronta pra tudo. Ensaiada."
{user} disse a {user1}: "Você anda leve demais pra quem tá em perigo."
{user} disse: "Eu tô com {user1} atravessado(a) na garganta."
{user} bateu o pé: "{user1}, eu sei que você sobe aquela escada à noite."
{user} disse a {user1}: "O seu jogo tem pegada de Traidor(a)."
{user} disse: "Quem tá quieto demais aqui é {user1}."
{user} provocou {user1}: "Traidor(a) bom(boa) é assim, né? Simpático(a)."
{user} disse a {user1}: "Você riu na hora errada ontem."
{user} disse: "{user1} escolhe as vítimas pelo olhar. Repararam?"
{user} disse a {user1}: "Não adianta me abraçar. Eu sei."
{user} falou: "{user1}, você mente olhando nos olhos."
{user} disse: "O castelo tá cego pra {user1}."
{user} disse a {user1}: "Você não me engana, meu bem."
{user} disse: "Um nome, gente. Um nome só: {user1}."
{user} acusou: "{user1} tá sempre perto de quem morre."
{user} disse a {user1}: "Sua história muda toda hora."
{user} falou: "{user1} é Traidor(a) e eu vou provar."
{user} disse: "Quem votou contra os Fiéis até agora? {user1}."
{user} disse a {user1}: "Você me olha como quem já decidiu a minha morte."
{user} disse: "{user1} tem cara de quem guarda segredo na torre."
{user} ergueu a voz: "Eu não vou mais calar sobre {user1}!"
{user} disse a {user1}: "Você não tem uma única atitude de Fiel."
{user} disse: "Se eu morrer hoje, a culpa é de {user1}."
{user} disse a {user1}: "Você salvou a pele de alguém ontem. De quem?"
{user} disse: "{user1} vira a casaca conforme o vento."
{user} falou: "{user1} é tão calmo(a) que chega a assustar."
{user} disse a {user1}: "Sua defesa é boa demais. Treinou?"
{user} disse: "Eu senti na primeira conversa: {user1} não é Fiel."
{user} disse a {user1}: "A máscara tá caindo, {user1}."
{user} disse: "{user1} é o(a) cérebro da torre, certeza."
{user} disse a {user1}: "Você acusa os outros pra não ser acusado(a)."
{user} falou: "Todo mundo que desconfiou de {user1} morreu. Coincidência?"
{user} disse a {user1}: "Pode chorar, eu não vou mudar meu voto."
{user} disse: "Eu tô vendo {user1} manipular essa mesa."
{user} disse a {user1}: "Você é Traidor(a) e vai ter que conviver com isso."
{user} disse: "{user1} parece Fiel do jeito que um lobo parece ovelha."
{user} disse a {user1}: "Você não me convence nem se jurar pela mãe."
{user} disse: "Chegou a hora de {user1} sair do jogo."
{user} falou: "{user1}, seu nome tá escrito na minha testa."
{user} disse a {user1}: "Você é Traidor(a). Pronto, falei."
{user} disse: "Eu olho pra {user1} e vejo a adaga."
{user} disse a {user1}: "Você nunca erra um voto. Estranho, né?"
{user} disse: "{user1} sabe demais sobre as mortes."
{user} disse a {user1}: "Você comemorou por dentro quando mataram."
{user} disse: "Fiel não age como {user1} age."
{user} provocou: "{user1}, a torre sente sua falta."
{user} disse a {user1}: "Você tá sobrando nesse castelo."
{user} disse: "Se não for {user1}, eu não entendo mais nada."
{user} acusou: "{user1} sempre sabe pra onde o voto vai."
{user} disse a {user1}: "Seu cinismo tem limite, ou não?"
{user} disse: "{user1} brinca de Fiel. Eu não brinco."
{user} disse a {user1}: "Você é o(a) Traidor(a) mais óbvio(a) da temporada."
{user} disse: "Eu juntei as peças. Todas levam a {user1}."
{user} falou: "{user1} se esconde atrás de quem é querido."
{user} disse a {user1}: "Você é bom(boa) de papo e ruim de álibi."
{user} disse: "Não confiem em {user1}, pelo amor de Deus."
{user} disse a {user1}: "Você passou a noite onde, exatamente?"
{user} disse: "{user1} tem a frieza que Traidor precisa."
{user} disse a {user1}: "Eu te acuso. E acuso de novo amanhã."
{user} disse: "{user1} é traição com sotaque de amizade."
{user} falou: "Vocês não veem? É {user1}!"
{user} disse a {user1}: "Você só se preocupa quando o voto é em você."
{user} disse: "{user1} nunca defendeu quem morreu depois."
{user} disse a {user1}: "Seu silêncio fala mais que você."
{user} disse: "Quem tem medo de {user1} levanta a mão."
{user} disse a {user1}: "Você chegou aqui com plano de Traidor(a)."
{user} disse: "Tá na cara: {user1} é da torre."
{user} disse a {user1}: "Você me escolheu como alvo e eu escolhi você."
{user} disse: "{user1} desvia o olho toda vez que falam em traição."
{user} falou firme: "Eu escreveria o nome de {user1} dez vezes."
{user} disse a {user1}: "Você não é quem diz ser."
{user} disse: "{user1} é Traidor(a). Me cobrem se eu errar."
{user} disse a {user1}: "Você não ajudou ninguém que não fosse te ajudar."
{user} disse: "Eu senti o frio da adaga perto de {user1}."
{user} disse a {user1}: "Seu jogo é bonito, mas é de Traidor(a)."
{user} disse: "{user1} tá tão seguro(a) que só pode saber de algo."
{user} disse a {user1}: "Você é a pessoa mais perigosa que conheci aqui."
{user} disse: "Eu vi como {user1} olhou pra vítima antes de dormir."
{user} disse a {user1}: "A gente vai te desmascarar hoje."
{user} disse: "{user1} é Fiel só de fachada."
{user} disse a {user1}: "Você sorri pra mim e vota em mim. Já sei."
{user} disse: "A cobra tem nome, e é {user1}."
{user} disse a {user1}: "Você já sabe que eu sei."
{user} disse: "{user1} lidera no escuro. Traidor(a) clássico(a)."
{user} disse a {user1}: "Seu álibi tem mais buraco que queijo suíço."
{user} disse: "Eu tô cansado(a) de fingir que {user1} é inocente."
{user} disse a {user1}: "Assume, vai. Vai ser até bonito."
{user} disse: "{user1} nunca foi alvo dos Traidores. Por que será?"
{user} disse a {user1}: "Você é intocável demais pra ser Fiel."
{user} disse: "O castelo tem um rato, e ele se chama {user1}."
{user} disse a {user1}: "Eu não vou te dar mais uma noite."
{user} disse: "{user1} é o(a) melhor ator/atriz do castelo."
{user} disse a {user1}: "Você está no topo da minha lista."
{user} disse: "Olha a cara de {user1} agora. Olha!"
{user} disse a {user1}: "Seu jogo tem assinatura, e é de Traidor(a)."
{user} disse: "Eu apostaria minha vida em {user1}. Na culpa, claro."
{user} disse a {user1}: "Você finge surpresa melhor que ninguém."
{user} disse: "{user1} anda de mãos dadas com a mentira."
{user} disse a {user1}: "Te conheço há pouco, mas já conheço sua capa."
{user} disse: "Quem sobe na torre à meia-noite? {user1}."
{user} disse a {user1}: "Você tá com medo. Dá pra ver daqui."
{user} disse: "{user1} escolhe amigo pra ter escudo humano."
{user} disse a {user1}: "Traidor(a) sempre se entrega no detalhe. E você se entregou."
{user} disse: "Eu tô vendo {user1} rir por dentro."
{user} disse a {user1}: "Você quer que eu pareça louco(a). Não vai rolar."
{user} disse: "{user1} manda na torre, eu sinto."
{user} disse a {user1}: "Hoje eu não vou errar: é você."
{user} disse: "{user1} é a sombra atrás de cada morte."
{user} disse a {user1}: "Seu voto de ontem te entregou."
{user} disse: "Não caiam no charme de {user1}."
{user} disse a {user1}: "Você não sabe mentir pra mim."
{user} disse: "{user1} tem a paciência de quem sabe o final."
{user} disse a {user1}: "Você sabia da morte antes de abrir a porta."
{user} disse: "Chega de dúvida: {user1} é Traidor(a)."
{user} disse a {user1}: "Nem o seu melhor amigo confia em você."
{user} disse: "{user1} é Traidor(a) de livro didático."
{user} disse a {user1}: "Você empurrou um Fiel pro abismo. Eu vi."
{user} disse: "Eu vou falar até alguém me ouvir: {user1}!"
{user} disse a {user1}: "Seu olhar muda quando falam da torre."
{user} disse: "{user1} é bom(boa) de jogo. Bom(boa) demais."
{user} disse a {user1}: "Você não me assusta. Você me confirma."
{user} disse: "O próximo banido tem que ser {user1}."
{user} disse a {user1}: "Você brinca, mas seus olhos não riem."
{user} disse: "{user1} escolheu o lado errado dessa história."
{user} disse a {user1}: "Você me deve uma explicação e o castelo também."
{user} disse: "É {user1}. Sempre foi {user1}."
{user} disse a {user1}: "Não é pessoal, é certeza."
{user} disse: "{user1} passa pano pra quem não devia."
{user} disse a {user1}: "Você tem muito a esconder pra alguém tão calmo(a)."
{user} disse: "Eu seguiria {user1} à noite só pra provar."
{user} disse a {user1}: "Seu nome é o primeiro que penso quando alguém morre."
{user} disse: "{user1} não tem medo de morrer. Sabe por quê?"
{user} disse a {user1}: "Você é Traidor(a) e eu não tenho dúvida."
{user} disse: "Olhem os votos de {user1}. Todos em Fiéis."
{user} disse a {user1}: "Sua cara de paisagem não cola mais."
{user} disse: "{user1} é tão gentil que chega a ser suspeito."
{user} disse a {user1}: "Se você é Fiel, prova. Eu espero."
{user} disse: "{user1} dorme como quem não tem culpa. Ou tem demais."
{user} disse a {user1}: "Você fez a escolha errada ao mirar em mim."
{user} disse: "A traição tem rosto, e o rosto é de {user1}."
{user} disse a {user1}: "Eu sei o que você fez na última noite."
{user} disse: "Não adianta chorar, {user1}. Eu vi."
{user} disse a {user1}: "Seu tempo aqui acabou."
{user} disse: "Pra mim, {user1} é Traidor(a) desde a chegada."
{user} disse a {user1}: "Eu te respeito como jogador(a). Mas você é Traidor(a)."
{user} disse: "Não confio em quem nunca se exalta. Né, {user1}?"
{user} disse a {user1}: "Você tá jogando xadrez com a nossa vida."
{user} disse: "{user1}, seu voto hoje vai ser no espelho?"
{user} disse a {user1}: "Você é o motivo de eu dormir de luz acesa."
{user} disse: "Traidor(a) tem nome e sobrenome: {user1}."
{user} disse a {user1}: "Sua lealdade é só pra torre."
{user} disse: "Eu vi {user1} rir quando a porta não abriu."
{user} disse a {user1}: "Você foi esperto(a). Só não foi o suficiente."
{user} disse: "Na dúvida, eu fico com a certeza: {user1}."
{user} disse a {user1}: "Não me venha com lágrima de crocodilo."
{user} disse: "{user1} manipula as conversas como quem mexe o chá."
{user} disse a {user1}: "Você não é vítima. Você é a caçadora do castelo."
{user} disse: "{user1} escolheu a vítima com carinho. Que frieza."
{user} disse a {user1}: "Não vem me abraçar depois de me apunhalar."
{user} disse: "Eu não tenho prova, tenho certeza: {user1}."
`);

export const SAY_SUSPECT = lines(`
{user} comentou: "Sei não, viu, {user1}..."
{user} olhou de lado para {user1}: "Você tá quieto(a) demais hoje."
{user} disse: "Tô de olho em você, {user1}. Só isso."
{user} perguntou a {user1}: "Dormiu bem essa noite?"
{user} disse: "{user1} não fecha pra mim ainda."
{user} deixou escapar: "Tem alguma coisa estranha em {user1}."
{user} disse a {user1}: "Não é acusação. É um alerta."
{user} comentou: "{user1} tá calmo(a) demais pro meu gosto."
{user} disse: "{user1} está na minha lista, mas não no topo."
{user} disse a {user1}: "Você me deixa com a pulga atrás da orelha."
{user} disse: "Não sei explicar, mas {user1} me incomoda."
{user} perguntou: "{user1}, você tá escondendo alguma coisa?"
{user} disse: "Ainda não sei se é {user1}. Mas pode ser."
{user} observou: "{user1} mudou o jeito desde ontem."
{user} disse a {user1}: "Só quero entender o seu jogo."
{user} disse: "Pode ser coisa da minha cabeça, mas {user1}..."
{user} disse a {user1}: "Seu olhar desviou agora. Por quê?"
{user} comentou: "{user1} fala baixo demais quando o assunto é a torre."
{user} disse: "Eu não acuso {user1}. Mas não confio."
{user} disse a {user1}: "Você sempre concorda comigo. Até demais."
{user} disse: "{user1} tá no meu radar."
{user} perguntou a {user1}: "Por que você votou daquele jeito?"
{user} disse: "Queria acreditar em {user1}. Tá difícil."
{user} disse a {user1}: "Você anda sumido(a) das conversas."
{user} comentou: "{user1} ri de tudo. Nervoso?"
{user} disse: "Alguém mais acha {user1} estranho(a) hoje?"
{user} disse a {user1}: "Me explica uma coisa: onde você tava?"
{user} disse: "Não vou votar em {user1} hoje. Ainda."
{user} disse a {user1}: "Você tem respostas rápidas demais."
{user} comentou: "{user1} cuida demais da própria imagem."
{user} disse: "Meu sexto sentido cutucou quando {user1} falou."
{user} disse a {user1}: "Tá tudo bem mesmo com você?"
{user} disse: "{user1} é uma interrogação ambulante."
{user} disse a {user1}: "Você não me convenceu ontem."
{user} comentou: "{user1} olha pra porta toda hora."
{user} disse: "Eu anotei mentalmente o que {user1} disse."
{user} disse a {user1}: "Não tô te acusando. Tô te observando."
{user} disse: "{user1} parece saber mais do que fala."
{user} disse a {user1}: "Engraçado você perguntar isso agora."
{user} comentou: "{user1} fica tenso(a) quando falam de votos."
{user} disse: "Tem uma nuvem em cima de {user1}."
{user} disse a {user1}: "Seu jogo tá mudando e eu reparei."
{user} disse: "Eu daria mais uma chance a {user1}. Só uma."
{user} disse a {user1}: "Você tá muito seguro(a) pra quem tá em risco."
{user} comentou: "{user1} escolhe bem as palavras. Bem demais."
{user} disse: "Vou prestar mais atenção em {user1}."
{user} disse a {user1}: "Me prova que eu tô errado(a) sobre você."
{user} disse: "{user1} não é meu voto. Ainda."
{user} disse a {user1}: "Seu sorriso chegou antes da notícia."
{user} comentou: "{user1} e a torre... sei lá."
{user} disse: "Não tô tranquilo(a) com {user1}."
{user} disse a {user1}: "Você nunca fala de quem desconfia."
{user} disse: "{user1} tá jogando em cima do muro."
{user} disse a {user1}: "Você não ficou triste com a morte. Ficou?"
{user} comentou: "{user1} mudou de assunto rapidinho."
{user} disse: "Eu tenho uma dúvida, e ela tem nome: {user1}."
{user} disse a {user1}: "Você parece aliviado(a). Por quê?"
{user} disse: "{user1} me deixa desconfortável."
{user} disse a {user1}: "Não sei se você é Fiel. Me ajuda a saber."
{user} comentou: "{user1} sempre sobra nas contas."
{user} disse: "Deixa eu pensar melhor sobre {user1}."
{user} disse a {user1}: "Olha, você não tá ajudando a sua defesa."
{user} disse: "{user1} é bom(boa) de papo. Isso me preocupa."
{user} disse a {user1}: "Você ficou vermelho(a) agora."
{user} comentou: "Ninguém fala de {user1}. Estranho."
{user} disse: "Eu tô dividido(a) sobre {user1}."
{user} disse a {user1}: "Você parece ensaiado(a)."
{user} disse: "{user1} tem um jeito de quem esconde o jogo."
{user} disse a {user1}: "Quem você protege, hein?"
{user} comentou: "{user1} sempre sabe o horário das coisas."
{user} disse: "Não descarto {user1}. Não mesmo."
{user} disse a {user1}: "Você nunca parece com medo."
{user} disse: "{user1} anda com quem tá seguro(a). Curioso."
{user} disse a {user1}: "Achei estranho você não ter perguntado nada."
{user} comentou: "{user1} bocejou na hora da notícia."
{user} disse: "{user1} é meu plano B de voto."
{user} disse a {user1}: "Me diz uma coisa sincera. Só uma."
{user} disse: "Tô sentindo um cheirinho de torre em {user1}."
{user} disse a {user1}: "Você sabe que tá na minha lista, né?"
{user} comentou: "{user1} fala de todos, menos de si."
{user} disse: "Se não for {user1}, é alguém bem perto."
{user} disse a {user1}: "Você me responde com pergunta. Sempre."
{user} disse: "Não confio cem por cento em {user1}."
{user} disse a {user1}: "Você tá rodeando alguém. Quem?"
{user} comentou: "{user1} tá tranquilo(a) até demais."
{user} disse: "Eu fiquei com uma pulga com {user1} hoje."
{user} disse a {user1}: "Seu voto me pegou de surpresa."
{user} disse: "{user1} vive em cima do muro."
{user} disse a {user1}: "Você anda muito com quem morreu. Reparei."
{user} comentou: "{user1} pisca muito quando mente? Tô testando."
{user} disse: "Meu voto ainda não é {user1}, mas tá perto."
{user} disse a {user1}: "Você tem um plano, dá pra ver."
{user} disse: "Estou observando {user1} com lupa."
{user} disse a {user1}: "Não se ofenda, mas eu duvido de você."
{user} comentou: "{user1} ficou em silêncio na hora errada."
{user} disse: "Queria ter certeza sobre {user1}."
{user} disse a {user1}: "Você mudaria seu voto se eu pedisse?"
{user} disse: "{user1} tá sendo protegido(a). Por quem?"
{user} disse a {user1}: "Você é simpático(a) com todo mundo. Até com quem odeia?"
{user} comentou: "{user1} olha muito pra escada."
{user} disse: "Tem algo em {user1} que não bate."
{user} disse a {user1}: "Você anda estudando a gente, né?"
{user} disse: "{user1} me deixa em dúvida todo santo dia."
{user} disse a {user1}: "Seus olhos contam outra história."
{user} comentou: "{user1} fica sempre no canto, observando."
{user} disse: "Não é certeza, é faro: {user1}."
{user} disse a {user1}: "Você me parece cansado(a). Noite longa?"
{user} disse: "{user1} desviou do assunto de novo."
{user} disse a {user1}: "Eu queria confiar em você. Ainda não dá."
{user} comentou: "Vocês viram a reação de {user1}?"
{user} disse: "{user1} não chorou, não riu, nada. Hum."
{user} disse a {user1}: "Essa sua calma me assusta um pouco."
{user} disse: "Um alerta amarelo pisca em {user1}."
{user} disse a {user1}: "Não leva a mal, é só o jogo."
{user} comentou: "{user1} falou 'a gente' sobre quem, exatamente?"
{user} disse: "Coloquei {user1} na lista de observação."
{user} disse a {user1}: "Você anda muito misterioso(a)."
{user} disse: "Não tô pronto(a) pra acusar {user1}. Mas quase."
{user} disse a {user1}: "Você sempre chega por último. Por quê?"
{user} comentou: "{user1} sempre sobrevive. Sorte ou plano?"
{user} disse: "Eu sinto que {user1} tá escondendo algo."
{user} disse a {user1}: "Você mentiria pra mim?"
{user} disse: "{user1} tá me devendo uma explicação."
{user} disse a {user1}: "Seu nome passou pela minha cabeça hoje."
{user} comentou: "{user1} é bom(boa) em sumir das conversas difíceis."
{user} disse: "Talvez {user1}. Talvez."
{user} disse a {user1}: "Tô tentando te ler e não consigo."
{user} disse: "{user1} não me convence nem me assusta. Ainda."
{user} disse a {user1}: "Você tá leve demais. Tá bom demais."
{user} comentou: "{user1} ajeitou o cabelo três vezes. Nervoso(a)?"
{user} disse: "Eu não esqueço a reação de {user1} ontem."
{user} disse a {user1}: "Pode me contar, eu guardo segredo."
{user} disse: "{user1} vive de meia palavra."
{user} disse a {user1}: "Você tem cara de quem tem um plano secreto."
{user} comentou: "{user1} ri das piadas certas pras pessoas certas."
{user} disse: "Um passarinho me falou de {user1}."
{user} disse a {user1}: "Você parece esperar algo de mim."
{user} disse: "{user1} não é inocente. Não do jeito que parece."
{user} disse a {user1}: "Qual é o seu jogo, afinal?"
{user} comentou: "{user1} some quando o assunto esquenta."
{user} disse: "Guardei a dúvida pra mesa: {user1}."
{user} disse a {user1}: "Não se preocupe. Só estou atento(a)."
{user} disse: "{user1} parece confortável demais aqui."
{user} disse a {user1}: "Você se defende antes de ser acusado(a)."
{user} comentou: "{user1} sabe o nome de todo mundo. Estudou?"
{user} disse: "Eu vou esperar {user1} errar."
{user} disse a {user1}: "Seu silêncio de ontem me incomodou."
{user} disse: "{user1} não é o(a) mais óbvio(a). Por isso desconfio."
{user} disse a {user1}: "Você vive perto de quem manda."
{user} comentou: "{user1} olhou pro chão quando perguntaram."
{user} disse: "Tem uma pulga, e ela pula perto de {user1}."
{user} disse a {user1}: "Me convence que você é Fiel."
{user} disse: "{user1} parece esconder uma carta na manga."
{user} disse a {user1}: "Você tá muito bonzinho(a) hoje."
{user} comentou: "{user1} sempre escolhe o lado vencedor."
{user} disse: "Não tiro {user1} da cabeça."
{user} disse a {user1}: "Olha, eu tô tentando confiar."
{user} disse: "Se me perguntarem, {user1} é minha dúvida."
{user} disse a {user1}: "Seu nome sempre aparece nas minhas contas."
{user} comentou: "{user1} parece ler a mente dos Traidores."
{user} disse: "Deixei {user1} em observação."
{user} disse a {user1}: "Não precisa ficar nervoso(a). Ou precisa?"
{user} disse: "{user1} é enigma demais pra ser só Fiel."
{user} disse a {user1}: "Você não parece triste com nada."
{user} comentou: "{user1} fez uma pergunta estranha hoje."
{user} disse: "Não durmo sem pensar em {user1}."
{user} disse a {user1}: "Você se esforça pra parecer normal."
{user} disse: "Hoje eu olhei {user1} com outros olhos."
{user} disse a {user1}: "Você é difícil de decifrar."
{user} comentou: "Quem viu {user1} ontem à noite?"
{user} disse: "{user1} tem a paz de quem sabe demais."
{user} disse a {user1}: "Eu reparei no seu voto. Só isso."
{user} disse: "Meio a meio: {user1} pode ser."
{user} disse a {user1}: "Você não respondeu minha pergunta."
{user} comentou: "{user1} fica perto demais de quem acusa."
{user} disse: "Ainda estou montando o quebra-cabeça de {user1}."
{user} disse a {user1}: "Não some da minha vista, tá?"
{user} disse: "Sabe quem eu não entendo? {user1}."
{user} disse a {user1}: "Você me deixa confuso(a)."
{user} comentou: "{user1} tá de olho em mim também, né?"
{user} disse: "Não é nada contra {user1}. É tudo contra, na verdade."
{user} disse a {user1}: "Se eu tiver errado(a), me desculpa depois."
{user} disse: "{user1} anda tão prestativo(a). Por quê?"
{user} disse a {user1}: "Seu tom mudou comigo."
{user} comentou: "{user1} some quando tem votação."
{user} disse: "Eu tô com uma sensação ruim sobre {user1}."
{user} disse a {user1}: "Você esconde o jogo muito bem."
{user} disse: "Tenho um palpite, mas guardo: {user1}."
{user} disse a {user1}: "Não vai me contar nada, né?"
{user} comentou: "{user1} fez cara de alívio. Eu vi."
{user} disse: "{user1} passou do ponto de simpatia."
{user} disse a {user1}: "Você já escolheu um lado, não escolheu?"
{user} disse: "Vou ficar colado(a) em {user1} hoje."
{user} disse a {user1}: "Você anda estranho(a). Todo mundo notou."
{user} comentou: "{user1} fala demais quando tá nervoso(a)."
{user} disse: "Não é sobre gostar de {user1}. É sobre confiar."
{user} disse a {user1}: "Você me parece um livro fechado."
{user} ergueu a sobrancelha para {user1}: "Hm. Anotado."
{user} disse a {user1}: "Seu silêncio fala alto, sabia?"
{user} disse: "{user1}, você piscou demais agora."
{user} disse a {user1}: "Engraçado você dizer isso."
{user} disse a {user1}: "Você mudou de assunto rapidinho, hein?"
{user} disse a {user1}: "Tô com uma pulga atrás da orelha com você."
{user} disse a {user1}: "Não é pessoal, mas você me intriga."
`);

export const SAY_INSULT = lines(`
{user} disse a {user1}: "Você é a pessoa mais falsa que eu já conheci."
{user} perdeu a paciência: "{user1}, você é insuportável!"
{user} chamou {user1} de cobra na frente de todos.
{user} disse: "{user1}, ninguém aguenta mais você."
{user} revirou os olhos para {user1}: "Ninguém perguntou."
{user} disse a {user1}: "Você é um poço de arrogância."
{user} soltou: "{user1}, vai caçar o que fazer."
{user} disse a {user1}: "Seu perfume é mais forte que seu caráter."
{user} disse: "{user1} tem a simpatia de uma porta."
{user} disse a {user1}: "Você fala muito pra quem pensa pouco."
{user} disparou: "{user1}, você é uma piada sem graça."
{user} disse a {user1}: "Você é o tipo de gente que eu evito lá fora."
{user} disse: "Com todo respeito, {user1}: que pessoa chata."
{user} disse a {user1}: "Seu ego não cabe nesse castelo."
{user} disse: "{user1}, você é o mosquito da minha noite."
{user} disse a {user1}: "Você é fraco(a) e todo mundo sabe."
{user} disse: "Eu tenho pena de quem confia em {user1}."
{user} disse a {user1}: "Você não passa de figurante nesse jogo."
{user} disse: "{user1}, cala a boca um pouquinho, por favor."
{user} disse a {user1}: "Você é mais falso(a) que nota de três reais."
{user} disse: "{user1} é o(a) chato(a) oficial do castelo."
{user} disse a {user1}: "Você não tem um pingo de noção."
{user} bufou: "{user1}, você cansa qualquer um."
{user} disse a {user1}: "Vai tomar um chá de simancol."
{user} disse: "{user1} é do tipo que puxa o tapete e pede desculpa."
{user} disse a {user1}: "Você é uma decepção ambulante."
{user} disse: "{user1}, vai dormir que você tá insuportável."
{user} disse a {user1}: "Seu teatro dá sono."
{user} disse: "{user1}, você é o drama em pessoa."
{user} disse a {user1}: "Você só sabe falar mal dos outros."
{user} disse: "{user1} tem cara de quem conta vantagem até dormindo."
{user} disse a {user1}: "Você é pior do que eu imaginava."
{user} disse: "Eu não suporto a voz de {user1}."
{user} disse a {user1}: "Você é mimado(a) demais pra esse jogo."
{user} disse: "{user1}, seu lugar é na plateia."
{user} disse a {user1}: "Você é uma nuvem carregada."
{user} disse: "{user1} é fofoqueiro(a) profissional."
{user} disse a {user1}: "Você não tem estratégia, tem sorte."
{user} disse: "{user1} é tão sem sal que o mingau tem mais gosto."
{user} disse a {user1}: "Você é o motivo das minhas enxaquecas."
{user} disse: "{user1}, você é chato(a) até em silêncio."
{user} disse a {user1}: "Você vive de aparência."
{user} disse: "{user1} é a definição de pessoa tóxica."
{user} disse a {user1}: "Seu jogo é fraco igual chá frio."
{user} disse: "{user1}, você é um(a) sonso(a) de carteirinha."
{user} disse a {user1}: "Você acha que engana alguém?"
{user} disse: "{user1} é tão falso(a) que até o espelho duvida."
{user} disse a {user1}: "Você é intragável."
{user} disse: "{user1} é o(a) planta do castelo, e planta de plástico."
{user} disse a {user1}: "Você não faz falta nenhuma."
{user} disse: "{user1}, você é um desastre de pessoa."
{user} disse a {user1}: "Vai procurar sua turma."
{user} disse: "{user1} é o(a) rei/rainha da fofoca barata."
{user} disse a {user1}: "Você não tem personalidade própria."
{user} disse: "{user1} copia todo mundo. Nem jogo próprio tem."
{user} disse a {user1}: "Seu sorriso é de plástico."
{user} disse: "Não aguento mais olhar pra {user1}."
{user} disse a {user1}: "Você é um(a) aproveitador(a)."
{user} disse: "{user1} só respira porque é de graça."
{user} disse a {user1}: "Você é o erro de casting da temporada."
{user} disse: "{user1}, você é mala sem alça."
{user} disse a {user1}: "Vai ser lembrado(a) como o(a) chato(a) do castelo."
{user} disse: "{user1} tem a sensibilidade de uma pedra."
{user} disse a {user1}: "Você só pensa em você."
{user} disse: "{user1} é mais perdido(a) que cego em tiroteio."
{user} disse a {user1}: "Você é arrogante e nem disfarça."
{user} disse: "{user1}, você é o(a) vilão(ã) sem carisma."
{user} disse a {user1}: "Você é tão previsível que dá preguiça."
{user} disse: "{user1} é um(a) interesseiro(a) de marca maior."
{user} disse a {user1}: "Você não aguenta uma crítica, né?"
{user} disse: "{user1} é o tipo de pessoa que cospe no prato que comeu."
{user} disse a {user1}: "Você é a pior companhia do castelo."
{user} disse: "{user1}, você é barulho sem conteúdo."
{user} disse a {user1}: "Seu jogo é cópia mal feita."
{user} disse: "{user1} é tóxico(a) até pra planta."
{user} disse a {user1}: "Você é uma pessoa pequena."
{user} disse: "{user1} vive de fazer caras e bocas."
{user} disse a {user1}: "Ninguém aqui te suporta, só finge."
{user} disse: "{user1} é o(a) mais chato(a) desde a chegada."
{user} disse a {user1}: "Você é tão falso(a) que devia vir com etiqueta."
{user} disse: "{user1}, você é a vergonha da temporada."
{user} disse a {user1}: "Você é passivo-agressivo(a) nível máximo."
{user} disse: "{user1} parece aqueles parentes que ninguém convida."
{user} disse a {user1}: "Seu charme vence na primeira semana, e só."
{user} disse: "{user1} é um(a) grosso(a) sem remédio."
{user} disse a {user1}: "Você é tão raso(a) que dá pra ver o fundo."
{user} disse: "Eu prefiro conversar com a armadura do salão do que com {user1}."
{user} disse a {user1}: "Você é presunçoso(a) demais."
{user} disse: "{user1}, você é um furacão de chatice."
{user} disse a {user1}: "Você é o tipo que ri da desgraça dos outros."
{user} disse: "{user1} é tão sem graça que as velas se apagam."
{user} disse a {user1}: "Seu jeito me dá nos nervos."
{user} disse: "{user1} é mimimi em forma de gente."
{user} disse a {user1}: "Você é um(a) puxa-saco profissional."
{user} disse: "{user1} não tem vergonha na cara."
{user} disse a {user1}: "Você é intrometido(a) demais."
{user} disse: "{user1}, você tem o carisma de uma geladeira."
{user} disse a {user1}: "Você é uma grande farsa."
{user} disse: "Se chatice desse prêmio, {user1} já tinha ganhado."
{user} disse a {user1}: "Você é um(a) egoísta sem tamanho."
{user} disse: "{user1} é o(a) vilão(ã) da própria novela."
{user} disse a {user1}: "Você tem a delicadeza de um trator."
{user} disse: "{user1}, você é mais perdido(a) que o mapa do castelo."
{user} disse a {user1}: "Seu caráter tem preço, e é barato."
{user} disse: "{user1} é tão seco(a) que o deserto tem inveja."
{user} disse a {user1}: "Você é um poço de veneno."
{user} disse: "{user1} vive de pose."
{user} disse a {user1}: "Você é patético(a), sinceramente."
{user} disse: "{user1} tem língua mais afiada que adaga."
{user} disse a {user1}: "Você é o câncer dessa convivência."
{user} disse: "{user1}, seu lugar não é aqui."
{user} disse a {user1}: "Você é tão invejoso(a) que chega a dar pena."
{user} disse: "{user1} é o tipo que finge amizade por prêmio."
{user} disse a {user1}: "Você é a pessoa mais cansativa do mundo."
{user} disse: "{user1} parece aquele alarme que ninguém sabe desligar."
{user} disse a {user1}: "Você é uma pessoa amarga."
{user} disse: "{user1} é uma vergonha pros Fiéis e pros Traidores."
{user} disse a {user1}: "Você não tem classe nenhuma."
{user} disse: "{user1} é tão sonso(a) que tropeça no próprio teatro."
{user} disse a {user1}: "Você é insuportável, e não é de hoje."
{user} disse: "{user1} é birrento(a) como criança."
{user} disse a {user1}: "Você só sabe reclamar."
{user} disse: "{user1}, você é um tédio."
{user} disse a {user1}: "Você é uma pessoa sem palavra."
{user} disse: "{user1} é o(a) inconveniente oficial."
{user} disse a {user1}: "Você é cara de pau demais."
{user} disse: "{user1} tem o brilho de uma lâmpada queimada."
{user} disse a {user1}: "Você é mal-educado(a) e acha que é sincero(a)."
{user} disse: "{user1} é dissimulado(a) e nem disfarça."
{user} disse a {user1}: "Você é o(a) mais irritante da face da Terra."
{user} disse: "{user1}, some da minha frente."
{user} disse a {user1}: "Você é uma bomba-relógio de chatice."
{user} disse: "{user1} é falso(a) de doer."
{user} disse a {user1}: "Seu lugar é na primeira eliminação."
{user} disse: "{user1} é o tipo de gente que vira as costas no primeiro problema."
{user} disse a {user1}: "Você é desagradável até dando bom dia."
{user} disse: "{user1} é o(a) queridinho(a) de ninguém."
{user} disse a {user1}: "Você é orgulhoso(a) e vazio(a)."
{user} disse: "{user1} tem cara de quem rouba o último pedaço."
{user} disse a {user1}: "Você é mentiroso(a) compulsivo(a)."
{user} disse: "{user1}, que ser humano difícil."
{user} disse a {user1}: "Você acha que é protagonista. Não é."
{user} disse: "{user1} é tão cínico(a) que devia dar aula."
{user} disse a {user1}: "Você é uma pessoa sem empatia."
{user} disse: "{user1} parece um mosquito na orelha."
{user} disse a {user1}: "Você é a pior parte do meu dia."
{user} disse: "{user1} é mimado(a) e metido(a)."
{user} disse a {user1}: "Você é o tipo que só aparece pra causar."
{user} disse: "{user1} é tão frio(a) que dá pra guardar sorvete."
{user} disse a {user1}: "Você fala e ninguém escuta. Já reparou?"
{user} disse: "{user1} é chato(a) em três idiomas."
{user} disse a {user1}: "Você é o maior erro desse castelo."
{user} disse: "{user1}, você nem joga, só atrapalha."
{user} disse a {user1}: "Você é hipócrita dos pés à cabeça."
{user} disse: "{user1} é a encarnação do mau humor."
{user} disse a {user1}: "Você é um(a) sem noção."
{user} disse: "{user1} é tão falso(a) que o nome devia ser outro."
{user} disse a {user1}: "Você é uma pessoa ruim. Simples assim."
{user} disse: "{user1}, vai lavar uma louça que você ganha mais."
{user} disse a {user1}: "Você é o sal no meu machucado."
{user} disse: "{user1} tem mais pose que conteúdo."
{user} disse a {user1}: "Você é chato(a) de doer os ouvidos."
{user} disse: "{user1} é uma ameaça ao bom senso."
{user} disse a {user1}: "Você é o(a) mais arrogante que já vi."
{user} disse: "{user1}, você é um(a) sanguessuga."
{user} disse a {user1}: "Você não tem graça, desiste."
{user} disse: "{user1} é o(a) Judas do castelo."
{user} disse a {user1}: "Você é tão manipulador(a) que dá nojo."
{user} disse: "{user1} é o cisco no olho de todo mundo."
{user} disse a {user1}: "Seu lugar é bem longe de mim."
{user} disse: "{user1} é tão sem noção que assusta."
{user} disse a {user1}: "Você tem inveja até da própria sombra."
{user} disse: "{user1}, você é desprezível."
{user} disse a {user1}: "Você é a razão de eu querer ir embora."
{user} disse: "{user1} é intragável e ponto."
{user} disse a {user1}: "Você é uma serpente de salto alto."
{user} disse: "{user1} é o(a) pior colega de quarto possível."
{user} disse a {user1}: "Você é chato(a) de manhã, de tarde e de noite."
{user} disse: "{user1} parece que nasceu de mau humor."
{user} disse a {user1}: "Você é uma farsa bem vestida."
{user} disse: "{user1} é o tipo que mente até no próprio nome."
{user} disse a {user1}: "Você é pequeno(a) demais pra esse jogo."
{user} disse: "{user1} é veneno puro."
{user} disse a {user1}: "Você me dá preguiça."
{user} disse: "{user1}, que pessoa sem sal, sem açúcar e sem noção."
{user} disse a {user1}: "Você é tão previsível quanto a chuva escocesa."
{user} disse: "{user1} é um(a) fingido(a) de primeira."
{user} disse a {user1}: "Você não merece nem o meu desprezo."
{user} disse: "{user1} é um desastre em forma de gente."
{user} disse a {user1}: "Você é a vergonha alheia do castelo."
{user} disse: "{user1} é tão chato(a) que o eco pede pra parar."
{user} disse a {user1}: "Você é uma pessoa mesquinha."
{user} disse: "{user1}, você é o furo do barco."
{user} disse a {user1}: "Você é fútil, fútil, fútil."
{user} disse: "{user1} é desleal até com o travesseiro."
{user} disse a {user1}: "Você devia ter ficado em casa."
{user} disse: "{user1} é o tipo de pessoa que eu bloquearia."
{user} disse a {user1}: "Você é uma pedra no meu sapato."
{user} disse: "{user1} é o próprio mau agouro."
{user} disse a {user1}: "Você é o prêmio de consolação do elenco."
{user} disse: "{user1} é tão falso(a) que o sorriso descasca."
{user} disse a {user1}: "Você me cansa só de existir."
`);
