import { lines } from './lines';

/** Falas do jogador na torre: {user} = jogador, {user1} = parceiro(a) de traição, {user2} = o(a) fiel de quem se fala. */

export const SAY_TOWER_ASK = lines(`
{user} perguntou a {user1}: "Quem você quer hoje à noite?"
{user} disse a {user1}: "Me fala o seu nome pra hoje."
{user} abriu o pergaminho para {user1}: "Quem vai ser?"
{user} perguntou a {user1}: "Em quem você tá pensando?"
{user} disse a {user1}: "Você já escolheu, né? Fala."
{user} perguntou a {user1}: "Quem te incomoda mais lá embaixo?"
{user} disse a {user1}: "Vamos decidir juntos. Seu nome?"
{user} perguntou a {user1}: "Quem tá chegando perto demais de nós?"
{user} disse a {user1}: "Me diz quem você tiraria do caminho."
{user} perguntou a {user1}: "Qual é o seu alvo?"
{user} disse a {user1}: "Antes de eu falar, quero ouvir você."
{user} perguntou a {user1}: "Quem desconfia de você?"
{user} disse a {user1}: "A vela tá acabando. Quem?"
{user} perguntou a {user1}: "Quem seria o golpe mais limpo?"
{user} disse a {user1}: "Me conta o seu plano pra essa noite."
{user} perguntou a {user1}: "Quem ninguém ia esperar?"
{user} disse a {user1}: "Você tem cara de quem já decidiu."
{user} perguntou a {user1}: "Quem é a maior ameaça pra você?"
{user} disse a {user1}: "Quero seu voto antes de mostrar o meu."
{user} perguntou a {user1}: "Quem você não aguenta mais ver no salão?"
{user} disse a {user1}: "Fala o nome sem enrolar."
{user} perguntou a {user1}: "Quem tá cercando a gente?"
{user} disse a {user1}: "Vamos alinhar: quem é o nome?"
{user} perguntou a {user1}: "Quem o castelo vai chorar menos?"
{user} disse a {user1}: "Me mostra o nome no pergaminho."
{user} perguntou a {user1}: "Quem faria mais falta pros Fiéis?"
{user} disse a {user1}: "Diz aí quem tá te tirando o sono."
{user} perguntou a {user1}: "Quem tá mais perto de descobrir a gente?"
{user} disse a {user1}: "Me passa sua lista, parceiro(a)."
{user} perguntou a {user1}: "Quem você mataria sem pensar duas vezes?"
{user} disse a {user1}: "Me fala o nome e o motivo."
{user} perguntou a {user1}: "Quem seria a vítima mais segura?"
{user} disse a {user1}: "Quero entender o que você tá pensando."
{user} perguntou a {user1}: "Quem você acha que tem escudo?"
{user} disse a {user1}: "Se a escolha fosse sua, quem morria?"
{user} perguntou a {user1}: "Quem faz a mesa mudar de ideia?"
{user} disse a {user1}: "Vamos, eu confio no seu faro."
{user} perguntou a {user1}: "Quem tá jogando bem demais?"
{user} disse a {user1}: "Me fala seu alvo e eu digo se concordo."
{user} perguntou a {user1}: "Quem vai confundir mais o castelo amanhã?"
{user} disse a {user1}: "Seu nome primeiro. Depois o meu."
{user} perguntou a {user1}: "Quem você acha que a mesa vai proteger?"
{user} disse a {user1}: "Tem um nome na sua boca. Solta."
{user} perguntou a {user1}: "Quem é querido demais pra continuar vivo?"
{user} disse a {user1}: "Me ajuda a decidir sem briga."
{user} perguntou a {user1}: "Quem tá mais perigoso(a) desde ontem?"
{user} disse a {user1}: "Qual o nome que te dá mais prazer riscar?"
{user} perguntou a {user1}: "Quem te acusou na mesa?"
{user} disse a {user1}: "Fala logo, que o sol não espera."
{user} perguntou a {user1}: "Quem é o elo mais forte dos Fiéis?"
{user} disse a {user1}: "Me dá um nome e uma razão."
{user} perguntou a {user1}: "Quem vai fazer o castelo chorar mais?"
{user} disse a {user1}: "Eu tenho um nome. Você tem outro?"
{user} perguntou a {user1}: "Quem tá mais sozinho(a) lá embaixo?"
{user} disse a {user1}: "Me conta quem você escolheu e por quê."
{user} perguntou a {user1}: "Quem nos deixa mais seguros se sumir?"
{user} disse a {user1}: "Me fala seu alvo, sem medo."
{user} perguntou a {user1}: "Quem você acha que vai votar em nós amanhã?"
{user} disse a {user1}: "Precisamos de um nome certeiro. Qual?"
{user} perguntou a {user1}: "Quem lidera os Fiéis agora?"
{user} disse a {user1}: "Sussurra o nome, só pra mim."
{user} perguntou a {user1}: "Quem está incomodando mais a torre?"
{user} disse a {user1}: "Me fala quem você risca primeiro."
{user} perguntou a {user1}: "Quem é o próximo? Pensa bem."
{user} disse a {user1}: "Quero ouvir seu raciocínio."
{user} perguntou a {user1}: "Quem ainda não desconfiou da gente?"
{user} disse a {user1}: "Me mostra quem você quer longe."
{user} perguntou a {user1}: "Quem pode virar Traidor(a) se sobrar?"
{user} disse a {user1}: "Me fala o nome que ninguém vai esperar."
{user} perguntou a {user1}: "Quem vai ser o susto de amanhã?"
{user} disse a {user1}: "Seu instinto aponta pra quem?"
{user} perguntou a {user1}: "Quem faz mais barulho lá embaixo?"
{user} disse a {user1}: "Não guarda o nome pra você. Divide."
{user} perguntou a {user1}: "Quem a gente não pode deixar chegar na final?"
{user} disse a {user1}: "Qual o fiel que mais te assusta?"
{user} perguntou a {user1}: "Quem seria o golpe perfeito?"
{user} disse a {user1}: "Me conta seu alvo antes da gente votar."
{user} perguntou a {user1}: "Quem te olhou torto hoje?"
{user} disse a {user1}: "Me fala quem, e a gente resolve."
{user} perguntou a {user1}: "Quem você acha que tá investigando a gente?"
{user} disse a {user1}: "Eu quero seu nome, parceiro(a)."
{user} perguntou a {user1}: "Quem é intocável lá embaixo? Porque aqui não é."
{user} disse a {user1}: "Fala quem, a vela tá pingando."
{user} perguntou a {user1}: "Quem tá unindo os Fiéis?"
{user} disse a {user1}: "Me passa o nome que te faz sorrir."
{user} perguntou a {user1}: "Quem é a peça que a gente tira do tabuleiro?"
{user} disse a {user1}: "Me diz seu alvo e eu digo o meu."
{user} perguntou a {user1}: "Quem vai dar menos trabalho?"
{user} disse a {user1}: "Me conta: quem você não suporta?"
{user} perguntou a {user1}: "Quem é o mais esperto lá embaixo?"
{user} disse a {user1}: "Me fala quem, que eu já tô pronto(a)."
{user} perguntou a {user1}: "Quem tá protegendo quem?"
{user} disse a {user1}: "Vamos escolher com calma. Seu nome?"
{user} perguntou a {user1}: "Quem vai fazer mais diferença sumindo?"
{user} disse a {user1}: "Me fala seu palpite da noite."
{user} perguntou a {user1}: "Quem você deixaria viver mais um dia?"
{user} disse a {user1}: "Sem rodeio: quem vai hoje?"
{user} perguntou a {user1}: "Quem ameaça mais o seu disfarce?"
{user} disse a {user1}: "Me dá sua escolha, que a gente vota junto."
{user} perguntou a {user1}: "Quem você acha que o castelo não vai entender?"
{user} disse a {user1}: "Tem alguém no seu caminho? Fala."
{user} perguntou a {user1}: "Quem é o favorito pra ganhar? A gente tira."
{user} disse a {user1}: "Me fala seu nome, sem culpa."
{user} perguntou a {user1}: "Quem está na sua mira desde o começo?"
{user} disse a {user1}: "Eu confio no seu nome. Qual é?"
{user} perguntou a {user1}: "Quem você mandaria embora primeiro?"
{user} disse a {user1}: "Me fala quem, e eu te conto meu plano."
{user} perguntou a {user1}: "Quem pode estar com escudo hoje?"
{user} disse a {user1}: "Vamos decidir antes que amanheça. Quem?"
{user} perguntou a {user1}: "Quem você acha mais fácil?"
{user} disse a {user1}: "Me fala sua vítima ideal."
{user} perguntou a {user1}: "Quem tem mais aliados lá embaixo?"
{user} disse a {user1}: "Quero sua opinião sincera. Quem?"
{user} perguntou a {user1}: "Quem vai desestabilizar os Fiéis?"
{user} disse a {user1}: "Me fala quem incomoda você de verdade."
{user} perguntou a {user1}: "Quem tá jogando pra nos pegar?"
{user} disse a {user1}: "Seu nome, parceiro(a), antes que eu escolha sozinho(a)."
{user} perguntou a {user1}: "Quem seria a surpresa do café?"
{user} disse a {user1}: "Me conta quem você escolheria se estivesse sozinho(a)."
{user} perguntou a {user1}: "Quem você acha que tá desconfiando de mim?"
{user} disse a {user1}: "Me fala quem, e a gente acaba logo."
{user} perguntou a {user1}: "Quem é o mais querido? A gente leva."
{user} disse a {user1}: "Vamos, me diz: quem?"
{user} perguntou a {user1}: "Quem pode nos entregar na mesa?"
{user} disse a {user1}: "Me fala o nome que você riscaria de olhos fechados."
{user} perguntou a {user1}: "Quem é a próxima estrela a apagar?"
{user} disse a {user1}: "Me passa a sua ideia de hoje."
{user} perguntou a {user1}: "Quem é o seu inimigo lá embaixo?"
{user} disse a {user1}: "Me fala o nome e a gente sela."
{user} perguntou a {user1}: "Quem vai deixar o castelo mais perdido?"
{user} disse a {user1}: "Me fala quem você acha que merece."
{user} perguntou a {user1}: "Quem pode virar a mesa contra nós?"
{user} disse a {user1}: "Me mostra o nome que tá na sua cabeça."
{user} perguntou a {user1}: "Quem a gente tira sem deixar rastro?"
{user} disse a {user1}: "Me fala quem, que eu apoio."
{user} perguntou a {user1}: "Quem tem cara de próximo alvo?"
{user} disse a {user1}: "Quero ouvir antes de decidir: quem?"
{user} perguntou a {user1}: "Quem é o perigo número um?"
{user} disse a {user1}: "Me fala quem você quer longe do prêmio."
{user} perguntou a {user1}: "Quem está sobrando no nosso caminho?"
{user} disse a {user1}: "Seu alvo de hoje, por favor."
{user} perguntou a {user1}: "Quem vai deixar a mesa mais cega?"
{user} disse a {user1}: "Me conta quem você quer, sem pressa."
{user} perguntou a {user1}: "Quem sabe demais sobre nós?"
{user} disse a {user1}: "Me fala seu alvo, e eu digo se topo."
{user} perguntou a {user1}: "Quem tá rondando a escada?"
{user} disse a {user1}: "Me dá um nome e a gente segue."
{user} perguntou a {user1}: "Quem você salvaria? E quem não?"
{user} disse a {user1}: "Me fala quem, o tempo tá correndo."
{user} perguntou a {user1}: "Quem fez a pergunta errada hoje?"
{user} disse a {user1}: "Me fala seu nome antes do meu."
{user} perguntou a {user1}: "Quem pode estar juntando votos contra nós?"
{user} disse a {user1}: "Me dá sua escolha de coração frio."
{user} perguntou a {user1}: "Quem vai causar mais confusão amanhã?"
{user} disse a {user1}: "Me fala quem, e sem pena."
{user} perguntou a {user1}: "Quem tá virando líder lá embaixo?"
{user} disse a {user1}: "Me fala o nome, e a noite é nossa."
{user} perguntou a {user1}: "Quem pode desconfiar de você amanhã?"
{user} disse a {user1}: "Me mostra quem você marcou."
{user} perguntou a {user1}: "Quem é a vítima que ninguém vai ligar à gente?"
{user} disse a {user1}: "Me fala seu escolhido."
{user} perguntou a {user1}: "Quem tem o olhar mais atento lá embaixo?"
{user} disse a {user1}: "Me fala quem e vamos dormir tranquilos."
{user} perguntou a {user1}: "Quem tá unido demais com quem?"
{user} disse a {user1}: "Me passa o nome antes de descer."
{user} perguntou a {user1}: "Quem incomoda nosso plano?"
{user} disse a {user1}: "Me conta quem vai ser o susto."
{user} perguntou a {user1}: "Quem você quer ver chorando no café? Digo, quem vai fazer chorar?"
{user} disse a {user1}: "Me fala seu alvo, parceiro(a) de capa."
{user} perguntou a {user1}: "Quem deixa a gente mais tranquilo(a) se sair?"
{user} disse a {user1}: "Me diz quem, e a gente age."
{user} perguntou a {user1}: "Quem é o mais difícil de enganar?"
{user} disse a {user1}: "Me fala quem, com a mão no coração frio."
{user} perguntou a {user1}: "Quem está te dando mais trabalho?"
{user} disse a {user1}: "Me mostra o nome que você circulou."
{user} perguntou a {user1}: "Quem ainda confia demais em nós? Dá pra usar."
{user} disse a {user1}: "Me fala quem, que eu confio no teu olho."
{user} perguntou a {user1}: "Quem tem mais chance de nos desmascarar?"
{user} disse a {user1}: "Me conta o nome, parceiro(a)."
{user} perguntou a {user1}: "Quem vai nos custar mais caro vivo?"
{user} disse a {user1}: "Me fala seu nome favorito pra essa noite."
{user} perguntou a {user1}: "Quem a gente tira pra ganhar tempo?"
{user} disse a {user1}: "Me dá o nome, e a gente escreve junto."
{user} perguntou a {user1}: "Quem é o coração dos Fiéis?"
{user} disse a {user1}: "Me fala quem, e seja rápido(a)."
{user} perguntou a {user1}: "Quem vai deixar mais saudade? Esse(a) é bom(boa)."
{user} disse a {user1}: "Me passa sua vítima da vez."
{user} perguntou a {user1}: "Quem está desconfiando da torre?"
{user} disse a {user1}: "Me fala quem, e amanhã a gente chora junto."
{user} perguntou a {user1}: "Quem mais atrapalha a nossa vitória?"
{user} disse a {user1}: "Me fala seu nome e eu fecho com você."
{user} disse a {user1}: "Sua vez de escolher. Quem?"
{user} perguntou a {user1}: "Quem está chegando perto de nós?"
{user} disse a {user1}: "Fala. Quem some do mapa hoje?"
{user} perguntou a {user1}: "Tem alguém que você não aguenta mais?"
{user} disse a {user1}: "Pensou em alguém pra essa noite?"
{user} perguntou a {user1}: "Quem ameaça mais a gente agora?"
{user} disse a {user1}: "Me dá sua lista. A curta."
{user} perguntou a {user1}: "Vamos de estratégia ou de vingança hoje?"
{user} perguntou a {user1}, acendendo a vela: "E aí, quem?"
`);

export const SAY_TOWER_KILL = lines(`
{user} bateu o dedo no pergaminho: "Hoje tem que ser {user2}, {user1}."
{user} tentou convencer {user1}: "{user2} precisa morrer esta noite."
{user} disse a {user1}: "{user2} está desconfiando de nós. Hoje."
{user} disse a {user1}: "Se {user2} viver mais um dia, a gente cai."
{user} disse a {user1}: "Vamos de {user2}. Confia em mim."
{user} disse a {user1}: "{user2} tá chegando perto demais."
{user} disse a {user1}: "{user2} manda nos votos. Tira {user2}."
{user} disse a {user1}: "Ninguém vai suspeitar se for {user2}."
{user} disse a {user1}: "{user2} é querido(a) demais. O luto vai confundir todo mundo."
{user} disse a {user1}: "{user2} olhou pra mim estranho hoje. É hoje."
{user} disse a {user1}: "Vota comigo: {user2}."
{user} disse a {user1}: "{user2} é a maior ameaça que a gente tem."
{user} disse a {user1}: "A gente precisa apagar {user2} antes que {user2} apague a gente."
{user} disse a {user1}: "{user2} vai nos entregar na próxima mesa."
{user} disse a {user1}: "Escreve {user2}. Eu escrevo também."
{user} disse a {user1}: "{user2} tá investigando a torre. Tenho certeza."
{user} disse a {user1}: "Eu não durmo com {user2} vivo(a)."
{user} disse a {user1}: "{user2} é o cérebro dos Fiéis."
{user} disse a {user1}: "Tirar {user2} deixa a mesa sem rumo."
{user} disse a {user1}: "{user2} tá ganhando força. Corta agora."
{user} disse a {user1}: "Confia: {user2} é o nome."
{user} disse a {user1}: "{user2} já fez perguntas demais sobre você."
{user} disse a {user1}: "{user2} tem os olhos mais atentos lá embaixo."
{user} disse a {user1}: "Com {user2} fora, a gente respira."
{user} disse a {user1}: "{user2} tá juntando os Fiéis contra nós."
{user} disse a {user1}: "{user2} é o próximo. Não tem discussão."
{user} disse a {user1}: "Se não for {user2} hoje, vai ser tarde amanhã."
{user} disse a {user1}: "{user2} tem uma aliança forte. Quebra ela."
{user} disse a {user1}: "Eu voto {user2}, e você devia votar também."
{user} disse a {user1}: "{user2} tem cara de quem ganha a final. Não pode."
{user} disse a {user1}: "Ninguém vai ligar a morte de {user2} a nós."
{user} disse a {user1}: "{user2} nunca vai ser banido(a). Então a gente resolve."
{user} disse a {user1}: "{user2} tá me encarando demais."
{user} disse a {user1}: "Pensa em quanto {user2} atrapalha. Pensa."
{user} disse a {user1}: "{user2} é influente. Influência é perigo."
{user} disse a {user1}: "{user2} viu algo. Eu sei que viu."
{user} disse a {user1}: "{user2} é a pedra no nosso sapato."
{user} disse a {user1}: "Vamos de {user2} e amanhã a gente chora bonito."
{user} disse a {user1}: "{user2} tá com a gente na mira. A gente mira primeiro."
{user} disse a {user1}: "{user2} tem a mesa na mão."
{user} disse a {user1}: "Eu sinto que {user2} vai nos desmascarar."
{user} disse a {user1}: "{user2} é o voto mais certeiro."
{user} disse a {user1}: "{user2} tá sem escudo hoje, eu vi."
{user} disse a {user1}: "Com {user2} vivo(a), a gente não chega na final."
{user} disse a {user1}: "{user2} é leal demais aos Fiéis. Perigoso."
{user} disse a {user1}: "{user2} fala demais sobre traição."
{user} disse a {user1}: "Eu escolho {user2}, e é por estratégia."
{user} disse a {user1}: "Não tem jeito: {user2}."
{user} disse a {user1}: "{user2} tá desconfiando de você. Te protege, vota nele(a)."
{user} disse a {user1}: "{user2} é o(a) Fiel mais esperto(a). Por isso."
{user} disse a {user1}: "{user2} tá costurando votos. Corta a linha."
{user} disse a {user1}: "Amanhã o castelo acorda sem {user2}."
{user} disse a {user1}: "{user2} tem que ir antes que junte provas."
{user} disse a {user1}: "Eu não suporto mais {user2}."
{user} disse a {user1}: "{user2} é querido(a) por todos. Isso quebra os Fiéis."
{user} disse a {user1}: "Vamos juntos em {user2}. É o mais inteligente."
{user} disse a {user1}: "{user2} é a pior ameaça, e você sabe."
{user} disse a {user1}: "{user2} tá perto de descobrir tudo."
{user} disse a {user1}: "{user2} é a nossa sentença. Ou a gente tira, ou cai."
{user} disse a {user1}: "Eu voto {user2} com a consciência tranquila."
{user} disse a {user1}: "{user2} tá liderando os Fiéis sem perceber."
{user} disse a {user1}: "{user2} vai ser o(a) herói(heroína) deles. Não deixa."
{user} disse a {user1}: "Escolhe {user2} comigo e a gente dorme em paz."
{user} disse a {user1}: "{user2} faz perguntas certas demais."
{user} disse a {user1}: "Tira {user2} e a mesa vira caos."
{user} disse a {user1}: "{user2} é o(a) único(a) que me assusta."
{user} disse a {user1}: "{user2} tá blindado(a) na mesa. Só nos resta a noite."
{user} disse a {user1}: "{user2} é peça-chave deles."
{user} disse a {user1}: "{user2} tá prestes a acusar você."
{user} disse a {user1}: "Vamos de {user2}, sem pena."
{user} disse a {user1}: "{user2} tá mais forte a cada dia."
{user} disse a {user1}: "{user2} é o próximo alvo, e eu não abro mão."
{user} disse a {user1}: "{user2} tá rindo da gente. Agora não vai mais."
{user} disse a {user1}: "Eu preciso que você vote em {user2}."
{user} disse a {user1}: "{user2} é quem mais se aproxima da verdade."
{user} disse a {user1}: "{user2} tá sempre um passo à frente. Hoje não."
{user} disse a {user1}: "{user2} é a ameaça silenciosa."
{user} disse a {user1}: "Olha o tanto de gente que ouve {user2}. Tira."
{user} disse a {user1}: "{user2} não pode ver o sol de amanhã."
{user} disse a {user1}: "{user2} tem que sair, e tem que ser pela nossa mão."
{user} disse a {user1}: "Eu confio na gente. E a gente escolhe {user2}."
{user} disse a {user1}: "{user2} tá blindado(a) de dia. De noite não."
{user} disse a {user1}: "{user2} tá desconfiando da sua voz."
{user} disse a {user1}: "Se {user2} ficar, a mesa acerta um de nós."
{user} disse a {user1}: "{user2} é o(a) mais perigoso(a), fecha comigo."
{user} disse a {user1}: "Vamos cortar o mal pela raiz: {user2}."
{user} disse a {user1}: "{user2} tá na cola da gente."
{user} disse a {user1}: "{user2} tem o voto mais influente."
{user} disse a {user1}: "Eu escolhi {user2}. Me acompanha?"
{user} disse a {user1}: "{user2} vai virar o jogo se ficar."
{user} disse a {user1}: "Pensa no caos que vai ser sem {user2}."
{user} disse a {user1}: "{user2} tem o coração dos Fiéis."
{user} disse a {user1}: "{user2} vive dizendo que vai descobrir a torre."
{user} disse a {user1}: "{user2} é a melhor escolha, e a mais segura."
{user} disse a {user1}: "{user2} tá com escudo? Não. Então vai."
{user} disse a {user1}: "Eu quero {user2} fora hoje."
{user} disse a {user1}: "{user2} tá contando os votos contra nós."
{user} disse a {user1}: "{user2} faz o castelo pensar. Isso é perigoso."
{user} disse a {user1}: "Vamos de {user2} e depois a gente pensa no resto."
{user} disse a {user1}: "{user2} nunca vai desconfiar de si mesmo(a) como alvo."
{user} disse a {user1}: "{user2} é o(a) Fiel mais leal. Tirar dói neles."
{user} disse a {user1}: "Escolhe {user2}. É o movimento certo."
{user} disse a {user1}: "{user2} tá amigo(a) demais de quem desconfia de nós."
{user} disse a {user1}: "{user2} vai nos entregar. É questão de tempo."
{user} disse a {user1}: "{user2} tem o faro mais apurado."
{user} disse a {user1}: "Com {user2} fora, a mesa de amanhã é nossa."
{user} disse a {user1}: "{user2} é inteligente demais pra ficar."
{user} disse a {user1}: "Eu voto {user2} e peço seu voto também."
{user} disse a {user1}: "{user2} tá costurando uma aliança contra nós."
{user} disse a {user1}: "{user2} é o nome que protege a gente."
{user} disse a {user1}: "{user2} tá chegando no seu nome, cuidado."
{user} disse a {user1}: "Não dá pra arriscar: {user2}."
{user} disse a {user1}: "{user2} tem o respeito de todos. Isso tem que acabar."
{user} disse a {user1}: "{user2} já acusou um de nós. É hoje."
{user} disse a {user1}: "{user2} é o(a) mais difícil de enganar."
{user} disse a {user1}: "Vamos de {user2} e amanhã eu choro por nós dois."
{user} disse a {user1}: "{user2} tá prestes a virar a mesa."
{user} disse a {user1}: "{user2} tem que sumir enquanto dá."
{user} disse a {user1}: "Eu vejo {user2} como nossa maior ameaça."
{user} disse a {user1}: "{user2} tá muito próximo(a) de quem desconfia."
{user} disse a {user1}: "{user2} vai lembrar de alguma coisa. Melhor não."
{user} disse a {user1}: "{user2} é o(a) Fiel que eu mais temo."
{user} disse a {user1}: "Confia no meu instinto: {user2}."
{user} disse a {user1}: "{user2} é peça de ouro deles. A gente leva."
{user} disse a {user1}: "{user2} tá sozinho(a) hoje. Oportunidade."
{user} disse a {user1}: "{user2} tem que ir. E tem que ser agora."
{user} disse a {user1}: "Se não for {user2}, me explica quem seria melhor."
{user} disse a {user1}: "{user2} tá desconfiando de todos os lados."
{user} disse a {user1}: "{user2} tá liderando uma caçada. A caça somos nós."
{user} disse a {user1}: "{user2} tem que sair do tabuleiro."
{user} disse a {user1}: "{user2} tem charme de vencedor(a). Corta."
{user} disse a {user1}: "Eu quero {user2}, e quero seu voto junto."
{user} disse a {user1}: "{user2} tá perto de adivinhar."
{user} disse a {user1}: "{user2} é o próximo, e o castelo vai tremer."
{user} disse a {user1}: "{user2} tá blindando os outros. Tira o escudo humano."
{user} disse a {user1}: "Eu vejo {user2} como o perigo número um."
{user} disse a {user1}: "{user2} tá de olho em você, parceiro(a)."
{user} disse a {user1}: "{user2}. Sem mais palavras."
{user} disse a {user1}: "{user2} merece ser nossa próxima surpresa."
{user} disse a {user1}: "{user2} tem que ser o susto de amanhã."
{user} disse a {user1}: "A gente tira {user2} e fica mais leve."
{user} disse a {user1}: "{user2} vai votar em você amanhã. Eu sinto."
{user} disse a {user1}: "{user2} é a ameaça que ninguém enxerga ainda."
{user} disse a {user1}: "Vamos de {user2} e seguimos invisíveis."
{user} disse a {user1}: "{user2} é o cabeça da aliança mais forte."
{user} disse a {user1}: "Se a gente não tirar {user2}, {user2} tira a gente."
{user} disse a {user1}: "{user2} já tá juntando as peças."
{user} disse a {user1}: "Escreve {user2}. Eu garanto que é o certo."
{user} disse a {user1}: "{user2} é o(a) mais querido(a) do castelo. Vai doer neles."
{user} disse a {user1}: "{user2} tá tranquilo(a) demais. Vamos tirar essa paz."
{user} disse a {user1}: "{user2} não pode passar desta noite."
{user} disse a {user1}: "{user2} fala comigo como quem sabe."
{user} disse a {user1}: "{user2} é o(a) Fiel que vai fazer diferença. Tira."
{user} disse a {user1}: "Eu não vejo outro nome além de {user2}."
{user} disse a {user1}: "{user2} tá nos farejando. Chega."
{user} disse a {user1}: "{user2} é a escolha que ninguém vai prever."
{user} disse a {user1}: "Vamos de {user2}, e eu assumo a culpa se der errado."
{user} disse a {user1}: "{user2} é o obstáculo entre nós e o prêmio."
{user} disse a {user1}: "{user2} tá se aproximando de quem sabe demais."
{user} disse a {user1}: "{user2} tem que ser o nome de hoje."
{user} disse a {user1}: "{user2} tá me tirando o sono. Resolve pra mim."
{user} disse a {user1}: "Com {user2} vivo(a), eu não vou até a final."
{user} disse a {user1}: "{user2} é a próxima estrela a se apagar."
{user} disse a {user1}: "{user2} vai confundir o castelo quando sumir."
{user} disse a {user1}: "Eu fecho em {user2}. Fecha comigo?"
{user} disse a {user1}: "{user2} tem a cabeça no lugar. Perigo."
{user} disse a {user1}: "{user2} tá sem aliados fortes. Momento perfeito."
{user} disse a {user1}: "{user2} já disse que sabe quem somos. Blefe ou não, vai."
{user} disse a {user1}: "{user2} é o vento contra. A gente fecha a janela."
{user} disse a {user1}: "Vamos de {user2} e deixa o resto comigo."
{user} disse a {user1}: "{user2} não pode chegar à mesa final."
{user} disse a {user1}: "{user2} tá ficando forte demais nas missões."
{user} disse a {user1}: "{user2} é leal e inteligente. Combinação mortal pra nós."
{user} disse a {user1}: "{user2} tem que morrer pra gente viver."
{user} disse a {user1}: "Eu escolho {user2} e durmo tranquilo(a)."
{user} disse a {user1}: "{user2} tá chegando no meu nome. Me ajuda."
{user} disse a {user1}: "Não tem vítima melhor que {user2} hoje."
{user} disse a {user1}: "{user2} faz os Fiéis pensarem. Chega de pensar."
{user} disse a {user1}: "{user2} tem que ser o(a) próximo(a) retrato na parede."
{user} disse a {user1}: "{user2}, e depois a gente conversa."
{user} disse a {user1}: "{user2} tá se tornando o(a) líder deles."
{user} disse a {user1}: "Vamos de {user2}. Frio e rápido."
{user} disse a {user1}: "{user2} tem que ir. Eu sinto no estômago."
{user} disse a {user1}: "{user2} é o risco que não dá pra correr."
{user} disse a {user1}: "Eu voto {user2} e você me acompanha, combinado?"
{user} disse a {user1}: "{user2} tá lendo o jogo bem demais."
{user} disse a {user1}: "Meu nome é {user2}. Sem discussão."
{user} disse a {user1}: "Se {user2} ficar, a gente cai amanhã."
{user} disse a {user1}: "{user2} é querido(a) demais. Perigoso."
{user} disse a {user1}: "Eu quero {user2}. Hoje à noite."
{user} disse a {user1}: "{user2} é o cérebro dos Fiéis. Corta."
{user} disse a {user1}: "Vamos de {user2}. Ninguém vai suspeitar da gente."
{user} disse a {user1}: "{user2} me olhou torto na mesa. Acabou."
{user} disse a {user1}: "Tira {user2} e a mesa fica perdida."
{user} disse a {user1}: "{user2} tá juntando aliados. Hora de parar."
{user} disse a {user1}: "Proponho {user2}. Seguro e útil."
{user} disse a {user1}: "{user2}. E dorme tranquilo(a)."
{user} disse a {user1}: "Assina comigo: {user2}."
{user} disse a {user1}: "Sem {user2}, os Fiéis perdem o rumo."
{user} disse a {user1}: "{user2} me acusou. Agora é a vez dele(a)."
{user} disse a {user1}: "{user2} tá desconfiando de você. Resolvo isso."
{user} disse a {user1}, frio(a): "{user2}. Não tem outro."
`);

export const SAY_TOWER_SPARE = lines(`
{user} pediu a {user1}: "Deixa {user2} vivo(a) mais uma noite. É útil."
{user} disse a {user1}: "Não mata {user2}. {user2} desvia a atenção de nós."
{user} disse a {user1}: "{user2} é nosso escudo. Poupa."
{user} disse a {user1}: "Se {user2} morrer, vão olhar pra mim."
{user} disse a {user1}: "{user2} tá sendo acusado(a). Deixa a mesa fazer o serviço."
{user} disse a {user1}: "Poupa {user2}. Ainda preciso dele(a)."
{user} disse a {user1}: "{user2} confia em mim. Isso vale ouro."
{user} disse a {user1}: "Matar {user2} agora é burrice."
{user} disse a {user1}: "{user2} vai ser banido(a) sozinho(a). Espera."
{user} disse a {user1}: "Deixa {user2} pra depois."
{user} disse a {user1}: "{user2} tá confuso(a) e confunde os outros. Ótimo pra nós."
{user} disse a {user1}: "{user2} é inofensivo(a). Tem alvo melhor."
{user} disse a {user1}: "Se {user2} sumir, a mesa vai me culpar."
{user} disse a {user1}: "{user2} vota errado sempre. Deixa votar."
{user} disse a {user1}: "Eu pedi pra poupar {user2}. Confia."
{user} disse a {user1}: "{user2} é peça útil no nosso tabuleiro."
{user} disse a {user1}: "Não gasta a noite com {user2}."
{user} disse a {user1}: "{user2} me defende na mesa. Preciso disso."
{user} disse a {user1}: "{user2} pode ser recrutado(a) depois."
{user} disse a {user1}: "Matar {user2} ia parecer vingança minha."
{user} disse a {user1}: "{user2} tá com escudo, aposto. Perde a noite."
{user} disse a {user1}: "Deixa {user2} viver. Vai ser nosso bode expiatório."
{user} disse a {user1}: "{user2} tá do nosso lado sem saber."
{user} disse a {user1}: "Poupa {user2}, eu te devo uma."
{user} disse a {user1}: "{user2} é o voto que a gente controla."
{user} disse a {user1}: "Sem {user2}, fico sem álibi."
{user} disse a {user1}: "{user2} tá na mira da mesa. Deixa eles errarem."
{user} disse a {user1}: "{user2} fala demais e atrapalha os Fiéis. Deixa."
{user} disse a {user1}: "{user2} não ameaça ninguém. Escolhe outro."
{user} disse a {user1}: "Me faz esse favor: não {user2} hoje."
{user} disse a {user1}: "{user2} desconfia das pessoas certas... erradas pra eles."
{user} disse a {user1}: "Se {user2} morrer, o castelo se une. Não queremos isso."
{user} disse a {user1}: "{user2} é o caos que precisamos lá embaixo."
{user} disse a {user1}: "Deixa {user2} viver mais um dia e observa."
{user} disse a {user1}: "{user2} me conta tudo. É nossa fonte."
{user} disse a {user1}: "Poupa {user2}. Eu cuido disso na mesa."
{user} disse a {user1}: "{user2} não é ameaça. É distração."
{user} disse a {user1}: "Matar {user2} é desperdício de noite."
{user} disse a {user1}: "{user2} vai sair na mesa de amanhã. Anota."
{user} disse a {user1}: "Eu gosto de {user2}. Me deixa ter isso."
{user} disse a {user1}: "{user2} tá brigando com todo mundo. Deixa brigar."
{user} disse a {user1}: "{user2} é mais útil vivo(a)."
{user} disse a {user1}: "Se {user2} ficar, os Fiéis se dividem."
{user} disse a {user1}: "Poupa {user2}, confia no meu plano."
{user} disse a {user1}: "{user2} acusa as pessoas erradas. Mantém."
{user} disse a {user1}: "{user2} é o meu escudo humano. Não mexe."
{user} disse a {user1}: "Deixa {user2} fora da lista essa noite."
{user} disse a {user1}: "{user2} não merece. Ainda."
{user} disse a {user1}: "{user2} vai nos ajudar a derrubar alguém maior."
{user} disse a {user1}: "Se matar {user2}, vira mártir. Pior pra nós."
{user} disse a {user1}: "Tem gente mais perigosa que {user2}."
{user} disse a {user1}: "{user2} acha que eu sou Fiel. Deixa assim."
{user} disse a {user1}: "Não, {user2} não. Pensa em outro."
{user} disse a {user1}: "{user2} tá nas nossas mãos. Não precisa matar."
{user} disse a {user1}: "Poupa {user2} hoje e colhe amanhã."
{user} disse a {user1}: "{user2} é fraco(a) na mesa. Deixa pra eles."
{user} disse a {user1}: "Deixa {user2} vivo(a) pra confundir o castelo."
{user} disse a {user1}: "{user2} tá desconfiando de outro Fiel. Perfeito."
{user} disse a {user1}: "{user2} não viu nada. Relaxa."
{user} disse a {user1}: "{user2} tem potencial de Traidor(a). Pensa em recrutar."
{user} disse a {user1}: "Não mexe com {user2}. Tenho um plano."
{user} disse a {user1}: "{user2} vai votar com a gente amanhã."
{user} disse a {user1}: "Matar {user2} ia apontar pra minha aliança."
{user} disse a {user1}: "{user2} é o voto que me salva."
{user} disse a {user1}: "Deixa {user2} em paz. Tem noite pra isso."
{user} disse a {user1}: "Poupa {user2} por mim, parceiro(a)."
{user} disse a {user1}: "{user2} tem escudo? Pode ter. Não arrisca."
{user} disse a {user1}: "{user2} não é o problema. O problema é outro."
{user} disse a {user1}: "{user2} tá lutando contra a pessoa certa pra nós."
{user} disse a {user1}: "Se {user2} ficar, a gente ganha tempo."
{user} disse a {user1}: "{user2} está acusando um Fiel forte. Deixa."
{user} disse a {user1}: "{user2} é a nossa cortina de fumaça."
{user} disse a {user1}: "Não, deixa {user2}. Escolhe outro alvo."
{user} disse a {user1}: "{user2} tá do meu lado na mesa."
{user} disse a {user1}: "{user2} não merece nossa noite."
{user} disse a {user1}: "Eu preciso de {user2} até a próxima mesa."
{user} disse a {user1}: "{user2} tá sendo perseguido(a) lá embaixo. Deixa a mesa agir."
{user} disse a {user1}: "Poupa {user2}. É a jogada mais esperta."
{user} disse a {user1}: "{user2} pode nos servir de álibi."
{user} disse a {user1}: "{user2} tá prestes a acusar outro Fiel. Espera."
{user} disse a {user1}: "Matar {user2} ia unir a aliança dele(a) contra nós."
{user} disse a {user1}: "{user2} é inofensivo(a) e distraído(a). Deixa."
{user} disse a {user1}: "Deixa {user2}. Eu sinto que é útil."
{user} disse a {user1}: "{user2} é o voto que nunca acerta. Precisamos disso."
{user} disse a {user1}: "Poupa {user2}, depois você me agradece."
{user} disse a {user1}: "{user2} tá sem força nenhuma. Não precisa."
{user} disse a {user1}: "{user2} é minha carta na manga."
{user} disse a {user1}: "{user2} vai cair sozinho(a). Espera."
{user} disse a {user1}: "Não gasta o golpe em {user2}."
{user} disse a {user1}: "{user2} tá confiando em nós dois. Não quebra isso."
{user} disse a {user1}: "Deixa {user2} viver e fica de olho."
{user} disse a {user1}: "{user2} tá brigando com o(a) Fiel mais forte. Ótimo."
{user} disse a {user1}: "Matar {user2} seria óbvio demais."
{user} disse a {user1}: "Todo mundo espera que {user2} morra. Surpreende."
{user} disse a {user1}: "{user2} não, por favor."
{user} disse a {user1}: "{user2} tá sendo o nosso para-raios."
{user} disse a {user1}: "Poupa {user2} e a mesa vai se destruir."
{user} disse a {user1}: "{user2} ainda não fez nada contra nós."
{user} disse a {user1}: "{user2} é peça que eu movo na mesa."
{user} disse a {user1}: "Deixa {user2} pra quando o jogo apertar."
{user} disse a {user1}: "{user2} é mais perigoso(a) morto(a). Vira herói(heroína)."
{user} disse a {user1}: "Vamos poupar {user2} e mirar em quem pensa."
{user} disse a {user1}: "{user2} tá distraído(a) com outra briga."
{user} disse a {user1}: "Não mata {user2}, eu já tenho ele(a) no bolso."
{user} disse a {user1}: "{user2} vota onde eu mando. Não tira."
{user} disse a {user1}: "Se {user2} morrer, eu perco meu melhor escudo."
{user} disse a {user1}: "{user2} tá afundando sozinho(a) na mesa."
{user} disse a {user1}: "Poupa {user2}, confia em mim dessa vez."
{user} disse a {user1}: "{user2} é o tipo de Fiel que ajuda a gente sem querer."
{user} disse a {user1}: "{user2} não é o nome de hoje."
{user} disse a {user1}: "{user2} tá desconfiando de outro. Aproveita."
{user} disse a {user1}: "Deixa {user2}. Tem alvo mais urgente."
{user} disse a {user1}: "{user2} é o bobo(a) que a mesa vai culpar."
{user} disse a {user1}: "{user2} ia fazer o castelo desconfiar de mim se morresse."
{user} disse a {user1}: "Poupa {user2} e escolhe quem ameaça de verdade."
{user} disse a {user1}: "{user2} tá do nosso lado, só não sabe."
{user} disse a {user1}: "Deixa {user2} vivo(a). Ainda vai servir."
{user} disse a {user1}: "{user2} não merece a adaga hoje."
{user} disse a {user1}: "{user2} é inofensivo(a) como um gatinho."
{user} disse a {user1}: "Se poupar {user2}, eu te devo uma noite."
{user} disse a {user1}: "{user2} é a cara que a mesa odeia. Deixa lá."
{user} disse a {user1}: "Não, {user2} fica. Escolhe outro nome."
{user} disse a {user1}: "{user2} tá cego(a) pra nós. Excelente."
{user} disse a {user1}: "{user2} é a peça mais fraca. Deixa jogar."
{user} disse a {user1}: "Poupa {user2} e mata a desconfiança."
{user} disse a {user1}: "{user2} vai acusar o Fiel certo pra nós amanhã."
{user} disse a {user1}: "Deixa {user2} para o fim."
{user} disse a {user1}: "{user2} me protege, e eu protejo a gente."
{user} disse a {user1}: "{user2} tá sem aliados. Não vale a noite."
{user} disse a {user1}: "{user2} tá apontando pra um Fiel. Deixa apontar."
{user} disse a {user1}: "Poupa {user2}, que o jogo agradece."
{user} disse a {user1}: "{user2} é útil demais pra morrer agora."
{user} disse a {user1}: "Não mexe em {user2}, tá dando certo."
{user} disse a {user1}: "{user2} tá com medo e o medo dele(a) ajuda a gente."
{user} disse a {user1}: "Deixa {user2}. Se morrer, eu viro suspeito(a)."
{user} disse a {user1}: "{user2} tá sempre na mira da mesa. Mais fácil banir."
{user} disse a {user1}: "Poupa {user2}. Eu sei o que tô falando."
{user} disse a {user1}: "{user2} é o elo fraco deles. Deixa enfraquecer."
{user} disse a {user1}: "{user2} tá do meu lado. Não quebra isso."
{user} disse a {user1}: "Deixa {user2} em paz essa noite, parceiro(a)."
{user} disse a {user1}: "{user2} vai votar no Fiel certo. Certo pra nós."
{user} disse a {user1}: "Não, poupa {user2}. Pensa no longo prazo."
{user} disse a {user1}: "{user2} tá guardado pra final. Ninguém vota nele(a)."
{user} disse a {user1}: "Matar {user2} é o que eles esperam. Não faz."
{user} disse a {user1}: "{user2} não pensa. Deixa não pensar."
{user} disse a {user1}: "Poupa {user2} pra eu ter com quem jogar."
{user} disse a {user1}: "{user2} tem uma briga que nos favorece."
{user} disse a {user1}: "{user2} vale mais vivo(a)."
{user} disse a {user1}: "Deixa {user2}. Eu cuido dele(a) depois."
{user} disse a {user1}: "{user2} tá blindando a gente sem saber."
{user} disse a {user1}: "Não escreve {user2}. Escreve outro."
{user} disse a {user1}: "{user2} tá tão perdido(a) que ajuda a gente."
{user} disse a {user1}: "Poupa {user2}, e a mesa vai se enforcar."
{user} disse a {user1}: "{user2} é peça de troca. Guarda."
{user} disse a {user1}: "{user2} tá desviando os olhares de nós."
{user} disse a {user1}: "Deixa {user2} viver, é nosso para-choque."
{user} disse a {user1}: "{user2} não tem cabeça pra nos pegar."
{user} disse a {user1}: "Poupa {user2} e escolhe quem pensa demais."
{user} disse a {user1}: "{user2} é nossa desculpa perfeita na mesa."
{user} disse a {user1}: "Se {user2} ficar, o castelo continua perdido."
{user} disse a {user1}: "{user2} tá no nosso bolso."
{user} disse a {user1}: "Deixa {user2}. Confia no plano."
{user} disse a {user1}: "{user2} tá com a atenção toda em outro."
{user} disse a {user1}: "Não vale a pena {user2} hoje."
{user} disse a {user1}: "{user2} é o voto fácil de manipular."
{user} disse a {user1}: "Poupa {user2}. A gente vai precisar."
{user} disse a {user1}: "{user2} não sabe de nada. Deixa assim."
{user} disse a {user1}: "Deixa {user2} viver pra gente ter mais um dia de sossego."
{user} disse a {user1}: "{user2} é a última ameaça da lista, não a primeira."
{user} disse a {user1}: "Não tira {user2}, tira quem pensa."
{user} disse a {user1}: "{user2} tá fora do radar. Mantém fora."
{user} disse a {user1}: "Poupa {user2} e ganha a confiança dele(a)."
{user} disse a {user1}: "{user2} é um(a) Fiel sem força. Não gasta."
{user} disse a {user1}: "Deixa {user2}, e vê o circo pegar fogo."
{user} disse a {user1}: "{user2} é inútil pros Fiéis. Útil pra nós."
{user} disse a {user1}: "Não, {user2} fica. Isso eu não negocio."
{user} disse a {user1}: "{user2} tá confiando em você. Usa isso."
{user} disse a {user1}: "Poupa {user2} e mira na cabeça deles."
{user} disse a {user1}: "{user2} vai ficar pra mesa decidir."
{user} disse a {user1}: "Deixa {user2}. Amanhã a gente revê."
{user} disse a {user1}: "{user2} é o voto que a gente vai precisar na final."
{user} disse a {user1}: "Não mata {user2}. Não agora."
{user} disse a {user1}: "{user2} é o nosso seguro."
{user} disse a {user1}: "Poupa {user2}. Eu insisto."
{user} disse a {user1}: "{user2} é o Fiel que os Fiéis não ouvem."
{user} disse a {user1}: "Deixa {user2} em paz e escolhe o perigo real."
{user} disse a {user1}: "{user2} é leal a mim. Isso vale muito."
{user} disse a {user1}: "Não gasta a adaga com {user2}."
{user} disse a {user1}: "{user2} tá distraído(a). Deixa distraído(a)."
{user} disse a {user1}: "Poupa {user2}, e depois a gente conversa."
{user} disse a {user1}: "{user2} tá mais perdido(a) que vela no vento."
{user} disse a {user1}: "Deixa {user2}. Tem gente que sabe mais."
{user} disse a {user1}: "{user2} não precisa morrer pra gente ganhar."
{user} disse a {user1}: "Poupa {user2} por hoje. Só por hoje."
{user} disse a {user1}: "Mata {user2} e a gente perde um bom disfarce."
{user} disse a {user1}: "{user2} tá tirando votos de nós. Deixa."
{user} disse a {user1}: "{user2} é inofensivo(a). Guarda pra depois."
{user} disse a {user1}: "Poupa {user2}. Tô usando ele(a)."
{user} disse a {user1}: "{user2} vota onde eu quero. Deixa vivo(a)."
{user} disse a {user1}: "Ainda não. {user2} tem utilidade."
{user} disse a {user1}: "{user2} tá acusando o(a) inocente certo(a). Deixa."
{user} disse a {user1}: "Guarda {user2} pra final. Fácil de vencer."
{user} disse a {user1}: "{user2} fica. Confia."
`);

export const SAY_TOWER_RECRUIT = lines(`
{user} sugeriu a {user1}: "E se a gente trouxer {user2} pro nosso lado?"
{user} disse a {user1}: "{user2} daria um(a) ótimo(a) Traidor(a)."
{user} disse a {user1}: "Eu acho que {user2} aceitaria a carta."
{user} disse a {user1}: "{user2} é ambicioso(a). Vai querer o prêmio."
{user} disse a {user1}: "Recrutar {user2} vale mais que matar."
{user} disse a {user1}: "{user2} mente bem. Ia ser útil aqui em cima."
{user} disse a {user1}: "Que tal mandar a carta pra {user2}?"
{user} disse a {user1}: "{user2} tá desiludido(a) com os Fiéis."
{user} disse a {user1}: "{user2} confia em mim. Aceitaria."
{user} disse a {user1}: "{user2} tem estômago pra isso."
{user} disse a {user1}: "Com {user2} aqui, a gente ganha fácil."
{user} disse a {user1}: "{user2} é frio(a) o bastante pra torre."
{user} disse a {user1}: "Pensa em {user2} de capa. Combina."
{user} disse a {user1}: "{user2} quer ganhar a qualquer custo. Perfeito."
{user} disse a {user1}: "{user2} tá sozinho(a). Uma carta muda tudo."
{user} disse a {user1}: "{user2} ia amar o poder da torre."
{user} disse a {user1}: "Eu vejo {user2} conosco."
{user} disse a {user1}: "{user2} é leal a quem paga mais."
{user} disse a {user1}: "{user2} não aguenta mais ser suspeito(a). Ia topar."
{user} disse a {user1}: "Recruta {user2} e o castelo nunca vai desconfiar."
{user} disse a {user1}: "{user2} tem cara de Traidor(a) enrustido(a)."
{user} disse a {user1}: "{user2} já age como a gente."
{user} disse a {user1}: "Uma carta pra {user2}, que tal?"
{user} disse a {user1}: "{user2} seria o(a) Traidor(a) que ninguém espera."
{user} disse a {user1}: "{user2} é esperto(a). Melhor com a gente que contra."
{user} disse a {user1}: "{user2} ia aceitar na hora, eu sinto."
{user} disse a {user1}: "Se trouxermos {user2}, os Fiéis perdem um líder."
{user} disse a {user1}: "{user2} é o reforço que a gente precisa."
{user} disse a {user1}: "{user2} sabe guardar segredo. Eu testei."
{user} disse a {user1}: "Pensa bem: {user2} na torre seria genial."
{user} disse a {user1}: "{user2} tá com raiva dos Fiéis. Usa isso."
{user} disse a {user1}: "{user2} tem ambição de sobra."
{user} disse a {user1}: "Vamos recrutar {user2} antes que alguém chegue nele(a)."
{user} disse a {user1}: "{user2} é o tipo que vira a casaca fácil."
{user} disse a {user1}: "{user2} é bom(boa) ator/atriz. Ia arrasar aqui."
{user} disse a {user1}: "Com {user2} do nosso lado, ninguém nos pega."
{user} disse a {user1}: "{user2} quer o prêmio mais que tudo."
{user} disse a {user1}: "{user2} nunca desconfiou de nós. Ia confiar."
{user} disse a {user1}: "Manda a carta pra {user2} e vê o que acontece."
{user} disse a {user1}: "{user2} tem o jeito certo pra torre."
{user} disse a {user1}: "Eu apostaria que {user2} aceita."
{user} disse a {user1}: "{user2} é pragmático(a). Vai entender a proposta."
{user} disse a {user1}: "{user2} não tem amigos de verdade lá embaixo."
{user} disse a {user1}: "Recrutar {user2} tira um voto deles e dá pra nós."
{user} disse a {user1}: "{user2} é leal a mim. Ia me seguir até aqui."
{user} disse a {user1}: "{user2} tá cansado(a) de perder. Oferece a vitória."
{user} disse a {user1}: "{user2} tem sangue frio. Precisamos disso."
{user} disse a {user1}: "Pensa em {user2}: discreto(a), esperto(a), ambicioso(a)."
{user} disse a {user1}: "{user2} ia ser um(a) Traidor(a) melhor que muita gente."
{user} disse a {user1}: "{user2} tá desconfiado(a) de todos. Menos de nós."
{user} disse a {user1}: "Vamos dar uma escolha a {user2}."
{user} disse a {user1}: "{user2} tem potencial. Muito potencial."
{user} disse a {user1}: "{user2} é o próximo Traidor(a), se a gente quiser."
{user} disse a {user1}: "{user2} faria qualquer coisa pra ficar no jogo."
{user} disse a {user1}: "Uma carta lacrada pra {user2}. Eu escrevo."
{user} disse a {user1}: "{user2} é o curinga que falta."
{user} disse a {user1}: "{user2} não tem medo de nada. Serve."
{user} disse a {user1}: "{user2} ia saber mentir na mesa."
{user} disse a {user1}: "Recrutamos {user2} e o jogo é nosso."
{user} disse a {user1}: "{user2} já disse que faria de tudo pelo prêmio."
{user} disse a {user1}: "{user2} tá solitário(a). A gente oferece companhia."
{user} disse a {user1}: "{user2} tem inveja de quem manda. Oferece o poder."
{user} disse a {user1}: "Com {user2}, a gente tem olhos em todo lugar."
{user} disse a {user1}: "{user2} é influente. Imagina influente do nosso lado."
{user} disse a {user1}: "{user2} tá magoado(a) com a aliança dele(a). Hora certa."
{user} disse a {user1}: "Eu confio que {user2} aceitaria."
{user} disse a {user1}: "{user2} tem um lado sombrio. Eu vi."
{user} disse a {user1}: "{user2} é a pessoa certa pra carta."
{user} disse a {user1}: "Vamos convidar {user2}. Pior que dá certo."
{user} disse a {user1}: "{user2} ama um jogo sujo."
{user} disse a {user1}: "{user2} seria nosso melhor recrutamento."
{user} disse a {user1}: "Pensa no susto dos Fiéis se {user2} virar."
{user} disse a {user1}: "{user2} tem tudo pra ser da torre."
{user} disse a {user1}: "{user2} não tem lealdade a ninguém lá embaixo."
{user} disse a {user1}: "Recrutar {user2} é jogada de mestre."
{user} disse a {user1}: "{user2} tá desesperado(a) por proteção."
{user} disse a {user1}: "{user2} guarda segredo como cofre."
{user} disse a {user1}: "{user2} ia amar o poder de escolher."
{user} disse a {user1}: "Manda o convite pra {user2}, confia."
{user} disse a {user1}: "{user2} é frio(a) na mesa. Perfeito pra nós."
{user} disse a {user1}: "{user2} é leal ao próprio bolso."
{user} disse a {user1}: "{user2} ia topar pra não morrer."
{user} disse a {user1}: "Vamos de carta pra {user2} e ver a reação."
{user} disse a {user1}: "{user2} é a surpresa que vai enlouquecer o castelo."
{user} disse a {user1}: "{user2} tem o dom da mentira."
{user} disse a {user1}: "Com {user2} aqui, a gente dobra a força."
{user} disse a {user1}: "{user2} tá sem aliados. Nós seríamos os aliados."
{user} disse a {user1}: "{user2} é o candidato perfeito."
{user} disse a {user1}: "Eu vejo {user2} de capa preta sorrindo."
{user} disse a {user1}: "{user2} não ia recusar o prêmio."
{user} disse a {user1}: "{user2} tá cansado(a) de ser alvo. Oferece o outro lado."
{user} disse a {user1}: "Recruta {user2}. Eu garanto."
{user} disse a {user1}: "{user2} tem a frieza que falta aqui."
{user} disse a {user1}: "{user2} já pensou em trair, tenho certeza."
{user} disse a {user1}: "{user2} seria um(a) Traidor(a) invisível."
{user} disse a {user1}: "Vamos mandar a carta pra {user2} hoje."
{user} disse a {user1}: "{user2} tem ambição e pouco escrúpulo."
{user} disse a {user1}: "Se {user2} aceitar, a gente vence."
{user} disse a {user1}: "{user2} é inteligente o bastante pra aceitar."
{user} disse a {user1}: "{user2} tá brigado(a) com os Fiéis. Aproveita."
{user} disse a {user1}: "{user2} tem cara de quem guarda um lado escuro."
{user} disse a {user1}: "{user2} ia ser nosso trunfo."
{user} disse a {user1}: "Chama {user2} pra torre. Ia ser lindo."
{user} disse a {user1}: "{user2} é pragmático(a), vai querer sobreviver."
{user} disse a {user1}: "{user2} sabe jogar dos dois lados."
{user} disse a {user1}: "Com {user2}, a mesa não nos pega nunca."
{user} disse a {user1}: "{user2} é leal a quem protege. A gente protege."
{user} disse a {user1}: "{user2} ia gostar do poder, eu sei."
{user} disse a {user1}: "Recrutar {user2} desmonta a aliança dele(a)."
{user} disse a {user1}: "{user2} já age em segredo. Só falta a capa."
{user} disse a {user1}: "Vamos de convite pra {user2}. Sem ultimato."
{user} disse a {user1}: "{user2} é mentiroso(a) nato(a). Perfeito."
{user} disse a {user1}: "{user2} tá procurando um lado. Oferece o nosso."
{user} disse a {user1}: "{user2} tem fome de vitória."
{user} disse a {user1}: "Uma carta pra {user2} e a gente vira o jogo."
{user} disse a {user1}: "{user2} ia aceitar sem pestanejar."
{user} disse a {user1}: "{user2} é bom(boa) em fingir. Precisamos disso."
{user} disse a {user1}: "Pensa no {user2} votando com a gente."
{user} disse a {user1}: "{user2} tem o perfil exato."
{user} disse a {user1}: "Se não recrutarmos {user2}, alguém vai usar {user2} contra nós."
{user} disse a {user1}: "{user2} não confia em ninguém. Vai confiar no poder."
{user} disse a {user1}: "{user2} é a peça que falta pra fechar o jogo."
{user} disse a {user1}: "Recrutar {user2} é arriscado, mas vale."
{user} disse a {user1}: "{user2} tá desiludido(a). Hora de oferecer um sonho."
{user} disse a {user1}: "{user2} tem coragem. Coragem serve aqui."
{user} disse a {user1}: "Manda a carta, e eu sei que {user2} aceita."
{user} disse a {user1}: "{user2} ia ser um(a) aliado(a) poderoso(a)."
{user} disse a {user1}: "{user2} é traiçoeiro(a) sem nem saber."
{user} disse a {user1}: "{user2} tem o jeito calculista que a gente gosta."
{user} disse a {user1}: "Vamos transformar {user2} em um(a) dos nossos."
{user} disse a {user1}: "{user2} é quem eu escolheria como parceiro(a)."
{user} disse a {user1}: "{user2} tá sofrendo lá embaixo. Aqui é melhor."
{user} disse a {user1}: "{user2} é ambicioso(a) e esperto(a). Recruta."
{user} disse a {user1}: "Uma carta pra {user2} e a gente dorme tranquilo."
{user} disse a {user1}: "{user2} é o Fiel mais fácil de converter."
{user} disse a {user1}: "{user2} ia amar ser Traidor(a). Olha o jeito."
{user} disse a {user1}: "Recruta {user2} antes que a mesa tire."
{user} disse a {user1}: "{user2} tem um coração frio escondido."
{user} disse a {user1}: "{user2} já me falou que queria estar do lado vencedor."
{user} disse a {user1}: "Convidar {user2} confunde todo mundo."
{user} disse a {user1}: "{user2} é leal a mim. Vai me seguir até a capa."
{user} disse a {user1}: "{user2} tá pronto(a) pra mudar de lado."
{user} disse a {user1}: "{user2} é ótimo(a) em esconder emoções."
{user} disse a {user1}: "Uma carta pra {user2}. Eu escrevo com carinho."
{user} disse a {user1}: "{user2} tem o que é preciso."
{user} disse a {user1}: "{user2} ia jogar muito bem aqui em cima."
{user} disse a {user1}: "Recruta {user2}: menos um Fiel, mais um de nós."
{user} disse a {user1}: "{user2} tem perfil de vencedor(a). Que vença com a gente."
{user} disse a {user1}: "{user2} tá sem rumo. Oferece um."
{user} disse a {user1}: "{user2} é o tipo que aceita e ainda agradece."
{user} disse a {user1}: "{user2} seria nosso(a) espião(ã) perfeito(a)."
{user} disse a {user1}: "Manda o convite pra {user2}, mas com jeito."
{user} disse a {user1}: "{user2} já tem a malícia, só falta a oportunidade."
{user} disse a {user1}: "{user2} ia amar enganar a mesa."
{user} disse a {user1}: "Com {user2} aqui, eu durmo em paz."
{user} disse a {user1}: "{user2} é influente e frio(a). Combinação ideal."
{user} disse a {user1}: "{user2} merece a carta, confia."
{user} disse a {user1}: "Recrutar {user2} é o golpe que ninguém espera."
{user} disse a {user1}: "{user2} não tem medo de sujar as mãos."
{user} disse a {user1}: "{user2} é leal enquanto ganha. A gente garante que ganhe."
{user} disse a {user1}: "Vamos testar {user2} com uma carta?"
{user} disse a {user1}: "{user2} daria um(a) Traidor(a) de respeito."
{user} disse a {user1}: "{user2} tá à procura de proteção. A gente dá."
{user} disse a {user1}: "{user2} tem a mentira na ponta da língua."
{user} disse a {user1}: "Recruta {user2}. Eu cuido da conversa."
{user} disse a {user1}: "{user2} é a melhor aposta da noite."
{user} disse a {user1}: "{user2} é esperto(a) demais pra ficar do lado perdedor."
{user} disse a {user1}: "{user2} vai aceitar pra não virar alvo."
{user} disse a {user1}: "Uma carta pra {user2} vale mais que uma morte."
{user} disse a {user1}: "{user2} tem o olhar de quem já traiu antes."
{user} disse a {user1}: "Com {user2}, a gente controla a mesa."
{user} disse a {user1}: "{user2} tá pedindo, sem saber, pra ser recrutado(a)."
{user} disse a {user1}: "Recrutar {user2} tira o chão dos Fiéis."
{user} disse a {user1}: "{user2} tem o jeitinho de Traidor(a)."
{user} disse a {user1}: "{user2} é a escolha certa pra carta."
{user} disse a {user1}: "Eu imagino {user2} aqui e sorrio."
{user} disse a {user1}: "{user2} não ia recusar poder. Ninguém recusa."
{user} disse a {user1}: "Vamos chamar {user2} e mudar a história."
{user} disse a {user1}: "{user2} é leal ao que é certo pra ele(a). E o certo somos nós."
{user} disse a {user1}: "{user2} é ideal: quieto(a) e letal."
{user} disse a {user1}: "Recruta {user2}, e depois a gente escolhe a vítima juntos."
{user} disse a {user1}: "{user2} tá a um empurrão de virar."
{user} disse a {user1}: "{user2} merece estar aqui em cima com a gente."
{user} disse a {user1}: "Manda a carta pra {user2} hoje à noite."
{user} disse a {user1}: "{user2} tem estratégia. Vai entender o convite."
{user} disse a {user1}: "{user2} seria meu(minha) parceiro(a) preferido(a)."
{user} disse a {user1}: "Com {user2}, a torre fica completa."
{user} disse a {user1}: "{user2} ia saber o que fazer com a capa."
{user} disse a {user1}: "{user2}, aqui em cima, seria imbatível."
{user} disse a {user1}: "Recruta {user2} e observa a mágica."
{user} disse a {user1}: "{user2} é a pessoa certa, no momento certo."
{user} disse a {user1}: "{user2} sabe mentir. Seria útil."
{user} disse a {user1}: "Traz {user2}? Ninguém desconfia dele(a)."
{user} disse a {user1}: "{user2} faria qualquer coisa pra ganhar."
{user} disse a {user1}: "Com {user2} na torre, a gente fica mais forte."
{user} disse a {user1}: "{user2} tem sangue frio. Convida."
{user} disse a {user1}: "Aposto que {user2} aceita sem pensar."
{user} disse a {user1}: "{user2} é leal a quem o(a) escolhe."
{user} disse a {user1}: "Vamos dar a carta pra {user2}?"
{user} disse a {user1}: "{user2} já joga sujo. Só falta a capa."
{user} disse a {user1}: "Recruta {user2}. Ninguém olha pra ele(a)."
{user} disse a {user1}: "{user2} tá sozinho(a). Vai topar."
`);
