import { lines } from './lines';

/** Respostas: {user} = quem responde, {user1} = jogador. Divididas pelo humor de quem responde. */

export const REPLY_ACCUSE = {
  good: lines(`
{user} respirou fundo: "Eu entendo você, {user1}. Mas está errado(a)."
{user} riu, magoado(a): "De todo mundo, você?"
{user} ficou com os olhos cheios de lágrimas: "Eu achava que você me conhecia."
{user} segurou o braço de {user1}: "Olha pra mim. Eu sou Fiel."
{user} disse baixinho: "Isso doeu, {user1}. Doeu mesmo."
{user} balançou a cabeça: "Você tá com medo, eu sei. Mas não sou eu."
{user} sorriu triste: "Tudo bem. Amanhã você vai ver."
{user} disse a {user1}: "Eu te defendi ontem. Lembra?"
{user} suspirou: "Se eu sair, vocês perdem um Fiel."
{user} disse: "Eu não vou brigar com você, {user1}. Só tô triste."
{user} ficou em silêncio, depois disse: "Pensa melhor, por favor."
{user} disse a {user1}: "Eu confio em você mesmo agora. Isso diz algo."
{user} abraçou {user1}: "Tá tudo bem. Eu entendo o jogo."
{user} disse: "Eu ia dizer seu nome como meu aliado(a)..."
{user} disse: "Não esperava isso logo de você, {user1}."
{user} limpou uma lágrima: "Você vai se arrepender quando eu for embora."
{user} disse a {user1}: "Me pergunta o que quiser. Eu respondo tudo."
{user} disse: "Se é isso que você acha, eu respeito. Mas é mentira."
{user} olhou para {user1}: "Eu nunca faria mal a você."
{user} disse: "Você tá sendo usado(a), {user1}. Abre o olho."
{user} riu nervoso(a): "Eu? Eu mal sei guardar segredo!"
{user} disse: "Tá bom, {user1}. Mas depois me pede desculpa."
{user} disse a {user1}: "Eu te dou minha palavra: sou Fiel."
{user} disse: "Não precisa ser assim, {user1}."
{user} disse: "A gente é amigo(a). Amigo(a) pergunta antes de acusar."
{user} disse: "Quem colocou isso na sua cabeça, {user1}?"
{user} ficou sem reação: "Você tá falando sério?"
{user} disse: "Eu perdoo você. Mas não esquece que perdoei."
{user} disse a {user1}: "Eu queria que você confiasse em mim como eu confio em você."
{user} disse: "Se eu fosse Traidor(a), você já estaria morto(a), querido(a)."
{user} disse: "Tô magoado(a), mas vou provar que sou Fiel."
{user} respondeu calmo(a): "Não sou eu. E você sabe disso no fundo."
{user} disse: "Vou fingir que não ouvi, {user1}."
{user} disse: "Pode me acusar. Eu continuo gostando de você."
{user} disse: "Isso foi um tiro no pé, {user1}."
{user} disse: "Eu não tô com raiva. Tô decepcionado(a)."
{user} disse a {user1}: "Olha nos meus olhos e repete."
{user} disse: "Quando descobrirem a verdade, você vai me procurar."
{user} disse: "Eu chorei por cada Fiel que morreu. Você viu."
{user} sorriu: "Você é muito desconfiado(a). Eu gosto, mas errou."
{user} disse: "A gente precisa conversar, {user1}. Depois."
{user} disse: "Tá tudo bem, eu também desconfiaria de mim."
{user} disse: "Você tá cansado(a), {user1}. Dorme e pensa melhor."
{user} disse: "Não sou eu. Mas obrigado(a) por falar na minha cara."
{user} disse: "Eu prefiro ser acusado(a) por você do que pelas costas."
{user} disse: "Você ainda vai rir disso comigo."
{user} disse: "Eu respeito a sua dúvida. Não a sua conclusão."
{user} disse: "Pergunta pro meu coração, {user1}."
{user} disse a {user1}: "Não deixa te colocarem contra mim."
{user} disse: "Eu seria o(a) pior Traidor(a) da história."
{user} disse: "Isso é o que eles querem: a gente brigando."
{user} disse: "Eu não guardo mágoa. Mas você errou."
{user} disse: "Você vai ver, {user1}. O tempo mostra."
{user} disse: "Me abraça e esquece isso, vai."
{user} disse: "Eu tô do seu lado, mesmo você não estando do meu."
{user} disse: "Você me acusa e eu te protejo. Irônico, né?"
{user} disse: "Eu juro pela minha família que sou Fiel."
{user} disse: "Se isso te deixa mais tranquilo(a)... mas não sou eu."
{user} disse: "Tudo bem, {user1}. Eu entendo o medo."
{user} disse: "Eu aceito sua desconfiança. Não aceito seu voto."
{user} disse: "Você sabe que isso vai doer em nós dois."
{user} disse: "Eu não sou quem você procura, {user1}."
{user} disse: "Você tá olhando pro lado errado, meu bem."
{user} disse: "A gente é do mesmo time. Não esquece."
{user} disse: "Eu esperava isso de qualquer um. Menos de você."
{user} disse: "Pode vir, {user1}. Minha consciência tá limpa."
{user} disse: "Me dá um dia pra provar."
{user} disse: "Você me dói, {user1}, mas eu ainda confio."
{user} disse: "Não sou eu. Eu te garanto."
{user} disse: "Quando a verdade aparecer, eu te abraço."
{user} disse: "Eu não vou te odiar por isso."
{user} disse: "Olha, eu sei que parece, mas não é."
`),
  neutral: lines(`
{user} cruzou os braços: "Pode votar. Vai perder um voto."
{user} ficou em silêncio por um segundo longo demais antes de negar.
{user} respondeu: "Eu sou Fiel. Olha pros outros, {user1}."
{user} deu de ombros: "Acusação não é prova."
{user} disse: "Tá bom. E qual é o seu argumento?"
{user} disse: "Você tá chutando, {user1}."
{user} arqueou a sobrancelha: "Interessante. Continua."
{user} disse: "Eu não vou me defender de achismo."
{user} disse: "Traz prova, {user1}, e aí a gente conversa."
{user} disse: "Você tem direito de achar. Eu tenho direito de negar."
{user} disse: "Eu sou Fiel. Próximo assunto."
{user} disse: "Engraçado, eu ia dizer o mesmo de você."
{user} disse: "Não sou eu, e isso vai ficar claro."
{user} suspirou: "De novo isso?"
{user} disse: "Você vai ver no meu voto quem eu sou."
{user} respondeu seco(a): "Não."
{user} disse: "Tá errado(a), {user1}. Mas tudo bem."
{user} disse: "Eu não tenho nada a esconder. Pergunta o que quiser."
{user} disse: "Isso é o que você acha. Não é o que é."
{user} disse: "Eu entendo a lógica, mas a conclusão tá errada."
{user} disse: "Fiel. Cem por cento."
{user} disse: "Se eu fosse Traidor(a), não ia estar aqui te ouvindo."
{user} disse: "Pensa melhor antes de gastar seu voto."
{user} disse: "Você tá olhando pra árvore e não vê a floresta."
{user} riu curto: "Tá bom, {user1}."
{user} disse: "Eu vou provar. Não com palavras."
{user} disse: "Isso é teoria. Eu vivo de fatos."
{user} disse: "Não vou perder tempo discutindo."
{user} disse: "Pode anotar: não sou eu."
{user} disse: "Você tá sendo manipulado(a) e nem percebe."
{user} disse: "Bonita acusação. Pena que tá errada."
{user} olhou para o teto: "Que dia longo."
{user} disse: "Eu respeito, mas discordo."
{user} disse: "A mesa decide. Eu tô tranquilo(a)."
{user} disse: "Se eu sair, você vai ver que eu era Fiel."
{user} disse: "Você é livre pra votar em quem quiser."
{user} disse: "Não vou chorar. Não vou gritar. Não sou eu."
{user} disse: "Tem Traidor rindo dessa conversa agora."
{user} disse: "Eu esperava mais de você, {user1}."
{user} disse: "Beleza. Guarda esse voto, que você vai precisar."
{user} disse: "Seu faro tá desregulado hoje."
{user} disse: "Eu não sou o problema desse castelo."
{user} disse: "Pode acusar. Eu durmo tranquilo(a)."
{user} disse: "Você quer que eu diga o quê? Que sou? Não sou."
{user} disse: "Isso não muda nada pra mim."
{user} disse: "Eu vou continuar jogando limpo."
{user} disse: "Tudo bem desconfiar. Mas vota com a cabeça."
{user} disse: "Não sou eu. Simples assim."
{user} disse: "Você tá mirando no alvo errado, {user1}."
{user} disse: "Acho que você tá nervoso(a) e precisa de um culpado."
{user} ficou olhando para {user1} sem dizer nada.
{user} disse: "Eu vou lembrar disso na hora do voto."
{user} disse: "Faz o que você achar certo."
{user} disse: "Quem acusa sem prova se entrega."
{user} disse: "Tá, e se eu disser que desconfio de você também?"
{user} disse: "O que eu ganho me defendendo? Nada. Não sou eu."
{user} disse: "Você precisa de mais que um pressentimento."
{user} disse: "A verdade não precisa gritar."
{user} disse: "Eu sou Fiel, {user1}. Aceita ou não aceita."
{user} disse: "Não vou gastar saliva."
{user} disse: "Você já decidiu, né? Então nem adianta."
{user} disse: "Se a mesa acreditar em você, azar da mesa."
{user} disse: "Você erra e eu pago o preço. Justo, né?"
{user} disse: "Tô ouvindo. Mas não tô concordando."
{user} disse: "Isso tá mais pra fofoca que pra acusação."
{user} disse: "Um dia você me pede desculpas."
{user} disse: "Ok. Mais alguém quer me acusar hoje?"
{user} disse: "Não sou Traidor(a). E não sou burro(a) também."
`),
  bad: lines(`
{user} explodiu: "Você tá me acusando pra se esconder, {user1}!"
{user} bateu na mesa: "Isso vai ter volta, {user1}."
{user} apontou de volta: "Quem acusa primeiro é quem tem mais a esconder."
{user} jurou que é Fiel. Ninguém pareceu convencido.
{user} gritou: "Traidor(a) é você!"
{user} riu na cara de {user1}: "Patético."
{user} disse: "Você tá desesperado(a), {user1}. Dá pra ver."
{user} levantou: "Olha quem fala!"
{user} disse: "Eu vou lembrar de cada palavra, {user1}."
{user} disparou: "Você quer me tirar porque eu te incomodo."
{user} disse: "Pode falar o que quiser. Eu sei o que você é."
{user} disse: "Você tá com medo de mim. E devia."
{user} apontou o dedo: "Seu nome vai estar no meu voto hoje."
{user} disse: "Acusação de Traidor(a) desesperado(a)."
{user} disse: "Que teatro barato, {user1}."
{user} disse: "Você não me engana com essa pose de justiceiro(a)."
{user} disse: "Engraçado: você acusa e alguém morre depois."
{user} disse: "Você é a cobra, {user1}. Não eu."
{user} bufou: "Nem me dou ao trabalho."
{user} gritou: "Parem de ouvir {user1}!"
{user} disse: "Vai ter troco, pode esperar."
{user} disse: "Você tá jogando sujo e todo mundo tá vendo."
{user} disse: "Eu não vou cair nessa armadilha."
{user} disse: "Quem te mandou me acusar, {user1}? A torre?"
{user} disse: "Você é o(a) Traidor(a) mais óbvio(a) dessa mesa."
{user} disse: "Você vai pagar por isso, {user1}."
{user} jogou o guardanapo: "Chega! Não vou aceitar isso calado(a)."
{user} disse: "Eu sempre soube que você era falso(a)."
{user} disse: "Olha a cara de pau de {user1}!"
{user} disse: "Você tá me atacando porque eu desconfio de você."
{user} disse: "Hipocrisia tem limite, {user1}."
{user} disse: "Essa acusação tem cheiro de torre."
{user} disse: "Você acabou de assinar sua sentença."
{user} disse: "Não vem me dar lição de moral."
{user} gritou: "Mentira! Mentira!"
{user} disse: "Você é que devia explicar muita coisa."
{user} disse: "Quem planta, colhe, {user1}."
{user} disse: "Eu sei exatamente o seu jogo."
{user} disse: "Você é covarde. Acusa quem não se defende bem."
{user} disse: "Continua falando, {user1}. Continua."
{user} disse: "Você quer briga? Então teremos briga."
{user} riu: "Essa foi a coisa mais ridícula que ouvi hoje."
{user} disse: "Traidor(a) adora acusar Fiel. Né, {user1}?"
{user} disse: "Eu vou te desmascarar, pode esperar."
{user} disse: "Você é veneno, {user1}."
{user} disse: "Se eu cair, você cai junto."
{user} levantou a voz: "Não me aponta o dedo!"
{user} disse: "Você não sabe com quem tá mexendo."
{user} disse: "Isso é inveja pura, {user1}."
{user} disse: "Eu tô vendo seu plano, e ele vai dar errado."
{user} disse: "Você tá desviando atenção de si mesmo(a)."
{user} disse: "Guarda bem esse momento, {user1}."
{user} disse: "Traidor(a) que acusa Fiel... clássico."
{user} disse: "Não vou ficar quieto(a) enquanto você mente."
{user} disse: "Você acabou de ganhar um(a) inimigo(a)."
{user} disse: "Eu vou votar em você, {user1}. Hoje e sempre."
{user} disse: "Que audácia, {user1}!"
{user} disse: "Você é o problema desse castelo."
{user} disse: "Olha quem tá tremendo agora."
{user} disse: "Você quer me derrubar? Tenta."
{user} disse: "Tá com medo de perder o prêmio, {user1}?"
{user} disse: "Isso aqui é desespero, gente. Reparem."
{user} disse: "Não admito, {user1}!"
{user} disse: "Eu já sabia que você ia fazer isso."
{user} disse: "Você tá enterrando a si mesmo(a)."
{user} disse: "Continua cavando, {user1}."
{user} saiu da mesa, furioso(a).
{user} disse: "Você tem coragem de me olhar assim?"
{user} disse: "Isso foi um erro, {user1}. Um grande erro."
`),
};

/** Traidor acusado que mente bem responde calmo demais: é uma pista para quem presta atenção. */
export const CALM_DENIAL = lines(`
{user} respondeu com uma calma impressionante: "Tudo bem, {user1}. Eu entendo."
{user} nem piscou: "Se isso te deixa tranquilo(a), pode votar em mim."
{user} sorriu devagar: "Interessante você pensar isso, {user1}."
{user} disse, sereno(a): "Eu sei quem sou. Não preciso provar."
{user} ajeitou a gola: "Hum. Anotado."
{user} disse, sem alterar a voz: "Você tem direito de errar."
{user} sorriu: "Vamos ver o que a mesa acha."
{user} disse com doçura: "Coitado(a) de você, {user1}."
{user} disse calmamente: "Eu vou te perdoar quando você perceber o erro."
{user} tomou um gole de chá: "Continua."
{user} disse, tranquilo(a): "Pode ser que eu seja. Pode ser que não."
{user} respondeu frio(a): "Você me decepciona, {user1}."
{user} sorriu de canto: "É uma teoria. Bonita, até."
{user} disse suave: "Eu gosto de você mesmo assim."
{user} disse sem emoção: "Tá bom."
{user} apenas olhou para {user1} e sorriu.
{user} disse devagar: "Você está com medo. É normal."
{user} disse: "Não vou discutir. Vou só esperar."
{user} disse calmo(a): "O tempo vai responder por mim."
{user} disse, relaxado(a): "Tudo bem. Não é o primeiro."
{user} disse, com um meio sorriso: "Você é observador(a). Mas errou."
{user} disse: "Hm. E se eu dissesse que desconfio de você?"
{user} disse baixinho: "Você não precisa fazer isso, {user1}."
{user} disse sereno(a): "Pode votar. Eu durmo bem."
{user} apoiou o queixo na mão: "Continua, tá divertido."
{user} disse, sem mudar a expressão: "Eu sou Fiel."
{user} disse, calmo(a) demais: "Tanto faz, {user1}."
{user} disse: "Eu respeito. Não concordo, mas respeito."
{user} riu baixinho: "Ah, {user1}..."
{user} disse com voz macia: "Vamos conversar depois, só nós dois."
{user} disse: "Você tá tentando me provocar. Não vai conseguir."
{user} disse tranquilamente: "Eu confio no julgamento da mesa."
{user} olhou fundo em {user1}: "Tem certeza?"
{user} disse, sem pressa: "Pensa bem antes de votar."
{user} disse, suave: "Todo mundo erra, {user1}."
{user} disse: "Acho engraçado. Só isso."
{user} cruzou as mãos na mesa: "Estou ouvindo."
{user} disse, estranhamente calmo(a): "Que bom que você falou na minha cara."
{user} deu um sorriso gelado: "Tá certo."
{user} disse: "Você não é o(a) primeiro(a) a pensar isso. Nem o(a) último(a)."
{user} disse, sem se abalar: "Próxima pergunta."
{user} disse calmamente: "Eu entendo o jogo que você tá jogando."
{user} disse: "Não me ofendo fácil, {user1}."
{user} disse, tranquilo(a): "Pode ficar à vontade."
{user} disse: "É uma pena você pensar assim."
{user} disse com serenidade: "Vou deixar a verdade falar."
{user} disse: "Hum, entendi. Obrigado(a) pela sinceridade."
{user} disse, quase sorrindo: "Você é corajoso(a)."
{user} disse: "Isso não me tira o sono."
{user} ergueu a xícara: "À sua saúde, {user1}."
{user} disse com calma: "Eu esperava algo assim."
{user} disse: "Tá bom, tá bom. Mais alguém?"
{user} disse, sereno(a): "Eu não vou implorar."
{user} disse, com voz baixa: "Cuidado com o que você deseja."
{user} disse: "Não é a primeira vez que me julgam errado."
{user} disse com leveza: "Tudo isso por mim? Que honra."
{user} disse: "Você vai precisar de mais que isso, querido(a)."
{user} sorriu, paciente: "Eu te espero mudar de ideia."
{user} disse tranquilamente: "Se é isso que você quer, vá em frente."
{user} fez um gesto de 'tanto faz'.
{user} disse, calmo(a): "Eu sou transparente. Olha."
{user} disse, sem piscar: "Você tá enganado(a)."
{user} disse: "Isso é quase um elogio, sabia?"
{user} disse: "Não vou me explicar pra quem já decidiu."
{user} disse, com um sorriso polido: "Anotado, {user1}."
{user} disse suavemente: "Você vai sentir falta de mim."
{user} disse: "Tudo bem. Acontece."
{user} apenas assentiu, sem dizer nada.
{user} disse, sem emoção nenhuma: "Ok."
{user} disse: "Eu acho curioso quem você não acusa."
{user} disse, com calma: "Olha pros lados, {user1}. Não pra mim."
{user} disse: "Eu sou paciente. Muito paciente."
{user} disse, tranquilo(a): "Deixa o voto falar."
{user} disse com voz serena: "Você é mais inteligente que isso."
{user} disse: "Eu entendo, mas não aceito."
{user} disse: "Isso me faz rir por dentro."
{user} disse, relaxado(a): "Eu não sou quem você pensa."
{user} disse, sorrindo: "Você é fofo(a) quando fica bravo(a)."
{user} disse: "Não tenho pressa em provar nada."
{user} disse, sem alterar o tom: "Eu sigo sendo Fiel."
{user} disse com frieza: "Você que sabe."
{user} disse: "Hm. Você tem um ponto. Mas não é o meu."
{user} disse, calmo(a): "Vou respirar e deixar passar."
{user} disse: "Sua acusação é bem montada. Só não é verdade."
{user} disse, com sorriso sereno: "O castelo vai decidir."
{user} disse suave: "Eu não guardo rancor, {user1}."
{user} disse: "Você é bom(boa) nisso. Só errou o alvo."
{user} disse tranquilamente: "Não vou me justificar."
{user} disse: "Tá bom. Vou lembrar disso com carinho."
{user} passou manteiga no pão, sem pressa: "Pode continuar."
{user} disse, sem tirar os olhos do prato: "Uhum."
{user} disse com calma assustadora: "Você me acusa e eu te ofereço um abraço."
{user} disse, sorrindo: "Você é esperto(a). Mas não o suficiente."
{user} disse: "Eu vou te ajudar a achar o verdadeiro Traidor."
{user} disse, sereno(a): "Tenho a consciência tranquila."
{user} disse, com um olhar vazio: "Hm."
{user} disse: "Eu não me abalo com pouco."
{user} disse suavemente: "Confia em mim. Um dia você vai."
{user} disse: "Não tenho nada a temer."
{user} disse calmamente: "Você fala de mim, eu falo com você. Diferença."
{user} disse, tranquilo(a): "Tudo tem seu tempo."
{user} disse: "Você vai ver, e eu vou sorrir."
{user} disse: "Não vou gritar. Quem grita tem culpa."
{user} disse, com um aceno: "Ótima observação."
{user} disse serenamente: "Eu te vejo amanhã no café."
{user} disse: "Acho que você precisa descansar, {user1}."
{user} disse, estável: "Minha resposta é a mesma: não."
{user} disse, com leveza: "Todo mundo tem um palpite errado."
{user} disse calmamente: "Eu admiro sua coragem. Não sua pontaria."
{user} disse: "Não vou tremer, {user1}."
{user} disse: "Isso é tudo?"
{user} disse, sem se mexer: "Eu tô bem, obrigado(a)."
{user} disse, calmo(a): "Olha que coincidência, eu também desconfio de alguém."
{user} disse: "Você é previsível, {user1}."
{user} disse suave: "Respira. Não sou seu inimigo(a)."
{user} disse, tranquilo(a): "Pode vir. Eu tô aqui."
{user} disse com serenidade: "Não sou eu, e vou continuar não sendo."
{user} disse, sorrindo gelado: "Veremos."
{user} disse calmamente: "Eu confio que a verdade chega."
{user} disse: "Não vou perder minha paz por isso."
{user} disse, com olhar firme: "Você vai lembrar desse momento."
{user} disse: "Engraçado. Muito engraçado."
{user} disse, sem pressa: "A gente vê na hora do voto."
{user} disse, com um sorriso contido: "Você é muito atento(a). Parabéns."
{user} disse: "Não me conhece, {user1}. Só acha que conhece."
{user} disse, sereno(a): "Eu sou exatamente quem pareço."
{user} disse calmo(a): "Eu te perdoo. Adiantado."
{user} disse: "Hum. Que interessante."
{user} disse, com calma quase ensaiada: "Eu não guardo segredos."
{user} disse suavemente: "O medo faz a gente ver fantasmas."
{user} disse: "Pode falar, eu não mordo."
{user} disse tranquilamente: "Acho que você tá confundindo as coisas."
{user} disse, sorrindo: "Você é adorável, {user1}."
{user} disse com frieza educada: "Obrigado(a) pela preocupação."
{user} disse: "Hum. Vou pensar nisso. Ou não."
{user} disse, sereno(a): "Minha cabeça tá tranquila."
{user} disse: "Não tenho motivo pra me explicar."
{user} disse, com leveza: "Tá tudo bem entre a gente."
{user} disse calmamente: "O tempo é o melhor juiz."
{user} disse: "Você tá procurando no lugar errado."
{user} disse, sem emoção: "Certo."
{user} disse, com um olhar paciente: "Termina de falar, eu espero."
{user} disse: "Você vai me dar razão amanhã."
{user} disse, tranquilo(a): "Sem ressentimentos."
{user} disse suave: "Você é muito sensível ao medo, {user1}."
{user} disse com calma: "Eu não vou te atacar de volta."
{user} disse: "Deixa pra lá, {user1}."
{user} disse sereno(a): "Eu entendo. Mas não sou eu."
{user} disse, calmo(a): "A sua dúvida é problema seu."
{user} disse: "Não vou me justificar pra quem não quer ouvir."
{user} disse, sorrindo: "Faz sentido. Só que não."
{user} disse com leveza: "Eu vou continuar aqui, sorrindo."
{user} disse, sem mudar a voz: "Você me acusa e eu durmo."
{user} disse suavemente: "Seja feliz com seu voto."
{user} disse: "Que pena, eu gostava das nossas conversas."
{user} disse calmamente: "Talvez amanhã você veja melhor."
{user} disse, tranquilo(a): "Você não é o primeiro e não vai ser o último."
{user} disse: "Uau. Ok."
{user} disse, com calma: "Eu sei o que eu sou."
{user} disse, com um aceno leve: "Tá bom, {user1}. Tá bom."
{user} disse serenamente: "Nem vou me defender, não precisa."
{user} disse: "Você é criativo(a), isso eu admito."
{user} disse, sorrindo sem mostrar os dentes: "Vamos ver."
{user} disse calmo(a): "Eu não tenho pressa nenhuma."
{user} disse: "Você vai se sentir mal depois. Eu não."
{user} disse com voz baixa: "Isso não muda nada."
{user} disse, tranquilo(a): "Sua opinião é importante. Pra você."
{user} disse suave: "Tá tudo sob controle."
{user} disse: "Você é bem-vindo(a) a errar."
{user} disse, com calma perturbadora: "Continua, {user1}. Eu gosto."
{user} disse: "Nada a declarar."
{user} disse, sereno(a): "Tudo bem, a mesa vai ver."
{user} disse com calma: "Acho que você tá cansado(a)."
{user} disse, sem se abalar: "Minha resposta não muda."
{user} disse: "Eu sei me cuidar, {user1}."
{user} disse tranquilamente: "Não sou eu. Mas boa tentativa."
{user} disse, com sorriso educado: "Eu anoto tudo, viu?"
{user} disse suavemente: "Não vou brigar com você."
{user} disse: "Você tá dando voltas, {user1}."
{user} disse com serenidade: "Eu não sou o seu problema."
{user} disse, relaxado(a): "Pode escrever meu nome. Eu não ligo."
{user} disse: "Hum. Ok. Seguimos."
{user} disse, calmo(a): "Você vai entender quando for tarde."
{user} disse com leveza: "Eu te quero bem mesmo assim."
{user} disse, sem piscar: "Não."
{user} disse: "Isso é tudo que você tem?"
{user} disse, sereno(a): "Eu confio em mim."
{user} disse calmamente: "O castelo sabe quem eu sou."
{user} disse: "Não me afeta, {user1}."
{user} disse, com um sorriso calmo: "A gente se vê no próximo café."
{user} deu de ombros: "Pensa o que quiser, {user1}."
{user} bebeu um gole e disse: "Anotado."
{user} sorriu: "Você não é o(a) primeiro(a), {user1}."
{user} disse, sereno(a): "O tempo vai mostrar quem eu sou."
{user} respondeu sem alterar a voz: "Tá bom. Próximo assunto?"
{user} riu baixinho: "Tão fofo(a) você tentando."
{user} disse: "Não vou me desgastar com isso, {user1}."
{user} respondeu: "Tenho a consciência tranquila. E você?"
{user} disse, calmo(a): "Respeito sua opinião. Discordo dela."
{user} disse: "Eu durmo bem à noite, {user1}."
{user} olhou para {user1}: "Quer que eu me desespere? Não vai rolar."
{user} disse, tranquilo(a): "Vota. Depois me pede desculpa."
{user} disse: "Isso não me tira o sono, {user1}."
{user} disse: "Olha, {user1}, eu entendo o medo. Mas não sou eu."
`);

export const REPLY_SUSPECT = {
  good: lines(`
{user} deu de ombros: "Pode ficar de olho. Não tenho nada a esconder."
{user} sorriu: "Eu também desconfiaria de mim."
{user} riu: "Justo! Me vigia que eu te vigio."
{user} disse: "Tá tudo bem, {user1}. Pergunta o que quiser."
{user} disse: "Eu entendo, é o jogo. Mas sou Fiel."
{user} disse: "Pode vir conversar comigo quando quiser."
{user} disse: "Me observa. Você vai ver que é tranquilo."
{user} disse: "Eu gosto de você, então vou provar."
{user} disse: "Faz bem em desconfiar. Só não de mim."
{user} disse: "Olha, eu entendo. Mas relaxa comigo."
{user} disse: "Se quiser, eu te conto tudo que fiz ontem."
{user} disse: "Tá bom, detetive. Pode investigar."
{user} riu: "Você é muito atento(a). Gosto disso."
{user} disse: "Eu não me ofendo, {user1}."
{user} disse: "Dúvida é saudável. Eu também tenho as minhas."
{user} disse: "Vem cá, a gente conversa sem pressão."
{user} disse: "Eu sou livro aberto, pode ler."
{user} disse: "Desconfia, mas não esquece que eu te gosto."
{user} disse: "Tudo bem, {user1}. Eu sei que você vai ver."
{user} disse: "Me observa de perto, que eu não fujo."
{user} disse: "Faz parte. Você desconfia e eu provo."
{user} disse: "Eu faria o mesmo no seu lugar."
{user} disse: "Pode perguntar pra quem quiser sobre mim."
{user} sorriu: "Tô tranquilo(a). Pode confiar."
{user} disse: "Não vou ficar chateado(a) com você."
{user} disse: "Você tem razão de ter cuidado."
{user} disse: "A gente pode investigar juntos, se quiser."
{user} disse: "Qualquer dúvida, vem direto em mim."
{user} disse: "Você vai me ver até o final. Como Fiel."
{user} disse: "Eu admiro quem fala na cara."
{user} disse: "Tudo bem, eu ganho sua confiança com o tempo."
{user} disse: "Pode perguntar, {user1}. Eu respondo tudo."
{user} disse: "Eu não tenho segredos com você."
{user} disse: "Olha, eu desconfiaria de todo mundo também."
{user} disse: "Você tá certo(a) de ficar esperto(a)."
{user} disse: "Vou te mostrar quem eu sou."
{user} disse: "Fica tranquilo(a), eu não sou quem você procura."
{user} riu: "Eu? Logo eu? Você me conhece!"
{user} disse: "Te entendo. Mas vou te surpreender."
{user} disse: "Eu tô do seu lado, mesmo com a dúvida."
{user} disse: "Desconfia à vontade, eu gosto de você igual."
{user} disse: "Você é esperto(a). Por isso sei que vai acertar."
{user} disse: "Tudo certo, {user1}. Sem estresse."
{user} disse: "Se isso te acalma, eu fico por perto."
{user} disse: "Vamos combinar: você me vigia e eu te protejo."
{user} disse: "Pode desconfiar, o voto é seu."
{user} disse: "Eu te conto tudo que eu sei. Quer?"
{user} disse: "A dúvida passa. A amizade fica."
{user} disse: "Você é o(a) único(a) que eu deixo desconfiar."
{user} disse: "Faz sentido. Mas vou te provar o contrário."
{user} disse: "Tudo bem, eu também tô no seu radar de amigos."
{user} disse: "Olha, eu entendo. Aqui ninguém confia em ninguém."
{user} disse: "Pode ficar à vontade pra perguntar."
{user} disse: "Isso não muda o que eu sinto por você."
{user} disse: "Eu vou te mostrar com atitudes."
{user} disse: "Você é cuidadoso(a). Eu admiro."
{user} disse: "Vem, me pergunta o que você quer saber."
{user} disse: "Te dou meu voto de confiança mesmo assim."
{user} disse: "Não vou fugir de nada."
{user} disse: "Você vai ver que eu sou o que pareço."
{user} disse: "Eu sei que você só quer acertar."
{user} disse: "A gente vai rir disso depois."
{user} disse: "Eu tô aqui, sem máscara."
{user} disse: "Você merece respostas. Pergunta."
{user} disse: "Fica de olho. Eu vou ficar de olho em você também. Com carinho."
{user} disse: "Eu não tenho medo da sua desconfiança."
{user} disse: "Me dá um dia e você muda de ideia."
{user} disse: "Pode confiar em mim, {user1}. Pode mesmo."
`),
  neutral: lines(`
{user} desviou o olhar e mudou de assunto.
{user} respondeu com uma pergunta: "E você, {user1}, estava onde?"
{user} disse: "Hm. Tá."
{user} disse: "Cada um desconfia de quem quer."
{user} deu de ombros: "Problema seu."
{user} disse: "Não vou me explicar por isso."
{user} disse: "Você tá no seu direito."
{user} disse: "Tudo bem. Eu também tenho minhas dúvidas."
{user} disse: "Isso é só impressão sua."
{user} disse: "Eu não vou perder o sono."
{user} disse: "Olha pros outros também, {user1}."
{user} disse: "Pode ser que eu seja, pode ser que não."
{user} disse: "Desconfiar é fácil."
{user} disse: "Beleza. Anotado."
{user} disse: "Vamos ver o que o tempo diz."
{user} disse: "Não tenho nada a declarar."
{user} disse: "Isso não me preocupa."
{user} disse: "Ok, {user1}."
{user} disse: "E por que eu, exatamente?"
{user} disse: "Você tá pensando demais."
{user} disse: "Não sei o que te dizer."
{user} disse: "Normal. Todo mundo desconfia de todo mundo."
{user} disse: "Fica à vontade."
{user} disse: "Então me vigia. Eu não ligo."
{user} disse: "Hm. Eu não esperava isso."
{user} disse: "Tá, e daí?"
{user} disse: "Tem gente mais estranha que eu aqui."
{user} disse: "Isso é paranoia, {user1}."
{user} disse: "Você que sabe."
{user} disse: "Não vou discutir."
{user} disse: "Eu entendo o jogo."
{user} disse: "É uma escolha sua."
{user} disse: "Eu sou o que sou."
{user} disse: "Não muda nada pra mim."
{user} disse: "Tá tudo bem. Só não vota errado."
{user} disse: "Você tem seus motivos. Eu tenho os meus."
{user} disse: "Engraçado, né? Eu ia falar o mesmo."
{user} disse: "Vou pensar no que você disse."
{user} disse: "Hum. Tá certo."
{user} disse: "Não precisa ficar me encarando."
{user} disse: "Ok. Mais alguma coisa?"
{user} disse: "Eu tô tranquilo(a) com minha consciência."
{user} disse: "Não vou te convencer, então nem tento."
{user} disse: "Desconfia de quem desconfia de todo mundo."
{user} disse: "Isso é problema seu, não meu."
{user} disse: "Se quiser, a gente conversa depois."
{user} disse: "Não é bem assim, {user1}."
{user} disse: "Vou fingir que não ouvi."
{user} disse: "Certo. Você tá de olho, eu tô de olho."
{user} disse: "Isso é o jogo."
{user} disse: "Não esquenta."
{user} disse: "Você tá confundindo as coisas."
{user} disse: "Normal, a gente tá nervoso."
{user} disse: "Pode ser. Pode não ser."
{user} disse: "Tá, tá bom."
{user} disse: "Sério mesmo? Tá."
{user} disse: "Não vou gastar energia com isso."
{user} disse: "Vamos ver no voto."
{user} disse: "Ninguém aqui é santo."
{user} disse: "Eu ia te dizer o mesmo."
{user} disse: "Se isso te ajuda a dormir..."
{user} disse: "Não esperava, mas tudo bem."
{user} disse: "Se é assim que você pensa..."
{user} disse: "Não tenho nada contra você por isso."
{user} disse: "Tá, mas me dá um motivo."
{user} disse: "Isso é só coisa da sua cabeça."
{user} disse: "Hum. Veremos."
`),
  bad: lines(`
{user} fechou a cara: "Desconfia de si mesmo(a) primeiro, {user1}."
{user} disse: "Você é que tá estranho(a)."
{user} disse: "Olha quem fala!"
{user} disse: "Desconfia de mim? Eu desconfio de você desde o início."
{user} disse: "Você não tem moral pra isso."
{user} disse: "Vai procurar outro pra encher."
{user} riu com desdém: "Que original."
{user} disse: "Você tá plantando dúvida. Traidor(a) faz isso."
{user} disse: "Engraçado vindo de você."
{user} disse: "Toma cuidado com o que você fala."
{user} disse: "Eu vou lembrar disso na mesa."
{user} disse: "Você me irrita, {user1}."
{user} disse: "Quem fala muito de desconfiança esconde algo."
{user} disse: "Não me testa, {user1}."
{user} disse: "Você devia olhar pro espelho."
{user} disse: "Isso é recalque, {user1}."
{user} disse: "Eu não te devo explicação nenhuma."
{user} disse: "Continua assim e você vai ver."
{user} disse: "Você é o(a) primeiro(a) da minha lista agora."
{user} disse: "Que audácia."
{user} disse: "Falou quem vive cochichando."
{user} disse: "Você não sabe de nada."
{user} disse: "Isso é teatro pra se proteger."
{user} disse: "Pode desconfiar. Eu te ignoro."
{user} disse: "Você quer me queimar, né?"
{user} disse: "Eu sei o que você tá fazendo."
{user} disse: "Não vou aceitar isso quieto(a)."
{user} disse: "Você vive de fofoca, {user1}."
{user} disse: "Me poupa, {user1}."
{user} disse: "Agora eu que desconfio de você."
{user} disse: "Quem desconfia de mim, desconfia do Fiel errado."
{user} disse: "Isso é ataque gratuito."
{user} disse: "Não vou esquecer isso."
{user} disse: "Você tá se entregando."
{user} disse: "Ah, pronto. Agora é comigo."
{user} disse: "Você não tem outro alvo, não?"
{user} disse: "Eu tô de saco cheio de você, {user1}."
{user} disse: "Tá querendo briga?"
{user} disse: "Some da minha frente."
{user} disse: "Você é o(a) mais suspeito(a) aqui."
{user} disse: "Eu vou te dar motivo pra desconfiar."
{user} disse: "Pode falar pra todo mundo. Eu não ligo."
{user} disse: "Você tá desesperado(a) atrás de um nome."
{user} disse: "Não me mete nas suas paranoias."
{user} disse: "Você é chato(a), {user1}."
{user} disse: "Traidor(a) adora desviar o foco."
{user} disse: "Guarda sua desconfiança pra você."
{user} disse: "Você me acusa e eu anoto."
{user} disse: "Isso é inveja."
{user} disse: "Continua me provocando, continua."
{user} disse: "Não tô nem aí pra sua opinião."
{user} disse: "Você é o(a) menos indicado(a) pra falar disso."
{user} disse: "Eu tenho uma lista, e você acabou de subir."
{user} disse: "Isso vai ter consequência."
{user} disse: "Você tá brincando com fogo."
{user} disse: "Não enche, {user1}."
{user} disse: "Pode desconfiar. Mas cuidado com as costas."
{user} disse: "Você não vale meu tempo."
{user} disse: "Eu sei exatamente o que você é."
{user} disse: "Olha, vai lá desconfiar de outro."
{user} disse: "Você tá procurando confusão."
{user} disse: "Que discurso de Traidor(a)."
{user} disse: "Eu não confio em você. Nunca confiei."
{user} disse: "Você vai se arrepender disso."
{user} disse: "Pode vir que eu tô preparado(a)."
{user} disse: "Isso é o mais baixo que você já foi."
{user} disse: "Guarda esse papo pra quem acredita."
`),
};

export const REPLY_INSULT = {
  good: lines(`
{user} ficou chocado(a): "Eu achava que a gente se dava bem, {user1}."
{user} disse, magoado(a): "Por que isso agora?"
{user} ficou calado(a) e saiu do salão.
{user} disse: "Isso não é você falando, {user1}."
{user} disse: "Você tá estressado(a). Eu te perdoo."
{user} disse: "Uau. Não esperava isso de você."
{user} disse: "Tá tudo bem? Você nunca falou assim."
{user} disse: "Eu vou fingir que não ouvi."
{user} disse com a voz tremendo: "Isso machucou, {user1}."
{user} disse: "Quando quiser pedir desculpas, eu tô aqui."
{user} disse: "Eu não mereço isso, mas tudo bem."
{user} disse: "O jogo tá mexendo com você, né?"
{user} disse: "Eu gosto de você mesmo assim. Infelizmente."
{user} disse: "A gente conversa quando você esfriar."
{user} disse: "Você vai se arrepender disso."
{user} baixou a cabeça: "Tá bom, {user1}."
{user} disse: "Eu pensei que tinha uma amizade aqui."
{user} disse: "Isso foi desnecessário, {user1}."
{user} disse: "Eu não vou responder no mesmo tom."
{user} disse: "Você tá sendo injusto(a) comigo."
{user} disse: "Essa doeu, viu?"
{user} ficou com os olhos marejados.
{user} disse: "Eu sempre te tratei bem..."
{user} disse: "Respira, {user1}. Eu sei que não é pessoal."
{user} disse: "Não precisava disso."
{user} disse: "Eu vou relevar, porque gosto de você."
{user} disse: "Você tá descontando em mim."
{user} disse: "Tudo bem, mas isso fica anotado."
{user} disse: "Olha, eu entendo o cansaço, mas não fala assim comigo."
{user} disse: "Isso não combina com você."
{user} disse: "Quer conversar sobre o que tá acontecendo?"
{user} disse: "Eu não vou te odiar por isso."
{user} disse: "Não esperava ouvir isso de um(a) amigo(a)."
{user} disse: "Tá tudo bem, eu sei que você tá sob pressão."
{user} disse: "Você me pegou desprevenido(a)."
{user} disse: "Isso vai ficar entre nós, tá?"
{user} disse: "Eu fico triste, mas passa."
{user} disse: "Que pena, {user1}. Que pena."
{user} disse: "Eu vou deixar essa passar."
{user} disse: "Você sabe que não é verdade."
{user} disse: "Eu esperava mais carinho, confesso."
{user} disse: "Não me afasta, {user1}."
{user} disse: "Isso é o castelo te consumindo."
{user} disse: "Eu fico do seu lado mesmo assim."
{user} disse: "Machucou, mas eu entendo."
{user} disse: "Você me decepcionou agora."
{user} disse: "Eu vou te dar tempo."
{user} disse: "Não faz isso com a gente."
{user} disse: "Eu não vou revidar."
{user} disse: "Isso foi um desabafo, né? Tudo bem."
{user} disse: "Você tá precisando de um abraço, não de briga."
{user} disse: "Tá, eu mereci? Me explica."
{user} disse: "Eu vou lembrar disso com tristeza."
{user} disse: "Por que você tá assim comigo?"
{user} disse: "Eu esperava tudo, menos isso."
{user} disse: "Você é melhor que isso, {user1}."
{user} disse: "Eu não vou deixar isso estragar tudo."
{user} disse: "Que dia difícil pra você, hein?"
{user} disse: "Eu te perdoo, mas pede desculpa."
{user} disse: "Não é assim que se trata um(a) aliado(a)."
{user} disse: "Isso aí não te representa."
{user} disse: "Tô magoado(a), mas passa."
{user} disse: "Eu sei que no fundo você não pensa isso."
{user} disse: "Vamos fingir que isso não aconteceu?"
{user} disse: "Não precisa me machucar pra se sentir melhor."
{user} disse: "Eu vou te esperar voltar a ser você."
{user} disse: "Isso me pegou, {user1}. De verdade."
`),
  neutral: lines(`
{user} respondeu à altura, e só pararam quando alguém separou os dois.
{user} olhou com desprezo: "Anotado."
{user} disse: "Não vou descer no seu nível."
{user} deu as costas.
{user} disse: "Tá bom. E?"
{user} disse: "Isso diz mais sobre você do que sobre mim."
{user} disse: "Que maturidade, {user1}."
{user} revirou os olhos.
{user} disse: "Continua. Tá divertido."
{user} disse: "Eu ouvi coisa pior no ônibus."
{user} disse: "Você terminou?"
{user} disse: "Ok. Seguimos."
{user} disse: "Nossa, que ofensa. Vou chorar. Só que não."
{user} disse: "Você tá cansado(a). Vai dormir."
{user} disse: "Isso não me atinge."
{user} disse: "Tá, e o que você ganha com isso?"
{user} disse: "Guarda pra mesa redonda, que lá vale mais."
{user} disse: "Não vou gastar energia com você."
{user} disse: "Ah, tá. Beleza."
{user} disse: "Educação passou longe, né?"
{user} disse: "Faz bem pra você falar isso?"
{user} disse: "Tá descontando em mim o que é de outro."
{user} disse: "Eu vou ignorar isso."
{user} disse: "Você é criativo(a) pra ofensa, pelo menos."
{user} disse: "Isso foi baixo."
{user} disse: "Não esperava menos de você."
{user} disse: "Você tá se queimando sozinho(a)."
{user} disse: "Engraçado. Eu pensava o mesmo de você."
{user} disse: "Pode falar. As paredes ouvem."
{user} disse: "Tá, mais alguma coisa?"
{user} disse: "Isso é o melhor que você tem?"
{user} disse: "Você tá nervoso(a) com o quê?"
{user} disse: "Que deselegante."
{user} disse: "Não vou responder. Não vale."
{user} disse: "Vai ficar feio pra você, não pra mim."
{user} disse: "Hm. Anotado, {user1}."
{user} disse: "Não vou perder a linha."
{user} disse: "Isso não tem necessidade nenhuma."
{user} disse: "Você perdeu a chance de ficar calado(a)."
{user} disse: "Hm, ok. Próximo."
{user} disse: "Tá tudo bem aí, {user1}?"
{user} disse: "Você deve ter tido uma noite ruim."
{user} disse: "Isso não muda meu voto. Nem pra lá, nem pra cá."
{user} disse: "Fala o que quiser. Eu sei quem sou."
{user} disse: "Uau. Tá bom."
{user} disse: "Não acho que isso te ajuda no jogo."
{user} disse: "Isso vai pro seu currículo aqui dentro."
{user} disse: "Não vou discutir com quem grita."
{user} disse: "Respira, {user1}."
{user} disse: "Eu guardo isso pra depois."
{user} disse: "Quem ofende perde a razão."
{user} disse: "Beleza, fica com a sua opinião."
{user} disse: "Você tá ansioso(a), dá pra ver."
{user} disse: "Isso não te leva a lugar nenhum."
{user} disse: "Que pena você pensar assim."
{user} disse: "Não esperava, mas ok."
{user} disse: "Hum. Tá bom então."
{user} disse: "Você não me conhece pra falar isso."
{user} disse: "Deixa pra lá."
{user} disse: "Isso é problema seu, {user1}."
{user} disse: "Eu tenho mais o que fazer."
{user} disse: "Não levo pro pessoal. Mas lembro."
{user} disse: "Você tá gastando saliva à toa."
{user} disse: "Eu vou relevar. Só essa vez."
{user} disse: "Hm. Você tá de mau humor, né?"
{user} disse: "Nem vou comentar."
{user} disse: "Sua opinião foi registrada."
`),
  bad: lines(`
{user} gritou de volta e o salão inteiro parou para assistir.
{user} jurou que {user1} vai sair na próxima mesa.
{user} jogou o guardanapo na mesa e saiu, batendo a porta.
{user} disse: "Olha quem fala, {user1}!"
{user} disse: "Você é que é insuportável!"
{user} disse: "Repete isso se tiver coragem!"
{user} disse: "Você vai engolir cada palavra."
{user} disse: "Eu não tenho medo de você."
{user} disse: "Você é a pessoa mais falsa daqui!"
{user} disse: "Isso vai te custar caro."
{user} disse: "Você acabou de fazer um(a) inimigo(a)."
{user} partiu pra cima, mas foi segurado(a).
{user} disse: "Hipócrita!"
{user} disse: "Você tá no meu voto até o fim."
{user} disse: "Vai lavar essa boca, {user1}!"
{user} disse: "Eu vou te derrubar, pode escrever."
{user} disse: "Covarde! Fala isso na mesa!"
{user} disse: "Você é veneno puro!"
{user} disse: "Que ódio de você, {user1}!"
{user} disse: "Não me dirige mais a palavra."
{user} disse: "Você é ridículo(a)!"
{user} disse: "Eu vou fazer questão de te ver saindo."
{user} disse: "Você não é nada, {user1}!"
{user} bateu a mão na mesa: "Chega!"
{user} disse: "Guarda seu veneno pra você!"
{user} disse: "Isso aqui não vai ficar assim."
{user} disse: "Você é o(a) pior daqui, e todo mundo sabe."
{user} disse: "Eu tô com nojo de você."
{user} disse: "Pode esperar a resposta, {user1}."
{user} disse: "Você tá pedindo pra ser banido(a)."
{user} disse: "Falsa(o)! Falsa(o) de carteirinha!"
{user} disse: "Eu vou contar pra todo mundo o que você é."
{user} disse: "Você é baixo(a) demais."
{user} disse: "Some daqui antes que eu perca a paciência!"
{user} disse: "Tá achando que é quem?"
{user} disse: "Você não merece nem meu desprezo."
{user} disse: "Isso é guerra, {user1}."
{user} disse: "Eu vou fazer da sua vida um inferno aqui dentro."
{user} disse: "Você acabou de cavar a própria cova."
{user} disse: "Mal-educado(a)! Grosso(a)!"
{user} disse: "Você é a pior pessoa desse castelo!"
{user} disse: "Eu nunca vou esquecer isso."
{user} disse: "Você não tem limite, né?"
{user} disse: "Eu vou lembrar disso no voto. Todo voto."
{user} disse: "Vem falar isso de perto!"
{user} disse: "Você é uma farsa, {user1}!"
{user} disse: "Tá mexendo com a pessoa errada."
{user} disse: "Você vai pagar, cada centavo."
{user} disse: "Isso não tem perdão."
{user} disse: "Você só sabe atacar quem é melhor que você."
{user} disse: "Vai chorar na torre, {user1}!"
{user} disse: "Olha o nível, gente. Olha o nível!"
{user} disse: "Eu te detesto, {user1}."
{user} disse: "Você é o câncer desse grupo!"
{user} disse: "Pode vir! Eu não vou recuar!"
{user} disse: "Você é mais baixo(a) do que eu pensava."
{user} disse: "Isso é inveja, pura inveja!"
{user} disse: "Ninguém aguenta você, {user1}!"
{user} disse: "Vou te mostrar quem é que é insuportável."
{user} disse: "Eu tô contando os dias pra você sair."
{user} disse: "Fala mais uma e eu não respondo por mim."
{user} disse: "Você é a vergonha do castelo!"
{user} disse: "Engole o que disse, {user1}!"
{user} disse: "Isso vai ter volta. E vai ser pior."
{user} disse: "Você é uma pessoa horrível."
{user} disse: "Tá achando que tá falando com quem?"
{user} disse: "Eu vou ser seu pesadelo aqui dentro."
`),
};
