import { lines } from './lines';

/** Respostas: {user} = quem responde, {user1} = jogador. */

export const REPLY_DEFEND = {
  good: lines(`
{user} agradeceu com os olhos marejados: "Não vou esquecer isso, {user1}."
{user} apertou a mão de {user1}: "Obrigado(a). De verdade."
{user} abraçou {user1} forte: "Você salvou minha pele."
{user} disse: "Eu te devo uma, e eu pago minhas dívidas."
{user} disse: "Você é o(a) único(a) que acreditou em mim."
{user} sussurrou: "Nunca vou votar em você. Nunca."
{user} disse, emocionado(a): "Isso significa muito."
{user} disse: "Agora você tem um(a) aliado(a) pra vida."
{user} chorou: "Eu achei que tava sozinho(a)."
{user} disse: "Obrigado(a) por me enxergar, {user1}."
{user} disse: "Eu vou retribuir, pode ter certeza."
{user} disse: "Você é gente de verdade, {user1}."
{user} disse: "Eu nunca vou esquecer quem ficou do meu lado."
{user} disse: "Te devo minha permanência aqui."
{user} disse: "Você é um anjo nesse castelo."
{user} disse: "Eu tô contigo até o fim agora."
{user} disse: "Isso foi a coisa mais bonita que fizeram por mim aqui."
{user} disse: "Obrigado(a) por ter coragem."
{user} disse: "Quando precisar, é só chamar."
{user} disse: "Você me deu esperança."
{user} disse: "Eu vou provar que você estava certo(a)."
{user} disse: "Você tem minha lealdade."
{user} disse: "Nossa, eu nem sei o que dizer."
{user} disse: "Eu te protejo de agora em diante."
{user} disse: "Você é o(a) melhor desse castelo."
{user} disse: "Vou lembrar disso em cada mesa."
{user} disse: "Eu te amo, {user1}. De coração."
{user} disse: "Você não sabe o bem que me fez."
{user} disse: "Me senti menos sozinho(a) agora."
{user} disse: "Pode contar comigo pra tudo."
{user} disse: "Você é sangue bom, {user1}."
{user} disse: "Eu não tenho palavras pra agradecer."
{user} disse: "Ninguém nunca me defendeu assim."
{user} disse: "Você é meu herói(minha heroína) hoje."
{user} disse: "Eu vou honrar essa confiança."
{user} disse: "Isso foi lindo, {user1}."
{user} disse: "Tô emocionado(a) aqui, não repara."
{user} disse: "Você acabou de ganhar um(a) amigo(a) pra sempre."
{user} disse: "Isso é lealdade. Obrigado(a)."
{user} disse: "Eu vou te defender também, pode apostar."
{user} disse: "Obrigado(a) por não desistir de mim."
{user} disse: "Você é a razão de eu ainda acreditar nesse jogo."
{user} disse: "Eu nunca vou te decepcionar."
{user} disse: "Você é muito especial, {user1}."
{user} disse: "Isso me deu forças."
{user} disse: "Você é daqueles(as) que a gente leva pra vida."
{user} disse: "Não tenho como te pagar."
{user} disse: "Você acabou de conquistar minha lealdade."
{user} disse: "Eu tava com tanto medo... obrigado(a)."
{user} disse: "Isso foi coragem pura."
{user} disse: "Você é meu escudo, e agora eu sou o seu."
{user} disse: "Obrigado(a). Eu não esqueço."
{user} disse: "Você me devolveu a paz."
{user} disse: "Eu vou retribuir na mesa, pode ter certeza."
{user} disse: "Você é o tipo de pessoa que eu admiro."
{user} disse: "Isso vai ficar marcado no meu coração."
{user} disse: "Eu te devo tudo, {user1}."
{user} disse: "Obrigado(a) por falar por mim."
{user} disse: "Eu não esperava, e isso tornou tudo mais especial."
{user} disse: "Juntos, a gente vai longe."
{user} disse: "Você é meu(minha) protetor(a) oficial."
{user} disse: "Você tem um coração enorme."
{user} disse: "Isso é amizade de verdade."
{user} disse: "Obrigado(a), mil vezes obrigado(a)."
{user} disse: "Eu fico te devendo essa pra sempre."
{user} disse: "Eu vou merecer essa confiança."
{user} disse: "Você é luz, {user1}."
`),
  neutral: lines(`
{user} agradeceu, mas ficou pensando no motivo da defesa.
{user} assentiu em silêncio.
{user} sorriu, meio sem graça: "Eu te devo uma, {user1}."
{user} disse: "Obrigado(a). Não precisava."
{user} disse: "Valeu. Vou lembrar."
{user} disse: "Hm. Obrigado(a), eu acho."
{user} disse: "Não esperava isso de você."
{user} disse: "Obrigado(a). Mas por quê?"
{user} disse: "Tá, obrigado(a)."
{user} deu um aceno curto.
{user} disse: "Isso foi gentil."
{user} disse: "Você me pegou de surpresa."
{user} disse: "Obrigado(a). Vou pensar nisso."
{user} disse: "Fico grato(a). De verdade."
{user} disse: "Não sei se mereço, mas obrigado(a)."
{user} disse: "Beleza, valeu."
{user} disse: "Isso ajuda. Obrigado(a)."
{user} disse: "Interessante você me defender."
{user} disse: "Anotado. No bom sentido."
{user} disse: "Obrigado(a), {user1}."
{user} disse: "Ok. Vou lembrar disso."
{user} disse: "Não precisava se expor por mim."
{user} disse: "Eu agradeço, mas cuidado com você também."
{user} disse: "Hum, tá. Obrigado(a)."
{user} disse: "Você não precisava fazer isso."
{user} disse: "Eu não sei o que dizer. Obrigado(a)."
{user} disse: "Obrigado(a). Espero retribuir."
{user} disse: "Isso vai contar a seu favor."
{user} disse: "Fico feliz, mas desconfiado(a)."
{user} disse: "Legal da sua parte."
{user} disse: "Valeu, {user1}."
{user} disse: "Obrigado(a). Vamos ver no voto."
{user} disse: "Não esperava ajuda hoje."
{user} disse: "Isso foi inesperado."
{user} disse: "Obrigado(a). Acho que você tá certo(a) sobre mim."
{user} disse: "Hm. Ok, obrigado(a)."
{user} disse: "Beleza. Tamo junto, eu acho."
{user} disse: "Te agradeço pela coragem."
{user} disse: "Isso mudou um pouco meu dia."
{user} disse: "Obrigado(a). Vou te observar melhor."
{user} disse: "Não pedi, mas agradeço."
{user} disse: "Agradeço, sério."
{user} disse: "É bom saber que alguém acredita."
{user} disse: "Obrigado(a). Vou pensar em você na mesa."
{user} disse: "Tudo bem. Obrigado(a)."
{user} disse: "Valeu pela força."
{user} disse: "Obrigado(a). Espero que não tenha interesse nisso."
{user} disse: "Hum. Legal."
{user} disse: "Obrigado(a). Isso me pegou."
{user} disse: "Vou lembrar de quem ficou do meu lado."
{user} disse: "Não esperava, mas obrigado(a)."
{user} disse: "Obrigado(a), você não precisava."
{user} disse: "Isso me deixou pensativo(a)."
{user} disse: "Tá, mas cuidado, que agora vão olhar pra você."
{user} disse: "Obrigado(a) pela defesa."
{user} disse: "Você é corajoso(a) de fazer isso."
{user} disse: "Vou fingir que não fiquei emocionado(a)."
{user} disse: "Obrigado(a). A gente conversa depois."
{user} disse: "Hm, você tá jogando comigo agora?"
{user} disse: "Fico te devendo."
{user} disse: "Obrigado(a). Mas não precisava arriscar."
{user} disse: "Beleza. Entendi seu lado."
{user} disse: "Obrigado(a), sério mesmo."
{user} disse: "Isso me dá um alívio."
{user} disse: "Obrigado(a). Eu reparei."
{user} disse: "Não esquecerei."
{user} disse: "Obrigado(a). Vou ver o que faço com isso."
`),
  bad: lines(`
{user} estranhou: "Por que você tá me defendendo, {user1}? O que você quer?"
{user} disse: "Não preciso da sua ajuda."
{user} disse: "Isso é jogada, né?"
{user} disse: "Me defender não vai te salvar."
{user} disse: "Você tá querendo o quê com isso?"
{user} disse: "Não confio nem na sua defesa."
{user} disse: "Guarda sua caridade pra outro."
{user} disse: "Agora você me defende? Engraçado."
{user} disse: "Isso tá com cara de armadilha."
{user} disse: "Não vou te agradecer por isso."
{user} disse: "Não pedi sua defesa."
{user} disse: "Isso não apaga o que você fez."
{user} disse: "Você acha que me compra assim?"
{user} disse: "Tô de olho em você mesmo assim."
{user} disse: "Hm. Que conveniente."
{user} disse: "Isso é teatro, {user1}."
{user} disse: "Você defende pra depois apunhalar."
{user} disse: "Não me ajuda, que eu desconfio."
{user} disse: "Traidor(a) adora defender pra ganhar confiança."
{user} disse: "Não cola, {user1}."
{user} disse: "Você tá tentando limpar sua barra?"
{user} disse: "Não esqueço o que você disse de mim antes."
{user} disse: "Isso não muda nada entre a gente."
{user} disse: "Quem te pediu?"
{user} disse: "Isso me deixou mais desconfiado(a)."
{user} disse: "Não gostei. Não sei por quê, mas não gostei."
{user} disse: "Você quer meu voto, né?"
{user} disse: "Defesa estranha, vinda de quem vem."
{user} disse: "Eu sei me defender sozinho(a)."
{user} disse: "Não precisa fingir que gosta de mim."
{user} disse: "Você tá jogando em dois lados."
{user} disse: "Isso não me convence de nada."
{user} disse: "Obrigado(a)? Não. Desconfiado(a)."
{user} disse: "Você nunca faz nada de graça."
{user} disse: "Eu vou continuar de olho em você."
{user} disse: "Me poupe da sua bondade."
{user} disse: "Isso é oportunismo."
{user} disse: "Você é o(a) último(a) que eu queria do meu lado."
{user} disse: "Não vai rolar, {user1}."
{user} disse: "Guarda pra você."
{user} disse: "Se isso for jogada, é das ruins."
{user} disse: "Não caio nessa."
{user} disse: "Você quer me usar de escudo depois?"
{user} disse: "Hm. Anotado. Com desconfiança."
{user} disse: "Que suspeito você vir me defender."
{user} disse: "Não me faz favor, que eu não te devo nada."
{user} disse: "Isso é estratégia barata."
{user} disse: "Não me mete nas suas jogadas."
{user} disse: "Você só me defende quando convém."
{user} disse: "Não sou idiota, {user1}."
{user} disse: "Isso tá cheirando a acordo da torre."
{user} disse: "Vai defender outro, vai."
{user} disse: "Eu te conheço, {user1}."
{user} disse: "Não compro essa bondade repentina."
{user} disse: "Você é o(a) mais falso(a) daqui, e agora me defende?"
{user} disse: "Não sei se agradeço ou se corro."
{user} disse: "Isso é o beijo de Judas?"
{user} disse: "Não tô pedindo sua ajuda."
{user} disse: "Guarda seu discurso bonito."
{user} disse: "Você acha que eu esqueço fácil?"
{user} disse: "Não vou virar seu(sua) aliado(a) por isso."
{user} disse: "Tô vendo o que você tá fazendo."
{user} disse: "Não me confunde, {user1}."
{user} disse: "Defesa de quem quer algo em troca."
{user} disse: "Não preciso que você salve minha pele."
{user} disse: "Você me defende e eu me preocupo."
{user} disse: "Não, obrigado(a)."
`),
};

export const REPLY_TRUST = {
  good: lines(`
{user} abraçou {user1}: "Eu também confio em você."
{user} sussurrou de volta: "Você e eu até o fim."
{user} disse: "Eu sentia o mesmo, {user1}."
{user} segurou a mão de {user1}: "Pode contar comigo."
{user} disse: "Que bom ouvir isso. Recíproco."
{user} disse: "Você também é meu porto seguro."
{user} disse: "Eu nunca vou te decepcionar."
{user} disse: "Confiança se paga com confiança. Tô contigo."
{user} disse: "Você acabou de ganhar meu voto de proteção."
{user} disse: "Eu tava esperando alguém dizer isso."
{user} disse: "Eu confio em você desde o primeiro dia."
{user} disse: "Isso me acalma muito, {user1}."
{user} disse: "A gente vai longe juntos."
{user} disse: "Você é das minhas pessoas aqui."
{user} disse: "Pode dormir tranquilo(a). Eu cuido de você."
{user} disse: "Você não imagina o quanto eu precisava disso."
{user} disse: "Eu sinto o mesmo, de verdade."
{user} disse: "Confiança mútua, então."
{user} disse: "Você é família aqui dentro."
{user} disse: "Eu nunca vou escrever seu nome."
{user} disse: "Isso vale mais que qualquer escudo."
{user} disse: "Eu tô do seu lado, {user1}."
{user} disse: "A gente se protege, fechado."
{user} disse: "Você me deixou mais leve."
{user} disse: "Obrigado(a) por confiar. Eu confio também."
{user} disse: "Você é meu norte aqui."
{user} disse: "Eu sei que posso contar com você."
{user} disse: "Isso é recíproco, {user1}. Totalmente."
{user} disse: "Eu te protejo na mesa, pode deixar."
{user} disse: "Você é daquelas pessoas raras."
{user} disse: "Confio de olhos fechados."
{user} disse: "Isso me deu forças pra continuar."
{user} disse: "A gente é time."
{user} disse: "Eu esperava ouvir isso de você."
{user} disse: "Você tem minha confiança também."
{user} disse: "Estamos juntos nessa, {user1}."
{user} disse: "Eu vou honrar isso."
{user} disse: "Você é meu refúgio também."
{user} disse: "A gente combina, né?"
{user} disse: "Você é o(a) único(a) em quem eu confio de verdade."
{user} disse: "Isso me fez sorrir."
{user} disse: "Eu vou retribuir essa confiança."
{user} disse: "Pode contar comigo pra qualquer coisa."
{user} disse: "Eu nunca vou te trair."
{user} disse: "Você é meu aliado(a) de coração."
{user} disse: "Eu tava me sentindo sozinho(a). Obrigado(a)."
{user} disse: "Conte comigo até a última mesa."
{user} disse: "A gente se entende sem palavras."
{user} disse: "Você é o melhor que me aconteceu aqui."
{user} disse: "Eu confio mais em você que em mim."
{user} disse: "Isso é lindo, {user1}."
{user} disse: "A gente vai se proteger sempre."
{user} disse: "Eu sinto verdade no que você diz."
{user} disse: "Você é meu voto de confiança também."
{user} disse: "Isso fica entre nós, e fica pra sempre."
{user} disse: "Eu estou com você, independente de tudo."
{user} disse: "Obrigado(a), de coração."
{user} disse: "Você é especial pra mim aqui dentro."
{user} disse: "Juntos até o fim, combinado."
{user} disse: "Isso me emocionou."
{user} disse: "A confiança é toda sua."
{user} disse: "Você é meu irmão(ã) de castelo."
{user} disse: "Eu te guardo no coração e no voto."
{user} disse: "Eu tô aqui, sempre."
{user} disse: "Você não vai se arrepender."
{user} disse: "Isso é o que me faz continuar."
{user} disse: "Pode confiar. Eu confio também."
`),
  neutral: lines(`
{user} sorriu, mas não disse que confiava de volta.
{user} respondeu: "Vamos ver nos próximos dias."
{user} apertou a mão de {user1}: "Então me prova isso na mesa."
{user} disse: "Obrigado(a). Eu ainda tô te conhecendo."
{user} disse: "Confiança se constrói, {user1}."
{user} disse: "Bom saber. Vou pensar."
{user} disse: "Hm. Tá."
{user} disse: "É um começo."
{user} disse: "Fico feliz. Mas vamos devagar."
{user} disse: "Eu vou ver como você vota."
{user} disse: "Palavras são fáceis, {user1}."
{user} disse: "Beleza. Vamos ver."
{user} disse: "Obrigado(a). Mas aqui ninguém confia cem por cento."
{user} disse: "Ok, anotado."
{user} disse: "Você é legal. Só não sei ainda."
{user} disse: "Isso é bom. Mas cuidado com quem você confia."
{user} disse: "Eu agradeço, mas prefiro ir com calma."
{user} disse: "Tá, e o que você espera de mim?"
{user} disse: "Vamos ver se isso dura."
{user} disse: "Hm, legal. Vamos ver."
{user} disse: "Eu vou te observar mais um pouco."
{user} disse: "Obrigado(a). Eu também gosto de você. Acho."
{user} disse: "Confiança é coisa séria aqui."
{user} disse: "Eu não sei se posso dizer o mesmo. Ainda."
{user} disse: "Isso é gentil da sua parte."
{user} disse: "Vou guardar isso."
{user} disse: "Talvez. Com o tempo."
{user} disse: "Eu sou mais desconfiado(a), desculpa."
{user} disse: "Obrigado(a). A gente vai se conhecendo."
{user} disse: "Mostra no voto, que eu acredito."
{user} disse: "Ok. Vou lembrar disso."
{user} disse: "Beleza. Um passo de cada vez."
{user} disse: "Eu aprecio, mas aqui é complicado."
{user} disse: "Hum. Veremos."
{user} disse: "Fico lisonjeado(a)."
{user} disse: "Não sei se mereço, mas obrigado(a)."
{user} disse: "Eu vou te dar o mesmo tempo que você me deu."
{user} disse: "Isso é bom. Muito bom. Mas vamos ver."
{user} disse: "Eu prefiro confiar em atitudes."
{user} disse: "Obrigado(a). Espero não te decepcionar."
{user} disse: "Confiança aqui é artigo de luxo."
{user} disse: "Eu gosto de você. Confiança é outra coisa."
{user} disse: "Talvez amanhã eu te responda."
{user} disse: "Tá bom, {user1}."
{user} disse: "Vamos combinar de ir devagar?"
{user} disse: "Eu sou cauteloso(a), você entende."
{user} disse: "Isso me deixa curioso(a)."
{user} disse: "Hm. Bom saber."
{user} disse: "É recíproco. Mais ou menos."
{user} disse: "Eu não tenho motivo pra desconfiar. Nem pra confiar."
{user} disse: "Vou pensar sobre isso."
{user} disse: "Tá, eu ouvi."
{user} disse: "Não sei se consigo retribuir tão rápido."
{user} disse: "Obrigado(a). Mas aqui dentro eu confio pouco."
{user} disse: "Ok, {user1}. Vamos ver no dia a dia."
{user} disse: "Fico feliz. Vamos seguindo."
{user} disse: "Bom. Muito bom."
{user} disse: "Eu vou lembrar das suas palavras."
{user} disse: "Espero que seja verdade."
{user} disse: "Hm, tá certo."
{user} disse: "Eu prefiro não prometer nada."
{user} disse: "É um bom sinal."
{user} disse: "Você é gentil. Só isso por enquanto."
{user} disse: "Obrigado(a). A gente se fala."
{user} disse: "Vou guardar essa com carinho."
{user} disse: "Eu vou ver como você age."
{user} disse: "Tudo bem, {user1}."
`),
  bad: lines(`
{user} ergueu uma sobrancelha: "Confiar é uma palavra forte, {user1}."
{user} disse: "Engraçado. Eu não confio em você."
{user} disse: "Você diz isso pra todo mundo."
{user} disse: "Hm. O que você quer?"
{user} disse: "Não cola, {user1}."
{user} disse: "Guarda sua confiança pra outro."
{user} disse: "Eu não sei se posso dizer o mesmo."
{user} disse: "Que suspeito você vir com isso agora."
{user} disse: "Confia em mim? Por quê?"
{user} disse: "Isso é jogada."
{user} disse: "Não caio nessa."
{user} disse: "Tá tentando me amolecer?"
{user} disse: "Você acha que me conquista assim?"
{user} disse: "Palavra bonita não vale nada aqui."
{user} disse: "Eu não confio em quem confia rápido."
{user} disse: "Hm. Estranho."
{user} disse: "Traidor(a) adora dizer isso."
{user} disse: "Isso me deixa mais desconfiado(a)."
{user} disse: "Não precisa fingir."
{user} disse: "Guarda pra quem acredita."
{user} disse: "Você tá forçando."
{user} disse: "Confia em mim e vota em mim, né?"
{user} disse: "Eu vi como você fala de mim pelas costas."
{user} disse: "Não, obrigado(a)."
{user} disse: "Eu não te dei motivo pra isso."
{user} disse: "Não sei o que você tá tramando."
{user} disse: "Isso é o que todo Traidor diz."
{user} disse: "Você não me engana."
{user} disse: "Confiança se ganha, não se anuncia."
{user} disse: "Tá, e o que você ganha com isso?"
{user} disse: "Não sou ingênuo(a), {user1}."
{user} disse: "Hm. Anotado. Com desconfiança."
{user} disse: "Você é a última pessoa que eu esperava ouvir isso."
{user} disse: "Não tô pronto(a) pra isso."
{user} disse: "Você fala demais, {user1}."
{user} disse: "Eu vou fingir que acredito."
{user} disse: "Isso não muda meu voto."
{user} disse: "Você tá desesperado(a) por aliados, né?"
{user} disse: "Não confio em ninguém. Muito menos em você."
{user} disse: "Isso é armadilha."
{user} disse: "Não esquece o que você me fez."
{user} disse: "Você tá confundindo as coisas."
{user} disse: "Não acho que seja recíproco."
{user} disse: "Hm, sei."
{user} disse: "Eu vou continuar de olho em você."
{user} disse: "Não compro isso."
{user} disse: "Você tá jogando comigo."
{user} disse: "Guarda essa pra quem cai."
{user} disse: "Não vem com essa."
{user} disse: "Isso cheira a interesse."
{user} disse: "Você não confia em ninguém. Por que eu?"
{user} disse: "Não me pede o mesmo."
{user} disse: "Tá, e amanhã você vota em mim."
{user} disse: "Isso foi tão falso que dói."
{user} disse: "Você devia confiar em quem merece."
{user} disse: "Não, {user1}. Não mesmo."
{user} disse: "Isso é teatro."
{user} disse: "Quem confia em todo mundo não confia em ninguém."
{user} disse: "Não me convence."
{user} disse: "Você tá tentando me recrutar pra algo?"
{user} disse: "Eu vou precisar de muito mais que palavras."
{user} disse: "Não sei o que te fez pensar isso."
{user} disse: "Você se engana fácil."
{user} disse: "Tá bom, tá bom. Mentira, mas tá bom."
{user} disse: "Não confio, e não vou fingir."
{user} disse: "Você é muito rápido(a) pra confiar. Estranho."
{user} disse: "Eu vou lembrar disso quando você votar em mim."
`),
};

export const REPLY_PRAISE = {
  good: lines(`
{user} ficou visivelmente feliz: "Você também, {user1}."
{user} abriu um sorrisão e deu um abraço em {user1}.
{user} corou: "Para, você me deixa sem graça."
{user} disse: "Vindo de você, isso vale ouro."
{user} disse: "Que fofo(a)! Obrigado(a)!"
{user} disse: "Você que é incrível, {user1}."
{user} riu: "Assim eu me apaixono pelo castelo."
{user} disse: "Isso fez meu dia, sério."
{user} disse: "Obrigado(a)! Eu tava precisando ouvir isso."
{user} disse: "Você é um amor, {user1}."
{user} disse: "Olha quem fala! Você arrasa."
{user} disse: "Eu vou guardar esse elogio no coração."
{user} disse: "Você sempre sabe o que dizer."
{user} disse: "Ai, que lindo! Obrigado(a)!"
{user} disse: "Você é gente boa demais."
{user} disse: "Tô todo(a) bobo(a) agora."
{user} disse: "Isso foi a coisa mais gentil do dia."
{user} disse: "Você me deixou vermelho(a)!"
{user} disse: "Obrigado(a)! Retribuo com juros."
{user} disse: "Nossa, que carinho!"
{user} disse: "Você é muito querido(a), {user1}."
{user} disse: "Você também brilha, sabia?"
{user} disse: "Isso me deu uma energia enorme."
{user} disse: "Eu adoro sua sinceridade."
{user} disse: "Você é a melhor companhia daqui."
{user} disse: "Para! Vou chorar!"
{user} disse: "Obrigado(a), de coração."
{user} disse: "Você é muito generoso(a)."
{user} disse: "Isso me motivou pra caramba."
{user} disse: "Você sempre levanta minha moral."
{user} disse: "Eu digo o mesmo de você!"
{user} disse: "Assim você me conquista, {user1}."
{user} disse: "Que elogio lindo. Obrigado(a)."
{user} disse: "Tô me sentindo a estrela do castelo agora."
{user} disse: "Você é um docinho."
{user} disse: "Isso vale mais que qualquer escudo."
{user} disse: "Eu fico sem jeito com elogio, mas obrigado(a)!"
{user} disse: "Você é a luz desse lugar."
{user} disse: "Obrigado(a)! Você me faz bem."
{user} disse: "Eu também te admiro muito."
{user} disse: "Olha, você me deixou feliz."
{user} disse: "Você é um presente, {user1}."
{user} disse: "Obrigado(a)! Vamos juntos até o fim."
{user} disse: "Isso me aqueceu mais que a lareira."
{user} disse: "Você tem um coração bonito."
{user} disse: "Obrigado(a)! Você é demais também."
{user} disse: "Ai, você! Obrigado(a)!"
{user} disse: "Eu vou lembrar disso quando o dia for ruim."
{user} disse: "Que gentileza, {user1}."
{user} disse: "Você me fez sorrir de verdade."
{user} disse: "Você também é incrível, não esquece."
{user} disse: "Isso foi muito especial."
{user} disse: "Você é o(a) melhor, {user1}."
{user} disse: "Eu tô derretido(a) aqui."
{user} disse: "Obrigado(a)! Você tem bom gosto."
{user} riu: "Continua que eu tô gostando."
{user} disse: "Você acabou de ganhar um(a) fã."
{user} disse: "Isso me deixou radiante."
{user} disse: "Você é muito fofo(a)."
{user} disse: "Eu admiro você também, muito."
{user} disse: "Obrigado(a)! Precisava ouvir isso hoje."
{user} disse: "Você é uma pessoa linda por dentro."
{user} disse: "Tô emocionado(a), {user1}."
{user} disse: "Isso é o que eu chamo de amizade."
{user} disse: "Obrigado(a)! Você também brilhou."
{user} disse: "Você é minha pessoa favorita hoje."
{user} disse: "Isso vale mais que o prêmio."
`),
  neutral: lines(`
{user} agradeceu educadamente.
{user} disse "obrigado(a)" sem tirar os olhos do prato.
{user} disse: "Hm. Obrigado(a)."
{user} deu um sorriso curto.
{user} disse: "Valeu."
{user} disse: "Obrigado(a), {user1}."
{user} disse: "Legal da sua parte."
{user} disse: "Beleza, obrigado(a)."
{user} disse: "Hm, gentil."
{user} disse: "Tá, obrigado(a)."
{user} disse: "Isso é simpático."
{user} disse: "Obrigado(a). Você também."
{user} disse: "Não sei o que dizer. Obrigado(a)."
{user} assentiu com a cabeça.
{user} disse: "Hm, legal."
{user} disse: "Tá bom, obrigado(a)."
{user} disse: "Fico feliz que pense assim."
{user} disse: "Obrigado(a). Vou lembrar."
{user} disse: "É bom ouvir isso."
{user} disse: "Hm, você acha?"
{user} disse: "Obrigado(a). Sério?"
{user} disse: "Valeu, mas não precisava."
{user} disse: "Tá bom então."
{user} disse: "Hm, fico lisonjeado(a)."
{user} disse: "Obrigado(a), eu acho."
{user} disse: "Beleza."
{user} disse: "É gentil você dizer isso."
{user} disse: "Tá, e aí?"
{user} disse: "Obrigado(a). Isso é raro aqui."
{user} disse: "Hm. Não esperava."
{user} disse: "Obrigado(a). Mas não exagera."
{user} disse: "Tudo bem, obrigado(a)."
{user} disse: "Legal. Você também é legal."
{user} disse: "Isso é bom de ouvir."
{user} disse: "Ok, anotado."
{user} disse: "Hm, obrigado(a) pelo carinho."
{user} disse: "Não sei se concordo, mas obrigado(a)."
{user} disse: "Obrigado(a). Vou tentar merecer."
{user} disse: "Tá. Obrigado(a)."
{user} disse: "É? Obrigado(a)."
{user} disse: "Muito gentil."
{user} disse: "Obrigado(a). Vamos ver se é verdade."
{user} disse: "Fico sem graça. Obrigado(a)."
{user} disse: "Hm, legal da sua parte."
{user} disse: "Isso é simpático, {user1}."
{user} disse: "Obrigado(a). Mas o jogo continua."
{user} disse: "Não vou negar que gostei."
{user} disse: "Tá bom, você venceu. Obrigado(a)."
{user} disse: "Hm, beleza."
{user} disse: "Obrigado(a), de verdade."
{user} disse: "Você é educado(a)."
{user} disse: "Isso é uma surpresa."
{user} disse: "Obrigado(a). Bom saber."
{user} disse: "Hm. Anotado."
{user} disse: "Tá, fico feliz."
{user} disse: "Obrigado(a). Você é observador(a)."
{user} disse: "Hm, legal."
{user} disse: "Valeu pela força."
{user} disse: "Obrigado(a). Vou lembrar disso."
{user} disse: "É gentil, mas relaxa."
{user} disse: "Isso é bom. Obrigado(a)."
{user} disse: "Hm, você é simpático(a)."
{user} disse: "Obrigado(a). Não esperava hoje."
{user} disse: "Tá bom, tá bom. Obrigado(a)."
{user} disse: "Ok, obrigado(a)."
{user} disse: "Isso é bom, {user1}."
{user} disse: "Obrigado(a). Você também é legal."
`),
  bad: lines(`
{user} desconfiou do elogio: "O que você quer, {user1}?"
{user} disse: "Elogio de você? Suspeito."
{user} disse: "Não vou votar diferente por isso."
{user} disse: "Guarda seus elogios."
{user} disse: "Isso é puxa-saquismo."
{user} disse: "Hm. Interesseiro(a)."
{user} disse: "Não me compra com elogio."
{user} disse: "Você tá forçando."
{user} disse: "Engraçado, ontem você falava mal de mim."
{user} disse: "Não cola, {user1}."
{user} disse: "Que falso(a)."
{user} disse: "Hm. Sei."
{user} disse: "Isso é estratégia, né?"
{user} disse: "Você quer meu voto?"
{user} disse: "Não precisa fingir."
{user} disse: "Elogio de Traidor(a) é assim mesmo."
{user} disse: "Você acha que eu caio nessa?"
{user} disse: "Guarda pra quem gosta."
{user} disse: "Isso não muda nada."
{user} disse: "Não confio em quem elogia demais."
{user} disse: "Tá querendo me amolecer?"
{user} disse: "Hm. Que conveniente."
{user} disse: "Você não me engana com isso."
{user} disse: "Isso tá com cheiro de interesse."
{user} disse: "Não preciso da sua aprovação."
{user} disse: "Obrigado(a)? Não. Desconfiado(a)."
{user} disse: "Isso é o beijo antes da facada."
{user} disse: "Você fala isso pra todo mundo."
{user} disse: "Não vem com essa."
{user} disse: "Eu sei o que você tá fazendo."
{user} disse: "Não caio em elogio barato."
{user} disse: "Sei. E amanhã?"
{user} disse: "Você é muito falso(a), {user1}."
{user} disse: "Não precisa me bajular."
{user} disse: "Isso não me convence de nada."
{user} disse: "Hm. Traidor(a) elogia antes de matar."
{user} disse: "Não gostei. Soou falso."
{user} disse: "Você quer alguma coisa. Fala logo."
{user} disse: "Elogio vazio, {user1}."
{user} disse: "Não me faz rir."
{user} disse: "Você tá tentando se aproximar por quê?"
{user} disse: "Isso é jogada suja."
{user} disse: "Não, obrigado(a)."
{user} disse: "Olha quem resolveu ser gentil."
{user} disse: "Não confio nem no seu sorriso."
{user} disse: "Você se esforça demais."
{user} disse: "Isso não me atinge."
{user} disse: "Hm, tá bom. Mentiroso(a)."
{user} disse: "Guarda pro seu grupinho."
{user} disse: "Você devia ser mais sincero(a)."
{user} disse: "Isso é patético, {user1}."
{user} disse: "Não precisa disso."
{user} disse: "Eu prefiro sinceridade a elogio."
{user} disse: "Você quer me usar."
{user} disse: "Que teatro, hein?"
{user} disse: "Elogio de quem não me suporta. Engraçado."
{user} disse: "Não compro."
{user} disse: "Eu sei ler gente, {user1}."
{user} disse: "Não vou te agradecer."
{user} disse: "Tá, e o que eu faço com isso?"
{user} disse: "Você tá brincando comigo."
{user} disse: "Isso não te salva de nada."
{user} disse: "Mentira bem contada, pelo menos."
{user} disse: "Você é o(a) último(a) que eu queria elogiando."
{user} disse: "Hm. Pouco convincente."
{user} disse: "Nem vem, {user1}."
{user} disse: "Guarda seu mel pra outro."
`),
};

export const REPLY_JOKE = {
  good: lines(`
{user} gargalhou tanto que chamou a atenção do salão.
{user} entrou na brincadeira e devolveu a piada.
{user} chorou de rir: "Para, {user1}!"
{user} riu alto: "Você é impossível!"
{user} deu um tapinha em {user1}: "Palhaço(a)!"
{user} riu até engasgar.
{user} disse, rindo: "Eu te adoro, sério."
{user} riu: "Essa foi boa demais!"
{user} completou a piada e os dois caíram na risada.
{user} gargalhou: "Você tem que fazer stand-up."
{user} riu: "Meu Deus, eu precisava disso."
{user} disse, rindo: "Você salvou meu dia."
{user} riu e imitou {user1}.
{user} riu tanto que derramou o chá.
{user} disse: "Hahaha! Você não presta!"
{user} riu: "Tô com dor na barriga de rir."
{user} disse, rindo: "Você é o(a) mais engraçado(a) daqui."
{user} riu e abraçou {user1}.
{user} disse: "Essa vai pro livro das melhores!"
{user} gargalhou: "Repete, repete!"
{user} riu: "Você é uma figura, {user1}."
{user} riu tanto que todo mundo olhou.
{user} disse: "Hahaha, eu não aguento você!"
{user} riu e fez uma piada ainda pior.
{user} disse, rindo: "Você me mata de rir."
{user} riu: "Olha, essa foi de primeira."
{user} riu com vontade: "Obrigado(a) por isso."
{user} chorou de rir e precisou sentar.
{user} disse: "Você é a alegria desse castelo!"
{user} riu: "Ai, meu Deus. Eu te amo."
{user} riu e bateu palmas.
{user} disse, rindo: "Você é um perigo, {user1}."
{user} gargalhou: "Guarda essa pra mesa!"
{user} riu tanto que perdeu o fôlego.
{user} disse: "Hahaha! Você é demais!"
{user} riu e disse: "Por isso que eu gosto de você."
{user} riu: "Essa foi certeira."
{user} disse: "Você devia ganhar o prêmio só por isso."
{user} riu e contou outra piada.
{user} gargalhou: "Tô morrendo aqui."
{user} riu: "Você é minha terapia."
{user} disse, rindo: "Ai, {user1}, não faz isso comigo."
{user} riu: "Nem o frio aguenta tanta graça."
{user} disse: "Hahaha, anota essa!"
{user} riu tanto que a lareira pareceu mais quente.
{user} riu: "Você é o(a) melhor, sério."
{user} disse: "Hahaha, eu não esperava!"
{user} riu e cutucou {user1}.
{user} gargalhou: "Você é impagável."
{user} riu: "Até eu tô com vergonha de rir tanto."
{user} disse, rindo: "Você me faz esquecer que tô num castelo assombrado."
{user} riu: "Essa foi pro hall da fama."
{user} riu e fez careta de volta.
{user} disse: "Hahaha, você é doido(a)!"
{user} riu: "Eu precisava tanto rir."
{user} disse, rindo: "Você é incrível, {user1}."
{user} gargalhou e pediu outra.
{user} riu: "Você salvou o clima."
{user} riu tanto que acordou metade do castelo.
{user} disse: "Hahaha! Tô chorando!"
{user} riu e não conseguia parar.
{user} riu: "Sua cara falando isso foi o melhor."
{user} disse: "Hahaha, obrigado(a) por existir."
{user} riu alto e contagiou todo mundo.
{user} disse, rindo: "Você tem um dom."
{user} riu: "Tô guardando essa pra contar lá fora."
{user} gargalhou e quase caiu da cadeira.
`),
  neutral: lines(`
{user} deu um sorriso de canto.
{user} riu por educação.
{user} disse: "Hm, engraçado."
{user} deu uma risadinha.
{user} disse: "Boa. Mais ou menos, mas boa."
{user} sorriu sem mostrar os dentes.
{user} disse: "Hehe."
{user} disse: "Tá, essa foi até boa."
{user} riu baixinho.
{user} disse: "Você tá inspirado(a) hoje, hein?"
{user} disse: "Hm, entendi a piada."
{user} deu um meio sorriso.
{user} disse: "Engraçadinho(a)."
{user} disse: "Tá, tá. Foi boa."
{user} disse: "Eu ri por dentro."
{user} disse: "Hm, criativo(a)."
{user} sorriu e voltou a comer.
{user} disse: "Você não perde uma, né?"
{user} disse: "Essa foi razoável."
{user} riu curto.
{user} disse: "Hm, entendi."
{user} disse: "Tá bom, palhaço(a)."
{user} sorriu educadamente.
{user} disse: "Engraçado. Não muito, mas engraçado."
{user} disse: "Hehe, ok."
{user} disse: "Você tá de bom humor."
{user} disse: "Pelo menos alguém tá rindo aqui."
{user} disse: "Hm. Legal."
{user} riu um pouquinho.
{user} disse: "Já ouvi melhores, mas vai."
{user} disse: "Você é engraçado(a), às vezes."
{user} deu uma risada contida.
{user} disse: "Boa, boa."
{user} disse: "Hm, tá."
{user} disse: "Essa foi fraquinha, mas valeu."
{user} disse: "Tá, rendeu um sorriso."
{user} sorriu, meio cansado(a).
{user} disse: "Hehe. Tá bom."
{user} disse: "Hm, que criativo."
{user} disse: "Você não cansa, né?"
{user} disse: "Até que foi boa."
{user} riu de leve.
{user} disse: "Hm, entendi a referência."
{user} disse: "Tá, essa passou."
{user} disse: "Você é uma figura."
{user} sorriu sem muita vontade.
{user} disse: "Pelo menos você tenta."
{user} riu pelo nariz.
{user} disse: "Hm, tá engraçadinho(a) hoje."
{user} disse: "Boa, {user1}."
{user} riu discretamente.
{user} disse: "Hm. Tá."
{user} disse: "Tá, foi bonitinho."
{user} disse: "Hehe, você."
{user} disse: "Essa foi quase boa."
{user} sorriu: "Tá bom, tá bom."
{user} disse: "Engraçado. De certo jeito."
{user} disse: "Hm. Vou rir depois."
{user} disse: "Você tá com o humor em dia."
{user} disse: "Eu entendi, eu entendi."
{user} deu um sorriso rápido.
{user} disse: "Hm, criatividade não falta."
{user} disse: "Tá. Rendeu."
{user} riu de canto de boca.
{user} disse: "Beleza, essa foi."
{user} disse: "Hm, fofo(a)."
{user} disse: "Tá, próxima."
`),
  bad: lines(`
{user} não achou a menor graça.
{user} revirou os olhos: "Isso não é hora, {user1}."
{user} disse: "Não teve graça."
{user} disse: "Você acha isso engraçado?"
{user} disse: "Piada de mau gosto."
{user} ficou sério(a) e saiu da mesa.
{user} disse: "Você tá rindo de quê?"
{user} disse: "Isso foi ofensivo, {user1}."
{user} disse: "Guarda suas piadas."
{user} disse: "Não tô no clima."
{user} disse: "Isso é falta de respeito."
{user} disse: "Engraçado só pra você."
{user} disse: "Hm. Péssima."
{user} disse: "Não força, {user1}."
{user} disse: "Você é inconveniente."
{user} disse: "Que piada sem noção."
{user} disse: "Tem gente morrendo e você fazendo piada?"
{user} disse: "Não ri."
{user} olhou feio para {user1}.
{user} disse: "Você devia pensar antes de falar."
{user} disse: "Isso não tem graça nenhuma."
{user} disse: "Faz piada com você mesmo(a)."
{user} disse: "Tá tentando ser engraçado(a)?"
{user} disse: "Que sem graça."
{user} disse: "Não curti."
{user} disse: "Isso me irritou, {user1}."
{user} disse: "Cala a boca, por favor."
{user} disse: "Você não tem noção de hora."
{user} disse: "Humor ácido demais pra mim."
{user} bufou.
{user} disse: "Isso foi grosseiro."
{user} disse: "Não vou rir disso."
{user} disse: "Você passou do ponto."
{user} disse: "Ninguém riu, {user1}."
{user} disse: "Piada ruim, hora ruim."
{user} disse: "Você acha que tá num show?"
{user} disse: "Não teve graça, e você sabe."
{user} disse: "Hm. Que infantil."
{user} disse: "Faz piada na torre, que lá combina."
{user} disse: "Isso é desrespeito com quem saiu."
{user} disse: "Você é muito sem noção."
{user} ficou em silêncio constrangedor.
{user} disse: "Não é engraçado quando é comigo."
{user} disse: "Guarda pra você."
{user} disse: "Engraçado? Não."
{user} disse: "Isso me ofendeu."
{user} disse: "Para com isso, {user1}."
{user} disse: "Você tá rindo da minha cara?"
{user} disse: "Que piada idiota."
{user} disse: "Não me faz rir, me faz raiva."
{user} disse: "Isso foi baixo."
{user} disse: "Não estou achando graça nenhuma."
{user} disse: "Você é chato(a) até brincando."
{user} disse: "Humor não é seu forte."
{user} disse: "Péssimo momento, {user1}."
{user} disse: "Isso foi pra mim? Sério?"
{user} disse: "Não brinca comigo."
{user} disse: "Isso é tudo menos engraçado."
{user} disse: "Você tá forçando a amizade."
{user} disse: "Não curto esse tipo de piada."
{user} disse: "Engraçadinho(a). Não."
{user} disse: "Você é inconveniente demais."
{user} disse: "Isso aí foi desnecessário."
{user} disse: "Não achei graça e não vou fingir."
{user} disse: "Pelo amor, {user1}."
{user} disse: "Isso foi muito ruim."
{user} disse: "Não tem clima pra isso."
`),
};

export const REPLY_ALLIANCE_YES = lines(`
{user} aceitou na hora: {user} e {user1} agora são aliados.
{user} apertou a mão de {user1}: "Fechado. Eu e você."
{user} sorriu: "Achei que você nunca ia pedir."
{user} disse: "Aliança feita. Um protege o outro."
{user} abraçou {user1}: "Combinado. Até o fim."
{user} disse: "Eu tava esperando por isso. Topo!"
{user} disse: "Sim! Vamos juntos."
{user} disse: "Fechou, {user1}. Somos time."
{user} disse: "Pode contar comigo. Aliança selada."
{user} bateu na mão de {user1}: "Tamo junto!"
{user} disse: "Com você? Sem pensar duas vezes."
{user} disse: "Aceito. E vou honrar."
{user} disse: "Aliança? Claro que sim!"
{user} disse: "Eu tava sentindo falta de um(a) parceiro(a). Topo."
{user} disse: "Fechado. Ninguém vai saber."
{user} disse: "Vamos nessa, {user1}."
{user} disse: "Aceito, e já tenho umas ideias."
{user} disse: "Sim. E prometo não te trair."
{user} disse: "Juntos somos mais fortes. Fechou."
{user} disse: "Pacto feito. Nada de votar um no outro."
{user} sorriu: "Achei que ia ter que te convencer."
{user} disse: "Topo! Você é minha dupla agora."
{user} disse: "Aceito com prazer."
{user} disse: "Combinado. Um cuida do outro."
{user} disse: "Fechado, e fechado de verdade."
{user} disse: "Sim, sim, mil vezes sim."
{user} disse: "Aliança selada. Brinde depois."
{user} disse: "Eu confio em você. Vamos."
{user} disse: "Topo, mas vamos ser discretos."
{user} disse: "Aceito! Finalmente alguém de confiança."
{user} disse: "Vamos até a final juntos."
{user} disse: "Fechado. A gente se fala antes de cada mesa."
{user} disse: "Pode ter certeza que eu tô contigo."
{user} disse: "Aliança? Você leu minha mente."
{user} disse: "Aceito. Vamos mostrar como se joga."
{user} disse: "Eu topo. Você cuida das costas, eu da frente."
{user} disse: "Combinado. Amanhã a gente já joga junto."
{user} disse: "Sim. E ninguém vai nos separar."
{user} disse: "Fechou! Dupla imbatível."
{user} disse: "Aceito sua aliança com o coração."
{user} disse: "Sim! Vamos cuidar um do outro."
{user} disse: "Topo, {user1}. Mas é pra valer."
{user} disse: "Eu tava torcendo pra você pedir."
{user} disse: "Aliança feita. Agora é nós dois."
{user} disse: "Com certeza. Vamos juntos."
{user} disse: "Fechado. Te protejo na mesa."
{user} disse: "Aceito. Você tem minha lealdade."
{user} disse: "Pode contar comigo, parceiro(a)."
{user} disse: "Sim. Vamos jogar em equipe."
{user} disse: "Fechou. E que os Traidores tremam."
{user} disse: "Aceito sem pensar."
{user} disse: "Vamos nessa, juntos até o fim."
{user} disse: "Topo. Você é das minhas pessoas."
{user} disse: "Aliança aceita. Não me decepciona."
{user} disse: "Fechado, e já tô mais tranquilo(a)."
{user} disse: "Eu aceito. Bem-vindo(a) ao meu time."
{user} disse: "Sim. A gente combina muito."
{user} disse: "Topo. Juntos a gente enxerga melhor."
{user} disse: "Aceito, com uma condição: sinceridade sempre."
{user} disse: "Fechou! Vamos nos cuidar."
{user} disse: "Combinado. Palavra dada."
{user} disse: "Sim, {user1}. Somos aliados."
{user} disse: "Aceito. Você me passa segurança."
{user} disse: "Topo. E a gente conversa todo dia."
{user} disse: "Fechado. Ninguém escreve o nome do outro."
{user} disse: "Aceito. Vamos longe."
{user} disse: "Com prazer, {user1}. Aliados."
{user} disse: "Sim. Você é a pessoa certa."
{user} disse: "Fechou, parceria firmada."
{user} disse: "Aceito, e tô feliz com isso."
{user} disse: "Topo! Era o que eu queria ouvir."
{user} disse: "Aliança? Já é!"
{user} disse: "Sim. Pode confiar."
{user} disse: "Fechado. Agora a gente joga junto."
{user} disse: "Aceito, e já te protejo hoje."
{user} disse: "Sim, sim! Vamos."
{user} disse: "Topo. Somos dois contra o caos."
{user} disse: "Fechado, com aperto de mão e tudo."
{user} disse: "Aceito. Você não vai se arrepender."
{user} disse: "Sim, e a gente começa agora."
{user} disse: "Combinado. Lealdade total."
{user} disse: "Topo. Vamos até a última vela."
{user} disse: "Fechado. A partir de hoje, time."
{user} disse: "Aceito, {user1}. Sempre juntos."
{user} disse: "Sim. Te devo essa confiança."
{user} disse: "Fechou! A gente vai se dar bem."
{user} disse: "Aceito. Obrigado(a) por me escolher."
{user} disse: "Topo. Tô dentro."
{user} disse: "Aliança feita, sem volta."
{user} disse: "Sim. Te protejo como protejo a mim."
{user} disse: "Fechado, parceiro(a) de castelo."
{user} disse: "Aceito. A gente se vê na mesa, do mesmo lado."
{user} disse: "Topo, e já tô aliviado(a)."
{user} disse: "Sim. Vamos jogar bonito."
{user} disse: "Combinado. Eu cumpro o que prometo."
{user} disse: "Aceito, e prometo ser leal."
{user} disse: "Fechado. Nós dois contra o mundo."
{user} disse: "Topo. Você é de confiança."
{user} disse: "Sim! Finalmente um(a) aliado(a) de verdade."
{user} disse: "Aceito. Vamos fazer história."
{user} disse: "Fechou. Pode contar comigo pra tudo."
{user} disse: "Topo. Juntos até o fim, não importa o que aconteça."
{user} disse: "Aceito. E já tenho em quem votar."
{user} disse: "Sim, {user1}. Estamos juntos."
{user} disse: "Fechado. Nada de segredos entre nós."
{user} disse: "Aceito. Você me conquistou."
{user} disse: "Topo, sem dúvida nenhuma."
{user} disse: "Aliança feita. Brindamos no café."
{user} disse: "Sim. Juntos a gente sobrevive."
{user} disse: "Aceito, e vou te defender na mesa."
{user} disse: "Fechado. Você e eu."
{user} disse: "Topo. Estava precisando disso."
{user} disse: "Combinado, aliança firme."
{user} disse: "Aceito. Vamos cuidar um do outro."
{user} disse: "Sim, e com todo prazer."
{user} disse: "Fechou. Agora somos um só voto."
{user} disse: "Topo. Me conta tudo que você sabe."
{user} disse: "Aceito, parceiro(a)."
{user} disse: "Sim. Confio em você."
{user} disse: "Fechado. Promessa é dívida."
{user} disse: "Aceito, e que dure até a final."
{user} disse: "Topo! Vamos juntos nessa loucura."
{user} disse: "Sim, e obrigado(a) por confiar."
{user} disse: "Combinado. Você tem meu voto."
{user} disse: "Aceito. Vamos ser a dupla da temporada."
{user} disse: "Fechou. Te espero amanhã no café pra combinar."
{user} disse: "Topo. Eu cuido de você."
{user} disse: "Aliança aceita com alegria."
{user} disse: "Sim. Tô com você."
{user} disse: "Fechado. Não me solta, que eu não te solto."
{user} disse: "Aceito, e já me sinto mais forte."
{user} disse: "Topo. A gente combina demais."
{user} disse: "Sim. Somos aliados agora."
{user} disse: "Fechado. Vamos com tudo."
{user} disse: "Aceito. Pode confiar em mim."
{user} disse: "Topo, {user1}. Vamos longe."
{user} disse: "Sim, e que os outros se cuidem."
{user} disse: "Combinado. A gente se protege."
{user} disse: "Aceito. Você não tá mais sozinho(a)."
{user} disse: "Fechou. Te devo lealdade agora."
{user} disse: "Topo. Juntos, sempre."
{user} disse: "Sim, com o coração aberto."
{user} disse: "Aceito, vamos nessa."
{user} disse: "Fechado. Nossa aliança é segredo."
{user} disse: "Topo. Me ensina seu jogo."
{user} disse: "Sim. Somos parceiros."
{user} disse: "Aceito. Que bom que você veio até mim."
{user} disse: "Fechado. Vamos proteger um ao outro até o fim."
{user} disse: "Topo. Tô feliz que é você."
{user} disse: "Sim, parceiro(a). Vamos."
{user} disse: "Aceito. E vou provar que sou leal."
{user} disse: "Fechou. Aliança pra valer."
{user} disse: "Topo, e já me sinto seguro(a)."
{user} disse: "Sim. Juntos a gente vence."
{user} disse: "Aceito. Você é minha escolha também."
{user} disse: "Fechado, e bem fechado."
{user} disse: "Topo. Vamos jogar juntos."
{user} disse: "Sim. Pode contar comigo sempre."
{user} disse: "Aceito, e que venham as mesas."
{user} disse: "Fechou. Somos um time."
{user} disse: "Topo. Não vou te decepcionar."
{user} disse: "Sim. Eu também te escolho."
{user} disse: "Aceito. Vamos juntos até o final."
{user} disse: "Fechado. A gente se cuida."
{user} disse: "Topo, com alegria."
{user} disse: "Sim, e a partir de agora é pra valer."
{user} disse: "Aceito. Parceria firmada."
{user} disse: "Fechou! Vamos nessa, {user1}."
{user} disse: "Topo. Eu tava precisando de alguém como você."
{user} disse: "Sim. Juntos até o fim."
{user} disse: "Aceito. Estamos juntos."
{user} disse: "Fechado. Te protejo com unhas e dentes."
{user} disse: "Topo. A gente vai se dar muito bem."
{user} disse: "Sim, {user1}. Pode confiar."
{user} disse: "Aceito, e prometo lealdade."
{user} disse: "Fechou. Você é meu time agora."
{user} disse: "Topo. Aliança feita."
{user} disse: "Sim. Vamos cuidar um do outro, sempre."
{user} disse: "Aceito. Obrigado(a) pela confiança."
{user} disse: "Fechado. Somos aliados de verdade."
{user} disse: "Topo, sem pestanejar."
{user} disse: "Sim, e vamos longe."
{user} disse: "Aceito. Conte comigo."
{user} disse: "Fechou, {user1}. Até o fim."
{user} disse: "Topo. Estou dentro."
{user} disse: "Sim, parceria selada."
{user} disse: "Aceito, e com orgulho."
{user} disse: "Até o fim, {user1}. Palavra."
{user} sorriu aliviado(a): "Eu tava esperando isso."
{user} bateu na mão de {user1}: "Time fechado!"
{user} disse: "Fechou. Ninguém mexe com a gente."
{user} disse: "Pode contar comigo, {user1}."
{user} abraçou {user1}: "Aliados. Que alívio."
{user} disse: "Aceito. E cobro lealdade, hein?"
{user} disse: "Juntos. Mas se me trair, acabou."
{user} disse: "Topo. Você é das poucas pessoas que eu confio."
{user} disse: "Sim! Finalmente alguém de confiança."
{user} disse: "Fechado. Nosso segredo."
{user} disse: "Aceito, {user1}. Vamos longe."
{user} disse: "Parceria selada. Sem volta."
{user} disse: "Bora. Eu te protejo."
{user} disse: "Sim. E ai de quem mexer com você."
{user} apertou a mão de {user1}: "Negócio fechado."
`);

export const REPLY_ALLIANCE_NO = lines(`
{user} desconversou: "Vamos ver, {user1}. Ainda é cedo."
{user} recusou com educação: "Prefiro jogar sozinho(a) por enquanto."
{user} disse: "Não sei se é uma boa ideia agora."
{user} disse: "Eu ainda não confio o suficiente."
{user} disse: "Talvez mais pra frente."
{user} disse: "Deixa eu pensar melhor."
{user} disse: "Aliança agora? Muito arriscado."
{user} disse: "Não leva a mal, mas não."
{user} disse: "Eu não faço aliança tão rápido."
{user} disse: "Hm. Vou pensar."
{user} disse: "Agora não, {user1}."
{user} disse: "Eu prefiro não me comprometer."
{user} disse: "Não é nada pessoal. É o jogo."
{user} disse: "Aliança chama atenção. Prefiro não."
{user} disse: "Eu ainda tô te conhecendo."
{user} disse: "Não, obrigado(a)."
{user} disse: "Me pergunta de novo amanhã."
{user} disse: "Eu já tenho meus compromissos."
{user} disse: "Desculpa, mas não."
{user} disse: "Por que eu faria aliança com você?"
{user} disse: "Não sei se posso confiar em você."
{user} disse: "Não agora. Talvez nunca."
{user} disse: "Eu sou um(a) lobo(a) solitário(a)."
{user} disse: "Aliança é coisa séria. Não tô pronto(a)."
{user} disse: "Hm, não sei não."
{user} disse: "Prefiro manter distância."
{user} disse: "Não me leva a mal, {user1}."
{user} disse: "Eu não confio em ninguém ainda."
{user} disse: "Você quer aliança ou quer escudo?"
{user} disse: "Não. Vou jogar do meu jeito."
{user} disse: "Deixa as coisas acontecerem naturalmente."
{user} disse: "Isso é muito rápido pra mim."
{user} disse: "Não sei o que você pretende."
{user} disse: "Eu vou recusar, mas com carinho."
{user} disse: "Não posso, {user1}. Desculpa."
{user} disse: "Hm. Não me convence."
{user} disse: "Não tô procurando aliança."
{user} disse: "Não vou me amarrar a ninguém."
{user} disse: "Por enquanto, não."
{user} disse: "Eu prefiro ver seu jogo primeiro."
{user} disse: "Não sei se você é o que parece."
{user} disse: "Aliança com você? Não sei."
{user} disse: "Me dá um motivo melhor."
{user} disse: "Não. Mas continuo gostando de você."
{user} disse: "Eu tenho outras prioridades."
{user} disse: "Não é o momento."
{user} disse: "Aliança é alvo, {user1}."
{user} disse: "Não vou arriscar."
{user} disse: "Talvez depois da próxima mesa."
{user} disse: "Não curto aliança."
{user} disse: "Deixa pra lá, {user1}."
{user} disse: "Não. Mas obrigado(a) por perguntar."
{user} disse: "Eu não consigo agora."
{user} disse: "Não sei. Tô confuso(a)."
{user} disse: "Não confio em alianças."
{user} disse: "Eu vou pensar e te falo."
{user} disse: "Não. Sem ofensa."
{user} disse: "Hm, melhor não."
{user} disse: "Ainda é muito cedo pra isso."
{user} disse: "Eu não te conheço direito."
{user} disse: "Não. E não insiste."
{user} disse: "Você é legal, mas não."
{user} disse: "Eu já tô comprometido(a) com outra pessoa."
{user} disse: "Prefiro jogar livre."
{user} disse: "Não tô pronto(a) pra confiar assim."
{user} disse: "Talvez amanhã. Hoje não."
{user} disse: "Não vou me comprometer agora."
{user} disse: "Você tá desesperado(a) por aliado?"
{user} disse: "Não me sinto seguro(a) com isso."
{user} disse: "Não, e não é pessoal."
{user} disse: "Deixa eu observar mais um pouco."
{user} disse: "Não sei se a gente combina no jogo."
{user} disse: "Hm. Não."
{user} disse: "Eu não faço acordos assim."
{user} disse: "Não. Mas a gente pode conversar."
{user} disse: "Não vejo vantagem pra mim."
{user} disse: "Não. Eu tenho meu jeito de jogar."
{user} disse: "Não posso me dar esse luxo."
{user} disse: "Não, {user1}. Mas obrigado(a)."
{user} disse: "Isso me parece arriscado."
{user} disse: "Não me convenceu ainda."
{user} disse: "Eu prefiro ficar neutro(a)."
{user} disse: "Não vou entrar em aliança agora."
{user} disse: "Não. E prefiro não explicar."
{user} disse: "Eu não confio em aliança de primeira."
{user} disse: "Vamos ver como você joga primeiro."
{user} disse: "Não, obrigado(a). Estou bem assim."
{user} disse: "Talvez. Mas hoje não."
{user} disse: "Não sei se você é Fiel."
{user} disse: "Não. Tenho meus motivos."
{user} disse: "Eu vou passar essa."
{user} disse: "Hm, prefiro não."
{user} disse: "Não faço aliança com quem mal conheço."
{user} disse: "Não vou arriscar minha pele."
{user} disse: "Não, mas quem sabe um dia."
{user} disse: "Eu não curto grupo fechado."
{user} disse: "Não. Mas relaxa, não é contra você."
{user} disse: "Não agora, {user1}. Desculpa."
{user} disse: "Eu tô bem sozinho(a)."
{user} disse: "Não me sinto confortável."
{user} disse: "Não sei. Preciso pensar."
{user} disse: "Não, e isso fica entre nós."
{user} disse: "Não. Mas continuo do seu lado na mesa."
{user} disse: "Eu não quero ser alvo."
{user} disse: "Hm. Não é pra mim."
{user} disse: "Não. Mas agradeço a lembrança."
{user} disse: "Não vou fechar com ninguém ainda."
{user} disse: "Prefiro esperar."
{user} disse: "Não, não e não."
{user} disse: "Não confio em quem pede rápido."
{user} disse: "Não vou me prender."
{user} disse: "Não. Me desculpa, {user1}."
{user} disse: "Aliança? Talvez com outra pessoa."
{user} disse: "Não sei, você me parece arriscado(a)."
{user} disse: "Não. Vou seguir sozinho(a)."
{user} disse: "Eu prefiro não."
{user} disse: "Não. Mas obrigado(a) pelo carinho."
{user} disse: "Não é o momento certo."
{user} disse: "Hm, vou recusar."
{user} disse: "Não. E não insiste, por favor."
{user} disse: "Eu não confio nem em mim."
{user} disse: "Não. Isso chama muita atenção."
{user} disse: "Não posso agora."
{user} disse: "Não sei o que você quer de mim."
{user} disse: "Não. Mas não somos inimigos."
{user} disse: "Hm, não curti a ideia."
{user} disse: "Não. Eu jogo sozinho(a)."
{user} disse: "Não, desculpa. Não dá."
{user} disse: "Talvez numa próxima."
{user} disse: "Não, mas a gente continua conversando."
{user} disse: "Eu não confio o suficiente em ninguém."
{user} disse: "Não. Sem ressentimentos."
{user} disse: "Eu vou deixar pra depois."
{user} disse: "Não, {user1}. Hoje não."
{user} disse: "Não sei se consigo cumprir."
{user} disse: "Não. Mas continuo sendo seu(sua) amigo(a)."
{user} disse: "Hm, não tô a fim."
{user} disse: "Não, aliança me assusta."
{user} disse: "Não. Prefiro ver no que dá."
{user} disse: "Não posso me comprometer."
{user} disse: "Não. Vou pensar melhor antes."
{user} disse: "Eu fico lisonjeado(a), mas não."
{user} disse: "Não. A gente conversa mais antes."
{user} disse: "Não sei. Talvez."
{user} disse: "Não. Eu não sou de aliança."
{user} disse: "Não. Mas você vai ter meu voto se merecer."
{user} disse: "Ainda não confio o suficiente em você."
{user} disse: "Não. Vamos com calma."
{user} disse: "Hm, prefiro não fechar nada."
{user} disse: "Não, mas obrigado(a) pela oferta."
{user} disse: "Eu tô fora, {user1}."
{user} disse: "Não. Talvez em outro momento."
{user} disse: "Não, sério. Não posso."
{user} disse: "Não. Não me sinto pronto(a)."
{user} disse: "Não, e não é por você."
{user} disse: "Hm, vou deixar passar."
{user} disse: "Não. Eu preciso ver mais."
{user} disse: "Não, obrigado(a). Estou bem sozinho(a)."
{user} disse: "Não. Talvez amanhã eu mude de ideia."
{user} disse: "Não. Aliança é complicada."
{user} disse: "Eu vou recusar dessa vez."
{user} disse: "Não. Mas gostei do convite."
{user} disse: "Não, {user1}. Mas não me esquece."
{user} disse: "Não. Deixa rolar."
{user} disse: "Hm, não. Desculpa."
{user} disse: "Não, mas tô aberto(a) a conversar."
{user} disse: "Não. Não quero me expor."
{user} disse: "Não. Muito cedo."
{user} disse: "Não, obrigado(a). De verdade."
{user} disse: "Não. Eu prefiro não ter amarras."
{user} disse: "Não. E que fique claro: não é pessoal."
{user} disse: "Hm, não sei se confio em você."
{user} disse: "Não. Mas você é legal."
{user} disse: "Não. Eu fico na minha."
{user} disse: "Não. Prefiro ser discreto(a)."
{user} disse: "Não. Me dá um tempo."
{user} disse: "Não. Por enquanto, cada um por si."
{user} disse: "Não. Mas não fica chateado(a)."
{user} disse: "Não. Talvez quando eu te conhecer melhor."
{user} disse: "Não, {user1}. Eu passo."
{user} disse: "Hm. Não, obrigado(a)."
{user} disse: "Não. Tô com a cabeça em outro lugar."
{user} disse: "Não. Eu prefiro observar."
{user} disse: "Não. Deixa pra outra hora."
{user} disse: "Não. Não quero me complicar."
{user} disse: "Não. Mas vou lembrar do convite."
{user} disse: "Não, e fica tudo bem entre a gente."
{user} disse: "Hoje não, {user1}. Talvez amanhã."
{user} disse: "Não confio em ninguém ainda. Nem em você."
{user} disse: "Aliança agora me deixa exposto(a)."
{user} disse: "Gosto de você, mas não. Desculpa."
{user} disse: "Você tá com gente que eu não curto."
{user} disse: "Preciso pensar. Não me cobra."
{user} disse: "Aliança com você? Me dá um motivo."
{user} riu: "Tá rápido demais, {user1}."
{user} disse: "Eu jogo melhor sozinho(a)."
{user} disse: "Não posso prometer o que não sei se cumpro."
{user} disse: "Deixa a gente se conhecer mais primeiro."
{user} disse: "Tô de olho em você ainda. Sem aliança."
{user} disse: "Hoje eu passo, {user1}."
{user} disse, sem graça: "Ai... não sei. Acho que não."
{user} disse: "Se eu fechar com você, viro alvo. Não."
`);
