import { lines } from './lines';

/** Convencer: {user} = quem ouve, {user1} = jogador, {user2} = de quem se fala. */

export const PERSUADE_GUILTY_YES = lines(`
{user} ficou pensativo(a): "Faz sentido, {user1}. Vou ficar de olho em {user2}."
{user} arregalou os olhos: "Eu também achava estranho o jeito de {user2}."
{user} disse: "Você tem razão. {user2} tá me enganando."
{user} disse: "Agora que você falou... é {user2}."
{user} disse: "Meu voto vai pra {user2}. Obrigado(a) por abrir meus olhos."
{user} disse: "{user2}? Nossa. Tudo encaixa."
{user} disse: "Eu tava cego(a). {user2}, claro."
{user} disse: "Tô contigo. {user2} vai sair."
{user} disse: "Você me convenceu. {user2} é suspeito(a)."
{user} disse: "Eu vi a mesma coisa em {user2}."
{user} disse: "Isso explica muita coisa sobre {user2}."
{user} disse: "Pode contar com meu voto em {user2}."
{user} disse: "Eu vou olhar {user2} com outros olhos."
{user} disse: "Tá certo. {user2} não me engana mais."
{user} disse: "Você é esperto(a), {user1}. {user2} faz sentido."
{user} disse: "Eu nunca tinha pensado nisso. {user2}..."
{user} disse: "Juntos a gente derruba {user2}."
{user} disse: "Faz todo sentido. {user2} tá mentindo."
{user} disse: "Eu tava desconfiado(a) de {user2} também."
{user} disse: "Você acabou de confirmar minha suspeita sobre {user2}."
{user} disse: "Vou falar com mais gente sobre {user2}."
{user} disse: "{user2}. Tá decidido."
{user} disse: "Obrigado(a) por me alertar sobre {user2}."
{user} disse: "Você me abriu os olhos pra {user2}."
{user} disse: "Eu sabia que tinha algo errado com {user2}."
{user} disse: "Vamos votar juntos em {user2}."
{user} disse: "Você tá certo(a). É {user2}."
{user} disse: "Eu confio em você. Vou atrás de {user2}."
{user} disse: "Agora eu vejo. {user2} tá manipulando."
{user} disse: "Isso muda tudo. {user2} tá na minha lista."
{user} disse: "Faz sentido demais. {user2} é o(a) Traidor(a)."
{user} disse: "Eu tava sentindo algo, e era {user2}."
{user} disse: "Você tem razão, {user1}. Totalmente."
{user} disse: "Tô convencido(a). {user2} vai cair."
{user} disse: "Uau. {user2}, quem diria."
{user} disse: "Vou prestar muita atenção em {user2} agora."
{user} disse: "Eu confio no seu faro. {user2} é o nome."
{user} disse: "Você juntou as peças que eu não juntei. {user2}."
{user} disse: "Meu Deus, {user2}. Faz sentido."
{user} disse: "Você me convenceu, {user1}. Hoje é {user2}."
{user} disse: "Eu ia votar em outro, mas agora é {user2}."
{user} disse: "Tô chocado(a) com {user2}."
{user} disse: "Você foi convincente. {user2} tá na mira."
{user} disse: "Eu vou te apoiar contra {user2}."
{user} disse: "Isso fecha. {user2} é da torre."
{user} disse: "Agora que você falou, {user2} tá muito estranho(a)."
{user} disse: "Faz sentido o comportamento de {user2}."
{user} disse: "Eu vou puxar votos contra {user2} também."
{user} disse: "Você me deixou preocupado(a) com {user2}."
{user} disse: "{user2} sempre me pareceu calmo(a) demais."
{user} disse: "Pode deixar. {user2} tá marcado(a)."
{user} disse: "Isso é muito sério. Vou vigiar {user2}."
{user} disse: "Você tem argumentos. {user2} tá encrencado(a)."
{user} disse: "Eu acredito em você. {user2} vai sair."
{user} disse: "Tô junto nessa. {user2}."
{user} disse: "Você acabou de ganhar meu voto contra {user2}."
{user} disse: "Eu senti a mesma coisa com {user2} ontem."
{user} disse: "Faz sentido, e me dá raiva de {user2}."
{user} disse: "Eu vou confrontar {user2} na mesa."
{user} disse: "Tá convencido(a). {user2} é meu voto."
{user} disse: "Você é bom(boa) nisso, {user1}. {user2}, então."
{user} disse: "Eu não tinha reparado. Mas é {user2}."
{user} disse: "Agora tudo faz sentido sobre {user2}."
{user} disse: "Obrigado(a). Eu ia confiar em {user2}."
{user} disse: "Você salvou meu voto. {user2}."
{user} disse: "Tô de olho em {user2} a partir de agora."
{user} disse: "Isso me convenceu. {user2} é perigoso(a)."
{user} disse: "Eu vou votar em {user2} sem dó."
{user} disse: "{user2} vai ter que se explicar."
{user} disse: "Faz sentido. E {user2} nem imagina."
{user} disse: "Eu tô contigo contra {user2}."
{user} disse: "Você tem um ótimo olho. {user2}."
{user} disse: "Nossa, {user1}. Eu tava cego(a) com {user2}."
{user} disse: "Vou espalhar isso sobre {user2}."
{user} disse: "Tá bom, me convenceu. {user2}."
{user} disse: "Eu vou te ajudar a tirar {user2}."
{user} disse: "Você me deixou com medo de {user2}."
{user} disse: "{user2} vai pagar."
{user} disse: "Eu vou pensar em {user2} na hora do voto."
{user} disse: "Sabia que não era só eu com {user2}."
{user} disse: "Você disse tudo que eu pensava de {user2}."
{user} disse: "{user2}. Não tem mais dúvida."
{user} disse: "Tá, é {user2}. Vamos juntos."
{user} disse: "Isso é grave. {user2} precisa sair."
{user} disse: "Eu vou ficar colado(a) em {user2}."
{user} disse: "Você tá certo(a), {user1}. É {user2}, com certeza."
{user} disse: "Faz sentido. {user2} sempre desvia."
{user} disse: "Eu acredito em você, e desconfio de {user2}."
{user} disse: "Agora {user2} tá no topo da minha lista."
{user} disse: "Você me convenceu fácil. {user2} é estranho(a)."
{user} disse: "Eu tava sentindo isso sobre {user2} e não sabia explicar."
{user} disse: "Juntos, {user2} não escapa."
{user} disse: "Tô chocado(a). {user2}!"
{user} disse: "{user2} vai ter uma surpresa na mesa."
{user} disse: "Você me deu motivos. {user2} tá fora."
{user} disse: "Faz todo sentido, {user1}. {user2}."
{user} disse: "Vou votar em {user2} e convencer mais gente."
{user} disse: "Tá claro agora. {user2}."
{user} disse: "Eu confio em você. {user2} vai sair."
{user} disse: "Você me convenceu. Obrigado(a)."
{user} disse: "Eu vou te acompanhar contra {user2}."
{user} disse: "{user2} mentiu pra mim também. Agora eu vejo."
{user} disse: "Tá bom. {user2} é o voto."
{user} disse: "Você abriu meus olhos sobre {user2}."
{user} disse: "Eu vi {user2} rindo ontem. Faz sentido."
{user} disse: "{user2}. Vamos tirar."
{user} disse: "Pode deixar que eu cuido de {user2} na mesa."
{user} disse: "Faz sentido. {user2} protegeu alguém que saiu Traidor."
{user} disse: "Você me convenceu, e não foi difícil."
{user} disse: "Eu vou falar com meus aliados sobre {user2}."
{user} disse: "{user2} tá com os dias contados."
{user} disse: "Isso muda meu voto. Obrigado(a)."
{user} disse: "Você acabou de mudar meu jogo. {user2}."
{user} disse: "Eu tava achando {user2} legal. Que decepção."
{user} disse: "{user2} vai ver quem ri por último."
{user} disse: "Faz sentido demais pra ser coincidência."
{user} disse: "Eu acredito em você. Totalmente."
{user} disse: "Eu vou atrás de {user2}."
{user} disse: "Tá convencido(a), {user1}. Tamo junto."
{user} disse: "Você me deixou de cabelo em pé com {user2}."
{user} disse: "{user2}, então. Fechado."
{user} disse: "Eu senti firmeza no que você disse."
{user} disse: "Isso explica a calma de {user2}."
{user} disse: "Eu vou votar em {user2}. Com certeza."
{user} disse: "Faz sentido. Muito sentido."
{user} disse: "Eu tava no escuro. Obrigado(a), {user1}."
{user} disse: "{user2} vai sair na próxima mesa."
{user} disse: "Você é convincente. {user2} tá fora."
{user} disse: "Tô com você nessa, {user1}."
{user} disse: "{user2} não vai me enganar mais."
{user} disse: "Eu vou cobrar {user2} na mesa."
{user} disse: "Faz sentido, e eu tô assustado(a)."
{user} disse: "Isso me convenceu de verdade."
{user} disse: "Vou reparar em cada gesto de {user2}."
{user} disse: "Eu tava achando que era outro. É {user2}."
{user} disse: "Você tá certo(a). E eu fui ingênuo(a)."
{user} disse: "{user2}. Tá marcado(a)."
{user} disse: "Você me convenceu. Vamos juntos."
{user} disse: "Faz sentido. {user2} sempre sabe demais."
{user} disse: "Eu vou te ajudar a provar."
{user} disse: "Agora eu entendo o jogo de {user2}."
{user} disse: "Você me deu clareza. {user2}."
{user} disse: "Eu vou falar com {user2} e ver a reação."
{user} disse: "Tá, é {user2}. Sem mais dúvidas."
{user} disse: "Eu acredito, {user1}. E vou agir."
{user} disse: "Você tá certíssimo(a) sobre {user2}."
{user} disse: "Faz sentido. E me assusta."
{user} disse: "Isso vai mudar a mesa de hoje."
{user} disse: "Tá decidido: {user2}."
{user} disse: "Eu vou ser seu voto contra {user2}."
{user} disse: "{user2} tá fingindo. Agora eu vejo."
{user} disse: "Você me convenceu com fatos."
{user} disse: "Eu vou te seguir nessa."
{user} disse: "{user2} vai ter uma noite difícil na mesa."
{user} disse: "Isso fecha o quebra-cabeça."
{user} disse: "Eu tava com a mesma sensação sobre {user2}."
{user} disse: "Faz sentido. Vou votar em {user2}."
{user} disse: "Você me deu coragem pra votar em {user2}."
{user} disse: "Eu vou avisar meus aliados."
{user} disse: "{user2}. Anotado e confirmado."
{user} disse: "Você tá certo(a). Eu confio no seu jogo."
{user} disse: "Isso muda tudo pra mim."
{user} disse: "Eu vou atrás da verdade sobre {user2}."
{user} disse: "Faz sentido. Muito obrigado(a)."
{user} disse: "Você me convenceu, {user1}. Hoje é {user2}."
{user} disse: "{user2} vai ter que se explicar muito."
{user} disse: "Eu tô do seu lado nessa."
{user} disse: "Faz sentido. {user2} tem cara de torre."
{user} disse: "Eu vou falar na mesa sobre {user2}."
{user} disse: "Isso me pegou. {user2}..."
{user} disse: "Eu tava ignorando os sinais. Obrigado(a)."
{user} disse: "Faz sentido demais. Tô dentro."
{user} disse: "Você me convenceu totalmente."
{user} disse: "{user2} é meu voto de hoje, pode confiar."
{user} disse: "Eu vou te dar razão na mesa."
{user} disse: "Faz sentido. Agora {user2} não me engana."
{user} disse: "Você é muito bom(boa) em ler as pessoas."
{user} disse: "{user2}. Vamos com tudo."
{user} disse: "Eu senti verdade no que você disse."
{user} disse: "Isso me convenceu de um jeito que eu não esperava."
{user} disse: "Eu vou votar com você em {user2}."
{user} disse: "Faz sentido, e eu vou agir."
{user} disse: "{user2} tá fora da minha lista de confiança."
{user} disse: "Você me convenceu, {user1}. Sem dúvida."
{user} disse: "Eu vou ficar atento(a) a {user2}."
{user} disse: "Faz sentido. E {user2} vai sentir."
{user} disse: "Eu tô contigo, {user1}. É {user2}."
{user} disse: "Isso é revelador."
{user} disse: "{user2}? Agora eu entendo."
{user} disse: "Eu vou votar em {user2}. Palavra."
{user} disse: "Faz sentido. Muito obrigado(a) por confiar em mim."
{user} disse: "Você me convenceu, e eu vou espalhar."
{user} disse: "{user2} vai cair. Juntos."
{user} disse: "Eu acredito em cada palavra sua."
{user} disse: "Faz sentido. É {user2}, com certeza."
{user} disse: "Eu vou te acompanhar na mesa."
{user} disse: "{user2}. Não vou esquecer."
{user} disse: "Faz sentido, {user1}. Você tá certo(a)."
{user} disse: "Pronto. {user2} tá na minha lista."
{user} disse: "Obrigado(a), {user1}. Eu tava cego(a) com {user2}."
{user} disse: "Você me abriu os olhos. {user2} hoje."
{user} disse: "Fechou. Vou em {user2} com você."
{user} disse: "Juntando tudo... é {user2} mesmo."
`);

export const PERSUADE_GUILTY_MAYBE = lines(`
{user} ficou em silêncio: "Não sei, {user1}... Mas vou prestar mais atenção em {user2}."
{user} franziu a testa: "Você não é o(a) primeiro(a) a me falar isso de {user2}."
{user} disse: "Hm. Pode ser. Vou observar {user2}."
{user} disse: "Não tenho certeza, mas vou pensar em {user2}."
{user} disse: "Faz um pouco de sentido. Só um pouco."
{user} disse: "Deixa eu observar {user2} mais um dia."
{user} disse: "Você plantou uma dúvida, {user1}."
{user} disse: "Hm. {user2}... talvez."
{user} disse: "Não descarto {user2}."
{user} disse: "Eu vou ficar de olho, mas sem acusar."
{user} disse: "Pode ser que você tenha razão sobre {user2}."
{user} disse: "Vou pensar nisso com calma."
{user} disse: "Você me deixou com a pulga atrás da orelha."
{user} disse: "{user2} vai pro meu radar."
{user} disse: "Não sei se é {user2}, mas vou ver."
{user} disse: "Hm. Não é impossível."
{user} disse: "Talvez. Me dá mais tempo."
{user} disse: "Você pode estar certo(a). Ou não."
{user} disse: "Eu vou reparar mais em {user2}."
{user} disse: "Faz algum sentido. Vou observar."
{user} disse: "Não tô convencido(a), mas tô atento(a)."
{user} disse: "{user2}? Hm. Vou pensar."
{user} disse: "Você me fez duvidar."
{user} disse: "Pode ser, {user1}. Pode ser."
{user} disse: "Vou esperar {user2} dar mais sinais."
{user} disse: "Não sei. {user2} me parece normal."
{user} disse: "Talvez eu esteja confiando demais em {user2}."
{user} disse: "Hm, você tem um ponto."
{user} disse: "Vou colocar {user2} na minha lista. No fim."
{user} disse: "Não tenho certeza, mas não descarto."
{user} disse: "Você me deixou pensativo(a)."
{user} disse: "Vou conversar com {user2} e ver."
{user} disse: "Pode ser. Mas preciso ver com meus olhos."
{user} disse: "Hm. Isso me deixou em dúvida."
{user} disse: "Talvez {user2}. Vou ver na mesa."
{user} disse: "Não sei se acredito, mas vou vigiar."
{user} disse: "Faz sentido em parte."
{user} disse: "Você não é o(a) único(a) que desconfia de {user2}."
{user} disse: "Vou ficar atento(a), prometo."
{user} disse: "Não me convenceu totalmente, mas plantou a semente."
{user} disse: "{user2}? Estranho. Vou pensar."
{user} disse: "Hm, você me deixou em dúvida sobre {user2}."
{user} disse: "Vou ver como {user2} age amanhã."
{user} disse: "Talvez. Mas eu gosto de {user2}."
{user} disse: "Não é certeza, mas é possível."
{user} disse: "Vou olhar {user2} com mais cuidado."
{user} disse: "Hm. Isso me incomodou."
{user} disse: "Pode ser que sim. Veremos."
{user} disse: "Você tem argumentos, mas eu preciso de mais."
{user} disse: "Não sei. Vou pensar até a mesa."
{user} disse: "Hm, {user2} tá estranho(a) mesmo."
{user} disse: "Faz sentido, mas também pode ser coincidência."
{user} disse: "Vou prestar atenção, {user1}."
{user} disse: "Eu vou guardar isso."
{user} disse: "Não sei se é {user2}. Mas agora fico na dúvida."
{user} disse: "Você me deu o que pensar."
{user} disse: "Talvez. Talvez não. Veremos."
{user} disse: "Hm. Vou reparar."
{user} disse: "Não descarto, mas não confirmo."
{user} disse: "Pode ser verdade. Vou investigar."
{user} disse: "Você não tá totalmente errado(a)."
{user} disse: "Vou ficar de antena ligada com {user2}."
{user} disse: "Isso me pegou um pouco."
{user} disse: "Hm. Vou falar com mais gente."
{user} disse: "Não sei. Preciso de prova."
{user} disse: "Você me deixou desconfiado(a). Um pouco."
{user} disse: "Vou pensar melhor sobre {user2}."
{user} disse: "Hm, faz um pouco de sentido, sim."
{user} disse: "Não sei. Mas obrigado(a) por me contar."
{user} disse: "Vou observar {user2} no café."
{user} disse: "Pode ser. Não tenho como negar."
{user} disse: "Hm. Você me deixou curioso(a)."
{user} disse: "Talvez {user2} esteja escondendo algo."
{user} disse: "Vou ficar esperto(a)."
{user} disse: "Não sei se concordo, mas vou pensar."
{user} disse: "Isso é uma possibilidade."
{user} disse: "Hm. Tô em cima do muro."
{user} disse: "Vou dar uma chance pra {user2} se explicar."
{user} disse: "Pode ser, mas não vou acusar ainda."
{user} disse: "Faz sentido. Mas não sei."
{user} disse: "Você tem um ponto, admito."
{user} disse: "Vou olhar os votos de {user2}."
{user} disse: "Hm. Anotado."
{user} disse: "Não sei. Mas também não confio cem por cento em {user2}."
{user} disse: "Vou esperar a mesa pra decidir."
{user} disse: "Talvez você tenha razão, {user1}."
{user} disse: "Hm. Vou pensar no que você disse."
{user} disse: "Não me convenceu, mas me deixou alerta."
{user} disse: "Vou ver com calma."
{user} disse: "Pode ser. Vou sentir melhor."
{user} disse: "Hm, isso muda um pouco minha visão."
{user} disse: "Vou observar sem pressa."
{user} disse: "Talvez sim. Talvez eu esteja errado(a) sobre {user2}."
{user} disse: "Não sei, mas fico mais atento(a)."
{user} disse: "Hm, você me fez pensar."
{user} disse: "Vou ficar de olho, como você pediu."
{user} disse: "Pode ser. Mas quero ver mais."
{user} disse: "Não tô pronto(a) pra votar em {user2}, mas vou pensar."
{user} disse: "Hm. Talvez."
{user} disse: "Você não me convenceu, mas me deixou encucado(a)."
{user} disse: "Vou pensar nisso antes de dormir."
{user} disse: "Pode ser. Vou ver."
{user} disse: "Faz sentido, mas preciso de mais."
{user} disse: "Hm. Não sei o que pensar agora."
{user} disse: "Você me deixou em dúvida, e eu não gosto de dúvida."
{user} disse: "Vou guardar isso na cabeça."
{user} disse: "Talvez {user2} mereça mais atenção."
{user} disse: "Hm. Pode ser."
{user} disse: "Não sei. Mas também não descarto."
{user} disse: "Vou prestar atenção no próximo passo de {user2}."
{user} disse: "Pode ser, {user1}. Vamos ver."
{user} disse: "Hm. Isso me incomoda."
{user} disse: "Vou olhar {user2} de outro jeito, talvez."
{user} disse: "Não sei. Preciso pensar."
{user} disse: "Você pode ter razão. Não sei."
{user} disse: "Vou ver o que {user2} faz."
{user} disse: "Hm. Você é convincente, mas não totalmente."
{user} disse: "Talvez. Deixa eu processar."
{user} disse: "Vou pensar. Prometo."
{user} disse: "Pode ser que {user2} esteja jogando."
{user} disse: "Hm. Vou ficar atento(a)."
{user} disse: "Não sei. Mas você me deixou pensando."
{user} disse: "Vou considerar {user2}."
{user} disse: "Faz sentido, mais ou menos."
{user} disse: "Hm. Não tenho como negar."
{user} disse: "Vou observar sem acusar."
{user} disse: "Talvez. A mesa vai dizer."
{user} disse: "Pode ser. Mas {user2} me parece tranquilo(a)."
{user} disse: "Hm. Vou pensar sobre {user2} com carinho."
{user} disse: "Não sei se é isso, mas vou reparar."
{user} disse: "Você me deixou com uma pulga."
{user} disse: "Vou esperar pra ver."
{user} disse: "Hm. Não é bobagem o que você disse."
{user} disse: "Talvez eu tenha que rever {user2}."
{user} disse: "Vou pensar, {user1}. Vou pensar."
{user} disse: "Pode ser. E se for, eu te dou razão."
{user} disse: "Hm. Vou reparar no café."
{user} disse: "Não sei. Mas obrigado(a)."
{user} disse: "Talvez. {user2} tem sido estranho(a)."
{user} disse: "Vou colocar {user2} em observação."
{user} disse: "Hm. Isso pesa um pouco."
{user} disse: "Pode ser. Mas quero certeza."
{user} disse: "Vou pensar antes de agir."
{user} disse: "Hm. Não descarto nada."
{user} disse: "Talvez você esteja certo(a)."
{user} disse: "Vou prestar atenção, mas sem pressa."
{user} disse: "Pode ser. Vou sentir o clima."
{user} disse: "Hm, você me deixou dividido(a)."
{user} disse: "Vou ver se {user2} se entrega."
{user} disse: "Talvez. Não sei ainda."
{user} disse: "Hm. Vou pensar muito nisso."
{user} disse: "Pode ser. {user2} anda estranho(a)."
{user} disse: "Vou observar e te falo."
{user} disse: "Não sei. Mas agora eu tô atento(a)."
{user} disse: "Hm. Você me fez duvidar de {user2}."
{user} disse: "Talvez. Mas não vou votar ainda."
{user} disse: "Vou pensar e amanhã te respondo."
{user} disse: "Pode ser. Mas com calma."
{user} disse: "Hm. Isso me pegou um pouquinho."
{user} disse: "Vou ficar de olho, só isso."
{user} disse: "Talvez. É uma boa observação."
{user} disse: "Hm. Não sei. Vou ver."
{user} disse: "Pode ser verdade. Vou reparar em {user2}."
{user} disse: "Vou pensar bem antes de acreditar."
{user} disse: "Hm. Talvez {user2} mereça atenção."
{user} disse: "Não sei. Mas fiquei curioso(a)."
{user} disse: "Pode ser. Vamos ver o que acontece."
{user} disse: "Hm. Vou prestar atenção em {user2}."
{user} disse: "Talvez. Não sei."
{user} disse: "Vou observar e decidir depois."
{user} disse: "Hm. Pode ser, {user1}."
{user} disse: "Não descarto, mas não tenho certeza."
{user} disse: "Vou pensar em tudo que você disse."
{user} disse: "Pode ser. Você me deixou encafifado(a)."
{user} disse: "Hm. Vou olhar melhor."
{user} disse: "Talvez. {user2} tá diferente mesmo."
{user} disse: "Vou ficar de olho e te conto."
{user} disse: "Hm. Não sei o que dizer."
{user} disse: "Pode ser. Mas eu ainda tenho dúvidas."
{user} disse: "Vou pensar, mas não prometo nada."
{user} disse: "Hm. Isso me deu o que pensar."
{user} disse: "Talvez. Vou observar {user2} de perto."
{user} disse: "Pode ser. Veremos na mesa."
{user} disse: "Hm. Vou reparar mais."
{user} disse: "Não sei. Mas agora fico com um pé atrás."
{user} disse: "Vou pensar, {user1}."
{user} disse: "Pode ser. {user2} é difícil de ler."
{user} disse: "Hm. Talvez eu esteja cego(a)."
{user} disse: "Vou observar sem julgar."
{user} disse: "Talvez. Obrigado(a) pelo alerta."
{user} disse: "Hm. Vou pensar no caso de {user2}."
{user} mordeu o lábio: "Não tinha pensado nisso, {user1}."
{user} disse: "Você plantou uma dúvida. Sobre {user2}."
{user} disse: "Vou conversar com {user2} e te falo."
{user} disse: "Pode ser, {user1}. Mas preciso de mais."
{user} disse: "{user2}? Talvez. Tá no meu radar agora."
{user} disse: "Não descarto {user2}. Mas não fecho ainda."
{user} disse: "Hm. {user2} teve umas atitudes estranhas mesmo."
{user} disse: "Deixa eu dormir com essa ideia, {user1}."
{user} disse: "Você é convincente. Mas {user2}... não sei."
{user} disse: "Vou observar {user2} na próxima mesa."
{user} disse: "Talvez. Mas se você errar, a culpa é sua."
{user} disse: "Meio a meio sobre {user2}. Por enquanto."
`);

export const PERSUADE_GUILTY_NO = lines(`
{user} discordou na hora: "{user2}? Você está vendo coisa, {user1}."
{user} desconfiou: "Por que você quer tanto que eu desconfie de {user2}?"
{user} disse: "Não. {user2} é Fiel, eu confio."
{user} disse: "Você tá errado(a) sobre {user2}."
{user} disse: "Que papo é esse? {user2} é gente boa."
{user} disse: "Não vou cair nessa, {user1}."
{user} disse: "Você tá tentando me usar contra {user2}?"
{user} disse: "Isso é intriga. Não gostei."
{user} disse: "{user2} nunca me deu motivo pra desconfiar."
{user} disse: "Agora eu desconfio de você, {user1}."
{user} disse: "Não. E não fala mais disso."
{user} disse: "{user2} é meu(minha) amigo(a). Cuidado."
{user} disse: "Você quer queimar {user2}? Por quê?"
{user} disse: "Isso não faz sentido nenhum."
{user} disse: "Não acredito em você."
{user} disse: "Você tá desviando atenção de si mesmo(a)."
{user} disse: "{user2}? Nunca. Você tá louco(a)."
{user} disse: "Eu confio mais em {user2} do que em você."
{user} disse: "Isso é jogada de Traidor(a)."
{user} disse: "Não vou votar em {user2} por fofoca."
{user} disse: "Você não tem prova nenhuma."
{user} disse: "{user2} é das pessoas mais leais daqui."
{user} disse: "Por que você tá atacando {user2}?"
{user} disse: "Isso me deixou com raiva, {user1}."
{user} disse: "Não. {user2} tá do nosso lado."
{user} disse: "Você tá manipulando, e eu vi."
{user} disse: "Eu vou contar isso pra {user2}."
{user} disse: "Não me mete nas suas armações."
{user} disse: "{user2} é inocente. Ponto."
{user} disse: "Você tá com medo de {user2}? Por quê?"
{user} disse: "Isso não me convence nem um pouco."
{user} disse: "Não. {user2} me ajudou quando ninguém ajudou."
{user} disse: "Você devia olhar pra outro lado."
{user} disse: "Isso é invenção sua."
{user} disse: "Eu não vou votar em {user2}. Nunca."
{user} disse: "Você tá me decepcionando, {user1}."
{user} disse: "Quem desconfia de {user2} não conhece {user2}."
{user} disse: "Não. E agora tô de olho em você."
{user} disse: "Isso tem cheiro de armação."
{user} disse: "{user2}? Não mesmo."
{user} disse: "Você quer me colocar contra meu(minha) aliado(a)?"
{user} disse: "Não gosto dessa conversa."
{user} disse: "Isso é o que um Traidor faria, {user1}."
{user} disse: "Não. Pode esquecer."
{user} disse: "Eu não acredito numa palavra."
{user} disse: "{user2} é Fiel. Eu sinto."
{user} disse: "Você tá errado(a) e vai ver."
{user} disse: "Não caio nessa, {user1}."
{user} disse: "Por que você quer {user2} fora?"
{user} disse: "Isso é suspeito vindo de você."
{user} disse: "{user2} não, {user1}. Escolhe outro alvo."
{user} disse: "Você não me engana."
{user} disse: "Eu vou defender {user2} na mesa."
{user} disse: "Não. Você tá forçando."
{user} disse: "Isso é fofoca barata."
{user} disse: "Não vou entrar nessa."
{user} disse: "{user2} é leal. Diferente de algumas pessoas."
{user} disse: "Você tá tentando me isolar?"
{user} disse: "Não. {user2} é a pessoa mais honesta daqui."
{user} disse: "Isso me faz desconfiar de você."
{user} disse: "Você tá com inveja de {user2}?"
{user} disse: "Não. E não insiste."
{user} disse: "Eu confio em {user2}. Não em você."
{user} disse: "Você tá plantando dúvida. Traidor faz isso."
{user} disse: "{user2}? Faz me rir."
{user} disse: "Não. Nem pensar."
{user} disse: "Isso é ridículo, {user1}."
{user} disse: "Você devia ter vergonha."
{user} disse: "Não, e eu vou lembrar dessa conversa."
{user} disse: "{user2} é inocente. Você que é suspeito(a)."
{user} disse: "Isso não tem pé nem cabeça."
{user} disse: "Não vou votar com você contra {user2}."
{user} disse: "Você tá jogando sujo."
{user} disse: "Não. {user2} é meu voto de confiança."
{user} disse: "Por que tanta vontade de tirar {user2}?"
{user} disse: "Não. Você tá enganado(a)."
{user} disse: "Isso é armação e eu vou descobrir."
{user} disse: "{user2}? De jeito nenhum."
{user} disse: "Não. E espero que você mude de ideia."
{user} disse: "Você não me convence."
{user} disse: "Eu conheço {user2}. Você não."
{user} disse: "Não. Isso é invenção."
{user} disse: "Você tá desesperado(a)?"
{user} disse: "Não vou acusar um Fiel por sua causa."
{user} disse: "{user2} é inocente, e eu vou provar."
{user} disse: "Não. Você perdeu minha confiança agora."
{user} disse: "Isso me deixou triste, {user1}."
{user} disse: "Não. Olha pra outro lado."
{user} disse: "Você tá sendo injusto(a) com {user2}."
{user} disse: "Não caio nesse papo."
{user} disse: "{user2}? Você tá delirando."
{user} disse: "Não. E eu vou avisar {user2}."
{user} disse: "Você tá tentando me manipular."
{user} disse: "Não. Muito menos por você."
{user} disse: "Isso é baixo, {user1}."
{user} disse: "Não acredito. Nem um pouco."
{user} disse: "Você devia desconfiar de si mesmo(a)."
{user} disse: "Não. {user2} é da minha confiança."
{user} disse: "Isso não vai colar."
{user} disse: "Você tá errado(a). Totalmente."
{user} disse: "Não vou votar em {user2}. Esquece."
{user} disse: "Você tá com algum problema com {user2}?"
{user} disse: "Não. Isso é intriga."
{user} disse: "{user2} é leal. Ponto final."
{user} disse: "Você quer um bode expiatório."
{user} disse: "Não. E não gostei do seu tom."
{user} disse: "Isso é muito suspeito, {user1}."
{user} disse: "Não. {user2} é inocente."
{user} disse: "Você quer me usar como arma."
{user} disse: "Não vou ser usado(a)."
{user} disse: "{user2}? Pff."
{user} disse: "Não. E pensa bem no que você tá fazendo."
{user} disse: "Você tá atirando no escuro."
{user} disse: "Não. {user2} tá acima de suspeita pra mim."
{user} disse: "Isso me faz pensar mal de você."
{user} disse: "Não. Chega de fofoca."
{user} disse: "{user2} é das nossas. Você não sei."
{user} disse: "Não. Nem vem."
{user} disse: "Você tá sendo manipulado(a), {user1}."
{user} disse: "Não. E cuidado com o que você espalha."
{user} disse: "{user2}? Nunca. Jamais."
{user} disse: "Não. Você perdeu a noção."
{user} disse: "Isso é muito estranho vindo de você."
{user} disse: "Não. E {user2} vai saber disso."
{user} disse: "Você tá errando o alvo feio."
{user} disse: "Não vou te ajudar nisso."
{user} disse: "{user2} é inocente e você sabe."
{user} disse: "Não. Muda de assunto."
{user} disse: "Você tá com medo de ser pego(a)?"
{user} disse: "Não. {user2} tem minha confiança."
{user} disse: "Isso é tão óbvio, {user1}. Não caio."
{user} disse: "Não. E agora você tá no meu radar."
{user} disse: "{user2}? Você tá brincando."
{user} disse: "Não. Chega."
{user} disse: "Você tá jogando comigo, e eu não gosto."
{user} disse: "Não. {user2} não é Traidor(a)."
{user} disse: "Isso não me desce."
{user} disse: "Não. Você tá precipitado(a)."
{user} disse: "{user2} é Fiel, e eu defendo."
{user} disse: "Não. Me deixa fora disso."
{user} disse: "Você tá sendo leviano(a)."
{user} disse: "Não. Pensa melhor, {user1}."
{user} disse: "{user2} é inocente, eu garanto."
{user} disse: "Não. Você tá forçando a barra."
{user} disse: "Isso não tem fundamento."
{user} disse: "Não. E eu tô chateado(a)."
{user} disse: "{user2}? Não, {user1}."
{user} disse: "Não. Você precisa de mais que isso."
{user} disse: "Isso é armadilha, e eu não vou cair."
{user} disse: "Não. {user2} é meu(minha) aliado(a)."
{user} disse: "Você tá jogando sujo com {user2}."
{user} disse: "Não. Nem se você implorar."
{user} disse: "{user2} tá limpo(a) pra mim."
{user} disse: "Não. Isso me deixou com raiva."
{user} disse: "Você tá me decepcionando."
{user} disse: "Não. E eu vou lembrar disso."
{user} disse: "{user2}? Faz favor."
{user} disse: "Não. Você não tem argumento."
{user} disse: "Isso é só achismo."
{user} disse: "Não. {user2} é leal."
{user} disse: "Você tá procurando briga."
{user} disse: "Não. E agora eu desconfio de você."
{user} disse: "{user2} é o(a) último(a) que eu acusaria."
{user} disse: "Não. Me poupe."
{user} disse: "Você tá errado(a), e eu vou mostrar."
{user} disse: "Não. Nem vou discutir."
{user} disse: "{user2} tem meu respeito."
{user} disse: "Não. Você tá sendo cruel."
{user} disse: "Isso é demais, {user1}."
{user} disse: "Não. E pensa no que você tá fazendo."
{user} disse: "{user2}? Não, obrigado(a)."
{user} disse: "Não. Você não me convence."
{user} disse: "Isso é inveja de {user2}, só pode."
{user} disse: "Não. {user2} tá comigo."
{user} disse: "Você tá desesperado(a) por um nome."
{user} disse: "Não. Escolhe outro."
{user} disse: "{user2} é inocente. Eu sei."
{user} disse: "Não. Você tá se entregando."
{user} disse: "Isso é suspeito demais."
{user} disse: "Não. Nem um pouco."
{user} disse: "{user2}? Esquece."
{user} disse: "Não. E não me procura mais com isso."
{user} disse: "Você tá errado(a), {user1}."
{user} disse: "Não. Eu vou proteger {user2}."
{user} disse: "Isso é armação, certeza."
{user} disse: "Não. {user2} é Fiel, e você vai ver."
{user} disse: "Você tá procurando confusão."
{user} disse: "Não. Nunca."
{user} disse: "{user2} merece mais respeito."
{user} disse: "Não. Você tá sendo injusto(a)."
{user} disse: "Isso me faz desconfiar das suas intenções."
{user} disse: "Não. E ponto."
{user} riu: "{user2}? Você tá delirando, {user1}."
{user} disse: "Conheço {user2} melhor que você. Não é."
{user} disse: "Isso tem cara de armação, {user1}."
{user} cruzou os braços: "Não vou cair nessa."
{user} disse: "Por que você tem tanta pressa de tirar {user2}?"
{user} disse: "Eu apostaria em qualquer um antes de {user2}."
{user} disse: "Esquece. {user2} tá comigo."
{user} disse: "Você acusando {user2}? Suspeito é você."
{user} disse: "Nada disso me convence, {user1}."
{user} disse: "Não. E para de insistir."
{user} disse: "Se eu votar em {user2}, você me paga."
{user} disse: "{user2} é das poucas pessoas limpas aqui."
`);

export const PERSUADE_INNOCENT_YES = lines(`
{user} assentiu: "Tá bom, {user1}. Vou dar um voto de confiança pra {user2}."
{user} suspirou: "Talvez eu estivesse sendo injusto(a) com {user2}."
{user} disse: "Você tem razão. {user2} não é Traidor(a)."
{user} disse: "Tá, vou tirar {user2} da minha lista."
{user} disse: "Faz sentido. {user2} é gente boa."
{user} disse: "Eu confio em você, então confio em {user2}."
{user} disse: "Você me convenceu. {user2} tá limpo(a)."
{user} disse: "Eu tava errado(a) sobre {user2}."
{user} disse: "Tá certo. Não voto em {user2}."
{user} disse: "Obrigado(a). Eu ia cometer um erro."
{user} disse: "Você abriu meus olhos sobre {user2}."
{user} disse: "Faz sentido. {user2} é leal."
{user} disse: "Vou defender {user2} também."
{user} disse: "Você tem razão, {user1}."
{user} disse: "{user2} merece uma chance."
{user} disse: "Tá, {user2} saiu da minha lista."
{user} disse: "Eu vou pedir desculpas a {user2}."
{user} disse: "Você me convenceu. Vou proteger {user2}."
{user} disse: "Faz sentido. {user2} sempre foi sincero(a)."
{user} disse: "Eu tava desconfiando à toa."
{user} disse: "Tá bom. {user2} é Fiel."
{user} disse: "Você me deu motivos. Confio em {user2}."
{user} disse: "Eu vou reconsiderar {user2}."
{user} disse: "Você tem um bom argumento."
{user} disse: "Tá, não vou votar em {user2}."
{user} disse: "Eu tava sendo paranoico(a)."
{user} disse: "Faz sentido. {user2} ajudou na missão."
{user} disse: "Você me convenceu, {user1}."
{user} disse: "Eu confio no seu julgamento."
{user} disse: "{user2} tá limpo(a) pra mim agora."
{user} disse: "Vou olhar {user2} com carinho."
{user} disse: "Tá, você tem razão."
{user} disse: "Eu vou defender {user2} na mesa."
{user} disse: "Faz sentido. Eu fui injusto(a)."
{user} disse: "Você me acalmou sobre {user2}."
{user} disse: "Obrigado(a). Eu tava confuso(a)."
{user} disse: "Tá bom, vou confiar em {user2}."
{user} disse: "Você é bom(boa) em ler pessoas."
{user} disse: "Faz sentido. {user2} nunca me fez mal."
{user} disse: "Eu vou mudar meu voto."
{user} disse: "{user2} merece minha confiança."
{user} disse: "Você me convenceu fácil."
{user} disse: "Tá, {user2} é dos nossos."
{user} disse: "Eu acredito em você, {user1}."
{user} disse: "Faz sentido. Vou proteger {user2}."
{user} disse: "Você tem razão. Eu vi {user2} chorar."
{user} disse: "Tá certo. {user2} é inocente."
{user} disse: "Eu vou deixar {user2} em paz."
{user} disse: "Obrigado(a) por me alertar."
{user} disse: "Você me fez ver o outro lado."
{user} disse: "Faz sentido, e eu tô aliviado(a)."
{user} disse: "Tá. {user2} tá fora da minha mira."
{user} disse: "Eu confio em você e em {user2}."
{user} disse: "Você me convenceu, e eu agradeço."
{user} disse: "Faz sentido. {user2} é tranquilo(a)."
{user} disse: "Eu vou dar uma chance pra {user2}."
{user} disse: "Tá bom, {user1}. Você venceu."
{user} disse: "Eu tava pegando pesado com {user2}."
{user} disse: "Faz sentido. Vou conversar com {user2}."
{user} disse: "Você me tirou uma dúvida."
{user} disse: "Tá, {user2} é leal."
{user} disse: "Eu vou te ouvir dessa vez."
{user} disse: "Faz sentido. {user2} não tem perfil."
{user} disse: "Você me deixou mais tranquilo(a)."
{user} disse: "Tá certo, vou confiar."
{user} disse: "Eu vou apoiar {user2}."
{user} disse: "Faz sentido. Obrigado(a), {user1}."
{user} disse: "Você é convincente."
{user} disse: "Tá, {user2} não vai ter meu voto."
{user} disse: "Eu mudei de ideia sobre {user2}."
{user} disse: "Faz sentido, {user2} é do bem."
{user} disse: "Você me ajudou a pensar melhor."
{user} disse: "Tá bom. Confio em {user2}."
{user} disse: "Eu vou retirar minha desconfiança."
{user} disse: "Faz sentido. {user2} é inocente."
{user} disse: "Você tem razão, e eu tava errado(a)."
{user} disse: "Tá, vou proteger {user2} também."
{user} disse: "Eu confio em você, então tudo bem."
{user} disse: "Faz sentido. {user2} é leal ao grupo."
{user} disse: "Você me convenceu com calma."
{user} disse: "Tá certo, {user2} fica."
{user} disse: "Eu tava desconfiado(a) sem motivo."
{user} disse: "Faz sentido. Vou votar em outro."
{user} disse: "Você é um(a) bom(boa) advogado(a) de {user2}."
{user} disse: "Tá bom, {user2} merece."
{user} disse: "Eu vou olhar pra outro lado."
{user} disse: "Faz sentido. {user2} me parece sincero(a) agora."
{user} disse: "Você me fez repensar."
{user} disse: "Tá, confio em {user2}."
{user} disse: "Eu vou te acompanhar na defesa."
{user} disse: "Faz sentido. Obrigado(a) pela calma."
{user} disse: "Você tem razão sobre {user2}."
{user} disse: "Tá bom. Vou proteger."
{user} disse: "Eu vou mudar meu olhar sobre {user2}."
{user} disse: "Faz sentido. E me alivia."
{user} disse: "Você me convenceu, e bem."
{user} disse: "Tá, {user2} é inocente pra mim."
{user} disse: "Eu vou confiar no seu instinto."
{user} disse: "Faz sentido. {user2} é gente de bem."
{user} disse: "Você me acalmou."
{user} disse: "Tá certo, {user1}."
{user} disse: "Eu vou deixar {user2} de fora."
{user} disse: "Faz sentido. Não vou mais desconfiar."
{user} disse: "Você tem razão. Eu fui precipitado(a)."
{user} disse: "Tá bom. {user2} fica comigo."
{user} disse: "Eu vou falar bem de {user2} na mesa."
{user} disse: "Faz sentido. Confio."
{user} disse: "Você me deu clareza."
{user} disse: "Tá, não vou mais atacar {user2}."
{user} disse: "Eu vou te ajudar a proteger {user2}."
{user} disse: "Faz sentido. {user2} é Fiel, sim."
{user} disse: "Você me convenceu. Obrigado(a)."
{user} disse: "Tá bom, vou pensar diferente."
{user} disse: "Eu tava enganado(a)."
{user} disse: "Faz sentido. {user2} é confiável."
{user} disse: "Você é bom(boa) nisso, {user1}."
{user} disse: "Tá, {user2} merece paz."
{user} disse: "Eu vou me desculpar com {user2}."
{user} disse: "Faz sentido. Vou votar diferente."
{user} disse: "Você me convenceu totalmente."
{user} disse: "Tá, confio no que você diz."
{user} disse: "Eu vou deixar {user2} fora do meu voto."
{user} disse: "Faz sentido. {user2} é gente boa demais."
{user} disse: "Você me acalmou o coração."
{user} disse: "Tá bom, {user2} tá limpo(a)."
{user} disse: "Eu vou defender {user2} com você."
{user} disse: "Faz sentido. Eu errei o alvo."
{user} disse: "Você tem argumentos bons."
{user} disse: "Tá certo. {user2} fica."
{user} disse: "Eu confio. Obrigado(a)."
{user} disse: "Faz sentido. {user2} é inocente, sim."
{user} disse: "Você me fez mudar de ideia."
{user} disse: "Tá, {user2} não é ameaça."
{user} disse: "Eu vou olhar pra outros suspeitos."
{user} disse: "Faz sentido. Vou apoiar {user2}."
{user} disse: "Você é muito convincente, {user1}."
{user} disse: "Tá bom. {user2} tem meu voto de confiança."
{user} disse: "Eu vou te dar razão."
{user} disse: "Faz sentido. Obrigado(a) pelo toque."
{user} disse: "Você me convenceu de verdade."
{user} disse: "Tá, confio em {user2} agora."
{user} disse: "Eu vou reavaliar tudo."
{user} disse: "Faz sentido. {user2} não teria coragem."
{user} disse: "Você me tirou um peso."
{user} disse: "Tá bom, {user1}. Obrigado(a)."
{user} disse: "Eu vou defender {user2} amanhã."
{user} disse: "Faz sentido. Não vou mais duvidar."
{user} disse: "Você me convenceu com o coração."
{user} disse: "Tá, {user2} é inocente. Anotado."
{user} disse: "Eu vou confiar em vocês dois."
{user} disse: "Faz sentido. {user2} tá do nosso lado."
{user} disse: "Você me convenceu e eu agradeço."
{user} disse: "Tá certo. Vou mudar meu voto."
{user} disse: "Eu vou deixar {user2} tranquilo(a)."
{user} disse: "Faz sentido. {user2} é honesto(a)."
{user} disse: "Você me fez ver com outros olhos."
{user} disse: "Tá bom, vou confiar em {user2}."
{user} disse: "Eu tava enganado(a), você tem razão."
{user} disse: "Faz sentido. Vou proteger {user2} na mesa."
{user} disse: "Você é muito sensato(a)."
{user} disse: "Tá, {user2} tá do lado certo."
{user} disse: "Eu vou te ouvir."
{user} disse: "Faz sentido. Obrigado(a) por abrir meus olhos."
{user} disse: "Você me convenceu, {user1}. Pode deixar."
{user} disse: "Tá certo. {user2} merece confiança."
{user} disse: "Eu vou apoiar {user2} na mesa."
{user} disse: "Faz sentido. {user2} não é quem eu pensava."
{user} disse: "Você me acalmou sobre {user2}."
{user} disse: "Tá bom. Mudei de ideia."
{user} disse: "Eu vou confiar em {user2}. Por você."
{user} disse: "Faz sentido. {user2} é gente fina."
{user} disse: "Você me convenceu, e tô aliviado(a)."
{user} disse: "Tá, {user2} fica de fora."
{user} disse: "Eu vou te acompanhar."
{user} disse: "Faz sentido. {user2} é leal."
{user} disse: "Você é persuasivo(a), {user1}."
{user} disse: "Tá bom. {user2} é inocente."
{user} disse: "Eu vou mudar de alvo."
{user} disse: "Faz sentido. Obrigado(a)."
{user} disse: "Você me convenceu com fatos."
{user} disse: "Tá certo, {user2} é dos nossos."
{user} disse: "Eu vou confiar. Você tem razão."
{user} disse: "Faz sentido. {user2} merece ficar."
{user} disse: "Você me fez pensar diferente."
{user} disse: "Tá bom, {user1}. Confio em {user2}."
{user} disse: "Eu vou proteger {user2} contigo."
{user} disse: "Faz sentido. Você tá certo(a)."
{user} disse: "Tá bom, {user2} sai da minha lista."
{user} disse: "Você me convenceu. {user2} é Fiel."
{user} disse: "Faz sentido. Eu tava vendo coisa em {user2}."
{user} disse: "Ok, {user1}. Confio em {user2} por você."
{user} disse: "Talvez eu tenha sido cruel com {user2}."
{user} disse: "Vou pedir desculpa a {user2}."
{user} disse: "Você tem razão. {user2} não teria como."
{user} disse: "Mudei de ideia sobre {user2}. Obrigado(a)."
{user} disse: "Então vou olhar pra outro lado. Não pra {user2}."
{user} disse: "Pensando bem... {user2} é inofensivo(a)."
{user} disse: "Beleza. Meu voto não vai em {user2}."
{user} disse: "Você tem bom olho. Confio em {user2} também."
{user} disse: "Tá certo. Retiro o que disse de {user2}."
{user} disse: "Acho que eu tava com raiva, não com razão."
{user} disse: "{user2} tá salvo(a) comigo."
{user} disse: "Fechado. {user2} fica."
`);

export const PERSUADE_INNOCENT_MAYBE = lines(`
{user} coçou a cabeça: "Pode ser, {user1}. Vou olhar {user2} com outros olhos."
{user} respondeu: "Ainda não estou convencido(a) sobre {user2}. Mas vou pensar."
{user} disse: "Hm. Talvez {user2} seja Fiel mesmo."
{user} disse: "Vou dar mais uma chance pra {user2}."
{user} disse: "Pode ser. Mas não tiro {user2} da lista ainda."
{user} disse: "Você me deixou em dúvida."
{user} disse: "Talvez eu tenha exagerado com {user2}."
{user} disse: "Vou observar {user2} mais um pouco."
{user} disse: "Hm. Não sei se concordo, mas vou pensar."
{user} disse: "Pode ser que você tenha razão."
{user} disse: "Vou pensar em {user2} com calma."
{user} disse: "Talvez. {user2} ainda me incomoda."
{user} disse: "Hm. Vou ver o que {user2} faz."
{user} disse: "Não sei. Você me deixou confuso(a)."
{user} disse: "Pode ser que {user2} seja inocente."
{user} disse: "Vou segurar meu voto em {user2}. Por enquanto."
{user} disse: "Talvez eu esteja errado(a) sobre {user2}."
{user} disse: "Hm. Você tem um ponto."
{user} disse: "Vou pensar melhor."
{user} disse: "Pode ser. Mas preciso ver com meus olhos."
{user} disse: "Talvez. Não tenho certeza."
{user} disse: "Hm. Vou reconsiderar."
{user} disse: "Não sei se confio em {user2}, mas vou tentar."
{user} disse: "Pode ser. Vou observar."
{user} disse: "Você me fez duvidar da minha suspeita."
{user} disse: "Hm. Vou esperar mais um dia."
{user} disse: "Talvez {user2} mereça o benefício da dúvida."
{user} disse: "Pode ser. Mas fico atento(a)."
{user} disse: "Vou pensar no que você disse."
{user} disse: "Hm. Não tô totalmente convencido(a)."
{user} disse: "Talvez. {user2} tem dias estranhos."
{user} disse: "Pode ser que eu esteja sendo injusto(a)."
{user} disse: "Vou conversar com {user2} antes de decidir."
{user} disse: "Hm. Você me deixou pensativo(a)."
{user} disse: "Talvez. Mas não prometo nada."
{user} disse: "Pode ser. Vamos ver."
{user} disse: "Não sei. Vou pensar até a mesa."
{user} disse: "Hm. {user2} pode ser inocente, sim."
{user} disse: "Talvez eu dê um tempo pra {user2}."
{user} disse: "Pode ser. Você é convincente."
{user} disse: "Vou olhar {user2} de outro jeito, talvez."
{user} disse: "Hm. Isso me deixou em dúvida."
{user} disse: "Talvez. Mas {user2} ainda me deixa inquieto(a)."
{user} disse: "Pode ser que você esteja certo(a)."
{user} disse: "Vou pensar, {user1}."
{user} disse: "Hm. Não sei. Vou ver."
{user} disse: "Talvez. Preciso de mais."
{user} disse: "Pode ser. Mas não baixo a guarda."
{user} disse: "Vou tentar confiar em {user2}. Tentar."
{user} disse: "Hm. Você me fez pensar."
{user} disse: "Talvez. {user2} tem sido gentil."
{user} disse: "Pode ser. Vou observar sem julgar."
{user} disse: "Não sei. Mas vou reconsiderar."
{user} disse: "Hm. Talvez eu esteja paranoico(a)."
{user} disse: "Talvez. Vou esperar {user2} provar."
{user} disse: "Pode ser. Mas ainda tenho um pé atrás."
{user} disse: "Vou pensar melhor antes de votar."
{user} disse: "Hm. Isso muda um pouco as coisas."
{user} disse: "Talvez. Você conhece {user2} melhor que eu."
{user} disse: "Pode ser. Vou dar uma chance."
{user} disse: "Não sei. Mas obrigado(a) por me contar."
{user} disse: "Hm. Vou reparar mais em {user2}."
{user} disse: "Talvez. Mas quero ver mais."
{user} disse: "Pode ser. Não tenho certeza de nada."
{user} disse: "Vou pensar com carinho."
{user} disse: "Hm. Talvez {user2} esteja só nervoso(a)."
{user} disse: "Talvez. Vou ficar observando."
{user} disse: "Pode ser. Você tem argumentos."
{user} disse: "Não sei. Preciso pensar."
{user} disse: "Hm. Vou conversar mais com {user2}."
{user} disse: "Talvez. Mas não é fácil mudar de ideia."
{user} disse: "Pode ser. Vou ver no café."
{user} disse: "Vou tentar olhar sem preconceito."
{user} disse: "Hm. Você me deixou dividido(a)."
{user} disse: "Talvez. {user2} tem me parecido sincero(a)."
{user} disse: "Pode ser. Mas fico de olho."
{user} disse: "Não sei. Vou decidir na mesa."
{user} disse: "Hm. Talvez."
{user} disse: "Talvez. Você é bom(boa) em convencer."
{user} disse: "Pode ser. Vou pensar sobre {user2}."
{user} disse: "Vou segurar meu julgamento."
{user} disse: "Hm. Não descarto que você tenha razão."
{user} disse: "Talvez. Vou dar mais tempo."
{user} disse: "Pode ser. Mas ainda tenho dúvidas."
{user} disse: "Não sei. Vou ver com calma."
{user} disse: "Hm. {user2} anda mais tranquilo(a)."
{user} disse: "Talvez. Vou pensar muito nisso."
{user} disse: "Pode ser. Você me fez duvidar."
{user} disse: "Vou tentar não julgar {user2} tão rápido."
{user} disse: "Hm. Pode ser que sim."
{user} disse: "Talvez. Mas vou ficar esperto(a)."
{user} disse: "Pode ser. Vou reavaliar."
{user} disse: "Não sei. Mas não voto em {user2} hoje."
{user} disse: "Hm. Talvez eu estivesse precipitado(a)."
{user} disse: "Talvez. Vou observar sem pressa."
{user} disse: "Pode ser. Vou dar uma trégua."
{user} disse: "Vou pensar e te respondo."
{user} disse: "Hm. Isso é possível."
{user} disse: "Talvez. {user2} merece um pouco de paz."
{user} disse: "Pode ser. Não sei."
{user} disse: "Não sei. Mas tô mais aberto(a)."
{user} disse: "Hm. Vou observar {user2} no café."
{user} disse: "Talvez. Você me deixou curioso(a)."
{user} disse: "Pode ser. Vou pensar melhor sobre {user2}."
{user} disse: "Vou dar o benefício da dúvida. Por hoje."
{user} disse: "Hm. Talvez {user2} seja legal mesmo."
{user} disse: "Talvez. Não sei o que pensar."
{user} disse: "Pode ser. Mas não mudo de opinião tão rápido."
{user} disse: "Não sei. Vou ficar em cima do muro."
{user} disse: "Hm. Vou pensar no seu argumento."
{user} disse: "Talvez. Vamos ver amanhã."
{user} disse: "Pode ser. Você me deixou com dúvida."
{user} disse: "Vou tentar olhar {user2} com mais calma."
{user} disse: "Hm. Pode ser verdade."
{user} disse: "Talvez. Não custa tentar."
{user} disse: "Pode ser. Vou observar."
{user} disse: "Não sei. Mas vou pensar em você quando votar."
{user} disse: "Hm. Talvez eu reveja."
{user} disse: "Talvez. {user2} nunca me fez mal, é verdade."
{user} disse: "Pode ser. Vamos com calma."
{user} disse: "Vou esperar pra decidir."
{user} disse: "Hm. Você tem certa razão."
{user} disse: "Talvez. Mas {user2} ainda me intriga."
{user} disse: "Pode ser. Vou dar uma chance."
{user} disse: "Não sei. Mas vou considerar."
{user} disse: "Hm. Talvez eu esteja vendo fantasma."
{user} disse: "Talvez. Vou prestar atenção."
{user} disse: "Pode ser. Você é persuasivo(a)."
{user} disse: "Vou pensar com carinho sobre {user2}."
{user} disse: "Hm. Pode ser, pode ser."
{user} disse: "Talvez. Mas continuo alerta."
{user} disse: "Pode ser. Vou ver como {user2} se comporta."
{user} disse: "Não sei. Mas você me deu o que pensar."
{user} disse: "Hm. Talvez."
{user} disse: "Talvez. Vou ouvir mais pessoas."
{user} disse: "Pode ser. Vou segurar o voto."
{user} disse: "Vou pensar. Obrigado(a)."
{user} disse: "Hm. {user2} pode ser inocente, sim."
{user} disse: "Talvez. Vou reparar no próximo passo."
{user} disse: "Pode ser. Não é impossível."
{user} disse: "Não sei. Mas vou ficar mais calmo(a)."
{user} disse: "Hm. Vou rever minha lista."
{user} disse: "Talvez. {user2} parece mais leve hoje."
{user} disse: "Pode ser. Vou tentar confiar."
{user} disse: "Vou pensar melhor sobre isso."
{user} disse: "Hm. Talvez eu deva confiar mais."
{user} disse: "Talvez. Mas preciso de tempo."
{user} disse: "Pode ser. Você tem um bom olhar."
{user} disse: "Não sei. Vou esperar."
{user} disse: "Hm. Vou dar uma chance a {user2}."
{user} disse: "Talvez. Vou te dizer amanhã."
{user} disse: "Pode ser. Mas vamos ver."
{user} disse: "Vou pensar em {user2} com outros olhos."
{user} disse: "Hm. Talvez sim."
{user} disse: "Talvez. {user2} tem se esforçado."
{user} disse: "Pode ser. Vou observar mais."
{user} disse: "Não sei. Mas vou reconsiderar."
{user} disse: "Hm. Você me deixou pensando."
{user} disse: "Talvez. Mas ainda tenho um pé atrás."
{user} disse: "Pode ser. Vou dar mais um dia."
{user} disse: "Vou pensar no caso de {user2}."
{user} disse: "Hm. Talvez eu tenha sido duro(a)."
{user} disse: "Talvez. Obrigado(a) por falar."
{user} disse: "Pode ser. Vou ver."
{user} disse: "Não sei. Mas fico mais aberto(a)."
{user} disse: "Hm. Talvez eu confie."
{user} disse: "Talvez. Vou observar no café."
{user} disse: "Pode ser. Você me fez pensar melhor."
{user} disse: "Vou dar uma trégua pra {user2}."
{user} disse: "Hm. Pode ser que eu esteja errado(a)."
{user} disse: "Talvez. Vou pensar mais."
{user} disse: "Pode ser. {user2} tem me surpreendido."
{user} disse: "Não sei. Mas vou tentar."
{user} disse: "Hm. Talvez {user2} mereça mais."
{user} disse: "Talvez. Vou ver com o tempo."
{user} disse: "Pode ser. Não descarto."
{user} disse: "Vou esperar {user2} mostrar quem é."
{user} disse: "Hm. Talvez."
{user} disse: "Talvez. Vou pensar nisso hoje."
{user} disse: "Pode ser. Você me deixou em dúvida sobre {user2}."
{user} disse: "Não sei. Mas obrigado(a) pela conversa."
{user} disse: "Hm. Vou olhar {user2} melhor."
{user} disse: "Talvez. Vou confiar um pouco mais."
{user} disse: "Pode ser. Vou dar uma chance, {user1}."
{user} disse: "Vou pensar, prometo."
{user} disse: "Hm. Pode ser que {user2} seja do bem."
{user} disse: "Talvez. Não sei ainda."
{user} disse: "Pode ser. Vou observar {user2}."
{user} disse: "Não sei. Mas você me acalmou um pouco."
{user} disse: "Não sei, {user1}. {user2} ainda me incomoda."
{user} disse: "Vou dar mais um dia pra {user2}."
{user} disse: "Pode ser que {user2} só seja estranho(a) mesmo."
{user} disse: "Hm. Você tá defendendo {user2} com muita força."
{user} disse: "Vou pensar no que você falou de {user2}."
{user} disse: "Meu voto em {user2} tá em dúvida agora."
{user} disse: "Não descarto, mas não tiro {user2} da lista."
{user} disse: "Se você confia em {user2}, vou tentar também."
{user} disse: "Deixa eu ver {user2} de perto hoje."
{user} disse: "Ok, baixei a guarda um pouco com {user2}."
{user} disse: "Você é convincente, {user1}. Mas ainda tô em cima do muro."
{user} disse: "Pode ser. Mas se {user2} for Traidor(a), eu te cobro."
{user} disse: "Tá, {user2} fica em observação. Não na forca."
{user} disse: "Não tô 100%. Talvez 50."
{user} disse: "Hm. Você me deixou em dúvida."
{user} disse: "Talvez, {user1}. Talvez."
{user} disse: "Talvez você conheça {user2} melhor que eu."
{user} disse: "Vou segurar meu voto em {user2}. Por ora."
{user} disse: "Hm. Você quase me convenceu sobre {user2}."
`);

export const PERSUADE_INNOCENT_NO = lines(`
{user} balançou a cabeça: "Não, {user1}. {user2} não me engana."
{user} estranhou: "Você defendendo {user2}? Agora eu desconfio dos dois."
{user} disse: "{user2} é suspeito(a), e você sabe."
{user} disse: "Não. {user2} tá mentindo."
{user} disse: "Você tá protegendo {user2} por quê?"
{user} disse: "Não caio nessa."
{user} disse: "Isso é o que um(a) parceiro(a) de torre diria."
{user} disse: "{user2} vai sair, e você não vai impedir."
{user} disse: "Não. Meu voto continua em {user2}."
{user} disse: "Você tá defendendo o(a) Traidor(a)."
{user} disse: "Não. Você tá cego(a) com {user2}."
{user} disse: "Isso me deixou mais desconfiado(a)."
{user} disse: "{user2} tem algo errado, e eu vou provar."
{user} disse: "Não. Você não me convence."
{user} disse: "Por que tanta defesa de {user2}?"
{user} disse: "Você e {user2} são aliados, né?"
{user} disse: "Não. {user2} tá jogando com você."
{user} disse: "Isso é teatro, {user1}."
{user} disse: "Você tá sendo usado(a) por {user2}."
{user} disse: "Não. E agora você entrou na minha lista."
{user} disse: "{user2}? Inocente? Nunca."
{user} disse: "Não. Você tá errado(a)."
{user} disse: "Isso é muito suspeito."
{user} disse: "Não. {user2} vai cair."
{user} disse: "Você tá desesperado(a) pra salvar {user2}."
{user} disse: "Não. E não insiste."
{user} disse: "{user2} te enganou direitinho."
{user} disse: "Não. Não confio em {user2}."
{user} disse: "Você tá protegendo um(a) Traidor(a)."
{user} disse: "Não. Olha os votos de {user2}."
{user} disse: "Isso é o que eles querem que você pense."
{user} disse: "Não. {user2} é perigoso(a)."
{user} disse: "Você me deixou desconfiado(a) de você."
{user} disse: "Não. Nada muda."
{user} disse: "{user2} tem sangue frio. Não me engana."
{user} disse: "Não. Você tá sendo ingênuo(a)."
{user} disse: "Isso não vai salvar {user2}."
{user} disse: "Não. E pensa bem em quem você defende."
{user} disse: "{user2} tá manipulando você."
{user} disse: "Não. Pode esquecer."
{user} disse: "Você tá do lado errado, {user1}."
{user} disse: "Não. Meu instinto diz outra coisa."
{user} disse: "Isso é armação dos dois."
{user} disse: "Não. {user2} tá fora da minha confiança."
{user} disse: "Você defende {user2} e eu desconfio de você."
{user} disse: "Não. Nem vem."
{user} disse: "{user2} vai mostrar quem é."
{user} disse: "Não. Você tá sendo manipulado(a)."
{user} disse: "Isso me confirma que {user2} é suspeito(a)."
{user} disse: "Não. Não vou mudar meu voto."
{user} disse: "Você tá errado(a) sobre {user2}."
{user} disse: "Não. E cuidado com {user2}."
{user} disse: "{user2}? Não, não e não."
{user} disse: "Não. Você não sabe o que eu sei."
{user} disse: "Isso é o que Traidor faz: um protege o outro."
{user} disse: "Não. {user2} tá encrencado(a)."
{user} disse: "Você tá forçando demais."
{user} disse: "Não. Eu vi o que eu vi."
{user} disse: "{user2} não me convence e você também não."
{user} disse: "Não. Chega."
{user} disse: "Você tá jogando junto com {user2}?"
{user} disse: "Não. {user2} é meu voto."
{user} disse: "Isso me deixou muito desconfiado(a)."
{user} disse: "Não. E eu vou falar na mesa."
{user} disse: "{user2} vai cair, com ou sem você."
{user} disse: "Não. Você tá enganado(a)."
{user} disse: "Você acabou de se complicar, {user1}."
{user} disse: "Não. {user2} é suspeito(a)."
{user} disse: "Isso é muito estranho."
{user} disse: "Não. Nem pensar."
{user} disse: "{user2} te enrolou, {user1}."
{user} disse: "Não. Não vou tirar {user2} da lista."
{user} disse: "Você tá defendendo quem não merece."
{user} disse: "Não. E eu tô de olho em você também."
{user} disse: "{user2} é Traidor(a), e você vai ver."
{user} disse: "Não. Você não me engana."
{user} disse: "Isso é defesa de quem tem algo a esconder."
{user} disse: "Não. Meu voto tá decidido."
{user} disse: "{user2}? Esquece."
{user} disse: "Não. E pensa bem no que tá fazendo."
{user} disse: "Você tá arriscando sua pele por {user2}."
{user} disse: "Não. Não tem jeito."
{user} disse: "{user2} tá te usando de escudo."
{user} disse: "Não. Isso não me convence."
{user} disse: "Você tá sendo bobo(a), {user1}."
{user} disse: "Não. {user2} vai sair hoje."
{user} disse: "Isso me deixa desconfiado(a) dos dois."
{user} disse: "Não. E não me procura mais com isso."
{user} disse: "{user2} tem um jogo muito estranho."
{user} disse: "Não. Nada feito."
{user} disse: "Você tá protegendo alguém perigoso."
{user} disse: "Não. {user2} tá na minha mira."
{user} disse: "Isso é teatro dos dois."
{user} disse: "Não. Não mudo de ideia."
{user} disse: "{user2}? Sei não, e você me deixou pior."
{user} disse: "Não. Você não tem argumento."
{user} disse: "Isso é muito conveniente pra {user2}."
{user} disse: "Não. E eu vou lembrar disso."
{user} disse: "{user2} é suspeito(a), ponto."
{user} disse: "Não. Você tá sendo cego(a)."
{user} disse: "Você e {user2} estão juntos nisso?"
{user} disse: "Não. Nada muda."
{user} disse: "{user2} vai ter que se explicar na mesa."
{user} disse: "Não. Não me convenceu."
{user} disse: "Isso me faz desconfiar das suas intenções."
{user} disse: "Não. {user2} tá mentindo pra você."
{user} disse: "Você tá errado(a), e vai se arrepender."
{user} disse: "Não. Nem um pouco."
{user} disse: "{user2}? Culpado(a), pra mim."
{user} disse: "Não. Você tá defendendo o lado errado."
{user} disse: "Isso é armação, certeza."
{user} disse: "Não. E cuidado com quem você protege."
{user} disse: "{user2} não merece sua defesa."
{user} disse: "Não. Meu voto é meu."
{user} disse: "Você tá sendo manipulado(a), {user1}."
{user} disse: "Não. {user2} é o nome."
{user} disse: "Isso é suspeito demais."
{user} disse: "Não. Não vou ceder."
{user} disse: "{user2} tá com sorte de ter você."
{user} disse: "Não. Você tá enganado(a) sobre {user2}."
{user} disse: "Você vai ver que eu tinha razão."
{user} disse: "Não. E ponto final."
{user} disse: "{user2} tá te fazendo de bobo(a)."
{user} disse: "Não. Meu faro não falha."
{user} disse: "Isso é o que eu esperava de quem é da torre."
{user} disse: "Não. {user2} vai sair."
{user} disse: "Você tá gastando saliva."
{user} disse: "Não. Não confio."
{user} disse: "{user2} tem muito a esconder."
{user} disse: "Não. Você não sabe de nada."
{user} disse: "Isso é inútil, {user1}."
{user} disse: "Não. {user2} é o meu voto."
{user} disse: "Você tá defendendo o(a) culpado(a)."
{user} disse: "Não. E agora você tá na minha lista também."
{user} disse: "{user2} vai cair, e você vai junto se continuar."
{user} disse: "Não. Nada disso."
{user} disse: "Isso não me convence de nada."
{user} disse: "Não. {user2} é Traidor(a), eu sinto."
{user} disse: "Você tá cego(a), {user1}."
{user} disse: "Não. Não vou mudar."
{user} disse: "{user2} vai se entregar sozinho(a)."
{user} disse: "Não. Você tá jogando errado."
{user} disse: "Isso me deixou mais certo(a) sobre {user2}."
{user} disse: "Não. E vai ser {user2} hoje."
{user} disse: "Você tá protegendo quem não devia."
{user} disse: "Não. Não tem conversa."
{user} disse: "{user2}? Nunca vou confiar."
{user} disse: "Não. Você não vai me mudar."
{user} disse: "Isso é muito estranho, vindo de você."
{user} disse: "Não. {user2} é suspeito(a), e pronto."
{user} disse: "Você devia desconfiar mais."
{user} disse: "Não. Eu sei o que vi."
{user} disse: "{user2} tá te usando, abre o olho."
{user} disse: "Não. E eu vou votar em {user2}."
{user} disse: "Isso é defesa de parceiro(a) de torre."
{user} disse: "Não. Nem vem."
{user} disse: "{user2} vai ter o que merece."
{user} disse: "Não. Você não tem razão."
{user} disse: "Isso me faz pensar mal de você."
{user} disse: "Não. {user2} não me convence."
{user} disse: "Você tá sendo ingênuo(a) demais."
{user} disse: "Não. Isso não vai rolar."
{user} disse: "{user2}? Não confio e não vou confiar."
{user} disse: "Não. Você tá errado(a), {user1}."
{user} disse: "Isso é suspeitíssimo."
{user} disse: "Não. Meu voto vai pra {user2}."
{user} disse: "Você tá defendendo o lobo."
{user} disse: "Não. E cuidado com suas companhias."
{user} disse: "{user2} tá manipulando geral."
{user} disse: "Não. Não tem como."
{user} disse: "Isso me confirma tudo."
{user} disse: "Não. {user2} é da torre."
{user} disse: "Você tá sendo usado(a), infelizmente."
{user} disse: "Não. Não mudo."
{user} disse: "{user2} tá rindo de você por dentro."
{user} disse: "Não. Nada a fazer."
{user} disse: "Isso é o que eu mais temia."
{user} disse: "Não. {user2} vai sair, e você vai ver."
{user} disse: "Você tá protegendo alguém muito perigoso."
{user} disse: "Não. Chega de conversa."
{user} disse: "{user2}? Não. Nunca."
{user} disse: "Não. Você tá errado(a) e eu tô certo(a)."
{user} disse: "Isso é muito, muito suspeito."
{user} disse: "Não. {user2} tem culpa no cartório."
{user} disse: "Você tá cego(a) de amizade."
{user} disse: "Não. Não vou tirar."
{user} disse: "{user2} vai se entregar, espera só."
{user} disse: "Defender {user2} te deixa suspeito(a), {user1}."
{user} disse: "Não. {user2} tem algo errado."
{user} disse: "Você tá cego(a) com {user2}."
{user} disse: "Pode defender à vontade. Meu voto é {user2}."
{user} disse: "{user2} te enganou direitinho, hein?"
{user} disse: "Vocês dois tão juntos nisso?"
{user} disse: "Não me convence. {user2} tá na mira."
{user} disse: "Se {user2} for Fiel, eu peço desculpa. Mas voto."
{user} disse: "Você não viu o que eu vi em {user2}."
{user} riu: "Boa tentativa, {user1}."
{user} disse: "Não. E quanto mais você defende, pior."
{user} disse: "{user2} vai cair. Com ou sem você."
{user} disse: "Por que tanto carinho por {user2}? Explica."
{user} disse: "Esquece, {user1}. Decidi."
{user} disse: "Não caio nessa. {user2} é o(a) mais suspeito(a)."
{user} disse: "Você é bonzinho(a) demais, {user1}."
{user} disse: "Não dá. {user2} me dá arrepio."
`);

/** Quem ouviu o jogador falar mal de alguém conta tudo para essa pessoa. {user} = quem conta, {user1} = de quem se falou, {user2} = jogador. */
export const TELL_ON = lines(`
Mais tarde, {user} contou tudo a {user1}. Agora {user1} sabe que {user2} fala mal dele(a).
{user} correu contar a {user1} o que {user2} disse.
{user} não aguentou e contou a {user1} a conversa com {user2}.
No jardim, {user} entregou tudo a {user1}: "{user2} tá contra você."
{user} cochichou com {user1}: "Cuidado com {user2}. Tá te queimando."
{user} foi direto(a) em {user1}: "{user2} tentou me convencer contra você."
{user} contou a {user1}, palavra por palavra, o que {user2} falou.
No corredor, {user} avisou {user1}: "{user2} tá espalhando coisa sobre você."
{user} disse a {user1}: "Você precisa saber o que {user2} anda dizendo."
{user} entregou {user2} para {user1} sem pensar duas vezes.
{user} contou a {user1}: "{user2} acha que você é Traidor(a)."
{user} foi fofocar com {user1} sobre a conversa com {user2}.
{user} avisou {user1}: "{user2} quer você fora."
{user} disse a {user1}, em segredo: "{user2} tá armando contra você."
{user} não guardou segredo e contou tudo a {user1}.
{user} procurou {user1}: "{user2} falou de você pra mim."
{user} disse a {user1}: "Fica esperto(a). {user2} tá juntando votos."
{user} contou a {user1} e os dois olharam feio para {user2}.
{user} foi logo avisar {user1} sobre {user2}.
{user} deixou escapar para {user1} o que {user2} tinha dito.
{user} disse a {user1}: "Adivinha quem tá falando mal de você? {user2}."
{user} contou a {user1}: "{user2} me pediu pra votar em você."
{user} foi fiel ao amigo(a): contou a {user1} tudo sobre {user2}.
{user} disse a {user1}: "{user2} não é seu(sua) amigo(a). Acredita em mim."
{user} avisou {user1} no quarto: "{user2} tá contra você."
{user} contou a {user1} a conversa com {user2}, com detalhes.
{user} disse a {user1}: "Eu ouvi {user2} te acusando."
{user} foi correndo contar a {user1}.
{user} disse a {user1}: "{user2} tá tentando te derrubar."
{user} não resistiu e contou tudo a {user1} no café.
{user} disse a {user1}: "Te protege de {user2}."
{user} contou a {user1}: "{user2} disse que você é suspeito(a)."
{user} avisou {user1}: "{user2} tá cochichando seu nome."
{user} entregou a conversa de {user2} para {user1}.
{user} disse a {user1}: "Toma cuidado, {user2} te quer na mesa."
{user} contou a {user1} que {user2} tentou virar os votos.
{user} disse a {user1}: "{user2} falou de você pelas costas."
{user} chamou {user1} num canto e contou tudo sobre {user2}.
{user} disse a {user1}: "Não confia em {user2}. Ele(a) fala de você."
{user} contou a {user1} e o clima entre {user1} e {user2} azedou.
{user} disse a {user1}: "{user2} quer seu nome no quadro."
{user} foi leal a {user1} e contou o que {user2} disse.
{user} disse a {user1}: "{user2} me procurou pra falar de você."
{user} contou tudo a {user1} antes do jantar.
{user} disse a {user1}: "{user2} tá plantando dúvida sobre você."
{user} avisou {user1}: "{user2} não gosta de você."
{user} contou a {user1}: "{user2} tentou me colocar contra você."
{user} disse a {user1}: "Você devia saber o que {user2} anda falando."
{user} foi contar a {user1}, e {user1} ficou furioso(a) com {user2}.
{user} disse a {user1}: "{user2} tá de olho em você, e não é bom."
{user} contou a {user1} tudo que {user2} insinuou.
{user} disse a {user1}: "Eu não concordo com {user2}, mas ele(a) acha que é você."
{user} entregou {user2} na primeira oportunidade.
{user} disse a {user1}: "{user2} tá te difamando."
{user} contou a {user1}, que agora não olha mais para {user2}.
{user} disse a {user1}: "Eu achei que você devia saber. É {user2}."
{user} foi direto a {user1}: "{user2} tá falando de você."
{user} avisou {user1} antes da mesa: "{user2} vai votar em você."
{user} contou a {user1}: "{user2} tá te acusando por aí."
{user} disse a {user1}: "{user2} tentou me convencer. Não caí."
{user} contou a {user1} e deixou a confusão armada.
{user} disse a {user1}: "Olha, {user2} tá contra você. Eu vi."
{user} não guardou a língua e contou a {user1}.
{user} disse a {user1}: "Cuidado: {user2} te chamou de Traidor(a)."
{user} contou a {user1}: "{user2} tá tentando juntar gente contra você."
{user} disse a {user1}: "Se prepara, {user2} te quer fora."
{user} contou a {user1} no ouvido o que {user2} disse.
{user} disse a {user1}: "Eu defendi você de {user2}."
{user} contou a {user1}, que foi tirar satisfação com {user2}.
{user} disse a {user1}: "{user2} tá te usando de alvo."
{user} contou a {user1} e agora o castelo inteiro sabe.
{user} disse a {user1}: "Você tem um(a) inimigo(a): {user2}."
{user} contou a {user1}: "{user2} disse coisas horríveis de você."
{user} disse a {user1}: "Fica atento(a) com {user2}. Sério."
{user} contou a {user1} a tentativa de {user2}.
{user} disse a {user1}: "{user2} tá querendo te derrubar na mesa."
{user} foi contar a {user1}, porque é leal a ele(a).
{user} disse a {user1}: "Eu ouvi tudo que {user2} falou de você."
{user} contou a {user1}: "{user2} tá contra você e não esconde."
{user} disse a {user1}: "Te conto porque gosto de você: {user2}."
{user} contou a {user1} e os dois fecharam contra {user2}.
{user} disse a {user1}: "{user2} tentou me virar contra você."
{user} contou a {user1} sem filtro nenhum.
{user} disse a {user1}: "{user2} tá falando que você é da torre."
{user} contou a {user1}, e {user1} jurou vingança contra {user2}.
{user} disse a {user1}: "Se cuida. {user2} tá armando."
{user} contou a {user1} tudo, tim-tim por tim-tim.
{user} disse a {user1}: "{user2} tentou me recrutar contra você."
{user} contou a {user1}: "{user2} quer seu voto fora do jogo."
{user} disse a {user1}: "Não fala nada, mas {user2} tá contra você."
{user} contou a {user1}, que ficou pálido(a).
{user} disse a {user1}: "{user2} tá te difamando pros outros também."
{user} contou a {user1}: "Eu não esperava isso de {user2}."
{user} disse a {user1}: "{user2} tá com você na mira."
{user} contou a {user1}, e agora {user2} tem um(a) inimigo(a).
{user} disse a {user1}: "Você precisa se defender de {user2}."
{user} contou a {user1} na hora do jantar.
{user} disse a {user1}: "{user2} tá tentando me convencer que é você."
{user} contou a {user1}: "{user2} não é quem você pensa."
{user} disse a {user1}: "Te devo essa: {user2} tá contra você."
{user} contou a {user1} o que ouviu de {user2}.
{user} disse a {user1}: "{user2} tentou me manipular sobre você."
{user} contou a {user1} e ainda deu sua opinião.
{user} disse a {user1}: "{user2} falou seu nome pra mim três vezes."
{user} contou a {user1}: "{user2} tá tramando alguma coisa."
{user} disse a {user1}: "Toma cuidado com as costas. {user2}."
{user} contou a {user1}, que agradeceu a lealdade.
{user} disse a {user1}: "{user2} tá tentando te queimar."
{user} contou a {user1} antes que fosse tarde.
{user} disse a {user1}: "Você precisa saber: {user2} tá contra você."
{user} contou a {user1} tudo que {user2} disse, com gestos.
{user} disse a {user1}: "Eu não gostei do que {user2} falou de você."
{user} contou a {user1}: "{user2} tá tentando fazer a mesa votar em você."
{user} disse a {user1}: "{user2} me procurou pra falar mal de você."
{user} contou a {user1} e o castelo ficou sabendo.
{user} disse a {user1}: "Cuidado. {user2} tá jogando contra."
{user} contou a {user1} e ainda imitou {user2}.
{user} disse a {user1}: "Você tem que saber o que {user2} disse."
{user} contou a {user1} sem esconder nada.
{user} disse a {user1}: "{user2} quer te ver sair."
{user} contou a {user1}: "{user2} tentou colocar você na berlinda."
{user} disse a {user1}: "Eu não concordo com {user2}. E te conto por isso."
{user} contou a {user1} no meio do café.
{user} disse a {user1}: "Olho aberto com {user2}."
{user} contou a {user1}: "{user2} tá te acusando pra todo mundo."
{user} disse a {user1}: "Você precisa se proteger. {user2} tá atrás de você."
{user} contou a {user1} e foi embora rindo.
{user} disse a {user1}: "{user2} não te suporta, sabia?"
{user} contou a {user1}: "{user2} disse que você finge."
{user} disse a {user1}: "Eu tô do seu lado. {user2} não."
{user} contou a {user1}, e o clima fechou de vez.
{user} disse a {user1}: "{user2} tá tentando juntar voto contra você."
{user} contou a {user1} tudo, sem dó de {user2}.
{user} disse a {user1}: "Fica sabendo: {user2} tá falando de você."
{user} contou a {user1}: "{user2} acha que você é o(a) Traidor(a)."
{user} disse a {user1}: "Você precisa confrontar {user2}."
{user} contou a {user1}, e {user1} não perdoou.
{user} disse a {user1}: "{user2} tá contra você, e eu contra {user2}."
{user} contou a {user1}: "{user2} falou horrores."
{user} disse a {user1}: "Eu achei que você devia saber de {user2}."
{user} contou a {user1} logo depois da conversa.
{user} disse a {user1}: "{user2} tá te caçando."
{user} contou a {user1}: "{user2} tentou me convencer e eu disse não."
{user} disse a {user1}: "Toma cuidado com {user2}, é sério."
{user} contou a {user1} tudo o que {user2} armou.
{user} disse a {user1}: "{user2} quer você fora da mesa final."
{user} contou a {user1} e ainda aumentou um pouco.
{user} disse a {user1}: "Não confia em {user2}. Nunca."
{user} contou a {user1}: "{user2} tá tentando te isolar."
{user} disse a {user1}: "Você devia ouvir o que {user2} anda falando."
{user} contou a {user1}, e a notícia correu pelo castelo.
{user} disse a {user1}: "{user2} tá contra você, e eu não acho justo."
{user} contou a {user1} enquanto todos dormiam.
{user} disse a {user1}: "{user2} é seu(sua) inimigo(a) número um."
{user} contou a {user1}: "{user2} tá te difamando nos cantos."
{user} disse a {user1}: "Se prepara pra mesa. {user2} vem com tudo."
{user} contou a {user1}, que ficou de olho em {user2}.
{user} disse a {user1}: "Eu não ia contar, mas {user2} passou do limite."
{user} contou a {user1}: "{user2} quer seu nome no quadro hoje."
{user} disse a {user1}: "{user2} tentou me virar. Não deu."
{user} contou a {user1} e jurou lealdade.
{user} disse a {user1}: "{user2} falou de você com raiva."
{user} contou a {user1}: "Fica esperto(a) com {user2}."
{user} disse a {user1}: "Eu ouvi {user2} tramando contra você."
{user} contou a {user1}, e {user1} foi direto tirar satisfação.
{user} disse a {user1}: "{user2} tá te queimando pros outros."
{user} contou a {user1} tudo o que {user2} sussurrou.
{user} disse a {user1}: "Você tem um alvo nas costas, e quem pôs foi {user2}."
{user} contou a {user1}: "{user2} tá falando que não confia em você."
{user} disse a {user1}: "Protege-se de {user2}. Ele(a) tá contra."
{user} contou a {user1}, e agora {user2} vai ter trabalho.
{user} disse a {user1}: "{user2} tentou me convencer de você. Não colou."
{user} contou a {user1}: "Eu não gosto do jogo de {user2}."
{user} disse a {user1}: "{user2} tá tentando fazer sua cabeça rolar."
{user} contou a {user1} e o drama começou.
{user} disse a {user1}: "Te aviso como amigo(a): {user2}."
{user} contou a {user1}: "{user2} tá contra você, e forte."
{user} disse a {user1}: "Eu vou te proteger de {user2}."
{user} contou a {user1}, e a guerra entre {user1} e {user2} começou.
{user} disse a {user1}: "Fica sabendo que {user2} tá te apunhalando."
{user} contou a {user1}: "{user2} não gosta de você, e diz pra todo mundo."
{user} disse a {user1}: "Cuidado com {user2}. Tô te avisando."
{user} contou a {user1} tudo que {user2} planejou.
{user} disse a {user1}: "{user2} tá te traindo, eu ouvi."
{user} contou a {user1}: "{user2} quer seu fim."
{user} disse a {user1}: "Eu não confio em {user2}, e você também não devia."
{user} contou a {user1}, e {user1} agradeceu com um abraço.
{user} disse a {user1}: "{user2} tentou me usar contra você."
{user} contou a {user1}: "{user2} tá falando de você sem parar."
{user} disse a {user1}: "Você precisa saber quem é {user2} de verdade."
{user} contou a {user1}, e os dois juraram tirar {user2}.
{user} disse a {user1}: "{user2} tá te caluniando."
{user} contou a {user1}: "{user2} tá desesperado(a) pra te tirar."
{user} foi direto a {user1}: "{user2} tá falando de você por aí."
{user} contou a {user1} cada palavra de {user2}.
{user} entregou {user2} para {user1} na primeira chance.
{user} disse a {user1}: "Sabe o que {user2} me pediu? Seu nome no papel."
{user} não guardou segredo: foi contar a {user1} o plano de {user2}.
{user} contou a {user1}, fingindo pena: "{user2} quer você fora."
{user} disse a {user1}: "Não era pra eu contar, mas {user2} te queimou."
{user} contou a {user1} que {user2} tentou virar votos.
{user} disse a {user1}: "{user2} me procurou pra falar de você. Mal."
{user} fez questão de repetir a {user1} tudo o que {user2} disse.
{user} disse a {user1}: "{user2} jura que você é Traidor(a). Ouvi agora."
`);
