import { lines } from './lines';

/** Respostas: {user} = quem responde, {user1} = jogador, {user2} = de quem se fala. */

/** "Em quem você desconfia?" / "O que acha de...?" quando a pessoa não confia no jogador. */
export const REPLY_ASK_REFUSE = lines(`
{user} desconversou: "E por que eu contaria isso logo pra você, {user1}?"
{user} riu: "Boa tentativa."
{user} disse: "Isso eu guardo pra mim."
{user} disse: "Pra você? Nem pensar."
{user} disse: "Não confio em você o bastante pra isso."
{user} cruzou os braços: "Próxima pergunta."
{user} disse: "Você quer saber pra quê?"
{user} disse: "Não vou te dar munição."
{user} disse: "Pergunta pra outra pessoa."
{user} disse: "Hm. Não."
{user} disse: "Isso é informação valiosa demais pra você."
{user} disse: "Você acha que eu sou bobo(a)?"
{user} deu as costas sem responder.
{user} disse: "Descobre sozinho(a)."
{user} disse: "Não vou falar nada."
{user} disse: "Por que tanta curiosidade, {user1}?"
{user} disse: "Isso fica comigo."
{user} disse: "Não é da sua conta."
{user} disse: "Você vai usar isso contra mim."
{user} disse: "Não, obrigado(a)."
{user} disse: "Engraçado você perguntar isso."
{user} disse: "Guarda sua pergunta."
{user} disse: "Não confio em quem pergunta demais."
{user} disse: "Só conto pra quem confio. Não é o caso."
{user} disse: "Tá tentando me investigar?"
{user} disse: "Isso é segredo de estado."
{user} disse: "Eu não abro o jogo assim."
{user} disse: "Hm, sei não."
{user} disse: "Não vou te ajudar nisso."
{user} disse: "Você devia desconfiar de si mesmo(a)."
{user} disse: "Não é hora de conversa."
{user} disse: "Deixa pra lá, {user1}."
{user} disse: "Não vou entregar ninguém."
{user} disse: "Você acha que eu vou te contar?"
{user} disse: "Pergunta difícil. Resposta: não."
{user} disse: "Talvez outro dia. Talvez nunca."
{user} disse: "Não confio em você pra isso."
{user} disse: "Hm. Não tô a fim."
{user} disse: "Você não merece essa informação."
{user} disse: "Isso é jogada sua, né?"
{user} disse: "Não. E não insiste."
{user} disse: "Você tá pescando, {user1}."
{user} disse: "Eu não falo de ninguém pelas costas."
{user} disse: "Por que eu faria isso?"
{user} disse: "Não vou alimentar fofoca."
{user} disse: "Descobre pelo seu faro."
{user} disse: "Não me mete nisso."
{user} disse: "Eu não sei, e se soubesse não contava."
{user} disse: "Sai dessa, {user1}."
{user} disse: "Não tenho nada a dizer pra você."
{user} disse: "Você é a última pessoa pra quem eu contaria."
{user} disse: "Isso é armadilha."
{user} disse: "Hm. Pergunta pra torre."
{user} disse: "Não vou colaborar."
{user} disse: "Você não tá do meu lado."
{user} disse: "Não conto. Ponto."
{user} disse: "Isso é problema seu."
{user} disse: "Não me faz perguntas assim."
{user} disse: "Não vou te dar esse gostinho."
{user} disse: "Meu voto é segredo."
{user} disse: "Você quer me queimar, né?"
{user} disse: "Não. Desculpa."
{user} disse: "Não sei do que você tá falando."
{user} disse: "Não vou falar, e pronto."
{user} disse: "Não tenho confiança pra isso."
{user} disse: "Descobre sozinho(a), detetive."
{user} disse: "Isso não é da sua conta, {user1}."
{user} disse: "Hm. Nada a declarar."
{user} disse: "Não, {user1}."
{user} disse: "Você não é meu(minha) confidente."
{user} disse: "Pergunta pra quem confia em você."
{user} disse: "Eu tô fora dessa."
{user} disse: "Não entrego ninguém."
{user} disse: "Não sei. E não quero saber."
{user} disse: "Olha pro espelho, {user1}."
{user} disse: "Não caio nessa."
{user} disse: "Isso é pessoal."
{user} disse: "Não vou contar e você sabe por quê."
{user} disse: "Não. Muda de assunto."
{user} disse: "Você não vai tirar nada de mim."
{user} disse: "Por que você acha que eu contaria?"
{user} disse: "Não. Nem se me pagassem."
{user} disse: "Guarda isso pra mesa."
{user} disse: "Hm, você quer demais."
{user} disse: "Não sou fofoqueiro(a)."
{user} disse: "Não vou te facilitar."
{user} disse: "Cada um com suas desconfianças."
{user} disse: "Não. Fica na sua."
{user} disse: "Não confio em você nem um pouco."
{user} disse: "Não vou abrir a boca."
{user} disse: "Hm, curiosidade matou o gato."
{user} disse: "Não, {user1}. Não vai rolar."
{user} disse: "Você quer usar isso pra quê?"
{user} disse: "Não tenho nada pra você."
{user} disse: "Não vou dividir isso."
{user} disse: "Eu não conto nem pra mim."
{user} disse: "Não. Pode ir."
{user} disse: "Hm. Desconfio da sua pergunta."
{user} disse: "Não vou me comprometer."
{user} disse: "Isso é demais pra pedir."
{user} disse: "Não. Nada feito."
{user} disse: "Não vou te dar esse nome."
{user} disse: "Não é contigo que eu falo disso."
{user} disse: "Não. Você tá no meu radar."
{user} disse: "Você é suspeito(a) demais pra eu contar."
{user} disse: "Não. Talvez depois."
{user} disse: "Não. Você não é de confiança."
{user} disse: "Hm. Esquece."
{user} disse: "Não vou te contar, {user1}."
{user} disse: "Isso morre comigo."
{user} disse: "Não. Prefiro calar."
{user} disse: "Pergunta pro vento."
{user} disse: "Não. Cada um no seu quadrado."
{user} disse: "Não vou falar mal de ninguém pra você."
{user} disse: "Não. Mas boa tentativa."
{user} disse: "Hm. Você é insistente."
{user} disse: "Não. Chega de perguntas."
{user} disse: "Não. Nem vem."
{user} disse: "Isso é confidencial."
{user} disse: "Não. Não confio."
{user} disse: "Não vou me meter nisso."
{user} disse: "Hm. Você não precisa saber."
{user} disse: "Não. Deixa eu jogar em paz."
{user} disse: "Não, obrigado(a). Passo."
{user} disse: "Não. Desconfio de você."
{user} disse: "Não vou contar, e ponto final."
{user} disse: "Isso não é pra você."
{user} disse: "Não. Não somos próximos."
{user} disse: "Hm. Não vou responder."
{user} disse: "Não. Conta você primeiro."
{user} disse: "Eu? Contar pra você? Não."
{user} disse: "Não. Você vai espalhar."
{user} disse: "Não. Nem pensar, {user1}."
{user} disse: "Não. Tenho meus motivos."
{user} disse: "Não. A gente não tem essa intimidade."
{user} disse: "Hm. Não tenho nada a dizer."
{user} disse: "Não. Vai procurar sua turma."
{user} disse: "Não. Eu sei guardar segredo."
{user} disse: "Não. Descubra."
{user} disse: "Não vou te entregar nada, {user1}."
{user} disse: "Não. Isso é meu."
{user} disse: "Hm, não. Obrigado(a)."
{user} disse: "Não. Não gosto dessa conversa."
{user} disse: "Não. E não me pergunta de novo."
{user} disse: "Não. Você não vai me usar."
{user} disse: "Não. Pergunte ao seu travesseiro."
{user} disse: "Não. Nem sob tortura."
{user} disse: "Não. Não é hora."
{user} disse: "Hm. Nada feito, {user1}."
{user} disse: "Não. Tenho mais o que fazer."
{user} disse: "Não. Fica pra próxima."
{user} disse: "Não. Não quero me expor."
{user} disse: "Não. Desculpa, não dá."
{user} disse: "Não. Nem vou pensar."
{user} disse: "Não. Você sabe por quê."
{user} disse: "Hm. Não sei nada."
{user} disse: "Não. Não tenho resposta."
{user} disse: "Não. Não somos amigos."
{user} disse: "Não. Não confio no seu jogo."
{user} disse: "Não. Pode esquecer."
{user} disse: "Não. Vai perguntar pra outro."
{user} disse: "Hm. Isso fica comigo."
{user} disse: "Não. Não abro o jogo."
{user} disse: "Não. Você já sabe demais."
{user} disse: "Não. Aqui não."
{user} disse: "Não. Nem agora, nem depois."
{user} disse: "Não. Você é suspeito(a)."
{user} disse: "Hm. Melhor não."
{user} disse: "Não. Eu não sei se você é Fiel."
{user} disse: "Não. Nada pra você."
{user} disse: "Não. Me deixa em paz."
{user} disse: "Não. Não vou falar."
{user} disse: "Não. Chega."
{user} disse: "Hm. Não conto."
{user} disse: "Não. Não posso te ajudar."
{user} disse: "Não. Você ia usar contra mim."
{user} disse: "Não. Nem tenta."
{user} disse: "Não. Eu me protejo."
{user} disse: "Não. Não confio em ninguém."
{user} disse: "Não. Cada um por si."
{user} disse: "Hm. Isso não."
{user} disse: "Não. Nem pense nisso."
{user} disse: "Não. Não é seguro."
{user} disse: "Não. Talvez pra outro."
{user} disse: "Não. Eu calo."
{user} disse: "Não. Você não merece."
{user} disse: "Hm. Não tenho o que dizer."
{user} disse: "Não. É tudo que vou dizer."
{user} disse: "Você primeiro, {user1}."
{user} sorriu: "Segredo é segredo."
{user} disse: "Hm, não. Você vai contar pra alguém."
{user} disse: "Não confio em você o suficiente pra isso."
{user} disse: "Pergunta pra outra pessoa, {user1}."
{user} riu: "Achou que ia ser fácil assim?"
{user} disse: "Meus palpites ficam comigo."
{user} disse: "Não tô afim de falar disso agora."
{user} disse: "Pra você? Nunca."
{user} disse: "Por que você quer saber, hein?"
{user} disse: "Se eu te falar, vira fofoca em cinco minutos."
{user} disse: "Não vou te dar munição, {user1}."
{user} disse, seco(a): "Não."
{user} disse: "Hoje eu fico calado(a)."
`);

/** "Em quem você desconfia?": {user2} é o nome que a pessoa conta. */
export const REPLY_ASK_NAME = lines(`
{user} cochichou para {user1}: "Eu desconfio de {user2}."
{user} olhou em volta: "Fica de olho em {user2}, {user1}."
{user} disse baixinho: "{user2}. Não conta pra ninguém."
{user} disse: "Meu nome é {user2}. Sem dúvida."
{user} disse: "{user2} me dá arrepio."
{user} disse: "Se eu tivesse que votar agora, {user2}."
{user} disse: "{user2}. Olha como fala da torre."
{user} disse: "Tô de olho em {user2} desde ontem."
{user} disse: "{user2} tá calmo(a) demais."
{user} disse: "Sabe quem? {user2}."
{user} disse: "Meu palpite é {user2}."
{user} disse: "{user2} não fecha pra mim."
{user} disse: "Eu apostaria em {user2}."
{user} disse: "{user2} tem algo estranho."
{user} disse: "Guarda isso: {user2}."
{user} disse: "{user2}. Aposto meu prêmio."
{user} disse: "Vou te contar: {user2}."
{user} disse: "Eu vi {user2} rindo na hora errada."
{user} disse: "{user2} muda de lado toda hora."
{user} disse: "Não confio em {user2}. Nem um pouco."
{user} disse: "{user2} sabe mais do que fala."
{user} disse: "{user2} tá sempre perto das mortes."
{user} disse: "Olha, {user2} me incomoda."
{user} disse: "Meu voto hoje é {user2}."
{user} disse: "{user2} tem cara de capa preta."
{user} disse: "Eu ficaria longe de {user2}."
{user} disse: "{user2} é bom(boa) demais em parecer inocente."
{user} disse: "{user2}. Pode anotar."
{user} disse: "Desconfio de {user2}, e não é de hoje."
{user} disse: "{user2} nunca chora por ninguém."
{user} disse: "Eu acho que é {user2}."
{user} disse: "{user2} tá manipulando a mesa."
{user} disse: "Presta atenção em {user2} amanhã."
{user} disse: "{user2} desvia o olhar quando falam de voto."
{user} disse: "Pra mim, {user2} é Traidor(a)."
{user} disse: "Se eu errar, erro com {user2}."
{user} disse: "{user2} tem um jogo muito calculado."
{user} disse: "{user2} faz perguntas demais."
{user} disse: "Eu não durmo tranquilo(a) com {user2}."
{user} disse: "{user2}. Tenho quase certeza."
{user} disse: "{user2} tá escondendo alguma coisa."
{user} disse: "Olha pro {user2} na próxima mesa."
{user} disse: "{user2} tá jogando dos dois lados."
{user} disse: "Meu faro diz {user2}."
{user} disse: "{user2} tá seguro(a) demais."
{user} disse: "Eu acho {user2} muito frio(a)."
{user} disse: "{user2} é o nome que não sai da minha cabeça."
{user} disse: "Vou votar em {user2}, e você devia pensar nisso."
{user} disse: "{user2} tem um sorriso que não me convence."
{user} disse: "Eu vi {user2} no corredor de madrugada."
{user} disse: "{user2} nunca desconfia de ninguém. Estranho."
{user} disse: "{user2}. E não me pergunta por quê."
{user} disse: "Eu desconfio de {user2} e de mais ninguém."
{user} disse: "{user2} é bom(boa) demais nesse jogo."
{user} disse: "{user2} fala uma coisa e faz outra."
{user} disse: "Toma cuidado com {user2}."
{user} disse: "{user2} é meu principal suspeito."
{user} disse: "{user2} tem resposta pronta pra tudo."
{user} disse: "Eu tô dividido(a), mas pendendo pra {user2}."
{user} disse: "{user2} me olhou estranho hoje."
{user} disse: "{user2} tá sempre do lado de quem ganha."
{user} disse: "{user2}. Você viu a reação dele(a) no café?"
{user} disse: "{user2} ri quando ninguém ri."
{user} disse: "{user2} some nas horas difíceis."
{user} disse: "Pra mim é {user2}, fácil."
{user} disse: "{user2} parece esconder a capa no armário."
{user} disse: "{user2} vota sempre no último segundo."
{user} disse: "{user2} tá muito tranquilo(a) pra quem tá em perigo."
{user} disse: "{user2}. Mas fica entre nós."
{user} disse: "{user2} defendeu quem não devia."
{user} disse: "Eu tô com {user2} atravessado(a)."
{user} disse: "{user2} é muito calculista."
{user} disse: "{user2} tem uma calma que assusta."
{user} disse: "{user2} tá guiando os votos."
{user} disse: "{user2} evita ficar sozinho(a) com Fiel."
{user} disse: "Eu apostaria em {user2}, de olhos fechados."
{user} disse: "{user2} tá no meu radar."
{user} disse: "Sinceramente? {user2}."
{user} disse: "{user2} mentiu pra mim ontem."
{user} disse: "{user2} tem cara de quem sabe tudo."
{user} disse: "{user2} sabia da morte antes de todo mundo."
{user} disse: "{user2} é bom(boa) de papo. Demais."
{user} disse: "{user2} não me passa verdade."
{user} disse: "{user2}. Olha os votos dele(a)."
{user} disse: "Eu ficaria de olho em {user2}."
{user} disse: "{user2} tá jogando muito bem pra ser Fiel."
{user} disse: "{user2} me parece ensaiado(a)."
{user} disse: "Meu voto de desconfiança vai pra {user2}."
{user} disse: "{user2} sempre sobrevive. Por quê?"
{user} disse: "{user2} tem uma aliança estranha."
{user} disse: "Eu desconfio de {user2}, e você?"
{user} disse: "{user2}. Vou votar nele(a) hoje."
{user} disse: "{user2} tá com o jogo muito limpo. Limpo demais."
{user} disse: "{user2} fala demais de lealdade."
{user} disse: "{user2} me deu uma resposta estranha."
{user} disse: "{user2}, com certeza."
{user} disse: "{user2} é o(a) mais perigoso(a) daqui."
{user} disse: "{user2} tem um olhar que não me engana."
{user} disse: "{user2} quer parecer útil demais."
{user} disse: "{user2}. Mas não tenho prova."
{user} disse: "{user2} tem algo a esconder, eu sinto."
{user} disse: "Eu acho que é {user2}, mas posso errar."
{user} disse: "{user2} tá sempre um passo à frente."
{user} disse: "{user2} escolhe as palavras com cuidado demais."
{user} disse: "{user2} fingiu surpresa, eu vi."
{user} disse: "{user2} me assusta um pouco."
{user} disse: "{user2} tá no topo da minha lista."
{user} disse: "{user2}, e pode confiar no meu faro."
{user} disse: "{user2} nunca se abala."
{user} disse: "{user2} é a pessoa que menos me convence."
{user} disse: "{user2} jogou alguém embaixo do ônibus."
{user} disse: "{user2}. Sem pensar duas vezes."
{user} disse: "{user2} tá tentando me isolar."
{user} disse: "{user2} tem ligação com quem saiu Traidor."
{user} disse: "{user2} anda muito misterioso(a)."
{user} disse: "{user2}. Mas fala baixo."
{user} disse: "{user2} me evita desde ontem."
{user} disse: "{user2} tá desviando atenção."
{user} disse: "{user2} tem pose de inocente. Pose."
{user} disse: "{user2} é o nome que eu não falei na mesa."
{user} disse: "{user2} tá sempre bem informado(a)."
{user} disse: "{user2} me dá um frio na espinha."
{user} disse: "{user2} tá tranquilo(a) demais depois de cada morte."
{user} disse: "Pra mim, {user2}. Mas é intuição."
{user} disse: "{user2} anda protegendo alguém."
{user} disse: "{user2}. Você também acha?"
{user} disse: "{user2} tá sempre fora das conversas importantes."
{user} disse: "{user2} tá rindo por dentro."
{user} disse: "{user2}, e eu vou provar."
{user} disse: "{user2} é bom(boa) em mentir."
{user} disse: "{user2} tem um plano, e não é de Fiel."
{user} disse: "{user2}. Toma cuidado."
{user} disse: "{user2} manipula com sorriso."
{user} disse: "{user2} tá aproveitando a confusão."
{user} disse: "{user2}. Só confio em você pra contar isso."
{user} disse: "{user2} é o(a) mais estranho(a) daqui."
{user} disse: "{user2} tá com medo. Medo de ser pego(a)."
{user} disse: "{user2} tem um segredo."
{user} disse: "{user2}. Mas não fala que fui eu."
{user} disse: "{user2} tá de olho em mim também."
{user} disse: "{user2} anda cochichando demais."
{user} disse: "{user2}, com todas as letras."
{user} disse: "{user2} nunca acusa ninguém. Suspeito."
{user} disse: "{user2} é leal a alguém que não é a gente."
{user} disse: "{user2}. Esse jogo não me engana."
{user} disse: "{user2} evita as perguntas certas."
{user} disse: "{user2} tem uma frieza que me incomoda."
{user} disse: "{user2}. E acho que você sabe disso."
{user} disse: "{user2} tá sempre no lugar certo."
{user} disse: "{user2} vive mudando de opinião."
{user} disse: "{user2}. Mas é só um palpite."
{user} disse: "{user2} tem cara de quem guarda segredo na torre."
{user} disse: "{user2} tá brincando com a gente."
{user} disse: "{user2}. Pode anotar e me cobrar."
{user} disse: "{user2} tem o voto mais estranho da mesa."
{user} disse: "{user2} nunca vota em quem sai Traidor."
{user} disse: "{user2} quer ser amigo(a) de todo mundo."
{user} disse: "{user2}. Tem algo errado ali."
{user} disse: "{user2} tá calculando tudo."
{user} disse: "{user2} me olhou como quem já decidiu."
{user} disse: "{user2}. Eu sinto no estômago."
{user} disse: "{user2} é o meu mistério favorito."
{user} disse: "{user2} tá sorrindo demais ultimamente."
{user} disse: "{user2}. Você não achou estranho?"
{user} disse: "{user2} tá sempre com a resposta na ponta da língua."
{user} disse: "{user2} tá rondando as pessoas certas."
{user} disse: "{user2}. Vigia pra mim?"
{user} disse: "{user2} tá se escondendo atrás de alguém."
{user} disse: "{user2} tem a paciência de quem sabe o final."
{user} disse: "{user2}. Mas eu posso estar enganado(a)."
{user} disse: "{user2} anda muito prestativo(a). Hm."
{user} disse: "{user2} tem um olhar de raposa."
{user} disse: "{user2}, sem sombra de dúvida."
{user} disse: "{user2} tá fazendo o jogo da torre."
{user} disse: "{user2}. Não deixa escapar."
{user} disse: "{user2} tá blefando o tempo todo."
{user} disse: "{user2} fala comigo como quem esconde algo."
{user} disse: "{user2}. Você viu como reagiu à notícia?"
{user} disse: "{user2} tá sempre ao lado do perigo."
{user} disse: "{user2} é bom(boa) de teatro."
{user} disse: "{user2}. Meu coração diz isso."
{user} disse: "{user2} não me convenceu até agora."
{user} disse: "{user2} tem uma energia estranha."
{user} disse: "{user2}. E você, desconfia de quem?"
{user} disse: "{user2} tá sempre um pouco longe demais."
{user} disse: "{user2}, e isso fica entre nós dois."
{user} disse: "{user2} tem a cara mais lavada do castelo."
{user} disse: "{user2}. É minha aposta."
{user} disse: "{user2} tá com a cabeça em outro lugar. Na torre?"
{user} disse: "{user2}. Mas você não ouviu isso de mim."
{user} disse: "Se fosse votar agora? {user2}."
{user} olhou para {user2} de longe: "Aquele(a) ali. Sei não."
{user} disse a {user1}: "{user2}. Mas não sai daqui."
{user} disse: "{user2} tá estranho(a) desde o começo."
{user} disse: "Meu palpite? {user2}."
{user} disse: "{user2}. Fala demais e diz nada."
{user} disse: "Não conta pra ninguém: {user2}."
{user} disse: "Eu tô de olho em {user2}. Muito."
{user} disse: "{user2}. Ponto."
{user} disse: "Pra mim é {user2}. Sem dúvida."
{user} sussurrou: "{user2} me dá calafrio."
{user} disse: "Aposto minhas fichas em {user2}."
`);

/** "Em quem você desconfia?" quando a resposta é o próprio jogador. */
export const REPLY_ASK_YOU = lines(`
{user} hesitou e disse, baixinho: "Sinceramente? Você, {user1}."
{user} olhou nos olhos de {user1}: "Em você."
{user} riu sem graça: "Você quer mesmo saber? Você."
{user} disse: "Tô desconfiando de você, {user1}. Desculpa."
{user} disse: "É você. Não me leva a mal."
{user} disse: "Você tá no topo da minha lista."
{user} disse: "Olha, eu desconfio de você."
{user} disse: "Pra ser sincero(a)? Você."
{user} disse: "Você me deixa com a pulga atrás da orelha."
{user} disse: "Eu ia te perguntar o mesmo, porque desconfio de você."
{user} disse: "Não fica bravo(a), mas é você."
{user} disse: "Você, {user1}. Tá estranho(a)."
{user} disse: "Hm. Você."
{user} disse: "Engraçado você perguntar. Desconfio de você."
{user} disse: "Você me parece suspeito(a)."
{user} disse: "Eu tô de olho em você, {user1}."
{user} disse: "Você, e eu não sei explicar."
{user} disse: "Você tá jogando muito calado(a)."
{user} disse: "Você. Mas posso mudar de ideia."
{user} disse: "Desconfio de você, e não é pessoal."
{user} disse: "Você é meu maior mistério aqui."
{user} disse: "É você, {user1}. Me prova que não."
{user} disse: "Você anda estranho(a) demais."
{user} disse: "Você pergunta muito. Isso me faz desconfiar."
{user} disse: "Você tá na minha lista. Primeiro lugar."
{user} disse: "Honestamente? Você."
{user} disse: "Eu acho que é você."
{user} disse: "Você. E acho que você sabe por quê."
{user} disse: "Você tá sempre perto de quem morre."
{user} disse: "Você me dá arrepio, {user1}."
{user} disse: "Você. Mas eu gosto de você mesmo assim."
{user} disse: "Não me leva a mal, mas é você."
{user} disse: "Eu desconfio de você desde a chegada."
{user} disse: "Você. Pronto, falei."
{user} disse: "Você tá jogando bem demais."
{user} disse: "Você tem cara de quem sobe a escada."
{user} disse: "Você, {user1}. E fico triste com isso."
{user} disse: "É você que eu vigio."
{user} disse: "Sinceridade: você."
{user} disse: "Você é o nome que não sai da minha cabeça."
{user} disse: "Você me deixa confuso(a), e isso me faz desconfiar."
{user} disse: "Você. Mas quero estar errado(a)."
{user} disse: "Eu tô de olho em você há dias."
{user} disse: "Você, e agora eu tô com vergonha de dizer."
{user} disse: "Você tá escondendo alguma coisa."
{user} disse: "Você, com certeza."
{user} disse: "É você. Olha o seu jogo."
{user} disse: "Você tá tranquilo(a) demais."
{user} disse: "Você me lembra os Traidores das outras temporadas."
{user} disse: "Você. Mas não vou votar ainda."
{user} disse: "Você é esperto(a) demais pra ser Fiel."
{user} disse: "Eu desconfio de você e de mais ninguém."
{user} disse: "Você. Sorry."
{user} disse: "Você me pergunta isso e eu desconfio mais."
{user} disse: "Você tá sempre bem informado(a)."
{user} disse: "Você. Mas prova que eu tô errado(a)."
{user} disse: "Olha, é você."
{user} disse: "Você tá no meu radar."
{user} disse: "Você, e ponto."
{user} disse: "Você me parece ter um plano."
{user} disse: "É você, {user1}. Desculpa a sinceridade."
{user} disse: "Você tá cheio(a) de perguntas. Isso é Traidor."
{user} disse: "Você, e eu vou te vigiar."
{user} disse: "Você anda muito leve pra esse jogo."
{user} disse: "Você. Não tenho outro nome."
{user} disse: "Você tá jogando com todo mundo."
{user} disse: "Você, e você sabe que eu sei."
{user} disse: "Você me dá medo às vezes."
{user} disse: "Você. Mas vou te dar uma chance."
{user} disse: "Você me engana bem, mas não tanto."
{user} disse: "Você, e é difícil te dizer isso."
{user} disse: "Você tá sempre com a resposta certa."
{user} disse: "Você. Queria que fosse outro."
{user} disse: "Você anda calculando tudo."
{user} disse: "Você, {user1}. Me convence do contrário."
{user} disse: "Você tá sorrindo demais."
{user} disse: "Você é a minha dúvida."
{user} disse: "Você. E essa conversa só aumentou."
{user} disse: "Você tá muito interessado(a) em saber."
{user} disse: "Você. Eu fico com um pé atrás."
{user} disse: "É você que eu desconfio."
{user} disse: "Você, e agora que falei me sinto melhor."
{user} disse: "Você me parece ter dois rostos."
{user} disse: "Você. E não é de hoje."
{user} disse: "Você tem cara de quem guarda segredo."
{user} disse: "Você, {user1}. Espero estar errado(a)."
{user} disse: "Você tá jogando pra si mesmo(a)."
{user} disse: "Você. Mas fica entre nós."
{user} disse: "Você tá cercando todo mundo."
{user} disse: "Você, e ninguém mais."
{user} disse: "Você tem um jogo muito limpo. Limpo demais."
{user} disse: "Você. Mas eu ainda gosto de você."
{user} disse: "Você anda muito misterioso(a)."
{user} disse: "Você, e eu vou te observar."
{user} disse: "Você tá sempre no lugar certo."
{user} disse: "Você. Vai me provar o contrário?"
{user} disse: "É você que eu mais observo."
{user} disse: "Você, e isso me dói."
{user} disse: "Você tá perguntando muito sobre suspeitas."
{user} disse: "Você. É o que eu sinto."
{user} disse: "Você me parece bem à vontade aqui."
{user} disse: "Você, {user1}. Não vou mentir."
{user} disse: "Você tá sempre tranquilo(a) nas mortes."
{user} disse: "Você. Mas pode ser coisa da minha cabeça."
{user} disse: "Você tá manipulando as conversas."
{user} disse: "Você, e só você."
{user} disse: "Você tá com um brilho estranho no olhar."
{user} disse: "Você. E me desculpa por isso."
{user} disse: "Você é bom(boa) demais pra ser verdade."
{user} disse: "Você, e eu queria que não fosse."
{user} disse: "Você tá me testando agora, né?"
{user} disse: "Você. Essa pergunta te entregou."
{user} disse: "Você tá muito curioso(a)."
{user} disse: "Você, {user1}. Com carinho, mas você."
{user} disse: "Você me deixa com dúvida todo dia."
{user} disse: "Você. Eu não confio totalmente em você."
{user} disse: "Você tá de olho em todos. Por quê?"
{user} disse: "Você. Olha, não briga comigo."
{user} disse: "Você tem um jeito de quem sabe algo."
{user} disse: "Você, sem rodeios."
{user} disse: "Você me parece um(a) ótimo(a) Traidor(a)."
{user} disse: "Você. E acho que a mesa também."
{user} disse: "Você tá sempre calculando."
{user} disse: "Você, e eu tô com medo de te dizer isso."
{user} disse: "Você anda muito com quem morreu."
{user} disse: "Você. Mas eu posso mudar."
{user} disse: "Você é a pessoa que eu mais vigio."
{user} disse: "Você, {user1}. Não posso mentir."
{user} disse: "Você tá sempre tranquilo(a)."
{user} disse: "Você. E essa pergunta deixou mais claro."
{user} disse: "Você me deixa desconfiado(a)."
{user} disse: "Você, e sinto muito."
{user} disse: "Você tá com um jogo bonito demais."
{user} disse: "Você. Espero que não."
{user} disse: "Você tá sempre pra cima e pra baixo."
{user} disse: "Você, e agora você sabe."
{user} disse: "Você me parece ter um segredo."
{user} disse: "Você. Mas a gente conversa."
{user} disse: "Você anda perguntando pra todo mundo."
{user} disse: "Você, {user1}. Pronto."
{user} disse: "Você tá sempre com um plano."
{user} disse: "Você. E isso me deixa triste."
{user} disse: "Você me dá sinais estranhos."
{user} disse: "Você. Mas eu posso estar errado(a), claro."
{user} disse: "Você tá muito seguro(a) de si."
{user} disse: "Você, e eu vou ficar atento(a)."
{user} disse: "Você tá jogando muito sozinho(a)."
{user} disse: "Você. É isso."
{user} disse: "Você anda com cara de quem tem capa."
{user} disse: "Você, e eu nem sei por quê."
{user} disse: "Você tá sempre desviando."
{user} disse: "Você. Mas não conta pra ninguém que eu disse."
{user} disse: "Você tá me fazendo perguntas demais."
{user} disse: "Você, {user1}. E agora?"
{user} disse: "Você é meu primeiro nome."
{user} disse: "Você. Se não for, me desculpa depois."
{user} disse: "Você tá sempre por perto das conversas certas."
{user} disse: "Você, e vou continuar de olho."
{user} disse: "Você tem algo que não me convence."
{user} disse: "Você. Eu sinto."
{user} disse: "Você anda muito observador(a)."
{user} disse: "Você, e isso fica entre nós."
{user} disse: "Você é o(a) mais difícil de ler."
{user} disse: "Você. Mas eu queria confiar."
{user} disse: "Você tá sempre sabendo de tudo."
{user} disse: "Você, {user1}. Com dor no coração."
{user} disse: "Você me parece à vontade demais com as mortes."
{user} disse: "Você. Me prova que não."
{user} disse: "Você tá jogando um jogo que eu não entendo."
{user} disse: "Você, e é só isso que eu vou dizer."
{user} disse: "Você é suspeito(a) pra mim."
{user} disse: "Você. Não fica bravo(a)."
{user} disse: "Você anda muito quieto(a)."
{user} disse: "Você, e eu acho que não tô errado(a)."
{user} disse: "Você tá sempre por cima."
{user} disse: "Você. É minha aposta."
{user} disse: "Você tá me observando também, né?"
{user} disse: "Você, {user1}. Desculpa."
{user} disse: "Você tem o jeito que eu mais desconfio."
{user} disse: "Você. Mas amanhã pode mudar."
{user} disse: "Você anda muito bem-informado(a)."
{user} disse: "Você, e agora a conversa ficou estranha."
{user} disse: "Você tá no meu radar desde o começo."
{user} disse: "Você. Com todo respeito."
{user} disse: "Não fica bravo(a), mas... você."
{user} disse: "Você. Desculpa, é o que eu sinto."
{user} riu nervoso(a): "Tô perguntando pra quem eu desconfio. Adivinha."
{user} disse: "Você, {user1}. Você é difícil de ler."
{user} disse: "Sinceridade? Você me deixa com o pé atrás."
{user} disse: "Te conto: você tá no meu radar."
{user} disse: "Você. E essa pergunta só piorou."
{user} disse: "Vou ser honesto(a): você."
{user} disse: "Olhando bem pra você agora... você."
{user} disse: "Você pergunta demais. Por isso, você."
{user} disse: "Tá na minha frente, {user1}."
{user} disse: "Não é pessoal, mas desconfio de você."
{user} disse: "É você. E você sabe por quê."
{user} disse: "Você, {user1}. Me prova que eu tô errado(a)."
{user} disse: "O nome que me vem é o seu."
{user} disse: "Você. Não me pergunte mais."
`);

/** "O que você acha de {user2}?": o que a pessoa diz depende do quanto confia em {user2}. */
export const REPLY_OPINION = {
  certain: lines(`
{user} respondeu sobre {user2}: "Confio de olhos fechados."
{user} disse: "{user2}? Coloco a mão no fogo."
{user} disse: "{user2} é Fiel. Não tenho dúvida."
{user} disse: "{user2} é das pessoas mais leais daqui."
{user} disse: "Eu defendo {user2} até o fim."
{user} disse: "{user2} é meu porto seguro."
{user} disse: "Se {user2} for Traidor(a), eu desisto do jogo."
{user} disse: "{user2}? Gente boa demais."
{user} disse: "{user2} nunca me deu motivo pra desconfiar."
{user} disse: "Eu confio em {user2} mais que em mim."
{user} disse: "{user2} é transparente. Adoro."
{user} disse: "{user2} tem meu voto de confiança eterno."
{user} disse: "{user2} é família aqui dentro."
{user} disse: "Fiel. Fiel com F maiúsculo."
{user} disse: "{user2} é a pessoa mais sincera que conheci aqui."
{user} disse: "Eu jamais votaria em {user2}."
{user} disse: "{user2} é inocente como criança."
{user} disse: "{user2} tá do nosso lado, certeza."
{user} disse: "Eu confio em {user2} completamente."
{user} disse: "{user2}? Um amor de pessoa. E Fiel."
{user} disse: "{user2} é leal até o osso."
{user} disse: "{user2} é o(a) mais confiável daqui."
{user} disse: "{user2} me protege e eu protejo {user2}."
{user} disse: "Não tem nada de traição em {user2}."
{user} disse: "{user2} é incapaz de mentir."
{user} disse: "Pode confiar em {user2}. Eu confio."
{user} disse: "{user2} é o tipo de pessoa que a gente leva pra vida."
{user} disse: "Eu garanto {user2} com meu nome."
{user} disse: "{user2} é luz nesse castelo."
{user} disse: "{user2} é Fiel, e eu vou provar."
{user} disse: "{user2} é o meu melhor amigo(a) aqui."
{user} disse: "{user2}? Totalmente de confiança."
{user} disse: "{user2} tem o coração mais puro daqui."
{user} disse: "Eu apostaria minha vida em {user2}."
{user} disse: "{user2} é a última pessoa que eu acusaria."
{user} disse: "{user2} é verdade num lugar de mentira."
{user} disse: "{user2} não trairia nem uma formiga."
{user} disse: "{user2} é meu voto de fé."
{user} disse: "{user2} merece ganhar esse jogo."
{user} disse: "Eu confio em {user2} de corpo e alma."
{user} disse: "{user2} é o(a) Fiel mais fiel daqui."
`),
  faithful: lines(`
{user} pensou um pouco e respondeu sobre {user2}: "Acho que é Fiel."
{user} disse: "{user2} me parece do bem."
{user} disse: "Eu gosto de {user2}. Acho que é Fiel."
{user} disse: "{user2}? Não vejo maldade."
{user} disse: "{user2} tá do nosso lado, eu acho."
{user} disse: "Confio em {user2}, mas com um pé atrás."
{user} disse: "{user2} é tranquilo(a). Não me preocupa."
{user} disse: "Acho {user2} honesto(a)."
{user} disse: "{user2} não tá na minha lista."
{user} disse: "{user2} me passa uma energia boa."
{user} disse: "Eu votaria em muita gente antes de {user2}."
{user} disse: "{user2} parece sincero(a)."
{user} disse: "{user2} é gente boa, até onde eu vejo."
{user} disse: "Acho {user2} confiável. Na medida do possível."
{user} disse: "{user2} é Fiel, eu aposto."
{user} disse: "{user2} tem jeito de Fiel."
{user} disse: "Não desconfio de {user2}."
{user} disse: "{user2} é leal, pelo que eu vi."
{user} disse: "{user2}? Tá tranquilo(a) pra mim."
{user} disse: "{user2} me ajudou na missão. Gosto."
{user} disse: "{user2} é das pessoas boas aqui."
{user} disse: "{user2} me parece bem intencionado(a)."
{user} disse: "Eu acho que dá pra confiar em {user2}."
{user} disse: "{user2} é Fiel, até que provem o contrário."
{user} disse: "Gosto de {user2}. Parece verdadeiro(a)."
{user} disse: "{user2} não tem cara de traição."
{user} disse: "{user2} tá limpo(a) pra mim."
{user} disse: "{user2} é bom(boa) de convivência. E Fiel, acho."
{user} disse: "Eu confio mais em {user2} que na maioria."
{user} disse: "{user2} é do bem, sinto isso."
{user} disse: "{user2} tá mais pra aliado(a) que pra ameaça."
{user} disse: "{user2} é leal, eu acho."
{user} disse: "{user2} passa confiança."
{user} disse: "Eu não votaria em {user2} hoje."
{user} disse: "{user2} parece Fiel, sim."
{user} disse: "{user2} é simpático(a) e honesto(a)."
{user} disse: "Até agora, {user2} só me deu motivo pra confiar."
{user} disse: "{user2} é um(a) bom(boa) aliado(a), acho."
{user} disse: "{user2} tá do lado certo, pra mim."
{user} disse: "{user2} é Fiel. Uns noventa por cento."
`),
  unsure: lines(`
{user} deu de ombros sobre {user2}: "Ainda não sei."
{user} disse: "{user2}? Não consigo ler."
{user} disse: "{user2} é um mistério pra mim."
{user} disse: "Meio a meio com {user2}."
{user} disse: "{user2} às vezes me convence, às vezes não."
{user} disse: "Não tenho opinião formada sobre {user2}."
{user} disse: "{user2} fala pouco. Difícil saber."
{user} disse: "Tô em cima do muro com {user2}."
{user} disse: "{user2}? Pergunta difícil."
{user} disse: "Não sei se confio em {user2}."
{user} disse: "{user2} pode ser qualquer coisa."
{user} disse: "Ainda tô observando {user2}."
{user} disse: "{user2} me deixa em dúvida."
{user} disse: "Não sei o que pensar de {user2}."
{user} disse: "{user2} é neutro(a) pra mim."
{user} disse: "Ainda não formei ideia de {user2}."
{user} disse: "{user2} tem dias bons e dias estranhos."
{user} disse: "{user2}? Sei lá, viu."
{user} disse: "Não confio nem desconfio de {user2}."
{user} disse: "{user2} é uma incógnita."
{user} disse: "Preciso conversar mais com {user2}."
{user} disse: "{user2} não me passa nada. Nem bom, nem ruim."
{user} disse: "Talvez {user2}. Talvez não."
{user} disse: "{user2} tá no meu 'não sei'."
{user} disse: "Eu não conheço {user2} direito."
{user} disse: "{user2} às vezes some, às vezes aparece."
{user} disse: "Difícil dizer sobre {user2}."
{user} disse: "{user2} é quieto(a) demais pra eu ter certeza."
{user} disse: "Não tenho como te responder sobre {user2}."
{user} disse: "{user2}? Estou decidindo ainda."
{user} disse: "Não sei. {user2} é difícil de decifrar."
{user} disse: "{user2} é um ponto de interrogação."
{user} disse: "Não vou arriscar opinião sobre {user2}."
{user} disse: "{user2} me confunde."
{user} disse: "Às vezes acho que sim, às vezes que não."
{user} disse: "{user2} tá numa zona cinzenta pra mim."
{user} disse: "Não sei. E você, o que acha de {user2}?"
{user} disse: "{user2} ainda não me mostrou quem é."
{user} disse: "Pode ser que {user2} seja, pode ser que não."
{user} disse: "{user2}? Vamos ver nos próximos dias."
`),
  doubt: lines(`
{user} franziu a testa sobre {user2}: "Tem alguma coisa errada ali."
{user} disse: "{user2} não me convence."
{user} disse: "Desconfio um pouco de {user2}."
{user} disse: "{user2} tá estranho(a) ultimamente."
{user} disse: "Eu ficaria de olho em {user2}."
{user} disse: "{user2} me deixa com a pulga atrás da orelha."
{user} disse: "Não confio muito em {user2}."
{user} disse: "{user2} tá calmo(a) demais."
{user} disse: "{user2} tem um jeito que não me agrada."
{user} disse: "{user2} esconde alguma coisa."
{user} disse: "Eu não daria as costas pra {user2}."
{user} disse: "{user2} fala demais e diz de menos."
{user} disse: "{user2} tá na minha lista. No meio, mas tá."
{user} disse: "{user2} não me passa verdade."
{user} disse: "{user2} anda desviando de perguntas."
{user} disse: "{user2}? Hm. Sei não."
{user} disse: "{user2} tem algo de estranho."
{user} disse: "Eu tomaria cuidado com {user2}."
{user} disse: "{user2} anda cochichando demais."
{user} disse: "{user2} sabe mais do que diz."
{user} disse: "{user2} me olhou torto hoje."
{user} disse: "Eu tenho um pé atrás com {user2}."
{user} disse: "{user2} tá jogando bem demais."
{user} disse: "{user2} muda de ideia toda hora."
{user} disse: "Não gosto do jeito que {user2} vota."
{user} disse: "{user2} tem uma calma suspeita."
{user} disse: "{user2} me deixa desconfortável."
{user} disse: "{user2} tá sempre perto de quem morre."
{user} disse: "Desconfio de {user2}, mas sem prova."
{user} disse: "{user2} tem um sorriso que não me convence."
{user} disse: "{user2} não chora por ninguém."
{user} disse: "Eu não votaria em {user2}. Ainda."
{user} disse: "{user2} tá me evitando."
{user} disse: "{user2} tem cara de quem sobe a escada."
{user} disse: "{user2} tá jogando dos dois lados, acho."
{user} disse: "{user2} é muito calculista pra mim."
{user} disse: "{user2}? Fico com um pé atrás."
{user} disse: "Eu não confio totalmente em {user2}."
{user} disse: "{user2} tá sempre com resposta pronta."
{user} disse: "{user2} me deixa em alerta."
`),
  traitor: lines(`
{user} disse, sem hesitar, sobre {user2}: "Tenho quase certeza de que é Traidor(a)."
{user} disse: "{user2}? É Traidor(a). Guarda isso."
{user} disse: "Meu voto hoje é {user2}."
{user} disse: "{user2} é a cobra do castelo."
{user} disse: "Eu não confio em {user2} nem um milímetro."
{user} disse: "{user2} tem capa preta no armário, aposto."
{user} disse: "{user2} é o(a) Traidor(a) mais óbvio(a) daqui."
{user} disse: "Fica longe de {user2}."
{user} disse: "{user2} tá mentindo pra todo mundo."
{user} disse: "Se não for {user2}, eu não entendo mais nada."
{user} disse: "{user2} é perigo puro."
{user} disse: "{user2} sabe quem vai morrer. Eu sinto."
{user} disse: "{user2}? Traidor(a). Ponto."
{user} disse: "{user2} manipula todo mundo."
{user} disse: "Eu apostaria meu prêmio que {user2} é da torre."
{user} disse: "{user2} tá rindo da nossa cara."
{user} disse: "Não dá as costas pra {user2}. Nunca."
{user} disse: "{user2} é traição com sorriso."
{user} disse: "{user2} é o nome que eu escrevo hoje."
{user} disse: "{user2} tem sangue frio de Traidor(a)."
{user} disse: "{user2} é o lobo em pele de ovelha."
{user} disse: "Eu tenho certeza sobre {user2}."
{user} disse: "{user2} é a raiz de todo mal aqui."
{user} disse: "{user2} tá nos enganando desde o primeiro dia."
{user} disse: "{user2} é o(a) Traidor(a) que a gente procura."
{user} disse: "{user2} precisa sair hoje."
{user} disse: "{user2}? Nem me fala. É da torre."
{user} disse: "{user2} tem cara, jeito e voto de Traidor(a)."
{user} disse: "Eu vi {user2} agir como Traidor(a)."
{user} disse: "{user2} é o perigo número um."
{user} disse: "{user2} me engana não, é Traidor(a)."
{user} disse: "Pra mim, {user2} é Traidor(a) desde a chegada."
{user} disse: "{user2} tá afiando a adaga."
{user} disse: "{user2}? Culpado(a), sem dúvida."
{user} disse: "{user2} é bom(boa) demais em mentir."
{user} disse: "{user2} tem a frieza de quem mata."
{user} disse: "Eu votaria em {user2} de olhos fechados."
{user} disse: "{user2} é o(a) mais falso(a) daqui."
{user} disse: "{user2} é Traidor(a). E vai cair."
{user} disse: "{user2} tá com os dias contados."
`),
};

/** Chegada: "o que achou de {user2}?" (primeira impressão, sem falar do jogo). */
export const REPLY_FIRST_IMPRESSION = {
  love: lines(`
{user} olhou para {user2} do outro lado do salão: "Adorei. Parece gente boa demais."
{user} disse: "{user2}? Já é meu(minha) favorito(a)."
{user} disse: "{user2} é um amor de pessoa."
{user} disse: "Eu e {user2} vamos ser amigos, sinto isso."
{user} disse: "{user2} tem uma energia incrível."
{user} disse: "{user2}? Me encantou na hora."
{user} disse: "{user2} é simpatia pura."
{user} disse: "Eu quero {user2} perto de mim."
{user} disse: "{user2} tem o sorriso mais bonito daqui."
{user} disse: "{user2} parece aquele amigo(a) de infância."
{user} disse: "{user2} é luz. Adorei."
{user} disse: "Conversei com {user2} e já tô apaixonado(a) pela pessoa."
{user} disse: "{user2}? Maravilhoso(a)."
{user} disse: "{user2} é a melhor surpresa da noite."
{user} disse: "Eu gostei muito de {user2}. Muito."
{user} disse: "{user2} é muito carismático(a)."
{user} disse: "{user2} tem um coração enorme, dá pra ver."
{user} disse: "{user2} me fez rir a noite toda."
{user} disse: "{user2}? Top demais."
{user} disse: "Eu sinto que posso confiar em {user2}."
{user} disse: "{user2} é o tipo de pessoa que eu quero ao lado."
{user} disse: "{user2} me acolheu logo de cara."
{user} disse: "{user2}? Uma graça."
{user} disse: "{user2} é incrível, simples assim."
{user} disse: "{user2} tem um astral que contagia."
{user} disse: "Amei {user2}. Já quero dividir quarto."
{user} disse: "{user2} é muito fofo(a)."
{user} disse: "{user2}? Primeira impressão perfeita."
{user} disse: "{user2} é gente como a gente."
{user} disse: "{user2} é pura simpatia."
{user} disse: "Eu adorei {user2}. De verdade."
{user} disse: "{user2} tem um jeito muito doce."
{user} disse: "{user2}? Um anjo."
{user} disse: "{user2} tem tudo pra ser meu(minha) melhor amigo(a) aqui."
{user} disse: "{user2} brilha, né?"
{user} disse: "{user2}? Gostei de cara."
{user} disse: "{user2} é leve e divertido(a)."
{user} disse: "{user2} me conquistou em cinco minutos."
{user} disse: "{user2} é demais. Adorei."
{user} disse: "{user2}? Sensacional."
`),
  like: lines(`
{user} disse sobre {user2}: "Simpático(a). Acho que vamos nos dar bem."
{user} disse: "{user2}? Gente boa, parece."
{user} disse: "Gostei de {user2}. Tranquilo(a)."
{user} disse: "{user2} é legal, conversamos um pouco."
{user} disse: "{user2} parece uma pessoa boa."
{user} disse: "{user2}? Bacana."
{user} disse: "{user2} tem um papo bom."
{user} disse: "Achei {user2} educado(a)."
{user} disse: "{user2} é agradável."
{user} disse: "{user2} me pareceu gente fina."
{user} disse: "Gostei. {user2} é tranquilo(a)."
{user} disse: "{user2}? Legal, legal."
{user} disse: "{user2} parece do bem."
{user} disse: "{user2} tem um sorriso bonito."
{user} disse: "{user2} é simpático(a), sim."
{user} disse: "{user2} foi gentil comigo."
{user} disse: "{user2}? Boa companhia."
{user} disse: "Achei {user2} divertido(a)."
{user} disse: "{user2} parece fácil de conviver."
{user} disse: "{user2} é bom de papo."
{user} disse: "{user2}? Uma pessoa legal."
{user} disse: "Gostei do jeito de {user2}."
{user} disse: "{user2} me pareceu sincero(a)."
{user} disse: "{user2} é bem-humorado(a)."
{user} disse: "{user2}? Gente boa."
{user} disse: "{user2} tem uma vibe boa."
{user} disse: "{user2} foi muito educado(a)."
{user} disse: "{user2} parece calmo(a). Gostei."
{user} disse: "{user2}? Tranquilo(a), bacana."
{user} disse: "{user2} é interessante."
{user} disse: "Achei {user2} uma boa pessoa."
{user} disse: "{user2}? Simpático(a), sem dúvida."
{user} disse: "{user2} é engraçado(a)."
{user} disse: "{user2} parece que vai ser um bom companheiro(a)."
{user} disse: "{user2}? Gostei do papo."
{user} disse: "{user2} tem um jeito legal."
{user} disse: "{user2} me passou uma boa impressão."
{user} disse: "{user2}? Legal. Gostei."
{user} disse: "{user2} parece bem gente boa."
{user} disse: "{user2}? Primeira impressão boa."
`),
  meh: lines(`
{user} deu de ombros sobre {user2}: "Ainda não sei. Falou pouco."
{user} disse: "{user2}? Nem reparei muito."
{user} disse: "{user2} é normal. Nada demais."
{user} disse: "Não conversei com {user2} ainda."
{user} disse: "{user2}? Quieto(a)."
{user} disse: "{user2} não me marcou."
{user} disse: "Hm, {user2}. Sei lá."
{user} disse: "{user2} passou meio despercebido(a)."
{user} disse: "{user2}? Normal."
{user} disse: "Não tenho opinião de {user2} ainda."
{user} disse: "{user2} parece reservado(a)."
{user} disse: "{user2}? Nem bom nem ruim."
{user} disse: "{user2} é na dele(a)."
{user} disse: "Mal vi {user2}."
{user} disse: "{user2}? Preciso conversar mais."
{user} disse: "{user2} é tímido(a), acho."
{user} disse: "{user2} não me disse muita coisa."
{user} disse: "{user2}? Indiferente."
{user} disse: "{user2} é neutro(a) pra mim."
{user} disse: "{user2} tá no meu 'depois eu vejo'."
{user} disse: "{user2}? Não sei. Tá cedo."
{user} disse: "{user2} ficou num canto a noite toda."
{user} disse: "{user2}? Hm, nada a declarar."
{user} disse: "{user2} parece sério(a)."
{user} disse: "{user2} é difícil de ler."
{user} disse: "{user2}? Ainda tô decidindo."
{user} disse: "{user2} falou só o básico."
{user} disse: "{user2}? Não me chamou atenção."
{user} disse: "{user2} é misterioso(a)."
{user} disse: "Não sei o que achar de {user2}."
{user} disse: "{user2} parece cansado(a) da viagem."
{user} disse: "{user2}? Veremos."
{user} disse: "{user2} é na moita."
{user} disse: "{user2}? Tranquilo(a), acho."
{user} disse: "{user2} não disse nem boa noite."
{user} disse: "{user2}? Não tenho impressão nenhuma."
{user} disse: "{user2} parece ok."
{user} disse: "{user2}? Meh."
{user} disse: "{user2} é um mistério ainda."
{user} disse: "{user2}? Sem opinião."
`),
  dislike: lines(`
{user} torceu o nariz sobre {user2}: "Sei lá... meio metido(a)."
{user} disse: "{user2}? Achei arrogante."
{user} disse: "{user2} fala alto demais."
{user} disse: "Não fui muito com a cara de {user2}."
{user} disse: "{user2} se acha, né?"
{user} disse: "{user2} é meio antipático(a)."
{user} disse: "{user2}? Esnobe."
{user} disse: "{user2} me cortou no meio da frase."
{user} disse: "{user2} parece forçado(a)."
{user} disse: "{user2} quer aparecer demais."
{user} disse: "{user2}? Não me desceu."
{user} disse: "{user2} é meio grosso(a)."
{user} disse: "Achei {user2} bem chato(a)."
{user} disse: "{user2} tem cara de quem se acha."
{user} disse: "{user2}? Falso(a), acho."
{user} disse: "{user2} riu da roupa de alguém."
{user} disse: "{user2} é meio exibido(a)."
{user} disse: "{user2}? Metido(a) demais."
{user} disse: "{user2} não me cumprimentou direito."
{user} disse: "{user2} parece mimado(a)."
{user} disse: "{user2}? Hm, prefiro distância."
{user} disse: "{user2} é muito barulhento(a)."
{user} disse: "Não curti o jeito de {user2}."
{user} disse: "{user2} tem uma energia pesada."
{user} disse: "{user2}? Não sei, me incomodou."
{user} disse: "{user2} só fala de si."
{user} disse: "{user2} parece arrogante."
{user} disse: "{user2}? Não é minha pessoa favorita."
{user} disse: "{user2} é convencido(a)."
{user} disse: "Achei {user2} meio sem educação."
{user} disse: "{user2}? Estranho(a)."
{user} disse: "{user2} me deu preguiça."
{user} disse: "{user2} tem um jeito que não me agrada."
{user} disse: "{user2}? Um pouco antipático(a)."
{user} disse: "{user2} é do tipo que quer ser o centro."
{user} disse: "{user2}? Não gostei muito."
{user} disse: "{user2} parece difícil de conviver."
{user} disse: "{user2}? Meio falso(a)."
{user} disse: "{user2} me olhou de cima a baixo."
{user} disse: "{user2}? Primeira impressão ruim."
`),
  hate: lines(`
{user} fez careta sobre {user2}: "Não fui com a cara. Nem um pouco."
{user} disse: "{user2}? Insuportável."
{user} disse: "Eu não aguento {user2}."
{user} disse: "{user2} é a pior pessoa desse salão."
{user} disse: "{user2}? Não me faz falar."
{user} disse: "{user2} é falso(a) de doer."
{user} disse: "{user2} me irritou em dois minutos."
{user} disse: "{user2}? Detestei."
{user} disse: "Fica longe de {user2}, sério."
{user} disse: "{user2} é o tipo que eu evito lá fora."
{user} disse: "{user2}? Nojento(a) de arrogante."
{user} disse: "{user2} é chato(a) demais."
{user} disse: "{user2} tem uma energia horrível."
{user} disse: "{user2}? Credo."
{user} disse: "Não suporto {user2}."
{user} disse: "{user2} me tratou mal."
{user} disse: "{user2}? Um pesadelo."
{user} disse: "{user2} é grosseiro(a) e metido(a)."
{user} disse: "{user2}? Nem me lembra."
{user} disse: "{user2} é o(a) mais irritante que já vi."
{user} disse: "{user2}? Odiei, sinceramente."
{user} disse: "{user2} é pura arrogância."
{user} disse: "Eu não confiaria em {user2} nem pra segurar a porta."
{user} disse: "{user2}? Não passa na minha garganta."
{user} disse: "{user2} é o tipo de pessoa que eu bloquearia."
{user} disse: "{user2}? Horrível."
{user} disse: "{user2} é muito falso(a)."
{user} disse: "{user2} me deu calafrio. Do ruim."
{user} disse: "{user2}? Péssimo(a)."
{user} disse: "{user2} é insuportável de verdade."
{user} disse: "{user2}? Não gosto e não vou gostar."
{user} disse: "{user2} é a antipatia em pessoa."
{user} disse: "{user2}? Me poupe."
{user} disse: "{user2} tem cara de encrenca."
{user} disse: "{user2}? Detestável."
{user} disse: "{user2} é pior do que parece."
{user} disse: "{user2}? Eu passo longe."
{user} disse: "{user2} é pedante e chato(a)."
{user} disse: "{user2}? Ranço instantâneo."
{user} disse: "{user2}? Primeira impressão péssima."
`),
};
