-- =====================================================================
-- Frases iniciais para todos os momentos, com teor e comportamento.
--
-- Marcadores na simulação automática:
--   {user}   quem fala
--   {user1}  de quem se fala (escolhido pelo teor: aliado na defesa, suspeito na acusação...)
--   {user2}  outra pessoa (na defesa, quem está acusando; na torre, outro traidor)
--   {victim} quem acabou de sair (morto da noite no café, banido na reação da mesa)
-- Na torre dos traidores, {user} e {user2} são traidores e {user1} é o fiel na mira.
-- =====================================================================

INSERT INTO phrases (phase, tone, behavior_id, text)
SELECT v.phase::phrase_phase, v.tone::phrase_tone, b.id, v.text
FROM (VALUES
  -- ------------------------------------------------------------ chegada
  ('ARRIVAL', 'FRIENDLY', 'Querido', '{user} abraçou {user1} logo na porta: "Eu sinto que a gente vai longe juntos."'),
  ('ARRIVAL', 'FRIENDLY', 'Amado', '{user} ofereceu uma taça de champanhe a {user1} e em minutos os dois riam como velhos amigos.'),
  ('ARRIVAL', 'FRIENDLY', 'Fofoqueiro', '{user} elogiou o sotaque de {user1} e em cinco minutos já sabia a vida inteira dele(a).'),
  ('ARRIVAL', 'FRIENDLY', 'Ingênuo', '"{user1}, você tem cara de gente boa. Senta aqui do meu lado", disse {user}, sem pensar duas vezes.'),
  ('ARRIVAL', 'FRIENDLY', NULL, '{user} e {user1} descobriram que são da mesma cidade e não se desgrudaram mais durante o jantar.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} tropeçou no tapete do salão principal e {user1} não conseguiu segurar a gargalhada.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} perguntou se o castelo tinha wi-fi. {user1} respondeu: "Só sinal de fumaça."'),
  ('ARRIVAL', 'HUMOR', 'Dramático', '{user} fez uma entrada triunfal de óculos escuros, mesmo com toda a neblina das Highlands.'),
  ('ARRIVAL', 'NEUTRAL', NULL, '{user} e {user1} ficaram admirando as armaduras do corredor em silêncio.'),
  ('ARRIVAL', 'NEUTRAL', NULL, '{user} contou para {user1} que nunca tinha pisado num castelo de verdade.'),
  ('ARRIVAL', 'NEUTRAL', 'Tímido', '{user} se sentou perto da lareira e ficou observando cada pessoa que entrava.'),
  ('ARRIVAL', 'SUSPICION', 'Paranoico', '{user} cochichou: "Não sei explicar, mas {user1} entrou sorrindo demais."'),
  ('ARRIVAL', 'SUSPICION', 'Astuto', '{user} reparou que {user1} decorou o nome de todo mundo em minutos. "Isso é jogo."'),
  ('ARRIVAL', 'SUSPICION', 'Estrategista', '"Primeira regra: não confiar em quem chega simpático demais", disse {user}, com os olhos em {user1}.'),
  ('ARRIVAL', 'ALLIANCE', 'Fiel', '{user} puxou {user1} para um canto: "Você e eu. Até o fim, combinado?"'),
  ('ARRIVAL', 'ALLIANCE', 'Fiel', '{user} e {user1} apertaram as mãos na escadaria: "Se um cair, o outro vinga."'),
  ('ARRIVAL', 'ALLIANCE', 'Manipulador', '{user} ofereceu um pacto a {user1} com um sorriso calculado demais.'),
  ('ARRIVAL', 'CONFLICT', 'Invejoso', '{user} revirou os olhos quando {user1} pediu a atenção de todos para um brinde.'),
  ('ARRIVAL', 'CONFLICT', 'Explosivo', '{user} e {user1} discutiram pelo melhor quarto do castelo antes mesmo do jantar.'),
  ('ARRIVAL', 'CONFLICT', 'Competitivo', '{user} avisou que ia ganhar todas as missões. {user1} respondeu, seco(a): "Vamos ver."'),
  ('ARRIVAL', 'EMOTION', 'Dramático', '{user} se emocionou ao ver o castelo iluminado: "Eu sonhei com isso a vida inteira."'),

  -- ------------------------------------------------------------ café da manhã
  ('BREAKFAST', 'EMOTION', 'Dramático', '{user} desabou ao ver a cadeira vazia de {victim}: "Era a pessoa mais honesta desta casa!"'),
  ('BREAKFAST', 'EMOTION', 'Fiel', '{user} ergueu a xícara: "Um brinde a {victim}, que não merecia isso."'),
  ('BREAKFAST', 'EMOTION', NULL, '{user} não tocou no café. "Eu dormi no quarto ao lado de {victim} e não ouvi nada."'),
  ('BREAKFAST', 'EMOTION', 'Querido', '{user} abraçou {user1} em silêncio. Ninguém precisou dizer nada.'),
  ('BREAKFAST', 'EMOTION', 'Tímido', '{user} confessou baixinho a {user1}: "Toda manhã eu acho que vai ser eu."'),
  ('BREAKFAST', 'SUSPICION', 'Paranoico', '{user} reparou em quem chegou por último: "{user1} entrou calmo(a) demais para quem acabou de perder {victim}."'),
  ('BREAKFAST', 'SUSPICION', NULL, '"Mataram {victim} porque estava chegando perto de alguém. De quem, {user1}?", perguntou {user}.'),
  ('BREAKFAST', 'SUSPICION', 'Fofoqueiro', '{user} comentou com {user2}: "Repara como {user1} nunca parece surpreso(a)."'),
  ('BREAKFAST', 'SUSPICION', 'Estrategista', '{user} anotou o nome de {user1} num guardanapo. "Só por garantia."'),
  ('BREAKFAST', 'SUSPICION', 'Fofoqueiro', '"{victim} desconfiava de {user1}. Eu ouvi com esses ouvidos", espalhou {user}.'),
  ('BREAKFAST', 'ACCUSATION', 'Explosivo', '{user} bateu na mesa: "{user1}, onde você estava ontem à meia-noite?"'),
  ('BREAKFAST', 'ACCUSATION', NULL, '{user} apontou o garfo para {user1}: "Você tem cara de quem dorme muito bem à noite."'),
  ('BREAKFAST', 'FRIENDLY', 'Querido', '{user} guardou um croissant para {user1}: "Come, vai ser um dia longo."'),
  ('BREAKFAST', 'FRIENDLY', 'Amado', '{user} fez {user1} rir contando histórias da infância e aliviou o clima da mesa.'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} chegou de roupão e anunciou: "Se eu morrer hoje, quero ser lembrado(a) assim."'),
  ('BREAKFAST', 'HUMOR', NULL, '"Estou vivo(a)! Alguém mais surpreso(a) do que eu?", brincou {user}.'),
  ('BREAKFAST', 'HUMOR', 'Fofoqueiro', '{user} jurou para {user1} que o mingau estava com gosto de traição.'),
  ('BREAKFAST', 'CONFLICT', 'Explosivo', '{user} e {user1} discutiram porque um acusou o outro de fingir choro ontem.'),
  ('BREAKFAST', 'CONFLICT', 'Invejoso', '{user} não suportou os elogios que {user1} recebeu e largou o café pela metade.'),
  ('BREAKFAST', 'CONFLICT', NULL, '"Você votou em mim ontem, {user1}. Eu não esqueço", disse {user}, sem levantar os olhos.'),
  ('BREAKFAST', 'ALLIANCE', 'Fiel', '{user} piscou para {user1} do outro lado da mesa: o pacto continua de pé.'),
  ('BREAKFAST', 'ALLIANCE', 'Estrategista', '{user} sussurrou para {user1}: "Hoje a gente vota junto. Confia em mim."'),
  ('BREAKFAST', 'DEFENSE', 'Fiel', '"Parem de olhar para {user1}! Eu respondo por ele(a)", disse {user}.'),
  ('BREAKFAST', 'DEFENSE', NULL, '{user} saiu em defesa de {user1} assim que {user2} começou a insinuar coisas.'),
  ('BREAKFAST', 'NEUTRAL', NULL, '{user} comentou com {user1} que a missão de hoje devia envolver água gelada. De novo.'),
  ('BREAKFAST', 'NEUTRAL', 'Tímido', '{user} passou o café inteiro calado(a), só observando quem falava demais.'),

  -- ------------------------------------------------------------ missão
  ('MISSION', 'NEUTRAL', NULL, '{user} leu as instruções em voz alta enquanto {user1} já corria na direção errada.'),
  ('MISSION', 'NEUTRAL', NULL, '{user} e {user1} dividiram as tarefas sem trocar uma palavra.'),
  ('MISSION', 'HUMOR', NULL, '{user} escorregou na lama e arrastou {user1} junto. Os dois riram até chorar.'),
  ('MISSION', 'HUMOR', 'Dramático', '{user} gritou "estratégia!" e saiu correndo sem estratégia nenhuma.'),
  ('MISSION', 'HUMOR', NULL, '{user} jurou para {user1} que a neblina das Highlands estava do lado dos Traidores.'),
  ('MISSION', 'FRIENDLY', 'Querido', '{user} ajudou {user1} a atravessar a parte mais difícil sem pensar duas vezes.'),
  ('MISSION', 'FRIENDLY', 'Amado', '{user} vibrou com cada acerto de {user1} como se fosse o próprio.'),
  ('MISSION', 'CONFLICT', 'Competitivo', '{user} tomou a frente e {user1} reclamou: "Ninguém te escolheu capitão(ã)!"'),
  ('MISSION', 'CONFLICT', 'Explosivo', '{user} acusou {user1} de fazer corpo mole na frente de todo mundo.'),
  ('MISSION', 'CONFLICT', 'Invejoso', '{user} não aguentou ver {user1} levando o crédito e corrigiu cada detalhe em voz alta.'),
  ('MISSION', 'SUSPICION', 'Paranoico', '{user} reparou que {user1} errou justo a parte mais fácil. "Estranho, né?"'),
  ('MISSION', 'SUSPICION', NULL, '{user} sussurrou para {user2}: "Se alguém quer sabotar essa missão, é {user1}."'),
  ('MISSION', 'SUSPICION', 'Astuto', '"Por que {user1} não quis ficar com o escudo?", perguntou {user}, desconfiado(a).'),
  ('MISSION', 'ALLIANCE', 'Fiel', '{user} fez questão de ficar no mesmo grupo que {user1}: "A gente se protege."'),
  ('MISSION', 'EMOTION', 'Dramático', '{user} chorou de alegria quando o dinheiro entrou no pote.'),
  ('MISSION', 'EMOTION', 'Tímido', '{user} ficou em silêncio depois de errar, com medo de virar alvo na mesa redonda.'),

  -- ------------------------------------------------------------ mesa redonda
  ('ROUND_TABLE', 'ACCUSATION', 'Explosivo', '{user} se levantou: "Eu não tenho dúvida nenhuma. {user1}, você é Traidor(a)!"'),
  ('ROUND_TABLE', 'ACCUSATION', 'Estrategista', '"Olhem os votos. {user1} sempre segue a maioria no último segundo", disparou {user}.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Paranoico', '{user} encarou {user1}: "Seu olho tremeu quando falaram de assassinato. Eu vi."'),
  ('ROUND_TABLE', 'ACCUSATION', 'Carismático', '{user} fez um discurso impecável contra {user1} e a mesa inteira ficou em silêncio.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Invejoso', '"{user1}, você é bom(boa) demais nesse jogo para ser Fiel", disse {user}, com um sorriso torto.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Manipulador', '{user} insinuou, com toda a calma do mundo, que {user1} tinha algo a esconder.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Fofoqueiro', '{user} contou para a mesa inteira o que ouviu {user1} dizer no corredor.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Ingênuo', '{user} apontou para {user1}: "Eu posso estar errado(a), mas eu voto com o coração."'),
  ('ROUND_TABLE', 'ACCUSATION', 'Competitivo', '"Três dias, três votos em Fiéis. Explica isso, {user1}", cobrou {user}.'),
  ('ROUND_TABLE', 'ACCUSATION', NULL, '"Eu vou votar em {user1}, e vou dizer por quê", começou {user}, com a voz firme.'),
  ('ROUND_TABLE', 'SUSPICION', 'Tímido', '{user} disse, quase sem voz, que {user1} está estranho(a) desde ontem.'),
  ('ROUND_TABLE', 'SUSPICION', 'Paranoico', '"Tem alguma coisa em {user1} que não fecha", repetiu {user}, pela terceira vez.'),
  ('ROUND_TABLE', 'SUSPICION', NULL, '{user} perguntou a {user1} por que mudou de voto na última hora ontem.'),
  ('ROUND_TABLE', 'SUSPICION', 'Astuto', '{user} lembrou a todos que {user1} foi o(a) único(a) que não se abalou com a última morte.'),
  ('ROUND_TABLE', 'DEFENSE', 'Fiel', '"{user1} é Fiel. Eu coloco a minha mão no fogo", declarou {user}.'),
  ('ROUND_TABLE', 'DEFENSE', 'Explosivo', '{user} rebateu {user2}: "Você está atacando {user1} porque está com medo de ser o(a) próximo(a)."'),
  ('ROUND_TABLE', 'DEFENSE', 'Carismático', '{user} defendeu {user1} com um discurso tão bonito que até {user2} abaixou a cabeça.'),
  ('ROUND_TABLE', 'DEFENSE', 'Dramático', '"Se {user1} for Traidor(a), eu saio deste castelo agora mesmo", gritou {user}.'),
  ('ROUND_TABLE', 'DEFENSE', 'Ingênuo', '{user} lembrou que {user1} foi quem mais se esforçou na missão. "Traidor não se esforça assim."'),
  ('ROUND_TABLE', 'DEFENSE', NULL, '{user} pediu calma: "Vocês estão caçando {user1} sem nenhuma prova."'),
  ('ROUND_TABLE', 'CONFLICT', 'Explosivo', '{user} e {user1} trocaram acusações aos gritos até alguém pedir ordem na mesa.'),
  ('ROUND_TABLE', 'CONFLICT', NULL, '"Você votou em mim ontem e ainda fala em confiança?", disparou {user} contra {user1}.'),
  ('ROUND_TABLE', 'CONFLICT', 'Invejoso', '{user} riu com desprezo enquanto {user1} tentava se defender.'),
  ('ROUND_TABLE', 'CONFLICT', 'Dramático', '{user} bateu a mão na mesa quando {user1} mencionou o nome dele(a).'),
  ('ROUND_TABLE', 'EMOTION', 'Dramático', '{user} chorou: "Eu sou Fiel. Eu juro pela minha família."'),
  ('ROUND_TABLE', 'EMOTION', NULL, '{user} ficou olhando a cadeira vazia de {victim} por um longo tempo.'),
  ('ROUND_TABLE', 'EMOTION', 'Explosivo', '"{victim} saiu, mas o jogo continua. E eu estou de olho em cada um de vocês", disse {user}.'),
  ('ROUND_TABLE', 'EMOTION', 'Querido', '{user} abraçou {victim} antes da saída e prometeu terminar o jogo pelos dois.'),
  ('ROUND_TABLE', 'CONFLICT', 'Explosivo', '"Parabéns a todo mundo que votou em {victim}. Espero que estejam orgulhosos", ironizou {user}.'),
  ('ROUND_TABLE', 'EMOTION', 'Dramático', '{user} soluçou quando {victim} se levantou da cadeira: "Não era para ser assim."'),
  ('ROUND_TABLE', 'EMOTION', 'Fiel', '{user} prometeu em voz alta que vai descobrir quem empurrou {victim} para fora do jogo.'),
  ('ROUND_TABLE', 'SUSPICION', 'Astuto', '{user} anotou mentalmente quem votou em {victim} e quem mudou de ideia no último segundo.'),
  ('ROUND_TABLE', 'SUSPICION', 'Paranoico', '"Quem puxou os votos contra {victim}? Porque essa pessoa sabia de algo", disse {user}.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Carismático', '{user} olhou para {user1}: "Você liderou o ataque contra {victim}. Amanhã é a sua vez de explicar."'),
  ('ROUND_TABLE', 'NEUTRAL', NULL, '{user} pediu a palavra, respirou fundo e admitiu que ainda não tinha decidido o voto.'),
  ('ROUND_TABLE', 'ALLIANCE', 'Fiel', '{user} olhou para {user1} antes de votar. Os dois assentiram ao mesmo tempo.'),

  -- ------------------------------------------------------------ torre dos traidores
  ('TRAITORS_MEETING', 'STRATEGY', 'Estrategista', '{user} abriu o mapa do castelo sobre a mesa: "{user1} está chegando perto demais. É hoje."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Astuto', '"Se matarmos {user1}, vão desconfiar de quem brigou com ele(a) ontem", calculou {user}.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Manipulador', '{user} sugeriu deixar {user1} vivo(a): "A mesa redonda vai banir por nós."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Invejoso', '{user} sorriu: "Todo mundo ama {user1}. Por isso mesmo."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Manipulador', '"{user1} confia em mim cegamente. Isso vale mais vivo do que morto", disse {user}.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Competitivo', '{user} riscou o nome de {user1} na lista: "Ameaça. Ponto final."'),
  ('TRAITORS_MEETING', 'STRATEGY', NULL, '{user} propôs matar {user1} para jogar a suspeita em cima de quem o(a) acusou.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Estrategista', '{user} avisou {user2}: "Se você continuar defendendo {user1} na mesa, vão desconfiar de você."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Carismático', '{user} garantiu que amanhã convence a mesa inteira de que {user1} é o(a) culpado(a).'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Explosivo', '{user} e {user2} discutiram por causa de {user1} e quase apagaram as velas da torre.'),
  ('TRAITORS_MEETING', 'CONFLICT', NULL, '"Você está ficando mole, {user2}", disse {user}, quando {user2} hesitou em escolher {user1}.'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Paranoico', '{user} desconfia que {user2} vai traí-lo(a) na próxima mesa redonda.'),
  ('TRAITORS_MEETING', 'HUMOR', 'Dramático', '{user} brincou: "Amanhã no café eu vou chorar mais que todo mundo."'),
  ('TRAITORS_MEETING', 'HUMOR', NULL, '{user} ensaiou a cara de surpresa para o café da manhã na frente de {user2}.'),
  ('TRAITORS_MEETING', 'EMOTION', 'Fiel', '{user} confessou a {user2} que não aguenta mais mentir para {user1}.'),
  ('TRAITORS_MEETING', 'NEUTRAL', 'Tímido', '{user} acendeu as velas e esperou os outros em silêncio.'),

  -- ------------------------------------------------------------ mesa final
  ('ENDGAME', 'ACCUSATION', 'Paranoico', '"Chegamos até aqui e eu ainda não confio em {user1}", disse {user}.'),
  ('ENDGAME', 'ACCUSATION', 'Competitivo', '{user} pediu mais uma rodada: "Não vou dividir o prêmio com {user1}."'),
  ('ENDGAME', 'ACCUSATION', NULL, '{user} olhou para {user1}: "Se eu estiver errado(a), me perdoa. Mas eu preciso ter certeza."'),
  ('ENDGAME', 'DEFENSE', 'Fiel', '{user} segurou a mão de {user1}: "Eu sei quem você é. Vamos encerrar."'),
  ('ENDGAME', 'DEFENSE', NULL, '"{user1} provou que é Fiel dez vezes", insistiu {user}, encarando {user2}.'),
  ('ENDGAME', 'EMOTION', 'Dramático', '{user} chorou lembrando de todos que ficaram pelo caminho.'),
  ('ENDGAME', 'EMOTION', NULL, '"Eu nunca menti para vocês", disse {user}, com a mão no peito.'),
  ('ENDGAME', 'EMOTION', 'Tímido', '{user} ficou em silêncio por um longo minuto antes de conseguir falar.'),
  ('ENDGAME', 'SUSPICION', 'Paranoico', '{user} olhou para cada rosto da mesa: "Um de vocês ainda está mentindo."'),
  ('ENDGAME', 'SUSPICION', NULL, '{user} lembrou que {user1} nunca votou num Traidor. Nenhuma vez.'),
  ('ENDGAME', 'ALLIANCE', 'Fiel', '{user} e {user1} trocaram um olhar: chegaram juntos e querem sair juntos.'),
  ('ENDGAME', 'CONFLICT', 'Explosivo', '{user} explodiu com {user1}: "Você me usou o jogo inteiro!"'),
  ('ENDGAME', 'CONFLICT', 'Invejoso', '{user} disse a {user1}: "Você não merece um centavo desse prêmio."')
) AS v(phase, tone, behavior, text)
LEFT JOIN behaviors b ON lower(b.name) = lower(v.behavior)
ON CONFLICT DO NOTHING;
