-- =====================================================================
-- Frases da CHEGADA ao castelo.
-- {user} fala; {user1} é escolhido pelo teor; {user2} é outra pessoa presente.
-- =====================================================================

INSERT INTO phrases (phase, tone, behavior_id, text)
SELECT 'ARRIVAL'::phrase_phase, v.tone::phrase_tone, b.id, v.text
FROM (VALUES
  -- amizade
  ('FRIENDLY', 'Querido', '{user} já sabia o nome, a idade e o signo de {user1} antes de chegarem ao salão.'),
  ('FRIENDLY', 'Carente', '{user} abraçou {user1} três vezes em dez minutos. {user1} parou de contar.'),
  ('FRIENDLY', 'Amado', '{user} dividiu o guarda-chuva com {user1} na chuva escocesa, e isso bastou para virar amizade.'),
  ('FRIENDLY', 'Protetor', '{user} ajudou {user1} com a mala pela escadaria inteira: "Aqui ninguém fica para trás."'),
  ('FRIENDLY', 'Diplomata', '{user} apresentou {user1} a todo mundo como se fosse anfitrião(ã) do castelo.'),
  ('FRIENDLY', 'Brincalhão', '{user} fez {user1} rir tanto que o champanhe saiu pelo nariz.'),
  ('FRIENDLY', 'Ingênuo', '"Você tem cara de quem nunca mentiu na vida", disse {user} para {user1}. Nunca se sabe.'),
  ('FRIENDLY', NULL, '{user} e {user1} descobriram que torcem para o mesmo time. Pronto, aliança espiritual selada.'),
  ('FRIENDLY', NULL, '{user} elogiou o casaco de {user1}, que respondeu: "É para esconder a adaga." Os dois gargalharam.'),
  ('FRIENDLY', NULL, '{user} ofereceu o lugar perto da lareira para {user1}. Gentileza ou estratégia? Ninguém sabe.'),
  ('FRIENDLY', NULL, '{user} e {user1} tiraram uma selfie mental na frente do castelo, já que os celulares ficaram na portaria.'),
  ('FRIENDLY', 'Heroico', '{user} carregou a mala de {user1} e a própria ao mesmo tempo, subindo a colina sem reclamar.'),
  ('FRIENDLY', 'Sonso', '{user} sorriu para {user1} com um sorriso tão doce que ninguém desconfiou de nada.'),
  ('FRIENDLY', 'Fofoqueiro', '{user} contou para {user1} tudo que já sabia sobre os outros convidados. Eram só quinze minutos de jogo.'),
  ('FRIENDLY', NULL, '{user} prometeu a {user1} que, se os dois chegassem à final, pagaria um jantar com o prêmio.'),
  ('FRIENDLY', 'Líder', '{user} reuniu {user1} e mais alguns no canto: "Vamos fazer desse grupo o mais unido da história do programa."'),
  ('FRIENDLY', NULL, '{user} ensinou {user1} a pronunciar "Highlands" com sotaque escocês. Ficou pior.'),
  ('FRIENDLY', 'Carismático', '{user} contou a história da própria vida e {user1} já estava emocionado(a) no segundo capítulo.'),
  ('FRIENDLY', NULL, '{user} e {user1} dividiram o último canapé de salmão como quem assina um tratado de paz.'),
  ('FRIENDLY', 'Querido', '{user} guardou uma taça de champanhe para {user1}, que chegou atrasado(a) e ensopado(a).'),
  ('FRIENDLY', NULL, '"Se eu for assassinado(a), cuida do meu travesseiro", pediu {user} a {user1}, já íntimos.'),
  ('FRIENDLY', NULL, '{user} jurou a {user1} que o castelo tem cheiro de biblioteca antiga. {user1} jurou que é mofo.'),
  ('FRIENDLY', 'Protetor', '{user} viu {user1} tremendo de frio e emprestou o cachecol sem dizer uma palavra.'),
  ('FRIENDLY', 'Amado', 'Bastou {user} entrar no salão para {user1} dizer: "Você eu quero no meu time."'),
  ('FRIENDLY', NULL, '{user} e {user1} combinaram um aperto de mão secreto. Ficou tão complicado que nenhum dos dois lembra.'),

  -- humor
  ('HUMOR', NULL, '{user} chegou de salto alto na trilha de lama. Durou quatro passos.'),
  ('HUMOR', 'Dramático', '{user} entrou no castelo cantando uma ópera inventada. {user1} aplaudiu por educação.'),
  ('HUMOR', NULL, '{user} perguntou se o castelo tinha elevador. O mordomo nem respondeu.'),
  ('HUMOR', 'Brincalhão', '"Se alguém aqui for traidor, levanta a mão", disse {user}. {user1} quase levantou por reflexo.'),
  ('HUMOR', NULL, '{user} confundiu uma armadura com um convidado e cumprimentou: "Prazer, você é de onde?"'),
  ('HUMOR', NULL, '{user} trouxe cinco malas para um jogo em que pode ser assassinado(a) na primeira noite.'),
  ('HUMOR', NULL, '{user} perguntou a {user1} se o capuz dos traidores vem em outros tamanhos.'),
  ('HUMOR', 'Caótico', '{user} anunciou que vai votar em quem tiver o pior sapato. {user1} olhou para os próprios pés, preocupado(a).'),
  ('HUMOR', NULL, '{user} achou que a gaita de foles era um alarme de incêndio e correu para a porta.'),
  ('HUMOR', 'Arrogante', '{user} se apresentou como "o(a) futuro(a) vencedor(a)". {user1} já decidiu votar nele(a) por esporte.'),
  ('HUMOR', NULL, '{user} tentou abrir a porta do salão empurrando. Era de puxar. Todos viram.'),
  ('HUMOR', NULL, '{user} jurou que viu um fantasma na escada. Era {user1} de roupão.'),
  ('HUMOR', 'Brincalhão', '{user} fingiu desmaiar quando ouviu a palavra "assassinato". {user1} não sabia se ria ou chamava o médico.'),
  ('HUMOR', NULL, '{user} disse que veio pelo dinheiro, pela fama e pelo café da manhã, não necessariamente nessa ordem.'),
  ('HUMOR', NULL, '"Eu não sei mentir", disse {user}, piscando os dois olhos ao mesmo tempo para {user1}.'),
  ('HUMOR', 'Chorão', '{user} chorou na chegada porque o castelo era "bonito demais". Ainda nem tinha começado.'),
  ('HUMOR', NULL, '{user} perguntou se podia escolher ser traidor(a). {user1} respondeu: "Agora eu sei em quem votar."'),
  ('HUMOR', NULL, '{user} escorregou no tapete persa e fez uma pose de quem tinha planejado aquilo.'),
  ('HUMOR', NULL, '{user} trouxe um livro chamado "Como identificar mentirosos". {user1} pediu emprestado. Suspeito.'),
  ('HUMOR', 'Fofoqueiro', '{user} já tinha apelidado metade do elenco antes do jantar. {user1} virou "o(a) do casaco suspeito".'),
  ('HUMOR', NULL, '{user} perguntou a {user1} se o vinho era envenenado. {user1} bebeu tudo de uma vez para provar que não.'),
  ('HUMOR', 'Ovelha', '{user} concordou com tudo que {user1} disse, inclusive quando {user1} se contradisse.'),
  ('HUMOR', NULL, '{user} tentou fazer uma reverência para o apresentador e bateu a cabeça na mesa.'),
  ('HUMOR', 'Rebelde', '{user} chegou de moletom em um jantar de gala. "Traidor não se veste pra agradar ninguém."'),
  ('HUMOR', NULL, '{user} contou que a mãe mandou "não confiar em ninguém e comer bem". Metade já foi cumprida.'),
  ('HUMOR', NULL, '{user} batizou o próprio quarto de "bunker" e anunciou que vai dormir de capacete.'),
  ('HUMOR', 'Dramático', '{user} olhou para o lustre gigante e sussurrou: "Isso aí cai em alguém até o fim da temporada."'),
  ('HUMOR', NULL, '{user} perguntou se tem Wi-Fi na torre dos traidores. {user1} respondeu: "Só se você for traidor(a)."'),
  ('HUMOR', NULL, 'Na primeira hora, {user} já tinha perdido a chave do quarto, a paciência e um sapato.'),
  ('HUMOR', 'Caótico', '{user} jurou que ia votar em si mesmo(a) só para ver o que acontece. Não pode. Ficou decepcionado(a).'),
  ('HUMOR', NULL, '{user} fez questão de apertar a mão de todo mundo "para sentir a energia". A de {user1} estava gelada. Suspeito.'),
  ('HUMOR', NULL, '{user} perguntou se existe seguro de vida no contrato. {user1} riu nervoso(a).'),
  ('HUMOR', 'Arrogante', '{user} disse que já assistiu a todas as temporadas e sabe tudo. Tropeçou no degrau logo depois.'),
  ('HUMOR', NULL, '{user} e {user1} dançaram gaita de foles como se fosse forró. Não era.'),
  ('HUMOR', NULL, '{user} batizou o corvo do jardim de "Juiz" e disse que ele vai decidir os votos.'),
  ('HUMOR', 'Brincalhão', '{user} ensaiou a cara de "sou fiel" no espelho do corredor e {user1} flagrou tudo.'),
  ('HUMOR', NULL, '{user} disse que o único traidor que conhece é o próprio estômago, que pediu mais sobremesa.'),
  ('HUMOR', NULL, '{user} descobriu que o quarto não tem tomada perto da cama e declarou luto oficial.'),
  ('HUMOR', 'Fofoqueiro', '{user} já criou um grupo imaginário de fofoca chamado "Sussurros da Torre". {user1} foi o primeiro membro.'),

  -- neutro
  ('NEUTRAL', NULL, '{user} e {user1} ficaram admirando as tapeçarias do corredor sem trocar uma palavra.'),
  ('NEUTRAL', NULL, '{user} contou a {user1} que largou o emprego para estar ali.'),
  ('NEUTRAL', 'Tímido', '{user} passou a chegada inteira encostado(a) na parede, observando.'),
  ('NEUTRAL', 'Observador', '{user} anotou mentalmente quem pegou o champanhe primeiro. Isso vai importar.'),
  ('NEUTRAL', NULL, '{user} perguntou a {user1} quantos anos tem o castelo. Ninguém soube responder.'),
  ('NEUTRAL', NULL, '{user} explicou a {user1} as regras do jogo, que {user1} já sabia de cor.'),
  ('NEUTRAL', NULL, '{user} e {user1} conversaram sobre família, trabalho e o frio absurdo da Escócia.'),
  ('NEUTRAL', 'Frio', '{user} cumprimentou todos com o mesmo aperto de mão seco. Nem um sorriso a mais.'),
  ('NEUTRAL', NULL, '{user} disse a {user1} que vai jogar limpo. Todos dizem isso.'),
  ('NEUTRAL', 'Estrategista', '{user} contou quantas cadeiras tem a mesa redonda e fez as contas em silêncio.'),
  ('NEUTRAL', NULL, '{user} ficou olhando para a torre do castelo por um bom tempo antes de entrar.'),
  ('NEUTRAL', NULL, '{user} e {user1} trocaram histórias de viagens até o jantar ser servido.'),
  ('NEUTRAL', 'Detetive', '{user} observou as mãos de cada convidado durante o brinde. Diz que mentiroso não sabe segurar taça.'),
  ('NEUTRAL', NULL, '{user} perguntou se {user1} já tinha jogado algo parecido. {user1} disse que só jogo de tabuleiro com a família.'),
  ('NEUTRAL', NULL, '{user} escolheu o quarto mais perto da escada: "Para fugir mais rápido."'),
  ('NEUTRAL', 'Observador', '{user} percebeu que {user1} olhou para a torre duas vezes. Guardou a informação.'),
  ('NEUTRAL', NULL, '{user} e {user1} dividiram o banco do barco na travessia do lago, em silêncio absoluto.'),
  ('NEUTRAL', NULL, '{user} contou que é a primeira vez que sai do país. {user1} achou isso adorável.'),
  ('NEUTRAL', 'Sonso', '{user} disse a {user1} que "nem sabe direito como o jogo funciona". Sabe sim.'),
  ('NEUTRAL', NULL, '{user} brindou "a quem chegar até o fim". Alguns copos demoraram a subir.'),

  -- suspeita
  ('SUSPICION', 'Paranoico', '{user} já desconfia de {user1}: "Quem chega sorrindo desse jeito tem algo a esconder."'),
  ('SUSPICION', 'Detetive', '{user} reparou que {user1} desviou o olhar quando falaram em traidores. Primeira anotação do caderno.'),
  ('SUSPICION', 'Astuto', '"{user1} é simpático(a) demais para o primeiro dia", comentou {user} baixinho.'),
  ('SUSPICION', 'Observador', '{user} viu {user1} decorando o nome de todo mundo. "Isso é trabalho de traidor."'),
  ('SUSPICION', 'Estrategista', '{user} marcou {user1} como "perigoso(a)" antes mesmo do jantar.'),
  ('SUSPICION', NULL, '{user} achou estranho {user1} ter feito tantas perguntas sobre as regras da torre.'),
  ('SUSPICION', 'Fofoqueiro', '{user} contou para {user2} que {user1} "tem cara de quem já mentiu para a mãe no Natal".'),
  ('SUSPICION', 'Paranoico', '{user} sentou de costas para a parede para não perder {user1} de vista.'),
  ('SUSPICION', NULL, '{user} jurou que viu {user1} ensaiando uma cara de surpresa no espelho.'),
  ('SUSPICION', 'Invejoso', '{user} não confia em {user1}: "Ninguém é tão perfeito(a) assim sem esconder alguma coisa."'),
  ('SUSPICION', 'Detetive', '{user} reparou que {user1} bebeu pouquíssimo. "Quer ficar sóbrio(a) para a torre?"'),
  ('SUSPICION', NULL, '"Vocês viram como {user1} riu quando falaram em assassinato?", perguntou {user}.'),
  ('SUSPICION', 'Paranoico', '{user} perguntou a {user1}, do nada, onde estaria à meia-noite. {user1} só riu.'),
  ('SUSPICION', 'Astuto', '{user} testou {user1} com uma pergunta capciosa sobre o programa. A resposta foi rápida demais.'),
  ('SUSPICION', NULL, '{user} disse que {user1} "tem energia de traidor". Não soube explicar o que isso significa.'),
  ('SUSPICION', 'Observador', '{user} ficou de olho em quem saiu primeiro da sala. Foi {user1}.'),
  ('SUSPICION', 'Mentiroso', '{user} espalhou que {user1} já tinha jogado algo parecido e "sabe mentir profissionalmente".'),
  ('SUSPICION', NULL, '{user} sussurrou a {user2}: "Fica de olho em {user1}. Eu sinto essas coisas."'),
  ('SUSPICION', 'Detetive', '{user} anotou que {user1} trocou de lugar na mesa três vezes. "Quer ouvir todas as conversas?"'),
  ('SUSPICION', 'Paranoico', '{user} dormiu com a cadeira travando a porta e culpou {user1}, sem motivo nenhum.'),
  ('SUSPICION', NULL, '{user} achou que {user1} olhou tempo demais para a torre. "Já sabe onde é a reunião, é?"'),
  ('SUSPICION', 'Estrategista', '"Os traidores vão parecer os mais legais. Então, {user1}...", pensou {user} em voz alta.'),

  -- aliança
  ('ALLIANCE', 'Fiel', '{user} puxou {user1} para o jardim: "Você e eu até o fim. Sem traição."'),
  ('ALLIANCE', 'Estrategista', '{user} propôs a {user1} um pacto de não votar um no outro nas três primeiras mesas.'),
  ('ALLIANCE', 'Protetor', '{user} prometeu a {user1} que vai defendê-lo(a) em qualquer mesa redonda.'),
  ('ALLIANCE', 'Manipulador', '{user} ofereceu uma aliança a {user1} com um sorriso que não chegou aos olhos.'),
  ('ALLIANCE', 'Líder', '{user} escolheu {user1} como braço direito antes mesmo do jantar começar.'),
  ('ALLIANCE', NULL, '{user} e {user1} juraram de mindinho, como crianças. Vale mais que contrato.'),
  ('ALLIANCE', 'Carente', '{user} perguntou a {user1}: "A gente vai ser melhores amigos, né?" antes de saber o sobrenome.'),
  ('ALLIANCE', NULL, '{user} e {user1} combinaram um sinal secreto: coçar a orelha significa "confio em você".'),
  ('ALLIANCE', 'Traíra', '{user} jurou lealdade eterna a {user1}. Eterna, segundo {user}, dura uns quatro dias.'),
  ('ALLIANCE', 'Diplomata', '{user} sugeriu a {user1} uma aliança "aberta", sem inimigos. {user1} achou lindo e ingênuo.'),
  ('ALLIANCE', NULL, '{user} disse a {user1}: "Se um de nós for traidor, o outro vai ser o último a saber. E tudo bem."'),
  ('ALLIANCE', 'Heroico', '{user} prometeu a {user1} que, se ganhar um escudo, pensa duas vezes antes de guardar para si.'),
  ('ALLIANCE', 'Sonso', '{user} se aproximou de {user1} com a desculpa de "não conhecer ninguém". Já conhecia todo mundo.'),
  ('ALLIANCE', NULL, '{user} e {user1} escolheram quartos lado a lado: "Se alguém vier pela noite, a gente grita."'),
  ('ALLIANCE', 'Fiel', '"Eu não troco você por prêmio nenhum", disse {user} a {user1}. Resta saber se é verdade.'),

  -- conflito
  ('CONFLICT', 'Invejoso', '{user} revirou os olhos quando {user1} foi o centro das atenções na chegada.'),
  ('CONFLICT', 'Explosivo', '{user} e {user1} discutiram pelo melhor quarto antes de a mala chegar ao chão.'),
  ('CONFLICT', 'Competitivo', '{user} avisou que ia ganhar todas as missões. {user1} respondeu: "Vamos ver no lago."'),
  ('CONFLICT', 'Arrogante', '{user} corrigiu a pronúncia de {user1} na frente de todos. Primeiro inimigo feito.'),
  ('CONFLICT', NULL, '{user} e {user1} descobriram que já brigaram numa rede social anos atrás. O castelo ficou pequeno.'),
  ('CONFLICT', 'Vingativo', '{user} não gostou do comentário de {user1} sobre sua roupa e prometeu: "Guardei."'),
  ('CONFLICT', 'Explosivo', '{user} bateu a taça na mesa quando {user1} insinuou que ele(a) seria o(a) primeiro(a) a sair.'),
  ('CONFLICT', NULL, '{user} disse que {user1} fala alto demais. {user1} respondeu falando mais alto ainda.'),
  ('CONFLICT', 'Rebelde', '{user} se recusou a fazer o brinde que {user1} propôs. "Não brindo com gente que eu não conheço."'),
  ('CONFLICT', 'Invejoso', '{user} fingiu não ouvir quando {user1} contou a própria história de superação. Todos ouviram {user} bufar.'),
  ('CONFLICT', NULL, '{user} e {user1} disputaram o último pedaço de bolo como se fosse o prêmio final.'),
  ('CONFLICT', 'Arrogante', '"Com todo respeito, você não dura uma semana", disse {user} a {user1}. Não teve respeito nenhum.'),
  ('CONFLICT', 'Competitivo', '{user} desafiou {user1} para uma queda de braço no salão. O mordomo pediu para parar.'),
  ('CONFLICT', NULL, '{user} ocupou a cadeira que {user1} tinha guardado. A guerra fria começou ali.'),
  ('CONFLICT', 'Vingativo', '{user} anotou o nome de {user1} num guardanapo e guardou no bolso. "É para não esquecer."'),

  -- emoção
  ('EMOTION', 'Dramático', '{user} chorou ao ver o castelo iluminado: "Eu sonhei com isso a vida inteira."'),
  ('EMOTION', 'Chorão', '{user} se emocionou ao falar da família e {user1} segurou a mão dele(a).'),
  ('EMOTION', NULL, '{user} contou que prometeu à avó que chegaria até a final. A voz falhou no meio.'),
  ('EMOTION', 'Carente', '{user} admitiu para {user1} que tem medo de ficar sozinho(a) no castelo.'),
  ('EMOTION', NULL, '{user} olhou a lareira e disse, baixinho: "Minha filha ia amar isso aqui."'),
  ('EMOTION', 'Heroico', '{user} disse que vai jogar pelo pai, que sempre assistiu ao programa com ele(a).'),
  ('EMOTION', 'Tímido', '{user} confessou a {user1} que quase desistiu no aeroporto de tanto nervoso.'),
  ('EMOTION', NULL, '{user} contou que o prêmio pagaria a casa da mãe. Ninguém fez piada.'),
  ('EMOTION', 'Chorão', '{user} chorou quando o gaiteiro tocou. Depois chorou de vergonha de ter chorado.'),
  ('EMOTION', NULL, '{user} e {user1} descobriram que perderam alguém importante no mesmo ano. Ficaram em silêncio juntos.'),
  ('EMOTION', 'Dramático', '{user} fez um discurso sobre "o jogo da vida" que ninguém pediu, mas todo mundo aplaudiu.'),
  ('EMOTION', NULL, '{user} escreveu uma carta para casa antes de dormir. "Caso eu não volte do café da manhã."')
) AS v(tone, behavior, text)
LEFT JOIN behaviors b ON lower(b.name) = lower(v.behavior)
ON CONFLICT DO NOTHING;
