-- =====================================================================
-- Frases das MISSÕES (servem para qualquer missão).
-- =====================================================================

INSERT INTO phrases (phase, tone, behavior_id, text)
SELECT 'MISSION'::phrase_phase, v.tone::phrase_tone, b.id, v.text
FROM (VALUES
  -- neutro
  ('NEUTRAL', NULL, '{user} leu as instruções duas vezes em voz alta. {user1} já estava correndo para o lado errado.'),
  ('NEUTRAL', NULL, '{user} e {user1} dividiram as tarefas sem trocar uma palavra.'),
  ('NEUTRAL', 'Líder', '{user} assumiu o comando antes de alguém perguntar quem ia comandar.'),
  ('NEUTRAL', 'Estrategista', '{user} calculou em voz alta quanto dinheiro cada erro custava. Ninguém quis ouvir.'),
  ('NEUTRAL', 'Observador', '{user} ficou atrás do grupo, olhando quem se esforçava e quem fingia.'),
  ('NEUTRAL', NULL, '{user} perguntou a {user1} se sabia nadar. A resposta foi um "mais ou menos" preocupante.'),
  ('NEUTRAL', 'Frio', '{user} fez a parte dele(a) sem suar, sem sorrir e sem falar.'),
  ('NEUTRAL', NULL, '{user} amarrou o cadarço de {user1}, que estava ocupado(a) segurando a corda.'),
  ('NEUTRAL', 'Detetive', '{user} anotou quem hesitou antes de cada escolha. Diz que traidor pensa demais em missão.'),
  ('NEUTRAL', NULL, '{user} lembrou ao grupo que cada centavo vai para o prêmio final. Ou para os traidores.'),
  ('NEUTRAL', 'Tímido', '{user} só falou uma vez durante a missão inteira, e foi para dar a resposta certa.'),
  ('NEUTRAL', NULL, '{user} e {user1} pararam para recuperar o fôlego e olharam o castelo lá longe.'),
  ('NEUTRAL', 'Sonso', '{user} fez questão de parecer atrapalhado(a). Não estava.'),
  ('NEUTRAL', NULL, '{user} contou os segundos em voz alta até o grupo inteiro implorar para parar.'),
  ('NEUTRAL', NULL, '{user} explicou a {user1} a estratégia pela terceira vez. Na quarta, {user1} fingiu entender.'),

  -- humor
  ('HUMOR', NULL, '{user} escorregou na lama e levou {user1} junto. Os dois riram até chorar.'),
  ('HUMOR', 'Dramático', '{user} gritou "estratégia!" e saiu correndo sem estratégia nenhuma.'),
  ('HUMOR', NULL, '{user} jurou para {user1} que a neblina das Highlands está do lado dos traidores.'),
  ('HUMOR', 'Brincalhão', '{user} fez uma continência para a missão como se fosse para a guerra. Perdeu o equilíbrio.'),
  ('HUMOR', NULL, '{user} caiu no lago de propósito "para refrescar". Ninguém acreditou.'),
  ('HUMOR', 'Caótico', '{user} resolveu o enigma com a resposta errada e mesmo assim deu certo. Ninguém entendeu.'),
  ('HUMOR', NULL, '{user} perdeu uma bota na lama e passou o resto da missão com um pé só, determinado(a).'),
  ('HUMOR', 'Arrogante', '{user} disse "deixa comigo" e, em seguida, deixou cair tudo.'),
  ('HUMOR', NULL, '{user} tentou assobiar para chamar {user1} e saiu um som de chaleira.'),
  ('HUMOR', 'Chorão', '{user} chorou porque a missão estava difícil, depois porque deu certo, depois porque estava com fome.'),
  ('HUMOR', NULL, '{user} confundiu esquerda com direita três vezes seguidas. {user1} desistiu de dar instruções.'),
  ('HUMOR', 'Brincalhão', '{user} narrou a missão como locutor de futebol. Até os vikings riram.'),
  ('HUMOR', NULL, '{user} disse que a água do lago estava "fresquinha". Estava três graus.'),
  ('HUMOR', 'Ovelha', '{user} seguiu {user1} com tanta dedicação que entrou no lago junto, sem precisar.'),
  ('HUMOR', NULL, '{user} ficou preso(a) numa cerca por dez minutos e pediu para narrarem isso "com dignidade".'),
  ('HUMOR', 'Caótico', '{user} sugeriu resolver o enigma "sentindo a energia". Por incrível que pareça, acertou.'),
  ('HUMOR', NULL, '{user} jurou que a corda era traidora: "Ela escorregou de propósito!"'),
  ('HUMOR', 'Rebelde', '{user} ignorou o plano do grupo e fez do próprio jeito. Deu errado, mas com estilo.'),
  ('HUMOR', NULL, '{user} comemorou um acerto com tanta força que derrubou a peça que tinha acabado de encaixar.'),
  ('HUMOR', 'Dramático', '{user} gritou "vão sem mim!" numa missão que não tinha perigo nenhum.'),
  ('HUMOR', NULL, '{user} perguntou se valia usar o mordomo como ajudante. Não valia.'),
  ('HUMOR', 'Brincalhão', '{user} batizou a missão de "Ovelhas no Gelo" e ninguém mais conseguiu levar a sério.'),
  ('HUMOR', NULL, '{user} e {user1} bateram cabeça literalmente. Os dois ficaram com o mesmo galo.'),
  ('HUMOR', 'Frio', '{user} viu {user1} cair na lama e só comentou: "Anotei."'),
  ('HUMOR', NULL, '{user} disse que se ganhar escudo vai dormir abraçado(a) com ele. Literalmente.'),
  ('HUMOR', 'Arrogante', '{user} se gabou de nunca errar. Errou a primeira pergunta.'),
  ('HUMOR', NULL, '{user} jurou que viu um fantasma no meio da missão. Era um espantalho. Ou era {user1}.'),
  ('HUMOR', 'Caótico', '{user} tentou subornar o viking com um chiclete.'),
  ('HUMOR', NULL, '{user} disse que o traidor dessa missão é o vento, que levou metade das anotações.'),
  ('HUMOR', 'Chorão', '{user} chorou ao ganhar o escudo e chorou de novo ao lembrar que só vale por uma noite.'),
  ('HUMOR', NULL, '{user} perguntou se podiam pedir pizza para o meio da missão. Ninguém respondeu.'),
  ('HUMOR', 'Brincalhão', '{user} prometeu fazer uma dancinha se o grupo acertasse. O grupo acertou. A dança foi pior que o erro.'),
  ('HUMOR', NULL, '{user} disse que o frio escocês "é só psicológico" enquanto os dentes batiam.'),
  ('HUMOR', 'Invejoso', '{user} comemorou em silêncio quando {user1} errou. Alto demais para ser silêncio.'),
  ('HUMOR', NULL, '{user} tentou ler o mapa de cabeça para baixo e jurou que era o jeito escocês.'),

  -- amizade
  ('FRIENDLY', 'Querido', '{user} ajudou {user1} a atravessar a parte mais difícil sem pensar duas vezes.'),
  ('FRIENDLY', 'Amado', '{user} vibrou com cada acerto de {user1} como se fosse o próprio.'),
  ('FRIENDLY', 'Heroico', '{user} pulou na água gelada no lugar de {user1}, que não sabia nadar.'),
  ('FRIENDLY', 'Protetor', '{user} segurou {user1} pela mochila quando o chão cedeu.'),
  ('FRIENDLY', NULL, '{user} e {user1} comemoraram o acerto com um abraço cheio de lama.'),
  ('FRIENDLY', 'Brincalhão', '{user} manteve {user1} rindo durante a missão inteira para ele(a) não entrar em pânico.'),
  ('FRIENDLY', 'Diplomata', '{user} elogiou o esforço de {user1} na frente do grupo, mesmo com o erro.'),
  ('FRIENDLY', 'Carente', '{user} segurou a mão de {user1} a missão inteira. Mesmo quando não precisava.'),
  ('FRIENDLY', NULL, '{user} dividiu o chocolate de emergência com {user1}.'),
  ('FRIENDLY', 'Querido', '{user} secou o cabelo de {user1} com o próprio casaco depois do mergulho.'),
  ('FRIENDLY', 'Líder', '{user} escolheu {user1} para a parte mais importante: "Eu confio em você."'),
  ('FRIENDLY', NULL, '{user} e {user1} cantaram para passar o tempo enquanto carregavam o peso.'),
  ('FRIENDLY', 'Heroico', '{user} carregou dois baús para que {user1} pudesse descansar.'),
  ('FRIENDLY', NULL, '{user} ensinou {user1} um nó de marinheiro que salvou a missão.'),
  ('FRIENDLY', 'Amado', 'Quando {user} acertou, até quem desconfiava dele(a) aplaudiu. {user1} gritou mais alto.'),

  -- conflito
  ('CONFLICT', 'Competitivo', '{user} tomou a frente e {user1} reclamou: "Ninguém te escolheu capitão(ã)!"'),
  ('CONFLICT', 'Explosivo', '{user} acusou {user1} de fazer corpo mole na frente de todo mundo.'),
  ('CONFLICT', 'Invejoso', '{user} não aguentou ver {user1} levando o crédito e corrigiu cada detalhe em voz alta.'),
  ('CONFLICT', 'Arrogante', '{user} chamou o plano de {user1} de "infantil". O plano de {user1} funcionou.'),
  ('CONFLICT', 'Explosivo', '{user} jogou a corda no chão e gritou com {user1}: "Assim a gente perde tudo!"'),
  ('CONFLICT', NULL, '{user} e {user1} discutiram sobre qual caminho seguir até o tempo acabar.'),
  ('CONFLICT', 'Vingativo', '{user} deixou {user1} de fora da parte que valia escudo. "Você votou em mim, lembra?"'),
  ('CONFLICT', 'Competitivo', '{user} disse que {user1} foi o elo fraco da missão. {user1} respondeu com um empurrão na lama.'),
  ('CONFLICT', NULL, '{user} culpou {user1} pelo dinheiro perdido. {user1} culpou o vento. O vento não se defendeu.'),
  ('CONFLICT', 'Rebelde', '{user} se recusou a seguir as ordens de {user1}. "Quem te deu a coroa?"'),
  ('CONFLICT', 'Traíra', '{user} prometeu ajudar {user1} e sumiu na hora mais difícil.'),
  ('CONFLICT', NULL, '{user} e {user1} brigaram pela mesma peça do quebra-cabeça até ela quebrar.'),
  ('CONFLICT', 'Explosivo', '{user} chutou um balde quando {user1} errou a resposta. O balde estava cheio.'),
  ('CONFLICT', 'Arrogante', '{user} explicou o óbvio para {user1} como se falasse com uma criança. {user1} anotou esse dia.'),
  ('CONFLICT', 'Invejoso', '{user} disse que {user1} só ganhou o escudo porque o jogo é "armado".'),
  ('CONFLICT', NULL, '{user} disse que {user1} estava sabotando. {user1} disse que {user} estava cego(a). Os dois estavam molhados.'),
  ('CONFLICT', 'Competitivo', '{user} cronometrou {user1} e esfregou o tempo na cara dele(a) no final.'),
  ('CONFLICT', 'Vingativo', '{user} escondeu a lanterna de {user1} "sem querer".'),

  -- suspeita
  ('SUSPICION', 'Paranoico', '{user} reparou que {user1} errou justo a parte mais fácil. "Estranho, né?"'),
  ('SUSPICION', NULL, '{user} sussurrou para {user2}: "Se alguém quer sabotar essa missão, é {user1}."'),
  ('SUSPICION', 'Astuto', '"Por que {user1} não quis ficar com o escudo?", perguntou {user}, desconfiado(a).'),
  ('SUSPICION', 'Detetive', '{user} percebeu que {user1} diminuiu o ritmo sempre que o dinheiro estava em jogo.'),
  ('SUSPICION', 'Observador', '{user} viu {user1} olhar para o relógio no momento exato em que tudo deu errado.'),
  ('SUSPICION', 'Paranoico', '{user} acha que {user1} derrubou a peça de propósito. Não tem prova, só certeza.'),
  ('SUSPICION', 'Estrategista', '{user} notou que {user1} sempre fica com a tarefa que ninguém consegue vigiar.'),
  ('SUSPICION', NULL, '{user} perguntou a {user1} por que ele(a) sabia a resposta antes de todo mundo.'),
  ('SUSPICION', 'Fofoqueiro', '{user} já espalhou para meio grupo que {user1} "fez corpo mole de caso pensado".'),
  ('SUSPICION', 'Detetive', '{user} reparou que {user1} torceu para o dinheiro não entrar. "Traidor não gosta de pote cheio? Ou gosta?"'),
  ('SUSPICION', 'Paranoico', '{user} suspeita que {user1} escolheu o caminho errado de propósito. Duas vezes.'),
  ('SUSPICION', NULL, '{user} lembrou que, em todas as missões que deram errado, {user1} estava por perto.'),
  ('SUSPICION', 'Astuto', '{user} testou {user1} passando uma informação falsa. {user1} usou a informação.'),
  ('SUSPICION', 'Observador', '{user} percebeu que {user1} sumiu por dez minutos no meio da missão.'),
  ('SUSPICION', 'Invejoso', '{user} acha que {user1} ganhou escudo fácil demais para ser fiel.'),

  -- aliança
  ('ALLIANCE', 'Fiel', '{user} fez questão de ficar no mesmo grupo que {user1}: "A gente se protege."'),
  ('ALLIANCE', 'Estrategista', '{user} combinou com {user1} de dividir o escudo, se um dos dois ganhar. Não dá para dividir.'),
  ('ALLIANCE', 'Protetor', '{user} garantiu que {user1} ficasse com a tarefa mais segura.'),
  ('ALLIANCE', NULL, '{user} e {user1} trabalharam como se já se conhecessem havia anos.'),
  ('ALLIANCE', 'Líder', '{user} indicou {user1} para o escudo na frente de todos.'),
  ('ALLIANCE', 'Manipulador', '{user} ajudou {user1} na frente das câmeras e cobrou o favor longe delas.'),
  ('ALLIANCE', 'Heroico', '{user} abriu mão da própria vez para que {user1} tentasse o escudo.'),
  ('ALLIANCE', NULL, '{user} e {user1} combinaram um código: se um tossir, o outro muda de estratégia.'),

  -- emoção
  ('EMOTION', 'Dramático', '{user} chorou de alegria quando o dinheiro entrou no pote.'),
  ('EMOTION', 'Tímido', '{user} ficou em silêncio depois de errar, com medo de virar alvo na mesa redonda.'),
  ('EMOTION', 'Chorão', '{user} desabou quando o tempo acabou. {user1} abraçou por um minuto inteiro.'),
  ('EMOTION', NULL, '{user} disse que a missão lembrou o pai, que ensinava a nadar num lago igual a esse.'),
  ('EMOTION', 'Heroico', '{user} terminou a missão com a mão sangrando e disse que valia a pena.'),
  ('EMOTION', NULL, '{user} ganhou o escudo e chorou: "Pela primeira vez em dias, eu vou dormir."'),
  ('EMOTION', 'Carente', '{user} pediu desculpas ao grupo inteiro pelo erro, um por um.'),
  ('EMOTION', NULL, '{user} olhou para o pote de dinheiro e disse: "Isso muda a vida da minha família."'),
  ('EMOTION', 'Chorão', '{user} chorou porque a missão acabou bem. Depois chorou porque acabou.'),
  ('EMOTION', 'Dramático', '{user} gritou para o céu das Highlands como se tivesse ganhado uma guerra.'),
  ('EMOTION', NULL, '{user} ficou emocionado(a) quando o grupo inteiro esperou por ele(a) na linha de chegada.'),
  ('EMOTION', 'Tímido', '{user} contou a {user1} que nunca tinha pulado de tão alto na vida. Tremia inteiro(a).')
) AS v(tone, behavior, text)
LEFT JOIN behaviors b ON lower(b.name) = lower(v.behavior)
ON CONFLICT DO NOTHING;
