-- =====================================================================
-- Frases da MESA REDONDA.
-- Antes do voto: sem {victim}. Depois da revelação, só frases com {victim}
-- (o banido), que não podem supor se ele era fiel ou traidor.
-- =====================================================================

INSERT INTO phrases (phase, tone, behavior_id, text)
SELECT 'ROUND_TABLE'::phrase_phase, v.tone::phrase_tone, b.id, v.text
FROM (VALUES
  -- acusação
  ('ACCUSATION', 'Explosivo', '{user} se levantou e apontou: "Eu tenho certeza absoluta. {user1}, você é Traidor(a)!"'),
  ('ACCUSATION', 'Detetive', '{user} listou três contradições de {user1} em ordem cronológica. A mesa ficou em silêncio.'),
  ('ACCUSATION', 'Carismático', '{user} olhou para cada um da mesa e terminou em {user1}: "Todos nós sabemos."'),
  ('ACCUSATION', 'Paranoico', '"Desde o primeiro dia eu falo de {user1} e ninguém me escuta!", gritou {user}.'),
  ('ACCUSATION', 'Estrategista', '{user} mostrou que {user1} nunca votou em quem saiu como traidor. Nenhuma vez.'),
  ('ACCUSATION', 'Líder', '{user} pediu a palavra: "Eu vou votar em {user1} e peço que confiem em mim."'),
  ('ACCUSATION', 'Vingativo', '{user} lembrou que {user1} puxou votos contra ele(a) duas mesas atrás. "Agora é a minha vez."'),
  ('ACCUSATION', 'Mentiroso', '{user} inventou, com uma calma assustadora, que viu {user1} saindo da torre à meia-noite.'),
  ('ACCUSATION', 'Rebelde', '{user} acusou {user1} só porque todo mundo estava protegendo {user1}. "Justamente por isso."'),
  ('ACCUSATION', 'Fofoqueiro', '{user} revelou para a mesa uma conversa privada que teve com {user1}. {user1} ficou branco(a).'),
  ('ACCUSATION', 'Arrogante', '{user} disse que "resolveu o jogo" e que {user1} é traidor(a). Pela quarta vez na temporada.'),
  ('ACCUSATION', 'Invejoso', '"{user1} é querido(a) demais. Isso é o disfarce perfeito", disse {user}.'),
  ('ACCUSATION', 'Detetive', '{user} lembrou que {user1} sabia de um detalhe do assassinato que ninguém tinha contado.'),
  ('ACCUSATION', 'Explosivo', '{user} bateu na mesa até as velas tremerem: "Chega de teatro, {user1}!"'),
  ('ACCUSATION', 'Astuto', '{user} fez uma pergunta simples a {user1} e deixou a resposta confusa falar por si.'),
  ('ACCUSATION', 'Caótico', '{user} votou por intuição e anunciou: "Não tenho nenhum motivo. É {user1}."'),
  ('ACCUSATION', 'Competitivo', '{user} lembrou que {user1} atrapalhou três missões seguidas. "Sabotagem tem nome."'),
  ('ACCUSATION', 'Ovelha', '{user} olhou para a mesa, viu para onde os votos iam e acusou {user1} também.'),
  ('ACCUSATION', 'Líder', '{user} organizou o raciocínio da mesa como um advogado e terminou: "Réu: {user1}."'),
  ('ACCUSATION', 'Paranoico', '{user} disse que {user1} "respira como traidor". Ninguém entendeu, mas ficou no ar.'),
  ('ACCUSATION', 'Mentiroso', '{user} jurou que {user1} tentou recrutá-lo(a) na noite passada. Ninguém sabe se é verdade.'),
  ('ACCUSATION', 'Estrategista', '{user} mostrou que toda vítima dos traidores tinha brigado com {user1} antes.'),
  ('ACCUSATION', 'Carismático', '{user} fez um discurso tão bonito contra {user1} que alguém aplaudiu sem querer.'),
  ('ACCUSATION', 'Frio', '{user} disse, sem alterar a voz: "{user1}, você mente mal. Só isso."'),
  ('ACCUSATION', 'Vingativo', '{user} cobrou {user1}: "Você me chamou de ovelha. Vamos ver quem é a ovelha agora."'),
  ('ACCUSATION', NULL, '"Eu vou votar em {user1}, e vou dizer por quê", começou {user}, com a voz firme.'),
  ('ACCUSATION', NULL, '{user} disse que {user1} está "confortável demais" para quem tem tanta gente contra.'),
  ('ACCUSATION', NULL, '{user} lembrou que {user1} jurou ser fiel "cem por cento". "Fiel não precisa de porcentagem."'),
  ('ACCUSATION', NULL, '{user} olhou para {user1}: "Você chorou na hora certa demais. Ensaiou?"'),
  ('ACCUSATION', NULL, '{user} apontou que {user1} mudou de alvo três vezes na mesma conversa.'),
  ('ACCUSATION', 'Detetive', '{user} lembrou que {user1} sempre defende quem depois é revelado traidor.'),
  ('ACCUSATION', 'Explosivo', '{user} derrubou a cadeira ao gritar o nome de {user1}. Ninguém ousou interromper.'),
  ('ACCUSATION', 'Invejoso', '{user} acusou {user1} de estar jogando "para a câmera" e não para o grupo.'),
  ('ACCUSATION', 'Caótico', '{user} tirou uma moeda do bolso, jogou para cima e anunciou: "É {user1}. A moeda nunca erra."'),
  ('ACCUSATION', NULL, '{user} disse a {user1}: "Se eu estiver errado(a), eu te peço desculpas de joelhos amanhã."'),

  -- suspeita
  ('SUSPICION', 'Tímido', '{user} disse, quase sem voz, que {user1} está estranho(a) desde ontem.'),
  ('SUSPICION', 'Paranoico', '"Tem alguma coisa em {user1} que não fecha", repetiu {user}, pela terceira vez.'),
  ('SUSPICION', NULL, '{user} perguntou a {user1} por que mudou de voto na última hora ontem.'),
  ('SUSPICION', 'Astuto', '{user} lembrou a todos que {user1} foi o(a) único(a) que não se abalou com a última morte.'),
  ('SUSPICION', 'Observador', '{user} disse que viu {user1} olhar para {user2} antes de cada voto. "Combinado?"'),
  ('SUSPICION', 'Detetive', '{user} ainda não tem certeza, mas o nome de {user1} está no topo da lista.'),
  ('SUSPICION', NULL, '{user} disse que votaria em {user1} "com dor no coração, mas votaria".'),
  ('SUSPICION', 'Estrategista', '{user} lembrou que {user1} não foi alvo dos traidores nenhuma vez. "Por quê?"'),
  ('SUSPICION', 'Fofoqueiro', '{user} contou que {user1} anda cochichando pelos cantos com gente diferente todo dia.'),
  ('SUSPICION', 'Paranoico', '{user} admitiu que desconfia de todos, mas de {user1} um pouco mais.'),
  ('SUSPICION', 'Sonso', '{user} fez uma pergunta "inocente" sobre {user1} que plantou a dúvida na mesa inteira.'),
  ('SUSPICION', NULL, '{user} disse que {user1} tem "cara de quem sabe onde fica a torre".'),
  ('SUSPICION', 'Observador', '{user} reparou que {user1} nunca fala primeiro. "Espera para ver para onde o vento vai."'),
  ('SUSPICION', 'Detetive', '{user} perguntou a {user1} onde estava durante a missão, minuto a minuto.'),
  ('SUSPICION', NULL, '{user} disse que não acusa ninguém, mas ficaria "de olho" em {user1}.'),
  ('SUSPICION', 'Ingênuo', '{user} disse que confia em todo mundo, "menos um pouquinho em {user1}".'),
  ('SUSPICION', 'Astuto', '{user} perguntou a {user1}: "Se você fosse traidor(a), quem você mataria?" A resposta demorou.'),
  ('SUSPICION', NULL, '{user} disse que {user1} está defendendo gente demais para quem diz não ter aliados.'),

  -- defesa
  ('DEFENSE', 'Fiel', '"{user1} é Fiel. Eu coloco a minha mão no fogo", declarou {user}.'),
  ('DEFENSE', 'Explosivo', '{user} rebateu {user2}: "Você está atacando {user1} porque está com medo de ser o(a) próximo(a)."'),
  ('DEFENSE', 'Carismático', '{user} defendeu {user1} com um discurso tão bonito que até {user2} abaixou a cabeça.'),
  ('DEFENSE', 'Dramático', '"Se {user1} for Traidor(a), eu saio deste castelo agora mesmo", gritou {user}.'),
  ('DEFENSE', 'Ingênuo', '{user} lembrou que {user1} foi quem mais se esforçou na missão. "Traidor não se esforça assim."'),
  ('DEFENSE', NULL, '{user} pediu calma: "Vocês estão caçando {user1} sem nenhuma prova."'),
  ('DEFENSE', 'Protetor', '{user} se colocou na frente de {user1}: "Se querem alguém, votem em mim."'),
  ('DEFENSE', 'Diplomata', '{user} lembrou a {user2} que ontem a mesa errou justamente por agir na pressa contra alguém como {user1}.'),
  ('DEFENSE', 'Líder', '{user} pediu que ninguém votasse em {user1}: "Eu assumo a responsabilidade."'),
  ('DEFENSE', 'Heroico', '{user} disse que {user1} salvou a missão de ontem sozinho(a) e merece respeito.'),
  ('DEFENSE', 'Detetive', '{user} desmontou a acusação de {user2} contra {user1} ponto por ponto.'),
  ('DEFENSE', 'Manipulador', '{user} defendeu {user1} tão bem que ninguém percebeu que o objetivo era proteger a si mesmo(a).'),
  ('DEFENSE', 'Fiel', '{user} segurou a mão de {user1} por baixo da mesa durante toda a acusação.'),
  ('DEFENSE', NULL, '{user} lembrou que {user1} foi o primeiro a votar em um traidor nesta temporada.'),
  ('DEFENSE', 'Carismático', '{user} virou o jogo: "Por que {user2} tem tanta pressa em tirar {user1} daqui?"'),
  ('DEFENSE', 'Diplomata', '{user} sugeriu que a mesa ouvisse {user1} até o fim antes de decidir.'),
  ('DEFENSE', 'Protetor', '"Enquanto eu estiver aqui, ninguém toca em {user1}", disse {user}. Soou como filme.'),
  ('DEFENSE', 'Chorão', '{user} chorou defendendo {user1}. Funcionou mais do que qualquer argumento.'),
  ('DEFENSE', NULL, '{user} perguntou a {user2}: "Qual prova você tem contra {user1}? Uma. Me dá uma."'),
  ('DEFENSE', 'Heroico', '{user} lembrou que {user1} recusou um escudo para o dinheiro ir para o pote.'),

  -- conflito
  ('CONFLICT', 'Explosivo', '{user} e {user1} trocaram acusações aos gritos até alguém pedir ordem na mesa.'),
  ('CONFLICT', NULL, '"Você votou em mim ontem e ainda fala em confiança?", disparou {user} contra {user1}.'),
  ('CONFLICT', 'Invejoso', '{user} riu com desprezo enquanto {user1} tentava se defender.'),
  ('CONFLICT', 'Dramático', '{user} bateu a mão na mesa quando {user1} mencionou o nome dele(a).'),
  ('CONFLICT', 'Vingativo', '{user} lembrou cada palavra que {user1} disse sobre ele(a) desde o primeiro dia.'),
  ('CONFLICT', 'Arrogante', '{user} disse que não perde tempo discutindo com {user1}. Perdeu dez minutos.'),
  ('CONFLICT', 'Explosivo', '{user} se levantou para sair da mesa, voltou e continuou a briga com {user1}.'),
  ('CONFLICT', 'Traíra', '{user} votou contra o combinado com {user1} e ainda disse que foi "estratégia conjunta".'),
  ('CONFLICT', NULL, '{user} chamou {user1} de "cobra". {user1} chamou {user} de "ovelha". O apelido pegou nos dois.'),
  ('CONFLICT', 'Rebelde', '{user} disse que {user1} está manipulando a mesa e que não vai obedecer.'),
  ('CONFLICT', 'Competitivo', '{user} disse que {user1} não fez nada no jogo até agora além de falar.'),
  ('CONFLICT', 'Vingativo', '{user} olhou para {user1}: "Eu te avisei que ia lembrar." E lembrou.'),

  -- emoção
  ('EMOTION', 'Dramático', '{user} chorou: "Eu sou Fiel. Eu juro pela minha família."'),
  ('EMOTION', 'Chorão', '{user} começou a chorar antes mesmo de ser acusado(a). "É o clima."'),
  ('EMOTION', 'Tímido', '{user} pediu a palavra, tremendo, e disse: "Eu só quero que vocês me vejam."'),
  ('EMOTION', 'Fiel', '{user} disse que perdeu a confiança em si mesmo(a) depois do último erro da mesa.'),
  ('EMOTION', NULL, '{user} jurou ser fiel "cem por cento, duzentos por cento, mil por cento". A mesa suspirou.'),
  ('EMOTION', 'Carente', '{user} perguntou à mesa: "Alguém aqui confia em mim? Uma pessoa só?"'),
  ('EMOTION', 'Dramático', '{user} tirou a aliança do dedo e colocou na mesa: "Juro pela minha casa."'),
  ('EMOTION', NULL, '{user} disse que a mesa redonda é o pior lugar do mundo e que ninguém sai inteiro(a) dela.'),

  -- humor, neutro e aliança
  ('HUMOR', 'Brincalhão', '{user} propôs votar em quem tivesse a pior letra no quadro. Riram. Depois ficaram sérios.'),
  ('HUMOR', 'Caótico', '{user} escreveu o próprio nome no quadro, apagou e escreveu o de {user1}. "Brincadeira."'),
  ('HUMOR', NULL, '{user} disse que se for banido(a) hoje, quer que tragam uma torta para a saída.'),
  ('HUMOR', 'Arrogante', '{user} disse que o voto de hoje é "óbvio". Metade da mesa votou diferente.'),
  ('HUMOR', 'Ovelha', '{user} esperou todo mundo mostrar o voto antes de escrever o dele(a). Não é assim que funciona.'),
  ('HUMOR', NULL, '{user} comparou a mesa redonda a um almoço de família no Natal. "Só que com menos gente viva."'),
  ('NEUTRAL', NULL, '{user} pediu a palavra, respirou fundo e admitiu que ainda não tinha decidido o voto.'),
  ('NEUTRAL', 'Observador', '{user} só falou no fim: "Eu escutei todo mundo. Já sei o que fazer."'),
  ('NEUTRAL', 'Frio', '{user} escreveu o nome no quadro sem demonstrar nenhuma emoção.'),
  ('ALLIANCE', 'Fiel', '{user} olhou para {user1} antes de votar. Os dois assentiram ao mesmo tempo.'),
  ('ALLIANCE', 'Estrategista', '{user} e {user1} votaram juntos, como combinado no jardim.'),
  ('ALLIANCE', NULL, '{user} bateu dois dedos na mesa: o sinal para {user1} de que o plano continua.'),

  -- reações à saída ({victim} = banido(a))
  ('EMOTION', NULL, '{user} ficou olhando a cadeira vazia de {victim} por um longo tempo.'),
  ('EMOTION', 'Querido', '{user} abraçou {victim} antes da saída e prometeu terminar o jogo pelos dois.'),
  ('EMOTION', 'Chorão', '{user} chorou quando {victim} passou pela porta. De novo.'),
  ('EMOTION', 'Fiel', '{user} pediu desculpas a {victim} em voz baixa, sem saber se tinha votado certo.'),
  ('EMOTION', 'Dramático', '{user} disse que a saída de {victim} foi "o momento mais pesado da vida".'),
  ('EMOTION', 'Protetor', '{user} ficou em silêncio a noite inteira depois que {victim} saiu.'),
  ('EMOTION', 'Carente', '{user} perguntou se alguém ainda confiava nele(a) depois da saída de {victim}.'),
  ('EMOTION', 'Tímido', '{user} disse que não votou em {victim}, mas se sente culpado(a) mesmo assim.'),
  ('EMOTION', NULL, '{user} lembrou a última piada que {victim} contou no café. Ninguém riu, todo mundo sorriu.'),
  ('SUSPICION', 'Astuto', '{user} anotou mentalmente quem votou em {victim} e quem mudou de ideia no último segundo.'),
  ('SUSPICION', 'Paranoico', '"Quem puxou os votos contra {victim}? Porque essa pessoa sabia de algo", disse {user}.'),
  ('SUSPICION', 'Detetive', '{user} reparou em quem sorriu quando {victim} revelou o papel.'),
  ('SUSPICION', 'Observador', '{user} viu {user1} respirar aliviado(a) quando {victim} foi banido(a).'),
  ('SUSPICION', NULL, '{user} disse que a saída de {victim} muda tudo e que amanhã ninguém está seguro.'),
  ('ACCUSATION', 'Carismático', '{user} olhou para {user1}: "Você liderou o ataque contra {victim}. Amanhã é a sua vez de explicar."'),
  ('ACCUSATION', 'Vingativo', '{user} disse a {user1}: "{victim} saiu por sua causa. Eu vou lembrar disso."'),
  ('ACCUSATION', 'Explosivo', '"Parabéns a quem votou em {victim}. Espero que estejam orgulhosos", ironizou {user}.'),
  ('CONFLICT', 'Explosivo', '{user} e {user1} discutiram, ainda na mesa, sobre quem convenceu os outros a votar em {victim}.'),
  ('CONFLICT', 'Invejoso', '{user} comentou que {victim} "saiu tarde". A mesa inteira se virou para {user}.'),
  ('CONFLICT', 'Vingativo', '{user} sussurrou para {user1}: "Com {victim} fora, agora é você."'),
  ('DEFENSE', 'Fiel', '{user} prometeu que vai limpar o nome de {victim} até o fim do jogo.'),
  ('DEFENSE', 'Diplomata', '{user} pediu à mesa que ninguém culpasse {user1} pela saída de {victim}.'),
  ('HUMOR', 'Brincalhão', '{user} disse que {victim} saiu com mais estilo do que entrou. Era verdade.'),
  ('HUMOR', 'Frio', '{user} comentou: "Pelo menos agora {victim} dorme em paz." A mesa não sabia se ria.'),
  ('HUMOR', NULL, '{user} disse que {victim} deixou um vazio na mesa e um travesseiro livre no quarto.'),
  ('HUMOR', 'Caótico', '{user} propôs um brinde a {victim} com água da jarra das velas. Ninguém aceitou.')
) AS v(tone, behavior, text)
LEFT JOIN behaviors b ON lower(b.name) = lower(v.behavior)
ON CONFLICT DO NOTHING;
