-- =====================================================================
-- Frases da TORRE DOS TRAIDORES.
-- {user} é traidor(a); {user1} é um(a) fiel na mira; {user2} é outro(a) traidor(a).
-- Frases com {user2} só aparecem quando há mais de um traidor.
-- =====================================================================

INSERT INTO phrases (phase, tone, behavior_id, text)
SELECT 'TRAITORS_MEETING'::phrase_phase, v.tone::phrase_tone, b.id, v.text
FROM (VALUES
  -- estratégia
  ('STRATEGY', 'Estrategista', '{user} abriu o mapa do castelo: "{user1} está chegando perto demais. É hoje."'),
  ('STRATEGY', 'Astuto', '"Se matarmos {user1}, vão desconfiar de quem brigou com ele(a) ontem", calculou {user}.'),
  ('STRATEGY', 'Manipulador', '{user} sugeriu deixar {user1} vivo(a): "A mesa redonda vai banir por nós."'),
  ('STRATEGY', 'Invejoso', '{user} sorriu: "Todo mundo ama {user1}. Por isso mesmo."'),
  ('STRATEGY', 'Frio', '{user} disse o nome de {user1} como quem escolhe o prato do jantar.'),
  ('STRATEGY', 'Detetive', '{user} avisou: "{user1} já me olhou torto três vezes. Ou ele(a) morre, ou eu saio."'),
  ('STRATEGY', 'Líder', '{user} bateu o martelo antes de ouvir os outros: "{user1}. Sem discussão."'),
  ('STRATEGY', 'Carismático', '{user} garantiu que amanhã convence a mesa inteira de que {user1} é o(a) culpado(a).'),
  ('STRATEGY', 'Competitivo', '{user} riscou o nome de {user1} na lista: "Ganha missão demais. Ameaça."'),
  ('STRATEGY', 'Vingativo', '{user} lembrou que {user1} votou nele(a) na última mesa: "Hoje ele(a) paga."'),
  ('STRATEGY', NULL, '{user} propôs matar {user1} para jogar a suspeita em cima de quem o(a) acusou.'),
  ('STRATEGY', 'Estrategista', '{user} avisou {user2}: "Se você continuar defendendo {user1} na mesa, vão desconfiar de você."'),
  ('STRATEGY', 'Manipulador', '"{user1} confia em mim cegamente. Isso vale mais vivo do que morto", disse {user}.'),
  ('STRATEGY', 'Astuto', '{user} sugeriu matar alguém aleatório para confundir o padrão. Mesmo assim, apontou {user1}.'),
  ('STRATEGY', 'Mentiroso', '{user} já tem pronta a história que vai contar no café sobre {user1}.'),
  ('STRATEGY', 'Sonso', '{user} disse, com a voz mais doce do mundo: "Eu acho que {user1} precisa ir, coitadinho(a)."'),
  ('STRATEGY', 'Estrategista', '{user} lembrou que {user1} provavelmente ganhou escudo: "Se for, a gente perde a noite. Arrisca?"'),
  ('STRATEGY', 'Detetive', '{user} percebeu que {user1} já montou uma lista de suspeitos. "E eu estou nela."'),
  ('STRATEGY', 'Líder', '{user} dividiu as tarefas de amanhã com {user2}: um acusa {user1}, o outro defende.'),
  ('STRATEGY', 'Frio', '{user} disse que não se apega a ninguém: "{user1} é só um nome no quadro."'),
  ('STRATEGY', 'Manipulador', '{user} propôs plantar a ideia de que {user1} é traidor(a) e deixar o castelo fazer o resto.'),
  ('STRATEGY', 'Traíra', '{user} já pensa em entregar {user2} se a mesa apertar. Não disse isso em voz alta.'),
  ('STRATEGY', 'Estrategista', '{user} calculou que matar {user1} deixa a aliança dele(a) sem líder.'),
  ('STRATEGY', NULL, '{user} sugeriu esperar mais uma noite antes de matar {user1}: "Ainda é útil."'),
  ('STRATEGY', 'Astuto', '{user} lembrou que {user1} é o(a) único(a) que ainda confia em {user2}. "Sem ele(a), você fica exposto(a)."'),
  ('STRATEGY', 'Carismático', '{user} disse a {user2}: "Eu seguro a mesa amanhã. Você só precisa chorar na hora certa."'),
  ('STRATEGY', 'Vingativo', '{user} disse que {user1} riu dele(a) no café. "Ninguém ri de mim duas vezes."'),
  ('STRATEGY', NULL, '{user} sugeriu recrutar em vez de matar. Depois olhou para {user1}: "Mas esse(a) não aceita."'),
  ('STRATEGY', 'Mentiroso', '{user} treinou em voz alta a frase que vai dizer amanhã: "Eu nunca desconfiei de {user1}."'),
  ('STRATEGY', 'Estrategista', '{user} desenhou um organograma das alianças do castelo. {user1} está no centro.'),
  ('STRATEGY', 'Competitivo', '{user} disse que matar {user1} é "tirar a maior peça do tabuleiro".'),
  ('STRATEGY', 'Manipulador', '{user} propôs espalhar amanhã que {user1} tinha escudo, para ninguém entender nada.'),
  ('STRATEGY', 'Frio', '{user} escreveu o nome de {user1} no pergaminho sem a mão tremer.'),
  ('STRATEGY', 'Líder', '{user} sugeriu que {user2} vote contra ele(a) amanhã para parecerem inimigos.'),
  ('STRATEGY', 'Sonso', '{user} lembrou que ninguém desconfia dele(a) porque "ele(a) parece um biscoito". Apontou {user1}.'),
  ('STRATEGY', NULL, '{user} disse que {user1} está perto demais de descobrir tudo e que "a curiosidade matou o gato".'),
  ('STRATEGY', 'Astuto', '{user} quer matar {user1} porque ele(a) é a única pessoa que ainda não o(a) acusou. "Ninguém vai entender."'),
  ('STRATEGY', 'Estrategista', '{user} insistiu: "Não matem quem desconfia de mim. Isso aponta pra mim." Olhou para {user1}.'),
  ('STRATEGY', 'Detetive', '{user} percebeu que {user1} anda fazendo perguntas certas demais.'),
  ('STRATEGY', 'Carismático', '{user} garantiu a {user2} que o castelo inteiro vai chorar por {user1} amanhã. E ninguém vai olhar para eles.'),
  ('STRATEGY', 'Mentiroso', '{user} já sabe quem vai acusar amanhã e não é {user1}: é quem mais vai sentir a falta dele(a).'),
  ('STRATEGY', NULL, '{user} disse que {user1} é "o(a) fiel mais perigoso(a) do castelo" e fechou o livro.'),
  ('STRATEGY', 'Frio', '{user} disse que a morte de {user1} vai ser "um favor para o ritmo do jogo".'),
  ('STRATEGY', 'Estrategista', '{user} sugeriu matar {user1} na noite em que o pote estiver cheio: "Todo mundo vai estar feliz demais para pensar."'),
  ('STRATEGY', 'Traíra', '{user} propôs matar {user1}, o próprio aliado. "Ninguém vai suspeitar que eu mataria meu melhor amigo(a)."'),
  ('STRATEGY', 'Manipulador', '{user} disse que vai consolar {user1} no café amanhã. Se {user1} ainda estiver vivo(a).'),
  ('STRATEGY', 'Líder', '{user} lembrou a {user2}: "Traidor que hesita vira banido. Escolhe: {user1} ou você."'),
  ('STRATEGY', 'Sonso', '{user} sugeriu {user1} "com todo o carinho do mundo".'),
  ('STRATEGY', NULL, '{user} lembrou que a mesa desconfia de {user1}: "Deixa vivo. Amanhã ele(a) cai sozinho(a)."'),
  ('STRATEGY', 'Astuto', '{user} quer matar quem defende {user1}, para {user1} ficar sozinho(a) na mesa.'),
  ('STRATEGY', 'Competitivo', '{user} disse que não aguenta mais perder missão para {user1}. "Resolvido."'),
  ('STRATEGY', 'Estrategista', '{user} sugeriu um ultimato a {user1}. "Ou vira traidor(a), ou vira lembrança."'),
  ('STRATEGY', 'Detetive', '{user} viu {user1} olhando para a torre ontem à noite. "Ele(a) sabe onde a gente se encontra."'),
  ('STRATEGY', 'Mentiroso', '{user} garantiu a {user2} que já tem um álibi para esta noite: "Eu estava chorando no quarto."'),
  ('STRATEGY', 'Carismático', '{user} disse que amanhã vai liderar a caça aos traidores. "Ninguém caça quem segura a tocha."'),
  ('STRATEGY', NULL, '{user} olhou pela janela da torre e apontou o quarto de {user1}: "A luz ainda está acesa."'),
  ('STRATEGY', 'Frio', '{user} disse que {user1} "até é legal", e em seguida votou pela morte dele(a).'),
  ('STRATEGY', 'Estrategista', '{user} sugeriu deixar a vítima de hoje parecer vingança pessoal. {user1} tinha brigado com meio castelo.'),
  ('STRATEGY', 'Vingativo', '{user} guarda o nome de {user1} desde o primeiro jantar, quando ele(a) riu da roupa dele(a).'),
  ('STRATEGY', 'Líder', '{user} traçou o plano da semana inteira, com {user1} como primeiro nome.'),
  ('STRATEGY', 'Manipulador', '{user} decidiu que {user1} vai ser a próxima vítima e que {user2} vai ser o próximo acusado, se precisar.'),
  ('STRATEGY', NULL, '{user} disse que matar {user1} é arriscado, mas não matar é pior.'),
  ('STRATEGY', 'Astuto', '{user} quer que {user1} viva mais um dia para a mesa acusá-lo(a) de ser traidor(a).'),
  ('STRATEGY', 'Sonso', '{user} admitiu que vai fingir choro amanhã por {user1}. "Eu choro bem, gente."'),
  ('STRATEGY', 'Estrategista', '{user} lembrou que, sem {user1}, a mesa perde a pessoa que mais organiza os votos.'),
  ('STRATEGY', 'Detetive', '{user} disse que {user1} está a um passo de descobrir {user2}. "Vai ser ele(a) ou você."'),
  ('STRATEGY', 'Competitivo', '{user} disse que o prêmio já está gasto na cabeça dele(a). "{user1} é o último obstáculo da semana."'),
  ('STRATEGY', 'Carismático', '{user} garantiu que ninguém vai desconfiar se amanhã ele(a) chorar mais do que todo mundo por {user1}.'),

  -- conflito
  ('CONFLICT', 'Explosivo', '{user} e {user2} discutiram por causa de {user1} e quase apagaram as velas da torre.'),
  ('CONFLICT', NULL, '"Você está ficando mole, {user2}", disse {user}, quando {user2} hesitou em escolher {user1}.'),
  ('CONFLICT', 'Paranoico', '{user} desconfia que {user2} vai traí-lo(a) na próxima mesa redonda.'),
  ('CONFLICT', 'Vingativo', '{user} lembrou a {user2} que foi voto vencido ontem: "Hoje é do meu jeito."'),
  ('CONFLICT', 'Arrogante', '{user} disse a {user2} que carrega a dupla nas costas. {user2} ficou calado(a), anotando.'),
  ('CONFLICT', 'Explosivo', '{user} derrubou o castiçal quando {user2} sugeriu poupar {user1}.'),
  ('CONFLICT', 'Traíra', '{user} perguntou a {user2}, meio brincando, quanto ele(a) vale na mesa redonda. Não era brincadeira.'),
  ('CONFLICT', 'Líder', '{user} cortou {user2} no meio da frase: "Quem decide aqui sou eu."'),
  ('CONFLICT', NULL, '{user} acusou {user2} de estar protegendo {user1} por amizade. "Traidor não tem amigo."'),
  ('CONFLICT', 'Invejoso', '{user} reclamou que {user2} recebe todos os elogios no castelo. "E quem faz o trabalho sujo sou eu."'),
  ('CONFLICT', 'Paranoico', '{user} perguntou a {user2} por que ele(a) chegou à torre três minutos atrasado(a).'),
  ('CONFLICT', 'Competitivo', '{user} disse que vai ganhar sozinho(a) se for preciso. {user2} ouviu muito bem.'),
  ('CONFLICT', 'Explosivo', '{user} e {user2} brigaram tão alto que alguém deve ter ouvido lá do salão.'),
  ('CONFLICT', 'Vingativo', '{user} não perdoou {user2} por não o(a) defender ontem. "Foi anotado."'),
  ('CONFLICT', NULL, '{user} disse a {user2}: "Se você cair, eu não vou cair junto." E falava sério.'),
  ('CONFLICT', 'Manipulador', '{user} semeou a dúvida: "E se {user2} estiver jogando para ganhar sozinho(a)?" Para ninguém, só para si.'),
  ('CONFLICT', 'Frio', '{user} disse a {user2} que, se precisar, vota nele(a) sem pensar duas vezes.'),
  ('CONFLICT', NULL, '{user} bateu na mesa da torre: "Eu não aguento mais {user1} me seguindo pelo castelo!"'),
  ('CONFLICT', 'Explosivo', '{user} disse que {user1} é insuportável e que morre hoje "nem que seja por paz de espírito".'),
  ('CONFLICT', 'Arrogante', '{user} disse que {user2} é "o elo fraco da traição" e que vai ser banido(a) logo.'),

  -- humor (ácido)
  ('HUMOR', 'Dramático', '{user} brincou: "Amanhã no café eu vou chorar mais que todo mundo."'),
  ('HUMOR', NULL, '{user} ensaiou a cara de surpresa para o café da manhã na frente de {user2}.'),
  ('HUMOR', 'Brincalhão', '{user} perguntou se a capa dos traidores vem com bolso. "Preciso guardar o lanche."'),
  ('HUMOR', 'Frio', '{user} disse que matar é fácil. Difícil é fingir que gosta do mingau.'),
  ('HUMOR', 'Caótico', '{user} sugeriu matar {user1} por causa do barulho que ele(a) faz ao mastigar.'),
  ('HUMOR', NULL, '{user} disse que a torre precisa de aquecedor: "Traidor também sente frio."'),
  ('HUMOR', 'Brincalhão', '{user} propôs votar na vítima com par ou ímpar. {user2} quase aceitou.'),
  ('HUMOR', 'Dramático', '{user} ensaiou o grito de "Não! Por quê?!" para amanhã. Ficou exagerado. Vai usar assim mesmo.'),
  ('HUMOR', NULL, '{user} comentou que a capa preta emagrece. {user2} concordou.'),
  ('HUMOR', 'Sonso', '{user} riu: "Se soubessem que sou eu, iam passar mal no croissant."'),
  ('HUMOR', 'Caótico', '{user} sugeriu assassinar o gaiteiro. Não pode. Ficou decepcionado(a).'),
  ('HUMOR', NULL, '{user} disse que vai dormir tranquilo(a): "Quem mata não tem medo de ser morto(a). Em tese."'),
  ('HUMOR', 'Frio', '{user} anotou o nome de {user1} e depois a lista de compras do castelo, no mesmo pergaminho.'),
  ('HUMOR', 'Brincalhão', '{user} imitou {user1} chorando no café. {user2} teve que tapar a boca para não rir.'),
  ('HUMOR', NULL, '{user} disse que ser traidor(a) é como ser síndico(a): todo mundo desconfia e ninguém agradece.'),
  ('HUMOR', 'Arrogante', '{user} disse que devia ganhar um troféu de melhor atuação. {user2} disse que é cedo.'),
  ('HUMOR', 'Dramático', '{user} entrou na torre como se fosse a noite de estreia de uma peça.'),
  ('HUMOR', NULL, '{user} sugeriu deixar um bilhete para {user1}: "Foi mal, nada pessoal." {user2} vetou.'),
  ('HUMOR', 'Caótico', '{user} quer escolher a vítima pela cor da meia. Hoje é quem estiver de meia verde. É {user1}.'),
  ('HUMOR', 'Frio', '{user} comentou que {user1} vai fazer falta no quiz da missão. Só no quiz.'),
  ('HUMOR', NULL, '{user} disse que a pior parte de ser traidor(a) é subir essa escada todo dia.'),
  ('HUMOR', 'Brincalhão', '{user} jurou que se for descoberto(a), vai sair da mesa fazendo reverência.'),
  ('HUMOR', 'Sonso', '{user} disse que amanhã vai abraçar {user1}... se {user1} ainda estiver lá para abraçar.'),
  ('HUMOR', NULL, '{user} pediu que a próxima vítima seja alguém que ronca. "Faço isso pela comunidade."'),
  ('HUMOR', 'Dramático', '{user} leu o nome de {user1} com voz de narrador de trailer.'),

  -- neutro
  ('NEUTRAL', 'Tímido', '{user} acendeu as velas e esperou os outros em silêncio.'),
  ('NEUTRAL', NULL, '{user} ajeitou o capuz e sentou à cabeceira da mesa da torre.'),
  ('NEUTRAL', 'Observador', '{user} contou o que ouviu no castelo hoje, palavra por palavra.'),
  ('NEUTRAL', NULL, '{user} disse a {user2} quem desconfia de quem, como um relatório.'),
  ('NEUTRAL', 'Frio', '{user} chegou, tirou o capuz e perguntou: "Quem é hoje?"'),
  ('NEUTRAL', NULL, '{user} passou os dedos pelo pergaminho com os nomes dos que ainda estão vivos.'),
  ('NEUTRAL', 'Estrategista', '{user} fez a contagem: quantos fiéis, quantos votos, quantas noites até a final.'),
  ('NEUTRAL', NULL, '{user} ficou olhando o fogo por um tempo antes de dizer qualquer coisa.'),

  -- emoção
  ('EMOTION', 'Fiel', '{user} confessou a {user2} que não aguenta mais mentir para {user1}.'),
  ('EMOTION', 'Chorão', '{user} chorou na torre. "Eu gosto de {user1}. Por que tinha que ser assim?"'),
  ('EMOTION', 'Carente', '{user} perguntou a {user2} se, no fim, eles ainda vão ser amigos.'),
  ('EMOTION', 'Protetor', '{user} pediu para poupar {user1} "só mais uma noite". Não foi atendido(a).'),
  ('EMOTION', NULL, '{user} disse que mentir para {user1} dói mais do que qualquer banimento.'),
  ('EMOTION', 'Heroico', '{user} disse que quer ganhar para a família, mas odeia a pessoa que está virando.'),
  ('EMOTION', 'Tímido', '{user} ficou quieto(a) a reunião inteira e só assentiu quando ouviu o nome de {user1}.'),
  ('EMOTION', 'Fiel', '{user} disse a {user2}: "Se você cair, eu caio junto. Juramos no primeiro dia."'),
  ('EMOTION', 'Chorão', '{user} teve que sair da torre por um minuto quando o nome de {user1} foi escolhido.'),
  ('EMOTION', NULL, '{user} olhou pela janela e disse que, em casa, ninguém acreditaria que ele(a) é capaz disso.')
) AS v(tone, behavior, text)
LEFT JOIN behaviors b ON lower(b.name) = lower(v.behavior)
ON CONFLICT DO NOTHING;
