-- =====================================================================
-- Mais frases para todos os momentos, com referências a momentos
-- icônicos do programa (sem nomes reais): o "fiel, traidor, não sei"
-- apontando para cada um, a "maior ovelha", o escudo escondido no bolso,
-- o "cem por cento fiel", o recado de despedida, o veneno na taça...
-- =====================================================================

INSERT INTO phrases (phase, tone, behavior_id, text)
SELECT v.phase::phrase_phase, v.tone::phrase_tone, b.id, v.text
FROM (VALUES
  -- ------------------------------------------------------------ chegada
  ('ARRIVAL', 'HUMOR', 'Dramático', '{user} deu a volta na mesa apontando para cada um: "Fiel. Traidor. Não sei. Fiel." Chegou em {user1} e travou.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} tentou fazer um brinde e derramou vinho na toalha histórica do castelo.'),
  ('ARRIVAL', 'HUMOR', 'Brincalhão', '{user} se apresentou com um nome falso "para treinar". {user1} caiu direitinho.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} perguntou se tinha como escolher o quarto mais longe da torre. Não tinha.'),
  ('ARRIVAL', 'HUMOR', 'Caótico', '{user} já declarou que desconfia de todo mundo que usa gola alta. Metade do elenco usa.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} chegou no barco errado e teve que ser resgatado(a) por um viking impaciente.'),
  ('ARRIVAL', 'HUMOR', 'Arrogante', '{user} disse que em três dias descobre todos os traidores. {user1} marcou no calendário.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} jurou que o retrato do corredor piscou para ele(a).'),
  ('ARRIVAL', 'HUMOR', 'Fofoqueiro', '{user} já sabia quem roncava antes da primeira noite. Ninguém sabe como.'),
  ('ARRIVAL', 'HUMOR', NULL, '{user} pediu o cardápio do castelo e perguntou se tinha opção "sem veneno".'),
  ('ARRIVAL', 'FRIENDLY', 'Diplomata', '{user} fez questão de conversar um pouco com cada pessoa do salão, inclusive com quem ninguém conversava.'),
  ('ARRIVAL', 'FRIENDLY', NULL, '{user} e {user1} ficaram amigos(as) discutindo qual é o melhor queijo do mundo.'),
  ('ARRIVAL', 'FRIENDLY', 'Brincalhão', '{user} apelidou {user1} de "Majestade". O apelido pegou no castelo inteiro.'),
  ('ARRIVAL', 'FRIENDLY', 'Heroico', '{user} tirou o próprio casaco para {user1}, que tinha esquecido o dele(a) no barco.'),
  ('ARRIVAL', 'FRIENDLY', 'Querido', '{user} descobriu o aniversário de {user1} e prometeu um bolo na torre... quer dizer, no salão.'),
  ('ARRIVAL', 'SUSPICION', 'Detetive', '{user} reparou que {user1} perguntou "quantos traidores costumam ser?" com interesse demais.'),
  ('ARRIVAL', 'SUSPICION', 'Paranoico', '{user} jurou que {user1} já se conhecia com alguém do elenco. Ninguém confirmou.'),
  ('ARRIVAL', 'SUSPICION', NULL, '{user} achou que {user1} ensaiou a própria apresentação. "Ninguém fala tão bem de improviso."'),
  ('ARRIVAL', 'SUSPICION', 'Observador', '{user} viu {user1} guardar um guardanapo no bolso. "Para anotar o quê?"'),
  ('ARRIVAL', 'SUSPICION', 'Astuto', '{user} disse que o traidor mais perigoso é o mais calmo. Olhou para {user1}, que estava calmíssimo(a).'),
  ('ARRIVAL', 'ALLIANCE', 'Protetor', '{user} adotou {user1} como "irmão(ã) de castelo" logo na chegada.'),
  ('ARRIVAL', 'ALLIANCE', 'Estrategista', '{user} ofereceu a {user1} troca de informações: "Tudo que eu ouvir, você ouve também."'),
  ('ARRIVAL', 'ALLIANCE', NULL, '{user} e {user1} prometeram nunca escrever o nome um do outro no quadro.'),
  ('ARRIVAL', 'CONFLICT', 'Arrogante', '{user} disse que {user1} "tem cara de primeiro(a) banido(a)". Clima péssimo instantâneo.'),
  ('ARRIVAL', 'CONFLICT', 'Competitivo', '{user} apostou com {user1} quem chega mais longe. O perdedor paga o jantar lá fora.'),
  ('ARRIVAL', 'CONFLICT', 'Invejoso', '{user} torceu o nariz quando {user1} ganhou o quarto com vista para o lago.'),
  ('ARRIVAL', 'CONFLICT', NULL, '{user} e {user1} discutiram política no primeiro jantar. Erro clássico.'),
  ('ARRIVAL', 'EMOTION', 'Carente', '{user} disse que é a primeira vez que dorme longe dos filhos. {user1} ficou com ele(a) até tarde.'),
  ('ARRIVAL', 'EMOTION', NULL, '{user} olhou para o castelo e disse que a mãe não vai acreditar quando ele(a) contar.'),
  ('ARRIVAL', 'NEUTRAL', NULL, '{user} ficou girando a taça sem beber, olhando cada rosto do salão.'),

  -- ------------------------------------------------------------ café da manhã
  ('BREAKFAST', 'HUMOR', 'Brincalhão', '{user} chegou ao café e anunciou: "Bom dia a todos os vivos."'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} disse que a pior parte de ser assassinado(a) deve ser perder o bacon.'),
  ('BREAKFAST', 'HUMOR', 'Chorão', '{user} entrou chorando "por antecipação": "Estou me preparando emocionalmente para a notícia do dia."'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} sugeriu escalar os quartos para dormir em dupla. {user1} perguntou quem dorme com o traidor.'),
  ('BREAKFAST', 'HUMOR', 'Frio', '{user} comentou que {victim} deixou um shampoo ótimo no banheiro. "Posso ficar?"'),
  ('BREAKFAST', 'HUMOR', 'Caótico', '{user} chegou vestido(a) de preto "para já estar pronto(a) para qualquer funeral".'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} disse que dormir no castelo é como jogar roleta russa com travesseiro.'),
  ('BREAKFAST', 'HUMOR', 'Fofoqueiro', '{user} já criou um ranking de "quem tem cara de ser o próximo". Colou na porta da cozinha.'),
  ('BREAKFAST', 'HUMOR', 'Dramático', '{user} desceu a escada em câmera lenta e desmaiou teatralmente na cadeira. Estava bem.'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} brincou que {victim} saiu do jogo sem pagar a aposta que perdeu ontem.'),
  ('BREAKFAST', 'HUMOR', 'Brincalhão', '{user} bateu uma colher no copo: "Discurso! Ninguém morreu? Ah, morreu. Discurso cancelado."'),
  ('BREAKFAST', 'HUMOR', 'Ovelha', '{user} foi chamado(a) de "maior ovelha do castelo" ontem e passou o café perguntando: "Mas eu sou fiel, né?"'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} disse que o chá está tão amargo que deve ter sido servido pelos traidores.'),
  ('BREAKFAST', 'HUMOR', 'Arrogante', '{user} disse que já sabia que {victim} ia morrer. Não tinha dito nada para ninguém.'),
  ('BREAKFAST', 'HUMOR', NULL, '{user} perguntou se o seguro cobre "morte por traição". O mordomo nem respondeu.'),
  ('BREAKFAST', 'EMOTION', 'Querido', '{user} fez um lugar de honra na mesa para {victim}, com flores do jardim.'),
  ('BREAKFAST', 'EMOTION', 'Heroico', '{user} prometeu ganhar a missão de hoje em homenagem a {victim}.'),
  ('BREAKFAST', 'EMOTION', NULL, '{user} disse que {victim} era a única pessoa com quem conseguia rir de verdade no castelo.'),
  ('BREAKFAST', 'EMOTION', 'Chorão', '{user} desabou abraçado(a) à cadeira de {victim}. {user1} teve que levantá-lo(a).'),
  ('BREAKFAST', 'EMOTION', 'Carente', '{user} disse que acordou e bateu na porta de todo mundo para ter certeza.'),
  ('BREAKFAST', 'EMOTION', NULL, '{user} contou que sonhou com {victim} dizendo "cuidado com quem sorri".'),
  ('BREAKFAST', 'EMOTION', 'Tímido', '{user} deixou um bilhete na porta de {victim}: "Obrigado(a) pela companhia."'),
  ('BREAKFAST', 'EMOTION', 'Fiel', '{user} prometeu à mesa que vai honrar {victim} votando com a cabeça, não com o coração.'),
  ('BREAKFAST', 'SUSPICION', 'Detetive', '{user} reparou que {user1} já sabia onde {victim} dormia. "Por quê?"'),
  ('BREAKFAST', 'SUSPICION', 'Paranoico', '{user} contou os sapatos na porta dos quartos: um par estava molhado. O de {user1}.'),
  ('BREAKFAST', 'SUSPICION', 'Astuto', '{user} lembrou que {victim} ia votar em {user1} hoje. "Agora não vai mais."'),
  ('BREAKFAST', 'SUSPICION', 'Observador', '{user} percebeu que {user1} não tocou na comida, mas também não pareceu triste.'),
  ('BREAKFAST', 'SUSPICION', NULL, '{user} perguntou a {user1} por que ele(a) desceu por último justo hoje.'),
  ('BREAKFAST', 'SUSPICION', 'Fofoqueiro', '{user} disse que {user1} andou "passeando pelo corredor" depois da meia-noite, segundo uma fonte confiável.'),
  ('BREAKFAST', 'SUSPICION', 'Detetive', '{user} lembrou que os traidores costumam matar quem está chegando perto. "Quem {victim} estava cercando?"'),
  ('BREAKFAST', 'SUSPICION', 'Paranoico', '{user} jurou ter ouvido uma porta ranger às duas da manhã. Olhou para {user1}.'),
  ('BREAKFAST', 'ACCUSATION', 'Explosivo', '{user} jogou o guardanapo na mesa: "Isso tem a assinatura de {user1}!"'),
  ('BREAKFAST', 'ACCUSATION', 'Vingativo', '{user} disse que {user1} vai pagar pela morte de {victim}, "nem que seja na mesa de hoje".'),
  ('BREAKFAST', 'ACCUSATION', 'Carismático', '{user} olhou para {user1} e perguntou, calmo(a): "Dormiu bem?" A mesa inteira entendeu.'),
  ('BREAKFAST', 'ACCUSATION', 'Detetive', '{user} expôs a teoria completa: {user1}, a torre, a ausência no corredor. Em cinco minutos.'),
  ('BREAKFAST', 'CONFLICT', 'Explosivo', '{user} e {user1} começaram brigando pelo lugar à mesa e terminaram brigando pela temporada inteira.'),
  ('BREAKFAST', 'CONFLICT', 'Invejoso', '{user} comentou que {user1} "é salvo(a) toda noite pelos escudos que ganha dos amigos".'),
  ('BREAKFAST', 'CONFLICT', NULL, '{user} disse que {user1} tem mais cara de traidor do que de fiel. {user1} devolveu na mesma moeda.'),
  ('BREAKFAST', 'CONFLICT', 'Arrogante', '{user} riu da teoria de {user1}: "Isso nem em novela."'),
  ('BREAKFAST', 'CONFLICT', 'Vingativo', '{user} ignorou {user1} a manhã inteira, de propósito, em frente a todos.'),
  ('BREAKFAST', 'FRIENDLY', 'Brincalhão', '{user} fez panquecas em formato de escudo para {user1}. "Proteção simbólica."'),
  ('BREAKFAST', 'FRIENDLY', 'Amado', '{user} entrou e o salão inteiro sorriu. {user1} até esqueceu da notícia por um minuto.'),
  ('BREAKFAST', 'FRIENDLY', 'Protetor', '{user} prometeu a {user1} ficar acordado(a) na porta do quarto dele(a) hoje à noite.'),
  ('BREAKFAST', 'FRIENDLY', NULL, '{user} e {user1} dividiram o jornal imaginário do castelo: "Manchete: ainda estamos vivos."'),
  ('BREAKFAST', 'DEFENSE', 'Fiel', '{user} defendeu {user1} antes que alguém acusasse: "Nem pensem nisso."'),
  ('BREAKFAST', 'DEFENSE', 'Diplomata', '{user} pediu que parassem de acusar {user1} "de estômago vazio".'),
  ('BREAKFAST', 'DEFENSE', NULL, '{user} lembrou que {user1} passou a noite no salão com metade do elenco.'),
  ('BREAKFAST', 'ALLIANCE', 'Fiel', '{user} deixou um sinal combinado no prato de {user1}: um croissant virado. O pacto segue.'),
  ('BREAKFAST', 'ALLIANCE', NULL, '{user} e {user1} saíram juntos para "tomar ar". Voltaram com o voto do dia decidido.'),
  ('BREAKFAST', 'NEUTRAL', NULL, '{user} contou quantos ainda estavam no jogo e fez uma cara difícil de ler.'),
  ('BREAKFAST', 'NEUTRAL', 'Observador', '{user} tomou o café na janela, de costas para a mesa, ouvindo tudo.'),
  ('BREAKFAST', 'NEUTRAL', 'Estrategista', '{user} fez a conta de quantas noites faltam até a final. Não gostou do resultado.'),
  ('BREAKFAST', 'EMOTION', 'Dramático', '{user} disse que se não morrer hoje, vai pedir o prêmio de melhor atriz/ator do castelo.'),
  ('BREAKFAST', 'EMOTION', NULL, '{user} disse que cada manhã no castelo envelhece um ano. "Hoje foram dois."'),
  ('BREAKFAST', 'HUMOR', 'Sonso', '{user} fez cara de surpresa ao saber de {victim}. Surpresa demais, segundo {user1}.'),

  -- ------------------------------------------------------------ missão
  ('MISSION', 'HUMOR', 'Brincalhão', '{user} tentou motivar o grupo com um grito de guerra viking. Saiu mais um espirro.'),
  ('MISSION', 'HUMOR', NULL, '{user} ficou tão concentrado(a) que colocou a peça certa no lugar errado com toda confiança.'),
  ('MISSION', 'HUMOR', 'Caótico', '{user} resolveu a missão "pelo caminho mais divertido". Foi o mais longo.'),
  ('MISSION', 'HUMOR', NULL, '{user} pediu um intervalo para ir ao banheiro no meio do pântano.'),
  ('MISSION', 'HUMOR', 'Dramático', '{user} caiu de joelhos na lama e gritou "por quê?" para o céu. Era só uma pedra.'),
  ('MISSION', 'HUMOR', NULL, '{user} disse que a missão foi desenhada por alguém que odeia joelhos.'),
  ('MISSION', 'HUMOR', 'Arrogante', '{user} disse que resolveria sozinho(a) em dois minutos. Levou vinte, com ajuda.'),
  ('MISSION', 'HUMOR', 'Chorão', '{user} chorou porque a água estava fria. Depois porque a água estava molhada.'),
  ('MISSION', 'HUMOR', NULL, '{user} jurou que o espantalho da missão tinha a cara de {user1}. {user1} não achou graça.'),
  ('MISSION', 'HUMOR', 'Brincalhão', '{user} escreveu "EU SOU FIEL" na lama com um galho. Ninguém se convenceu.'),
  ('MISSION', 'HUMOR', NULL, '{user} confundiu um pato com o pássaro da missão e passou dez minutos tentando conversar com ele.'),
  ('MISSION', 'HUMOR', 'Ovelha', '{user} perguntou a {user1} se devia pular. Pulou antes da resposta.'),
  ('MISSION', 'HUMOR', NULL, '{user} disse que depois dessa missão merece um escudo, um banho e uma terapia.'),
  ('MISSION', 'HUMOR', 'Frio', '{user} viu o grupo inteiro cair no lago e disse: "Previsível."'),
  ('MISSION', 'HUMOR', NULL, '{user} escondeu o escudo no bolso e disse que não ganhou. Esqueceu que as câmeras viram tudo.'),
  ('MISSION', 'HUMOR', 'Caótico', '{user} tentou ganhar tempo contando uma piada para o viking cronometrista.'),
  ('MISSION', 'HUMOR', NULL, '{user} disse que o balão dourado tinha "energia de traidor" e estourou de propósito.'),
  ('MISSION', 'HUMOR', 'Brincalhão', '{user} narrou o próprio fracasso como documentário da natureza.'),
  ('MISSION', 'HUMOR', NULL, '{user} ficou com lama até nas sobrancelhas e declarou: "É tratamento de pele."'),
  ('MISSION', 'HUMOR', 'Dramático', '{user} se despediu do grupo antes de entrar no túnel como se fosse para a guerra. Voltou em 3 minutos.'),
  ('MISSION', 'FRIENDLY', 'Querido', '{user} guardou o último gole de água para {user1}, que estava exausto(a).'),
  ('MISSION', 'FRIENDLY', 'Heroico', '{user} voltou para buscar {user1}, que tinha ficado para trás, mesmo custando tempo.'),
  ('MISSION', 'FRIENDLY', 'Protetor', '{user} ficou do lado de {user1} no ponto mais alto até ele(a) perder o medo.'),
  ('MISSION', 'FRIENDLY', NULL, '{user} deu os parabéns a {user1} mesmo tendo perdido o escudo para ele(a).'),
  ('MISSION', 'FRIENDLY', 'Diplomata', '{user} impediu uma briga entre {user1} e outra pessoa no meio da missão.'),
  ('MISSION', 'FRIENDLY', 'Amado', '{user} tropeçou e o grupo inteiro correu para ajudar. {user1} chegou primeiro.'),
  ('MISSION', 'FRIENDLY', 'Brincalhão', '{user} fez {user1} rir no meio do pântano, e o grupo ganhou fôlego.'),
  ('MISSION', 'FRIENDLY', NULL, '{user} e {user1} comemoraram o dinheiro dançando na lama.'),
  ('MISSION', 'CONFLICT', 'Competitivo', '{user} chamou {user1} de "peso morto" na frente de todos.'),
  ('MISSION', 'CONFLICT', 'Explosivo', '{user} arrancou o mapa da mão de {user1}: "Me dá isso, você está lendo ao contrário!"'),
  ('MISSION', 'CONFLICT', 'Invejoso', '{user} fingiu não ver quando {user1} pediu ajuda.'),
  ('MISSION', 'CONFLICT', 'Arrogante', '{user} disse que o grupo perdeu dinheiro "por culpa dos fracos". Olhou para {user1}.'),
  ('MISSION', 'CONFLICT', NULL, '{user} acusou {user1} de esconder o escudo que ganhou. {user1} jurou que não ganhou nada.'),
  ('MISSION', 'CONFLICT', 'Vingativo', '{user} lembrou a {user1} que ninguém o(a) ajudou na última missão. "Aqui se faz, aqui se paga."'),
  ('MISSION', 'CONFLICT', 'Rebelde', '{user} fez o contrário do que {user1} mandou. Deu certo. {user1} ficou furioso(a).'),
  ('MISSION', 'CONFLICT', 'Competitivo', '{user} disputou o escudo com {user1} como se fosse a final olímpica.'),
  ('MISSION', 'CONFLICT', 'Explosivo', '{user} gritou tanto com {user1} que até os pássaros voaram.'),
  ('MISSION', 'CONFLICT', NULL, '{user} e {user1} se culparam mutuamente pelo dinheiro perdido. O viking bocejou.'),
  ('MISSION', 'SUSPICION', 'Detetive', '{user} reparou que {user1} errou de propósito para não levar o escudo. "Traidor não precisa de escudo."'),
  ('MISSION', 'SUSPICION', 'Paranoico', '{user} acha que {user1} contou os segundos errado para prejudicar o grupo.'),
  ('MISSION', 'SUSPICION', 'Observador', '{user} viu {user1} cochichando com {user2} longe da missão.'),
  ('MISSION', 'SUSPICION', 'Astuto', '{user} deixou {user1} escolher o caminho para testar. O caminho estava errado.'),
  ('MISSION', 'SUSPICION', NULL, '{user} lembrou que {user1} nunca quer escudo. "Quem não tem medo da noite?"'),
  ('MISSION', 'SUSPICION', 'Fofoqueiro', '{user} espalhou que {user1} ganhou um escudo e está mentindo sobre isso.'),
  ('MISSION', 'SUSPICION', 'Detetive', '{user} reparou que {user1} sabia o caminho do túnel antes de receber o mapa.'),
  ('MISSION', 'SUSPICION', 'Paranoico', '{user} jurou que {user1} empurrou o barco para longe "sem querer".'),
  ('MISSION', 'SUSPICION', NULL, '{user} contou que {user1} ficou parado(a) na hora mais importante. "Parado(a) ou esperando?"'),
  ('MISSION', 'ALLIANCE', 'Fiel', '{user} passou a pista secreta só para {user1}.'),
  ('MISSION', 'ALLIANCE', 'Estrategista', '{user} combinou com {user1} quem ficaria com o escudo, se ganhassem. Não ganharam.'),
  ('MISSION', 'ALLIANCE', 'Protetor', '{user} indicou {user1} para a parte que valia escudo: "Ele(a) precisa mais do que eu."'),
  ('MISSION', 'ALLIANCE', NULL, '{user} e {user1} fizeram a missão lado a lado, sincronizados como dançarinos.'),
  ('MISSION', 'ALLIANCE', 'Líder', '{user} escalou {user1} como vice-capitão(ã) na frente de todos.'),
  ('MISSION', 'EMOTION', 'Heroico', '{user} disse que a missão foi pela família e dedicou o dinheiro a ela.'),
  ('MISSION', 'EMOTION', 'Chorão', '{user} chorou no pódio improvisado do escudo.'),
  ('MISSION', 'EMOTION', NULL, '{user} ficou em silêncio olhando o lago depois da missão. "Isso aqui é lindo demais para tanta mentira."'),
  ('MISSION', 'EMOTION', 'Carente', '{user} perguntou a {user1} se tinha ido bem. Perguntou de novo cinco minutos depois.'),
  ('MISSION', 'EMOTION', 'Dramático', '{user} disse que essa missão mudou a vida dele(a). Era a quarta missão que mudava a vida dele(a).'),
  ('MISSION', 'EMOTION', NULL, '{user} agradeceu ao grupo por não ter desistido dele(a) quando travou.'),
  ('MISSION', 'EMOTION', 'Tímido', '{user} acertou a resposta decisiva e ficou vermelho(a) com os aplausos.'),
  ('MISSION', 'NEUTRAL', NULL, '{user} lembrou ao grupo que cada erro custa dinheiro. O grupo errou mesmo assim.'),
  ('MISSION', 'NEUTRAL', 'Observador', '{user} passou a missão observando quem comemorava o dinheiro de verdade.'),
  ('MISSION', 'NEUTRAL', NULL, '{user} dividiu o grupo em funções com uma calma impressionante.'),
  ('MISSION', 'NEUTRAL', 'Frio', '{user} terminou a missão e foi embora sem comemorar nem lamentar.'),
  ('MISSION', 'NEUTRAL', 'Estrategista', '{user} sugeriu deixar o escudo para quem está mais ameaçado na mesa. Ninguém quis abrir mão.'),
  ('MISSION', 'NEUTRAL', NULL, '{user} e {user1} ficaram responsáveis pela parte chata. Fizeram sem reclamar.'),
  ('MISSION', 'HUMOR', 'Sonso', '{user} "não entendeu as regras" até o momento exato de vencer.'),
  ('MISSION', 'HUMOR', NULL, '{user} perdeu a peruca imaginária de dignidade no terceiro tombo.'),

  -- ------------------------------------------------------------ mesa redonda
  ('ROUND_TABLE', 'ACCUSATION', 'Detetive', '{user} apontou para cada um da mesa: "Fiel. Fiel. Não sei. Traidor." Parou em {user1}.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Paranoico', '{user} disse que {user1} parece "à prova de balas" e que ninguém é tão intocável sendo fiel.'),
  ('ROUND_TABLE', 'ACCUSATION', NULL, '{user} lembrou que {user1} disse ter escudo e depois disse que não tinha. "Qual das duas?"'),
  ('ROUND_TABLE', 'ACCUSATION', 'Carismático', '{user} perguntou à mesa: "Quem aqui nunca desconfiou de {user1}? Levanta a mão." Ninguém levantou.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Explosivo', '{user} disse que se {user1} não sair hoje, ele(a) sai amanhã por conta própria.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Estrategista', '{user} mostrou que {user1} sempre vota no último instante, depois de ver o voto dos outros.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Vingativo', '{user} olhou para {user1}: "Você me chamou de maior ovelha do castelo. Bééé. Voto em você."'),
  ('ROUND_TABLE', 'ACCUSATION', NULL, '{user} disse que {user1} jurou "cem por cento fiel" três vezes hoje. "Uma vez bastava."'),
  ('ROUND_TABLE', 'ACCUSATION', 'Líder', '{user} pediu que a mesa confiasse no instinto dele(a) só desta vez: {user1}.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Mentiroso', '{user} disse que ouviu {user1} falar da torre enquanto dormia.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Detetive', '{user} lembrou que {user1} foi a última pessoa a falar com todas as vítimas.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Rebelde', '{user} disse que a mesa está sendo guiada por {user1} como um rebanho e que isso é coisa de traidor.'),
  ('ROUND_TABLE', 'ACCUSATION', 'Frio', '{user} disse apenas: "{user1}." E cruzou os braços.'),
  ('ROUND_TABLE', 'SUSPICION', 'Observador', '{user} disse que {user1} relaxa sempre que o assunto é assassinato. "Por quê?"'),
  ('ROUND_TABLE', 'SUSPICION', NULL, '{user} lembrou que {user1} foi quem sugeriu o nome do último banido fiel.'),
  ('ROUND_TABLE', 'SUSPICION', 'Astuto', '{user} perguntou a {user1} em quem ele(a) votaria se não pudesse votar em ninguém da lista dele(a).'),
  ('ROUND_TABLE', 'SUSPICION', 'Detetive', '{user} reparou que {user1} fala "nós" quando se refere aos traidores. Ato falho?'),
  ('ROUND_TABLE', 'SUSPICION', 'Paranoico', '{user} disse que tem uma sensação ruim sobre {user1} desde o café.'),
  ('ROUND_TABLE', 'SUSPICION', 'Ingênuo', '{user} disse que gosta muito de {user1}, mas "gostar não é confiar, né?"'),
  ('ROUND_TABLE', 'DEFENSE', 'Protetor', '{user} contou que {user1} passou a noite cuidando dele(a) quando ficou doente. "Traidor não faz isso."'),
  ('ROUND_TABLE', 'DEFENSE', 'Carismático', '{user} fez a mesa rir e, no meio da risada, tirou {user1} da mira.'),
  ('ROUND_TABLE', 'DEFENSE', 'Fiel', '{user} escreveu o nome de {user1} num papel e rasgou: "Esse nome não vai para o quadro."'),
  ('ROUND_TABLE', 'DEFENSE', NULL, '{user} lembrou que {user1} recusou um escudo para o pote ficar cheio.'),
  ('ROUND_TABLE', 'DEFENSE', 'Diplomata', '{user} sugeriu que {user2} e {user1} conversassem antes de qualquer voto.'),
  ('ROUND_TABLE', 'DEFENSE', 'Detetive', '{user} provou que {user1} estava na missão no horário em que o suposto encontro teria acontecido.'),
  ('ROUND_TABLE', 'CONFLICT', 'Explosivo', '{user} disse a {user1}: "Você está jogando comigo desde o primeiro dia!"'),
  ('ROUND_TABLE', 'CONFLICT', 'Invejoso', '{user} disse que {user1} está sendo protegido(a) porque é "o(a) queridinho(a) do castelo".'),
  ('ROUND_TABLE', 'CONFLICT', NULL, '{user} e {user1} começaram a falar ao mesmo tempo e ninguém entendeu nada.'),
  ('ROUND_TABLE', 'CONFLICT', 'Traíra', '{user} trocou de lado no meio da discussão e deixou {user1} sozinho(a).'),
  ('ROUND_TABLE', 'EMOTION', 'Chorão', '{user} desabou: "Eu sou fiel! Cem por cento! Duzentos!" A mesa suspirou de novo.'),
  ('ROUND_TABLE', 'EMOTION', 'Carente', '{user} disse que a pior parte do jogo é ver amigos escrevendo o nome dele(a).'),
  ('ROUND_TABLE', 'EMOTION', NULL, '{user} pediu que, se fosse banido(a), alguém contasse à família que ele(a) jogou limpo.'),
  ('ROUND_TABLE', 'HUMOR', 'Brincalhão', '{user} escreveu o nome no quadro com um coração em volta. "Nada pessoal."'),
  ('ROUND_TABLE', 'HUMOR', NULL, '{user} disse que a mesa redonda é o único lugar do mundo onde "eu te amo" vem antes de "voto em você".'),
  ('ROUND_TABLE', 'HUMOR', 'Caótico', '{user} votou e piscou para a câmera. Ninguém entendeu para quem era a piscada.'),
  ('ROUND_TABLE', 'EMOTION', NULL, '{user} olhou para {victim} saindo e disse que o castelo acabou de ficar mais frio.'),

  -- ------------------------------------------------------------ torre
  ('TRAITORS_MEETING', 'STRATEGY', 'Estrategista', '{user} sugeriu um ultimato: "Se {user1} recusar, pelo menos ninguém desconfia de nós."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Manipulador', '{user} quer que {user1} viva para servir de bode expiatório na próxima mesa.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Astuto', '{user} sugeriu matar alguém sem escudo "para variar". {user1} nunca tem escudo.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Frio', '{user} disse que {user1} já viveu demais para quem desconfia tanto.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Líder', '{user} mandou {user2} votar com a maioria amanhã, custe o que custar.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Mentiroso', '{user} vai dizer amanhã que tem escudo, para parecer protegido(a) e fiel.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Carismático', '{user} garantiu que a mesa vai perdoar qualquer coisa se ele(a) chorar por {user1}.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Detetive', '{user} percebeu que {user1} começou a contar votos. "Quem conta votos descobre traidor."'),
  ('TRAITORS_MEETING', 'STRATEGY', NULL, '{user} disse que a morte de {user1} vai parecer vingança de quem ele(a) acusou ontem.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Estrategista', '{user} sugeriu envenenar a confiança antes de envenenar o chá: "Primeiro a gente isola {user1}."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Vingativo', '{user} quer {user1} fora porque ele(a) escreveu o nome dele(a) no quadro. "Olho por olho."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Sonso', '{user} sugeriu {user1} com voz de quem pede desculpas.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Manipulador', '{user} disse a {user2} que amanhã vai acusá-lo(a) de leve na mesa. "É teatro. Confia."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Competitivo', '{user} disse que {user1} está ganhando escudo demais e que "escudo não dura para sempre".'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Astuto', '{user} lembrou que matar o(a) mais popular gera luto, e luto gera distração. Apontou {user1}.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Traíra', '{user} sugeriu que, se a mesa apertar, os dois se acusem entre si. {user2} não gostou nada.'),
  ('TRAITORS_MEETING', 'STRATEGY', NULL, '{user} disse que {user1} já falou o nome dele(a) duas vezes na mesa. "Não vai ter terceira."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Estrategista', '{user} calculou: sem {user1}, a aliança dos fiéis perde a maioria.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Frio', '{user} dobrou o pergaminho com o nome de {user1} e apagou a vela.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Líder', '{user} lembrou que traidor unido não cai: "Escolhemos {user1}, juntos, e ninguém recua."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Mentiroso', '{user} inventou para {user2} que {user1} desconfia dele(a). Não desconfia. Mas agora vai morrer.'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Detetive', '{user} disse que {user1} lê pessoas bem demais. "É o(a) próximo(a) a ler a gente."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Carismático', '{user} disse que vai liderar o luto por {user1} amanhã. "Ninguém desconfia de quem organiza o velório."'),
  ('TRAITORS_MEETING', 'STRATEGY', NULL, '{user} disse que {user1} é leal demais para ser recrutado(a). "Então sobra a outra opção."'),
  ('TRAITORS_MEETING', 'STRATEGY', 'Astuto', '{user} sugeriu matar quem mais defende {user2} na mesa, para ninguém perceber a proteção.'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Explosivo', '{user} acusou {user2} de ter vazado informação da torre sem querer.'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Vingativo', '{user} disse a {user2}: "Você me deixou sozinho(a) na mesa ontem. Não esqueço."'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Arrogante', '{user} disse que {user2} só está vivo(a) porque ele(a) fez todo o trabalho.'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Paranoico', '{user} perguntou a {user2} se ele(a) já pensou em entregá-lo(a). Pela cara, já.'),
  ('TRAITORS_MEETING', 'CONFLICT', NULL, '{user} e {user2} não chegaram a um acordo sobre {user1} e ficaram meia hora em silêncio.'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Traíra', '{user} começou a desconfiar de {user2} e a guardar informações só para si.'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Competitivo', '{user} disse a {user2} que, no fim, só um dos dois vai ganhar. "Não vai ser você."'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Líder', '{user} tirou de {user2} a palavra final sobre {user1}: "Hoje eu decido."'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Explosivo', '{user} jogou o capuz no chão: "Se é para ter medo de {user1}, eu nem devia estar aqui!"'),
  ('TRAITORS_MEETING', 'CONFLICT', 'Frio', '{user} disse a {user2} que o prêmio não se divide com quem hesita.'),
  ('TRAITORS_MEETING', 'HUMOR', 'Brincalhão', '{user} chegou na torre fazendo "bu!". {user2} quase teve um infarto.'),
  ('TRAITORS_MEETING', 'HUMOR', NULL, '{user} disse que a torre precisa de um sofá: "Conspiração cansa."'),
  ('TRAITORS_MEETING', 'HUMOR', 'Caótico', '{user} sugeriu que a próxima vítima fosse escolhida pelo corvo do jardim.'),
  ('TRAITORS_MEETING', 'HUMOR', 'Frio', '{user} comentou que {user1} deve ter um travesseiro muito confortável. "Vai precisar."'),
  ('TRAITORS_MEETING', 'HUMOR', 'Dramático', '{user} leu o nome de {user1} e fez uma pausa de três minutos "pelo drama".'),
  ('TRAITORS_MEETING', 'HUMOR', NULL, '{user} brincou que o plano de aposentadoria dele(a) é o prêmio, e o plano de saúde é o escudo dos outros.'),
  ('TRAITORS_MEETING', 'HUMOR', 'Sonso', '{user} disse que amanhã vai perguntar, bem inocente: "Gente, quem morreu?"'),
  ('TRAITORS_MEETING', 'HUMOR', 'Brincalhão', '{user} propôs um aperto de mão secreto dos traidores. Ficou parecendo coreografia de festa junina.'),
  ('TRAITORS_MEETING', 'HUMOR', NULL, '{user} disse que o capuz esquenta demais e que traidor também merece ar-condicionado.'),
  ('TRAITORS_MEETING', 'HUMOR', 'Caótico', '{user} sugeriu matar {user1} e depois ir ao velório dele(a) de branco.'),
  ('TRAITORS_MEETING', 'EMOTION', 'Carente', '{user} admitiu que queria ser amado(a) pelo castelo e agora é o(a) monstro(a) da história.'),
  ('TRAITORS_MEETING', 'EMOTION', 'Fiel', '{user} disse que vai carregar a culpa por {user1} pelo resto da vida. Mesmo assim, votou.'),
  ('TRAITORS_MEETING', 'EMOTION', NULL, '{user} perguntou a {user2} se eles ainda vão conseguir olhar para a família depois disso.'),
  ('TRAITORS_MEETING', 'EMOTION', 'Chorão', '{user} escreveu o nome de {user1} com a mão tremendo e uma lágrima no pergaminho.'),
  ('TRAITORS_MEETING', 'EMOTION', 'Protetor', '{user} tentou salvar {user1} a noite inteira. Perdeu a discussão.'),
  ('TRAITORS_MEETING', 'NEUTRAL', NULL, '{user} repassou com {user2} o que cada um vai dizer no café.'),
  ('TRAITORS_MEETING', 'NEUTRAL', 'Observador', '{user} trouxe um relatório de quem cochichou com quem durante o dia.'),
  ('TRAITORS_MEETING', 'NEUTRAL', NULL, '{user} ficou em pé na janela da torre enquanto os outros decidiam.'),
  ('TRAITORS_MEETING', 'NEUTRAL', 'Estrategista', '{user} fez um mapa das próximas três noites com uma pena e muita frieza.'),
  ('TRAITORS_MEETING', 'NEUTRAL', NULL, '{user} disse que a torre é o único lugar do castelo onde ninguém mente. Ironicamente.'),

  -- ------------------------------------------------------------ mesa final
  ('ENDGAME', 'ACCUSATION', 'Detetive', '{user} apresentou uma linha do tempo completa da temporada. Toda ela apontava para {user1}.'),
  ('ENDGAME', 'ACCUSATION', 'Paranoico', '{user} disse que não encerra enquanto {user1} estiver sentado(a) nessa mesa.'),
  ('ENDGAME', 'ACCUSATION', 'Vingativo', '{user} lembrou a {user1} o dia em que foi acusado(a) por ele(a): "Hoje a mesa gira."'),
  ('ENDGAME', 'ACCUSATION', 'Carismático', '{user} pediu que todos olhassem nos olhos de {user1} antes de votar.'),
  ('ENDGAME', 'ACCUSATION', 'Explosivo', '{user} gritou: "{user1}, se você for fiel, eu peço desculpas ajoelhado(a)! Mas eu voto em você!"'),
  ('ENDGAME', 'ACCUSATION', 'Estrategista', '{user} disse que um traidor chegaria na final exatamente como {user1} chegou: sem arranhões.'),
  ('ENDGAME', 'ACCUSATION', NULL, '{user} disse que {user1} está "tranquilo(a) demais para quem pode perder tudo agora".'),
  ('ENDGAME', 'ACCUSATION', 'Líder', '{user} convocou a mesa: "Última chance de acertar. Eu voto em {user1}."'),
  ('ENDGAME', 'ACCUSATION', 'Mentiroso', '{user} garantiu ter visto {user1} saindo da torre na primeira semana. Nunca contou antes.'),
  ('ENDGAME', 'ACCUSATION', 'Competitivo', '{user} disse que {user1} perdeu todas as missões de propósito e agora quer o dinheiro.'),
  ('ENDGAME', 'ACCUSATION', 'Detetive', '{user} lembrou que os traidores nunca tentaram matar {user1}. "Nem uma vez."'),
  ('ENDGAME', 'ACCUSATION', 'Invejoso', '{user} disse que {user1} está sendo protegido(a) por ser simpático(a). "Simpatia não é prova de fidelidade."'),
  ('ENDGAME', 'ACCUSATION', 'Rebelde', '{user} disse que todo mundo quer encerrar, e justamente por isso ele(a) não quer.'),
  ('ENDGAME', 'ACCUSATION', 'Frio', '{user} disse, sem piscar: "{user1}, eu sei."'),
  ('ENDGAME', 'ACCUSATION', 'Caótico', '{user} votou para banir de novo "porque o jogo ainda não me deu adrenalina suficiente".'),
  ('ENDGAME', 'ACCUSATION', NULL, '{user} disse que vai votar em {user1} e depois pedir desculpas no avião.'),
  ('ENDGAME', 'ACCUSATION', 'Paranoico', '{user} disse que desconfia de {user1} desde o café do segundo dia, quando ele(a) não chorou.'),
  ('ENDGAME', 'ACCUSATION', 'Arrogante', '{user} disse que acertou todos os traidores até agora e que o último é {user1}. Não acertou nenhum.'),
  ('ENDGAME', 'DEFENSE', 'Fiel', '{user} disse que conhece {user1} melhor do que ninguém ali: "Ele(a) é fiel. Ponto."'),
  ('ENDGAME', 'DEFENSE', 'Protetor', '{user} ficou de pé ao lado da cadeira de {user1} durante toda a acusação.'),
  ('ENDGAME', 'DEFENSE', 'Carismático', '{user} lembrou cada vez que {user1} salvou o grupo, e a mesa ficou em silêncio.'),
  ('ENDGAME', 'DEFENSE', 'Heroico', '{user} disse que {user1} merece esse prêmio mais do que ele(a) mesmo(a).'),
  ('ENDGAME', 'DEFENSE', 'Diplomata', '{user} pediu que ninguém repetisse o erro das mesas passadas acusando {user1} sem prova.'),
  ('ENDGAME', 'DEFENSE', NULL, '{user} lembrou que {user1} foi quem descobriu um dos traidores lá atrás.'),
  ('ENDGAME', 'DEFENSE', 'Detetive', '{user} mostrou que o voto de {user1} sempre foi em quem saiu como traidor.'),
  ('ENDGAME', 'DEFENSE', 'Chorão', '{user} chorou pedindo que confiassem em {user1}: "Ele(a) segurou minha mão no pior dia."'),
  ('ENDGAME', 'DEFENSE', 'Líder', '{user} assumiu: "Se {user1} for traidor(a), a culpa é minha. Encerrem."'),
  ('ENDGAME', 'DEFENSE', 'Fiel', '{user} lembrou a {user2} que {user1} votou certo quando todos erraram.'),
  ('ENDGAME', 'DEFENSE', 'Manipulador', '{user} defendeu {user1} com fervor. Quanto mais defendia, menos olhavam para ele(a) mesmo(a).'),
  ('ENDGAME', 'DEFENSE', NULL, '{user} pediu que a mesa lembrasse de quem {user1} protegeu nas noites mais perigosas.'),
  ('ENDGAME', 'DEFENSE', 'Diplomata', '{user} pediu a {user2} que desse a {user1} o mesmo benefício da dúvida que recebeu na semana passada.'),
  ('ENDGAME', 'DEFENSE', 'Heroico', '{user} disse que abriria mão da parte dele(a) do prêmio se {user1} fosse traidor(a). Tamanha é a certeza.'),
  ('ENDGAME', 'EMOTION', 'Dramático', '{user} fez um discurso de dez minutos sobre amizade, traição e croissants.'),
  ('ENDGAME', 'EMOTION', 'Chorão', '{user} chorou tanto que precisou de um tempo antes de votar.'),
  ('ENDGAME', 'EMOTION', NULL, '{user} disse que, ganhe ou perca, nunca mais vai confiar tão fácil em ninguém.'),
  ('ENDGAME', 'EMOTION', 'Carente', '{user} pediu um abraço coletivo antes do último voto. Foi o abraço mais tenso da história.'),
  ('ENDGAME', 'EMOTION', 'Heroico', '{user} disse que ganhou algo mais importante que dinheiro: amigos para a vida. Olhou para {user1}.'),
  ('ENDGAME', 'EMOTION', 'Fiel', '{user} lembrou de cada aliado(a) que perdeu e disse o nome de todos em voz alta.'),
  ('ENDGAME', 'EMOTION', 'Tímido', '{user} disse que chegou até ali calado(a), e que agora finalmente vai falar: "Obrigado(a)."'),
  ('ENDGAME', 'EMOTION', NULL, '{user} disse que o castelo mudou quem ele(a) é. "Não sei se para melhor."'),
  ('ENDGAME', 'EMOTION', 'Frio', '{user} disse que não chora, mas pediu um minuto de silêncio por quem ficou pelo caminho.'),
  ('ENDGAME', 'EMOTION', 'Querido', '{user} agradeceu a {user1} por ter sido a primeira pessoa a sorrir para ele(a) no castelo.'),
  ('ENDGAME', 'EMOTION', NULL, '{user} contou que prometeu à avó chegar até ali. "Vó, eu cheguei."'),
  ('ENDGAME', 'EMOTION', 'Dramático', '{user} olhou para o céu pela janela e disse que o prêmio já não importa. Ainda importava.'),
  ('ENDGAME', 'EMOTION', 'Chorão', '{user} disse que vai sentir falta até do mingau.'),
  ('ENDGAME', 'EMOTION', NULL, '{user} lembrou do primeiro jantar, quando todos eram desconhecidos. "Agora são família. E suspeitos."'),
  ('ENDGAME', 'EMOTION', 'Carente', '{user} perguntou se todos vão manter contato depois. Ninguém respondeu rápido.'),
  ('ENDGAME', 'SUSPICION', 'Observador', '{user} disse que passou a temporada observando e que ainda não tem certeza sobre {user1}.'),
  ('ENDGAME', 'SUSPICION', 'Detetive', '{user} lembrou que {user1} falou em "nós" ao comentar uma morte. "Ato falho?"'),
  ('ENDGAME', 'SUSPICION', 'Paranoico', '{user} disse que a calma de {user1} é a coisa mais assustadora do castelo.'),
  ('ENDGAME', 'SUSPICION', NULL, '{user} perguntou a {user1} por que ele(a) nunca foi acusado(a). "Sorte ou estratégia?"'),
  ('ENDGAME', 'SUSPICION', 'Astuto', '{user} testou {user1}: "Se ainda tiver um traidor aqui, quem seria?" A resposta demorou.'),
  ('ENDGAME', 'SUSPICION', 'Estrategista', '{user} fez as contas dos votos de {user1}: nenhum voto em traidor revelado.'),
  ('ENDGAME', 'SUSPICION', 'Ingênuo', '{user} disse que confia em {user1}, mas que o coração está apertado.'),
  ('ENDGAME', 'SUSPICION', 'Observador', '{user} reparou que {user1} não olhou para ninguém quando falaram em encerrar.'),
  ('ENDGAME', 'SUSPICION', NULL, '{user} disse que tem uma última pergunta para {user1} e que a resposta decide o voto.'),
  ('ENDGAME', 'SUSPICION', 'Detetive', '{user} lembrou que {user1} estava por perto em todas as noites em que alguém morreu.'),
  ('ENDGAME', 'SUSPICION', 'Paranoico', '{user} disse que ainda escuta passos na escada da torre. "E alguém aqui sabe de quem são."'),
  ('ENDGAME', 'SUSPICION', 'Fofoqueiro', '{user} contou uma última fofoca sobre {user1} que ninguém tinha ouvido.'),
  ('ENDGAME', 'SUSPICION', 'Astuto', '{user} perguntou quem ia votar para encerrar antes de votar. {user1} respondeu rápido demais.'),
  ('ENDGAME', 'ALLIANCE', 'Fiel', '{user} disse que, se ele(a) e {user1} chegaram juntos, vão sair juntos, com ou sem dinheiro.'),
  ('ENDGAME', 'ALLIANCE', 'Protetor', '{user} prometeu a {user1} que o voto dele(a) não vai para ele(a), nunca.'),
  ('ENDGAME', 'ALLIANCE', 'Estrategista', '{user} e {user1} combinaram votar juntos até o último segundo.'),
  ('ENDGAME', 'ALLIANCE', NULL, '{user} e {user1} bateram as mãos na mesa ao mesmo tempo, como no primeiro dia.'),
  ('ENDGAME', 'ALLIANCE', 'Querido', '{user} disse a {user1}: "Se for para dividir com alguém, que seja com você."'),
  ('ENDGAME', 'ALLIANCE', 'Líder', '{user} lembrou que ele(a) e {user1} estão invictos na mesa. "Não vamos perder agora."'),
  ('ENDGAME', 'ALLIANCE', 'Heroico', '{user} disse que prefere sair do que votar em {user1}.'),
  ('ENDGAME', 'ALLIANCE', NULL, '{user} e {user1} trocaram um bilhete por baixo da mesa: "Confio."'),
  ('ENDGAME', 'CONFLICT', 'Explosivo', '{user} disse a {user1} que nunca vai perdoar o voto da semana passada.'),
  ('ENDGAME', 'CONFLICT', 'Invejoso', '{user} disse que {user1} é o(a) favorito(a) do público e que isso não é justo.'),
  ('ENDGAME', 'CONFLICT', 'Vingativo', '{user} cobrou de {user1} a traição do quinto dia com juros.'),
  ('ENDGAME', 'CONFLICT', 'Arrogante', '{user} disse que {user1} só está ali por sorte. {user1} disse que sorte é ter chegado sem ninguém gostar dele(a).'),
  ('ENDGAME', 'CONFLICT', 'Traíra', '{user} rompeu com {user1} bem na mesa final: "Cada um por si agora."'),
  ('ENDGAME', 'CONFLICT', NULL, '{user} e {user1} tiveram a discussão mais longa da temporada. Sem vencedor.'),
  ('ENDGAME', 'CONFLICT', 'Competitivo', '{user} disse que dividir o prêmio com {user1} seria a maior derrota da vida dele(a).'),
  ('ENDGAME', 'CONFLICT', 'Rebelde', '{user} disse que não vai votar como {user1} mandou, nem se for para encerrar.'),
  ('ENDGAME', 'CONFLICT', 'Explosivo', '{user} derrubou a vela ao se levantar contra {user1}. O apresentador nem piscou.'),
  ('ENDGAME', 'HUMOR', 'Brincalhão', '{user} disse que, se ganhar, vai comprar um castelo só para nunca mais entrar em um.'),
  ('ENDGAME', 'HUMOR', 'Caótico', '{user} sugeriu que todos confessassem ao mesmo tempo, "para economizar tempo".'),
  ('ENDGAME', 'HUMOR', NULL, '{user} disse que depois de tantas semanas de desconfiança, vai desconfiar até do próprio espelho.'),
  ('ENDGAME', 'HUMOR', 'Dramático', '{user} pediu que as velas fossem apagadas "para o momento ficar à altura".'),
  ('ENDGAME', 'HUMOR', 'Frio', '{user} disse que a única coisa em que ele(a) confia de verdade é no mingau: sempre ruim, nunca mente.'),
  ('ENDGAME', 'HUMOR', NULL, '{user} disse que vai dormir uma semana e depois processar o castelo por danos emocionais.'),
  ('ENDGAME', 'HUMOR', 'Brincalhão', '{user} propôs encerrar e ir todo mundo comer uma pizza. Ninguém votou contra a pizza.'),
  ('ENDGAME', 'HUMOR', 'Sonso', '{user} perguntou, bem baixinho: "E se eu disser que sou traidor(a), vocês acreditam?" Silêncio mortal.'),
  ('ENDGAME', 'HUMOR', 'Arrogante', '{user} disse que o prêmio devia vir com um troféu com o rosto dele(a).'),
  ('ENDGAME', 'HUMOR', NULL, '{user} lembrou que ninguém ali sabe a senha do Wi-Fi até hoje. "Isso sim é traição."'),
  ('ENDGAME', 'HUMOR', 'Caótico', '{user} votou e depois perguntou em quem tinha votado.'),
  ('ENDGAME', 'HUMOR', 'Brincalhão', '{user} disse que se tiver traidor ali, ele(a) merece o prêmio só pelo cansaço.')
) AS v(phase, tone, behavior, text)
LEFT JOIN behaviors b ON lower(b.name) = lower(v.behavior)
ON CONFLICT DO NOTHING;
